### ISSUE TITLE
User resolver types for all non scalar properties in ResolversTypes map

### ISSUE THREAD

**Issue by hbj** [dotansimha/graphql-code-generator#10091]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-resolvers

### Describe the bug

Is there a reason why we don't use the resolver types for all non scalar properties? cc @eddeee888 ([original comment](https://github.com/dotansimha/graphql-code-generator/issues/10004#issuecomment-2266643673))

### Your Example Website or App

https://codesandbox.io/p/devbox/codegen-resolver-types-example-4ndv2y

### Steps to Reproduce the Bug or Issue

For example for the following schema:

```gql
type A {
  a: String
}

type B {
  b: String
}

type C {
  a: A
  b: B
}
```

we get the following resolver types (with `defaultMapper: 'Partial<{T}>'`):

```ts
export type ResolversTypes = ResolversObject<{
  A: ResolverTypeWrapper<Partial<A>>;
  B: ResolverTypeWrapper<Partial<B>>;
  C: ResolverTypeWrapper<Partial<C>>;
}>;
```

### Expected behavior

Why not get this mapping instead?

```ts
export type ResolversTypes = ResolversObject<{
  A: ResolverTypeWrapper<Partial<A>>;
  B: ResolverTypeWrapper<Partial<B>>;
  C: ResolverTypeWrapper<Partial<Omit<C, 'a' | 'b'> & { a: ResolversTypes['A'], b: ResolversTypes['B'] }>>;
}>;
```

At the end when we're resolving a field of type `C` we will also be resolving `a` and `b`.

### Platform

- OS: n/a
- NodeJS: n/a
- `graphql` version: n/a
- `@graphql-codegen/typescript-resolvers` version: 4.2.1

### Codegen Config File

```ts
import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "schema.graphql",
  generates: {
    "types.ts": {
      plugins: ["typescript", "typescript-resolvers"],
      config: {
        defaultMapper: "Partial<{T}>",
      },
    },
  },
};

export default config;
```

**Comment by eddeee888** [comment]
Hi @hbj,

Could you let me know what problem would this solve?

**Comment by hbj** [comment]
Hey @eddeee888,

I updated the codesandbox example to show an issue I'm facing in a project. The issue should be visible in the `resolvers.ts` file but I think you have to clone it to see TS errors. Here is a screenshot:

<img width="1497" alt="Screenshot 2024-08-29 at 08 31 13" src="https://github.com/user-attachments/assets/a82ebbaf-d929-428e-8098-bce82cc6b031">

As you can see I have to return `D.c.b` with `a` because its type is set to `A` instead of `ResolversTypes['A']`. Eventually I should not do this and only rely on the `C.b` resolver, but do you think my scenario is legitimate and should be supported?

**Comment by hbj** [comment]
Hey @eddeee888 , actually I have a more concrete case (codesandbox updated). The error is also in `resolvers.ts`. In this example a mutation should return a result object containing a field of type `C`. We have resolvers for `C.a` and `C.b` and I should not need to return them in the mutation resolver.

Here is a screenshot:

![Screenshot 2024-08-30 at 20 14 58](https://github.com/user-attachments/assets/690949cb-04ce-4551-ad70-58f444ffc184)

Defining `C` as described in the issue's description would avoid the error.

**Comment by eddeee888** [comment]
Hi @hbj ,

For your case, I recommend using the [mappers](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers#mappers) option instead of `Partial<{T}>`. This allows you to declare what can be returned to a `type C` node. For example:

```ts
// resolvers.ts
export type CMapper = { str: string }

// codegen.ts
import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "schema.graphql",
  generates: {
    "types.ts": {
      plugins: ["typescript", "typescript-resolvers"],
      config: {
        mappers: {
          C: "./resolvers#CMapper",
        },
      },
    },
  },
};

export default config;
```

Then, the `parent` of each `C`'s resolver will become `CMapper` so you can use it to resolve `a` and `b`:

<img width="601" alt="Screenshot 2024-09-05 at 11 14 36 PM" src="https://github.com/user-attachments/assets/e739a5f5-58d2-4190-9356-bb3459123e42">

`typescript-resolvers` is built around `mappers` and treats it as the first-class citizen 🙂

**Comment by hbj** [comment]
OK I see, thanks!

But in general, wouldn't it be logical to use resolver types for all fields? At the end every field will be resolved.

Perhaps I'm missing something here but please feel free to close the ticket if you think this is not feasible or should not be done for any reason.

Thank you for your feedback 🙏

**Comment by eddeee888** [comment]
> But in general, wouldn't it be logical to use resolver types for all fields? At the end every field will be resolved.

Ah, I see what you mean 🙂 However, the complexity of server type requires us to add other types to support it as well.

FYI, we are recommending Server Preset as the new way to support writing server code now ([Guide](https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga-with-server-preset)). This approach has stricter type-safety, makes wiring up mapper simpler and takes care of folder structures, so you can focus on business logic.

I'll close this issue now, thanks for your questions 🙏
