### ISSUE TITLE
No `graphql` tag is provided without using client preset

### ISSUE THREAD

**Issue by gijsmin** [dotansimha/graphql-code-generator#10111]
### Describe the bug

I'm using URQL and tried to use  codegen with client preset and the following plugins: `['typescript', 'typescript-operations', 'typescript-urql']` this resulted in duplicates, then I tried to use without the client preset which did not gave me the duplicates but now I'm missing the `graphql(`query {}`)` tag. 

### Steps to Reproduce the Bug or Issue

```
		'graphql/generated.ts': {
			plugins: ['typescript', 'typescript-operations', 'typescript-urql'],
			config: {
				documentMode: 'string',
				inlineFragmentTypes: 'combine',
				dedupeFragments: true,
				withHooks: true,
			},
		},
```

### Expected behavior

That the following is also generated:

```
export function graphql(...)

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
```

**Comment by eddeee888** [comment]
Hi @gijsmin,

Client Preset generates the `graphql()` function, so if you remove the preset, not seeing `graphql` is expected. I believe you can either use Client Preset approach, or `typescript-urql` approach, but not both together.

`typescript-urql` generates a function that wraps Urql's `useQuery` function. 
However, with the Client Preset approach, you can pass the output of `graphql()` function directly to Urql's `useQuery` e.g.

```ts
import * as urql from 'urql'

const doc = graphql(`
query Me {
  me {
    id
  }
}
`)

const Component = () => {
  const result = urql.useQuery(doc)
}
```

**Comment by eddeee888** [comment]
Closing as this is the expected behaviour. Please let me know if I misunderstood the issue.
