### ISSUE TITLE
suggest: update the "@graphql-codegen/cli" dependency - 'micromatch'  to "micromatch": ">=4.0.8"

### ISSUE THREAD

**Issue by SpooRe91** [dotansimha/graphql-code-generator#10125]
### Describe the bug

The NPM package micromatch is vulnerable to Regular Expression Denial of Service (ReDoS). The vulnerability occurs in micromatch.braces() in index.js because the pattern .* will greedily match anything. By passing a malicious payload, the pattern matching will keep backtracking to the input while it doesn't find the closing bracket. As the input size increases, the consumption time will also increase until it causes the application to hang or slow down. There was a merged fix but further testing shows the issue persists. This issue should be mitigated by using a safe pattern that won't start backtracking the regular expression due to greedy matching.

### Your Example Website or App

a

### Steps to Reproduce the Bug or Issue

go to the @graphql-codegen/cli and check package.json file, the micromatch should be updated to it's latest version to avoid vulnerabilities

### Expected behavior

go to the @graphql-codegen/cli and check package.json file, the micromatch should be updated to it's latest version to avoid vulnerabilities

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.9.0]
- `@graphql-codegen/*` version(s): [5.0.2]

**Comment by eddeee888** [comment]
Hi @SpooRe91 ,

`micromatch` is not pinned in the latest version of `@graphql-codegen/cli` [here](https://github.com/dotansimha/graphql-code-generator/blob/1fb1c7a9e26197ec782939461dc54fdb1d4745bd/packages/graphql-codegen-cli/package.json#L71):

```json
"micromatch": "^4.0.5",
```

This means as the user, you can install the latest version of `micromatch` by using one of these options (not exhaustive list):

1. using [Yarn's resolutions (Yarn 1.x)](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) or the equivalent
2. remove all deps that use `micromatch` in your repo, then re-install them all to bump `micromatch` to the latest version

Apart from that, `@graphql-codegen/cli` is a `devDeps` that is run locally on your machine so normally security audits shouldn't be looking into dev packages of this nature 🙂

**Comment by eddeee888** [comment]
Closing this as affected package is not pinned, meaning consumers can freely choose the version that is not vulnerable.
