### ISSUE TITLE
[Security Vulnerability]: Bump dset from 3.1.3 to 3.1.4 due to a vulnerability

### ISSUE THREAD

**Issue by navv-christofer-flores** [dotansimha/graphql-code-generator#10145]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

Hi :wave:
First of all, thanks for all the hard work 👍
According to dependantbot:

> Versions of the package dset before 3.1.4 are vulnerable to Prototype Pollution via the dset function due improper user input sanitization. This vulnerability allows the attacker to inject malicious object property using the built-in Object property proto, which is recursively assigned to all the objects in the program.

Seems like I can patch this lib, but wonder if might worth to fix it on the cli itself maybe?

### Your Example Website or App

not-really

### Steps to Reproduce the Bug or Issue

1.- Run `npm install @graphql-codegen/cli@5.0.2`

You'll see the security vulnerability error message

### Expected behavior

Bump dset dependency so we don't get any errors

### Platform

- OS: macOS
- NodeJS: v20.10.0
- `@graphql-codegen/cli` version(s): 5.0.2

**Comment by eddeee888** [comment]
Hi @navv-christofer-flores ,

I can see `@graphql-codegen/cli@5.0.2` and its underlying deps (most noticably `@graphql-tools/utils`) do not explicitly pin `dset` to versions below 3.1.4. 

For example, its dep - `@graphql-tools/utils` at v10.3.2 - have `dset@^3.1.2` in its dependency which means any version from `3.1.2` to below `4.0.0` can be used according to [semver spec](https://semver.org/) - and the consumer can choose which ever version they want to.

Your package manager should follow the semver which means you can choose to (1) force resolution or (2) re-instsall all packages that brings in `dset` as dependency, so it can bring in newer version of dset, ideally the version with the security fix 🙂

**Comment by eddeee888** [comment]
Closing this as Codegen doesn't pin the mentioned package at the vulnerable version, thus, consumers can update the versions by themselves.
