### ISSUE TITLE
Type generation skips `type` declarations inside `.graphql` schema

### ISSUE THREAD

**Issue by KieranTH** [dotansimha/graphql-code-generator#10168]
### Which packages are impacted by your issue?

@graphql-codegen/cli, @graphql-codegen/typescript

### Describe the bug

When using the typescript plugin to attempt to generate types from a GraphQL Schema - it seems although the plugin ignores `type` declarations inside the schema.

```gql
type Test {
 name: String
}

input TestCreate {
name: String
}
```

Only the `Input` type would be generated in this example.

Here is the result:

```ts
/* eslint-disable */
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
};

export type TestCreate = {
  name: Scalars['String']['input'];
};

```

### Your Example Website or App

https://codesandbox.io/p/sandbox/nlpsfz

### Steps to Reproduce the Bug or Issue

1. Go to sandbox.
2. Download directory
3. run `npm i && npm run compile:codegen`
4. Check the `./src/__gen__` folder and see that only the `TestCreate` type is generated and not `Test` 

### Expected behavior

Seeing as the plugin is described as generating types for a SCHEMA - the Schema also included type declarations. These should be generated too.

### Platform

- OS: Linux
- NodeJS: 20.17.0
- `graphql` version:N/A
- `@graphql-codegen/*` version(s): 5.0.3
- `@graphl-codegen/typescript` version: 4.1.0

### Codegen Config File

```
const config = {
  schema: "./schema.graphql",

  generates: {
    "./src/__gen__/": {
      preset: "client",
      presetConfig: {
        gqlTagName: "gql",
        fragmentMasking: false,
      },
    },
  },
  ignoreNoDocuments: true,
};

export default config;
```

**Comment by gutnidev** [comment]
I encountered the same issue. 
When codegen generates types, it ignores the type declarations of specific entities.

I resolved the problem by downgrading the "@graphql-codegen/client-preset" package to version "4.3.3".

**Comment by KieranTH** [comment]
> I encountered the same issue. 
> 
> When codegen generates types, it ignores the type declarations of specific entities.
> 
> 
> 
> I resolved the problem by downgrading the "@graphql-codegen/client-preset" package to version "4.3.3".

Oh so this is a regression?! 

Thank you for that solution - I'll try that and see if it helps

**Comment by drzastwakamil** [comment]
Yeah looks like it's the new default behaviour in 4.4.0 version. It seems like that's connected to how [the client-preset is configuring the typescript plugin](https://github.com/dotansimha/graphql-code-generator/commit/8471a180cd61dc03dedace87876c5973b09b35f8#diff-ed39ff0c875833ec0c3683ef7180f00064b8e78694999501f2bb2871bbeca9f0R221) and only enabling enum and operation types 🤔

**Comment by drzastwakamil** [comment]
@KieranTH looks like there is already an open issue about this. Have a look -> the [open issue](https://github.com/dotansimha/graphql-code-generator/issues/10167)
