### ISSUE TITLE
.gql fragments template

### ISSUE THREAD

**Issue by awdyson** [dotansimha/graphql-code-generator#1045]
I'm interested in auto-generating the fragments available. The template below does a halfway decent job for my schema  -- which is long enough that it'd have been a pain to write manually.

Would there be interest in adding this plugin? If not, feel free to close this.

Anyone interested writing some failing tests for me to make pass? I don't trust my understanding of GraphQL or this utility enough to assume I won't need plenty of hand-holding.

```
{{#each types}}
fragment {{ name }} on {{ name }} {
  {{#each fields}}
  {{#ifCond isType '||' isUnion}}
  {{ name}} {
    ...{{ type }}
  }
  {{else}}
  {{ name }}
  {{/ifCond}}
  {{/each}}
}

{{/each}}

{{#each unions}}
fragment {{ name }} on {{ name }} {
  {{#each possibleTypes}}
  ... on {{ this }} {
    ...{{ this }}
  }
  {{/each}}
}

{{/each}}
```

**Comment by dotansimha** [comment]
That's interesting!
So you are basically generating a stub fragment for all the available types, and then you modify it according to your needs? like some kind of scaffolding? 
I think we are open to any kind of plugins that has a use case :)

**Comment by stvnwrgs** [comment]
Im wondering why you need to define documents in general. When i look into https://graphql-code-generator.com/#live-demo there is no additional information in the documents. It's just a different syntax.

I would like to generate typescript-react-apollo components directly out of the schema without duplicating my code. Is there any solution for this or is another plugin like this one here the only way? 

Or is there a good reason why you want to have separated documents that im missing?
