### ISSUE TITLE
Generated props by typescript-react-apollo are not working

### ISSUE THREAD

**Issue by dusan-dragon** [dotansimha/graphql-code-generator#1053]
**Describe the bug**
If you include props from generated typescript types as `class MyComponent extends Component<MyQuery.Props<{}> { ... }` then the types are not applied and everything is of type `any`

Instead you have to do:
`export interface Props extends DataProps<MyQuery.Query, MyQuery.Variables> {}`
and then:
`class MyComponent extends Component<Props<{}> { ... }`

**To Reproduce**
in https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript-react-apollo/example/src/components/TestWithHOC/TestWithHOC.view.tsx#L5 use instead AllPostsProps an try if the loading, error is typed properly

**Expected behavior**
All props should be typed properly (loading, error and others)

**Schema/Documents**
If possible and relevant, please provide your GraphQL schema and GraphQL documents.

**Environment:**
 - OS: Ubuntu 18.04.1 LTS
 - Codegen: 0.15.0
 - Node: 10.9.0

**Comment by dotansimha** [comment]
Fix available in 1.0.0 👍
