### ISSUE TITLE
[TypeScript Resolvers] The default name for interfaces should not contains "I" prefix 

### ISSUE THREAD

**Issue by steida** [dotansimha/graphql-code-generator#1089]
I suppose naming generation should be consistent. These tree interfaces are prefixed with `I`.

`ISubscriptionResolverObject`
`IResolvers`
`IDirectiveResolvers`

I think they should be:

`SubscriptionResolverObject`
`Resolvers`
`DirectiveResolvers`

**Comment by dotansimha** [comment]
Fixed in the recent refactor. we'll release it soon.

**Comment by dotansimha** [comment]
Fix available in 1.0.0 👍

**Comment by lednhatkhanh** [comment]
@dotansimha I still got `IResolvers` and `IDirectiveResolvers` in the generated file in `@graphql-codegen/typescript@1.0.0`, also empty type with Generic will make tsc failed to compile when `strict:true`:

![image](https://user-images.githubusercontent.com/9303093/70884883-cb8c8580-2009-11ea-95ae-ce7963412252.png)

**Comment by dotansimha** [comment]
@lednhatkhanh please use the latest version of the codegen.

**Comment by lednhatkhanh** [comment]
I'm using version: 1.9.1 of the CLI:

```
"@graphql-codegen/cli": "^1.9.1"
```

**Comment by lednhatkhanh** [comment]
Oh, so the CLI installs the old version of plugins, upgraded them to latest version fixes the problem, thank you, maybe someone should make a PR to upgrade the cli to install latest available version of plugins.

**Comment by dotansimha** [comment]
@lednhatkhanh 1.9.1 is the correct latest version, all plugins should use the same. How did you get the dependencies? using `init` command?

**Comment by lednhatkhanh** [comment]
@dotansimha Yes I used the `init` command and it installed version 1.0 of the plugins

**Comment by dotansimha** [comment]
I see, thanks @lednhatkhanh , we'll take a look :)
