### ISSUE TITLE
[TypeScript Resolvers] Resolvers returned data type cannot be introspected

### ISSUE THREAD

**Issue by swcarlosrj** [dotansimha/graphql-code-generator#1103]
**Describe the bug**
Cannot introspect resolvers returned data

**To Reproduce**

Clone repository:
`git clone -b graphql-ts https://github.com/swcarlosrj/SpaceX-API.git`
Install deps & start server:
`yarn && yarn start`
Generate types:
`yarn generate`
Introspect _src/schema/capsule/resolvers.ts_ resolvers returned data

**Expected behavior**
[This](https://twitter.com/swcarlosrj/status/1080137536507465729) would be the desired behaviour, it's not even real because I've hardcoded
**QueryResolvers.CapsulesResolver**
from
`CapsulesResolver<...> = (Resolver<R, Parent, Context, CapsulesArgs>`
to
`CapsulesResolver<...> = Promise<Capsule[]>`

I believe that it's a TypeScript thing but it'd be incredible if we could have that feature using **QueryResolvers.Resolvers** as [here](https://twitter.com/swcarlosrj/status/1080137519499481088), does it's even possible?

**Environment:**
OS: macOS Mojave 10.14.2 (18C54)
Codegen: 0.15.2
Node: 10.10.0

**Additional context**
It looks like that when you check the returned data type, it's well formed (in this case Capsule[]) but I cannot see in VSCode the fields of my type/interface as [here](https://twitter.com/swcarlosrj/status/1080137536507465729)

**Comment by kamilkisiela** [comment]
So what you want to have is a Return Type of a resolver?

Turning that:

```ts
namespace QueryResolvers {
  export type CapsuleResolver = Resolver<R,...>;
}
```

into:

```ts
namespace QueryResolvers {
  export type CapsuleResolver = Resolver<R,...>;

  export type CapsuleResult = Capsule;
}
```

Right?

**Comment by swcarlosrj** [comment]
@kamilkisiela yep although not sure about how it'd should be the written in order to have the ability to introspect the resolver's returned data only using the **QueryResolvers.Resolvers**. That'd be the ideal case IMO but It could be added manually too!

Resuming, doing [this](https://twitter.com/swcarlosrj/status/1080137519499481088), be able to do [this](https://twitter.com/swcarlosrj/status/1080137536507465729) (withouth adding QueryResolvers.CapsulesResolver)

**Comment by kamilkisiela** [comment]
> introspect the resolver's returned data only using the QueryResolvers.Resolvers
What do you mean by that, to return data of some shape in the resolver use that shape in a child resolver? Treat TypeScript as the source of truth and not the GraphQL Schema?

**Comment by kamilkisiela** [comment]
@swcarlosrj 
`QueryResolvers.CapsuleResolvers` is a type that represents a resolver and since resolver is a function, the type defines that function. What you want to have is a type that represents the shape of a returned value, which is a different story, in where you loose signatures of arguments, a root value and a context. I don't know why it could be useful.

**Comment by swcarlosrj** [comment]
👍, I though that it was possible to return the shape of a returned value without losing the signatures of arguments, a root value and a context.

The interesting point here is returning the shape of a returned value (in this case, Capsule), TypeScript could check if whatever you're returning matches the shape, which I've just checked it and it's doing it but it doesn't appear in VSCode as [here](https://twitter.com/swcarlosrj/status/1080137536507465729)

You can close this issue or tag it as a proposal feature, doesn't make sense put more time on it. Thanks anyways 😄

**Comment by kamilkisiela** [comment]
@swcarlosrj this is how TypeScript works.

When you do this:

```ts
type Foo = string;

const query = {
  foo(): Foo /* <-- */ {
  	return 'Foo';
  }
}
```

TypeScript treats that as a shape of a returned value, not as function's signature. 

To have typed arguments and others, you would have to define that signature, otherwise it's `any`.

**Comment by swcarlosrj** [comment]
That's what I've supposed it. Ah, I'll try that out, having no idea about TS (goal for 2019 😬)

**Comment by kamilkisiela** [comment]
@swcarlosrj can we close the issue now or there's something still missing?

**Comment by swcarlosrj** [comment]
Sure, you can close it!
