### ISSUE TITLE
[TypeScript Resolvers] Trivial resolvers aren't generated as expected

### ISSUE THREAD

**Issue by swcarlosrj** [dotansimha/graphql-code-generator#1106]
**Describe the bug**
Resolvers based on types (not by Query) aren't generated as expected.

**To Reproduce**

Clone repository:
`git clone -b graphql https://github.com/swcarlosrj/SpaceX-API.git`
Install deps & start server:
`yarn && yarn start`
Generate types:
`yarn generate`
Add _CapsuleResolvers.Resolvers_ type to _src/schema/dragon/resolvers/Capsule.ts_ resolver

**Expected behavior**
Add the generated resolver type that match with the desired types.  

**Environment:**
OS: macOS Mojave 10.14.2 (18C54)
Codegen: 0.15.2
Node: 10.10.0

**Additional context**
When resolving a field coming from a specific Type, the respective _TypeParent_ generated type doesn't match with the returned data type. As far as I can see, I think that it's just a problem with the `TypeParent` coming from `getParentType` function.

**Comment by kamilkisiela** [comment]
@swcarlosrj There's no `graphql-ts` branch anymore, could you share the code?

**Comment by swcarlosrj** [comment]
@kamilkisiela try with `graphql` branch

**Comment by kamilkisiela** [comment]
But that's the expected behavior. We can't tell how you want to resolve `Capsule` type, that's why in order to overwrite the default behavior, you can use [Mappers feature](https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers-overwrite-parents-and-resolved-values).

**Comment by swcarlosrj** [comment]
Great, I didn't know about the Mappers, I'll give a try! Thanks 😄
