### ISSUE TITLE
Idea: Show deprecated fields when generating code

### ISSUE THREAD

**Issue by FredyC** [dotansimha/graphql-code-generator#1107]
**Is your feature request related to a problem? Please describe.**
It might be out of the scope of this package. 
We recently started using deprecated fields, but we did not find any tool that would show this client side. It makes sense to see deprecated fields in relation to what's actually used in queries/mutations.

**Describe the solution you'd like**
There is a handy function [`findDeprecatedUsages`](https://github.com/graphql/graphql-js/blob/master/src/utilities/findDeprecatedUsages.js#L22) in `graphql` package which expects schema and a document. It would be great if I could see it as a part of generation output, possibly hidden behind some flag.

**Describe alternatives you've considered**
Probably some standalone tool which means that it will have to read & parse each document again to do this.

**Comment by dotansimha** [comment]
Sounds like a great idea @FredyC ! 
I think we can use https://github.com/kamilkisiela/graphql-inspector to perform these checks. @kamilkisiela ?

**Comment by FredyC** [comment]
Interesting tool, not sure what are exact differences with `graphql` package which also has `findBreakingChanges` and `findDangerousChanges`. However, it works by comparing two schemas, not schema and doc. I think I would rather see deprecated fields I am actually using and where I am using them instead of a full list of what got deprecated.

**Comment by kamilkisiela** [comment]
@FredyC 

https://github.com/kamilkisiela/graphql-inspector/pull/28

You run `$ graphql-inspector validate schema.json src/**/*.graphql` and you get a list of errors per each document and list of fields that have been deprecated and are used.

Why I didn't use `findBreakingChanges` and `findDangerousChanges`? Because it's not that hard to implement it myself and I get more control over the result and messages. I also need to track changes that are not affecting API consumers.

**Comment by FredyC** [comment]
@kamilkisiela That looks promising. Thanks, will give it a try 👍

**Comment by FredyC** [comment]
@kamilkisiela That was tricky. I used the command in a form you mentioned here and it was screaming `Couldn't handle src/**/*.graphql`. It took me some time to figure out that it's an opposite order, schema goes as a second 😈 

Anyway, it's not really working, either way. There is something wrong with my introspection file. This is probably the wrong spot for trying to solve this, just in case if you have seen this before, some hint would be great.

```
Introspection result missing directive locations: { name:
"include", description: "Directs the executor to include this field or fragment only when the `if` argument is true.", args: [{
name: "if", description: "Included when true.", type: { kind: "NON_NULL", name: null, ofType: { kind: "SCALAR", name: "Boolean", ofType: null } }, defaultValue: null }] }
```

**Comment by FredyC** [comment]
Nevermind, found it, some shenanigans in our custom tooling code.

Either way, I think it would be lovely to integrate this part of the inspector into the generator as I originally said. If anything, it would save some processing time and it kinda makes sense to me to get warned about deprecations right away when I am writing queries, not later when I am done coding :)

**Comment by dotansimha** [comment]
@FredyC closing for now. You can use `graphql-inspector`, and I think it can provide better experience by integrating it with GitHub Actions.

**Comment by FredyC** [comment]
@dotansimha That's cool, but we don't use GitHub for production apps. Although we might switch given it's getting better and better with Microsoft intervention and there are private repos for free also.

**Comment by dotansimha** [comment]
@FredyC what do you use? maybe @kamilkisiela can help with that

**Comment by kamilkisiela** [comment]
@FredyC I could support Bitbucket but I would need some help

**Comment by FredyC** [comment]
Yea, we do use BitBucket, but don't worry about it now. Currently, I am just running inspector check after schema update, it's sufficient for now.

**Comment by dotansimha** [comment]
@FredyC don't worry, @kamilkisiela already planned to support BitBucket: https://github.com/kamilkisiela/graphql-inspector/issues/54 ;)
