### ISSUE TITLE
How would you handle two different configurations through single `codegen.yaml` file 

### ISSUE THREAD

**Issue by kuncevic** [dotansimha/graphql-code-generator#1111]
In my project I have two scripts
```
"introspect": "gql-gen --schema http://localhost:8080/graphql --template graphql-codegen-introspection-template --out src/app/graphql/schema.json",
"generate": "gql-gen --schema src/app/graphql/schema.json --template graphql-codegen-apollo-angular-template --out src/app/graphql/index.ts src/app/graphql/*.graphql",
```
With a new breaking change now we have to use `codegen.yaml` to specify the options https://github.com/dotansimha/graphql-code-generator/releases/tag/v0.14.0.  

It is not clear how would you handle multiple configuration through single a `codegen.yml` file ? 
Should you just create `.yml` file for each configuration ? - if so I would like to request a feature to be able to  handle each configuration through single `codegen.yml` file.

**Comment by dotansimha** [comment]
Hi @kuncevic ! 

In your case, it seems like you have multiple commands, and they they depend on each other (I guess that one is for downloading the schema as JSON and saving it as static file).
So you should create two `.yml` files, and specify each one with `--config` flag.

If they don't have a dependency to each other, in the new `.yml` config, you can specify multiple records under `generates` field, and specify multiple outputs.

**Comment by kuncevic** [comment]
@dotansimha so you are saying I can have one single `.yml` file for each script in case if scripts does not depends on each other?

**Comment by dotansimha** [comment]
Closing for now, @kuncevic , feel free to re-open if it's still relevant.
