### ISSUE TITLE
Usage in development workflow

### ISSUE THREAD

**Issue by meatherly** [dotansimha/graphql-code-generator#1135]
Hello,
I was wondering if you guys have any suggestions on development workflow when using this tool? Some suggestions given here might be something that could be added to the docs.

For instance what are some of the example ways people could use this tool with their development:
- Do you run this tool one off command while developing a project? 
- Could you combine it with your already existing tool like webpack  #739 , task runner( e.g. grunt, gulp), [custom scripts](https://graphql-code-generator.com/docs/getting-started/#using-in-runtime), combine with npm command, or run 2 terminal sessions?
- Should you ignore the generated files?

All these questions above is more or less pointing to my over arching question:  If you're actively working on a project using this tool how do you use it?

Last question is their a community page/chat for questions besides github issues?

**Comment by xanf** [comment]
I'm just putting it in watch mode while I'm developing through npm script. It sits in other terminal window :)

**Comment by meatherly** [comment]
apollo codegen decieded to wait on this [feature](https://github.com/Microsoft/TypeScript/issues/3136) of typescript instead trying to implement a webpack plugin https://github.com/apollographql/apollo-tooling/issues/360. Looks very promising.

**Comment by dotansimha** [comment]
We hope to bring back the Webpack plugin in the future, but that's not possible at the moment. 
As @xanf said, you can start the watch mode in a different terminal session.

Leaving open, because we need to document the usage in the website.

**Comment by ardatan** [comment]
Or you can use concurrently to run two different watchers at the same time.

**Comment by dotansimha** [comment]
Documented in: https://github.com/dotansimha/graphql-code-generator/commit/6cf5bfb299a534fef3db7e0b5726eda3dbd88639
