### ISSUE TITLE
[TypeScript Server] Make it as part of `typescript-resolvers` and `typescript-client`

### ISSUE THREAD

**Issue by kamilkisiela** [dotansimha/graphql-code-generator#1140]
I find it a bit misleading to use `typescript-server` on the client, we might want to name it differently or to even merge `typescript-server` with `typescript-resolvers` and add `typescript-server` to `typescript-client`.

I think it makes sense and solves that problem: https://github.com/dotansimha/graphql-code-generator/issues/1041#issuecomment-447783675

**Comment by ardatan** [comment]
In some cases, `typescript-server` might not be needed if user decides to use own types by using `import` with `add` plugin. Maybe, we can call it in different name like `typescript-schema-types` or something else.

**Comment by dotansimha** [comment]
Maybe it should be just `typescript` and we can support mappers also in this package, and then mappers will also effect the original type definitions.
