### ISSUE TITLE
[TypeScript Server] Generic support for Relay model?

### ISSUE THREAD

**Issue by vreality64** [dotansimha/graphql-code-generator#1141]
Hello. I think GraphQL types written based on facebook's [Relay model](https://facebook.github.io/relay/graphql/connections.htm) have less extensibility. It's not comfortable to change Node's Type. I think It can be easy with generic support. Below code will show what I want to do 😃 

***written types - User and connection***
```graphql
type User {
  id: ID!
  followers: UserConnnection!
}

type UserConnection {
  edges: [UserEdge!]!
  pageInfo: UserPageInfo!
}

type UserEdge {
  node: User!
  cursor: ID!
}

type Query {
  user(id: ID!): User
}
```

***generated resolver types***
- There are no easy way that can change only `Node` type
```ts
export interface UserConnection {
  edges: UserEdge[];
  pageInfo: UserPageInfo;
}
export interface UserEdge {
  node: User;
  cursor: string;
}

export type UsersConnectionResolver<R = UserConnection, Parent = {}, Context = {}> = Resolver<R, Parent, Context, UsersConnectionArgs>;
```

***what I want to do***
- change node type as custom type
```ts
type CustomType = {}

const followFieldResolver: UserResolvers.FollowerResolver<UserConnection<CustomType>> = () => {}
```

***suggested solution***
- give generic for generated `UserConnection` type
```ts
export interface UserConnection<T = User> {
  edges: UserEdge<T>[];
  pageInfo: UserPageInfo;
}
export interface UserEdge<T = User> {
  node: T;
  cursor: string;
}
```

**Comment by kamilkisiela** [comment]
I don't know if I understand what is an actual issue here but we allow to define custom types in resolvers through a feature called [Mappers](https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers-overwrite-parents-and-resolved-values).

**Comment by dotansimha** [comment]
@kamilkisiela I think it might be related to: https://github.com/dotansimha/graphql-code-generator/issues/1041

**Comment by vreality64** [comment]
@kamilkisiela @dotansimha 
Yes. It is related to #1041. Also I'm already using `Mappers`.

I agree  `Mappers` is good feature. However I want to declare parent type in resolvers to reduce context switching. Since the mapper works through codegen, It is not easy to see if there is a mapping of parent type In Newbie's eyes.

So, in my situation, I need to change the result type to a custom type. And I think generics can solve this situation :)

**Comment by dotansimha** [comment]
Closing for now. `mappers` are way better than it was before, and you can always override types using generics.
