### ISSUE TITLE
Inject custom plugins in runtime

### ISSUE THREAD

**Issue by aniknafs** [dotansimha/graphql-code-generator#1144]
Is there any way to add custom plugins programmatically? I tried: 
```
import { generate } from 'graphql-code-generator';
async function doSomething() {
  const generatedFiles = await generate(
    {
      schema: 'http://127.0.0.1:3000/graphql',
      overwrite: true,
      documents: './src/**/*.graphql',
      generates: {
        [process.cwd() + '/models/']: './my-plugin.js'
      }
    },
    true
  );
}
```
Basically replacing 
```{ plugins: ['typescript-common', 'typescript-server'] }```
with the path to the custom plugin. But it throws with `Invalid "generates" config!`

Generates seems to accept strings as NamedPlugin: 
yml-config-types.d.ts: 
```
generates: {
            [filename: string]: OutputConfig | ConfiguredOutput;
};
type OutputConfig = InstanceOrArray<NamedPlugin | ConfiguredPlugin>;
type NamedPlugin = string;
```
making it an array throws differetly saying it can't find the plugin: 
```
generates: {
        [process.cwd() + '/models/']: ['./my-plugin.js']
}

**Comment by kamilkisiela** [comment]
In order to use your custom plugin you define it just like you would normally do that with regular plugins but instead, you pass a relative path. The path should be relative to `process.cwd()`.

Could you check if your path to a plugin is correct?

**Comment by dotansimha** [comment]
@aniknafs can you please try to use it as array?
```
      generates: {
        [process.cwd() + '/models/']: ['./my-plugin.js']
      }
```

**Comment by dotansimha** [comment]
@aniknafs any update?

**Comment by dotansimha** [comment]
@aniknafs Closing for now. Please feel free to open a new issue it it's still relevant.
