### ISSUE TITLE
Duplicate declaration "Component"

### ISSUE THREAD

**Issue by dragonfire1119** [dotansimha/graphql-code-generator#1152]
**Describe the bug**
When ever I run webpack it gives me ``Duplicate declaration "Component"`` in the generated-models.tsx file

**To Reproduce**
1. Any generated-models.tsx
2. Run with webpack & babel typescript preset
3. Run the following command: `gql-gen ...`

**Expected behavior**
Would be not to have ``generated-models.tsx: Duplicate declaration "Component"``

**Environment:**
 - OS: Mac OS Sierra
 - Codegen: 0.15.2
 - Node: v8.12.0

UPDATE: I also tried ts-loader instead of babel-loader & it gave me 
```
TS2345: Argument of type '{ new (): Document; prototype: Document; }' is not assignable to parameter of type 'DocumentNode'.
  Type '{ new (): Document; prototype: Document; }' is missing the following properties from type 'DocumentNode': kind, definitions
```

UPDATE: I got ts-loader to work & compile with another generate. Babel typescript preset doesn't support namespaces so I think that's why it doesn't work.

**Comment by harrisrobin** [comment]
@dragonfire1119 im running into the same issue...

`Duplicate declaration "Document"`

How did you get around this? do you mind providing more details?

**Comment by harrisrobin** [comment]
@dragonfire1119 gave up on CRA's typescript support because they don't support namespacing and reverted back to using tsc. It's a shame they don't support namespacing though! really a blocker for me because this tool is more useful than dropping tsc.

**Comment by seawatts** [comment]
Is there anyway to solve this without turning off namespaces? I'm using next.js and babel to transpile my typescript

**Comment by dragonfire1119** [comment]
@seawatts Babel has said they are not going to support namespaces already https://github.com/babel/babel/issues/8244

**Comment by ardatan** [comment]
@seawatts Babel's TypeScript support has a lot of issues like that. I recommend you to use TypeScript's own compiler which already handles JSX transpilation, and you can make a bundle with Webpack.

**Comment by dotansimha** [comment]
In the recent refactor, we removed `namespace`s completely, so now everyone should be able to use it without loosing the ability to use other features.
