### ISSUE TITLE
Attempting to use a custom schema loader results in a YAML indentation error

### ISSUE THREAD

**Issue by artemzakharov** [dotansimha/graphql-code-generator#1157]
**Describe the bug**
When I attempt to use a custom loader for my schema, I get an error saying that my indentation is incorrect. Using the actual example given in the [docs](https://graphql-code-generator.com/docs/getting-started/schema-field#custom-schema-loader), for instance, causes this error:

```
YAMLException: bad indentation of a sequence entry at line 3, column 13:
          loader: my-url-loader.js
```
Have tried every spacing and tabbing combination imaginable, can't get it to work. 

**To Reproduce**
1. Copy and paste the example give in the docs
2. Attempt to generate

**Expected behavior**
I expect to be able to use a custom loader. 

**Environment:**
 - OS: Windows
 - Codegen: 0.15.2
 - Node: 10.9.0

**Comment by kevin-lindsay-1** [comment]
Having the same issue

**Comment by kamilkisiela** [comment]
Here's how it should be: 
https://github.com/dotansimha/graphql-code-generator/pull/1168/files

#1168 fixes it
