### ISSUE TITLE
Installing graphql-codegen-typescript-client failis

### ISSUE THREAD

**Issue by thomasfedb** [dotansimha/graphql-code-generator#1159]
**Describe the bug**
When installing the suggested `graphql-codegen-typescript-client` with Yarn the following error occurs:

```
$ yarn add typescript-client --dev
yarn add v1.12.3
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/graphql-codegen-graphql-files-modules: Not found".
```

It appears that perhaps the dependency should be on `graphql-codegen-typescript-graphql-files-modules` instead, as `graphql-codegen-graphql-files-modules` doesn't appear to exist on NPM.

**Comment by thomasfedb** [comment]
The same issue occurs when trying to install `graphql-codegen-typescript-graphql-files-modules` or `graphql-codegen-introspection`:

```
$ yarn add graphql-codegen-introspection --dev
yarn add v1.12.3
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/graphql-codegen-graphql-files-modules: Not found".
```

```
$ yarn add graphql-codegen-typescript-graphql-files-modules --dev
yarn add v1.12.3
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/graphql-codegen-graphql-files-modules: Not found".
```

**Comment by kamilkisiela** [comment]
Are you sure?

`graphql-codegen-typescript-client` [doesn't depend on `graphql-codegen-graphql-files-modules`](https://www.npmjs.com/package/graphql-codegen-typescript-client).

**Comment by thomasfedb** [comment]
That is what appears to be happening. I could not work out why.

**Comment by kamilkisiela** [comment]
Here's the reproduction. Installing every mentioned package works, without any issue.
https://github.com/kamilkisiela/reproduce-codegen-1159

But I think what is the issue you have. There's a `graphql-codegen-graphql-files-modules` in your `package.json` and I can assume that it ended up there when you used `gql-gen init`, am I right?

Here's the fix for that https://github.com/dotansimha/graphql-code-generator/pull/1169

**Comment by thomasfedb** [comment]
Sounds likely @kamilkisiela. Unfortunately I can't say for sure as I have already rebuild the project, this time successfully by adding my dependencies by hand.
