### ISSUE TITLE
[typescript-graphql-files-modules] generates multiple definitions for the same module name when there are multiple files with the same name

### ISSUE THREAD

**Issue by dobesv** [dotansimha/graphql-code-generator#1165]
**Describe the bug**

If you have multiple graphql files with the same name as an input to this module, it still generates more than on `declare module '*/whatever.graphql'` block, which results in typescript errors.

**Expected behavior**

I think it should either:

1. Merge all the declarations into one with all the exports for any of the same-named files,
2. Report a warning and only omit a `declare namespace` for the first one it finds, or
3. Report an error and refuse to generate any output at all

**Comment by dotansimha** [comment]
Also fixed in the latest refactor: https://github.com/dotansimha/graphql-code-generator/pull/1353

**Comment by dotansimha** [comment]
Fix available in 1.0.0 👍
