### ISSUE TITLE
Feature: atomic write file, only if changed

### ISSUE THREAD

**Issue by dobesv** [dotansimha/graphql-code-generator#1172]
When writing a new file, it would be good to write to a temporary file and then rename the file into place.  This way if typescript / tslint is running in "watch" mode it won't pick up a partial file.

Also, if there is a file being overwritten, don't replace it if the new and old file are exactly the same.  This way the file won't be "touched" unless it changes.

**Comment by mariusmarais** [comment]
This sounds like a good idea, but if implemented exactly as requested "watch" mode won't pick up changes at all.  Generation to a temporary file which is then copied into the output file (without renaming) should give you what you want: a single, complete change which is picked up by watch when it's done.  That would also be a good place to compare the result with the existing file.

What do you think?

**Comment by dobesv** [comment]
Oh, interesting, I had assumed that typescript's watch mode would pick up this kind of atomic file write.  Many editors save files that way.  Well, you could try the other approach.  I just had some cases where typescript or webpack running in watch mode reported errors because they read a partially written file.  I'm not sure whether "copying" the file would solve this.  I can't imagine that would be any better than buffering the whole file in memory before writing it instead of writing it piecemeal (assuming you currently are writing to the file as you go).  Buffering it all in memory would allow comparing to the existing file prior to rewriting it.

**Comment by mariusmarais** [comment]
My concern is more about the create-new-file-and-rename part, since that is a known bug in many watchers which cause the change to become invisible, although it's a safe way to write a file.  Buffering in memory would be better if that's possible.

**Comment by dobesv** [comment]
Yeah, you are right, I do recall having an issue with some file watchers not picking up renames, although I think they have since fixed it.  At least for typescript and webpack they watch the whole folder now.  I think.

**Comment by dotansimha** [comment]
I think the best solution for this is to keep a hash of the generated file, and check if before writing the actual file. It will reduce the file-system writes and avoid writing files over and over. 
I'm implementing it as part of the changes in: https://github.com/dotansimha/graphql-code-generator/pull/2359

**Comment by dotansimha** [comment]
Fixed in 1.6.0
