### ISSUE TITLE
Generator output (TypeScript & React Apollo plugins) doesn't generate code as expected.

### ISSUE THREAD

**Issue by jdreg95** [dotansimha/graphql-code-generator#1186]
**Describe the bug**
TypeScript types & React Apollo components are not being generated, though, I believe I have the right config & setup.

```ts
export type Maybe<T> = T | null;

export enum Team {
  Home = 'home',
  Away = 'away'
}

export enum CacheControlScope {
  Public = 'PUBLIC',
  Private = 'PRIVATE'
}

/** The `Upload` scalar type represents a file upload. */
export type Upload = any;
```

**Expected behavior**

Using the following Codegen config:

```yml
overwrite: true
schema: "http://localhost:4000/graphql"
generates:
  generated/graphql.tsx:
    plugins:
      - typescript-common
      - typescript-client
      - typescript-react-apollo
```

I expect that TypeScript types and related React Apollo components should be generated based on my GraphQL schema.

**Schema/Documents**

My GraphQL schema is (downloaded using `graphql get-schema`):

```graphql
directive @cacheControl(maxAge: Int, scope: CacheControlScope) on FIELD_DEFINITION | OBJECT | INTERFACE

enum CacheControlScope {
  PUBLIC
  PRIVATE
}

type Game {
  id: String!
  teamHomeScore: Int!
  teamAwayScore: Int!
  participations: [Participation]!
}

type Mutation {
  createPlayer(firstName: String!, lastName: String!): Boolean!
  createGame(teamHomeScore: Int!, teamAwayScore: Int!, teamHome: [String]!, teamAway: [String]!): Boolean!
}

type Participation {
  game: Game!
  player: Player!
  team: Team!
}

type Player {
  id: String!
  firstName: String!
  lastName: String!
  participations: [Participation]!
}

type Query {
  players: [Player]!
  games: [Game]!
  participations: [Participation]!
}

enum Team {
  home
  away
}

"""The `Upload` scalar type represents a file upload."""
scalar Upload
```

**Environment**

    OS: Arch Linux
    Codegen: v0.15.2
    Node: v10.15.0

**Additional context**

I just got started with GraphQL and created an Apollo Server that comes down to the schema above. I don't quite understand why I am getting such a scarce output from the code generator. I expected it to return types for lets say `Player`, but also HOCs for mutations for example. Is it due to my codegen config or my server being configured poorly?

Thanks a lot,

Jori

**Comment by donovantc** [comment]
@jdreg95 did you manage to resolve this issue? I'm facing the same problem with version 0.16.

**Comment by dotansimha** [comment]
Hi @donovantc @jdreg95 !
Please note that `typescript-react-apollo` requires you to provide your GraphQL documents (queries/mutations/subscriptions/fragments), and it uses both schema and documents to generate output. 
In your config file, I saw only `schema:`, and there are not `documents:` provided.

**Comment by jdreg95** [comment]
@dotansimha hi! The reason for the problem was exactly that: not including `documents/**/*.graphql`  in the config. I didn't know that `typescript-react-apollo` required me to implement documents to generate React components.

Thanks for the clarification!
