### ISSUE TITLE
[Typescript] Option to output a __typemap for GraphQL arguments

### ISSUE THREAD

**Issue by samdenty** [dotansimha/graphql-code-generator#1210]
**Is your feature request related to a problem? Please describe.**

Currently the arguments / inputs are exported as separate types, only referable by importing them. It would be helpful to have an option to inline argument types next to their fields.

That way, it's possible for a library to infer field arguments without needing to use generics.

**Describe the solution you'd like**

Input:
```gql
type Test{
  test(a: String): String;
}
```

output:

```typescript
interface Test {
  test?: string;
  __typemap: {
    test: {
      args: TestArgs
    }
  }
}

interface TestArgs {
  a: string;
}
```

**Comment by dotansimha** [comment]
Hi @samdenty! Can you please provide a complete code example? where do you import `new Query` from? 
We are currently thinking a lot about refactoring the TypeScript template and reduce the number of generated interfaces, so might try to find a solution for that.

**Comment by samdenty** [comment]
Hi there, updated code. The `Query` interface is passed as a generic in my last example `{
  users: { id: string; name: string; age: number }[]
}`

**Comment by vadistic** [comment]
I wanted to help you, but I think I do not understand what you want to do :/

The post field here
```graphql
type Author {
  id: Int!
  firstName: String!
  lastName: String!
  posts(findTitle: String): [Post]
}
```

is entirely different than here
```ts
interface Author {
  id: number;
  firstName: string;
  lastName: string;
  posts(args?: PostAuthorArgs)?: Post[];
}
```

Either you use object arguments pattern or you don't. To get your desired output you just need to write:
```graphql
input PostAuthorArgs {
  findTitle: String
}

type Author {
  id: Int!
  firstName: String!
  lastName: String!
  posts(args: PostAuthorArgs): [Post]
}

```

Is that it?

**Comment by vadistic** [comment]
@samdenty Thanks, got it :)

Disclaimer: I'm not in any way involved in developing of this lib, so wait for official answer ;)

In generated types you've got `Query` & `Mutation` types, that indeed does not have arguments. My guess that it's because they are meant to typing responses.

But there is quite simple way to get argument type :smirk: (gotta love those typescript 3.0 tuples)

```ts
export type SecondArgument<T> = T extends (arg1: any, arg2: infer U, ...args: any[]) => any ? U : never

type TypeMap<T> = { [K in keyof T]: SecondArgument<T[K]> }

type Args = TypeMap<MutationResolvers.Resolvers>['fieldName']
```
So you can do the thing you want

```ts
// btw. I should remap it to reflect your use your 'args' prop but nvm
type GetArgs<T extends object, Field extends keyof T> = TypeMap<T>[Field]

type _TestArgs = GetArgs<Test, 'a'>
```

**Comment by samdenty** [comment]
@vadistic Mhm, yeah I figured as much. I'm in need of the types on the client side

**Comment by dotansimha** [comment]
Types will be available from the next release, and you can force `__typename` with a configuration.

**Comment by dotansimha** [comment]
Fix available in 1.0.0 👍

**Comment by samdenty** [comment]
@dotansimha Is there documentation on the new feature? or what's the new option called

**Comment by dotansimha** [comment]
@samdenty `__typename` is added by default for all generated types of `typescript-operations`. 
You can set `skipTypename: true` to disable.
The new website and docs are being deployed right now, and will be available in a few minutes.

**Comment by samdenty** [comment]
@dotansimha I just updated to the latest version, and I don't understand how this allows me to use a generic to get the argument types for a specific field on the generated output.

```
// ... generated output from the latest version
export type Query = {
  getUser?: Maybe<User>,
};

export type QueryGetUserArgs = {
  id?: Maybe<Scalars['ID']>
};

// Imagine in another file, given the query type (without importing QueryGetUserArgs)
import { Query } from 'generated'

type B = Query
// How can I automatically get the QueryGetUserArgs interface (without importing it)
type ArgsTypeForGetUser = B['getUser'] // ?
```

**Comment by dotansimha** [comment]
@samdenty What's the problem with importing `QueryGetUserArgs`? 
I mean, we can always add `Query['__args']` or something and point to `QueryGetUserArgs`, and this way you'll import only `Query`, but I don't think it matters, because there are just TypeScripr `type`s and they are being stripped while compiling the TS code.

**Comment by samdenty** [comment]
@dotansimha For my specific use case, I've created a library that auto-generates graphql queries using ES6 proxies. It uses the generated query type in `useQuery<Data>`, to automatically makes everything else type safe.

Without this feature, the only way to get type safety on `getUser({ id })` is to manually import a specific arg interface with `getUser<QueryGetUserArgs>({ id })`.

With this feature, I'd be able to automatically infer that, whilst still keeping everything type-safe.

<img src="https://user-images.githubusercontent.com/13242392/54625462-428af280-4a67-11e9-8638-2ef43e0bbd69.png" height="400">

**Comment by dotansimha** [comment]
I see. I can add `Query['$Variables']` (because `$` is not valid GraphQL char, so it won't conflict with fields names) if it will be helpful for you. @samdenty

**Comment by warent** [comment]
Was this ever added? This is something I need as well @dotansimha

**Comment by dotansimha** [comment]
@warent we didn't add this. The original issue was referring to `__typename` and this is available on each type.
