### ISSUE TITLE
Cannot run when installed with pnpm: Declare explicit dependencies 

### ISSUE THREAD

**Issue by SoyYoRafa** [dotansimha/graphql-code-generator#1211]
**Describe the bug**
I cannot run gql-gen when gql-gen is installed by pnpm & @microsoft/rush. 
The node_modules setup they create is very strict. Packages cannot use indirect dependencies pulled in by other dependencies. They won't be found. For example, listr-update-renderer is used by packages/graphql-codegen-cli/src/utils/listr-renderer.ts but never declared in packages/graphql-codegen-cli/package.json

**Solution**
Please add `listr-update-renderer` and `change-case` to the production dependencies of graphql-codegen-cli. Also, please move `common-tags` and `graphql-tools` from dev to production.

We have a work around that allows us to patch the package.json but ideally we wouldn't keep that around forever.

**Environment:**
 - OS: Linux
 - Codegen: 0.16
 - Node: 10.15

**Additional context**
https://rushjs.io/pages/advanced/phantom_deps/

**Comment by dotansimha** [comment]
Hi @SoyYoRafa !
I actually never tried to use `pnpm`, but as far as I understand, it's more strict. 
Regarding `listr-update-renderer`, `change-case`, `graphql-tools` and `common-tags` - you are right, they should be added to `dependencies` field.

**Comment by dotansimha** [comment]
@SoyYoRafa 
Fixed in this PR: https://github.com/dotansimha/graphql-code-generator/pull/1234

**Comment by dotansimha** [comment]
Fixed in 0.16.1 :)
