### ISSUE TITLE
[Typescript Common] Handlebars HTML-escapes enum values

### ISSUE THREAD

**Issue by kamilkisiela** [dotansimha/graphql-code-generator#1212]
https://github.com/dotansimha/graphql-code-generator/blob/9ae6a3729b14dd45a1ba10f8348f1365c1b49ad5/packages/plugins/typescript-common/tests/typescript-common.spec.ts#L209-L231

Given the input, we should see:

```ts
export enum A {
  One = '1', 
  Two = '2', 
}
```

**Comment by dotansimha** [comment]
No more handlebars, so we can close it after the next release.
