### ISSUE TITLE
Error typescript-resolvers code generator version 0.16: Type 'NodeResolvers' is not generic. [2315]

### ISSUE THREAD

**Issue by chenglabs** [dotansimha/graphql-code-generator#1213]
**Describe the bug**
In version 0.16 the typescript-resolvers code generator creates compile errors.
It creates an IResolver type with 
`
  Node?: NodeResolvers<Context>;
`

**To Reproduce**
To reproduce this error, I have created a demo project in https://github.com/chenglabs/code-generator-demo.
When compiling with tsc, this results in the following error in src\server\generated\types.ts
[ts] Type 'NodeResolvers' is not generic. [2315]

If I downgrade the code generator to version 0.15.2 everything works ok

**Expected behavior**
In version 0.16, it generated the following incorrect code for IResolvers:
`
  Node?: NodeResolvers<Context>;
`
In version 0.15.2,  this was.
`
  Node?: NodeResolvers;
`

**Environment:**
 - OS: Windows 10
 - Codegen: v.0.16
 - Node: v.10

**Additional context**
To reproduce the problem:
git clone https://github.com/chenglabs/code-generator-demo
cd code-generator-demo
yarn install
yarn codegen
yarn tsc

**Comment by lirbank** [comment]
This seems to happen when you have GraphQL interfaces and unions in your schema.

**Comment by janhartmann** [comment]
I have the same issue, see these generated types:

```
 UnitEventDetails?: UnitEventDetailsResolvers.Resolvers<Context>;

....

export namespace UnitEventDetailsResolvers {
  export interface Resolvers {
    __resolveType: ResolveType;
  }
  export type ResolveType<
    R =
      | "DamageReportEvent"
      | "CanErrorEvent"
      | "PrecheckEvent"
      | "ServiceCalendarEvent"
      | "ServiceHourEvent"
      | "ServiceKmEvent",
    Parent =
      | DamageReportEvent
      | CanErrorEvent
      | PrecheckEvent
      | ServiceCalendarEvent
      | ServiceHourEvent
      | ServiceKmEvent,
    Context = IContext
  > = TypeResolveFn<R, Parent, Context>;
```

Type 'Resolvers' is not generic.ts(2315)

**Comment by kamilkisiela** [comment]
I think it was fixed already, could you try `0.17.0-alpha.4317ee16`?

**Comment by seamusv** [comment]
> I think it was fixed already, could you try `0.17.0-alpha.4317ee16`?

This is working for me.  Thanks!

**Comment by janhartmann** [comment]
Worked - looking forward for the stable release.

**Comment by chenglabs** [comment]
@dotansimha 
Thanks! It's working.
