### ISSUE TITLE
schema-ast plugin is not listed in "Available Plugins" docs page

### ISSUE THREAD

**Issue by mattwilson1024** [dotansimha/graphql-code-generator#1221]
If I am understanding things correctly, there is a plugin called `schema-ast` plugin (`graphql-codegen-schema-ast` on npm) which generates a .graphql file. 

This seems very useful for "downloading" a copy of the schema from a remote server (for example, a backend api) into a client application (such as an Angular app that consumes that API). Having a copy of the schema.graphql file pulled down into the client project enables things like autocompletion in the editor when working on the frontend queries.

I _can_ see `Schema AST` listed in the examples at https://graphql-code-generator.com/, but it is **not listed** in the "Available Plugins" page here https://graphql-code-generator.com/docs/plugins/.

Is this an oversight or is `Schema AST` not intended to be used in this way?

**Comment by dotansimha** [comment]
Done in:  https://github.com/dotansimha/graphql-code-generator/commit/6cf5bfb299a534fef3db7e0b5726eda3dbd88639
Thanks @mattwilson1024
