### ISSUE TITLE
Empty files should be ignored

### ISSUE THREAD

**Issue by furier** [dotansimha/graphql-code-generator#1235]
Empty files are not ignored. This is a problem if one has empty *.gql files that are scanned by graphql-code-generator, you get an `unexpected end of file` exception. With Angular Schematics we want to auto generate `*.component.gql` files when we use the CLI to create new components, and by default they are then empty.

![image](https://user-images.githubusercontent.com/776919/51977798-ab52e700-2488-11e9-866f-3cbbe0d2272e.png)

**Comment by dotansimha** [comment]
@furier thank you for reporting it, I'll take a look :)

**Comment by dotansimha** [comment]
@furier we moved the logic of files loading to `graphql-toolkit`, and I fixed it there: https://github.com/dotansimha/graphql-code-generator/pull/1257

**Comment by dotansimha** [comment]
Fixed in 0.16.1 :)
