### ISSUE TITLE
graphql-code-generator IResolvers types are not compatible with IResolvers from graphql-tools

### ISSUE THREAD

**Issue by ellipticaldoor** [dotansimha/graphql-code-generator#1244]
**Describe the bug**
When I try to use **graphql-codegen-typescript-resolvers**  on my resolvers with **makeExecutableSchema** from graphql-tools I get a type error.

**To Reproduce**
When using this code
``` typescript
import { makeExecutableSchema } from "graphql-tools";
import { IResolvers } from "@generated/apollo";

const resolvers: IResolvers = {
  Query: {},
  Mutation: {},
};

const schema = makeExecutableSchema({
  typeDefs: importSchema("./src/schema.graphql"),
  resolvers,
});
```

I get the following error message
```
Type 'IResolvers<ApolloContext>' is not assignable to type 'IResolvers<any, any> | IResolvers<any, any>[] | undefined'.
  Type 'IResolvers<ApolloContext>' is not assignable to type 'IResolvers<any, any>'.
    Index signature is missing in type 'IResolvers<ApolloContext>'.
```

I think this happens because the types from graphql-code-generator for IResolvers types are not compatible with IResolvers types from graphql-tools.

**Environment:**
 - OS: macos
 - Codegen: ^0.16.0
 - Node: v10.13.0

**Comment by dotansimha** [comment]
Hi @ellipticaldoor ! Thank you for reporting it. 
There is an existing issue related to it: https://github.com/dotansimha/graphql-code-generator/issues/1133
