### ISSUE TITLE
Quick Start - does not work - gql-gen: command not found

### ISSUE THREAD

**Issue by bastman** [dotansimha/graphql-code-generator#1253]
Could you please help ?

I tried follow the Quick Start.

$ npm install graphql-code-generator
$ gql-gen init

-bash: gql-gen: command not found

**Comment by bastman** [comment]
this seems to work: $ node_modules/.bin/gql-gen init

**Comment by iamclaytonray** [comment]
Did you install `graphql-code-generator` in one directory and then change into another directory? If so, that module would not be found. 

Other possible solutions would be:

- Install globally (`npm i -g graphql-code-generator # yarn global add graphql-code-generator`)
- Use npx (`npx gql-gen init`)
- Install and refresh your terminal session.

If you could give your version of NPM and your OS, that would be helpful. Thanks!

**Comment by dotansimha** [comment]
@bastman please read the comments here: https://github.com/dotansimha/graphql-code-generator/issues/1222
