### ISSUE TITLE
Types are not generated for introspection query (Re-Submit)

### ISSUE THREAD

**Issue by Jonatthu** [dotansimha/graphql-code-generator#1275]
**Describe the bug**
Trying to generate the typescript of the next query.

```
query LoadEntities {
	__schema {
		queryType {
			name
			fields {
				name
				description
				isDeprecated
				deprecationReason
				type {
					name
					kind
				}
			}
		}
	}
}
```

Resulting in:

```
export namespace LoadEntities {
  export type Variables = {
  }

  export type Query = 
}
```

My configuration:
```
{
	"schema": "http://localhost:5000/graphql",
	"overwrite": true,
	"documents": "src/app/**/*.graphql",
	"generates": {
		"./src/app/generated/graphql.ts": {
			"config": {
				"noGraphqlTag": false
			},
			"plugins": [
				"typescript-common",
				"typescript-client",
				"typescript-server",
				"typescript-apollo-angular"
			]
		},
		"./schema.json": {
			"plugins": [
				"introspection"
			]
		}
	}
}
```

On the version:
```
"graphql-code-generator": "^0.16.1",
"graphql-codegen-introspection": "^0.16.1",
"graphql-codegen-typescript-apollo-angular": "^0.16.1",
"graphql-codegen-typescript-client": "^0.16.1",
"graphql-codegen-typescript-common": "^0.16.1",
"graphql-codegen-typescript-server": "^0.16.1",
```

I see there was a pull request but has been closed or forgotten.

I am writing an app to manage this queries and would be really useful to be able to generate this types.

Related issues
https://github.com/dotansimha/graphql-code-generator/pull/660
https://github.com/dotansimha/graphql-code-generator/issues/643

**Comment by dotansimha** [comment]
Thanks @Jonatthu !
I'm currently working on a big refactor for the typescript templates, so I might give it another try. 
Closing, let's track the progress in: https://github.com/dotansimha/graphql-code-generator/issues/643
