### ISSUE TITLE
Generating multiple files

### ISSUE THREAD

**Issue by rsrinivasan15** [dotansimha/graphql-code-generator#1292]
@dotansimha - We recently started using this codegen for one of our project and it works great so far (Thank you for building this awesome thing!!). I see that this project had a template for splitting the output into multiple files and was removed due to circular dependency issue. We wanted to know what is the recommended best practice for maintaining the generated files as putting everything in one file will really bloat the generated file once we start to have more graphql schemas and documents. Just wanted to check if this has already been discussed before or is there a template out there that solves this issue?

**Comment by dotansimha** [comment]
Hi @rsrinivasan15 ! Thank you for opening this issue.
We had support for multiple files before, but the dependencies and the needs to calculate the imports on each file was a mess and it was very hard to maintain. Also, it was very hard to share code with the single-file output plugins. 
We decided to drop it a few months, but we are planning to add support for generating multiple files in a future version. It does not mean that we are going to add it to the existing plugins, but developers will be able to output more than one file.
