### ISSUE TITLE
Support Iterable Interface for Resolvers

### ISSUE THREAD

**Issue by blakeembrey** [dotansimha/graphql-code-generator#1298]
**Is your feature request related to a problem? Please describe.**

GraphQL supports the iterator protocol via `iterall`. It only supports sync iterables right now for regular returns though, but it'd be nice if the generated TypeScript interfaces also accepted iterator returns.

**Describe the solution you'd like**

Changing all arrays generated by GraphQL to TypeScript resolvers into iterables.

**Comment by dotansimha** [comment]
Implement by @kamilkisiela in the recent refactor, it will be available soon.

**Comment by blakeembrey** [comment]
I think I found the change but an array is iterable, it seems redundant to specify array or iterable.

**Comment by dotansimha** [comment]
@kamilkisiela ^ ?

**Comment by kamilkisiela** [comment]
@blakeembrey So if Array is Iterable then why to use Iterable in a first place?

**Comment by blakeembrey** [comment]
Because Array implements Iterable, Iterable does not implement Array.

**Comment by dotansimha** [comment]
So basically, @blakeembrey we can use just `Iterable`? are you sure it's compatible with all TypeScript configurations? 

@kamilkisiela

**Comment by dotansimha** [comment]
Available in 1.0.0 👍

**Comment by slosd** [comment]
I was looking for this exact feature, but discovered that the changes (https://github.com/dotansimha/graphql-code-generator/pull/1471) were reverted only a few days later (for the release of 1.0.3 it seems) with https://github.com/dotansimha/graphql-code-generator/pull/1534:
> Remove ArrayOrIterable at the moment, until we'll figure out if it's really needed.

Can this issue be reopened?

**Comment by laurisvan** [comment]
I recently stumbled upon this issue when trying to speed up our subscriptions where we try to avoid excess memcopies by returning Iterables instead of Arrays.

Is there a way to explicitly make one resolver return e.g. Iterable, so that we could gradually transition from Arrays to Iterables?
