### ISSUE TITLE
Use environment variables in codegen.yml

### ISSUE THREAD

**Issue by n44ps** [dotansimha/graphql-code-generator#1302]
**Describe the bug**
I can't use an environment variables in the codegen.yml file.
**To Reproduce**
1. Try using : `schema: ${API_ENDPOINT}`

And you'll get : `Unable to find matching files for glob: ${API_ENDPOINT} in directory`

**Expected behavior**
I would like to use the environment variables instead of raw string

**Environment:**
 - OS: MacOS Mojave
 - Codegen: ^0.16.0
 - Node: v10.15.0

**Comment by dotansimha** [comment]
@n44ps thank you for reporting it.
The codegen does not support it at the moment, but that's definitely a valid use case.
As a workaround, I can suggest you to run the [codegen from code, using the programmatic API](https://graphql-code-generator.com/docs/getting-started/programmatic-usage), and use your environment variables.

**Comment by n44ps** [comment]
This is what I've ended up with, thank you @dotansimha !

**Comment by dotansimha** [comment]
Available in 0.18.0 🎉

**Comment by steebchen** [comment]
It would be awesome if you could specify a default value, like you can usually do with yaml files such as in docker:

```yaml
version: '3'

services:
  lb:
    image: nginx:latest
    environment:
      PASSWORD: "${PASS:-secret}"
```

**Comment by dotansimha** [comment]
@steebchen can you please open a new issue for that? It will be easier to track.

**Comment by steebchen** [comment]
See #1812
