### ISSUE TITLE
--header Option does not work

### ISSUE THREAD

**Issue by mctep** [dotansimha/graphql-code-generator#132]
I think there is mistyping. :)

In `cli` it is requesting `header` option https://github.com/dotansimha/graphql-code-generator/blob/a6c3d1d13fb69f142d1139b4e52eb2d6ac934c1e/packages/graphql-codegen-cli/src/cli.ts#L65

But in generation it passes `headers`

https://github.com/dotansimha/graphql-code-generator/blob/a6c3d1d13fb69f142d1139b4e52eb2d6ac934c1e/packages/graphql-codegen-cli/src/cli.ts#L116

**Comment by dotansimha** [comment]
Thanks @mctep 
Please try `0.8.7`. 

Note that to add multiple headers, you need to specify `--header` multiple times, and separate the value with `=` or `:`.

`gql-gen --header "A=1" --header "B:2"`

**Comment by mctep** [comment]
It works! 👍
