### ISSUE TITLE
How To: Create a custom handlebars template with the latest release 

### ISSUE THREAD

**Issue by bhaidar** [dotansimha/graphql-code-generator#1323]
Hello,
I am reading through the docs and I couldn't find enough info on how to provide our own handlebars template to generate custom stuff?

Thanks
Bilal

**Comment by dotansimha** [comment]
Hi @bhaidar ! 
We changed the way the templates are being written, and now you are not forced to use Handlebars.
You can read the docs here: https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin
And there is a section that explains how to use Handlebars if you wish to: https://graphql-code-generator.com/docs/custom-codegen/using-handlebars
