### ISSUE TITLE
Custom hooks (typescript-react-apollo)

### ISSUE THREAD

**Issue by FredyC** [dotansimha/graphql-code-generator#1336]
BTW: useSubscription is [merged and released](https://github.com/trojanowski/react-apollo-hooks/pull/37) 🎉 

**Is your feature request related to a problem? Please describe.**
I definitely love that I can generated "hooked" variants for queries (and subscriptions). However, I do have some wrapper hooks around `useQuery` (mostly to normalize loading/data slightly) and `useMutation` for error handling.

**Describe the solution you'd like**
It would be nice to be able to specify a path to file that exports useQuery/Mutation/Subscription so it can be customized.

**Describe alternatives you've considered**
Not much really, except some weird aliasing of `react-apollo-hooks` and forking.

**Comment by dotansimha** [comment]
Available in 0.18.0 🎉
