### ISSUE TITLE
Configurable `gql` import

### ISSUE THREAD

**Issue by FredyC** [dotansimha/graphql-code-generator#1342]
**Is your feature request related to a problem? Please describe.**
It's pretty much [a recommended way](https://github.com/facebook/create-react-app/pull/5481) to use `graphql.macro` for loading graphql files or inlining documents. Since CRA2.0 has `babel-plugin-macros` includes it's a fairly cheap optimization of runtime code.

**Describe the solution you'd like**
Add configuration option `gqlImportFrom` to specify where to find `gql`.

**Describe alternatives you've considered**
Perhaps a boolean flag directly for a macro variant?

**Comment by IanVS** [comment]
I think this shouldn't be a Boolean. It would be great if it's flexible, to support other import locations, like Gatsby: https://github.com/dotansimha/graphql-code-generator/issues/1321

**Comment by dotansimha** [comment]
Fixed in `graphql-toolkit` by @kamilkisiela . PR here: https://github.com/dotansimha/graphql-code-generator/pull/1370

**Comment by kamilkisiela** [comment]
@dotansimha It's not exactly the same. I made `graphql-tag-pluck` to support any kind of package, either with default or named export but we don't have a way to define those packages in `graphql-code-generator` through `codegen.yml`.

**Comment by kamilkisiela** [comment]
@dotansimha #1376 should enable that

**Comment by kamilkisiela** [comment]
More on that here https://github.com/DAB0mB/graphql-tag-pluck#options

**Comment by dotansimha** [comment]
Available in 0.18.0 🎉
