### ISSUE TITLE
Planned breaking changes for typescript plugins 🚀

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#1350]
Hi,

We are currently planing to refactor and reimplement the `typescript` plugins.

These changes include:
- Change the scope of the plugins. Today we have `typescript-common`, `typescript-client`, `typescript-server` and `typescript-resolvers`. After this change, we'll have `typescript` (which includes all types, similar to server and common packages), `typescript-client` (types for queries, mutations, subscriptions and fragments, **based on** the `typescript` types), and `typescript-resolvers`. 
- Use `Pick<>` to get the fields from `typescript` plugin declarations. It also means that we no longer need to generate `namespace`s.
- Changes and refactor to the configuration flags.
- Allow to add `__typename` automatically to the generated output.
- Allow `scalars` config to override every type. 
- Better naming solution, we know that the current solution might be annoying. We still plan to use `pascalCase` as default, but it will be easier and less buggy to override it.
- We will try to provide backward compatibility, and it might not be easy. 
- Allow to generate internal fields of `graphql`.
- Tree shaking for all packages
- Cleanup for old code

Please feel free to add to this thread more ideas regarding the `typescript` package! 🚀

**Comment by jonaskello** [comment]
> * Allow to add `__typename` automatically to the generated output.

Does this mean adding `__typename` to the full schema types? (see my [comment here](https://github.com/dotansimha/graphql-code-generator/issues/649#issuecomment-467332215))

**Comment by dotansimha** [comment]
@jonaskello The goal is to add `__typename` automatically to selection set. We added a similar solution for `flow` templates. Can you please elaborate how adding `__typename` can benefit to the schema types as well? If you are dealing with client-side cache, I guess that adding `__typename` to every type will solve this issue for you?

**Comment by jonaskello** [comment]
Yes, adding `__typename` to all types, including the "full" types that are today generated by `typescript-server` would solve my use-case. I need `__typename` when I add entities to the client-side cache because I use it to generate the unique ID in the cache. To explain some more, I have this on the client-side:

```ts
const newProduct: Partial<WithTypename<GqlSchema.Product>> = {
        __typename: "Product",
        id: "theid",
        key: "thekey",
        name: "thename",
        retired: false,
        description: "thedescription",
      };
const patch = GqlCachePatch.createEntity<Partial<GqlSchema.ProductAtTx>>(getObjectId(newProduct), newProduct),
```

The `getObjectId` function uses `__typename` to generate a concatenated unique ID in the flat normalized cache as `__typename;obj.id`. `WithTypename` is my current workaround to add `__typename`. It is simply `type WithTypename<T> = T & { readonly __typename: string };` but this is not safe as it is `string` rahter than the correct string literal type. I understand my use-case and this example is probably unusual but I hope the example clarifies rather than adds more confusion :-).

My understanding of the outlined plan is that the `typescript-common` and `typescript-server` packages will be joined into a `typescript` package. This new package will also somehow be the base for `typescript-client`. So if the `typescript` package supports adding `__typename` then it will be possible to add it everywhere, both to types for query/mutation documents and for full schema types.

**Comment by dotansimha** [comment]
Yeah that's right, common and server will be joined into `typescript`, and it will be the base for `typescript-documents`. I'm still thinking about adding `__typename` to the types, because it's not part of the GraphQL standard, and I'm need to check how it will behave with the `typescript-resolvers` package. 
We are making it way more easy to make changes, so it might be very easy to implement if you need a custom behaviour.

**Comment by jonaskello** [comment]
Agreed, the `__typename` field is a bit special since it is part of the schema in the sense that you can query for it (and I guess that ability is part of the spec). But then again it is not really part of the schema as you don't declare it in the types.

Btw, I just migrated from 0.13 to 0.17 yesterday and I am loving the new config files, so much simpler 👍

**Comment by maapteh** [comment]
Just some weird thought, maybe it helps.
- Create schema changes overview. Our app is using graphql-modules and we can generate schema's without running the application (so no endpoint needed). It would be nice if we could compare it with the current schema on production (which is also in our codebase). Then in our pipeline we can show this overview without running anything.
- Accept regex in the current graphql documents glob so it will be able to use this to generate generated files per matched item. So for example: '/\/src\/module\/([a-z])+\/(.*)\.graphql/' then it knows it can place all module/user stuff in that folder, and maybe all common stuff in module. Don't know if it then becomes more friendly or the opposite :)

**Comment by dotansimha** [comment]
@maapteh 

> Accept regex in the current graphql documents glob so it will be able to use this to generate generated files per matched item. So for example: `/\/src\/modules\/([a-z])+\/(.*)\.graphql/` then it knows it can place all `modules/user` stuff in that folder, and maybe all common stuff in module. Don't know if it then becomes more friendly or the opposite :)

We support `glob` which is an easier way to do regex when dealing with files.
If you wish to get all files recursively, you can use `src/modules/**/*.graphql`.

**Comment by dotansimha** [comment]
@maapteh 
> Create schema changes overview. Our app is using graphql-modules and we can generate schema's without running the application (so no endpoint needed). It would be nice if we could compare it with the current schema on production (which is also in our codebase). Then in our pipeline we can show this overview without running anything.

It feels like this feature it not part of the codegen's scope, but I think https://github.com/kamilkisiela/graphql-inspector can do this for you :)

**Comment by maapteh** [comment]
Wow this last i totally missed, will run it today.
My second thought was about how to generate types per module, but as already discussed it will be hard when modules require other modules. So one file maybe is still best :)

**Comment by NickClark** [comment]
Super excited to see this merged in! In my enthusiasm I decided to try `0.19.0-alpha.07841c6`! But no cigar. I get a `is_glob_1.default is not a function` error when trying to run the generator. I know this is an alpha, just wanted to make sure it was on your radar

**Comment by NickClark** [comment]
@ardatan Nice! Tried `0.19.0-alpha.85ff402e`, and #1468 seems to have done the trick. Everything except one plugin seems to be working for me now. When using `typescript-apollo-angular` I now get an error: `indent_string_1.default is not a function`

**Comment by ardatan** [comment]
Could you try again with the latest canary? @NickClark

**Comment by NickClark** [comment]
@ardatan I tried ``, but it seems to have the same issue. I then manually edited module (removed all the `.default`'s), so I would have expected your fix to work. Did the right version get deployed to npm? Also, I found out, that even with that fix, I now get an issue with my fragments: 

```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/client/generated/graphql.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Syntax Error: Unexpected $


 Found 1 error

  ✖ GraphQL request
    Syntax Error: Unexpected $

    GraphQL request (7:5)
    6: }
    7:     ${DeviceAttributesFragmentDoc}
           ^


Something went wrong
error Command failed with exit code 1.
```

My current deps:
```
    "graphql-code-generator": "^0.19.0-alpha.14bf4dca",
    "graphql-codegen-schema-ast": "^0.18.0",
    "graphql-codegen-typescript": "^0.19.0-alpha.14bf4dca",
    "graphql-codegen-typescript-apollo-angular": "^0.19.0-alpha.14bf4dca",
    "graphql-codegen-typescript-operations": "^0.19.0-alpha.14bf4dca",
    "graphql-codegen-typescript-resolvers": "^0.19.0-alpha.14bf4dca",
```
But the lock file seems to be using the wrong deps?

**Comment by dotansimha** [comment]
@NickBolles can you please share the fragment file? and your `.yml` config?

**Comment by NickClark** [comment]
@dotansimha Assuming you're talking to me 😉... I'll see if I can make a simpler reproduction of the issue. Also, I'm still getting the following when printing out errors:

```
  ❯ Generate outputs
    ❯ Generate src/client/generated/graphql.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Syntax Error: Unexpected $
indent_string_1.default is not a function
```
I've kinda hijacked this issue... should I move this to a dedicated issue? Wasn't sure, since this all alpha stuff.

**Comment by NickClark** [comment]
@dotansimha Here's a minimal reproduction. You may need to open a new terminal and run `yarn start` manually. I believe this shows both the `indent_string_1.default is not a function` and the fragment issue

[![Edit 4rzr0rky44](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4rzr0rky44?fontsize=14&module=%2Fcodegen.yml&view=editor)

**Comment by kamilkisiela** [comment]
@NickClark I checked your example and the `master` branch has a fix, you can try it yourself under `0.19.0-alpha.dd5bacfd` (pin dependencies).

**Comment by NickClark** [comment]
> (pin dependencies)

...of course! 🤦‍♂️  Thanks!

**Comment by NickClark** [comment]
Looking over the output... Good work guys! Also love that Class documents are exported separately now!

**Comment by NickClark** [comment]
Looks like the enums config has changed... checking...

**Comment by dotansimha** [comment]
1.0.0 is available now 👍 

@NickClark Please open a new issue if something is wrong :)

**Comment by NickClark** [comment]
Yay!

**Comment by slikts** [comment]
Does there happen to be something like a Slack channel for following the development?
