### ISSUE TITLE
Dart plugin available ?

### ISSUE THREAD

**Issue by fvisticot** [dotansimha/graphql-code-generator#1354]
Is it yet possible to generate Dart code from this generator ?

I try this: https://github.com/micimize/graphql-to-dart

But I get an error: TypeError: Must provide Source. Received: {}

**Comment by dotansimha** [comment]
Hi @fvisticot !
`graphql-to-dart` package is using the old API of the codegen. You can try to use it with an old version (`0.9.2`), or contact @micimize in order to update it to the latest API.

**Comment by micimize** [comment]
@fvisticot I don't believe there are any robust dart generators yet. [You can try using mine](https://github.com/micimize/graphql-to-dart/issues/3#issuecomment-468009069) with the older generator - I should hopefully have time to update it soon

**Comment by micimize** [comment]
`graphql-to-dart@0.1.0-alpha1` should now work with `0.18.0`

**Comment by Parables** [comment]
Hello there, please check out the generator  I wrote for Flutter to generate Freezed models from your GraphQL types #8171. 

Let me know if you need any features. I am actively working on it cause I need it for some projects and I hate to manually write Freezed models when my backend keeps changing frequently.
