### ISSUE TITLE
Add support for ignored element in `gqlgen.json`

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#136]
To ignore specific GraphQL elements when generating with custom templates

**Comment by tjme** [comment]
Custom templates are great, especially the Project option for generating a file for each Type, but (other than for Input Types) I don't see how to be selective about which which types are created.

**Comment by tjme** [comment]
It is very useful that with the new feature of 0.8.18: "Generator will not write a file to file system if the content is empty", custom templates can now be selective (by including an outer conditional that can selectively result in an empty output). A configuration option in gql-gen.json might still be useful though (and might perform better).
