### ISSUE TITLE
[typescript] Add option to use string unions instead of arrays

### ISSUE THREAD

**Issue by nklayman** [dotansimha/graphql-code-generator#1379]
**Is your feature request related to a problem? Please describe.**
Prisma [uses string unions instead of enums](https://github.com/prisma/prisma/issues/3429). This causes type errors where typescript thinks graphql code generator's enums are not compatible with prisma's string unions. To avoid this, you have to manually typecast everything (which tslint doesn't like). This will disable type checking for that statement, resulting in issues if your database type and your schema type are different.

**Describe the solution you'd like**
Since Prisma [hasn't merged this PR and it doesn't seem like they will merge it anytime soon](https://github.com/prisma/prisma/pull/3438), It would be really nice if it could be fixed on your end.

**Describe alternatives you've considered**
Graphqlgen [appears to have this fixed](https://github.com/prisma/graphqlgen/issues/213).

Thanks for your awesome work on this!

**Comment by dotansimha** [comment]
Hi @nklayman! 
We support this feature for a long time (actually, [since May 2018](https://github.com/dotansimha/graphql-code-generator/commit/d80ea2a1ab71853a27def71ca0e33447a72cd709) 😉),  just use `enumsAsTypes`. 
It will generate `export type MyEnum = 'A' | 'B'` instead of `export enum ...`.

**Comment by nklayman** [comment]
Awesome! Sorry to bother you, I know how annoying it is to deal with issues like these.
