### ISSUE TITLE
Simplify fragment emitting

### ISSUE THREAD

**Issue by altschuler** [dotansimha/graphql-code-generator#139]
With the editor I'm using union types makes the type documentation rather big (big as in every field of some type is being reported instead of the type itself).

I think this would be alleviated if single fragments where emitted without an empty object type.

**tl;dr**: it'd be nice if

```
export type Nodes = {
    } & ProfileCard.Fragment
```

was being emitted as simply

```
export type Nodes = ProfileCard.Fragment
```

**Comment by dotansimha** [comment]
@altschuler 
Thank you, I will fix it in the next release :)
