### ISSUE TITLE
[typescript-graphql-files-modules] Option to support fragments

### ISSUE THREAD

**Issue by dobesv** [dotansimha/graphql-code-generator#1424]
**Is your feature request related to a problem? Please describe.**

I am switching over to `typescript-graphql-files-modules` and there are a few places where I import fragments.  This works for me, because I am using https://github.com/detrohutt/babel-plugin-import-graphql and it supports fragments.

**Describe the solution you'd like**

Fragments should also be declared in the modules output by the plugin, perhaps as an option if someone isn't using a graphql import system that supports them.

**Comment by dobesv** [comment]
*Workaround*

If a fragment is placed in its own file, you can import it as the default export of that file.

**Comment by dotansimha** [comment]
Hi @dobesv ! 
During the refactor of TypeScript plugins (https://github.com/dotansimha/graphql-code-generator/pull/1353), we fixed this issue :) 
See: https://github.com/dotansimha/graphql-code-generator/blob/refactor/typescript/packages/plugins/typescript-graphql-files-modules/src/index.ts#L16

**Comment by dotansimha** [comment]
Fix available in 1.0.0 👍
