### ISSUE TITLE
missing typing in graphql-codegen-compiler (0.8.10)

### ISSUE THREAD

**Issue by thunder7553** [dotansimha/graphql-code-generator#143]
The package.json file contains the wrong path for the typings. It says to look for the typings in /dist/src/index.d.ts, but they are in /dist/index.d.ts.

**Comment by thunder7553** [comment]
it's also bogus in graphql-codegen-generators

**Comment by dotansimha** [comment]
Fixed, will release soon.
Thanks @thunder7553
