### ISSUE TITLE
Add support for all fields given by fragments on models

### ISSUE THREAD

**Issue by Kurren123** [dotansimha/graphql-code-generator#145]
I'm doing a C# generator. To make serialization easier I'm trying to match what the JSON output of the query is. E.g. this query:

```
query GetCustomer{
  customers{
    ...customerFields
  }
}

fragment customerFields on customer {
  id
  name
  reference
}
```

Can give this response:

```
{
  "data": {
    "customers": [
      {
        "id": 1,
        "name": "Kurren",
        "reference": "KUR"
      },
      {
        "id": 2,
        "name": "Bob",
        "reference": "BOB"
      }
    ]
  }
}
```

However currently the fragments are provided as separate types to the handlebars template (and the typescript template generates separate classes for each one). Ideally I want all the fields given by fragments to be _embedded_ as fields in the current class.

I propose adding a property to models called `fieldsFromFragments` which will give me all the fields given by fragments (including nested fragments, fragments within other fragments). This will allow me to generate something like this for above:

```
public class GetCustomerResult
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Reference { get; set; }
}
```

Which means I can get the graph query result and deserialize it using any existing JSON deserializers out there. 

I am more than happy to submit a PR for this as I'll probably be adding this feature to my own fork in the next week.

**Comment by dotansimha** [comment]
Hi @Kurren123! It's so amazing that your are writing a C# generator!

Your use case is need to merge the fields from both selection set, and fragments' selection sets, right?
In TypeScript, the generator generated a merged types with `&`.

In C#, you can do something similar? maybe implement an interface? 

Another solution, is to do something similar to this in your Handlebars template:
```
  export type {{ operationType }} = {
    {{> selectionSet fields }}
    {{#each fragmentsSpread}}
          {{> selectionSet fields }}
    {{/each}}
    {{#each inlineFragments}}
          {{> selectionSet fields }}
    {{/each}}
  }
```

Because each operation that uses fragments spread or inline fragment, has an array of `fragmentsSpread` / `inlineFragments`, and the value of each item in the array is the reference to the actual fragment type, and you can use it's fields.

**Comment by Kurren123** [comment]
Hi @dotansimha. Thanks for your help. I think that second solution looks appropriate, because when a class in C# implements an interface we still need to declare each property in that class (including properties given by interfaces). Will your second solution work if there are fragments within fragments? (nested fragments)? Like so:

```
query GetCustomer{
  customers{
    ...customerFields
  }
}

fragment customerFields on customer {
  id
  name
  ...nestedCustomerFields
}

fragment nestedCustomerFields on customer {
  reference
}
```

**Comment by dotansimha** [comment]
@Kurren123 You can create a template, and call is recursively :)

**Comment by dotansimha** [comment]
@Kurren123 how it's going?

**Comment by dotansimha** [comment]
@Kurren123 please let me know if you still need help :) closing for now.
