### ISSUE TITLE
Correct update parameters in mutation

### ISSUE THREAD

**Issue by pdobrigkeit** [dotansimha/graphql-code-generator#1476]
Hey, I am starting to use the Code Generator for Angular. 

I have a basic query

    mutation upsert_test($test: String!) {
      insert_test(objects: [{test: $test}]) {
        affected_rows
        returning {
          id
          test
        }
      }
    }

I generated a Mutation Service using the angular plugin

    @Injectable({
      providedIn: "root"
    })
    export class UpsertTestGQL extends Apollo.Mutation<
      UpsertTest.Mutation,
      UpsertTest.Variables
    > {
      document: any = gql`
        mutation upsert_test($test: String!) {
          insert_test(objects: [{ test: $test }]) {
            affected_rows
            returning {
              id
              test
            }
          }
        }
      `;
    }

And I want to execute the mutation and update my store

    this.upsertTestGQL.mutate({ test: 'ghi' }, {
      update: (proxy, {data: insert_test}) => {
        console.log(proxy);
        console.log(insert_test);
      }
    }).subscribe(({data}) => {
      console.log('got data', data);
    }, (error) => {
      console.log('there was an error sending the query', error);
    });

What are the correct parameters and imports for the `update`, because I get the following error:
Argument type {update: (proxy: any, {data: insert_test}: {data: any}) => void} is not assignable to parameter type MutationOptions<UpsertTest.Mutation, UpsertTest.Variables> | undefined 
Inspection info: Checks TypeScript called function parameters , return values , assigned expressions to be of correct type.

**Comment by dotansimha** [comment]
@kamilkisiela can you please take a look?

**Comment by pdobrigkeit** [comment]
I am certain I tried this before, but now it seem to work without further imports 

    this.upsertTestGQL.mutate({ test: 'mnop' }, {
      update: (store, {data: { insert_test } }) => {
        // Read the data from our cache for this query.
        const data: MyTest.Query = store.readQuery({ query: this.testGQL.document });
        // Add our comment from the mutation to the end.
        data.test.push(insert_test.returning[0]);
        // Write our data back to the cache.
        store.writeQuery({ query: this.testGQL.document, data });
      }
    }).subscribe(({data}) => {
      console.log('got data', data);
    }, (error) => {
      console.log('there was an error sending the query', error);
    });
