### ISSUE TITLE
Arrays not being emitted as optional in typescript generator

### ISSUE THREAD

**Issue by altschuler** [dotansimha/graphql-code-generator#149]
An input type like

```
input Foo {
  tags: [String!]
}
```

is not being emitted with `tags` as optional. It should, unless the gql type was `tags: [String!]!`.

Digging a little further, this only happens when the inner type of the array is non-null, so

```
input Foo {
  tags: [String]
}
```

Will emit correctly as `tags?: string[]`

This is related to the recent change from `| null` to `?`.

**Comment by dotansimha** [comment]
@altschuler after changing the `?` to `?` and `| null`, does this solve this issue?

**Comment by altschuler** [comment]
Yes, forgot about this issue. It works perfectly now :) Thanks!
