### ISSUE TITLE
No plugins where a target is not selected init command

### ISSUE THREAD

**Issue by P4sca1** [dotansimha/graphql-code-generator#1494]
**Describe the bug**
I just started learning GraphQL and saw this package.
I realized that `v1.0.0` just got released and gave it a try.

**To Reproduce**

1. `npm i -D @graphql-codegen/cli`
2. `npx grapql-codegen init`
3. Press enter (doesn't matter what you select here afaik).
4. Type `./schema.graphql` (doesn't matter what you type here afaik).
5. There are no plugins to select, neither can this step be skipped.

**Expected behavior**
I expected to be able to select plugins.

**Environment:**

- OS: macOS High Sierra
- Codegen: v1.0.0
- Node: 10.15.0

**Comment by kamilkisiela** [comment]
One thing I noticed is an incorrect path to `package.json` but other than that it works:

https://codesandbox.io/s/wy21wxrpjk?expanddevtools=1&fontsize=14&hidenavigation=1&view=preview

Try to open a new terminal and type `yarn gql-gen init`.

**Comment by P4sca1** [comment]
Could you check whether it works for you with `npx`?

**Comment by kamilkisiela** [comment]
I updated the example to have `npx` installed and it works too

**Comment by P4sca1** [comment]
I can't get CodeSandbox to load properly so I can't test your example.

**Comment by kamilkisiela** [comment]
https://codesandbox.io/s/wy21wxrpjk

Does the download button work in there?

This is what codesandbox produced for me: 
https://github.com/kamilkisiela/gql-gen-init

**Comment by kamilkisiela** [comment]
I also added integration tests in #1496

**Comment by P4sca1** [comment]
Here's what I did:

1. Cloned the repo
2. `npm install`
3. `npx gql-gen init`

Still the same issue.
Could it be because I am using oh-my-zsh?

**Comment by kamilkisiela** [comment]
I see why it might not work, did you select an option in the first question? Hitting `space` selects an item but pressing `enter` goes to the next question without selecting anything.

**Comment by kamilkisiela** [comment]
#1500 should prevent it

**Comment by P4sca1** [comment]
I always tried enter to confirm the answer, so that could be the issue very likely. Will check tomorrow.
Maybe it would be good to also allow enter for submitting an answer.
