### ISSUE TITLE
Typescript Enum config no longer working in 1.0

### ISSUE THREAD

**Issue by NickClark** [dotansimha/graphql-code-generator#1495]
**Describe the bug**
Adding a custom enum to the the typescript plugin config no longer works

**To Reproduce**

1. Add an enum to your schema
2. Add a custom enum file
3. Add the mapping to your config

Example project:
[![Edit Broken Custom Enums](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4w0xy04wqx?fontsize=14&module=%2Fcodegen.yml&view=editor)

**Expected behavior**
It should import my custom enum and use it instead of the default generated one.

**Environment:**

- OS: macOS 10.13.6
- Codegen: 1.0.0
- Node: 10

**Comment by dotansimha** [comment]
Hi @NickClark, thank your for reporting this issue.
In 1.0.0, we changed `enums` to `enumValues`. Also, I found a bug in the declaration of it, and the ability to map an existing enum was missing. 
I fixed and added the missing feature here: https://github.com/dotansimha/graphql-code-generator/pull/1518

**Comment by dotansimha** [comment]
Fixed in 1.0.1 🚀

**Comment by NickClark** [comment]
Thanks! I finally seem to have a working setup of 1.0, thanks! This is awesome work!
