### ISSUE TITLE
Add support for custom indention

### ISSUE THREAD

**Issue by altschuler** [dotansimha/graphql-code-generator#150]
It would be very useful to support a custom level of indention in the generated files.

**Comment by dotansimha** [comment]
@altschuler 
Currently my approach is to ignore the indentation issue by adding `tslint:disable` and similar comments. 
The indentation now is part of the template, and I'm not sure there is a quick way to switch between indentation configurations in Handlebars. 

Also, I'm thinking about exposing a clean JS engine besides Handlebars, so we can also write the templates in pure JS code, and it might simplify things like indentation.

What do you think?

**Comment by zephraph** [comment]
You could add a custom formatting step. Let people do a programmatic raw transformation from src to src. It'd be easy to pass the results through prettier or some other formatter then. Along with any other custom transformations that they may need.

**Comment by altschuler** [comment]
I like @zephraph's idea. In general I think you're both right in that it's better to achieve this as part of a more overarching transformation/control than specifically setting indention level.

**Comment by dotansimha** [comment]
@altschuler @zephraph what do you think about integrating [this](https://www.npmjs.com/package/handlebars-helper-prettify) ?

**Comment by zephraph** [comment]
It seems like a bit too narrow of a solution. What if they aren't generating JS? I think the point is that it's hard to anticipate what a user's use case will be for this functionality. 

```bash
gql-gen --file mySchema.json --template typescript --out ./typings/ "./src/**/*.graphql" --formatter ./my/formatter.js
```

The formatter here could just be a module that exports a function. Here's what an example no-op formatter might look like. 

```javascript
export default function formatter(src) {
   return src;
}
```

**Comment by dotansimha** [comment]
Done in: https://github.com/dotansimha/graphql-code-generator/pull/193 
The code will automatically go through prettier, and if you have a prettier local config file, it will use it.

**Comment by altschuler** [comment]
Awesome! :tada:
