### ISSUE TITLE
@graphql-codegen/core has no member generate in 1.0

### ISSUE THREAD

**Issue by defrex** [dotansimha/graphql-code-generator#1503]
**Describe the bug**
I've just upgraded to 1.0. I use the programmatic API, and unfortunately the import isn't valid.

```js
import { generate } from '@graphql-codegen/core' 
```

The above generates:
`Module '"../../node_modules/@graphql-codegen/core/dist/esnext"' has no exported member 'generate'.ts(2305)`

From my `package.json`

```json
    "@graphql-codegen/cli": "^1.0.0",
    "@graphql-codegen/core": "^1.0.0",
    "@graphql-codegen/typescript": "^1.0.0",
    "@graphql-codegen/typescript-operations": "^1.0.0",
    "@graphql-codegen/typescript-react-apollo": "^1.0.0",
```

**To Reproduce**

1. Install 1.0
2. Try to import `generate` from `@graphql-codegen/core`

**Expected behavior**
Access programmatic API.

**Comment by defrex** [comment]
FYI, this is what I'm seeing for `@graphql-codegen/core` after installing locally.
```js
export * from './errors';
export { codegen } from './codegen';
export { executePlugin, ExecutePluginOptions } from './execute-plugin';
export { mergeSchemas } from './merge-schemas';
```
No `generate`

**Comment by defrex** [comment]
Also, I can confirm the CLI is working fine with my config.

**Comment by defrex** [comment]
... and finally, I can confirm that the following works fine.
```js
import { generate } from '@graphql-codegen/cli'
```

**Comment by dotansimha** [comment]
@defrex you can use `codegen` from `@graphql-codegen/core`, or `generate` from `@graphql-codegen/cli`. 
If you don't want to add all the cli dependencies, you can use `core`.
You can find an example here: https://github.com/dotansimha/graphql-code-generator/blob/master/website/live-demo/src/App.js#L85

**Comment by defrex** [comment]
No problem, that's just not what the documentation said. I see it's been updated though, so that's good! However, I believe the docs are still incorrect, even with the change to `codegen`.

[These docs](https://graphql-code-generator.com/docs/getting-started/programmatic-usage) imply you can pass a config directly to `codegen`, but this is the signature I'm seeing for it locally:

```typescript
function codegen(options: {
    filename: string;
    plugins: Types.ConfiguredPlugin[];
    schema: DocumentNode;
    documents: Types.DocumentFile[];
    config: {
        [key: string]: any;
    };
    pluginMap: {
        [name: string]: CodegenPlugin;
    };
}): Promise<string>;
```

As you can see, there is no `generates` field at all, and `schema` & `documents` can't take strings.

**Comment by dotansimha** [comment]
Thanks @defrex , missed that. Opened a new issue: https://github.com/dotansimha/graphql-code-generator/issues/1523
