### ISSUE TITLE
init fails with ENOENT: no such file or directory, open '...\node_modules\@graphql-codegen\cli\dist\package.json'

### ISSUE THREAD

**Issue by Alucardz** [dotansimha/graphql-code-generator#1514]
**Describe the bug**
Running graphql-codegen init via:

1. `npx graphql-codegen init`
2. `node_modules\.bin\graphql-codegen init`
3. `yarn run graphql-codegen init`

(because simply running `graphql-codegen init` doesn't work, gives 'no such command was found')

It initiates the wizard, asks the proper questions, but by the end generates an error and nothing gets generated:

`ENOENT: no such file or directory, open '...\node_modules\@graphql-codegen\cli\dist\package.json'`

It seems to be looking for the project's package.json in the wrong folder.

**To Reproduce**

1. yarn add @graphql-codegen/cli -D
2. Run any of the init commands listed above

**Expected behavior**
I expect the code-gen wizard to work and not throw an error

**Environment:**

- OS: Windows 10
- Codegen: 1.0.0
- Node: 8.12.0

**Comment by kamilkisiela** [comment]
fixed in #1496

**Comment by dotansimha** [comment]
Fixed in 1.0.1 🚀

**Comment by fredericojesus** [comment]
This issue is happening again to me in version 1.8.3 and above. 
If I use version 1.8.2 or below everything works fine, but if I upgrade to 1.8.3 or above I get the error ENOENT: no such file or directory, open ...... 
Are you aware of this issue ?

**Comment by dotansimha** [comment]
@fredericojesus We fixed it, please try latest.
