### ISSUE TITLE
Update programatic usage documentation

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#1523]
As discussed here: https://github.com/dotansimha/graphql-code-generator/issues/1503#issuecomment-474872791

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/commit/31ed540b62d3e26dbb67330aefd520013d95bf73

**Comment by dotansimha** [comment]
Fix available in 1.0.2.

**Comment by dimitar-nikovski** [comment]
Hi, firstly many thanks for all your great work.

The `schema` type for the config in the programatic usage docs is required to be a `DocumentNode` by the referenced [implementation](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/codegen.ts#L7-L16), however in the example in the docs it's the result of `buildSchema` which returns a `GraphQLSchema`.

I couldn't find a way to negotiate these two types and derive a `DocumentNode` from my `GraphQLSchema`. Any advice much appreciated.

**Comment by dotansimha** [comment]
@dimitar-nikovski my bad, just use `printSchema` over the `GraphQLSchema` you are getting from `buildSchema`. Or, you can use `parse` (from `graphql`).

**Comment by dimitar-nikovski** [comment]
Thanks, I did `parse(printSchema(schema))`. Happy to put forward some edits of that page in a PR.

**Comment by dotansimha** [comment]
@dimitar-nikovski go for it!
