### ISSUE TITLE
Use singular instead of plural names for array types

### ISSUE THREAD

**Issue by lukejagodzinski** [dotansimha/graphql-code-generator#1524]
I don't know if it's a bug or expected behavior but for me it looks more like a bug.
I have the GraphQL schema like this one:

```gql
type Query {
  visitorMetrics: [VisitorMetric!]
}

type VisitorMetric {
  date: DateTime!
  value: Int!
}
```

so for `visitorMetrics` query I'm just returning array of `VisitorMetric` objects. And here is what TS types the `graphql-code-generator` generated for me:

```ts
export type Query = {
  __typename?: "Query";
  visitorMetrics: VisitorMetrics[] | null;
};

export type VisitorMetrics = {
  __typename?: "VisitorMetric";
  date: string;
  value: number;
};
```

The "BUG" part for me is naming type `VisitorMetrics` (plural) instead of `VisitorMetric` (singular).

**Environment:**

- OS: MacOS 0.14.3
- Codegen: 0.18.0
- Node: 8.12.0

**Comment by dotansimha** [comment]
@lukejagodzinski in 0.18, we were using the **name of the field** (`visitorMetrics`) for the name of the property, and not the name of the type it's referring to (`VisitorMetric`). If you wish to get a different name, use GraphQL aliases (`visitorMetric: visitorMetrics`).
You can update to 1.0.0 and you'll get better generated code with those additional generated types/namespaces.

**Comment by lukejagodzinski** [comment]
@dotansimha is there any particular reason why you're doing it that way instead of taking type name? It's counter intuitive especially for TypeScript, where we clearly see that it's an array of values.

Oh 1.0 was just released today :) nice

**Comment by dotansimha** [comment]
@lukejagodzinski Because this way we could generate `type` with less conflicts.
The following: 
```graphql
type Something {
  a: SomethingElse
  a: SomethingElse

}
```

**Comment by lukejagodzinski** [comment]
@dotansimha oh I see, that makes sense :) thanks!
I would check how it's done in 1.0.0 but it's still not available through NPM ;)

**Comment by dotansimha** [comment]
@lukejagodzinski it does, we just changed the name of the packages, and we are using scoped packages now. 
Use `@graphql-codegen/cli` instead of `graphql-code-generator`, and `@graphql-codegen/PLUGIN` for plugins.

**Comment by lukejagodzinski** [comment]
@dotansimha Oh I see! That's nice :D Thanks!

**Comment by kaminskypavel** [comment]
any advice on this? im on `"@graphql-codegen/cli": "1.19.4"` , and codegen generates `Users`

so 
```	
query {
		users {
			id
                        .....
		}
	}
```

is resolved with 

```
       type QueryResult = {
            users: Users[] (!!)
        };
```

is there's anything I can configure?

**Comment by dotansimha** [comment]
We don't support that at the moment. You can use fragments and name it based on your preference.
