### ISSUE TITLE
[TypeScript Resolvers] mappers don't apply for interfaces

### ISSUE THREAD

**Issue by ardatan** [dotansimha/graphql-code-generator#1525]
schema
```graphql
interface User {
   ...
}
```
codegen.yml
```yml
mappers: 
       User: ./entities/UserEntity#UserEntity
```

Generates:
```
export type UserResolvers<Context = ModuleContext, ParentType = User> = {
```

Expected:
```
export type UserResolvers<Context = ModuleContext, ParentType = UserEntity> = {
```

**Comment by dotansimha** [comment]
I think already been fixed. Added a test: https://github.com/dotansimha/graphql-code-generator/commit/191895100153641bb60d1390f13f88f1aecade7a

@ardatan ?

**Comment by kgtkr** [comment]
The same bug exists in Subscription

**Comment by dotansimha** [comment]
Fixed in 1.0.4

**Comment by kgtkr** [comment]
Why doesn't mappers apply to child elements of type whose mappers are not set?

**Comment by dotansimha** [comment]
@kgtkr  can you please add an example?

**Comment by kgtkr** [comment]
```
type A{
  x:B!
}

type B{
  ...
}

mappers: 
       B: B2

export type AResolvers<Context = ModuleContext, ParentType = {x:B2}> = {
```

**Comment by dotansimha** [comment]
The current default types are the types that `typescript` package is generating. If you wish to point to a specific parent type of A, you can do: 

```
type A{
  x:B!
}

type B{
  ...
}

mappers: 
       A: "{ x: B2 }"
```

**Comment by kgtkr** [comment]
Is it difficult to do this automatically?
In this method, rewriting is necessary when the number of properties increases, etc.

**Comment by dotansimha** [comment]
@kgtkr It's not that simple. Me and @kamilkisiela talked about it before. It requires to generate complete new type, and not using the base type generated by `typescript` plugin.
