### ISSUE TITLE
[TypeScript Resolvers] defaultMapper: any doesn't work anymore

### ISSUE THREAD

**Issue by danielbischoff** [dotansimha/graphql-code-generator#1526]
**Describe the bug**
If you set the property
```
generates:
  src/generated/graphql.ts:
    config:
      defaultMapper: any
```
any is not used for non mapped (return) values. Instead it uses the generated type.

Behavior described here:

> Every other, not mapped type follows the default convention, so in order to overwrite it you can use the defaultMapper option

https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers-overwrite-parents-and-resolved-values

**To Reproduce**
Add `defaultMapper: any` to config and generate code.

**Expected behavior**
For every type not specified in the mapping config, it should take any as the value and not the generated type

**Environment:**

- OS: Mac OS
- Codegen: 1.0.2
- Node: 10.15.0

**Comment by dotansimha** [comment]
Fixed in 1.0.3
