### ISSUE TITLE
Custom Scalars?

### ISSUE THREAD

**Issue by garrettm** [dotansimha/graphql-code-generator#153]
In Typescript, custom scalar types are emitted like:

```ts
export type Foo = any;
```

How can I make the emitted Foo refer to my existing types?

For example, if somewhere else in my code base, I have:
```ts
class Foo {
  bar: string

  someMethod() {
    ...
  }
}
```

I know this supports templating, but even with templating, I'm not sure how to make Foo in the generated types refer to my project's Foo.  It seems like I'd need to import existing scalar definitions into my schema template?  Or I'd need to define all my custom scalars in templates?  Both of these sound pretty unmaintainable.  Is there some convenient way to do this?  Or is there an example for solving this sort of problem?

PS. Thank you for this package!

**Comment by dotansimha** [comment]
@garrettm 
I think we can add a custom configuration per each generator, and pass it via `gql-gen.json` config file. this way we can add custom scalars mapping (and also an import from the file that contains the interface).

What do you think?

**Comment by garrettm** [comment]
Correct me if I'm wrong, here's what I'm imagining, given what you said:

- add an option for extern definitions of scalars
- if set, gql-gen adds extra emits:

```ts
import * as Extern from './extern'
```

```ts
export type ScalarName = Extern.ScalarName
```

The user can export scalar types from this `extern.ts` file, and the TS compiler will complain if you forget one.

**Comment by dotansimha** [comment]
@garrettm yeah it makes sense. 
I'm currently working on the generator-specific configuration, and then we will be able to implement this feature

**Comment by garrettm** [comment]
@dotansimha sounds good.  If you're interested in letting someone else do the work, point me in the direction when ready and I can take a look.

**Comment by FredyC** [comment]
I am curious if there is any progress on this? Would love to be able specify types for my scalars :)

**Comment by pleerock** [comment]
@dotansimha facing same issue here. In my case I have a simple scalar `Date` and I would like to avoid generator to add `export type Date = any;` in the output since I already have a Date object globally available.

**Comment by dotansimha** [comment]
I see, @pleerock . I am thinking about the right solution for this.

We can easily pass custom configuration, so maybe a map like that:
```
{
    config: {
        scalars: [
             { scalar: "Date", type: "Date" }
        ]
    }
}
```

And if you want to use a custom TypeScript type you wrote, for example: `MyDateType` and map it to a specific GraphQL Scalar, we might need `import` as well:

```
{
    config: {
        scalars: [
             { scalar: "Date", type: "MyDateType", import: "../../types/my-date-type" }
        ]
    }
}
```

And it will also add the import on top of the file.

What do you think?

**Comment by pleerock** [comment]
It will definitely resolve most of issues.

**Comment by jonaskello** [comment]
I like the typescript solution. I actually came across a a use-case with scalars today that it would solve. My other idea was to patch the generated code to add an import and replace the generated type alias with a regex, but this solution is of course much nicer :-).

One note about the import. Lets say you want to do a named import, how would that work? Perhaps something like this could work:

```
{
    config: {
        imports: ["import {MyDateType}" from "../datelib", import {MyFooType} from "../foolib" ]
        scalars: [
             { scalar: "Date", type: "MyDateType"},
             { scalar: "Foo", type: "MyFooType"}
        ]
    }
}
```

**Comment by dotansimha** [comment]
@jonaskello yeah you are right, your examples supports more use cases (such as names import, default import or any other way).

**Comment by Slessi** [comment]
For query/mutation code generation, I use [apollo-cli](https://github.com/apollographql/apollo-cli#apollo-codegengenerate-output), which has the flag `--customScalarsPrefix` when using `codegen`

```ts
// with --customScalarsPrefix=GQL
interface SomeType {
    date: GQLDate;
}
```

`GQLDate` will not be exported in the generated types, and I keep a separate `.d.ts` with

```ts
declare type GQLDate = Date;
```

**Comment by Slessi** [comment]
@dotansimha Since new #444 was released, there seems to be an issue with  my JSON scalar type.

schema
```gql
scalar JSON

type foo {
  bar: JSON!
}
```
generated types
```ts
export type JSON = any; //  as before

export interface foo {
  bar: Json; // not as before
}
```

I'm aware of the new `scalars` option for `gql-gen.json` but this doesn't help me as it results in the following
```ts
export type JSON = MyFancyType; // ok

export interface foo {
  bar: Json; // Json != JSON
}
```

**Comment by kamilkisiela** [comment]
I published a canary version: `0.11.0-alpha.4c054a57`

Could you check if it works for you?

> Successfully published:
>  - graphql-code-generator@0.11.0-alpha.4c054a57
>  - graphql-codegen-compiler@0.11.0-alpha.4c054a57
>  - graphql-codegen-core@0.11.0-alpha.4c054a57
>  - codegen-templates-scripts@0.11.0-alpha.4c054a57
>  - graphql-codegen-introspection-template@0.11.0-alpha.4c054a57
>  - graphql-codegen-typescript-mongodb-template@0.11.0-alpha.4c054a57
>  - graphql-codegen-typescript-react-apollo-template@0.11.0-alpha.4c054a57
>  - graphql-codegen-typescript-template@0.11.0-alpha.4c054a57

**Comment by elie222** [comment]
Is this still waiting for release?

**Comment by jonaskello** [comment]
@elie222 You can use [ScalarsMap](https://graphql-code-generator.com/docs/plugins/typescript#scalars-scalarsmap) now.

**Comment by teebszet** [comment]
> @teebszet yes, but note that you can't really send JS `Date` over the network, so it will probably get serialized and you'll get it as `string` in the client, so the server can use JS `Date`, but the client will get `string`.

@dotansimha yeah that makes sense. I guess it would be up to the typescript-apollo-angular plugin to initialise those DateTime fields as Date objects in the client. But I'm not sure if that is a feature that exists or not

**Comment by dotansimha** [comment]
@teebszet I think it should be done in Apollo client, during the runtime, and then you can reflect the status of data by using custom scalars in the codegen. 
I think you can do that with Apollo Link.

**Comment by FredyC** [comment]
@dotansimha Do you have some useful resources on how it can be done universally with Apollo Link? 

I've found this pretty old (but still active) [feature request for Apollo client](https://github.com/apollographql/apollo-feature-requests/issues/2) and it almost seems like it's still not possible. It would be really lovely to get ISO date automatically parsed and converted and along with correct typings, it would be a breeze.

This has especially become an issue with date-fns v2 which no longer supports passing a string. Only a `Date` or `number`. It's definitely fairly tedious doing that manually whenever there is a need to work with field that contains a stringified date.

**Comment by Slessi** [comment]
@FredyC use [parseISO](https://date-fns.org/v2.4.1/docs/parseISO)

 >The previous `parse` implementation was renamed to `parseISO`.

**Comment by finaxar-arthur** [comment]
Can anyone update on this? I am still not able to convert custom scalars. This is my `codegen.yml` but it doesn't work.

```
overwrite: true
schema: 'schema.graphql'
generates:
  src/generated/graphql.tsx:
    config:
      scalars:
        Long: number
        BigDecimal: number
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
      - 'typescript-graphql-files-modules'
      - 'typescript-document-nodes'
      - 'fragment-matcher'
  ./graphql.schema.json:
    plugins:
      - 'introspection'
```

**Comment by ardatan** [comment]
@finaxar-arthur What do you mean by converting custom scalars? If you have any issues, could you please create a new issue with a minimal reproduction?

**Comment by JCMais** [comment]
@finaxar-arthur the config must be at the top, like
```yaml
overwrite: true
schema: 'schema.graphql'
config:
  scalars:
    Long: number
    BigDecimal: number
```

**Comment by Rockson** [comment]
Is there an example on how to configure custom scalars mapping them to custom types?

**Comment by dotansimha** [comment]
> Is there an example on how to configure custom scalars mapping them to custom types? How do you specify where should the custom types be imported from?

You can use mappers format for scalars, we use it in other places as well, should look like that:

```
generates:
  types.ts:
    config:
      scalars:
        Date: "my-file#MyType"
    plugins:
      - typescript
```

**Comment by elie222** [comment]
Would it make sense to default to this:

```yml
scalars:
  DateTime: "string | Date"
```

Instead of `any`?

**Comment by nandorojo** [comment]
> > Is there an example on how to configure custom scalars mapping them to custom types? How do you specify where should the custom types be imported from?
> 
> You can use mappers format for scalars, we use it in other places as well, should look like that:
> 
> ```
> generates:
>   types.ts:
>     config:
>       scalars:
>         Date: "my-file#MyType"
>     plugins:
>       - typescript
> ```

@dotansimha I'm new to this plugin, could you share what `my-file` looks like?

**Comment by prichodko** [comment]
@nandorojo it could be just a simple TypeScript file that exports a type which name you would use behind `#`.

For example:
```ts
// file: my-custom-type.ts

export type MyCustomType =  {
   id: string
}
```

then in codegen.yml you could do:
```yaml
generates:
  types.ts:
    config:
      scalars:
        Date: "path/to/file/my-custom-type#MyCustomType"
```

**Comment by tjmgregory** [comment]
Noticing that this doesn't work for the `typescript-operations` plugin - it works for the root generated file made by the `typescript` plugin, but for each file made by `typescript-operations` with `preset: near-operation-file`, it sets the field to the type correctly, but it forgets to import it from the mapped location.

**Comment by prichodko** [comment]
@tjmgregory that's actually true. I ended up declaring the type globally.

```
declare global {
  declare type JsonObject = Prisma.JsonObject
}
```

**Comment by credcore-dave** [comment]
> > Is there an example on how to configure custom scalars mapping them to custom types? How do you specify where should the custom types be imported from?
> 
> You can use mappers format for scalars, we use it in other places as well, should look like that:
> 
> ```
> generates:
>   types.ts:
>     config:
>       scalars:
>         Date: "my-file#MyType"
>     plugins:
>       - typescript
> ```

I know resurrecting old issues is frowned upon but I stumbled on this issue needing to do exactly this today and I have to say it's an extremely powerful feature for a certain class of problems, so thank you so much for implementing it.

**Comment by hypeJunction** [comment]
@tjmgregory I was able to fix the issue by adding the path to scalar types to `tsconfig.json` under `compilerOptions.types`
