### ISSUE TITLE
Watch doesn't work for negative glob matches

### ISSUE THREAD

**Issue by NickClark** [dotansimha/graphql-code-generator#1530]
**Describe the bug**
Saving a file doesn't re-generate the outputs when the glob includes a negative matcher

**To Reproduce**
Set the documents or schema config to include something like: `src/!(generated)/**/!(schema).graphql`

**Expected behavior**
It should re-generate the outputs

**Environment:**

- OS: 10.13.6
- Codegen: 1.0.1
- Node: 10

**Comment by dotansimha** [comment]
In this case, I think it might also be related to this (because you are trying to avoid watching the generated files?): https://github.com/dotansimha/graphql-code-generator/issues/1537. @ardatan is working on a fix for it. 

Regarding the glob expression, we are using `chokidar` for watching the file-system, and I think it has a known issue: https://github.com/paulmillr/chokidar/issues/740

**Comment by NickClark** [comment]
Ya. I'm trying to do two things. 1. Ignore generated GraphQL files. 2. Make the document config section not include schema files, and visa versa. My ideal was going to ultimately be all files with a `-schema.graqhql` postfix or in a `schema/` directory would be schema, and all other files with a `.graphql` extension would be considered documents. 

The main two issues I've run into with this so far: 
1. I can't negatively match for the document case
2. I can't be proactive and add the rule including documents nested under `schema/` until my project contains at least one such case. Not a big issue, but definitely prevents me from porting my config between projects. (although, just commenting for now is sufficient ;D )

**Comment by ardatan** [comment]
@NickClark I am working on ignoring generated files #1558 and codegen already ignores schema definition files as I know, doesn't it? @dotansimha 
https://github.com/ardatan/graphql-toolkit/blob/f0f6fd00fabe1ffc867b2a649aca8761fbe96527/tests/loaders/documents/documents-from-glob.spec.ts#L76

**Comment by dotansimha** [comment]
@NickClark, I recently merged @ardatan's fix for ignoring the generated files.
Also, the codegen knows to detect each document and skip if if it's not relevant, so no need to worry about separating those files.
Alternatively, you can use `.graphqls` for schema files and `.graphql` for operations.

**Comment by dotansimha** [comment]
Fixed in 1.0.4. @NickClark feel free to re-open if you think it's not resolved.

**Comment by NickClark** [comment]
Ok. So everything seems to work now, even when using a looser config like: 

```
documents:
  - src/client/**/*.graphql
schema:
  - src/client/**/*.graphql
```

But this generates alot of 
`File "[PATH_OF_PARTICULAR_FILE]-schema.graphql" was filtered because it contains an invalid GraphQL document definition! types of errors.

Is this intended? Seems quite noisy for intended behavior.

Thanks again for your guys work! It been so nice seeing you fixing these issues so well and quickly! Kudos! 🎆

**Comment by dotansimha** [comment]
@NickClark it's intended because we would to let you know that the codegen loads file that it shouldn't. 
I recommend to use `.graphqls` for schema files if they are in the same directory. It's supported by all IDEs and tools,
