### ISSUE TITLE
Release js-yaml

### ISSUE THREAD

**Issue by simPod** [dotansimha/graphql-code-generator#1541]
Hi @dotansimha can you please release a new version that has this commit included https://github.com/dotansimha/graphql-code-generator/commit/110961cd5a92a1d3ad751f18ce8c65e70c515553? As ^ is not used for version definition, it forces js-yaml 3.12.2 which contains security vulnerability https://www.npmjs.com/advisories/788

Thanks!

**Comment by dotansimha** [comment]
On it now, will be available in a few minutes :)

**Comment by dotansimha** [comment]
1.0.3 available. @simPod

**Comment by simPod** [comment]
Respect brother! Thanks a lot! 👌
