### ISSUE TITLE
Generated components, hooks and HOCs contain typesPrefix

### ISSUE THREAD

**Issue by jeroenvisser101** [dotansimha/graphql-code-generator#1550]
**Describe the bug**
When using `typesPrefix: I` and when generating components, documents, hooks or HOCs, it also adds the type prefix to their names.

**To Reproduce**

1. Configure any project with queries, mutations and/or subscriptions to generate components, hooks or HOCs, and configure with `typesPrefix: I`

**Expected behavior**
I expected typesPrefix to prefix all type exports, but to leave other exports unchanged.

**Environment:**
- Codegen: 1.0.3

**Comment by jeroenvisser101** [comment]
@dotansimha it seems my PR wasn't completely working so I got a few more coming, but since names are sometimes passed along and used as parts of a composite name, it's not immediately clear what parts are affected.

**Comment by jeroenvisser101** [comment]
I was also having trouble testing it in a project locally using yarn link, since visitor-plugin-common has a devDependency on `graphql`, which conflicts.

**Comment by dotansimha** [comment]
@jeroenvisser101 Thank you for your contributions! 
Regarding working locally, you can use `npm pack` inside a package, create a `tar.gz` file and then install it locally in order to test it. Or, you can use the unit tests which should cover most of the test cases.

**Comment by dotansimha** [comment]
Fixed in 1.0.4
