### ISSUE TITLE
Add new template or config option to `apollo-react` to support `urql`

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#1575]
Please consider adding a special template or config for `apollo-react` generator to support
https://github.com/FormidableLabs/urql/
It's quite popular and will be nice to have.

**Comment by mxstbr** [comment]
Yes please, we really need this! I am starting to dig into this, will open a WIP PR soon.

cc @kitten the main maintainer of urql

**Comment by dotansimha** [comment]
Thank you @mxstbr !  Your PR is merged, and if someone wants to try it before the stable release, you can use `1.1.4-alpha-b8bdef27.12`. 
(also, keeping open until we'll release a new version)

**Comment by dotansimha** [comment]
Available in `1.2.0`. Thanks @mxstbr !
