### ISSUE TITLE
rxjs map operator does not infer type

### ISSUE THREAD

**Issue by darkbasic** [dotansimha/graphql-code-generator#158]
![map_does_not_infer_type](https://user-images.githubusercontent.com/1047358/32222522-d9672f4a-be39-11e7-919a-a8d1d3af9b61.png)

Test code: https://github.com/darkbasic/angularcli-graphql
`/src/app/apollo/apollo.component.ts`

**Comment by dotansimha** [comment]
Did you try to use `ApolloQueryObservable<..>` instead of `Observable<ApolloQueryResult<...>>`? 

Also, if it does not work, I would expect the `result.data.allMembers` to be marked as syntax error... 

@darkbasic

**Comment by darkbasic** [comment]
> Did you try to use ApolloQueryObservable<..> instead of Observable<ApolloQueryResult<...>>?

No, because I'm using apollo-client 2.0 and AFAIK I am supposed to use Observable<ApolloQueryResult<...>> with latest version:

```
export class QueryRef<T> {
  public valueChanges: Observable<ApolloQueryResult<T>>;
```

> Also, if it does not work, I would expect the result.data.allMembers to be marked as syntax error...

Webstorm has several ways to infer types (it also looks for the text string to see if it has been used elsewhere, etc..), but if you CTRL + mouse hover on `result` it clearly shows that it's of type `any`:

![map_does_not_infer_type_2](https://user-images.githubusercontent.com/1047358/32223024-f62b6482-be3b-11e7-9e76-e04261d54d48.png)

**Comment by dotansimha** [comment]
@darkbasic maybe it's because of the `map` usage? 
The signature of `map` in `rxjs` is: 
```ts
export function map<T, R>(this: Observable<T>, project: (value: T, index: number) => R, thisArg?: any): Observable<R> {
  return higherOrderMap(project, thisArg)(this);
}
```

Did you try to add the output type as generic for `map`?

**Comment by darkbasic** [comment]
> Did you try to add the output type as generic for map?

If you mean something like
```typescript
const a = query.valueChanges.map<ApolloQueryResult<AllMembers.Query>, AllMembers.AllMembers[]>(result => result.data.allMembers);
```
it indeed works, but why should I need to specify something like that? It should be able to automatically infer it, in fact it already knows that `query.valueChanges` returns `Observable<ApolloQueryResult<AllMembers.Query>>`:

![map_does_not_infer_type_3](https://user-images.githubusercontent.com/1047358/32230130-c1a7d4d6-be52-11e7-8d3b-2e23dc0926ed.png)

With apollo-client 1.x it already worked that way.

**Comment by darkbasic** [comment]
![map_does_not_infer_type_5](https://user-images.githubusercontent.com/1047358/32231327-9248db24-be55-11e7-81ec-eca99c397c87.png)

![map_does_not_infer_type_4](https://user-images.githubusercontent.com/1047358/32231330-95396772-be55-11e7-96f2-b6f2627d3d7f.png)

Uhm... that's strange, maybe it's a bug in Webstorm?

**Comment by darkbasic** [comment]
https://youtrack.jetbrains.com/issue/WEB-29502

If you use Webstorm please vote for this issue.

**Comment by dotansimha** [comment]
@darkbasic , it makes sense. Also, which version of `typescript` do you use? And which version is in use in WebStorm settings?

**Comment by darkbasic** [comment]
2.4.2

**Comment by dotansimha** [comment]
@darkbasic same for me, with 2.5/2.6.
I guess that it's a WebStorm issue. 
Do you think we can close the issue?

**Comment by darkbasic** [comment]
Yes I think so. Thanks.
