### ISSUE TITLE
Type "DateTime" gives an error in variables type

### ISSUE THREAD

**Issue by chengjia0807** [dotansimha/graphql-code-generator#1581]
There is a type error when I generated the DateTime type.

Here is the generated code:

```export type GetBookedLessonsQueryVariables = {   from: DateTime;   to: DateTime;   bookingStage?: Maybe<BookingStages>;   bookingStatus?: Maybe<BookingStatuses>;   paymentStatus?: Maybe<PaymentStatuses>;   lessonStatus?: Maybe<LessonStatuses>; };```

Type "DateTime" is not existing at all.

I guess the correct item should be 'Scalars["DateTime"]'  or use "Date" in Javascript

Please look into it  👍 

Thanks
CJ

**Comment by dotansimha** [comment]
Hi @chengjia0807 , thank you for reporting it. 
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/1582

**Comment by dotansimha** [comment]
@chengjia0807 fixed in 1.0.6 :)

**Comment by chengjia0807** [comment]
> @chengjia0807 fixed in 1.0.6 :)

Thank you so much for your quick fix 👍 👍
