### ISSUE TITLE
 Online live demo website:  GraphQLDocumentError: Unknown directive "client"

### ISSUE THREAD

**Issue by fooraiyz** [dotansimha/graphql-code-generator#1588]
**Describe the bug**

I am trying to get an understanding of how the graphql-codegen works with the @client directive.

However, when I try the online code generator https://graphql-code-generator.com and use the @client directive, the following error occurs.

GraphQLDocumentError:  Unknown directive "client". at undefined:4:16

**To Reproduce**

1. My GraphQL schema:

```graphql
scalar Date

schema {
  query: Query
}

extend type User{
  isLoggedIn: Boolean!
}

type Query {
  me: User!
  user(id: ID!): User
  allUsers: [User]
  search(term: String!): [SearchResult!]!
  myChats: [Chat!]!
}

enum Role {
  USER,
  ADMIN,
}

interface Node {
  id: ID!
}

union SearchResult = User | Chat | ChatMessage

type User implements Node {
  id: ID!
  username: String!
  email: String!
  role: Role!
}

type Chat implements Node {
  id: ID!
  users: [User!]!
  messages: [ChatMessage!]!
}

type ChatMessage implements Node {
  id: ID!
  content: String!
  time: Date!
  user: User!
}
```

2. Documents:

I have added a @client property to the findUser query

```graphql
query findUser($userId: ID!) {
  user(id: $userId) {
    ...UserFields
    isLoggedIn @client
  }
}

fragment UserFields on User {
  id
  username
  role
  
}
```

3. Config

```yml
generates:
  components.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
```

**Expected behavior**

The relevant types and the FindUserGQL class to be created. 

**Environment:**

Online generator @ https://graphql-code-generator.com/

**Comment by dotansimha** [comment]
Hi @fooraiyz ,
The `@client` directive is only a declarative directive that being removed during runtime by `apollo-client`, and it's not part of the codegen, or GraphQL in general.
If you wish to use it, make sure to add the following to your schema:

```
directive @client on FIELD
```

**Comment by fooraiyz** [comment]
Hi @dotansimha ,

Thanks for the prompt reply and your advice.  I have been trying to work this out but am struggling.

In the Apollo docs [concerning local state management](https://www.apollographql.com/docs/angular/basics/local-state#combine-data) they state

> What’s really cool about using a @client directive to specify client-side only fields is that you can actually combine local and remote data in one query.

Given what you have said, does this mean that it is not possible to achieve this using the 'graphql-code-generator?  In other words, to use it you have to give up strong typing?

Also was this previously possible in the pre 1.0 version?

Thanks.

**Comment by dotansimha** [comment]
@fooraiyz Sorry, I don't understand what's the issue here.
If you are using client-side local state with Apollo, you need to have 2 schemas: the remote schema, and the client-only schema. 
The live-demo on the website allow you to write only 1 schema for test-purposes, but you can specify multiple schemas when you are using the codegen from the cli in your project.
Please see the docs: https://graphql-code-generator.com/docs/integrations/apollo-local-state

**Comment by fooraiyz** [comment]
@dotansimha Thank you for your time and patience.  I understand now.   I am really appreciative of your help.
