### ISSUE TITLE
Generator can't convert empty object literal to AST

### ISSUE THREAD

**Issue by slikts** [dotansimha/graphql-code-generator#1597]
**Describe the bug**
 
Empty object literal as a default value produces the following error at the Generate step: `TypeError: Cannot convert value to AST: {}`

**To Reproduce**
Repo with minimal example: https://github.com/slikts/gql-gen-default-value-issue/
```
git clone git@github.com:slikts/gql-gen-default-value-issue.git
cd gql-gen-default-value-issue
npm i
npx gql-gen
```

GraphQL schema:

```graphql
scalar Bar

input Foo {
  bar: Bar = {}
}
```

**Environment:**

- OS: macOS 10.13.6
- `@graphql-codegen/...`: 1.0.4
- NodeJS: 11.9.0

**Comment by dotansimha** [comment]
@slikts , thank you for reporting it, I'll take a look soon.

**Comment by dotansimha** [comment]
I managed to reproduce it. The method `printSchema` from `graphql` is expecting each scalar to be serializable, and by providing only `scalar A` (with the GraphQLScalarType object), makes it impossible to print.

We can use `printSchemaWithDirectives` from `graphql-toolkit` that should handle this case as well. 
I'll check and update.

**Comment by dotansimha** [comment]
@slikts I tested it and it's not simple to avoid this error without building the schema correctly. 
I think the easiest solution for you at the moment is to build your schema manually with your `scalar` resolvers, and let GraphQL Modules load that schema. Make sure to implement `serialize` method for the scalar resolvers:

```
        Bar: {
          serialize: (v) => {
            return JSON.stringify(v);
          }
        }
```

@ardatan @kamilkisiela what do you think?

**Comment by josegoval** [comment]
Any news about this? 

I'm getting the same error.
