### ISSUE TITLE
Flow template

### ISSUE THREAD

**Issue by blackxored** [dotansimha/graphql-code-generator#160]
Where's Flow support and how we can contribute to that?

**Comment by zephraph** [comment]
So, when the last major refactor happened the flow work wasn't ported over. If you want to help, checkout the graphql-code-generators package. It has [typescript-single-file](https://github.com/dotansimha/graphql-code-generator/tree/master/packages/graphql-codegen-generators/src/typescript-single-file) and [typescript-multi-file](https://github.com/dotansimha/graphql-code-generator/tree/master/packages/graphql-codegen-generators/src/typescript-multi-file) setups. Copying those and tweaking things for flow is where I would start.

**Comment by blackxored** [comment]
See #161

**Comment by dotansimha** [comment]
WIP here: https://github.com/dotansimha/graphql-code-generator/pull/917

**Comment by dotansimha** [comment]
Available since 0.15.0 :)
