### ISSUE TITLE
Feature request: run prettier on generated code

### ISSUE THREAD

**Issue by blackxored** [dotansimha/graphql-code-generator#163]
[Prettier](https://github.com/prettier/prettier) has programmatic support and it would be handy to run this before writing the file so we don't end up with very large comment and overall the code is
properly formatted. 
I could add initial support (without custom config) if this is something that people would like.

EDIT: related to #150.

**Comment by dotansimha** [comment]
Yeah it's related to https://github.com/dotansimha/graphql-code-generator/issues/150 , and I think that I will go with @zephraph  idea (see his comment there). What do you think, @blackxored ?

**Comment by blackxored** [comment]
IMHO prettier should be the default. Ability to override it with a custom formatter should be weirdly needed (I can only think for languages that prettier doesn't support, and for people that don't like prettier (even after being able to customize its config). If we have a way to know which generator language was used (or setup a `formatterOptions` or `formatterLanguage` or just `language`) then we can invoke it with the approppiate parser. What do you think?

**Comment by dotansimha** [comment]
Done in: https://github.com/dotansimha/graphql-code-generator/pull/193 
The code will automatically go through prettier, and if you have a prettier local config file, it will use it.

**Comment by dotansimha** [comment]
Available in 0.8.19 :)
