### ISSUE TITLE
Suggestion: Allow __typename in types returned by resolvers

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#1633]
**Is your feature request related to a problem? Please describe.**

When working with resolvers that returns an union type there is a need to resolve the concrete type. Graphql supports [several ways](https://stackoverflow.com/a/53082574/2761797) to do this. One way is the `__resolveType` function. However there is also a built-in default implementation of the `__resolveType` function  which will check the `__typename` property of the returned value. This is convinient and allows us to write resolvers like this without having to implement `__resolveType` ourselves:

```ts
  async resolverThatReturnsUnionType(parent, args ctx) {
    return {
      __typename: "MyConcreteType",
      myprop: 1
    } as any; // any required becuase generated types does not include __typename
  },
```

However the generated types for resolvers does not allow `__typename` to be included. 

**Describe the solution you'd like**
I propose that `__typename` is included in an optional fashsion for these types, same as for operation types.

**Describe alternatives you've considered**
I could add a lot of mappers and add the `__typename` field, but since this functionality is built-in to `graphql` I think it should also be built-in for the type generator tool.

**Comment by jonaskello** [comment]
Ideally, the optional `__typename` field could be added to the raw schema types generated by the `typescript` plugin. That would solve the above and also my more unusual use-case mentioned [here](https://github.com/dotansimha/graphql-code-generator/issues/1350#issuecomment-467345175).

This change would be non-breaking if the `__typename` field is generated as optional. I guess the `typescript` plugin could have a setting for this if people really don't want it generated.

**Comment by jonaskello** [comment]
These are the use-cases for `__typename` that I currently know of:

1. You can ask for `__typename` in an operation sent to the server.
2. You can use `__typename` in resolvers for resolving types of union and interfaces instead of `__resolveType`.
3. You can use `__typename` to construct an unique ID for a normalized cache (I think apollo allows you to construct your own ID like this).

Given that the above use-cases spans across `typescript-operations` and `typescript-resovlers` I think it would make sense to include `__typename` in the base types generated by the `typescript` plugin.

I could work on a PR for this if it would be accepted.

**Comment by leebenson** [comment]
👍 for this. We have a ton of code that branches based on a union's/interface's returned `__typename`, and being able to select that as a first-class field gives this parity with the GraphQL spec.

Currently, we're working around this by having a concrete field called `type` that returns the same thing, but that's redundant since it's being auto-generated by our GraphQL server.

**Comment by CameronFletcher92** [comment]
Would it be feasible to add support for the `skipTypename` config option to the base @graphql-codegen/typescript plugin, and just have it default to `true`?

Same as how it's provided to the operations plugin?
https://graphql-code-generator.com/docs/plugins/typescript-operations#skiptypename-boolean-default-value-false

**Comment by jefflewis** [comment]
I opened a PR to add `__typename` to the base types. Any chance this will get merged/published soon?

**Comment by dotansimha** [comment]
Implemented in: https://github.com/dotansimha/graphql-code-generator/pull/1701 , we can close this one :)
