### ISSUE TITLE
HOC signature uses union with undefined instead of optional parameters

### ISSUE THREAD

**Issue by slikts** [dotansimha/graphql-code-generator#1665]
Currently the HOC signature is generated with `| undefined` for the optional parameter:
```
export function withCreateFoo<TProps, TChildProps = {}>(
  operationOptions:
    | ReactApollo.OperationOption<
        TProps,
        CreateCurrencyMutation,
        CreateCurrencyMutationVariables,
        CreateCurrencyProps<TChildProps>
      >
    | undefined
) {
```
The result is that calling `withCreateFoo()` is an error: `Expected 1 arguments, but got 0.` The workaround is to call it as `withCreateFoo(undefined)`, which doesn't look good.

**Environment:**

- `@graphql-codegen/...`: 1.0.7

**Comment by dotansimha** [comment]
Fixed in `1.1.0` 🚀
