### ISSUE TITLE
Set HOC config.alias to improve debuggability

### ISSUE THREAD

**Issue by slikts** [dotansimha/graphql-code-generator#1672]
[config.alias] in react-apollo docs.

Currently the generated HOCs don't set any options, but it would be useful if `config.alias` was set because it improves the representation of the HOC in React DevTools.

When the alias is left as default, the wrapped components are named `Apollo(WrappedComponent)`, while setting the `alias` could make them look like `withHocName(WrappedComponent)`.

[config.alias]: https://www.apollographql.com/docs/react/api/react-apollo#graphql-config-alias

**Comment by dotansimha** [comment]
Fixed in 1.1.1 🎉
