### ISSUE TITLE
react-apollo should be configurable like hooksImportFrom

### ISSUE THREAD

**Issue by slikts** [dotansimha/graphql-code-generator#1675]
There are issues with `react-apollo` such as the `withMutation` HOC [missing error and loading states][issue], and working around these issues requires, e.g., adding an another HOC. It would provide better usability if it were possible to override the import path like it is with `hooksImportFrom`.

[issue]: https://github.com/apollographql/react-apollo/issues/421

**Comment by dotansimha** [comment]
Fixed in `1.1.0` 🚀
