### ISSUE TITLE
[TypeScript Compatibility] Doesn't work with non-default Query type

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#1679]
https://github.com/dotansimha/graphql-code-generator/issues/1602#issuecomment-481142287

**Comment by cdupuis** [comment]
Thanks @dotansimha, I'm confident that we have a good upgrade story once this is in.

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/commit/c83eba157269ce8778d80eeb33a2425c740c9c7e

**Comment by cdupuis** [comment]
This is working great now. Thanks.

**Comment by dotansimha** [comment]
Fixed in `1.1.0` 🚀
