### ISSUE TITLE
Use npx

### ISSUE THREAD

**Issue by brikou** [dotansimha/graphql-code-generator#168]
Hey, it would be great to support `npx gql-gen`. This way you don't have to install it globally (or locally) for a single shot.

Great job :+1:

**Comment by FredyC** [comment]
Just my two cents. With Yarn, you already have this feature included by default ... `yarn gql-gen` ;) I understand, it's not always viable to use Yarn, but this is not very well known feature imo.

**Comment by dotansimha** [comment]
Just tested the latest version of the codegen with the latest version of npx and it works :)

@FredyC got a good point, Yarn has a built-in `npx` ;)
