### ISSUE TITLE
Custom gql-tag import won't work from 1.0

### ISSUE THREAD

**Issue by azazdeaz** [dotansimha/graphql-code-generator#1680]
**Describe the bug**
custom `gql-tag` imports won't be recognised in 1.0

**To Reproduce**
use a reexported `gql-tag` or [`tagged-template-noop`](https://www.npmjs.com/package/tagged-template-noop)

```ts
import gql from 'tagged-template-noop'
serverSideQuery(gql`query { foo }`) // the condegen won't find this operation because gql is not from `gql-tag`
```

**Expected behavior**
Create the types for every gql operation tagged with anything called `gql`

**Environment:**

- `"@graphql-codegen/cli": "^1.0.6"`
- `"@graphql-codegen/typescript": "^1.0.6"`
- `"@graphql-codegen/typescript-operations": "^1.0.6"`

I didn't find any option or workaround in the docs for this. Did i miss something?

**Comment by dotansimha** [comment]
Hi @azazdeaz , I'm note sure it's related to 1.0. We are using `graphql-tag-pluck` before 1.0 to extract document from code files. 
If you wish to use custom `gql` tag, you need to specify `pluckConfig`, see my comment here: https://github.com/dotansimha/graphql-code-generator/issues/1555#issuecomment-476212983
