### ISSUE TITLE
export introspection to report errors

### ISSUE THREAD

**Issue by OneCyrus** [dotansimha/graphql-code-generator#1691]
is there a way to export the exact introspection? we get the following error and it's a bit difficult to troubleshoot this. it was working with 0.16.1 so i guess there is something special with the schema at this position. but it's hard to tell if we can't see more of the schema at this position.

```
× GraphQL request
    Syntax Error: Expected Name, found }

    GraphQL request (1651:1)
    1650:
    1651: }
          ^
    1652:`

**Comment by dotansimha** [comment]
@OneCyrus please provide your schema and codegen config file. 
It looks like one of your schema files has syntax errors.

**Comment by OneCyrus** [comment]
we don't have a "schema-file" as we are using code-first in C#.  but i managed to catch the introspection from the graphql-codegen request.

### introspection
[introspection_codegen.txt](https://github.com/dotansimha/graphql-code-generator/files/3067529/introspection_codegen.txt)

### config
```
module.exports = {
  schema: {
    "http://localhost:35280/api/graphql": {
      headers: {
        Authorization: "Bearer " + process.env.ACCESS_TOKEN
      }
    }
  },
  documents: ["Scripts/**/*.graphql"],
  config: {
    namingConvention: {
      default: "change-case#pascalCase",
      enumValues: "change-case#upperCase"
    }
  },
  overwrite: true,
  generates: {
    "./Scripts/shared/api/api.ts": {
      config: {
        resolvers: false
      },
      plugins: ["typescript", "typescript-operations"]
    },
    "./Scripts/shared/fragmentTypes.json": {
      plugins: ["fragment-matcher"]
    }
  }
};

```

**Comment by dotansimha** [comment]
@OneCyrus It seems like the introspection works fine, but maybe something is wrong with one of the `Scripts/**/*.graphql` - can you please make sure?

**Comment by OneCyrus** [comment]
we already tried without the *.graphql files and had the same issue. and the other files don't have 1651 rows. looks very strange.

**Comment by dotansimha** [comment]
@OneCyrus Can you please try to use your introspection as source of schema? (use JSON extension, `schema: scheme.json`)

**Comment by OneCyrus** [comment]
if i use the introspection-file linked above i get the exact same error. the config looks like this now 

```
module.exports = {
  schema: "introspection_codegen.json",
  documents: ["Scripts/**/*.graphql"],
  config: {
    namingConvention: {
      default: "change-case#pascalCase",
      enumValues: "change-case#upperCase"
    }
  },
  overwrite: true,
  generates: {
    "./Scripts/shared/api/api.ts": {
      config: {
        resolvers: false
      },
      plugins: ["typescript", "typescript-operations"]
    },
    "./Scripts/shared/fragmentTypes.json": {
      plugins: ["fragment-matcher"]
    }
  }
};
```

**Comment by OneCyrus** [comment]
using the toolkit like this gives me no error

```
import { loadSchema } from "graphql-toolkit";

loadSchema("./introspection_codegen.json").then(x => console.log(x));
```

**Comment by OneCyrus** [comment]
ok. problem looks like it's an incompatibility with graphql@14.1.1. updating this package seems to resolve the issue.
