### ISSUE TITLE
Backport js-yaml dependency upgrade to v0.18

### ISSUE THREAD

**Issue by simPod** [dotansimha/graphql-code-generator#1693]
https://www.npmjs.com/advisories/788

js-yaml 3.12.0 is marked as vulnerable. Upgrade to 3.13.0 is required. However, gql-code-generator v0.18 requires it as `3.12.0` and not as `^3.12.0` so the version is locked. Can we have v0.18.1 with dep upgrade, please?

**Comment by dotansimha** [comment]
Hi, @simPod , sorry for the delay. I released 0.18.1 with this fix. (btw, if you are using `yarn`, you can use the `resolutions` field to do this kind of overrides).

**Comment by simPod** [comment]
@dotansimha Hi, no worries. Thanks for reply and ur work. Meanwhile I used `resolutions`, thanks for the tip tho ;)

**Comment by simPod** [comment]
@dotansimha yea... one more thing https://www.npmjs.com/advisories/813 sorry :D It needs js-yaml `3.13.1` now. 

_Why not use `^3.13.0` anyway?_

**Comment by dotansimha** [comment]
@simPod that's the one I upgraded to: https://github.com/dotansimha/graphql-code-generator/commit/7713bf549f52c62028f2725a5cd8d72aaf8d648d#diff-e8b2a1e1f04630fb5c0898905c324ab4R71 

And we prefer to use pinned dependencies, makes it easier to maintain and track :)

**Comment by simPod** [comment]
@dotansimha u r right, mb. Thanks!
