### ISSUE TITLE
Stencil 1.0 will require "import { h } from '@stencil/core'" in JSX components

### ISSUE THREAD

**Issue by jereckley** [dotansimha/graphql-code-generator#1695]
**Describe the bug**
This is just a heads up... you have a breaking change coming your way. After upgrading I see: 
Missing "h" import for JSX types: src/generated/graphql.tsx:1523:6
           In order to load accurate JSX types for components, the "h" function must be
           imported from "@stencil/core" by each component using JSX. For example: import
           { Component, h } from '@stencil/core';

Thank you guys! If anyone has a sweet workaround until official release that would be awesome. If not I'll get to writing a script eventually.

**To Reproduce**
Upgrade stencil to 1.0.0_alpha.8

**Comment by ardatan** [comment]
You can use `@graphql-codegen/add` to add `import { h } from '@stencil/core';` to the top.
`codegen.yml`
```yml
plugins:
  - add: import { h } from '@stencil/core';
```

**Comment by jereckley** [comment]
Super awesome. Thanks!
