### ISSUE TITLE
How does the --export flag work?

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#170]
I cannot find docs about exactly how to use it.

I tried with a file that exports a schema like this:

**schema.ts**

```ts
import gql from "graphql-tag";

export const schema = gql`
  type User {
    id: ID!
    first_name: String!
    last_name: String!
  }
`
```

And I run this:

```
gql-gen --export schema.js --template typescript --out ./types.ts ./src/**/*.ts
```

And I get this error:

```
Loading GraphQL Introspection from JavaScript ES6 export: schema.js...
TypeError: schema.getTypeMap is not a function
```

**Comment by dotansimha** [comment]
@jonaskello please try to change your export to:
```ts
import gql from "graphql-tag";

export default gql`
  type User {
    id: ID!
    first_name: String!
    last_name: String!
  }
`;
```

**Comment by jonaskello** [comment]
Yes, I tried that but still the same error. (When I omit export I get an error messages saying it needs either default export or "schema" export so I guess both are supported, although the named export is not in the readme.)

I think maybe the `gql` tag don't convert the string to the correct type. From what I understand codegen needs an object of type `GraphQLSchema`. I think what is generated is something called TypeDefs that are then used as input to apollo's `makeExecutableSchema()` function, which then in turn will finally generate an object of type `GraphQLSchema`. However I cannot run  `makeExecutableSchema()` without also providing resolvers, and I don't want them in the schema.js file...

**Comment by jonaskello** [comment]
The schema object that my example above export has a structure similar to this:

```
{ kind: 'Document',
   definitions:
    [ { kind: 'InputObjectTypeDefinition',
        name: [Object],
    directives: [],
        fields: [Array] },
      { kind: 'ObjectTypeDefinition',
...
```

**Comment by jonaskello** [comment]
Seems like something like [this function](https://github.com/apollographql/graphql-tools/blob/master/src/schemaGenerator.ts#L174) would be needed to translate it to a GraphQLSchema type.

**Comment by jonaskello** [comment]
I was able to fix it by creating a function that will convert a string or graphql document abstract syntax tree into a `GraphQLSchema` object like below.

Perhaps something like this could be included in codegen so that `--export` option could handle either a string, an ast (`DoumentNode`), or a` GraphQLSchema` object. If you want I could try to make a PR for it.

```ts
import {
  GraphQLSchema,
  DocumentNode,
  parse,
  buildASTSchema,
  extendSchema
} from "graphql";
import { extractExtensionDefinitions } from "graphql-tools";

export function buildSchemaFromAstOrString(
  typeDefinitions: string | DocumentNode
): GraphQLSchema {
  let myDefinitions = typeDefinitions;
  let astDocument: DocumentNode | undefined = undefined;

  if (isDocumentNode(typeDefinitions)) {
    astDocument = typeDefinitions;
  } else if (typeof myDefinitions === "string") {
    astDocument = parse(myDefinitions);
  } else {
    const type = typeof myDefinitions;
    throw new Error(`typeDefs must be a string, or schema AST, got ${type}`);
  }

  let schema: GraphQLSchema = buildASTSchema(astDocument);

  const extensionsAst = extractExtensionDefinitions(astDocument);
  if (extensionsAst.definitions.length > 0) {
    schema = extendSchema(schema, extensionsAst);
  }

  return schema;
}

function isDocumentNode(
  typeDefinitions: string | DocumentNode
): typeDefinitions is DocumentNode {
  return (typeDefinitions as DocumentNode).kind !== undefined;
}
```

**Comment by dotansimha** [comment]
@jonaskello sound good. I think that we should support as many inputs as possible. do you want to create a PR for this?

**Comment by jonaskello** [comment]
@dotansimha  I started a PR for this in #177, please review :-).

**Comment by GD-Aichi** [comment]
Is this review finish?

**Comment by dotansimha** [comment]
@GD-Aichi soon :) 
@jonaskello please read my latest comment in the PR.
