### ISSUE TITLE
Export individual resolver types

### ISSUE THREAD

**Issue by nklayman** [dotansimha/graphql-code-generator#1707]
**Is your feature request related to a problem? Please describe.**

If you store your resolvers in separate files, it is impossible to declare their type with 1.0. With previous versions, `QueryResolvers` was a namespace, so you could use `QueryResolvers.myResolver`.

**Describe the solution you'd like**
Add an option to use namespaces like pre-1.0, or export each resolver individually.

**Describe alternatives you've considered**
Using pre-1.0, manually creating each resolver type

**Additional context**

This is what I did with pre-1.0, doesn't work anymore.
```ts
import { prisma } from 'prisma-client'
import { QueryResolvers } from 'schema-types'

const users: QueryResolvers.users = () => prisma.users()

export default users
```

**Comment by kamilkisiela** [comment]
@nklayman You can do:

```ts
import { prisma } from 'prisma-client'
import { QueryResolvers } from 'schema-types'

const users: QueryResolvers['users'] = () => prisma.users()

export default users
``

**Comment by dotansimha** [comment]
@nklayman I agree with @kamilkisiela , can you please try it and let us know if that works for you?

**Comment by nklayman** [comment]
@kamilkisiela Thanks, it worked!
