### ISSUE TITLE
[Typescript plugin] Add prefix to types but not to enums?

### ISSUE THREAD

**Issue by giovanioliani** [dotansimha/graphql-code-generator#1712]
Hi, I'm aware that the `typesPrefix` option adds the prefix to both types and enums (as commented on https://github.com/dotansimha/graphql-code-generator/issues/1338#issuecomment-475126440), but is there some combination of options that will prefix types but not enums? If not, do you plan on adding this feature sometime in the future?

Thanks.

**Comment by dotansimha** [comment]
Hi @giovanioliani , sure, we can add it, but not as default, probably as a configuration (something like `enumPrefix: false`)

**Comment by dotansimha** [comment]
I'm working on this now. I think we'll change the config to be `string` or an object with a prefix per each GraphQL object.

**Comment by dotansimha** [comment]
Implemented in: https://github.com/dotansimha/graphql-code-generator/pull/2267

**Comment by dotansimha** [comment]
Available in 1.5.0 🎉
