### ISSUE TITLE
How to generate as a interface ?

### ISSUE THREAD

**Issue by alonstar** [dotansimha/graphql-code-generator#1716]
version: 1.0.7

I followed the step to create typescript model, but I need "interface" not type. How should I do?

And, 

I found [the live demo](https://graphql-code-generator.com)  is also "type", but [the document](https://graphql-code-generator.com/docs/getting-started/) is interface. 

`export type Post 
 {
  id: number;
  title: string;
  author: Author;
}`

codegen.yml:

> overwrite: true
schema: "http://localhost:9001/graphql"
generates:
  src/app/shared/models/graphql_models.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
    config:
      typesPrefix: I

**Comment by kamilkisiela** [comment]
I'm not quite sure how's `type` is any different than `interface`. Could you explain why you need an interface?

**Comment by dotansimha** [comment]
I agree with @kamilkisiela , there is no difference between `type` and `interface` in TypeScript (>=3). 
We chose to use `type` because it's easier to add/remove/join fields. 

Do you have a specific use case? Maybe we are missing something.

**Comment by alonstar** [comment]
Hi, thanks for your help.

I asked this question because I got error from [tslint](https://palantir.github.io/tslint/rules/interface-over-type-literal/)

> Prefer an interface declaration over a type literal (type T = { ... })

**Comment by bopfer** [comment]
There is probably no reason for tslint to care about the auto-generated files.  You should add this line under `plugins` in your codegen config:

```
- add: "/* tslint:disable */\n"
```

**Comment by dotansimha** [comment]
@alonstar You should either change you linter settings (because in TypeScript, there is drastic differences between `type` and `interface`, so I don't see any reason to prefer interfaces over types), or use @bopfer suggestion to use `add`.
