### ISSUE TITLE
Document which code-style should be used

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#172]
It would make it easier for contributors if there is a determined code-style.

I would suggest using [prettier](https://github.com/prettier/prettier) and set it up with lint-staged as described [here](https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged). It really helps to reduce whitespace changes etc. when doing PR:s.

**Comment by dotansimha** [comment]
@jonaskello 
Personally, I hate git-hooks, but I guess we cab give it a try. 
Currently, the only code-style is tslint, but I think we can add `prettier`. 
Any chance you want to create a PR for it?

**Comment by jonaskello** [comment]
Using husky and lint-staged (git hooks) is not a requirement for prettier. There is also [tslint-plugin-prettier](https://www.npmjs.com/package/tslint-plugin-prettier) which has tslint rules to follow the prettier style. Also if you use vscode you can install the [prettier plugin](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) which will automatically format your code according to prettier style using the regular formatting comand in vscode (and you can enable editor.formatOnSave to make it automatic).

Anyway, I'll make a PR with lint-staged becuase it provides the simplest way to make sure all commited code is formatted. If it does not work out you can of course revert it.

**Comment by dotansimha** [comment]
@jonaskello Sound good. It might be a good chance to see a good example for git hooks :)

**Comment by jonaskello** [comment]
I started a PR for this in #194.

**Comment by dotansimha** [comment]
Thank you @jonaskello !
