### ISSUE TITLE
Watch doesn't reload codegen.yml file on file changes

### ISSUE THREAD

**Issue by koenpunt** [dotansimha/graphql-code-generator#1735]
I'm trying to use watch mode on the `codegen.yml` file itself, because I'm adding a lot of new mappers.

But even though it outputs;

    ✔ Parse configuration
    ✔ Generate outputs

It doesn't take into account the newly added mappers.

When I quit watch mode and start it again, it correctly uses the new mappers.

**Comment by dotansimha** [comment]
Hi @koenpunt ! You are right, this is currently not supported. 
But I think it might be simple to implement, we can add it in the future.

**Comment by dotansimha** [comment]
Fixed in 1.6.0.

**Comment by lioneltay** [comment]
Hi, I seem to be getting the same issue in 1.19.2 
![image](https://user-images.githubusercontent.com/20704084/100320834-e509c000-3015-11eb-94a5-341bb6b632a1.png)

When making an update to `codegen.yml` the watcher outputs
![image](https://user-images.githubusercontent.com/20704084/100320885-f652cc80-3015-11eb-8043-c96da473e0cc.png)
 but it doesn't actually generate any code.

**Comment by dotansimha** [comment]
@lioneltay this issue it outdated. Can you please report a new if this still relevant? 
Thanks!
