### ISSUE TITLE
Support new mutation hook interface once it's released

### ISSUE THREAD

**Issue by kirill-konshin** [dotansimha/graphql-code-generator#1736]
https://github.com/trojanowski/react-apollo-hooks/pull/93

This is a very much needed functionality... hope codegen package will adopt it.

**Comment by ardatan** [comment]
I believe it will work correctly because we don't redefine complete signature of hook function. Let's keep it open until it's released and confirmed.

**Comment by kirill-konshin** [comment]
It seems to be working fine with latest alpha.

**Comment by dotansimha** [comment]
Awesome! Thank you @kirill-konshin , I guess we can close it for now. Feel free to open a new issue if something changes.
