### ISSUE TITLE
Ignore commented code

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#174]
Currently when a string with the `gql` tag exists but is commented, there will be an exception:

```
{ GraphQLError: Syntax Error ./xxxx/container-component.tsx (2:1) Cannot parse the unexpected character "/".
```

**Comment by dotansimha** [comment]
@jonaskello , you are right, I will fix it soon. 
Also, I need to add support for `gql(...)` (use it as function)

**Comment by jonaskello** [comment]
IIRC the checks are now done with regexp. I think maybe a better approach would be to parse it into an AST using babel or typescript. That would probably be more accurate than a regexp. But of course it would be more complex to implement and maybe slower too.

**Comment by dotansimha** [comment]
@jonaskello Yeah sure it makes sense. Do you have a reference or example for checking a code file as AST? I'll give it a try :)

**Comment by dotansimha** [comment]
@jonaskello 
`strip-comments` seems to work great (see unit tests)

https://github.com/dotansimha/graphql-code-generator/pull/192

**Comment by dotansimha** [comment]
Fixed in 0.8.19 :)

**Comment by jonaskello** [comment]
IMO, using strip-comments is a simpler solution and therefore better :-). If there are more advanced code-analysis needed later we can look into parsing into an abstract syntax tree at that point.

**Comment by FredyC** [comment]
Yea well, this wasn't a good move. See #196  ;)

**Comment by jonaskello** [comment]
Regarding parsing to AST I think we could either use [babylon](https://github.com/babel/babel/tree/master/packages/babylon) as it now has typescript support (see [here](https://github.com/babel/babylon/pull/523#issuecomment-311941007)). Or we could simply use typescript, see [here](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#traversing-the-ast-with-a-little-linter) for a simple example of traversing the AST.

**Comment by dotansimha** [comment]
@jonaskello @FredyC 
We recently merged this: https://github.com/dotansimha/graphql-code-generator/pull/907 , now the codegen will parse the code file as AST and extract the documents from it.
