### ISSUE TITLE
How to unit-test resolvers?

### ISSUE THREAD

**Issue by janhartmann** [dotansimha/graphql-code-generator#1763]
I am trying to unit test some resolvers after the update to v. 1.0.0. Take this resolver:

```tsx
import { AuthenticationResponseResolvers } from "./generated-types";

const authenticationResponseResolver: AuthenticationResponseResolvers = {
  accessToken: parent => {
    return parent.token;
  }
};
```

Where the generated code is the following:

```tsx
export type ResolversTypes = {
  // ... 
  AuthenticationResponse: IAuthenticationApiResponse;
  // ... 
};

export type AuthenticationResponseResolvers<
  ContextType = IContext,
  ParentType = ResolversTypes["AuthenticationResponse"]
> = {
  accessToken?: Resolver<ResolversTypes["String"], ParentType, ContextType>;
};
```

I would like to test that given a specific `IAuthenticationApiResponse` I pass the token to the `accessToken` resolver.

Before v. 1.0.0 I was able to test it like so:

```ts
describe("AuthenticationResponse", () => {
  describe("authenticationResponse.accessToken", () => {
    it("returns the access token from the response", async () => {
      const authenticationApiResponse: IAuthenticationApiResponse = {
        token: "12345678",
        customer: "FakeCustomer",
        name: "FakeUser",
        uom: "FakeUom"
      };
      const accessToken = mockResolver(
        authenticationResponseResolver.accessToken
      );
      const result1 = await accessToken(authenticationApiResponse);
      expect(result1).toEqual("12345678");
    });
  });
});
```

With a mocked resolver like so:

```ts
import { Resolver } from "../../src/resolvers/generated-types";

type MockResolver<TResult, TParent, TContext, TArgs> = (
  parent?: TParent | any,
  args?: TArgs | any,
  context?: TContext | any,
  info?: any
) => Promise<TResult> | TResult;

export function mockResolver<TResult, TParent, TContext, TArgs>(
  resolver: Resolver<TResult, TParent, TContext, TArgs>
): MockResolver<TResult, TParent, TContext, TArgs> {
  return (parent: TParent, args: TArgs, context: TContext, info) =>
    resolver(parent, args, context, info);
}
```

However, this gives the following error now:

```
Cannot invoke an expression whose type lacks a call signature. Type 'Resolver<TResult, TParent, TContext, TArgs>' has no compatible call signatures.ts(2349)
```

Is there any way of testing each resolvers using the new version (^1.0.0)? Maybe a simple direction or example ?

**Comment by kamilkisiela** [comment]
That's because we support Schema Stitching which makes `Resolver` type a union of a regular and stitching resolver. If you don't use Schema Stitching, set `noSchemaStitching: true` in your config.

**Comment by janhartmann** [comment]
Just to clearify, if I were using Schema Stiching, I would not be able to test any other resolvers? If I cast it to `ResolverFn` it still does not work.

**Comment by kamilkisiela** [comment]
Of course you can but you need to tell TypeScript which type should be used (for regular or stitching resolver) or a boolean or even nothing but it depends on what you're trying to test - only a function or a fragment + resolve function.

https://stackblitz.com/edit/graphql-codegen-resolvers-mock

**Comment by janhartmann** [comment]
Interesting, thanks I will have a look :-)

**Comment by vladinator1000** [comment]
Hi y'all, this issue is still relevant to me today, how does everyone unit test their resolvers?

**Comment by Urigo** [comment]
@vladinator1000 can you please open that as a new issue?
Maybe add also a reproduction on Code-Sandbox?
And suggest the solution you might want to see, or maybe just a way or a place to document it?

**Comment by vladinator1000** [comment]
@Urigo I think it's more of a docs thing, the `noSchemaStitching: true` worked perfectly for me. I can open a PR for it.

**Comment by Urigo** [comment]
@vladinator1000 thank you, a PR with a pointer to that in the right place would be great!
