### ISSUE TITLE
[Plugin Request] Scaffolding resolvers

### ISSUE THREAD

**Issue by alber70g** [dotansimha/graphql-code-generator#1772]
I'd like to request a "scaffolding resolvers" feature. I know that `graphqlgen` has a feature called ["scaffolding resolvers"](https://github.com/prisma/graphqlgen/blob/master/docs/03-scaffolding-resolvers.md). I'd like this feature to be in this repo as well, it would be awesome several reasons:

I'd like to have a framework for my resolvers scaffolded so it can reduce cognitive overhead when implementing a schema. This goes for two things: 1. best-practices wise and 2. for convenience. I understand that best-practices regarding resolvers could be situation specific, but there are certainly parts where it applies. Convenience being mainly that it doesn't require to know all the ins-and-outs of the types that's being used, and not needed to think about how to setup the `resolvers`-object with which typings, but that a Schema is converted one-to-one to the resolvers.

I also know that `graphqlgen` seems to not really tried to be compatible with this awesome generator (as [can be read here](https://github.com/prisma/graphqlgen/issues/152)) and that's why I'm asking this feature here, where I would have to rely on prisma/graphqlgen otherwise

**Comment by wtrocki** [comment]
/Going to work on in when porting graphback.dev generator to codegen.
