### ISSUE TITLE
[Typescript] type declaration for actual data

### ISSUE THREAD

**Issue by palindrom615** [dotansimha/graphql-code-generator#1774]
**Is your feature request related to a problem? Please describe.**

for now, generated Query type looks like this:
```typescript
export type CompanyDetailInfoQuery = { __typename?: "Query" } & {
  company: Maybe<
    { __typename?: "CompaniesRow" } & Pick<
      CompaniesRow,
      | "id"
      | "status"
      | "type"
      | "name"
      | "countryIso"
      | "postcode"
      | "address"
      | "tel"
      | "email"
      | "closedAt"
      | "taxType"
    > & {
        comments: Array<
          { __typename?: "CommentsRow" } & Pick<
            CommentsRow,
            "id" | "contents" | "createdAt" | "createdBy"
          >
        >;
      }
  >;
};
```
so when i try to specify type of data for client side instead of server-decided one (ex. `CompaniesRow`) I have to declare one.

code should declare picked type first and then declare query type like: 
```typescript 
export type CompanyDetailInfoQueryCompany = Maybe<
    { __typename?: "CompaniesRow" } & Pick<
      CompaniesRow,
      | "id"
      | "status"
      | "type"
      | "name"
      | "countryIso"
      | "postcode"
      | "address"
      | "tel"
      | "email"
      | "closedAt"
      | "taxType"
    > & {
        comments: Array<
          { __typename?: "CommentsRow" } & Pick<
            CommentsRow,
            "id" | "contents" | "createdAt" | "createdBy"
          >
        >;
      }
  >;

export type CompnayDetailInfoQuery = {
  company: CompanyDetailInfoQueryCompany;
}
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dotansimha** [comment]
@palindrom615 What you actually ask for is not compatible with the actual query result of GraphQL, because the result object first contain the `Query` type, and then the actual fields (because `Query` is still a GraphQL type, and `company` is a field of `Query`). 

You can do `export type CompanyDetailInfoQueryCompany = CompanyDetailInfoQuery['company']` manually, or create a codegen plugin that does that for you (see our Compatibility plugin, it does a similar thing).

**Comment by palindrom615** [comment]
@dotansimha I had missed some details. actually, you can do `export type CompanyDetailInfoQueryCompany = CompanyDetailInfoQuery['company'] ` as you say.

 But when I need to specify the type for comment of company, `export type CompanyDetailInfoQueryCompanyComment = CompanyDetailInfoQuery['company']['comments']` makes compile error obviously because company is `MayBe` type.

I have seen Compatibility plugin, and it evokes compile error just because of that reason.

I am pleased with more robust new `Scalars` type, but because it does not support optional, it makes impossible to use its server-side type instead of actual fields of query.
