### ISSUE TITLE
Typescript definition or interface models into graphql schema?

### ISSUE THREAD

**Issue by 4F2E4A2E** [dotansimha/graphql-code-generator#178]
Hello there!

ATM it seams, that there is no way of converting ts models into gql, can you guys maybe confirm it?
![image](https://user-images.githubusercontent.com/64590/34894205-bed83f62-f7e0-11e7-8df0-fa52475b8f09.png)

https://stackoverflow.com/questions/48231152/typescript-definition-or-interface-models-into-graphql-schema

**Comment by zephraph** [comment]
I think that's a little bit of a misnomer. This library is primarily for creating bindings from GQL to other languages (like typescript), not the reverse. 

Typescript has recently exposed an API that will let you programmatically do things based on typescript code, but this library doesn't do anything with that.

**Comment by 4F2E4A2E** [comment]
Thanks for the confirmation. Now one graphQl schema question: are type parameters - as in the stackoverflow question described - possible in the graphql schema definition?
```ts
export interface Bank<T> {
    account: T;
    errors: ErrorList[];
}
```

**Comment by 4F2E4A2E** [comment]
I found a solution for this, but you're not going to like it:  

1. Convert your typescript complex objects to a json schema draft 4 using [typescript-json-schema](https://github.com/YousefED/typescript-json-schema)
2. Use a openAPI (e.g.: swagger.json) schema containing all endpoints and types definitions
3. Replace the definitions properties from the swagger.json file with the json schema draft 4 types definitions
4. Reference the swagger.json endpoints (paths) to the new types definitions generated from typescript
5. Start the graphQL backend with [swagger-to-graphql](https://github.com/yarax/swagger-to-graphql)

Sadly there are no direct way in doing this.
@zephraph thanks for you time, closing issue.
