### ISSUE TITLE
[ts] Question: Types for entity relationships fetched via custom field resolvers

### ISSUE THREAD

**Issue by elado** [dotansimha/graphql-code-generator#1780]
Assuming this schema:

```gql
type Author {
  id: ID!
  name: String!
}

type Article {
  id: ID!
  authorId: ID!
  author: Author!
  title: String
}

type Query {
  randomArticle: Article
}
```

The resolver type for `Query.randomArticle` query requires me to return an object with both `author/title`.

However, I want to define the `author` fetching in a field resolver of `Article`:

```ts
const resolvers = {
  Article: {
    author: obj => DB.authors.find(obj.authorId)
  },

  Query: {
    randomArticle: async () => {
      const a = await DB.articles.random()
      return {
        id: a.id,
        title: a.title,
        authorId: a.authorId,
      }
    }
  }
}
```

The generated type of `randomArticle` requires a mandatory `author`, but my implementation is somewhere else. I acknowledge `author` is possibly null, but I'd like to rely on GQL's schema validation, and not to have to make `author` optional.

The problem comes when a client type is generated with an optional `author` on an `Article` object. It forces me to test for `if (article.author)` in strict TypeScript.

My current workaround is to fake force casting the returned object as the full object, relying on the field resolver to fill the value in, and GQL schema validator to validate nothing is missing:

```ts
// ...

  Query: {
    randomArticle: async () => {
      const a = await DB.articles.last()
      return {
        id: a.id,
        title: a.title,
        authorId: a.authorId,
      } as Article // <--- this
    }
  }
```

Thoughts? Any better solution?

**Comment by dotansimha** [comment]
Hi @elado !
We have `mapping` configuration that allow you to specify custom object types for the resolvers plugin, please take a look here: https://graphql-code-generator.com/docs/plugins/typescript-resolvers 
You can also specify generics to the resolver signature to override the parent/return type of the resolvers.
