### ISSUE TITLE
Security Issue NODE_TLS_REJECT_UNAUTHORIZED is set to 0

### ISSUE THREAD

**Issue by TSiege** [dotansimha/graphql-code-generator#1806]
Found a major security concern. [This package sets my project's `NODE_TLS_REJECT_UNAUTHORIZED` to 0 for the entire process](https://github.com/dotansimha/graphql-code-generator/blob/de7ad41f4f93dbf47e4da4b4919ac35acbd791a6/packages/graphql-codegen-cli/src/generate-and-save.ts#L9) thereby disabling SSL. I found this when searching after seeing this security warning from node.
```
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
```

I've traced it back to this commit... https://github.com/dotansimha/graphql-code-generator/pull/147/commits/8b0bc1ea8408badb845696e35df85c6a84a4563a

**Comment by simPod** [comment]
Can it be backported to v0.18 pls?

**Comment by dotansimha** [comment]
@simPod on it now, sorry for the delay.

**Comment by dotansimha** [comment]
@simPod 0.18.2 is available now.

**Comment by simPod** [comment]
@dotansimha thanks, contacted NPM about fix for https://www.npmjs.com/advisories/834 (there's no release with fix for v1 AFAIK)

**Comment by dotansimha** [comment]
Fixed in `1.2.0`.

**Comment by simPod** [comment]
@dotansimha Hi, NPM cannot find the release https://www.npmjs.com/package/graphql-code-generator

![image](https://user-images.githubusercontent.com/327717/58027634-5f9c7a00-7b19-11e9-9931-bb2d3ae75007.png)

**Comment by dotansimha** [comment]
@simPod we moved to organization libraries after 1.0, `graphql-code-generator` is now `@graphql-codegen/cli` and plugins are also moved (for example `graphql-codegen-typescript` is now `@graphql-codegen/typescript`.

**Comment by simPod** [comment]
@dotansimha right, I forgot that! thanks
