### ISSUE TITLE
Allow wider range of graphql package version

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#181]
I am using graphql-tools which tells me this:

```
graphql-tools@2.21.0" has incorrect peer dependency
"graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
```

So I need at least 0.11.0 of graphql. However graphql-code-generator tells me this:

```
warning "graphql-code-generator > graphql-codegen-core@0.8.14" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0".
warning "graphql-code-generator > graphql-codegen-core > graphql-tools@1.2.3" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0".
```

There can be only one version of the graphql in total in the project or everything will break down becuase `instanceof` checks will not work. This is manifested by an error message like this during install:

```
 |   Error: Cannot use GraphQLSchema "[object Object]" from another module or realm.
 |
 |   Ensure that there is only one instance of "graphql" in the node_modules
 |   directory. If different versions of "graphql" are the dependencies of other
 |   relied on modules, use "resolutions" to ensure only one version is installed.
 |
 |   https://yarnpkg.com/en/docs/selective-version-resolutions
 |
 |   Duplicate "graphql" modules cannot be used at the same time since different
 |   versions may have different capabilities and behavior. The data from one
 |   version used in the function from another could produce confusing and
 |   spurious results.
```

Since each package cannot have their own version of the graphql package, they all have to agree on a single version. If graphql-code-generator could be updated to allow "graphql@^0.11.0 || ^0.12.0 || ^0.13.0" it would make it easier to use together with other packages.

**Comment by FredyC** [comment]
Please note that with `0.13.0` comes a breaking change that directly influences this package ... https://github.com/graphql/graphql-js/issues/1221

**Comment by dotansimha** [comment]
Done!
