### ISSUE TITLE
featuring graphql-code-generator in Docusaurus

### ISSUE THREAD

**Issue by NishealJ** [dotansimha/graphql-code-generator#1821]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) page.

Are you with me on this? Also, can you provide your logo?

More info about this [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by dotansimha** [comment]
Hi @NishealJ ! 
Sure, it would be great. (and you can also add https://graphql-modules.com there :) )
Our logo is available in the repo: https://github.com/dotansimha/graphql-code-generator/blob/master/logo.png

**Comment by dotansimha** [comment]
@NishealJ Closing this. Feel free to include it :)
