### ISSUE TITLE
Generation result contains total of 0 files...

### ISSUE THREAD

**Issue by leemhenson** [dotansimha/graphql-code-generator#183]
Hi.

I'm trying to follow the docs that describe how to customise the template output. I've added this `gql-gen.json` to `<project root>` (alongside `package.json`):

```json
{
  "flattenTypes": true,
  "primitives": {
    "Boolean": "boolean",
    "Float": "number",
    "ID": "string",
    "Int": "number",
    "String": "string"
  }
}
```

and I've added a directory containing these templates files (which is exact copies of the templates here: https://github.com/dotansimha/graphql-code-generator/tree/master/packages/graphql-codegen-generators/src/typescript-single-file

```
<project-root>/src/graphqlCodegen/documents.handlebars
<project-root>/src/graphqlCodegen/schema.handlebars
<project-root>/src/graphqlCodegen/selection-set.handlebars
<project-root>/src/graphqlCodegen/template.handlebars
<project-root>/src/graphqlCodegen/type.handlebars
```

I'm running the following cli command:

`DEBUG=true VERBOSE=true gql-gen --project ./src/graphqlCodeGen --no-documents --file ./src/apollo/__generated__/schema.json`

where the `schema.json` file is the introspection query data.

Unfortunately this generates no output, and the debuglog statements finish with:

```
Generation result contains total of 0 files...
Generation result is:  []
```

It's clearly parsed some schema data as it earlier mentions:

```
[executeWithOptions] Schema template context build, the result is:
Total of types: 57
Total of inputTypes: 16
Total of enums: 6
Total of unions: 0
Total of scalars: 0
Total of interfaces: 3
Total of definedDirectives: 3
```

Ultimately my goal is to try to write some resolver function types, but I'm struggling to get over the first hurdle. What am I doing wrong?

Cheers!
Lee

**Comment by GD-Aichi** [comment]
I think you forget the extension of file. for example
```js
<project-root>/src/graphqlCodegen/ts.type.handlebars // or
<project-root>/src/graphqlCodegen/js.type.handlebars // or what do you want
```
add this for all files.

**Comment by leemhenson** [comment]
Ok, prepending `ts.` to the handlebar files causes it to generate output now. Thanks! 

Unfortunately, I want to generate a single file but now I'm getting one file per template invocation, e.g. `something.type.ts`, `somethingElse.type.ts`. I just want everything to be concatenated into a single `generated.ts` file. 

I've tried adding `"inputType": "SINGLE_FILE",` to my `gql-gen.json` but it looks like that gets ignored if you're using `--project`. 

I then tried `gql-gen --no-documents --file ./src/apollo/__generated__/schema.json --template ts --out ./src/graphqlCodegen/generated.ts` which did generate a single file as requested but of course that is no longer using my copies of the templates.

Is it possible to do what I want to do?

**Comment by GD-Aichi** [comment]
add a name of file to file of template for a single file.
```
generated.ts.type.handlebars
```
You can mix single file and multi files.
in my project
```
loaders.ts.schema.handlebars
ts.type.handlebars
...
```

**Comment by leemhenson** [comment]
Hmm, `generated.ts.type.handlebars` just gives me a load of files like this `generated.myType.type.ts`....

**Comment by GD-Aichi** [comment]
try it with schema.
```
generated.ts.schema.handlebars
```
I dotn't use 'type' file for single file.

**Comment by leemhenson** [comment]
Thanks for helping me out with this. I got `The partial type could not be found`:

```
[executeWithOptions] Schema template context build, the result is:
Total of types: 57
Total of inputTypes: 16
Total of enums: 6
Total of unions: 0
Total of scalars: 0
Total of interfaces: 3
Total of definedDirectives: 3
[transformDocument] transforming total of 0 definitions...
[executeWithOptions] using project: ./src/graphqlCodeGen
[executeWithOptions] Got project config JSON:  { flattenTypes: true,
  primitives:
   { Boolean: 'boolean',
     Float: 'number',
     ID: 'string',
     Int: 'number',
     String: 'string' } }
[scanForTemplatesInPath] Scanning for templates using glob pattern: /path/to/project/src/graphqlCodeGen/**/*.@(template|handlebars|tmpl|gqlgen)
[scanForTemplatesInPath] Got results from glob:  [ '/path/to/project/src/graphqlCodeGen/generated.ts.schema.handlebars',
  '/path/to/project/src/graphqlCodeGen/ts.documents.handlebars',
  '/path/to/project/src/graphqlCodeGen/ts.selection-set.handlebars',
  '/path/to/project/src/graphqlCodeGen/ts.template.handlebars',
  '/path/to/project/src/graphqlCodeGen/ts.type.handlebars' ]
[compileTemplate] starting to compile template with input type = PROJECT
[compileTemplate] settings =  { generateSchema: true, generateDocuments: false }
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/generated.ts.schema.handlebars
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/ts.documents.handlebars
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/ts.selection-set.handlebars
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/ts.template.handlebars
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/ts.type.handlebars
[compileTemplate] generateDocuments is false, ignoring documents...
[compileTemplate] Executing generateMultipleFiles...
[compileTemplate] Compiling template: /path/to/project/src/graphqlCodeGen/generated.ts.schema.handlebars...
[cleanTemplateComments] called, looking for magic comments in /path/to/project/src/graphqlCodeGen/generated.ts.schema.handlebars...
[cleanTemplateComments] /path/to/project/src/graphqlCodeGen/generated.ts.schema.handlebars does not contains any magic comments, skipping...
[compileTemplate] Compiling template: /path/to/project/src/graphqlCodeGen/ts.documents.handlebars...
[cleanTemplateComments] called, looking for magic comments in /path/to/project/src/graphqlCodeGen/ts.documents.handlebars...
[cleanTemplateComments] /path/to/project/src/graphqlCodeGen/ts.documents.handlebars does not contains any magic comments, skipping...
[compileTemplate] Compiling template: /path/to/project/src/graphqlCodeGen/ts.selection-set.handlebars...
[cleanTemplateComments] called, looking for magic comments in /path/to/project/src/graphqlCodeGen/ts.selection-set.handlebars...
[cleanTemplateComments] /path/to/project/src/graphqlCodeGen/ts.selection-set.handlebars does not contains any magic comments, skipping...
[compileTemplate] Compiling template: /path/to/project/src/graphqlCodeGen/ts.template.handlebars...
[cleanTemplateComments] called, looking for magic comments in /path/to/project/src/graphqlCodeGen/ts.template.handlebars...
[cleanTemplateComments] /path/to/project/src/graphqlCodeGen/ts.template.handlebars does not contains any magic comments, skipping...
[compileTemplate] Compiling template: /path/to/project/src/graphqlCodeGen/ts.type.handlebars...
[cleanTemplateComments] called, looking for magic comments in /path/to/project/src/graphqlCodeGen/ts.type.handlebars...
[cleanTemplateComments] /path/to/project/src/graphqlCodeGen/ts.type.handlebars does not contains any magic comments, skipping...
[compileTemplate] Templates names:  [ '/path/to/project/src/graphqlCodeGen/generated.ts.schema.handlebars',
  '/path/to/project/src/graphqlCodeGen/ts.documents.handlebars',
  '/path/to/project/src/graphqlCodeGen/ts.selection-set.handlebars',
  '/path/to/project/src/graphqlCodeGen/ts.template.handlebars',
  '/path/to/project/src/graphqlCodeGen/ts.type.handlebars' ]
[generateMultipleFiles] Compiling multiple files...
[generateMultipleFiles] Checking template: /path/to/project/src/graphqlCodeGen/generated.ts.schema.handlebars
[generateMultipleFiles] Using custom template handlers, parsed template name result:  { prefix: '/path/to/project/src/graphqlCodeGen/generated',
  handler: [Function: handleSchema],
  fileExtension: 'ts' }
[handleSchema] called
{ Error: The partial type could not be found
    at Object.invokePartial (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:281:11)
    at Object.invokePartialWrapper [as invokePartial] (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at eval (eval at createFunctionContext (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at prog (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval [as main] (eval at createFunctionContext (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:31)
    at main (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/path/to/project/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  message: 'The partial type could not be found',
  name: 'Error',
  number: undefined }
Error: Error: The partial type could not be found
```

I thought this might be because of these lines here:

```
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/generated.ts.schema.handlebars
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/ts.documents.handlebars
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/ts.selection-set.handlebars
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/ts.template.handlebars
[compileTemplate] register partial template /path/to/project/src/graphqlCodeGen/ts.type.handlebars
```

It looks like it's registered the full path as the partial name, instead of the just the "short" template name. I hacked in a change to these lines:

https://github.com/dotansimha/graphql-code-generator/blob/f3f6e0aa4d482bf407e507267424e363d1d32758/packages/graphql-codegen-compiler/src/compile.ts#L29-L31

to see if extracting `/(?:\/|\.)([^\/\.]+)\.handlebars$/.exec(templateName)[1]` would help. When I renamed my partials to:

```
generated.ts.schema.handlebars
documents.handlebars
selection-set.handlebars
template.handlebars
type.handlebars
```

and reran the command it did then find the partials and only generated a single file called `generated.ts`! 

Success! I am confused how this could be working for you though. 🤔

**Comment by GD-Aichi** [comment]
I thing, you forgot the type of file "ts.selection-set.handlebars"
```
ts.selection-set.schema.handlebars
```
look to [example](https://github.com/dotansimha/graphql-code-generator-usage-example/tree/master/src/models).

**Comment by leemhenson** [comment]
If I put the `ts.` prefix back in on `type` then it generates individual files for all the types as well. 😅

**Comment by dotansimha** [comment]
It should be `FILE_PREFIX.EXTENSION.CONTEXT.handlebars`.
If you use `type` context then it will generate a file per each type. 
If you use `schema` you will get the entire schema as context (single file).

**Comment by leemhenson** [comment]
Hello again! I'm still not getting anywhere with this. I think the reason the example that you link to works is because this file: 

https://github.com/dotansimha/graphql-code-generator-usage-example/blob/master/src/models/mongoose.ts.schema.handlebars

Doesn't use partials in the same way that this single-file schema template does:

https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-generators/src/typescript-single-file/schema.handlebars#L7

I've tried every combination of filenames that you have suggested, but it never finds the `type` partial unless I patch `compileTemplate` using the regex I mentioned earlier.

**Comment by dotansimha** [comment]
@leemhenson 
Ohhh I see now. You have a template which is the main template (with a `type`/`schema`) context, and you want to use a partial inside the main template. Is that correct?

If so, I think that I need to add support for `my-name.partial.handlebars` and register it as partial.

**Comment by dotansimha** [comment]
Also, @leemhenson @GD-Aichi , feel free to send notes regarding the `project` API and it's structure. 
I think we can improve it's API and usage, but I need to get your notes to get more use cases :)

**Comment by GD-Aichi** [comment]
Hi @dotansimha,
my projects are [graphql-codegen-migrations-sequelize](https://github.com/GD-Aichi/graphql-codegen-migrations-sequelize) and [graphql-codegen-sequelize-typescript](https://github.com/GD-Aichi/graphql-codegen-sequelize-typescript).

**Comment by leemhenson** [comment]
All I am trying to do right now is use the templates from:

https://github.com/dotansimha/graphql-code-generator/tree/master/packages/graphql-codegen-generators/src/typescript-single-file

In my project. I want the schema template to use the other partials to build up a single file.

**Comment by GD-Aichi** [comment]
I think, you can close this.

**Comment by leemhenson** [comment]
Without the changes I mentioned to `compile.ts` above, my scenario still does not work. I don't know whether they are the way you want to go though.

**Comment by dotansimha** [comment]
@leemhenson if that's still relevant, can you please open a new issue with all the details?
