### ISSUE TITLE
Make suffix of generated React components customizable

### ISSUE THREAD

**Issue by jlkiri** [dotansimha/graphql-code-generator#1834]
**Is your feature request related to a problem? Please describe.**

Since components generated by `typescript-react-apollo` all have `Component` suffix in their name, it is not easy to distinguish between components that do the query work and those that don't in my code. It would be nice to still be able to distinguish the query components from others by using the `Query` suffix, e.g. not `MyItemsComponent` but `MyItemsQuery`. However, there is no way to specify this in the plugin config.

**Describe the solution you'd like**

Make it possible to specify `customSuffix` in plugin config inside `codegen.yml`. E.g. `customSuffix: 'Query'`.

**Describe alternatives you've considered**

**Additional context**

**Comment by dotansimha** [comment]
Available in `1.2.0`.
