### ISSUE TITLE
Add a config option to generate optional query.data

### ISSUE THREAD

**Issue by steebchen** [dotansimha/graphql-code-generator#1836]
**Is your feature request related to a problem? Please describe.**

When using the angular client with `fetchPolicy: 'cache-and-network'` with watchQuery, usually cached results are streamed at first, and when the network request is done new results are streamed. However, when the cache is empty, a response is streamed where `data` is undefined. This means that it would require `data` to be optional so you have to check it with if before you use data.xxx.

**Describe the solution you'd like**
Since all other fetchPolicies don't come with this issue, I wouldn't like to set data to nullable by default. Instead, I think it would be best to provide an option in the `config` option where types are generated where data is set to nullable, so people who use `fetchPolicy: 'cache-and-network'` in their app can simply set the option to have correct types.

**Comment by dotansimha** [comment]
Hi @steebchen ! 
I'm not sure it's 100% related to the codegen, because I think we are just passing the `TData` generics, and the `data` property is declared by Apollo.

@kamilkisiela ?

**Comment by steebchen** [comment]
Dang, true. I could have seen this by just looking in the generated file. I guess we can close this issue here, not sure what I will do about this in general.

**Comment by dotansimha** [comment]
@steebchen I think you can just check for the value of `data` anyway, even if it's not optional.

**Comment by steebchen** [comment]
Of course, it's just about type safety. Thanks anyway!
