### ISSUE TITLE
Docs on programmatic usage give incorrect example

### ISSUE THREAD

**Issue by Micahnator** [dotansimha/graphql-code-generator#1858]
**Describe the bug**
The website's documentation for using graphql-code-generator programmatically gives an invalid example configuration object. The websites shows plugins being assigned an object:
`plugins: {
    typescript: {}, // Here you can pass configuration to the plugin
},`

But the actual source for the codegen function specifies 'plugins' as:
`plugins: Types.ConfiguredPlugin[];`.

The only way I've gotten it to work is to specify plugins this as an array of objects:
`plugins: [
        { typescript: {} },
],`

**Expected behavior**
Is there a reason that the 'plugins' field is not an object just like the 'pluginMap' field is? Seems like it would be best for them both to be structured as objects rather than an array. But if 'plugins' needs to remain an array, then the website should show a correct example.

**Environment:**

- OS: Windows 10
- `@graphql-codegen/1.1.3`: 
- NodeJS: 10.15.0

**Additional context**
The programatic usage documentation in question: https://graphql-code-generator.com/docs/getting-started/programmatic-usage

**Comment by andrewmartin** [comment]
Thanks for this!

**Comment by dotansimha** [comment]
You are right, I updated it in the docs.

You can use `normalizeConfig` from our codebase in order to prepare any kind of config object: 
```
export function normalizeConfig(config: any): any[] {
  if (typeof config === 'string') {
    return [{ [config]: {} }];
  } else if (Array.isArray(config)) {
    return config.map(plugin => (typeof plugin === 'string' ? { [plugin]: {} } : plugin));
  } else if (typeof config === 'object') {
    return Object.keys(config).reduce((prev, pluginName) => [...prev, { [pluginName]: config[pluginName] }] as any, []);
  } else {
    return [];
  }
}
```

I might change it in a future release, I don't want to break the API at the moment.
