### ISSUE TITLE
Add non-optional __typename to typescript-operations plugin

### ISSUE THREAD

**Issue by piotr-m-jurek** [dotansimha/graphql-code-generator#1878]
**Feature Request - force non-optional __typename to typescript-operations**

Apollo inmemory cache has an option to use `__typename` field to generate keys.
Adding `__typename` to every level of operation is obscuring.

**Describe the solution you'd like**
Adding option `forceTypename`, that defaults to false. 

**Describe alternatives you've considered**
I didn't, but IMHO this is a nice change 🤷‍♂ 

**Additional context**

I forked the repo and work on PR myself, but it can take me some time to get along in the codebase, give me a heads up if it is a quicker job for you.

**Comment by piotr-m-jurek** [comment]
https://github.com/dotansimha/graphql-code-generator/pull/1879

**Comment by dotansimha** [comment]
Available in 1.2.0, thanks @piotr-m-jurek !
