### ISSUE TITLE
Enum key starting with underscore is not generated correctly

### ISSUE THREAD

**Issue by chengjia0807** [dotansimha/graphql-code-generator#1900]
Now it's generating this which is wrong:

```
export enum AgeEnum {
  LessThan19 = 'LessThan19',
  20to24 = '_20to24',
  25to29 = '_25to29',
  30to34 = '_30to34',
  35to39 = '_35to39',
  40to44 = '_40to44',
  45to49 = '_45to49',
  50to54 = '_50to54',
  55to59 = '_55to59',
  60to64 = '_60to64',
  65to74 = '_65to74',
  75to84 = '_75to84',
  85AndOver = '_85AndOver'
}
```

The correct one should be

```
export enum AgeEnum {
  _LessThan19 = 'LessThan19',
  _20to24" = '_20to24',
  _25to29" = '_25to29',
  _30to34 = '_30to34',
  _35to39 = '_35to39',
   ...
}
```

basically we need to keep the underscore because the enum key cannot be a number.

Hope can be fixed in short. :) 

Great work guys

Thanks
CJ

**Comment by dotansimha** [comment]
Hi @chengjia0807 , which version of the codegen and plugins do you use? (we have a template for our issues exactly for that).

I this issue already fixed in: https://github.com/dotansimha/graphql-code-generator/issues/1569

**Comment by dotansimha** [comment]
Fixed in https://github.com/dotansimha/graphql-code-generator/commit/96e1ad38f5b1f6ccc8952d5539abd656ae549def

**Comment by dotansimha** [comment]
Fixed in 1.3.1

**Comment by dotansimha** [comment]
Fixed in 1.3.1

**Comment by calebergh** [comment]
I am using 1.9.1, and appear to be having this issue - can you advise?

example:

```
export enum Enum_MyVar {
  6 = '_6',
  4 = '_4',
  2 = '_2',
  Zero = 'ZERO',
  Neg_2 = 'NEG_2',
  Neg_4 = 'NEG_4',
  Neg_6 = 'NEG_6'
}
```

Note the `6` is omitting the initial underscore, which is invalid.

**Comment by ardatan** [comment]
Could you try the latest version`1.12.1`? If this still doesn't fix your problem, please open a new issue with a reproduction.
Thanks @calebergh
