### ISSUE TITLE
Interested in linking to blog post about this tool?

### ISSUE THREAD

**Issue by stevenmusumeche** [dotansimha/graphql-code-generator#1914]
Hello maintainers, and thank you for this awesome tool.  I recently wrote a blog post about using this tool with an example that may be a useful link in your documentation.  The post is at https://formidable.com/blog/2019/strong-typing/

Feel free to close this issue if inappropriate.

**Comment by dotansimha** [comment]
Hi @stevenmusumeche ! your blog post looks great! 
Keeping open until we'll add it to the docs (and feel free to add it in a PR ;) )

**Comment by stevenmusumeche** [comment]
I will open a PR.  Do you have an idea of where you'd like to see it?

**Comment by dotansimha** [comment]
@stevenmusumeche, maybe we can add another sidebar item (in https://github.com/dotansimha/graphql-code-generator/blob/master/website/sidebars.json#L11), for "Further Reading", and include this link there? (add then I'll add some more).
