### ISSUE TITLE
Prop Typings with Multiple HoC Queries Doesn't Work

### ISSUE THREAD

**Issue by freedomflyer** [dotansimha/graphql-code-generator#1922]
Using `"@graphql-codegen/typescript-react-apollo": "^1.1.0"`

In the case where multiple queries (and thus multiple HoC's) are used on a single component, Apollo's docs state that the developer should give each of them a `name` in their options. Otherwise, the queries overlap each other on the resulting `props.data` property.

In the case of a single query, Apollo places query results based on a name parameter directly on `props`, instead of placing a single query result on `props.data`. 

For example, this codeblock should follow the comments I've added to it.

```ts
export default compose(
  withFoo(), // should have {name: "myFooQuery"}
  withBar(), // should have {name: "myBarQuery"}
)(MyFooBarComponent)
```

And the query results should be available on `props.myFooQuery` and `props.myBarQuery`.

However, if I do this, the HoC prop typings that I'd place on `MyFooBarComponent` won't work, since they have a `data` prop.

```ts
type AllProps = FooQueryProps & BarQueryProps // HoC props generated by typescript-react-apollo
class MyFooBarComponent extends Component<AllProps, IState> {
    render() {
        const { foo, bar } = this.props // typings don't work here, because of custom name in query HoC
    }
}
```

I don't believe there is any workaround to this. The only solution I can see is doing something like this, which seems overly verbose and brittle.

```ts
interface AllProps {
  myFooQuery: FooQuery // generated by typescript-react-apollo
  myBarQuery: BarQuery // generated by typescript-react-apollo
}
```

**Comment by dotansimha** [comment]
Hi @freedomflyer , as you suggested, you should set a `name` for your operation, otherwise it will conflict with the other one. 
I'm not sure how to pass the `name` to it as a key, maybe we can put a generic for that.

@ardatan what do you think?

**Comment by ardatan** [comment]
Is that related to https://github.com/dotansimha/graphql-code-generator/issues/1672 ?

**Comment by freedomflyer** [comment]
@ardatan it is somewhat similar, but I believe the `config.alias` referenced in https://github.com/dotansimha/graphql-code-generator/issues/1672 is more about how the HoC shows up in react devtools and other places.

In this case, the `name` option is used solely to prevent a name clash between two queries. When a single query runs, the data is stored in `props.data`, but if two queries run, the second query would overwrite what is in `props.data`, so instead Apollo allows you to name them specifically, so you can access data like `props.foo` and `props.bar`.

**Comment by dotansimha** [comment]
@freedomflyer The generated HOC signature allow you to set the name manually when you use it, just like passing `variables`.

```
export default compose(
  withFoo({name: "myFooQuery"}), 
  withBar({name: "myBarQuery"}),
)(MyFooBarComponent)
```

We can't set this because the `data` field is hardcoded in React-Apollo typings, so even if we would set the `name` field, you'll still get `.data` only (see interface `DataProps` of react-apollo).
