### ISSUE TITLE
Mismatch between what is in the docs and actual output?

### ISSUE THREAD

**Issue by andrzey** [dotansimha/graphql-code-generator#1942]
In the documentation the following schema should give the following output:

    // schema

    type Author {
      id: Int!
      firstName: String!
      lastName: String!
      posts(findTitle: String): [Post]
    }

    type Post {
      id: Int!
      title: String!
      author: Author!
    }

    type Query {
      posts: [Post]
    }

    schema {
      query: Query
    }

    // generated Typescript typings

    interface Query {
      posts?: Post[];
    }

    interface Post {
      id: number;
      title: string;
      author: Author;
    }

    interface Author {
      id: number;
      firstName: string;
      lastName: string;
      posts?: Post[];
    }

    interface PostsAuthorArgs {
      findTitle?: string;
    }

However when I try this example my generated output looks like this:

    export type Maybe<T> = T | null;
    /** All built-in and custom scalars, mapped to their actual values */
    export type Scalars = {
      ID: string;
      String: string;
      Boolean: boolean;
      Int: number;
      Float: number;
    };

    export type Author = {
      __typename?: "Author";
      id: Scalars["Int"];
      firstName: Scalars["String"];
      lastName: Scalars["String"];
      posts?: Maybe<Array<Maybe<Post>>>;
    };

    export type AuthorPostsArgs = {
      findTitle?: Maybe<Scalars["String"]>;
    };

    export type Post = {
      __typename?: "Post";
      id: Scalars["Int"];
      title: Scalars["String"];
      author: Author;
    };

    export type Query = {
      __typename?: "Query";
      posts?: Maybe<Array<Maybe<Post>>>;
    };

Config file:

    {
      "overwrite": true,
      "schema": "./schemas/something.graphql",
      "generates": {
        "src/generated/graphql.ts": {
          "plugins": ["typescript"],
        },
        "src/generated/merged-schema.graphql": {
          "plugins": ["schema-ast"]
        }
      }
    }

Am I doing something wrong or is this the expected behaviour? Using version 1.0.0.

**Comment by dotansimha** [comment]
Thank you for reporting it, @andrzey ! 
The docs are outdates, I'll update it soon.

**Comment by AlexMabry** [comment]
I'd prefer the output to match the documentation than the other way around.  Are there configuration settings that would output something like this?

```
export type Author = {
  __typename?: "Author";
  id: number;
  firstName: string;
  lastName: string;
  posts?: Post[];
};

export type AuthorPostsArgs = {
  findTitle?: string;
};

export type Post = {
  __typename?: "Post";
  id: number;
  title: string;
  author: Author;
};

export type Query = {
  __typename?: "Query";
  posts?: Post[];
};
```

**Comment by gtsopour** [comment]
@andrzey @AlexMabry I am wondering the same. Did you find any other configuration?

**Comment by AlexMabry** [comment]
@gtsopour I didn't.

**Comment by dotansimha** [comment]
@AlexMabry @andrzey The actual output is not that different. We chose to use a bridge type for `Scalars` to make it easier to generate output and avoid bugs. 
We are thinking about adding a feature in the future to avoid this and generate the primitive types in-place instead using bridge types.

**Comment by dotansimha** [comment]
Updated. Thanks @andrzey !
