### ISSUE TITLE
Type does not satisfy the constraint '"__typename"' when using inline fragments on interfaces

### ISSUE THREAD

**Issue by panzelva** [dotansimha/graphql-code-generator#1943]
Hello I think found a bug that looks very similar to this: https://github.com/dotansimha/graphql-code-generator/issues/1762, except its with interfaces instead with unions.

![A3y9nNMR2L](https://user-images.githubusercontent.com/28455278/58709568-bd9f4c00-83ba-11e9-923c-ce721428f33e.png)

I made small repo with this error here: https://github.com/panzelva/gql-gen-interface-issue

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/commit/d4804df119feb6ecdcd8593a7f81d398bb03419b

**Comment by dotansimha** [comment]
Fixed in 1.4.0 🎉
