### ISSUE TITLE
Invariant Violation: Minified React error #321

### ISSUE THREAD

**Issue by diegopamio** [dotansimha/graphql-code-generator#1947]
**Describe the bug**
The Live Demo in the GraphQL-code-generator page is not showing up, and the console shows: 11.13c641d9.chunk.js:1 Invariant Violation: Minified React error #321

**To Reproduce**
* Open https://graphql-code-generator.com/#live-demo

1. My GraphQL schema:
N/A

2. My GraphQL operations:
N/A

3. My `codegen.yml` config file:
N/A

**Expected behavior**
The usual live demo can be used.

**Environment:**

- OS: MacOS
- Browser: Safari 12.0.3, Chrome 73.0.3683.103

**Additional context**
Was working a couple of weeks ago on the same laptop.

**Comment by dotansimha** [comment]
Not sure why it happens, seems like something with the build of react-scripts (because it works in dev, and it does not throw any error...) .
I reverted to the last working version, and I'll take a look soon.

**Comment by dotansimha** [comment]
I managed to fix it (see https://github.com/facebook/react/issues/15628#issuecomment-500123610 for more info). 
Website is live now :)
