### ISSUE TITLE
Space missing in fragments type assignment

### ISSUE THREAD

**Issue by FredyC** [dotansimha/graphql-code-generator#197]
It's completely insignificant issue, but I am reporting it just to be known. This is from generated star-wars example and you can see space missing there.

https://github.com/dotansimha/graphql-code-generator/blob/329b77375a08f1dc4a062b1196c4aa5e34366594/dev-test/star-wars/ts-multiple/herodetailswithfragment.query.d.ts#L13

I am guessing it's hidden somewhere in here, but I do have some trouble reading handlebars templates :/

https://github.com/dotansimha/graphql-code-generator/blob/329b77375a08f1dc4a062b1196c4aa5e34366594/packages/graphql-codegen-generators/src/typescript-single-file/fragments.handlebars#L1

**Comment by dotansimha** [comment]
I guess that now that the code goes through `prettier` it should solve things like that.

**Comment by dotansimha** [comment]
Please try 0.8.20 and let me know if it looks better
