### ISSUE TITLE
Replace namespaces with ES6 modules

### ISSUE THREAD

**Issue by tomaswitek** [dotansimha/graphql-code-generator#1982]
**Is your feature request related to a problem? Please describe.**
We use this code generator for both server and client code and it worked perfectly until we decided to upgrade to v1. 

#### generated types
```
export namespace RebalancingPage {
  export type Variables = {
    selector: RebalancingSelector;
  }

  export type Query = {
    __typename?: "Query";
    
    rebalancing: Rebalancing | null;
  }

  export type Rebalancing = RebalancingQueryFragment.Fragment
}
```

#### app code
```
import {RebalancingPage} from "types";
let rebalancing: RebalancingPage.Rebalancing
```

#### generated types
```
export type RebalancingPageQueryVariables = {
  selector: RebalancingSelector
};


export type RebalancingPageQuery = ({ __typename?: 'RootQuery' } & { rebalancing: Maybe<({ __typename?: 'DiscretionaryRebalancing' } & RebalancingQueryFragment)> });

```

#### app code
```
import {RebalancingPageQuery} from "types";
let rebalancing: RebalancingPageQuery["rebalancing"]
```
With this approach our code can get unreadable very fast, for example we can end-up with a following type `RebalancingPageQuery["rebalancings"][0]["title"]`. Types like that are most of the time optional which causes even more changes in the previous code.

**Describe the solution you'd like**
Why not to replace/simulate namespaces using files together with es6 modules? Should be possible with a `near-operation-file` preset right?
```
  // RebalancingPage.ts

  export type Variables = {
    selector: RebalancingSelector;
  }

  export type Query = {
    __typename?: "Query";
    
    rebalancing: Rebalancing | null;
  }

  export type Rebalancing = RebalancingQueryFragment.Fragment
```

**Describe alternatives you've considered**
I tried to change the config to match my requirements. I was also considering to write own plugin. I also tried the alternative generator from Apollo team, which has a similar approach I've described above, but there are other issues with the Apollo generator.

I also tried to find an answer first. It looks like I am not the only one searching for this kind of answer: https://github.com/dotansimha/graphql-code-generator/issues/1602. Unfortunately namespaces are no go for us because we want to migrate our project to `@babel/preset-typescript`.

**Comment by dotansimha** [comment]
Hi @tomaswitek 
We decided to drop TypeScript `namespace`s, because it was very hard to maintain. Having a single type per operation simplifies the output. We know that it was a bit more difficult to upgrade from <1, and that's why we published the `typescript-compatibility` plugin, that will generate intermediate types like you had before 1.0, and should make it easier for you to migrate.
