### ISSUE TITLE
Fragment importing other fragment generates unused imports (near-operation-file)

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#1989]
**Describe the bug**
If your fragment imports fragment that uses another fragment its generated parts are getting imported without usage causing compilation error from TS side.

**To Reproduce**
[![Edit Use before declare + unused imports](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/use-before-declare-unused-imports-8dlju?fontsize=14&module=%2Fsrc%2Fdocument.graphql&view=editor)

**Comment by dotansimha** [comment]
Fixed in 1.4.0 🎉
