### ISSUE TITLE
Use before declare fragment for .graphql files causes self imports and duplicated declarations as a result (near-operation-file)

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#1990]
**Describe the bug**
If you use fragment in a fragment that is imported below, then you're getting duplicates and self imports. If you change the direction it's all good and working nicely.

**To Reproduce**
[![Edit Use before declare + unused imports](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/use-before-declare-unused-imports-8dlju?fontsize=14&module=%2Fsrc%2Fdocument.graphql&view=editor)

**Comment by dotansimha** [comment]
Fixed in 1.4.0 🎉
