### ISSUE TITLE
Make "default" resolvers of mapped types optional

### ISSUE THREAD

**Issue by schmod** [dotansimha/graphql-code-generator#1996]
**Is your feature request related to a problem? Please describe.**

If I am using Mapped types with typescript-resolvers, I occasionally want to just allow scalar values to "pass through" from my Mapped (parent) type to the GraphQL response type, _without_ having to define a resolver for each field, or disable `avoidOptionals`.

This corresponds to the behavior of the [Default Resolver](https://www.apollographql.com/docs/graphql-tools/resolvers/#default-resolver) in graphql-tools. 

**Describe the solution you'd like**

For instance, if I have the following GraphQL Schema:

```graphql
type Query {
  getUser(id: Int!): User
}
type User {
  firstName: String!
  lastName: String!
  fullName: String!
}
```

I might have the following mapped type that represents a user in my database:
```ts
type UserParent {
  userId: number;
  firstName: string;
  lastName: string;
}
```

I would like to be able to define a resolver that "enhances" `UserParent` with a `fullName` resolver, _without_ repeating the scalar values that I want to be passed through via the default field resolver:
```ts
const resolvers = {
  Query: {
    getUser: () => UserParent;   // pseudo-code
  },
  User: {
    fullName: (parent) => `${parent.firstName} ${parent.lastName}`
  }
};
```

**Describe alternatives you've considered**

It's possible that this functionality already exists, and I'm doing something wrong.  

Disabling `avoidOptionals` works, but has some obvious drawbacks, as the type system no longer guarantees that I've actually defined everything.

**Comment by dotansimha** [comment]
Hi @schmod ,
Unfortunately, there is not other option for that. Because we would like to allow developers to separate the implementation of their resolvers to multiple objects, and with `avoidOptionals` set to `true`, you will get a signature that forces you to implement all resolvers. 

Why not removing `avoidOptionals` (or, set to `false`)? (if you use it because of other plugins, such as `typescript`, note that you can set configuration per each plugin).

**Comment by cullophid** [comment]
If you set avoidOptionals to false, you will not be required to provide the resolver for fullName, and it will throw at runtime if you forget.

Ideal behavior would be that if you provide a mapping to a parent type then ti would make all the fields in that type optional in the resolver, and any fields not defined should be required.

so in @schmods case: 
the generated UserResolver would be


```
type UserResolver= {
  userId?:(parent, args, ctx) =>  ...
  firstName?: (parent, args, ctx) =>...
  lastName?: (parent, args, ctx) => ...
  fullName:(parent, args, ctx) => ..
}
```

**Comment by dotansimha** [comment]
Im closing this, as the only way to implement it is to force all types.
@cullophid this sounds like a different issue, if you think we should add the use-case, feel free to open a new issue :)

**Comment by danilobuerger** [comment]
@dotansimha I think this was closed prematurely. The solution that @cullophid describes would actually solve OPs case.

This seems actually pretty important when using mappers and `avoidOptionals: false` (the default) as you loose all type safety for the difference between the mapped type and the generated type. 

Consider the above example. The mapped type `UserParent` does not provide the field `fullName` which is a non-null field in the generated type. Forgetting to add a resolver for `fullName` will lead to a runtime crash, whereas the point of typings is to catch this at compile time.

The fix would be diffing the mapped type against the generated type and marking every resolver for a field thats in that diff as not being optional.

**Comment by dotansimha** [comment]
@danilobuerger We are tracking a similar issue here: https://github.com/dotansimha/graphql-code-generator/issues/3278
