### ISSUE TITLE
Resolver types: can the resolve function return either expected type OR a revolvers type?

### ISSUE THREAD

**Issue by craigsmitham** [dotansimha/graphql-code-generator#1998]
Currently (or the best of my understanding) resolver types type any of the output object types returned by the resolver as a simple typed representation of the GraphQL type. In many cases we need to return an object that implements its own resolvers because some of the properties may be lazy loaded or have custom logic, etc. 

As an example, assume the following schema:
```graphql
type Airport {
   id: ID!
   name: String!
   location: Location!
}

type Location {
   id: ID!
   name: String!
   weatherStatus: String!
}
```
The TypeScript resolvers plugin will generate at least 4 types: `Airport`, `Location`, `AirportResolvers` and `LocationResolvers`. 

The challenge becomes when a field such as `Location.weatherStatus` will never be available as a simple property on an object (it has to be fetched, parsed, manipulated etc) and as such we have implemented the `LocationResolvers` type. 

The problem becomes that we cannot return an object of the type `LocationResolvers` when implementing the `location` resolver for the `AirportResolvers` type. 

So, is essential for us to be able to use _either_ the simply typed `Location` type _or_ the `LocationResolvers` when it may be included in the type (even if it deeply nested) returned by a resolver function.

Hopefully the above example was easy to follow. It's a trivial case but this pattern would help us extensively as we are code genning our ORM types which would also implement their own resolver functions for related entities, but which aren't readily available when fetched - so the simply generated types won't do. Bottom line: ***in our resolve function, we need to be able to _possibly_ return type(s) that implement custom resolvers***.

Is there something I'm missing in the current implementation or docs that will help us achieve this goal, or any thoughts on how we would go about doing this?

**Comment by pnordhus** [comment]
You can map generated types to other types. You could make all types `Partial`:
```yaml
  config:
    defaultMapper: Partial<{T}>
```
This is documented [here](https://graphql-code-generator.com/docs/plugins/typescript-resolvers#usage-example-wrap-default-types-with-partial).

If you need stronger type safety and/or more flexibility, you could write a [mapper](https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers-object) for your type and overwrite `weatherStatus` as optional, e.g.:
```typescript
export type MakeWeatherStatusOptional<T> = Omit<T, 'weatherStatus'> & {
  weatherStatus?: string;
};
```
```yaml
config:
  mappers:
    Location: ./location#MakeWeatherStatusOptional<{T}>
```
Then you can return `Location` from your resolver without `weatherStatus`.

**Comment by dotansimha** [comment]
Hi @craigsmitham :) 
As @pnordhus said, you can use `mappers` to map GraphQL types to your custom type/interface, and the codegen will use your types instead.
