### ISSUE TITLE
support for useMutation return value in react-apollo-hooks 0.5.0 

### ISSUE THREAD

**Issue by gentleShark** [dotansimha/graphql-code-generator#2009]
**Is your feature request related to a problem? Please describe.**
useMutation react-apollo-hooks 0.5.0-alpha.0 returns a tuple with the mutation function and an object with properties such as data, loading, error, called, etc.  Ex:

```
const [mutate, { data, loading, error }] = useMutation(GQL);
```
 

It would be nice to be able to use useMutation as specified in react-apollo-hooks 0.5.0

**Comment by dotansimha** [comment]
Hi @gentleShark ! 
Thank you for reporting it. 

Can you please let us know what preventing you from using it now? 
The generated hook is just a wrapper around the original `useMutation` (for example, see https://github.com/dotansimha/graphql-code-generator/blob/master/dev-test/githunt/types.reactApollo.hooks.tsx#L517-L518), so I'm not sure why it doesn't work as needed.

**Comment by gentleShark** [comment]
You're right @dotansimha. After digging into it a bit more I can confirm that the useMutation hook generated by graphql-codgen returned the correct types for the tuple returned by useMutation in react-apollo-hooks  0.5.0-alpha.0. Thanks!
