### ISSUE TITLE
Have to cast typename when creating an object

### ISSUE THREAD

**Issue by BeeeQueue** [dotansimha/graphql-code-generator#2017]
**Describe the bug**
When generating the types for a type that implements an interface in the GQL schema the generator currently makes the type of the `__typename` be a combination of both types.

See this repo for an example: https://github.com/BeeeQueue/gql-gen-issue

`Cat` implements `Animal`, so the type of `__typename` becomes `"Cat" & "Animal"` instead of `"Cat"`.

**Environment:**

- OS: any
- `@graphql-codegen/typescript`: 1.2.1
- NodeJS: any

**Comment by dotansimha** [comment]
Hi @BeeeQueue ,
I tested it with the latest version (1.3.1) and it seems to work. now there is no `__typename` at all in `interface`s. 

```ts
export type Maybe<T> = T | null;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Animal = {
  legs: Scalars["Int"];
};

export type Cat = Animal & {
  __typename: "Cat";
  legs: Scalars["Int"];
  cute: Scalars["Boolean"];
};

```
