### ISSUE TITLE
Possible to remove Maybe & Scalars types in favor of `number | null` and inlined Scalar values?

### ISSUE THREAD

**Issue by ericbiewener** [dotansimha/graphql-code-generator#2048]
Rather than the creation of `type Maybe<T> = T | null`, is it possible to just inline the `| null` everywhere it is used? Same with the `type Scalars`. To clarify:

Current output:

```typescript
Maybe<Scalars["String"]>
```

Desired output:
```typescript
string | null
```

I'd also be interested to know if there is an advantage to the current approach.

**Comment by dotansimha** [comment]
Hi @ericbiewener , we are already thinking about adding this feature. 
Please see my comment here: https://github.com/dotansimha/graphql-code-generator/issues/1904#issuecomment-496557106

**Comment by cothman** [comment]
Same here, is the Maybe type removed or at least configurable

**Comment by omarbenmegdoul** [comment]
Is this still in the cards, or perhaps already implemented?

**Comment by adamtaylor13** [comment]
I looked at https://github.com/dotansimha/graphql-code-generator/pull/2107, and it doesn't seem to resolve the originally asked question. Ideally, I'd like for the generated type files to just inline Maybe whenever possible. For example, currently the behavior is:

```
export type Maybe<T> = T | undefined;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};
export type User = {
  __typename?: 'User';
  email: Scalars['String'];
  id: Scalars['String'];
  name: Scalars['String'];
  profilePictureUrl?: Maybe<Scalars['String']>;
};
```

But, I'd really like to ability to simply generate:
```
export type User = {
  __typename?: 'User';
  email: string;
  id: string;
  name: string;
  profilePictureUrl?: string | undefined;
};
```

Is there some trade-off here between the two that I don't understand?

**Comment by ryancarloscorrea** [comment]
@adamtaylor13 Did you find any solution?

**Comment by adamtaylor13** [comment]
@ryancarloscorrea Unfortunately not ☹️

**Comment by venkatd** [comment]
I would like the same as @adamtaylor13 the readability of the types is more confusing for others on our team and simply inlining the types (as though I was writing them by hand) would be the ideal.

I could hack it with some regexp find/replace but would rather have an option for this!

**Comment by denakol** [comment]
Hi! no news regarding it? Types are quite ugly.

**Comment by jhopley-stadion** [comment]
Yea it would be pretty good to have config to remove this. Really annoying and forcing me to cast types when doing transforms,

**Comment by TreeOfLearning** [comment]
Since this hasn't been addressed 4 years on, I had to sort something out myself. Here's what I ended up with. Note: this may or may not work with your codebase, you may need to modify it, etc. etc.

```
const fs = require('fs');
const path = require('path');

// Get the file path from the command line arguments
const args = process.argv.slice(2);
if (args.length !== 1) {
  console.error('Usage: node clean-graphql.js <file-path>');
  process.exit(1);
}

const filePath = path.resolve(args[0]);
const fileContent = fs.readFileSync(filePath, 'utf-8');

const maybeRegex = /Maybe<([^>]+)>/g;
const inputMaybeRegex = /InputMaybe<([^>]+)>/g;
const scalarsRegex = /Scalars\['([^']+)'\]\['([^']+)'\]/g;

// Extract the scalar map from the file content
const scalarMap = {};
const scalarTypeRegex = /(\w+): { input: ([^;]+); output: ([^;]+); }/g;

const lines = fileContent.split('\n');
let inScalarsSection = false;
let scalarsSection = '';

for (const line of lines) {
  if (line.includes('export type Scalars = {')) {
    inScalarsSection = true;
  }
  if (inScalarsSection) {
    scalarsSection += line + '\n';
    if (line.includes('};')) {
      break;
    }
  }
}

if (scalarsSection) {
  let match;
  while ((match = scalarTypeRegex.exec(scalarsSection)) !== null) {
    const [_, scalarName, inputType, outputType] = match;
    scalarMap[scalarName] = { input: inputType.trim(), output: outputType.trim() };
  }
} else {
  console.error('Failed to extract Scalars section from the file.');
  process.exit(1);
}
console.log('Extracted scalar map:', scalarMap);

// With my codegen config, the first 11 lines are header/exports we don't want to modify
const preservedLines = lines.slice(0, 11).join('\n');
let transformedContent = lines.slice(11).join('\n');

// Inline Scalars
transformedContent = transformedContent.replace(scalarsRegex, (match, scalarType, scalarIO) => {
  if (scalarMap[scalarType] && scalarMap[scalarType][scalarIO]) {
    return scalarMap[scalarType][scalarIO];
  } else {
    console.error(`Scalar type ${scalarType} with IO ${scalarIO} not found in scalar map.`);
    return match;
  }
});

// Remove Maybe & InputMaybe
transformedContent = transformedContent.replace(inputMaybeRegex, '$1 | null');
transformedContent = transformedContent.replace(maybeRegex, '$1 | null');
transformedContent = preservedLines + '\n' + transformedContent;

fs.writeFileSync(filePath, transformedContent, 'utf-8');

console.log('File transformation complete.');
```

Invoked like so:
`node clean-graphql.js src/path/to/your/graphql.ts`

I then just run this after running codegen, and it cleans up the file.

**Comment by lirobinxc** [comment]
Works great, thanks for sharing!
