### ISSUE TITLE
Uncompileable javascript generated by numeric names for enums.

### ISSUE THREAD

**Issue by merisbahti** [dotansimha/graphql-code-generator#2070]
**Describe the bug**

**To Reproduce**

1. My GraphQL schema:
For example, the graphql type

```graphql
enum NumberEnum {
  _25
  _50
  _75
  _100
}
```
Generates this code:
```typescript
export enum NumberEnum {
  25 = "_25",
  50 = "_50",
  75 = "_75",
  100 = "_100"
}
```

which is incorrect and does not compile in typescript:
```[tsserver 2452] [E] An enum member cannot have a numeric name.```

2. My GraphQL operations:

Not applicable. (I think?)

3. My `codegen.yml` config file:

Not applicable. (I think?)

**Expected behavior**

Maybe generate this instead?
```typescript
export enum NumberEnum {
  _25 = "_25",
  _50 = "_50",
  _75 = "_75",
  _100 = "_100"
}
```

**Environment:**

- OS: mac os
- `@graphql-codegen/typescript`: 
- NodeJS: 10 

**Additional context**

**Comment by dotansimha** [comment]
Hi @merisbahti 
You can use `namingConvention` to override the `enumValues` transformations:
```yml
config:
  namingConvention:
    enumValues: keep
```
