### ISSUE TITLE
add a scanner for `schema` similar to documents scanner for `documents`

### ISSUE THREAD

**Issue by helios1138** [dotansimha/graphql-code-generator#2078]
- `documents` field allows specifying a glob matching code files which have gql queries defined in them using `gql-tag`
- it would be nice if `schema` field would also allow doing the same

**Comment by dotansimha** [comment]
Hi @helios1138 ! 
You are right, it's not supported at the moment (we are using https://github.com/ardatan/graphql-toolkit to load the schema, so it should be implemented there).

**Comment by dotansimha** [comment]
Fixed in `graphql-toolkit` 0.4.0, will be available in the next release.

**Comment by dotansimha** [comment]
Fixed in 1.5.0 🎉
