### ISSUE TITLE
space getting trimmed in the generated comments from triple quoted comment

### ISSUE THREAD

**Issue by veeramarni** [dotansimha/graphql-code-generator#2081]
**Describe the bug**
 
The generated comments from a triple-quoted comment in the final output come with trimmed beginning space. We like to have space not trimmed when our comments are multi-lined. 
**To Reproduce**

1. My GraphQL schema:

```graphql
"""
 @title - name
 @description - name of the object
"""
type name
```

2. My generated output

```
/** @title - contributes.colors
@description -  name of the object
**/
```

**Expected behavior**

It should not trim the space, so it would appear as below.

```
/** 
@title - contributes.colors
@description -  name of the object
**/
```
**Environment:**

- OS: 
- `@graphql-codegen/...`:  1.3.1

**Comment by dotansimha** [comment]
Fixed in 1.5.0 🎉
