### ISSUE TITLE
New plugin that generates Typescript source file from GraphQL files

### ISSUE THREAD

**Issue by dex4er** [dotansimha/graphql-code-generator#2083]
Hi,

I wrote some additional plugin https://github.com/dex4er/js-graphql-codegen-typescript-document-nodes

It generates Typescript files from GraphQL schema, ie.:

```ts
import {DocumentNode} from 'graphql';
import gql from 'graphql-tag';

export const viewerQuery: DocumentNode = gql`
  query Viewer {
    viewer {
      login
      name
    }
  }
`;
```

It would be great if this plugin will be a part of your framework. Just feel free to include it and change it if you find it useful.

**Comment by dotansimha** [comment]
Hi @dex4er ! That's awesome! 

Do you want to create a PR for it?

**Comment by dex4er** [comment]
@dotansimha ok, I never worked with lerna but I'll try
