### ISSUE TITLE
Default output paths inside node_modules

### ISSUE THREAD

**Issue by Urigo** [dotansimha/graphql-code-generator#2084]
I've just had a chat with @schickling

They are recommending their users to output the generated code in node_modules.

They do that because that way there is less confusion about the best practice to not put those files into source control and also that imports can look nicer.

He also said they are working on a convention to put generated files under a `@generated/some-package` path.
Not sure who will maintain that npm org but I guess it doesn't matter.

As it's already easy to configure the output path we don't have a lot to do here, maybe just change examples to use that convention and maybe add defaults (even though with our config structure I'm not sure defaults make sense).

Putting it here to start a discussion

**Comment by ardatan** [comment]
But in this case, project will look broken at the first time. So people must add `preinstall: "graphql-codegen"` script to package.json.
I think operation types should be imported using `.graphql` itself instead of another file using `declare module`.
And codegen can provide a special register extension for non-TS, code parts in order to import them using `.graphql` extension on runtime.

**Comment by dotansimha** [comment]
@ardatan maybe as `postinstall` script? this way all the dependencies (and the codegen) will get installed, then `postinstall` will run `graphql-codegen` and create the output file under `node_modules`.

**Comment by ardatan** [comment]
Sorry I meant `postinstall` :)

**Comment by teevik** [comment]
Hey, i wanted to have my generated files inside node_modules/@generated too, and that part is working. However, when trying to import from there in a react app, it's erroring:
```
[CRA] ./node_modules/@generated/apollo.tsx 5:7
[CRA] Module parse failed: Unexpected token (5:7)
[CRA] You may need an appropriate loader to handle this file type.
[CRA] | import * as ReactApollo from 'react-apollo';
[CRA] | import * as ReactApolloHooks from 'react-apollo-hooks';
[CRA] > export type Maybe = T | null;
[CRA] | export type Omit = Pick>;
[CRA] | /** All built-in and custom scalars, mapped to their actual values */
```
(i'm using create-react-app)

I'm guessing webpack doesn't handle any .tsx files in node_modules? Any way to get around this?

**Comment by schickling** [comment]
The solution to this is to not generate a `.tsx` file but to "pre-compile" it (either via `tsc` or generate it this way in the first place) to a `.js` + `.d.ts` file. This could also be a config option to adjust this behavior.

**Comment by n1ru4l** [comment]
Before doing this we should also about people using mono repos:

Pain Points I can think of right now:

Makes it especially hard in case you have to build Dockerfiles for each service you generate types for. (one central codegen config for all workspaces in repo root).

You can certainly work around it by first copying the types over after installing the dependencies, however, that should be something that should get documented.

**Comment by dotansimha** [comment]
@n1ru4l I think using `yarn install --focus` can help a lot for monorepo with Dockerfile, it will install every dependency in it's own package dir and will skip hoisting. Also, using the root dir as Docker context dir helps :)

**Comment by ardatan** [comment]
@teevik As @schickling said, CRA doesn't compile files inside node_modules. But I think having precompiled files like `.js` and `.d.ts` is overkill. This is a missing feature in CRA and codegen shouldn't be responsible of typescript compilation. @dotansimha What do you think?

**Comment by dotansimha** [comment]
I agree with @ardatan .
Currently, there is no default output path in our codegen, because the output files are defined under `generates`, and it's a `key => value`, so there must be a key. 
I can't see a benefit for generating files into `node_modules`, but I think we can leave this open in case we'll collect more uses cases.

**Comment by dotansimha** [comment]
I think we can close this one. Output path is super flexible and if someone want to build this into a package, you can do that easily.
