### ISSUE TITLE
quickguide not working

### ISSUE THREAD

**Issue by silveracy** [dotansimha/graphql-code-generator#2097]
https://github.com/dotansimha/graphql-code-generator#quick-start

```
$ yarn add -D graphql @graphql-codegen/cli
~~~~install~~~~
$ graphql-codegen init
bash: command not found: graphql-codegen
```

so I think to fix it like this:

`
$ yarn global add graphql @graphql-codegen/cli
`

**Comment by ardatan** [comment]
Try `yarn graphql-codegen init`.

**Comment by silveracy** [comment]
OH. thank you so much
