### ISSUE TITLE
SchemaAST plugin. write schema with directives

### ISSUE THREAD

**Issue by alx13** [dotansimha/graphql-code-generator#2128]
**Is your feature request related to a problem? Please describe.**

[Currently](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/other/schema-ast/src/index.ts#L6) `schema-ast` plugin uses `printSchema` from `graphql`.
That function strips all directives from generated schema.

So it's impossible to use `schema-ast` to write down full schema to, for example, compare changes with tools like [graphql-inspector](https://github.com/kamilkisiela/graphql-inspector)

**Describe the solution you'd like**
An option to the `schema-ast` plugin or another plugin to write schema with directives (e.g., to use `printSchemaWithDirectives` from [graphql-toolkit](https://github.com/ardatan/graphql-toolkit))

**Comment by dotansimha** [comment]
Fixed in 1.4.0 🎉
