### ISSUE TITLE
Partials, when using the --project option

### ISSUE THREAD

**Issue by tjme** [dotansimha/graphql-code-generator#213]
Is there a way to define partials/shared templates, along with custom templates?

I tried including a templates entry in gql-gen.json (with either an embedded partial definition, or a .handlebars file reference), but it seems to be ignored.

**Comment by dotansimha** [comment]
This PR resolves this issue: https://github.com/dotansimha/graphql-code-generator/pull/210 

@micimize @tjme 

I'll release it soon :)

**Comment by dotansimha** [comment]
Done in 0.9.0 :)
