### ISSUE TITLE
Add header comment for autogenerated files

### ISSUE THREAD

**Issue by cktang88** [dotansimha/graphql-code-generator#2131]
**Is your feature request related to a problem? Please describe.**

I work in code bases where it is not always clear that a file is autogenerated, so sometimes people try to change the autogenerated files, which cause lots of issues.

**Describe the solution you'd like**
Each autogenerated file should have a header block comment that states that it is an autogenerated file, maybe with metadata as well as to the date the file was generated, the version of graphql-code-generator that was used, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by dotansimha** [comment]
Hi @cktang88 ,
We decided not to add it automatically, but let the developers choose how and where to add it. 
There is a a plugin called `add` you can use for that: https://graphql-code-generator.com/docs/plugins/add#examples
