### ISSUE TITLE
Specify `graphql` as a dependency for @graphql-codegen/typescript

### ISSUE THREAD

**Issue by joshlam** [dotansimha/graphql-code-generator#2140]
**Describe the bug**
 

The typescript plugin [uses `isIntrospectionType`](https://github.com/dotansimha/graphql-code-generator/blob/v1.3.1/packages/plugins/typescript/typescript/src/index.ts#L122) from [`graphql`](https://github.com/dotansimha/graphql-code-generator/blob/v1.3.1/packages/plugins/typescript/typescript/src/index.ts#L2) as part of its main plugin function. This imported function from `graphql` is therefore required for usage of the package (not just for dev, as the `graphl` dependency is [currently specified](https://github.com/dotansimha/graphql-code-generator/blob/v1.3.1/packages/plugins/typescript/typescript/package.json#L18)).

The problem is that `isIntrospectionType` was introduced in [`graphql@0.12.0`](https://github.com/graphql/graphql-js/releases/tag/v0.12.0), making the typescript plugin incompatible with older versions of `graphql`. The `package.json` should be updated to reflect this, otherwise this can cause issues when trying to use older versions of `graphql` as a consumer of `@graphql-codegen`.

**To Reproduce**

In your project that is consuming `@graphql-codegen`, use the `typescript` plugin along with a version of `graphql` older than `v0.12.0`. Notice errors about the missing `isIntrospectionType` function.

1. My `codegen.yml` config file:

```yml
overwrite: true
schema: ${SCHEMA_PATH}
generates:
    ${CODEGEN_GQL_PATH}/codegen.ts:
        plugins:
            - 'typescript'
            - 'typescript-operations'
```

**Expected behavior**

I expect to be able to use older versions of `graphql` (that fit in with the peer dependency requirements specified in `@graphql-codegen`, which is currently `graphql@0.8.0` and up). If the plugin has a dependency on newer versions of `graphql`, then this should be reflected as a dependency or peer dependency of that package.

**Comment by dotansimha** [comment]
Done in 1.4.0 🎉

**Comment by joshlam** [comment]
Thanks!
