### ISSUE TITLE
Unique operation names requirement and `near-operation-file` preset

### ISSUE THREAD

**Issue by vhenzl** [dotansimha/graphql-code-generator#2143]
The generator throws if it encounters duplicated operation names (requested in #720, implemented in #913).

This is perfectly correct if all generated code goes to a single file. However, with  `near-operation-file` preset, duplicated names aren't a problem any longer (unless the duplication would be in the same file). It seems like the validation should be on output level rather than on global level.

I'm still relatively new to GraphQL world so I'm not sure what are the best practices, maybe it's the best to have unique names anyway, but with my current understanding the requirement of unique names across relatively large application seems to be limiting.

**Comment by dotansimha** [comment]
You are right, I'll take a look today :)

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/2269 , you can try it with the latest alpha `1.4.1-alpha-45ce6b30.65`.

**Comment by dotansimha** [comment]
Fixed in 1.5.0 🎉
