### ISSUE TITLE
[ts-react-apollo] integration with latest react-apollo-hooks (0.5.0)

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#2146]
There are breaking changes, as described in this commit: https://github.com/trojanowski/react-apollo-hooks/commit/e0d05fd 

@Urigo @ardatan

**Comment by zifahm** [comment]
has this been fixed in 1.4? should i not update to 0.5.0?

**Comment by ardatan** [comment]
@dotansimha I think it doesn't break anything in our template, does it?

**Comment by dotansimha** [comment]
I'm not sure, can you please verify it?

**Comment by mvestergaard** [comment]
I'm using 0.5.0, and there are no issues. The breaking change only affects the consumption side of the mutations. So nothing that should affect the generated code.
