### ISSUE TITLE
Generate more generic but less code

### ISSUE THREAD

**Issue by hediet** [dotansimha/graphql-code-generator#2153]
In general, you want to generate as less code as possible but as much as you can get from your source data (graphql schemas in this case) that you cannot do with JavaScript at runtime / TypeScript at compile time.

In particular, React-Apollo-Components and HOC-functions are generated directly using specific types.
However, that could be improved, if abstractions for query types are introduced.

Given this query:
```graphql
query GetConversation($id: ID!, $messageCount: Int!) {
	messenger {
		conversation(id: $id) {
			...FullConversation
		}
	}
}
```
Rather than generating this:
```ts
export const GetConversationDocument = gql`
	query GetConversation($id: ID!, $messageCount: Int!) {
		messenger {
			conversation(id: $id) {
				...FullConversation
			}
		}
	}
	${FullConversationFragmentDoc}
`;
export type GetConversationComponentProps = Omit<
	ReactApollo.QueryProps<GetConversationQuery, GetConversationQueryVariables>,
	'query'
> &
	(
		| { variables: GetConversationQueryVariables; skip?: false }
		| { skip: true });

export const GetConversationComponent = (
	props: GetConversationComponentProps
) => (
	<ReactApollo.Query<GetConversationQuery, GetConversationQueryVariables>
		query={GetConversationDocument}
		{...props}
	/>
);

export type GetConversationProps<TChildProps = {}> = Partial<
	ReactApollo.DataProps<GetConversationQuery, GetConversationQueryVariables>
> &
	TChildProps;
export function withGetConversation<TProps, TChildProps = {}>(
	operationOptions?: ReactApollo.OperationOption<
		TProps,
		GetConversationQuery,
		GetConversationQueryVariables,
		GetConversationProps<TChildProps>
	>
) {
	return ReactApollo.withQuery<
		TProps,
		GetConversationQuery,
		GetConversationQueryVariables,
		GetConversationProps<TChildProps>
	>(GetConversationDocument, {
		alias: 'withGetConversation',
		...operationOptions,
	});
}
```
One could just generate this:
```ts
export const GetConversationDocument = gql`
	query GetConversation($id: ID!, $messageCount: Int!) {
		messenger {
			conversation(id: $id) {
				...FullConversation
			}
		}
	}
	${FullConversationFragmentDoc}
`;
export const GetConversation = query<GetConversationQueryVariables, GetConversationQuery>({
	operationType: 'Query',
	document: GetConversationDocument,
        name: "GetConversation",
});
```

The `query` function could be defined in "userland" with methods like `reactHoc(...)` or `Component`.
This leads to smaller bundle sizes since less code is generated and more flexibility since the generated types are more generic.

In my case, I wanted a typed version of watch queries that yield a mobx observable. Sadly, this is not possible without generating even more code.

**Comment by dotansimha** [comment]
@ardatan can you please take a look?

**Comment by ardatan** [comment]
@dotansimha I think we can wait for new react apollo version. What do you think?

**Comment by hediet** [comment]
I would like to improve this code:
```ts
this.authenticatedClientService.currentClient
			.mutate<
				ArchiveConversationMutation,
				ArchiveConversationMutationVariables
			>({
				mutation: ArchiveConversationDocument,
				variables: {
					id: conversationId,
				},
			})
```
With the code I would generate, it would look like this:
```ts
ArchiveConversation.mutate(this.authenticatedClientService.currentClient, {
  id: conversationId,
})
```
As this is quite blocking for us, I am going to start implementing our own code generator plugin that supports this.

**Comment by dotansimha** [comment]
@hediet if you are using only `typescript-operations`, you'll need to provide generics to your client. If you are using `typescript-apollo-angular` (or, any other of our clients wrappers) - you can just use the generated component as-is. 

Also, which do you need to access the client manually? you can use `withHooks` and then just `useArchiveConversationMutation()` and that's it, without specifying types of generics. 

If you need a custom code, you can write plugin and communicate with the existing plugins, and this way to get custom code that fits your needs (and if that's a common pattern, you can submit a PR).

If I missed something, feel free to add a reproduction that we can use (using codesandbox) and re-open this issue.

**Comment by hediet** [comment]
I was basically looking for https://github.com/dotansimha/graphql-typed-document-node ;)
