### ISSUE TITLE
How does one use the resolvers plugin? Or is that not even applicable here?

### ISSUE THREAD

**Issue by JosephCarrington** [dotansimha/graphql-code-generator#2158]
**IF** I have the following types:
```
type Event {
  title: String!
  venue: Venue!
}

type Venue {
  title: String!
}
```

**BUT** I use an external datasource, which replies with a response like
```
event = {
  title: "Cool Place",
  venueId: 123
}
```

**THUS** I only want to go about getting a venue by it's ID if the end user has actually requested it:
THIS:
```
query {
  events {
    title
    venue
  }
}
```
NOT THIS:
```
query {
  events {
    title
  }
}
```
because it takes an extra HTTP request to, let's say, `getVenueById`.

**THEN** what should the return type of the Event resolver be?

```ts
import { Event, Venue } from './generated/graphql'
const resolvers = {
  Query: {
    async events(_, __, { dataSources }: Context): Promise<Event[]> {
      const events = await dataSources.someSource.getEvents()
      return events.map(event: ??? => ({
        title: event.title,
        // Not putting a venue here throws an error, because Events typeDef MUST HAVE a Venue
        // Putting venue: event.venueId here doesn't work because a number is not a Venue
        // But I know that if the end user requests event -> venue, the below resolver will work
      })
    }
  }
  Event: {
    async venue(parent: ???, __, { dataSources }: Context): Promise<Venue> {
      const { venueId } = parent
      const venue = await dataSources.someSource.getVenueById(venueId)
      return venue
    }
}
```

I think that maybe this is what the resolvers plugin attempts to solve, but it is not clear to me at all how to use those types. Any advice, even a few keywords to search for, would be so very appreciated. Thank you for your time.

**Comment by dotansimha** [comment]
Hi @JosephCarrington ! How are you? 
To use the `typescript-resolvers` plugin, just add it to your codegen.yml, and you'll get a new type generated- `Resolvers`. You can import it and assign this type to any of your resolvers objects:

```ts
import { Resolvers } from './generated/graphql'
const resolvers: Resolvers = {
  Query: {
    // ...
  }, // ...
};

```

And that's it! Now all your resolvers functions within this `resolvers` object will be type-safe (and you'll have auto-complete in your IDE for the args, parent type and return type).

I also recommend you to take a look at the documentation on our website, and read the docs about `mapping` feature (https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers-overwrite-parents-and-resolved-values) - you can use it to map between GraphQL types and your model types, and it will make it easier for you to integrate it with your backend types.
