### ISSUE TITLE
Wrong component prop type names when using typescript-react-apollo

### ISSUE THREAD

**Issue by jlkiri** [dotansimha/graphql-code-generator#2160]
**Describe the bug**
As a result of #2116, using `operationResultSuffix` leads to generation of wrong React Apollo component prop type names. They are not updated, but operation result type name is generated correctly.

**To Reproduce**
1. Specify `operationResultSuffix` in `config.yml` (e.g. `"Response"`), when using `typescript-react-apollo` plugin.
2. Generate output.
3. Check the generated file and make sure that `TData` in generated `ReactApollo.DataProps<TData, TGraphQLVariables>` has a wrong type name. E.g. `MyOperationQuery` instead of `MyOperationQueryResponse`.

**Expected behavior**
Component prop type names are updated too when `operationResultSuffix` is used.

**Environment:**
Any

**Additional context**
This is my mistake and I will fix in a PR.

**Comment by mohsen89z** [comment]
Same! Also, Query argument's name is wrong!

**Comment by jlkiri** [comment]
I did some tests and it looks like only generated React Apollo HOC props are affected by the change. The only current workaround is to set `withHOC` to `false`.  
This is a pretty easy fix, I'll send a PR.

**Comment by dotansimha** [comment]
Fixed in 1.5.0 🎉
