### ISSUE TITLE
How to access the type of an array?

### ISSUE THREAD

**Issue by MarkKahn** [dotansimha/graphql-code-generator#2163]
I'm in the process of converting our types from using apollo to this lib and am running into a small issue I'm hoping someone has a solution for.

In Apollo, all of the nested types are `_` delimited, e.g. `someQuery_field_subField`, which makes using those types in sub-components pretty easy.

With this lib types in Arrays don't seem to be readily accessible, so I'm not sure how to access them.  e.g.:

```gql
fragment foo on bar {
  things {
    id
    name
  }
}
```

yields:

```ts
type fooFragment {
  things: Maybe<Array<{ __typename?: 'thing'; id: string; name: string }>>;
};
```

How do I gain access to the `{ __typename?: 'thing'; id: string; name: string }` object so that I can do something like:

```js
class Things extends React.Component<things> {
}

class Thing extends React.component<thing> {
}
```

**Comment by dotansimha** [comment]
Hi @MarkKahn ! 
TypeScript supports accessing to any inner type, you can use `fooFragment[things][0]` to get the inner type. 
Note that if you'll use fragments for `thing`, the codegen will generate a type for the fragment, and will use it in the list type.
