### ISSUE TITLE
Catch ‘Error writing to store caused by same queries without ID’

### ISSUE THREAD

**Issue by mhuconcern** [dotansimha/graphql-code-generator#2185]
**Is your feature request related to a problem? Please describe.**
https://github.com/apollographql/apollo-client/issues/2510

Apollo codegen catches this issue, It would be nice to have to catch this before it fails on production.
**Describe the solution you'd like**

Throw warning on code generation

**Comment by dotansimha** [comment]
@mhuconcern Can you please add more details on this issue? and point us to an example?

**Comment by mhuconcern** [comment]
Example 
Query 1 : 
`query getOrganizationUsers($id: ID!) {
     organization(id: $id) {
      id
      user
     }
}`

Query 2: 
`query getOrganizationRegions($id: ID!) {
     organization(id: $id) {
        region
     }
}`

It would be nice if the generation process would throw a warning saying that id is missing in query 2. Apollo codegen catches this issue during the generation process.

**Comment by dotansimha** [comment]
Hi @mhuconcern , Apollo does that because it requires `id` to function properly. The codegen doesn't require that, and I think it's out of the codegen scope. 
@ardatan @kamilkisiela what do you think?

**Comment by ardatan** [comment]
@dotansimha  Having this kind of feature inside an IDE plugin would be better in my opinion.

**Comment by dotansimha** [comment]
Closing for now. If this is relevant for more developers, please feel free to comment here and we'll consider to re-open and implement it.
