### ISSUE TITLE
Having avoidOptionals: false breaks compatibility with Apollo Server

### ISSUE THREAD

**Issue by fabis94** [dotansimha/graphql-code-generator#2188]
![image](https://user-images.githubusercontent.com/938316/61405991-a9200000-a8e3-11e9-9fc9-b4617e2fbeaa.png)

I may be wrong (TypeScript errors make me go crosseyed), but it looks like Apollo Server expects my custom scalar type to not be optional. However, with avoidOptionals: false, this tool generates all resolvers as optional. 

I need this option to be false because I don't want to define resolvers for all of my custom types which Apollo Server will resolve automatically. Any ideas how to resolve this?

This is what the schema looks like:

``` 
# Custom scalars
  scalar DateTime

  # Root types (Query, Mutation, Subscription)
  type Query {
    users: [User!]
  }

  type Mutation {
    doNothing: String
  }

  # Custom types
  type User {
    id: ID!
    email: String!
    userName: String!
    createdAt: DateTime!
  }
```

And this is how I've defined the resolver for the DateTime scalar:
```
import { GraphQLScalarType, Kind } from "graphql";

export default {
  DateTime: new GraphQLScalarType({
    name: "DateTime",
    description: "DateTime represented as an ISO8601 Zulu string",
    parseValue(value: string): Date {
      return new Date(value);
    },
    serialize(value: Date): string {
      return value.toISOString();
    },
    parseLiteral(ast): Date | undefined {
      if (ast.kind === Kind.STRING) {
        return new Date(ast.value);
      }

      return undefined;
    }
  })
};
```

**Comment by dotansimha** [comment]
@fabis94 can you please share your `codegen.yml` file and the version of the codegen you use? 
Also, do you use `useIndexSignature`? (https://graphql-code-generator.com/docs/plugins/typescript-resolvers#useindexsignature-boolean-default-value-false)

**Comment by fabis94** [comment]
@dotansimha Hi, I resolved this by setting 'useIndexSignature' to true. I'm confused as to why, though, and the documentation is a bit too concise for me to understand what this property actually does. Can you please elaborate what it means and why it solves this issue?

**Comment by lookfirst** [comment]
@dotansimha 

Latest version of codegen.

I had a similar issue and useIndexSignature fixed it for me.

```
src/index.ts:48:2 - error TS2322: Type 'Resolvers<Context>' is not assignable to type 'IResolvers<any, any> | IResolvers<any, any>[] | undefined'.
  Type 'Resolvers<Context>' is not assignable to type 'IResolvers<any, any>'.
    Property 'Node' is incompatible with index signature.
      Type 'NodeResolvers<Context, Node> | undefined' is not assignable to type 'GraphQLScalarType | IEnumResolver | (() => any) | IResolverObject<any, any, any> | IResolverOptions<any, any, any>'.
        Type 'undefined' is not assignable to type 'GraphQLScalarType | IEnumResolver | (() => any) | IResolverObject<any, any, any> | IResolverOptions<any, any, any>'.
```

```
export const typeDefs = gql`
    """An object with an ID"""
    interface Node {
        id: ID!
    }

    type Rig implements Node {
        id: ID!
        type: String
        name: String
    }

    type Query {
        getRig(id: ID!): Rig
    }

    schema {
        query: Query
    }
`;
```

```
export const resolvers: Resolvers = {
	Query: {
		getRig: (_: any, args: QueryGetRigArgs, context: Context, info: GraphQLResolveInfo) => {
			console.log(info);
			return {
				id: `Hello world! ${args.id}`,
				name: 'rig name'
			}
		},
	} as QueryResolvers,
	Node: {
		__resolveType(query: Query, context: Context, info: GraphQLResolveInfo) {
			return null;
		}
	} as NodeResolvers,
};
```

```
overwrite: true
schema: "./schema.graphql"
documents: null
generates:
  src/gql/generated.ts:
    config:
      contextType: ../index#Context
    #      useIndexSignature: true
    plugins:
      - "typescript"
      - "typescript-resolvers"

  ./graphql.schema.json:
    plugins:
      - "introspection"

```

**Comment by dotansimha** [comment]
@fabis94 see: https://github.com/dotansimha/graphql-code-generator/issues/1133#issuecomment-456812621 

Closing :)

**Comment by lookfirst** [comment]
@dotansimha Should add something to the documentation to let people know it is required with Apollo.

**Comment by dotansimha** [comment]
Thanks @lookfirst . done in https://github.com/dotansimha/graphql-code-generator/commit/9f0662a798f9cb1bb28c96623d0347c212968913#diff-2e4db0927cea96d01402e7d186a1451aR134
