### ISSUE TITLE
Why are ReactApollo.DataProps wrapped in Partial<> for HOC Props?

### ISSUE THREAD

**Issue by bensaufley** [dotansimha/graphql-code-generator#2192]
`typescript-react-apollo` will generate the following Props for a HOC for a query named `GetThings`:

```ts
export type GetThingsProps<TChildProps = {}> = Partial<
  ReactApollo.DataProps<GetThingsQuery, GetThingsQueryVariables>
> &
  TChildProps;
```
Why is `ReactApollo.DataProps` wrapped in `Partial`? Looking at [`withQuery`](https://github.com/apollographql/react-apollo/blob/9e4b573a5ae8ee068bc6f9229e6d84b36974da6b/packages/hoc/src/query-hoc.tsx#L20), which is what `withGetThings` wraps, `WrappedComponent` should expect `TProps & TChildProps`, where `TChildProps = DataProps<…>`. Is `data` ever _not passed in_? Is it marked as optional simply to avoid _requiring_ that the `WrappedComponent` expect `DataProps`? If so, is there a way to … not do that? The alternative is that `const { data: { loading } } = this.props` blows up because `data` is marked as optional.

Is `data` ever actually undefined? It seems like it should never be undefined.

**Comment by dotansimha** [comment]
@ardatan can you please take a look?

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/2297

**Comment by dotansimha** [comment]
Fixed in 1.5.0 🎉

**Comment by valerybugakov** [comment]
@dotansimha it seems that there might be a case when `data` will be missing. When developer specifies `config.props` it might not pass `data` down. But it will still be required because of `QueryNameProps<TChildProps>`.

Is there a way to tell TS about that using current typings?

**Comment by dotansimha** [comment]
@valerybugakov Can you please explain? 
With the latest Apollo-Client, `data` might not be set (in past versions, it was `{}`, but now it could be `undefined`).

**Comment by ardatan** [comment]
@valerybugakov @dotansimha We directly reference to React Apollo's typings with some generics. So we don't generate all the signature for HOCs, hooks or components. If there is a problem in Apollo's typings, I think an issue should be opened in their repo.

**Comment by valerybugakov** [comment]
If developer renames `data` prop with it's own alias, for example: `patientData` then, `data` prop will not exist in the child component. Code generator output for HOCs: 

```ts
// Generated output
export type TPatientProps<TChildProps = {}> = ApolloReactHoc.DataProps<
  TPatientQuery,
  TPatientQueryVariables
> &
  TChildProps;
export function withPatient<TProps, TChildProps = {}>(
  operationOptions?: ApolloReactHoc.OperationOption<
    TProps,
    TPatientQuery,
    TPatientQueryVariables,
    TPatientProps<TChildProps>
  >,
) {
  return ApolloReactHoc.withQuery<
    TProps,
    TPatientQuery,
    TPatientQueryVariables,
    TPatientProps<TChildProps>
  >(PatientDocument, {
    alias: 'patient',
    ...operationOptions,
  });
}

// Usage of the generated HOC
const withPatientData = withPatient<TPatientProps, TPatientChildProps>({
  name: 'patientData',
  options: props => ({
    variables: {
      patientId: props.match.params.patientId,
    },
  }),
})
```

`TPatientProps<TChildProps>` — this line marks `data` prop as required and there's no way to change it after code is generated. Does it make sense?
