### ISSUE TITLE
Typescript Operations don't handle unions properly

### ISSUE THREAD

**Issue by tempname11** [dotansimha/graphql-code-generator#2200]
**Describe the bug**
The typescript-operations plugin generates incorrect types for unions.

There are two problems, as far as I can see:

1) Not all union cases are generated (the server may actually return every one of them, regardless of what cases the query fragments specify).
2) If fragments operate on interfaces, the types are joined by `&` in the overall type, instead of just the cases which implement this interface.

**To Reproduce**
Minimal repro is at https://github.com/tempname11/gcg-example
See the output at https://gist.github.com/tempname11/c1f9a8ca97530bae078cfd55654f3068

example1 is correct:
```
  example1:
    | ({ __typename: "Foo" } & Pick<Foo, "foo">)
    | ({ __typename: "Bar" } & Pick<Bar, "bar">);
```
However, both example2 and example 3 are incorrect:
```
  example2: { __typename: "Foo" } & Pick<Foo, "foo">;
  example3: ({ __typename: "Foo" | "Bar" } & Pick<Common, "common">) &
({ __typename: "Foo" } & Pick<Foo, "foo">);
>;
```

**Expected behavior**
```
  example2:
    | ({ __typename: "Foo" } & Pick<Foo, "foo">)
    | ({ __typename: "Bar" })
  example3:
    | ({ __typename: "Foo" } & Pick<Foo, "foo"> & Pick<Common, "common">))
    | ({ __typename: "Bar" } & Pick<Common, "common">))
>;
```

**Environment:**

- OS: macOS 10.14.5
- `@graphql-codegen/...`: 1.4.0
- NodeJS: 10.16.0

**Comment by n1ru4l** [comment]
I created a duplicate with some more context and a codesandbox example: https://github.com/dotansimha/graphql-code-generator/issues/2240

**Comment by n1ru4l** [comment]
I just created a pull request with failing tests: #2248

**Comment by dotansimha** [comment]
Thank you! Will take a look very soon.

**Comment by dotansimha** [comment]
Closing this for now, let's continue discussing it here: https://github.com/dotansimha/graphql-code-generator/issues/2240 (it has more context and examples)
