### ISSUE TITLE
[Docs] typescript-mongodb is not a dev-dependency but a default one

### ISSUE THREAD

**Issue by smeijer** [dotansimha/graphql-code-generator#2215]
[The typescript-mongodb docs](https://graphql-code-generator.com/docs/plugins/typescript-mongodb) suggest to install the plugin, and save it to our `devDependencies`
 
```
yarn add -D @graphql-codegen/typescript-mongodb
```

yet, we also need to import the `DIRECTIVES`, and add them to our schema in production:

```
import { makeExecutableSchema } from 'graphql-tools';
import { DIRECTIVES } from '@graphql-codegen/typescript-mongodb';

const schema = makeExecutableSchema({
  typeDefs: [
    DIRECTIVES,
    // the rest of your GraphQL types
  ],
  resolvers,
});
```

Shouldn't `@graphql-codegen/typescript-mongodb` be installed as a default dependency?

```
yarn add @graphql-codegen/typescript-mongodb
```

I believe that it's important to mention this one correct, especially because all other plugins indeed are devDependencies.

**Comment by dotansimha** [comment]
You are right, @smeijer , thank you, we'll fix soon.

**Comment by dotansimha** [comment]
Update, will deploy soon. Thanks @smeijer !
