### ISSUE TITLE
typescript-mongodb and typescript-react-apollo require conflicting file extension

### ISSUE THREAD

**Issue by smeijer** [dotansimha/graphql-code-generator#2216]
**Describe the bug**
I'm trying to use `typescript-mongodb` together with `typescript-react-apollo`. The first requires the extension to be `ts`, while the last requires a `tsx`. So, either I cannot use one of them, or I need to have two output files. Which is unwanted, as they do share a lot of base types.

Shouldn't all plugins that require `ts` also be fine with `tsx`?

https://github.com/dotansimha/graphql-code-generator/blob/d8316ef16ec34914d771a5409207f191c1cd6e0a/packages/plugins/typescript/mongodb/src/index.ts#L136-L140

**To Reproduce**

https://codesandbox.io/s/graphql-codegen-issue-template-2bd6r

1. My GraphQL schema:

* irrelevant *

2. My GraphQL operations:

* irrelevant *

3. My `codegen.yml` config file:

```yml
generates:
  types.tsx:
    plugins:
      - 'typescript'
      - 'typescript-react-apollo'
      - 'typescript-mongodb'
```

**Expected behavior**
Plugins required to have a `ts` extension, should also be fine with a `tsx` extension.

**Environment:**

```
- OS: CodeSandbox
- NodeJS: v10.16.0
- @graphql-codegen/add: 1.3.1
- @graphql-codegen/cli: 1.3.1
- @graphql-codegen/typescript: 1.3.1
- @graphql-codegen/typescript-mongodb: 1.4.0
- @graphql-codegen/typescript-operations: 1.3.1
- @graphql-codegen/typescript-react-apollo: 1.4.0
- graphql: 14.3.1
```

**Additional context**
Just trying to generate both `react-apollo` types and `mongodb` types. Can't get it to work without breaking up the file. But, generating two files also mean a lot of duplicates, as they won't import a shared 'base file'.

The problem is with the plugins mentioned above. At the end I'm trying to generate something using the plugins:

```yml
plugins:
  - 'typescript'
  - 'typescript-operations'
  - 'typescript-resolvers'
  - 'typescript-react-apollo'
  - 'typescript-mongodb'
```

**Comment by dotansimha** [comment]
Hi @smeijer ,
can you please explain the use case of using both of this plugins together? 
The `typescript-mongodb` is for backend, and `typescript-react-apollo` is for client-side. 
We can allow `.tsx` in `typescript-mongodb`, but we need make sure the use-case is valid first.

**Comment by smeijer** [comment]
I'm using Meteor so my client and server code are shared. But isn't this also the case with server side rendering?

I can imagine that one would like to have the bundles separate if using different code bases for client and server side. But Meteor really still an exception to that rule? 

Basically, I currently have a folder structure like:

```
src
  /client/main.js
  /common
    /components
      /...
  /server
    /api # graphql typeDefs & resolvers
    /main.js # config apollo, SSR routes
  /generated
    /graphql.tsx
    /mongo.ts
```

So, the react components are used by both server and client. Thereby, `react-apollo` (hooks) are required in both scopes. Mongo wouldn't be required by the client. But as the code lives in a single repo, with the same root folder (`./src`), it's unnecessary to have the same base definitions in both generated files.

I believe that it would also be fine to separate the files even further if that would be possible. And make them import each other. But as far as I'm aware, that's currently not possible, and would be harder to implement.

What I'm saying is, types like Scalars (but also every other Graphql type), are currently saved in all my generated files.

```
export interface Scalars {
  ID: string;
  String: string;
  Boolean: boolean;
}
```

So instead of making 1 HUGE file with base types, mongo types, react hooks. It would be even better to have them import each other when required.

```
// graphql.ts
export interface Scalars {
}

export interface Comment {
}
```

```
// react.tsx
import * as graphql from './graphql.ts'
```

```
// mongo.ts
import * as graphql from './graphql.ts'
```

My main goal is to prevent generated files from containing the same definitions. Because

- That would mean double file size (I'm aware it's filtered out)
- That would mean double lines in github PR (reviews)
- Developers would be confused from which `generated` file to import

**Comment by smeijer** [comment]
While writing down the post above, I though of a very simple solution actually.

```yml
  generated/graphql.tsx:
    documents: 'src/common/**/*.graphql'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-resolvers'
      - 'typescript-react-apollo'

  generated/mongo.ts:
    plugins:
      - add: *top-comment
      - add: import { Maybe } from './graphql';
      - 'typescript-mongodb'
```

That one seems to work. Just manually adding the `Maybe` import. I think this issue can be closed than. It would mean I need to keep an eye on other required imports, but that's doable.

Or, keep it open, if you want to add functionality to automatically add those kind of imports from a `base file`. 😇

**Comment by dotansimha** [comment]
@smeijer Meteor is a valid use case, but you can still generate 2 files. 
You solution is also looks elegant and I think workaround this issue in a nice way. 
In order to separate `typescript-operations` from `typescript`, you can do use `namespacedImportName: Types` and use `add` to add an import like `import * as Types from './base-types';` (for `typescript-operations`). 

You are right that they share the same base types, but at the moment they couldn't be separated. 

If you think this should be solved - let's move this to a new issue with more details on the use can and your expected output.
