### ISSUE TITLE
Remove export on types and CacheControlScope enum?

### ISSUE THREAD

**Issue by hiphigi** [dotansimha/graphql-code-generator#2232]
In my instance, my Typescript types/interfaces only work when they're _not_ exported as a module. Is there a way to turn off the export keyword so that it isn't inserted before every exported type?

I'm also curious as to what CacheControlScope accomplishes when it isn't referenced. If it's unused, can this be disabled as well?

**Comment by dotansimha** [comment]
Hi @hiphigi 
I think it's the same issues as in: https://github.com/dotansimha/graphql-code-generator/issues/2246 , please refer to my answer there. Closing this at the moment to avoid duplicates. 

Can you please explain your question regarding `CacheControlScope`? I'm not sure it's related to our implementation.
