### ISSUE TITLE
Modify URL schema loader to use custom fetch

### ISSUE THREAD

**Issue by jlkiri** [dotansimha/graphql-code-generator#2271]
**Is your feature request related to a problem? Please describe.**

`graphql-toolkit` changed its dependency for URL schema loading. It switched to `cross-fetch` from `request`. The problem is that `cross-fetch` does not respect the HTTP_PROXY environment variable. This indirectly makes it impossible to use `graphql-code-generator` behind a (corporate) proxy.

In `0.5.0` it got fixed so you can inject custom fetch: https://github.com/ardatan/graphql-toolkit/pull/190

**Describe the solution you'd like**
Internally modify `graphql-codegen-cli` package (`load.ts`) to use `omni-fetch` for schema loading, because `omni-fetch` respects HTTP_PROXY environment variable.

**Describe alternatives you've considered**
Specify fetch library in `graphql-code-generator` configuration. But it seems pretty hard to implement and not a very useful functionality for most users?

**Additional context**

**Comment by dotansimha** [comment]
@ardatan can you please take a look?

**Comment by jlkiri** [comment]
Wow, thank you!

**Comment by dotansimha** [comment]
Fixed in 1.6.0
