### ISSUE TITLE
Generate per operation file into specific folder

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#2287]
That would be awesome to have something like `near-operation-file` but to have it generated to the `/generated` or whatever folder file by file, operation by operation, not near but in some root `/generated` where you have `baseTypes` for example.
Like
```pages/
   some-page.tsx
   another-page.tsx
generated/
  baseTypes.ts
  some-page.types.ts
  another-page.types.ts
```
Let's name it `each-operation-file` :D 

Why? Because Gatsby, for example, is extremely annoying, and if I’ll generate these `*.types.ts` alongside the `/pages`, it will generate a freaking empty static page with the URL of `/another-page-types` and while in dev mode it’s ok, in build it will break.

I found a workaround that using page creator plugin like
```
{
  resolve: `gatsby-plugin-page-creator`,
  options: {
    path: `${__dirname}/src/views`,
    ignore: [`**/*.generated.(js|ts)?(x)`],
  },
}
```
But it doesn’t override ignores for `/pages` so I just put `gitkeep` into the `pages` and my new `/pages` folder is `/views`now  :) 

I think `next.js` may have the same issues because they are both use project structure and files in specific folders to enable their “magic”

Also, it will ensure proper dynamic imports/tree-shaking and other stuff as a regular `near-operation-file` so you use stuff chunk by chunk.

**Comment by dotansimha** [comment]
Available in 1.7.0
Thanks @fforres
