### ISSUE TITLE
Publish package to other package managers

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#23]
- [ ] Homebrew
- [ ] MacPorts
- [ ] ?

**Comment by alexgorbatchev** [comment]
Is that really necessary? Feels like this might be adding too much overhead.

**Comment by dotansimha** [comment]
@alexgorbatchev at the moment, you have to install NodeJS manually and then use `npm` or `yarn`, and that something that Swift developers for example does not use on daily basis, so I thought about publishing to brew to make it easier for them to start with it as a CLI tool, without installing NodeJS manually.
It might be an overhead at the moment, that's why I think that we will do it in the future and not now..
