### ISSUE TITLE
Move to official apollo react hooks in react-apollo plugin

### ISSUE THREAD

**Issue by feelfreelinux** [dotansimha/graphql-code-generator#2301]
The `react-apollo` plugin has a `useHooks` option that enables a react hooks generator. It's a great feature, however for now it's using unofficial `react-apollo-hooks` library. 

We should consider moving to official `@apollo/react-hooks`.
Note: the official apollo hooks support is still in beta, so maybe it's a better idea to wait until stable release.

**Comment by ardatan** [comment]
@feelfreelinux 
See here 
https://github.com/dotansimha/graphql-code-generator/issues/2112
