### ISSUE TITLE
Add support for useLazyQuery

### ISSUE THREAD

**Issue by immortalx** [dotansimha/graphql-code-generator#2302]
@apollo/react-hooks added useLazyQuery
https://www.apollographql.com/docs/react/api/react-hooks/#uselazyquery

It's possible to support it?

Adding a configuration like:
withLazyQuery: true

And generating a useQueryLazyComponent for each query, i wonder if it's the best way to do it.

**Comment by n1ru4l** [comment]
Maybe it would be a better solution to allow controlling what kind of code you want to generate for which query/mutation? E.g. by using directives on the operation definition?

I may not want to generate a lazy query component for each query in my project? Or is this something that should be handled by the bundler aka tree shaking?

**Comment by immortalx** [comment]
A similar scenario already happens if you use hooks and hoc/component, in the end it/should be handled by the bundler.

**Comment by ardatan** [comment]
That would be nice! I'll add this soon.

**Comment by ardatan** [comment]
You can try it in the following canary version;
```
 1.5.1-alpha-e4e10196.6+e4e10196
```

**Comment by immortalx** [comment]
Wow, that was fast. Seems to be working fine for me!
Thank you @ardatan

**Comment by dotansimha** [comment]
Added in 1.6.0.

**Comment by DarkLite1** [comment]
It would be great if useLazyQuery could also be added to the Vue plugin #5258

**Comment by ejkkan** [comment]
Hey!
So is lazy queries supported?
I've been trying to figure out how and browsing docs but without success yet.
What an I missing?
Does anyone have a code sample?

**Comment by n1ru4l** [comment]
@ejkkan Ir is not supported in the apollo react hooks plugin. However, you can either use the `client-preset` or `typed-document-node` plugin for generating typed document nodes that you can then use with `useLazyQuery` from apollo client.
