### ISSUE TITLE
Custom template does not work with output directory (--out) in node module template

### ISSUE THREAD

**Issue by GD-Aichi** [dotansimha/graphql-code-generator#231]
In my [node module template](https://github.com/GD-Aichi/graphql-codegen-sequelize-typescript) does not work the output directory.
```
gql-gen --export ./dist/generator/schema.js -t graphql-codegen-sequelize-typescript --out ./src/models/types/
```
config file
```js

const config = {
  inputType: 'MULTIPLE_FILES',
  templates: {
    type,
    inputType,
    interface: interfaceTemplate,
    enum: enumTemplate,
    scalar,
    union,
    'loaders.ts.schema.handlebars': loaders,
    'loaders-export.ts.schema.handlebars': loadersExport
  },
  flattenTypes: true,
  filesExtension: 'ts',
....
```
The files 'loaders.ts' and 'loaders-export.ts' are writing in the root path, but output directory is './src/models/types/'.

Is it a bug?
In gql-gen.json file is working with loaders.ts.schema.handlebars file.

**Comment by dotansimha** [comment]
@GD-Aichi I think we need to think about it. 
If you have a nested tree of templates inside your `--project` directory, how to you expect it to behave? 

I think maybe we need to preserve the structure of the templates, but output it to the out directory. 
What do you think?

**Comment by dotansimha** [comment]
Related: https://github.com/dotansimha/graphql-code-generator/pull/210

**Comment by dotansimha** [comment]
Fixed in #210

**Comment by GD-Aichi** [comment]
I think the structure of the templates is good and enough for my. But output of the schema file must put to the out directory.
Pull #210 don't fixed it, i tested that.

**Comment by dotansimha** [comment]
@GD-Aichi any idea how to resolve this?

**Comment by GD-Aichi** [comment]
I looked in the code for a minutes and if the line 293 in to 
```js
prefix // or prefix: prefix 
```
then the files will writing in out directory.
I don't know, what do the master version do.
https://github.com/dotansimha/graphql-code-generator/blob/da33ee50a7fa82a17ad4595be124cd1639deb6db/packages/graphql-codegen-compiler/src/generate-multiple-files.ts#L293-L299
I will checking the master build.

**Comment by GD-Aichi** [comment]
I think you can close the ticket. Version 0.9.1 fixes my problem.
