### ISSUE TITLE
breaking changes in 1.5.0

### ISSUE THREAD

**Issue by jacobheric** [dotansimha/graphql-code-generator#2316]
Sorry, not exactly a bug. Let me know if you want me to ask this somewhere else. 

I've tried upgrading our app from 1.4.0 to 1.5.0 (to get a bunch of features and bugfixes we need) and I see this project has moved to react apollo v3. 

I've installed all the obvious missing new dependencies, @apollo/react-* etc, though I still have a bunch of unmet peer dependency warnings from those.  I've got the app running but all of our uses of the generated render props component are broken. I've started to dig in but it looks like these are not going to be quick fixes. 

Is there a way to use 1.5.0 without react apollo v3?

**Comment by dotansimha** [comment]
Hi @jacobheric ! 

Please see @ardatan 's comments here: https://github.com/dotansimha/graphql-code-generator/pull/2182#issuecomment-519202681
