### ISSUE TITLE
--out doesn't work for config json

### ISSUE THREAD

**Issue by mirkara** [dotansimha/graphql-code-generator#232]
Running:
`gql-gen --project ./src/  --url <url> --config src/config.json --out ./output
`
Output:
```
Loading GraphQL Introspection from remote: <url>
Loading config file from: <path_to_config>
Generated file written to <where_templates_are>
```
The generated files go to where the templates are and not the specified --out path. 

Any ideas why?

**Comment by GD-Aichi** [comment]
That sounds like my problem #231.

**Comment by dotansimha** [comment]
It's the same issue in https://github.com/dotansimha/graphql-code-generator/issues/231. 
Closing and we'll continue to discuss it there.
