### ISSUE TITLE
Unknown type "JSON" error when using graphql-type-json 

### ISSUE THREAD

**Issue by kgajera** [dotansimha/graphql-code-generator#2320]
**Describe the bug**

I'm using [graphql-type-json ](https://github.com/taion/graphql-type-json) to add a JSON scalar type. When running the code generator, I'm getting the following error: `Error: Unknown type "JSON".`

**To Reproduce**
Created the following repo containing an example of the issue: https://github.com/kgajera/graphql-code-generator-json-scalar-bug

**Expected behavior**
The JSON scalar type is recognized.

**Comment by dotansimha** [comment]
@kgajera Thank you for reporting it. I managed to reproduce it in `graphql-toolkit`. Working on a fix.

**Comment by dotansimha** [comment]
Fixed in 1.6.0.
