### ISSUE TITLE
Generated TypeScript arrays always allows null values (?)

### ISSUE THREAD

**Issue by Hubro** [dotansimha/graphql-code-generator#2325]
**Describe the bug**

When my GraphQL schema specifies an optional array of `X` and I use `graphql-code-generator` to generate TypeScript typings for that schema, it generates an optional array of `Maybe<X>`, which means that the typings will accept an array like `[null, null, null]`.

**To Reproduce**

Go to the example box at https://graphql-code-generator.com/

Set it to TypeScript and input this schema:

```graphql
type Program {
  id: ID!
  series: [Series]
}

type Series {
  id: ID!
  program: Program!
  notes: String!
  totalPoints: Int
}
```

Press generate. The relevant output is:

```typescript
export type Program = {
  __typename?: 'Program',
  id: Scalars['ID'],
  series?: Maybe<Array<Maybe<Series>>>,
};
```

The `series` field is now an optional field which accepts either `null` or an array of either `Series` objects or `null`s. This is unusable, at least for my project, as it accepts `[null, null, null]` as a value for the `series` field.

I would expect the output to be:

```typescript
export type Program = {
  __typename?: 'Program',
  id: Scalars['ID'],
  series?: Maybe<Array<Series>>,
};
```

Which would let the `series` field contain either `undefined`, `null` or an array of `Series` objects.

Or:

```typescript
export type Program = {
  __typename?: 'Program',
  id: Scalars['ID'],
  series?: Array<Series>,
};
```

Which would let the field contain either `undefined` or an array of `Series` objects.

Why does the code generator do this? Is there some way to avoid it?

**Comment by JKillian** [comment]
@Hubro, the types in your original schema are wrong (the code generator is actually acting correctly). Your schema specifies an optional array of optional `Series`s.

What you need to do is change your schema:

```diff
type Program {
   id: ID!
-  series: [Series]
+  series: [Series!]
}
```

**Comment by Hubro** [comment]
Ah, that makes sense.

My schema is automatically generated by graphite-python from a many-to-one relationship in Django, so it's weird that it allows an array of null values.

Not a problem with graphql-code-generator though, thanks for your time @JKillian :)
