### ISSUE TITLE
Support extend input

### ISSUE THREAD

**Issue by ChrisLahaye** [dotansimha/graphql-code-generator#2333]
**Is your feature request related to a problem? Please describe.**

Generated TypeScript type does not contain `extend input` properties.

**Describe the solution you'd like**
When using `extend input` I want the generated TypeScript type to contain the extended properties.

**Describe alternatives you've considered**
None

**Comment by dotansimha** [comment]
@ChrisLahaye what do you mean by `Generated TypeScript type does not contain`? You mean that the codegen ignores `extend input`? or something is missing with the output? 
Can you please create a small reproduction in a repo/sandbox?

**Comment by ChrisLahaye** [comment]
@dotansimha Yes indeed, the DSL syntax `extend input` is not parsed by codegen. Hence the extensions are not in the output.

**Comment by dotansimha** [comment]
I fixed it in `graphql-toolkit`, can you try the latest alpha? `1.5.1-alpha-67fbd2c9.21`

**Comment by dotansimha** [comment]
Fixed in 1.6.0.

**Comment by ChrisLahaye** [comment]
@dotansimha thank you!
