### ISSUE TITLE
[Plugin Request] Option to auto generate all queries/mutations/fragments from a schema

### ISSUE THREAD

**Issue by user471** [dotansimha/graphql-code-generator#2349]
For example I have a lot of mutations like this 
```
type Mutation {
  createFoo(bar: Float!, foo: String!): String!
}
```
And I don't what to white 
```
mutation createFoo($foo: String!, $bar: Float!) {
	createFoo(foo: $foo, bar: $bar)
}
```
for every mutation
So It would be helpful if code generator just generate ```useCreateFooMutation``` for every mutation from the schema

**Comment by n1ru4l** [comment]
How would you know the correct selection set for each mutation? What if there was any recursion?

**Comment by user471** [comment]
>How would you know the correct selection set for each mutation? What if there was any recursion?

By default it could select everything except nested fields, if you need a different result you need to write a custom mutation. Also there could be a config option to include nested fields. Mutation with recursion could be skipped.

**Comment by dotansimha** [comment]
PRs are welcome :) Very similar to what AWS Amplify does. 

@n1ru4l we can add `level: X` to the config of this plugin and then create queries/documents according to that.

**Comment by Konosh93** [comment]
I am trying to open a PR for this issue, but I am stuck at generating the `documents` and making them available for subsequent `plugins`. File generation, currently, seems to be done with `Promise.all` which does not guarantee any specific order for the generated files.

https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/generate-and-save.ts#L27
Is it possible to add an option to allow certain plugins to run synchronously?

**Comment by dotansimha** [comment]
@Konosh93 The piece of code you mentioned is only the writing process of the output files, and not the generation itself. 
You can't communicate between plugins at the moment - each one is running on it's own (in order, but on it's own). 
Why do you need to pass documents between plugins? you don't want to write the output to the fs?

**Comment by Konosh93** [comment]
@dotansimha 
> The piece of code you mentioned is only the writing process of the output files, and not the generation itself

I agree, and this is what I was trying to find a workaround for.

> You can't communicate between plugins at the moment - each one is running on it's own (in order, but on it's own).

As you mentioned, the `codegen` is run in order, for all plugins. At this point, `documents` are generated by the desired plugin but not yet written to the `fs`.

> Why do you need to pass documents between plugins? you don't want to write the output to the fs?

I don't. Sorry, my wording was confusing. I want to make the generated documents files available for subsequent plugins.

```
overwrite: true
schema: "graphql/schema.graphql"
generates:
  graphql/docs.graphql:
    documents: null
    plugins:
      - plugin-for-generating-docs
  output/types.ts:
    documents: "graphql/docs.graphql"
    plugins: 
      - plugin-that-uses-the-generated-docs
```

**Comment by dotansimha** [comment]
I see. It's not possible at the moment, because plugins are being executed after the point that all documents has been collected, parsed and validated against the schema.

**Comment by Konosh93** [comment]
Thanks. We figured that wouldn't be possible with the current interface. In our own use cases, we will be running the plugin before other plugins, using a separate config file. I will update this answer once the plugin is ready.

**Comment by Fazzacoot** [comment]
Hello everyone. 
Is there any update to this issue?

**Comment by dotansimha** [comment]
At the moment, no updates on this issue. 

If someone really needs it, you can use `buildOperationNodeForField` from `@graphql-toolkit/common` (https://github.com/ardatan/graphql-toolkit/blob/master/packages/common/src/build-operation-for-field.ts). You can find an example for using it here: https://github.com/Urigo/graphql-mesh/blob/77311327ee1ba246adafd71dcbd3f658f8750305/packages/runtime/src/utils.ts#L153

PRs are welcome ;)
