### ISSUE TITLE
[federation] __resolveReference resolver type is incorrect

### ISSUE THREAD

**Issue by hannesj** [dotansimha/graphql-code-generator#2373]
**Describe the bug**
The generated code uses regular resolver type for the `__resolvereference` field, when federation is enabled, while the actual type is missing the args argument, and only has `(parent, context, info)`. See [Documentation](https://www.apollographql.com/docs/apollo-server/api/apollo-federation/#__resolvereference) for confirmation.

**Comment by dotansimha** [comment]
@kamilkisiela you recent changes also solves this?

**Comment by kamilkisiela** [comment]
@dotansimha no
