### ISSUE TITLE
Generate document by raw string format

### ISSUE THREAD

**Issue by david0u0** [dotansimha/graphql-code-generator#2400]
**Is your feature request related to a problem? Please describe.**

According to the [document](https://graphql-code-generator.com/docs/plugins/typescript-stencil-apollo#gqlimport-string-default-value-gql-graphql-tag), there are three document modes in the config:

> documentMode ('graphQLTag' | 'documentNode' | 'external', default value: 'graphQLTag')

It would be nice to have another mode 'rawString', which prevent the `graphql-tag` before the document. This could be done by external mode, but I think it's natural to support raw string natively. After all, the syntax is guaranteed to be correct by the codegen process. There is no need to involve the `graphql-tag` library for error handling.

**Describe the solution you'd like**

With a simple mutation below:
```
mutation Login($id: String!, $password: String!) {
	login(id: $id, password: $password)
}
```
codegen will generate something like:

```typescript
// graphQLTag
export const LoginDocument = gql`
    mutation Login($id: String!, $password: String!) {
  login(id: $id, password: $password)
}
    `;

// documentNode
export const LoginDocument: DocumentNode = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"Login"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}},"directives":[]},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"password"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}},"directives":[]}],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"login"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}},{"kind":"Argument","name":{"kind":"Name","value":"password"},"value":{"kind":"Variable","name":{"kind":"Name","value":"password"}}}],"directives":[]}]}}]};
```

It will be nice to have the following:

```typescript
// rawString
export const LoginDocument = `
    mutation Login($id: String!, $password: String!) {
  login(id: $id, password: $password)
}
    `;
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ardatan** [comment]
I think it should be always `DocumentNode` for apollo-client. See the API reference, it only takes `DocumentNode` so we can't use `string` directly. It would only break `Fragment` definitions.
https://www.apollographql.com/docs/react/api/apollo-client/

**Comment by dotansimha** [comment]
@ardatan is right, `apollo-client` and `react-apollo` requires `DocumentNode` (static, or created by `graphql-tag` on runtime). 

@david0u0 can you explain the use case? maybe we're missing something.

**Comment by david0u0** [comment]
Thanks for the fast reply!

@ardatan I apologize for referring to a wrong document. This document is what I actually meant: https://graphql-code-generator.com/docs/generated-config/client-side-base-visitor#documentmode-graphqltag-documentnode-external-default-value-graphqltag

@dotansimha  I'm not using Apollo, but a light-weight gql library `graphql-request` https://github.com/prisma/graphql-request.

It doesn't rely on `graphql-tag` or other gql library. Of course, you can still have graphql-tag as a syntax guarantee. E.g.:
```typescript
import { gql } from 'graphql-tag';
import { print } from 'graphql';
import { GraphQLClient } from 'graphql-request';

let client = GraphQLClient('localhost:8080');

const query = gql`
	mutation Login($id: String!, $password: String!) {
		login(id: $id, password: $password)
	}
`;
client.request(print(query), {
	id, password
});
```

With `graphql-codegen`, I can write something like:

```typescript
//api.ts, generated by codegen process
export const LoginDocument = gql`
	mutation Login($id: String!, $password: String!) {
		login(id: $id, password: $password)
	}
`;

// index.ts
import { gql } from 'graphql-tag';
import { print } from 'graphql';
import { GraphQLClient } from 'graphql-request';
import { LoginDocument } from './api';

let client = GraphQLClient('localhost:8080');

client.request(print(query), {
    id, password
});
```

And with raw string supported, I could eliminate the dependency of graphql and graphql-tag during run time.

**Comment by dotansimha** [comment]
Hmm I see, thanks @david0u0 ! 
Keeping this open, we maybe implement it in the future. If you want, you can create a PR for this :)

**Comment by dotansimha** [comment]
`DocumentMode` has `string` now. we can close this one :)

**Comment by YutaUra** [comment]
I now know that setting DocumentMode to string works, but that is not documented.
How can I open a PR for that?

https://www.graphql-code-generator.com/docs/plugins/typescript-document-nodes

**Comment by YutaUra** [comment]
That is, there is no mention of `string` in the current documentation (the description of `DocumentMode` in the URL above).
So, I think we need to update about it, don't you?
