### ISSUE TITLE
Installation instructions are wrong?

### ISSUE THREAD

**Issue by marcosfede** [dotansimha/graphql-code-generator#2401]
running  `npm install --save-dev graphql @graphql-codegen/cli` does not place any `graphql-codegen` comand in $PATH, Are the instructions correct?

**Comment by dotansimha** [comment]
@marcosfede Like any other Node library, you have to either run it with NPM scripts (create a script under `scripts` section of `package.json`, then run the script with `npm run myscript`), or, use `npx`, or use Yarn (`yarn graphql-codegen`)

**Comment by marcosfede** [comment]
@dotansimha I forgot to mention that I've tried that already. neither writing a script in `package.json` nor  running with `npx` is working. I've just tried using yarn and it works with no problems, so I think its not working correctly with npm

**Comment by dotansimha** [comment]
@marcosfede can you please share a reproduction of the issue in a repo? Which OS, Node and NPM do you use?
