### ISSUE TITLE
Obtaining query result after running the generated lazy query

### ISSUE THREAD

**Issue by killjoy2013** [dotansimha/graphql-code-generator#2423]
Hi,
I'm using graphql code generator 1.6.0.  I'd like to run one of my generated queries as follows;

`const [executeQuery, {data, loading, error}] = useNodesLazyQuery()`

However, couldn't obtain query result after `executeQuery` called, `data `is always undefined. Would be great if we could obtain the query result after user interaction, like button click.

Thanks

**Comment by dotansimha** [comment]
@killjoy2013 The generated lazy hook is just a wrapper around Apollo Hooks, so if `.data` is empty, it's not related to the codegen. We might be able to help any way and point you to the issue, but we'll need a reproduction in repo or codesandbox.

**Comment by dotansimha** [comment]
Closing. @killjoy2013 feel free to share more info if it's still relevant.
