### ISSUE TITLE
Async resolvers do not make Typescript suggestions

### ISSUE THREAD

**Issue by cypcz** [dotansimha/graphql-code-generator#2438]
**Describe the bug**
When making a resolver async (as most of them need to be), the Typescript suggestions do not show.

![Screenshot from 2019-08-24 21-32-15](https://user-images.githubusercontent.com/29678037/63641938-1c711a80-c6b7-11e9-8748-6e6c3c92c792.png)

![Screenshot from 2019-08-24 21-34-03](https://user-images.githubusercontent.com/29678037/63641940-28f57300-c6b7-11e9-95d2-93f28bbe129c.png)

**Expected behavior**
Typescript suggestions in async resolvers.

**Comment by kamilkisiela** [comment]
I think it happens because we use a lot of `OR` in types logic and vscode won't give any hints since there are no properties in common. I guess if you turn off [the support of Schema Stitching](https://graphql-code-generator.com/docs/plugins/typescript-resolvers#noschemastitching-boolean-default-value-false) it may help.

**Comment by dotansimha** [comment]
@cypcz can you please try Kamil's solution?

**Comment by cypcz** [comment]
I have tried it but it didn't help.

**Comment by dotansimha** [comment]
@cypcz what if you return `Promise.resolve({})`? does it auto completes?

**Comment by dotansimha** [comment]
@cypcz can you please try what I mentioned above? If it's still not working, can you please create a reproduction repo/sandbox?

**Comment by cypcz** [comment]
@dotansimha it is not working. Sandbox [here](https://codesandbox.io/s/focused-colden-fn3zc)

**Comment by dotansimha** [comment]
@cypcz It should work because the resolver method is declared to return `Promise` so it knows that it could be `async`.

Btw, which IDE do you use? VSCode?

**Comment by dotansimha** [comment]
@cypcz It's because you are forcing the type over the object, and not declaring it as the type correctly.

Using the following form of declarations should work:

```ts
import { Resolvers } from "../../../types";

const resolvers: Resolvers = {
  Query: {
    me: async (parent, args, context) => {
      return {};
    }
  }
};

export default resolvers;
```

![image](https://user-images.githubusercontent.com/3680083/66903091-797bb380-f00a-11e9-9d1a-084f33d8f715.png)
