### ISSUE TITLE
Generate types for Query fields

### ISSUE THREAD

**Issue by simPod** [dotansimha/graphql-code-generator#2447]
v0.19 used to generate exclusive types for fields

```tsx
export type XxxQuery = {
  __typename?: "Query";

  field: Maybe<XxxField>;
};

export type XxxField = {
  ...
};
```

Equivalent in current stable 

```ts
export type XxxQuery = (
  { __typename?: 'Query' }
  & { field: Maybe<(
...
```

Is there a way to use original behaviour so I can use type `XxxField`? Or do I have to use `XxxQuery['field']`?

Thanks!

**Comment by simPod** [comment]
I think compatibility plugin is the key but why is the new format preferred? Typing `XxxQuery['field']` feels softer than `XxxField`.

**Comment by dotansimha** [comment]
It's been a long time since 0.x versions, and a lot has changed. 
As @simPod said, you can use `typescript-compatibility` in order to generated those and migrate easily to 1.6.
