### ISSUE TITLE
codegen stops working when using a different gql library

### ISSUE THREAD

**Issue by mrtnbroder** [dotansimha/graphql-code-generator#2467]
When configuring the`gqlImport` and setting it to e.g. `graphql.macro#gql`, graphql-code-generator doesn't pickup the usage of `gql` it seems, thus it does not detect the usage of it to generate functions.

**To Reproduce**

I created a sandbox to reproduce the issue.
https://codesandbox.io/embed/graphql-codegen-issue-template-k43f6

In codegen.yml, comment out `gqlImport` and use `graphql-tag` and run `yarn generate` to get typings + functions

but use `gqlImport: graphql.macro#gql` and use `graphql.macro` inside `component.tsx` and run `yarn generate` and it only generates types, not functions.

Please make sure to remove the contents of `types.tsx` before running each `yarn generate`! looks like there is a bug where it doesn't overwrite the file in codesandbox.

**Comment by dotansimha** [comment]
@mrtnbroder using `pluckConfig` doesn't work? You tried it? see: https://github.com/dotansimha/graphql-code-generator/issues/1555#issuecomment-476212983

**Comment by mrtnbroder** [comment]
That seems to do the trick. Thanks.

Documentation should link to `pluckConfig` from `gqlImport` !

**Comment by dotansimha** [comment]
@mrtnbroder Those are different features. 
`pluckConfig` is a core feature, that tell the codegen how to scan and find your documents. 
`gqlImport` is a plugin-specific config that let you choose how to generate GraphQL operations inside the generated files.
