### ISSUE TITLE
default variable is non-optional

### ISSUE THREAD

**Issue by WillSquire** [dotansimha/graphql-code-generator#2496]
The `isOptional` argument below is created as an optional typing, however the `isNotOptional` argument is not (even though it has a default value). 

```
query example(
  $isOptional: String
  $isNotOptional: Boolean = false
) {
  example(
    isOptional: $isOptional
  ) {
    edges {
      node {
        id
        isNotOptional @include(if: $isNotOptional) {
          id
          name
        }
      }
    }
  }
}
```

@graphql-codegen/typescript == 1.2.0

**Comment by ardatan** [comment]
@WillSquire Could you create a reproduction using this sandbox and use latest version?
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template

**Comment by dotansimha** [comment]
I'm closing this one, let's track issues with `@include` / `@skip` directives here: https://github.com/dotansimha/graphql-code-generator/issues/2506
