### ISSUE TITLE
Edit and improve Migration to 1.0.0 page

### ISSUE THREAD

**Issue by rccoe** [dotansimha/graphql-code-generator#2500]
**Is your feature request related to a problem? Please describe.**

[This Page](https://graphql-code-generator.com/docs/migration/from-0-18) has no date on it. When was this posted? When did the change happen? Does it affect me?

It also has a lot of typos which makes it difficult to read.

- Stablize
- depreacted
- Introcude 

**Describe the solution you'd like**
Add a date and fix the typos.

**Describe alternatives you've considered**

**Additional context**

**Comment by dotansimha** [comment]
Done, thanks @rccoe . I will be available in the next deployment.

**Comment by dotansimha** [comment]
Done  🚀
