### ISSUE TITLE
Unable to read type defs from simple apollo-server sample

### ISSUE THREAD

**Issue by glennreyes** [dotansimha/graphql-code-generator#2510]
**Describe the bug**
Hey folks, I'm trying to get the TS types generated based on the sample apollo server type defs but I'm getting following error:

```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate .generated/graphql.ts
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unable to find any GraphQL type definitions for the following pointers: ./src/server.js
        Generate
```

**To Reproduce**

```sh
git clone https://github.com/glennreyes/codegen-apollo-sample
cd codegen-apollo-sample
yarn
yarn start
yarn generate # different tab
```

Minimal example: https://github.com/glennreyes/codegen-apollo-sample

1. My GraphQL schema:

```graphql
# Comments in GraphQL are defined with the hash (#) symbol.

# This "Book" type can be used in other type declarations.
type Book {
  title: String
  author: String
}

# The "Query" type is the root of all GraphQL queries.
# (A "Mutation" type will be covered later on.)
type Query {
  books: [Book]
}
```

2. My GraphQL operations:

none

3. My `codegen.yml` config file:

```yml
generates:
  .generated/graphql.ts:
    documents:
      - ./src/server.js
    schema: http://localhost:4000
    plugins:
      - typescript
```

**Expected behavior**

Should just work?

**Environment:**

- OS: latest MacOS
- `@graphql-codegen/...`: latest
- NodeJS: latest

**Additional context**

I don't have any queries or mutations created yet but I would have expected to have the schema generated TS types?

**Comment by ardatan** [comment]
`documents` field is for operations not type definitions. Please remove that field and try again. You would have those definitions.

**Comment by glennreyes** [comment]
@ardatan Thanks for pointing to it. Maybe it'd make sense to put this information into the docs.

**Comment by ardatan** [comment]
@glennreyes I think it is clear enough on docs;
https://graphql-code-generator.com/docs/getting-started/schema-field
https://graphql-code-generator.com/docs/getting-started/documents-field
If you have any suggestions, you can submit a PR :)
