### ISSUE TITLE
Support for hooks with Apollo client and typescript

### ISSUE THREAD

**Issue by mchong-teal** [dotansimha/graphql-code-generator#2520]
**Is your feature request related to a problem? Please describe.**

Apollo Client now supports hooks, which feel way easier to use and with less boilerplate than HOCs (https://www.apollographql.com/docs/react/recipes/static-typing/#typing-hooks).

I guess it be cool to have some autogenerated hooks to save me from having to specify the type parameters and query document when I use the hooks, just like we do for the HOCs

**Describe the solution you'd like**

auto-generated typed hooks for queries like we do for HOCs.

**Describe alternatives you've considered**

Um I guess I could just write the types out myself with my fingers..

**Additional context**

Seems like a simple enough feature to implement.  I guess if I have the time (seems unlikely, but maybe in the next week or so), I'll try to make a PR..

**Comment by adrianschneider94** [comment]
I use this already 🤔

config: 
  withHooks: true

**Comment by mchong-teal** [comment]
lol cool whoops.  Googling fail I guess.

https://graphql-code-generator.com/docs/plugins/typescript-react-apollo#withhooks-boolean-default-value-false
