### ISSUE TITLE
Enum string not found

### ISSUE THREAD

**Issue by adostal** [dotansimha/graphql-code-generator#253]
Hi all,
I have problem with declaration TS file with string enumns.

I generate schema with:
`gql-gen --file graphql.schema.json --template typescript --out ./types/graphql-model.d.ts`

In graphql-model.d.ts:
`
export enum EnumA {
    FIRST = 'FIRST',
    SECOND = 'SECOND',
}
`

Compile with tsc is allright, but error is when I start node.js:
`Error: Cannot find module '@graphql-model'`

Errors are in *.js files, which import EnumA.

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "outDir": "dist",
    "rootDir": "src",
    "baseUrl": ".",
    "strict": true,
    "moduleResolution": "node",
    "lib": [
      "es2015",
      "esnext.asynciterable"
    ],
    "inlineSourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "paths": {
      "@graphql-model": [
        "types/graphql-model.d.ts"
      ]
    }
  }
}
```

I use Typescript 2.8.1

**Comment by dotansimha** [comment]
@adostal can you please try to change the file extension to ‘.ts’ instead of ‘.d.ts’?

**Comment by dotansimha** [comment]
I can use the generator-specific config feature to add this, but I'm not sure it's the best solution. 

@adostal can you please elaborate on the reason for not changing it to `.ts`? it should work the same as `.d.ts`

**Comment by dotansimha** [comment]
@adostal 
I implemented it in: https://github.com/dotansimha/graphql-code-generator/pull/293

**Comment by dotansimha** [comment]
Done in 0.9.0 :)
