### ISSUE TITLE
script process does not end with non-zero exit code when it fails

### ISSUE THREAD

**Issue by pedrotainha** [dotansimha/graphql-code-generator#2536]
If the script fails, it does not terminate with a failure:

![image](https://user-images.githubusercontent.com/4137458/64726145-eb258680-d4cd-11e9-8a63-a02d204990ac.png)

I'm using v1.0.0

**Expected behavior**

Should terminate the Node.js process with a non-zero exit code

**Comment by dotansimha** [comment]
Hi @pedrotainha 
Can you please try the latest version? 1.7.0

Also, it seems like the error is an invalid yml file, I guess you miss `"`

**Comment by dotansimha** [comment]
Closing. @pedrotainha feel free to contact if you are still having an issues with the latest version.
