### ISSUE TITLE
Generate query return type

### ISSUE THREAD

**Issue by sroettering** [dotansimha/graphql-code-generator#2542]
I'm using the `typescript-apollo-angular` plugin to generate types and services for my queries.

When generating services a type for the query is generated as well. However, there is no simple type definition generated for the actual data that is returned. This would make typing easier when using the queries.

**Comment by n1ru4l** [comment]
You can do `type GetPersonsQueryData = GetPersonsQuery["getPersons"]`

Or use fragments which will also generate the desired type

**Comment by sroettering** [comment]
Of course I can define the type myself but why should I when already using a generator?
I didn't try using fragments, could you maybe elaborate with a simple example?

**Comment by n1ru4l** [comment]
@sroettering

```graphql
fragment PersonFragment on Person {
  id
  fullName
}
query GetPersons {
  getPersons {
    ...PersonFragment
  }
}
```

```tsx
import * as React from "react";
import { PersonFragment } from "./generated-types";

const MyComponent: React.FC<{ persons: PersonFragment[] }> = ({ persons }) => {
  return null;
};
```

I do not understand why this library should generate an additional type for this.

You can still do something like this:

```tsx
import * as React from "react";
import { GetPersonsQuery } from "./generated-types";

const MyComponent: React.FC<{ persons: GetPersonsQuery["getPersons"] }> = ({ persons }) => {
  return null;
};
```

**Comment by sroettering** [comment]
Using fragments works for me. So I will close this issue.
The other solution `GetPersonsQuery["getPersons"]` is too verbose IMHO.

**Comment by n1ru4l** [comment]
You could also write your own plugin to achieve this without fragments. From my perspective, I do not think that `GetPersonsQuery["getPersons"]` is verbose. You are just using a typescript language feature.

**Comment by dotansimha** [comment]
@sroettering you can also add the `typescript-compatibility` plugin, it will generate bridge types (because in the past we had those)

**Comment by antonvialibri1** [comment]
What about array query return types? How can you easily refer to the type of the array if GraphQL Codegen generates them inline using the `Array<{...}>` inline object type syntax?

E.g. if you have:

```graphql
extend type Query {
  parent: Parent
}

type Parent {
  id: ID!
  children: [Child!]!
}

type Child {
  id: ID!
  title: String
  description: String
}

query GetParent {
  parent {
   children {
      id
      title
      description
    }
  }
}
```

Then GraphQL Codegen generates something like:

```ts
export type GetParentQuery = {
  parent: {
     __typename: 'Parent';
     id: string;
     children: Array<{
        __typename: 'Child';
        id: string;
        title: string | null;
        description: string | null;
     }>;
  }
};
```

If I have function which refers to the element type of `children` (`{
        __typename: 'Child';
        id: string;
        title: string | null;
        description: string | null;
     }`), how can I refer to it e.g. in JSDoc comments?
     
```js
/**
 * @param {???} child - What should I put here? `child` is the object of the `children` array returned by the GetParentQuery...
 */
function doSomethingWithChildOfParent(child) {
  // Do something with `child`...
}
     
```
     
In this case something like `@param {GetParentQuery.parent.children} child` won't work, because `GetParentQuery.parent.children` is the array of children, but I need to target the child/element type of the `children` array. 
How can I target it? Is the only solution using a fragment on `Child`?

Thanks!

**Comment by seemX17** [comment]
@antonvialibri1 I agree! We need a better solution to generate types only for data that has been asked. The current solution creates more bugs if certain data is not being fetched but exists in the type. 
It is simple to get the type for a result but what about the child?

**Comment by qingemeng** [comment]
Is there any update to this?
