### ISSUE TITLE
JSDoc

### ISSUE THREAD

**Issue by rlindskog** [dotansimha/graphql-code-generator#2558]
It would be cool to generate [JSDoc](https://devdocs.io/jsdoc/) annotations from graphql descriptions. A lot of modern code editors get inline documentation when writing a function. (ex. [VSCode](https://code.visualstudio.com/docs/languages/javascript#_jsdoc-support))

**Comment by CarloPalinckx** [comment]
I wouldn't mind having a look at this, I'll tag you in a PR ;)

**Comment by CarloPalinckx** [comment]
@rlindskog have a look at: https://github.com/dotansimha/graphql-code-generator/pull/2572 :)

**Comment by rlindskog** [comment]
@CarloPalinckx Does this create the doc from the graphql description? https://www.apollographql.com/docs/apollo-server/schema/schema/#describing-types

Example:
```graphql
"Description for the type"
type MyObjectType {
  """
  Description for field
  Supports **multi-line** description for your [API](http://example.com)!
  """
  myField: String!

  otherField(
    "Description for argument"
    arg: Int
  )
}
```

**Comment by n1ru4l** [comment]
@rlindskog Nope, only hook docs.

**Comment by dotansimha** [comment]
Fixed in 1.8.0 🚀

**Comment by smolster** [comment]
@dotansimha it doesn't seem like the added functionality actually implements what the original poster asked about.

Is there a plan to generate JSDoc comment bodies from GraphQL schema descriptions?

**Comment by dotansimha** [comment]
@smolster please report a new issue if you think it's missing, and please make sure to reference the relevant plugins :)
