### ISSUE TITLE
Use exported original queries/mutations 

### ISSUE THREAD

**Issue by tafelito** [dotansimha/graphql-code-generator#2573]
I have a file quereis.ts where I define all my queries. When the generated types are generated, it will copy and rename each query mutation to use it, for example, in a hooks

so If I have in queries.ts

```js
export const ME_QUERY = gql`
  query me {
    me {
      id
      email
    }
  }
`;
```

Then the generated.ts will have

```js
export const MeDocument = gql`
  query me {
    me {
      id
      email
    }
  }
`;

export function useMeQuery(
  baseOptions?: ApolloReactHooks.QueryHookOptions<MeQuery, MeQueryVariables>,
) {
  return ApolloReactHooks.useQuery<MeQuery, MeQueryVariables>(
    MeDocument,
    baseOptions,
  );
}
export type MeQueryHookResult = ReturnType<typeof useMeQuery>;
export type MeQueryResult = ApolloReactCommon.QueryResult<
  MeQuery,
  MeQueryVariables
>;
```
What I'd like, if it's possible to do,  instead of having the MeDocument being generated, I want my ME_QUERY constant to be imported, that way when I see the definition of the query hook and I need to jump to the query definition, I can go right away, instead of trying to find the original query. 
 
I tried different configs but I couldn't make it work, I'm not sure if this is supported or not

Thanks

**Comment by lukasluecke** [comment]
@tafelito I think this should be possible using the `documentMode` and `importDocumentNodeExternallyFrom` config options for the "typescript-react-apollo" plugin.
Could you try them, and post your config with these values, if it doesn't work for you?

**Comment by tafelito** [comment]
I did try that, but it doesn't work like I'd like. That only changes where to import the queries but it doesn't use the original ones I create

this is my config

```js
overwrite: true
schema:
  - http://localhost:4000/graphql
  - graphql/client-schema.ts
documents: 'graphql/**/*.ts'
generates:
  generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-resolvers'
      - 'typescript-react-apollo'
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: './graphql'
      reactApolloVersion: 3
      gqlImport: apollo-boost#gql
      hooksImportFrom: '@apollo/react-hooks'
      withHooks: true
      withHOC: false
      withComponent: false
      withMutationFn: false
``` 

I also tries using `'near-operation-file'` but different results, same issue

**Comment by lukasluecke** [comment]
Based on the documentation and the tests it should work like this:
https://github.com/dotansimha/graphql-code-generator/blob/16974558a6ce43bedde8ca9431ceae9f0e3fd5e4/packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts#L1436-L1457

Is that different from what you're trying to do? Could you share the file where you export your document nodes?

**Comment by tafelito** [comment]
That's what I tried as you can see from the config I put above. It does change the import from what I put in `importDocumentNodeExternallyFrom ` but it doesn't change the name od the document queries. 
The other issues is that I don't have all my queries/mutations in one place. I could create an index file to get around that but that's not ideal

Here' s a short example of what I have

src/graphql/queries.ts

```js
import { gql } from 'apollo-boost';

export const ME_QUERY = gql`
  query me {
    me {
      id
      email
    }
  }
`;
```

and this is what it generates after using that config

src/generated/graphql.ts

```js
import {
  GraphQLResolveInfo,
  GraphQLScalarType,
  GraphQLScalarTypeConfig,
} from 'graphql';
import * as Operations from '../graphql/queries';
import * as ApolloReactCommon from '@apollo/react-common';
import * as ApolloReactHooks from '@apollo/react-hooks';
export type Maybe<T> = T | null;
...
```

![image](https://user-images.githubusercontent.com/5973652/65049452-bed99200-d933-11e9-97b4-637cc9b67d26.png)

As you can see, the MeDocument does not exist, and that's not the name of my exported query 

I also have a bunch of Fragments with errors because the gql import is not being imported but the fragments are and they are using it as you can see here

![image](https://user-images.githubusercontent.com/5973652/65049613-052ef100-d934-11e9-84af-9d3bf01a4243.png)

**Comment by ardatan** [comment]
I tried to reproduce your issue but it works as expected in mine.
In this branch I added a config similar to yours together with similar structure of yours;
https://github.com/dotansimha/graphql-code-generator/tree/reproduction-2573/dev-test/test-message
You can see the `codegen.yml`;
https://github.com/dotansimha/graphql-code-generator/blob/0cd045e3714b9685aba42ee705d354e2a5e3a306/dev-test/codegen.yml#L281
And this is the output;
https://github.com/dotansimha/graphql-code-generator/blob/0cd045e3714b9685aba42ee705d354e2a5e3a306/dev-test/test-message/types.tsx#L132

Is there any difference between yours and mine?

**Comment by ardatan** [comment]
I'm closing this issue for now. So feel free to open again if your issue still persists.

**Comment by tafelito** [comment]
@ardatan I set the exact same config as you and still not working.

Having this query
```js
export const ME_QUERY = gql`
  query me {
    me {
      id
      email
    }
  }
`;
```

this is how the generated code looks like

As you see, it does not use the ME_QUERY property, it uses the name of the query. In your case works because the name of the query and the variable are the same. 

Also I do have more than just 1 file where I put all my operations and `importDocumentNodeExternallyFrom` does not accept an array of files so I will have to create an index an re export all operations from there

**Comment by Urigo** [comment]
@tafelito does that issue still happens on latest?

If so, could you open a new issue please?
