### ISSUE TITLE
Struggling to understand the distinction between "Load GraphQL Schemas" and "Load GraphQL Documents"

### ISSUE THREAD

**Issue by ajhool** [dotansimha/graphql-code-generator#2581]
**Is your feature request related to a problem? Please describe.**
I'm using hasura as my graphql engine and have used `graphql-codegen init` to set the project up. I was not sure about how to answer "Where are your operations and fragments?:" and accepted the default " src/**/*.graphql". My graphql understanding was that everything would be contained in the schema

**Describe the solution you'd like**

An explanation or example of what these `src/**/*.graphql` files ought to look like would be immensely helpful. I am relatively new to the graphql ecosystem so perhaps this is trivial for other users, I'm not sure.

**Describe alternatives you've considered**

**Additional context**
The error is:

```
$ graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.ts
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unable to find any GraphQL type definitions for the fo
…
        Generate
    ❯ Generate ./graphql.schema.json
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unable to find any GraphQL type definitions for the fo
…
        Generate


 Found 2 errors

  ✖ src/generated/graphql.ts
    Error: Unable to find any GraphQL type definitions for the f
ollowing pointers: src/**/*.graphql

  ✖ ./graphql.schema.json
    Error: Unable to find any GraphQL type definitions for the f
ollowing pointers: src/**/*.graphql
```

**Comment by ardatan** [comment]
Document is the file that contains your operations inside your client;
```gql
query fooQuery {
   foo
}
```
Schema is the file that contains your type definitions including your queries, mutations and subscriptions;
```gql
type Query {
  foo: String
}
```

**Comment by aldegoeij** [comment]
Hi! I have a similar issue, my use-case:

`schema.graphql`:

```graphql
schema {
  query: Query
}

type Greeting {
  name: String!

type Query {
  sayHello(name: String): Greeting
}
```

Now I would like to generate the 'document that holds your operations', something looking like:

```javascript
export const sayHello = `query sayHello($name: ID!) {
  sayHello(name: $name) {
    name
  }
}
`;
```

However, `codegen.yml`:

```yaml
overwrite: true
schema: "./schema.graphql"
generates:
  ./generated/graphql.d.ts:
    plugins:
      - typescript-document-nodes
```

yields:

```
./src/generated/graphql.d.ts
    Error: Unable to find any GraphQL type definitions for the following pointers: ./generated/graphql.d.ts
```

How can I get to that file of GQL strings (or DocumentNodes) using `graphql-codegen`?

**Comment by dotansimha** [comment]
@aldegoeij We can't really tell that this specific string is a GraphQL operation, without your marking it (by using `gql` tag or using `/* GraphQL */` comment before the string value.
