### ISSUE TITLE
Feature Request: Multiple output files

### ISSUE THREAD

**Issue by aeb-sia** [dotansimha/graphql-code-generator#2607]
I want to be able to generate multiple files from one plugin.

I know this was possible in the past and is planned to be reintroduced in the future. I'm aware of issues like #1292. I think it's a good idea to have a feature request open, so people can vote on it, and subscribe to it, so they are notified once this is actually implemented.

**Comment by dotansimha** [comment]
@aeb-sia The codegen now supports generating multiple files. 

See: https://graphql-code-generator.com/docs/presets/near-operation-file (there are a lot of usage examples in issues in this repo).
