### ISSUE TITLE
`near-operation-file` with latest selection set changes breaks fragments imports

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#2608]
Related: https://github.com/dotansimha/graphql-code-generator/issues/2548#issuecomment-534067192

**Comment by dotansimha** [comment]
@Swatinem  I think I managed to fix the fragments issues in: https://github.com/dotansimha/graphql-code-generator/pull/2620
Can you please try the latest alpha version? `1.7.1-alpha-59af2256.91`

**Comment by Swatinem** [comment]
@dotansimha thanks for notifying me.
So the fragment imports are correct now, but there is yet another regression:
It now tries to use the `XXXMutation` and `XXXMutationVariables` from the `Types` (`baseTypesPath`) namespace, which is wrong.
The declarations are local to each operation file, so no need to use the base types namespace.

**Comment by dotansimha** [comment]
It's related to changes by @veeramarni in order to support `import-types` preset. 
I think I'll separate the configuration names in order to fix that.

**Comment by dotansimha** [comment]
@Swatinem I managed to fix that in this PR: https://github.com/dotansimha/graphql-code-generator/pull/2667 

Can you please try the latest alpha? `1.7.1-alpha-23589acb.118`

**Comment by dotansimha** [comment]
Fixed in 1.8.0 🚀
