### ISSUE TITLE
enumPrefix not being respected for mutation variables

### ISSUE THREAD

**Issue by P4sca1** [dotansimha/graphql-code-generator#2621]
**Describe the bug**
The generation of mutation variables does not respect `enumPrefix: false`.

**To Reproduce**
https://codesandbox.io/embed/graphql-codegen-issue-template-iyx2e

Use `yarn generate`.
Have a look at `types.ts`. You'll notice that `IGender` is used in `IUpdateUserProfileMutationVariables` instead of `Gender`.

**Expected behavior**
Mutation variable generation should respect `enumPrefix`.

**Environment:**

- Windows 10 / macOS Catalina Beta
- `@graphql-codegen/1.7.0`
- `Node.js v10.16.3`

**Comment by dotansimha** [comment]
@P4sca1 I think I managed to fix that in: https://github.com/dotansimha/graphql-code-generator/pull/2622
Can you please give it a try? the latest alpha is `1.7.1-alpha-1e9152fb.90`.

**Comment by P4sca1** [comment]
Using `1.7.1-alpha-1e9152fb.90` solves the issue!

**Comment by dotansimha** [comment]
Fixed in 1.8.0 🚀
