### ISSUE TITLE
Way to add external template instead of modifying `graphql-codegen-generators` itself

### ISSUE THREAD

**Issue by frantic1048** [dotansimha/graphql-code-generator#263]
The generator performs well, but sometimes I need to do some subtle modification on the built-in template. e.g. I want to expose enum values' descriptions to the client.

I achieved it via adding a new template to `graphql-codegen-generators`. It works, but I had to maintain a fork of `graphql-codegen-generators`, just for a subtle template change. That sounds not so reasonable.

So I'm questioning if there is/will be a way to specify an external template to use with `graphql-codegen-generators`?

**Comment by dotansimha** [comment]
Hi @frantic1048 ! 
At the moment, you can either edit the code inside this package, or create your own template using a NPM package. 
For example, call your npm package `frantic1048-template` and then you can use it it's name in `--template` flag. 
The goal is to migrate all built-in templates to be an independent packages.

Your NPM package should export a `main` javascript file, that export a `GeneratorConfig` as default export.

**Comment by dotansimha** [comment]
And also, i'm working on moving all the existing template to use this: https://github.com/dotansimha/graphql-code-generator/issues/266

**Comment by dotansimha** [comment]
@frantic1048 please see this: https://github.com/dotansimha/graphql-code-generator/blob/feature/packages/packages/templates/README.md
