### ISSUE TITLE
Inclusion of __typename is not enforced on the optimisticResponse for a mutation

### ISSUE THREAD

**Issue by camfletch** [dotansimha/graphql-code-generator#2635]
**Describe the bug**
 
For `optimisticResponse` to work correctly: https://www.apollographql.com/docs/react/performance/optimistic-ui/#basic-optimistic-ui
You _must_ provide the `__typename` of each object in your `optimisticResponse`. For example:

```
   updateUserColorBlind({
      variables: {
        memberId,
        colorBlind,
      },
      optimisticResponse: {
        updateUserColorBlind: {
          __typename: 'Member',
          id: memberId,
          prefs: {
            __typename: 'Member_Prefs',
            colorBlind,
          },
        },
      },
```

Now the generated types correctly detect if there is a typo in the `__typename` (which is great!), but the `__typename` field itself is optional, i.e `__typename?: "Member" | undefined'`.

**To Reproduce**
1. Generate types for a mutation
2. Consume the generated mutation hook, and provide an `optimisticResponse` that does not include `__typename` properties
3. No typescript errors, but the optimistic update will not apply correctly

**Comment by n1ru4l** [comment]
I can confirm this issue.

**Comment by dotansimha** [comment]
@camfletch You can either specify `__typename` explicitly in your schema, or set `nonOptionalTypename: true` and it will force `__typename` as non-optional.

**Comment by LydiaF** [comment]
Hey, sorry for tagging on to this issue, I found this issue while wondering why typescript was underlining __typename: 'Mutation' in my optimisticResponse from the autogenerated types. It seems you don't have to put this in, as my code is working without it.

I noticed that you haven't put in __typename: 'Mutation'. Do you know anything about this? In the example in the docs, it has it.

```
optimisticResponse: {
       __typename: 'Mutation' //You don't have this
        updateUserColorBlind: {
          __typename: 'Member',
          id: memberId,
          prefs: {
            __typename: 'Member_Prefs',
            colorBlind,
          },
        },
      },
```

Thanks for any thoughts and apologies if this is irrelevant to your issue.

**Comment by camfletch** [comment]
@LydiaF yep I also noticed that it wasn't necessary (after setting nonOptionalTypename to true) so removed it. I would guess the root Mutation and Query types are treated as special internally?

**Comment by dotansimha** [comment]
I see. The goal of those plugin is to generate the most broad and customizable code as possible. I don't think we should change it's behavior in order to support a specific feature in Apollo Client (we do allow customizations, so if someone wants to add `excludeTypenameFromRootTypes` or something similar, we welcome it!)
