### ISSUE TITLE
codegen init fails (but it is documented)

### ISSUE THREAD

**Issue by wtrocki** [dotansimha/graphql-code-generator#2642]
Happy to remove it from docs if agreed and not issue:

![Screenshot 2019-09-27 at 11 54 02](https://user-images.githubusercontent.com/981838/65764444-8dc04500-e11d-11e9-929d-612e5634c85f.png)

**Comment by dotansimha** [comment]
Just tested it and it seems to work. @wtrocki can you please share a small repo? 
Also, do you run it as global command? does your codegen installed globally?

**Comment by wtrocki** [comment]
I have removed it globally. Tried different cases. 
It was fixed but it seems that npx do not work as graphql is added as peer dependency.

```
[wtrocki@wtrockigraph investigations ]$ npx @graphql-codegen/cli init
npx: installed 285 in 18.735s
Cannot find module 'graphql'
```

Feel free to close this though.

**Comment by ardatan** [comment]
You need to try it on a project by installing like;
```
yarn add @graphql-codegen/cli graphql
```

**Comment by jorrit** [comment]
I got this same issue when I accidently installed `graphql-codegen` instead of `@graphql-codegen/cli`.
