### ISSUE TITLE
optional-js support for maybeValue

### ISSUE THREAD

**Issue by frankruegamer** [dotansimha/graphql-code-generator#2646]
**Is your feature request related to a problem? Please describe.**

There is [this](https://www.npmjs.com/package/optional-js) library for JavaScript which abstracts possible undefined values and was inspired by Java. I'm trying to wrap my head around how to use it directly for `maybeValue`.

**Describe the solution you'd like**
Ideally modify codegen.yml like so:
```
config:
  avoidOptionals: true
  maybeValue: Optional<T>
```
For this to work Optional's constructor would have to be called with the value.

**Describe alternatives you've considered**
The alternative is to use `undefined` and or `null` and wrap it later using `Optional.ofNullable(data.nullableField)` which is a bit cumbersome.

**Comment by dotansimha** [comment]
Closing. This can be done using configuration (`maybeValue`) and if you need to add imports, you can use `add` plugin.
