### ISSUE TITLE
 @graphql-codegen/typescript-react-apollo@1.7.0 requires a peer of @types/graphql@* but none is installed

### ISSUE THREAD

**Issue by jeffreyffs** [dotansimha/graphql-code-generator#2650]
**Describe the bug**
typescript-react-apollo requires @types/graphql, but the package has been deprecated since graphql added type definitions to their repo.

**To Reproduce**
Install typescript-react-apollo without @types/graphql

**Expected behavior**
No warning from `npm` or `yarn`

**Environment:**
- OS: macOS
- `@graphql-codegen/...`: 1.7.0
- NodeJS: 10.15.1

Edit: I've just noticed this was patched almost a month ago but hasn't been released yet (https://github.com/dotansimha/graphql-code-generator/commits/master/packages/plugins/typescript/react-apollo/package.json)

**Comment by dotansimha** [comment]
Thanks @jeffreyffs ! we'll fix that very soon :)

**Comment by dotansimha** [comment]
Pushed a fix to `master`.

**Comment by dotansimha** [comment]
Fixed in 1.8.0 🚀

**Comment by jeffreyffs** [comment]
Thanks! 🎉
