### ISSUE TITLE
Add ability to import schema from node_modules

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#2656]
https://graphql-code-generator.com/docs/getting-started/schema-field
I see all kinds of options to load schema, but one I think is still kinda missing :)
What do you think about to add schema resolution from regular JS modules?
Example:
```
schema:
  - '@revolut/our-awesome-schema/schema.graphql'
```
Where `@revolut/our-awesome-schema` is the name of the module.

I assume I can hack around it right now like that.
```
schema:
  - 'placeholder'
      loader: my-js-loader.js  
```
my-js-loader.js
```js
const { buildSchema } = require('graphql');
const { readFileSync } = require('fs');

module.exports = function() {
  return buildSchema(
    readFileSync(
      `${require.resolve("@revolut/our-awesome-schema")}/schema.graphql`, 
      { encoding: 'utf-8' }
      )
    );
};
```
But it still requires the creation of a file in the root of my module which is a bummer.

**Comment by dotansimha** [comment]
You can do it now, because codegen will use `require`. Just add `noPluck` and it will do `require` automatically and load the file from there.
