### ISSUE TITLE
Include directive is non-optional 

### ISSUE THREAD

**Issue by WillSquire** [dotansimha/graphql-code-generator#2657]
Noticed the typings for properties with include directives are non-optional, but the return values can be undefined. For example, in:
```
query ($withFoo: Boolean = false){
  foo @include(if: $withFoo) {
    bar
  }
}
```
`foo` can be optional.

**Comment by dotansimha** [comment]
Let's track in: https://github.com/dotansimha/graphql-code-generator/issues/3836
