### ISSUE TITLE
question: ordering

### ISSUE THREAD

**Issue by maapteh** [dotansimha/graphql-code-generator#2660]
Hi team :)

We checkin our generated types so we can also see the changes. I noticed it keeps on changing the ordering of keys when we extend a type in another module. Sometimes it gets on the top, sometimes on the bottom. Is it maybe better to have them as an option be sorted on alphabet? Is that possible? Don't tell me its already configurable :)

Maybe we will ditch the checkin as we have kamil's validator in place

```
type Product {
+ offer: Offer
  id: String!
  ean: String
  title: String!
@@ -37,6 +36,7 @@ type Product {
  """TODO: question does 'offerData' belong here?"""
  offerData: ProductOfferData
  parentCategoryPaths: ProductParentCategoryPaths
- offer: Offer
}

**Comment by dotansimha** [comment]
I caused by `graphql-toolkit` and the fact that we changed the `glob` library to `fast-glob` which doesn't promise consistency. 
@ardatan added some fixes related to sorting in the latest version of `graphql-toolkit` (it's also available in the latest alpha version of the codegen).
