### ISSUE TITLE
Resolver return type requires unnecessary properties

### ISSUE THREAD

**Issue by mastilver** [dotansimha/graphql-code-generator#2665]
**Describe the bug**

Hi

I'm not sure if it's even possible
A resolver type requires me to add property to an object when it's being handle by another resolver
For example I have
- a `user` resolver that only send `firstName` and `lastName` 
- a `fullName` resolver on the `User` object

the `user` resolver type still requires me to return `fullName`

**To Reproduce**

- clone: https://github.com/mastilver/graphql-code-generator-computed-field-issue
- `npm generate`
- `npm ts` <- this will fail

**Expected behavior**

The type for the `user` resolver not to include `fullName`  
The only way I can see this issue resolved is by looking at the resolvers object by I might be missing something and it's already possible?

Thank you

**Comment by ardatan** [comment]
So, your entity type has `firstName` and `lastName`. You should define a type like below,,
```ts
export interface UserEntity {
   firstName: string;
   lastName: string;
}
```
then use `mappers` field inside `codegen.yml`;
```yml
mappers:
    User: ./user-entity#UserEntity
```

**Comment by mastilver** [comment]
Thank you for the quick answer! :+1:
