### ISSUE TITLE
typescript-apollo-client

### ISSUE THREAD

**Issue by P4sca1** [dotansimha/graphql-code-generator#2690]
**Is your feature request related to a problem? Please describe.**
The new typescript-graphql-request plugin released today is very great. It solves many issues I had about huge boilerplate when calling graphql queries because you no longer have to specify query, query type and variable types.

For another frontend project I am using vue-apollo and apollo-client is not supported by the getSdk function.

**Describe the solution you'd like**
Would be great if there was a plug-in typescript-apollo-client which exposes the same getSdk function but for the Apollo client.

**Describe alternatives you've considered**
Maybe there could be a general typescript-graphql-sdk plugin which is tree-shakeable and exposes multiple getSdk implementations for various graphql clients. This would reduce the number of different plugins and it may be more comfortable to have those sdks all in a single code base.

**Comment by dotansimha** [comment]
Hi @P4sca1 
I think it should be very simple to implement, because the API is similar. 
I'll try to take a look this week.

**Comment by dotansimha** [comment]
Actually noticed that we have an issue for that already: https://github.com/dotansimha/graphql-code-generator/issues/2415 
Let's track it there :)
