### ISSUE TITLE
Question: Writing my own plugin like docs, vs like actual plugins are written.

### ISSUE THREAD

**Issue by petecarapetyan** [dotansimha/graphql-code-generator#2703]
My plugins that are written per the docs work fine, using this basic format

`module.exports = {
  plugin: (schema, documents, config) => {
...`

If I'd prefer to write in the post-common.js style - such as virtually everything in packages/graphql-codegen-cli/src/init/plugins.ts - but I don't know how to reference this style of code into my development workflow without inserting into the plugin.ts etc.

Is this possible? Documented? Or do I have to stick with the documented common.js style until I am ready to make it a part of the graphql-codegen-cli?,

**Comment by dotansimha** [comment]
Hi @petecarapetyan ! 
Can you please explain what do you mean by `post-common.js`? 
You wish to use ES6 or TypeScript for writing your plugins? You can easily do that with `tsc`, just make sure to compile it and point the correct files in your `package.json`'s `main` field.

**Comment by petecarapetyan** [comment]
Yes, by post-common-js I meant ES6 or ES2017 or any of the other later versions, none of which use common.js `requires` or `module.exports`

I would like to use the same kind of ES6 code that I see in the plugins written in `graphql-code-generator`

I am attempting to write a generator for web components and lit-apollo

**Comment by dotansimha** [comment]
@petecarapetyan We are using TypeScript, compiled with `tsc`. You can copy the following and it will work for you:
- https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/typescript/tsconfig.json
- https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/typescript/package.json#L27-L33
