### ISSUE TITLE
How to generate multiple files from a single plugin, as determined by the schema?

### ISSUE THREAD

**Issue by petecarapetyan** [dotansimha/graphql-code-generator#2715]
I would like my plugin to be able to write one or more files for each relevant object in the schema.

Is this documented anywhere? I can search in `graphql-code-generator` for `config.generates` and get some ideas on this, but I get lost before I find a working example.

**Comment by dotansimha** [comment]
@petecarapetyan Can you please add more context to what you are trying to achieve? 
Basically, each plugin returns a `string` and the combination of multiple plugins creates a output file, based on `config.generates` keys. 

The codegen core also supports `presets` which are a way to manipulate `generates` section before it's being executed.  For example, `near-operation-file` will create a `generates` keys for every operation file found. (you can find the source code under this repo, `packages/plugins/presets`)

You can easily create a preset that extends `generates` on runtime according to your schema.

**Comment by petecarapetyan** [comment]
For context: Here is what I have done in previous generators I have written:

Schema contains n tables (more like objects in graphql). For each - I provided a combination of controller and other artifact(s) for a CRUD user interface, usually in different files, for each table.

**Comment by petecarapetyan** [comment]
From doing a search on preset I can see how to do this:

Basically I create a function  called presets that returns an array of plugin configurations to iterate on. Each artifact required gets it's own `plugin` configuration.
