### ISSUE TITLE
Environment variables doesn't work since 1.8.1

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#2722]
Related: 
https://github.com/dotansimha/graphql-code-generator/issues/1757#issuecomment-540317073

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/2758 
Alpha available: `1.8.2-alpha-c7249947.43`

**Comment by JoelVenable** [comment]
Thanks for fixing this.  The alpha version seems to work well for us.

**Comment by dotansimha** [comment]
Fixed in 1.8.2.
