### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by CarloPalinckx** [dotansimha/graphql-code-generator#2724]
Found a small typo in the docs, on this [page](https://graphql-code-generator.com/docs/plugins/typescript-operations#requirements) `docuemnts` should be `documents`. I wouldn't mind fixing this but I couldn't find this typo in the codebase so I'm guessing it comes from a CMS?

**Comment by dotansimha** [comment]
@CarloPalinckx thanks! 
You couldn't find it because it was already fixed ;) 
https://github.com/dotansimha/graphql-code-generator/pull/2712 (Thanks @patrykkopycinski)

**Comment by CarloPalinckx** [comment]
Fixed bugs are my favorite kind of bugs 😉

**Comment by dotansimha** [comment]
Fixed in 1.8.2.
