### ISSUE TITLE
Error when using .gql extension for schema files

### ISSUE THREAD

**Issue by jsonmaur** [dotansimha/graphql-code-generator#2744]
When trying to use the `.gql` extension for my schema files, I get the error `Syntax Error: Cannot parse the unexpected character "/".` If I change my schema files to `.graphql`, everything works fine.

Did some digging, and seems to be coming from [this issue](https://github.com/Urigo/graphql-import/issues/244) in the `graphql-import` library. There is a PR currently open to fix it, but it has been dormant for about 2 1/2 months. There's a workaround described in the comments, maybe it might be worth it to implement here? Otherwise `.gql` files cannot be used.

Example: https://codesandbox.io/s/graphql-codegen-issue-2743-likc1

**Comment by dotansimha** [comment]
@jsonmaur Thank you for reporting this. 
`graphql-import` has been recently moved to our maintenance, so we can take a look. 

Closing this now for now, because it's not a direct issues of the codegen, but an issue with `graphql-import`.
