### ISSUE TITLE
Typescript-Resolver: custom `resolveInfo` type

### ISSUE THREAD

**Issue by ab-pm** [dotansimha/graphql-code-generator#2746]
Hi, we are using the Postgraphile library which not only uses a [custom context](https://graphql-code-generator.com/docs/plugins/typescript-resolvers#custom-context-type) but also [has an extended `resolveInfo` argument](https://www.graphile.org/postgraphile/make-extend-schema-plugin/#the-selectgraphqlresultfromtable-helper). They do [provide their own `AugmentedGraphQLFieldResolver` type](https://github.com/graphile/graphile-engine/blob/1d589633698b4bdfb2923226a330b6345505dd77/packages/graphile-utils/src/makeExtendSchemaPlugin.ts#L44-L56) but since it returns `any` it's not really compatible with the proper resolver types created by `graphl-codegen`.

Feature request: Could you please add another configuration option so that one could choose the type of the `ResolveFn`'s `info` argument?
```ts
export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
//      ^^^^^^^^^^^^^^^^^^ customise this
) => Promise<TResult> | TResult;
```

**Comment by dotansimha** [comment]
Implemented in 1.8.2.
