### ISSUE TITLE
Remove variables from types when they are exported by the @export directive

### ISSUE THREAD

**Issue by CarloPalinckx** [dotansimha/graphql-code-generator#2771]
**Is your feature request related to a problem? Please describe.**

Imagine you have a query:

```graphql
query getCurrentUserPosts($userId: ID!, $topic: String!) {
  currentUser @client {
    id @export(as: "userId")
  }
  getPostsByUser(id: $userId, topic: $topic) {
    id
    title
    text
  }
}
```

As of right now, if you run codegen on this, it would generate queries that would still require both `topic` and `userId` as variables. Even though we export `userId` by querying it from our client state.

**Describe the solution you'd like**

Given the query above, we could strip out `userId` as a variable based on the occurence of their `@export` directive

**Comment by dotansimha** [comment]
Thank you for reporting this @CarloPalinckx ! 

At the moment we doesn't handle specific features from `apollo-client`, but prefer to have a general types. 
The codegen core/plugin doesn't know about `@export` and how it effect the runtime. 

If someone wants to add this feature - feel free :) We always welcome PRs.

**Comment by andreialecu** [comment]
Also requested here: #3403

I ended up really needing this feature. Any pointers to where I might look to open a PR for this? Relevant files?

**Comment by andreialecu** [comment]
I was able to figure out a solution for this and opened a PR: #3886

**Comment by andreialecu** [comment]
If anyone needs to use this functionality before it is merged, there's a .patch here:

https://gist.github.com/andreialecu/d8c02b0df2f6fcd249bdd960c725f9c0

You can use [patch-package](https://npmjs.com/package/patch-package) to apply it. Simply copy/paste the contents of the gist to `./patches/@graphql-codegen+visitor-plugin-common+1.13.2.patch` and do the steps in the [setup section of patch-package](https://www.npmjs.com/package/patch-package#set-up).

**Comment by dotansimha** [comment]
Closing.

To get this behaviour, use a custom schema loader, and perform this manipulation over your existing schema. Codegen will not support anything out of the spec of `graphql`, but you can do that manually (with a custom schema loader and `graphql-compose` for example)

**Comment by ToledoNicola** [comment]
@CarloPalinckx  i have the same problem, how did you solve?

**Comment by CarloPalinckx** [comment]
> Closing.
> 
> To get this behaviour, use a custom schema loader, and perform this manipulation over your existing schema. Codegen will not support anything out of the spec of `graphql`, but you can do that manually (with a custom schema loader and `graphql-compose` for example) 

@ToledoNicola I didn't :). We have since migrated away from the `@client` directive to just using react context instead

**Comment by ToledoNicola** [comment]
@CarloPalinckx  ah ok, me too i work with angular and i use services, but it's annoying everytime get the user id and pass it to the query

and i don't  know how to create the  custom schema loader, it seems too complicated ☹️, and for now it is faster like this but I would like to use the export to make it more correct

**Comment by Maximaximum** [comment]
@andreialecu Could you please give me a hint on how to properly generate a patch file with the required changes, but for the latest (2.2.0) version of `@graphql-codegen/visitor-plugin-common`?

Looks like no one's going to work on implementing the solution suggested by @dotansimha, so I'm trying to patch the library

**Comment by andreialecu** [comment]
@Maximaximum I'm not using `@export` any more so I don't need this patch, hence I didn't update it. But what you could do is:

- clone this repository
- apply the changes from https://github.com/dotansimha/graphql-code-generator/pull/3886/files manually
- run the build script so the .ts files are transpiled to .js (forgot what it is)
- copy the outputs to your `node_modules` and test them
- in your project install [patch-package](https://www.npmjs.com/package/patch-package) and configure it
- run `npx patch-package @graphql-codegen/visitor-plugin-common` (or whatever the right one is)
