### ISSUE TITLE
Generated types conflicting with mapped types

### ISSUE THREAD

**Issue by gustavopch** [dotansimha/graphql-code-generator#2783]
**Describe the bug**
When I use `mappers`, mapped types conflict with generated types.

**To Reproduce**
Sandbox: https://codesandbox.io/s/graphql-codegen-issue-template-vbdij?fontsize=14

Take a look at `types.ts`. The are two types named `User`:
- First one is my mapped type which is imported from `my-types.ts`
- Second one is generated by this lib and declared inside `types.ts`.

**Expected behavior**
I think this lib should not generate a `User` type when I've already declared a mapped type with that name.

**Environment:**
- OS: Linux 5.3.1-arch1-1-ARCH x86_64
- `@graphql-codegen/...`: 1.8.1
- NodeJS: 8.13.0

**Additional context**
Manually deleting the generated types that conflict with my mapped types solves the problem.

**Comment by Zikoel** [comment]
I'm not an expert but the generated types have the same name of the schema, the mapper are intended for resolver types, not for the basic types that need to respect the graphql schema. You are wrong calling your mapped type with the same name as the generated ones! My two cents!

**Comment by dotansimha** [comment]
As @Zikoel said, we can't really solve that, just make sure to have different naming. 
You can also try to add prefixes to your types, it might make it easier and resolve some of the conflicts.

**Comment by gustavopch** [comment]
@dotansimha I actually tried to use the prefix, but had other issues. I'll try to create a repro and open another issue. Thanks.
