### ISSUE TITLE
Request for More Examples of Usage

### ISSUE THREAD

**Issue by rpedroni** [dotansimha/graphql-code-generator#2790]
The learning curve of this project could be greatly lowered if there were examples to follow along in the documentation, specially for usage of the different plugins.

For now, I'm better understanding the value of each one by manually installing, adding, generating and viewing the output, which is a tedious and cumbersome task.

I suggest more examples of usage overall, specially for each individual plugin.

I'll be happy to add examples once I tame what exactly each one can do (I'm loving this project but learned about it only 2 days ago :P)

**Comment by KevinJMC** [comment]
That "tedious and cumbersome task" sounds like a great PR. Share the wealth!

**Comment by dotansimha** [comment]
We updated the website with more docs, examples, live demo and getting started sections. cli also has `init` command that should help. 
Closing :)
