### ISSUE TITLE
V1.8.1 didn't update @graphql-code-generator/cli graphql-toolkit as expected

### ISSUE THREAD

**Issue by chrisbull** [dotansimha/graphql-code-generator#2816]
when installing fresh @graphql-code-generator/cli @ 1.8.1 still shows "graphql-toolkit": "0.5.16"... which has a bug. Needs to be "graphql-toolkit": "0.5.18". The package.json shows it was updated here in github, but not on NPM. Please update NPM with a 1.8.2 or something. Thanks!

**Comment by dotansimha** [comment]
@chrisbull the fix for using the latest graphql-toolkit is done, but not merged yet. 
You can use the latest alpha `1.8.2-alpha-36d48260.84` until we'll release a new version.

**Comment by dotansimha** [comment]
@chrisbull 1.8.2 available :)
