### ISSUE TITLE
How can I modify the result of a plugin?

### ISSUE THREAD

**Issue by artalar** [dotansimha/graphql-code-generator#2833]
How can I modify the result of a plugin?

Currently, I use `typescript-graphql-request` plugin and I need to make all responses fields are not optional. I start to write my own plugin to modify the result of the previous (`typescript-graphql-request`) plugin but found that I can only incrementing the result file and can't rewrite the result of previous plugins.

**Comment by dotansimha** [comment]
@artalar
The `typescript-graphql-request` plugin is using `typescript-operations` types as base types, and just creates a wrapping SDK for `graphql-request`.

The `typescript-operations` (and `typescript`) plugin has a configuration called `avoidOptionals`, try to set it to `true` and see if it works for you.

If you wish to avoid all optionals and maybe - the only way to do it is to change your schema and use non-nullable types.

**Comment by artalar** [comment]
I'm still confusing why plugins can not override the result of other plugins, but your suggestion resolves the issue, thx.
