### ISSUE TITLE
Save output files next to inputs

### ISSUE THREAD

**Issue by dobesv** [dotansimha/graphql-code-generator#284]
For the mutation and query files it would be nice to put the generated ts schema in the same folder as the original, e.g. if a file is named `login.graphql` the types for that file could go into `login.graphql.d.ts` or somesuch.

**Comment by dotansimha** [comment]
@dobesv 
I think this is a specific request that relevant to `typescript-multiple` template, right? I think it could be either a config for this template... any chance you want to implement it and create a PR? :)

**Comment by dobesv** [comment]
Actually I realized that each type could come from multiple files and it's not always clear which file a type came from the way things are now, this probably isn't worth the trouble.
