### ISSUE TITLE
jsdoc is not formatted correctly

### ISSUE THREAD

**Issue by allen-munsch** [dotansimha/graphql-code-generator#2841]
**Describe the bug**

jsdoc is not formatted correctly

ERROR: assets/js/common/graphql/types.ts:13:1 - jsdoc is not formatted correctly on this line
ERROR: assets/js/common/graphql/types.ts:13:1 - asterisks in jsdoc must be aligned
ERROR: assets/js/common/graphql/types.ts:18:1 - jsdoc is not formatted correctly on this line
ERROR: assets/js/common/graphql/types.ts:18:1 - asterisks in jsdoc must be aligned

**To Reproduce**

Run codegen
Run tslint on codegen

```
export type Maybe<T> = T | null;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /**
   * The `DateTime` scalar type represents a DateTime
   * value as specified by
   * [iso8601](https://en.wikipedia.org/wiki/ISO_8601).
   **/
  DateTime: any;
  /**
   * Leverages the internal Python implmeentation of UUID (uuid.UUID) to provide native UUID objects
   * in fields, resolvers and input.
   **/
  UUID: any;
};
```

**Comment by dotansimha** [comment]
@allen-munsch We recommend not to run tslint/eslint on codegen generated files. The effort of making it 100% compatible it not worth the effort.
You can either integrate `prettier` with the codegen (see docs) and prettify the generated file after it's being generated, or add tslint ignore for this file (using `add` plugin).
