### ISSUE TITLE
Query variables are not supported in @graphql-codegen/typescript-stencil-apollo despite doc

### ISSUE THREAD

**Issue by ChristianUlbrich** [dotansimha/graphql-code-generator#2848]
**Variables are not supported in @graphql-codegen/typescript-stencil-apollo despite doc**
[GraphQL query variables](https://graphql.org/learn/queries/#variables) are not supported with `@graphql-codegen/typescript-stencil-apollo` despite the doc saying so.

The [documentation](https://graphql-code-generator.com/docs/plugins/typescript-stencil-apollo) for typescript-stencil-apollo says that:

```
<TestComponent variables={...}>
...
</TestComponent> 
```
can be used and thus it implies, that query variables can be used. However neither the types are correctly generated nor is there actual code for this.
**To Reproduce**
* `git clone https://github.com/ChristianUlbrich/stencil-apollo#origin/add-class-with-variables`
* `cd stencil-apollo/example-with-codegen-variables`
* `npm i`
* `npm run build`

> TypeScript: src/components/my-component-with-codegen-variables/my-component-with-codegen-variables.tsx:27:10
           Type '{ variables: { id: number; }; renderer: ({ data, loading }: QueryResult<{ __typename?: "Query"; } & {
           postsOf: ({ __typename?: "Post"; } & Pick<Post, "title" | "id" | "votes"> & { author: { __typename?:
           "Author"; } & Pick<Author, "id" | ... 1 more ... | "lastName">; })[]; }, AllPostsOfAuthorQueryVariables>) =>
           any; }' is not assignable to type 'ApolloAllPostsOfAuthor &
           HTMLAttributes<HTMLApolloAllPostsOfAuthorElement>'.Property 'variables' does not exist on type
           'ApolloAllPostsOfAuthor & HTMLAttributes<HTMLApolloAllPostsOfAuthorElement>'.

**Additional context**
* Fix should not be so difficult and just involve adding proper Type generation in [packages/plugins/typescript/stencil-apollo/src/visitor.ts](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/stencil-apollo/src/visitor.ts). I try to hack a PR together...

**Comment by dotansimha** [comment]
@ardatan please take a look, you are the Stencil expert ;)

**Comment by ardatan** [comment]
@ChristianUlbrich Thank you for the fix! You can use it with this canary version until it is released;
`1.8.3-alpha-5b6e16fa.30+5b6e16fa`

**Comment by ChristianUlbrich** [comment]
@ardatan Thx. Works perfectly; how about adding / enhancing the codegen example in `stencil-apollo`? Want me to PR this as well?

**Comment by dotansimha** [comment]
Fixed in 1.8.3 

@ChristianUlbrich a PR sounds good ;) Thank you!
