### ISSUE TITLE
Required Query Variables are optional

### ISSUE THREAD

**Issue by tbrannam** [dotansimha/graphql-code-generator#2870]
**Is your feature request related to a problem? Please describe.**

I'm frustrated that my GraphQL variables are not enforced in generated hooks

```
type Query {
    hello(foo: String!): String
}
```

```
query Bar ($foo: String!) {
  hello(foo: $foo)
}
```

**Describe the solution you'd like**

Hooks (Apollo 3) generated typically have optional baseOptions.  So callers of the generated hooks sometimes forget that a query requires a variable.   If a query document includes a variable - it would be ideal if the type signature reflected this requirement.

See:  https://codesandbox.io/s/apollo-server-de1p6

**Describe alternatives you've considered**
Create module level override hooks that add required fields from their signature and call the generated ones.

**Comment by dotansimha** [comment]
@tbrannam the query and fragment you mentioned are not valid. Can you please share a reproduction of the issue? in a repo or in a codesandbox. 

Also, which version of codegen do you use?

**Comment by tbrannam** [comment]
I've created a mock server here: it has client.ts which shows how the generated hook variable contract isn't being typechecked.   It would seem that if a Query required variables, the baseOptions would no longer be marked as optional.

https://codesandbox.io/s/apollo-server-de1p6

**Comment by tbrannam** [comment]
closing pending further research

**Comment by Stuart4** [comment]
Why did you close this? `baseOptions` and `baseOptions.variables` should not be required  if the variable is required in the query.

**Comment by dotansimha** [comment]
@Stuart4 if you are still having issue with this, can you please open a new issue with a reproduction?

**Comment by eyalw** [comment]
Having the same issue here, the generated typing does not enforce user to provide mandatory variables.

**Comment by dotansimha** [comment]
@eyalw can you please share a reproduction?

**Comment by Mathieuu** [comment]
@dotansimha Here's a sandbox reproducing the issue:
https://codesandbox.io/s/apollo-server-forked-fn0q5?file=/client.ts

In that sandbox you can see that the mutation `UpdateUser` requires an `id` as an input.

However in the component:

```tsx
  // Does not throws an error with a missing id = INCORRECT
  // BaseOption should not be optional
  useUpdateUserMutation();

  // This throws an error, as it should = CORRECT
  useUpdateUserMutation({ variables: { input: { }});

  // The only correct way that should be valid = CORRECT
  useUpdateUserMutation({ variables: { input: { id: "hello" } } });
```

**Comment by filip-lipinski-tsh** [comment]
@dotansimha 
Hello! Will the changes be completed? It would be great if this were merged as this optional variables type can cause a lot of trouble.
