### ISSUE TITLE
Add "--check" flag to detect stale code

### ISSUE THREAD

**Issue by gustavopch** [dotansimha/graphql-code-generator#2872]
**Is your feature request related to a problem? Please describe.**
I need some way to check whether the generated code is up-to-date with the source code, so that I can check before every commit with husky and during CI.

**Describe the solution you'd like**
There could be a `--check` flag in the CLI that would generate all the code in memory, compare to what's in my working directory and exit with an error if they are different.

**Describe alternatives you've considered**
None.

**Additional context**
It would be similar to how `prettier --check` or `prettier --list-different` works.

**Comment by ajotaos** [comment]
This is so heavily needed. Amazing idea!!!

**Comment by mkaraula** [comment]
We are currently doing 

```
npm run codegen
git status --porcelain
git diff-index --quiet HEAD
```

in gitlab CI to make a pipeline fail if the generated code differs from what was commited.

**Comment by ajotaos** [comment]
I see benefit on a check as part of my pre commit hook while in development as well.

**Comment by dotansimha** [comment]
@ajotaos we recommend not to commit your generated files. It bloats the git repo with files that would change anyway...

**Comment by ajotaos** [comment]
You’re right I misread the issue, I was thinking about checking on the schema.prisma file.

**Comment by ajotaos** [comment]
You’re right I misread the issue, I meant that I could check whether the generated files are up to date with my configuration and schema. Like it could try to generate the files and if it succeeds, exits with zero and nothing gets created but if it runs and doesn’t match the in-memory doesn’t the generated file, it exists with non-zero.

**Comment by dotansimha** [comment]
At the moment we don't. 
You can implement it with a git-hook (using `husky` or similar tools). And just run codegen and then run `git add` to the generated files. This way it will make sure you are always committing the updated files. 
In most setups, running codegen takes less than a second, so it shouldn't be an overhead for running this during commit or push hooks.

**Comment by ajotaos** [comment]
Wouldn’t that end up commuting the generated files to git?

**Comment by dotansimha** [comment]
I thought that was your goal, and the author of that issue. 
As I said, I don't recommend to commit the generated files, but if you decide to, some actions should be taken to make sure it's always in sync.

**Comment by ajotaos** [comment]
I’ll open up another issue, it’s true it’s no the same from the author.

**Comment by elliottsj** [comment]
As an alternative, we made a general-purpose CLI which verifies that a command generates a file equivalent to the file on disk: https://github.com/Yolk-HQ/diff-verify-cli

e.g.

```ts
$ diff-verify -p ./graphql-types.ts -- node_modules/.bin/graphql-codegen --config codegen.yml
```

**Comment by charlypoly** [comment]
@elliottsj @mkaraula  @gustavopch @ajotaos 

Hi all!
Sorry for the delay in handling this feature request.
As part of our work on codegen v3, we started by improving the CLI.

Your feature request is now fulfilled with the `--check` cli flags as part of the following canary release: `@graphql-codegen/cli@2.11.0-alpha-269e9f9ad.0`

Could you give it a try and let us know? 🙏🏼

**Comment by charlypoly** [comment]
The dry-run mode is now available via the `--check` CLI flag, from `@graphql-codegen/cli@2.11.0` 📦

**Comment by leethree** [comment]
i tried the `--check` flag. it doesn't seem to work with [afterOneFileWrite](https://www.graphql-code-generator.com/docs/config-reference/lifecycle-hooks#afteronefilewrite) hook. 🤔 

```yml
hooks:
  afterOneFileWrite:
    - prettier --write
```

**Comment by charlypoly** [comment]
Hi @leethree,

This is expected, the `--check` dry run mode is not writing any file to disk; it just checks if there are any stale files.

**Comment by leethree** [comment]
@charlypoly understood. thanks!

**Comment by leethree** [comment]
Sorry my earlier comment wasn't very clear. Our generated files in working directory are formatted with `prettier`. So they will always be different from the code generated in memory. 

Essentially `--check` will always fail because the files were manipulated with `afterOneFileWrite` hook even if the files are up-to-date. Is there a way to get around this?

**Comment by charlypoly** [comment]
Okay, I get the problem!
I'll look at existing hooks and if needed, add a new one dedicated to the check mode, like "beforeCheck".

**Comment by charlypoly** [comment]
@leethree, could you try with the `beforeAllFileWrite` hook as follows (in addition to your `afterOneFileWrite` hook):

```yaml
hooks:
  beforeAllFileWrite:
    - prettier --write
  afterOneFileWrite:
    - prettier --write
```

**Comment by leethree** [comment]
@leethree I just tried it and it doesn't seem to work. It still says I have stale files and exits with 1.

**Comment by charlypoly** [comment]
After thinking more about it, it makes sense.
I don't see any solution here since we can't apply prettier to files that are not written to disk.

I guess, in the same way, we recommend not committing generated files; prettier should not be run against generated files; otherwise, it makes codegen CLI "file changes" mechanism obsolete (also for the watcher).

**Comment by leethree** [comment]
@charlypoly yeah that makes sense to me. it would be great to include this caveat in the documentation. https://www.graphql-code-generator.com/docs/integrations/prettier

**Comment by charlypoly** [comment]
@leethree, you are right, I've pushed some doc changes: 749fcc064f7770ebfe28bd22b71670e8c563dece
Will be deployed in a few minutes 🕐
