### ISSUE TITLE
Add CLI output for skipped files during the generation process

### ISSUE THREAD

**Issue by kroeder** [dotansimha/graphql-code-generator#2876]
**Is your feature request related to a problem? Please describe.**

I was playing around with hooks and was confused that my global hooks were executed but my local "output level" hooks weren't whatever I wrote in the config file.

After debugging I noticed that my file was skipped because of the output hash mechanism.

**Describe the solution you'd like**
Show something like 
```
> graphql-codegen --config codegen.yml

  √ Parse configuration
  √ Generate outputs
Running lifecycle hook "afterStart" scripts...
[CLI] Loading Schemas
[CLI] Loading Schemas
[CLI] Loading Documents
[CLI] Generating output
  - Skipped unchanged file 'path-to/some-generated-file.ts'
[CLI] Loading Documents
[CLI] Generating output
```

**Describe alternatives you've considered**
Show info about skipped files in `DEBUG=1` env mode

**Additional context**
If you agree with this I'd be happy to contribute this, just let me know 🙂

**Comment by dotansimha** [comment]
@kroeder PR sounds perfect ;) Thanks

**Comment by dotansimha** [comment]
It's already available, we can close this (https://github.com/dotansimha/graphql-code-generator/blob/1d3bf1f97f879ad175f9b039a24d27ff9d9edc3e/packages/graphql-codegen-cli/src/generate-and-save.ts#L47)
