### ISSUE TITLE
Is there a way to have a combined type instead of a collection of <Pick...>'s?

### ISSUE THREAD

**Issue by reinvanimschoot** [dotansimha/graphql-code-generator#2910]
Hi guys

It was kind of difficult to explain my question in the title but I'll try to elaborate a bit more.

When I use GraphQL Codegen to generate TypeScript types for my operations, the return values of said operations are never just 1 type but a collection of `<Pick >`'s.

To illustrate:

![Screenshot 2019-11-07 at 09 27 10](https://user-images.githubusercontent.com/35171567/68372586-78d5c900-0141-11ea-89c3-75a94852da99.png)

The problem is that, when you have a query that returns a list of values, like for example a list of Posts, there is no way to reference the type of an item in that list since it is not stored separately. It is just that list of `<Pick>`'s as seen in the screenshot.

Is there a way to alter my codegen setup to make this work? I had no problems getting this result while using Apollo Codegen but I really would love it if I could just use GraphQL Codegen for everything going forward.

Or maybe there is a typescript feature that would let me reference the type of one array element?

Thanks for the help!

**Comment by pnordhus** [comment]
I'm not sure if codegen provides an option to generate these types, but you should be able to get what you need with
```typescript
type TechnicianJob = JobsForTechnicianQuery['jobsForTechnician']['nodes'][0];
```
`[0]` extracts the type of the first array element. You can specify any index here, as all elements in a TypeScript array have the same type.

**Comment by pachuka** [comment]
You can use [preResolveTypes: true](https://graphql-code-generator.com/docs/generated-config/base-documents-visitor#preresolvetypes-boolean-default-value-false) to resolve the primitives. For the subtypes you may want to create Fragments since those also get typed explicitly.

**Comment by ardatan** [comment]
I'm closing this issue now. Feel free to open a new one if you have another issue.
