### ISSUE TITLE
graphql field alias not typed correctly (preset near-operation-file / preResolveTypes)

### ISSUE THREAD

**Issue by cmattick** [dotansimha/graphql-code-generator#2916]
**Describe the bug**
When using preset near-operation-file with option preResolveTypes the generated type for a graphql field with an alias is missing the "Types." prefix coming from the imported base types.

**To Reproduce**
https://codesandbox.io/s/near-operation-file-issue-with-alias-6esqp

Run 'yarn start' for the code generation process which produces the issue. See document.ts for the resulting error.

**Expected behavior**
In document.ts we should have "dep: Types.Department" instead of "dep: Department"

**Comment by dotansimha** [comment]
@cmattick Thanks, fixed this in: https://github.com/dotansimha/graphql-code-generator/pull/3017

**Comment by dotansimha** [comment]
Fixed in 1.9.0
