### ISSUE TITLE
Parse error for string-valued defaults

### ISSUE THREAD

**Issue by jsshapiro** [dotansimha/graphql-code-generator#2928]
The following input type parses (correctly) without complaint:

```
input TestTypeInput {
    id: ID!
    lang: String! = "en"
}
```
But the following _regular_ type does not:

```
type TestType {
    id: ID!
    lang: String! = "en"  # If the default value is present, parsing fails
}
```

If I am reading the GraphQL spec correctly, this default value should be legal in both places.

** To Reproduce **
Construct a graphql schema file with the two types above. Execute graphql-codegen on this file.

**Expected behavior**
The graphql spec allows defaults on both input types and regular types. graphql-codegen
accepts defaults on regular type fields when the types are integer, float, or boolean. It apparently does _not_ accept them when the field type is string.

The problem looks like a parse issue, so the underlying cause may actually be in the parser provided by the GraphQL npm package.

**Comment by jsshapiro** [comment]
On further investigation, it appears that the parser may not accept defaults on Object fields of _any_ type - all of the current defaults in my schema appear on Input Object fields. I have confirmed that the spec allows defaults on Types, though it doesn't seem to me that this is conceptually a good idea.

Regardless, there is a difference of opinion between the spec and the implementation, and one or the other is incorrect.

Like I said, happy to file the bug on GraphQL/lang/schema if that's the right place for it.

Thanks again, and thanks for all of your excellent work. I've written several production compilers, so I appreciate what you've done here. :-)

**Comment by dotansimha** [comment]
@jsshapiro yes you are right, is seems like `graphql.js` doesn't accept the default values on `type`, only for input/variables/arguments.

**Comment by jsshapiro** [comment]
Can you advise where to file a bug against graphql.js?

Thanks!
