### ISSUE TITLE
Error diagnostics do not provide input file name or line number

### ISSUE THREAD

**Issue by jsshapiro** [dotansimha/graphql-code-generator#2929]
When an input syntax error is present, the error diagnostic from graphql-codegen is a backtrace. Since the backtrace mainly talks about the GraphQL parser internals, it isn't all that helpful. Conspicuously _absent_ in the output is the file name and line number where the syntax error was encountered.

It appears to me that the desired source file and position information may be present in the GraphQLError object in the fields 'source' and 'positions'.  Is there any chance you might check if this is the case, and if so, report the source position of the error rather than the callstack of the exception?

If the information is not present or if this is actually a parser error in the graphql/lang/schema package, please advise and I'll be happy to file a bug there.

Thank you!

**Comment by ardatan** [comment]
Could you share a reproduction with codesandbox?

**Comment by jsshapiro** [comment]
I'll try to isolate a small example next time it happens and add it.

As far as I can tell, the problem is true for EVERY syntax error. The only
syntax diagnostic I've ever seen out of graphql-codegen is a backtrace. A
backtrace doesn't provide the original source file and line number where
the error occurs.

**Comment by dotansimha** [comment]
@jsshapiro any update?

**Comment by dotansimha** [comment]
@jsshapiro ?

**Comment by mdugue** [comment]
@dotansimha any news on this? I think a hint on the file and line of code would be very helpful

**Comment by ardatan** [comment]
See;
https://github.com/dotansimha/graphql-code-generator/issues/4227

**Comment by mdugue** [comment]
thanks for the hint!
