### ISSUE TITLE
Add JSDoc based plugin for environments that aren't running typescript or flow

### ISSUE THREAD

**Issue by CarloPalinckx** [dotansimha/graphql-code-generator#2934]
**Is your feature request related to a problem? Please describe.**

Currently, there are environments that could rely on JSDoc to type check their code. It would be great if we could reach out to those people as well 🙌 

**Describe the solution you'd like**

If we could add a plugin that generates operation types in JSDoc, we could allow other plugins to tap into those defined types. Which could avoid possible duplicate code if we want to expand on the plugins that contain docblocs.

I suggest:
- A `jsdoc-operations` plugin that defines types for query/mutation/fragment results and variables.
- In every plugin that has docblocs we could check if a user has the jsdoc plugin enabled. If they do, we can go ahead and add more extensive information to the docblocs like type annotations.

**Comment by CarloPalinckx** [comment]
I made some progress on this in https://github.com/CarloPalinckx/graphql-code-generator/tree/jsdoc-operations

**Comment by dotansimha** [comment]
WIP in this PR: https://github.com/dotansimha/graphql-code-generator/pull/3223

**Comment by CarloPalinckx** [comment]
since #3223 has been merged, this issue can be closed I guess 🚀
