### ISSUE TITLE
[docs] skipTypename description may be wrong

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [dotansimha/graphql-code-generator#2985]
It [currently says](https://graphql-code-generator.com/docs/plugins/typescript-operations#skiptypename-boolean-default-value-false):

> Automatically adds __typename field to the generated types, even when they are not specified in the selection set.

But based on my experiments in combination with [this issue](https://github.com/dotansimha/graphql-code-generator/issues/2683), I suspect it should probably be something like this instead?

> Does not add __typename to the generated types, unless it was specified in the selection set.

**Comment by dotansimha** [comment]
Thanks @s-h-a-d-o-w ! Pushed a fix. 
I will be deployed to our website with the next release.

**Comment by dotansimha** [comment]
Fixed in 1.9.0
