### ISSUE TITLE
DOS vulnerability in indirect dependencies

### ISSUE THREAD

**Issue by pdemarino** [dotansimha/graphql-code-generator#2997]
**Describe the bug**
`npm audit` reports a vulnerability in indirect dependencies

**To Reproduce**

```
mkdir x
cd x
npm init
npm install @graphql-codegen/typescript@1.8.3 
npm audit
```

Output is:

```
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mem                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @graphql-codegen/typescript                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @graphql-codegen/typescript >                                │
│               │ @graphql-codegen/visitor-plugin-common > relay-compiler >    │
│               │ yargs > os-locale > mem                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1084                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 low severity vulnerability in 2135 scanned packages
  1 vulnerability requires manual review. See the full report for details.


```

**Expected behavior**
`npm audit` should be clean

**Environment:**

- OS: Ubuntu Linux
- @graphql-codegen/typescript  1.8.3
- NodeJS: 12.13.1

**Additional context**
None

**Comment by dotansimha** [comment]
You are right, `yarn audit` shows the same, I think upgrading relay compiler might solve this (https://github.com/dotansimha/graphql-code-generator/pull/2798)

**Comment by dotansimha** [comment]
It seems like it's not updated in `relay-compiler -> yargs -> mem`. 

I think the codegen and it's dependencies shouldn't be in use in production, so as long as it's being remained as devDependency - I think it shouldn't have any effect. 

You can workaround this by using `resolutions` field in `package.json` (with Yarn), and override the dependency for `mem`.

**Comment by cktang88** [comment]
Will there be a new release soon that incorporates this change?

**Comment by dotansimha** [comment]
@cktang88 @pdemarino 
I suggested a workaround in the comment above. Also, using the codegen as `devDependency` shouldn't effect your production usage. 

The actual fix should be done in `relay-compiler`, by upgrading `yargs` to latest version.

**Comment by marklawlor** [comment]
> @cktang88 @pdemarino
> I suggested a workaround in the comment above. Also, using the codegen as `devDependency` shouldn't effect your production usage.
> 
> The actual fix should be done in `relay-compiler`, by upgrading `yargs` to latest version.

The fix has already been published https://github.com/facebook/relay/pull/2934
