### ISSUE TITLE
Unable to find field "(...)" on type "(...)"!

### ISSUE THREAD

**Issue by andreyvital** [dotansimha/graphql-code-generator#3018]
I'm getting a lot of:
```
→ Unable to find field "(...)" on type "(...)"!
```

With the latest version of @graphql-codegen `near-operation-file`. I wish I could put the schema here, but I can't create a reproducible example right now. I am querying fields that exists on those types....and the weird part is, it's random—if I comment out certain fields, it works.

Right now I am using @1.7.0 and everything seems to be working well, but it'd be neat if I could update to the latest.

**Comment by dotansimha** [comment]
Hi @andreyvital 
We really would like to help, but we need a reproduction, and information regarding your queries and schema, and you configuration file.

**Comment by dotansimha** [comment]
@andreyvital ?

**Comment by andreyvital** [comment]
@dotansimha I'll try to create a reproducible example later. Sorry for the delay

**Comment by dotansimha** [comment]
@andreyvital Closing. Feel free to contact us again it's still relevant :)

**Comment by andreyvital** [comment]
Hi @dotansimha. I've created a reproducible example here:

https://codesandbox.io/s/ecstatic-hill-f2dbd

```
Error: Unable to find field "chiefExecutiveOfficer" on type "ReclameAquiRating"!
```

It thinks that I am querying `chiefExecutiveOfficer` on `ratings` or `ReclameAquiRating`. Right now I'm stuck with this:

```DIFF
-    "@graphql-codegen/cli": "^1.4.0",
-    "@graphql-codegen/fragment-matcher": "^1.4.0",
-    "@graphql-codegen/near-operation-file-preset": "^1.4.0",
-    "@graphql-codegen/typescript": "^1.4.0",
-    "@graphql-codegen/typescript-operations": "^1.4.0",
+    "@graphql-codegen/cli": "^1.10.0",
+    "@graphql-codegen/fragment-matcher": "^1.10.0",
+    "@graphql-codegen/near-operation-file-preset": "^1.10.0",
+    "@graphql-codegen/typescript": "^1.10.0",
+    "@graphql-codegen/typescript-operations": "^1.10.0",
```

Can't go from 1.40 to any version above.
