### ISSUE TITLE
Not all constituents of type 'Resolver<...>' are callable.

### ISSUE THREAD

**Issue by raphrueda** [dotansimha/graphql-code-generator#3024]
**Describe the bug**
I'm in the middle of upgrading from 0.8.2 to 1.8.3 and I'm getting some type issues trying to call a resolver from another resolver.
I'm typing my 'sub' resolvers (which are merged with `merge-graphql-schemas`) with the generated `Resolvers<Context>`. When I want to resolve a field in Resolver A with Resolver B, I get the following TS error when trying to call Resolver B.
```
This expression is not callable.
  Not all constituents of type 'Resolver<ResolverTypeWrapper<B>, {}, SessionContext, RequireFields<QueryBArgs, "id">>' are callable.
    Type 'StitchingResolver<ResolverTypeWrapper<B>, {}, SessionContext, RequireFields<QueryBArgs, "id">>' has no call signatures.
```
I'm guessing that because the Resolver type is an enum of StitchingResolver and ResolverFn and only the latter is callable.

**To Reproduce**

1. My resolvers:
In account.resolvers.ts
```typescript
export const accountResolver: Resolvers<SessionContext> = {
    Query: {
        account: async (root, args, context) => {      /** Returns type Account **/
            const apiService = new ApiService(context.apiClient);
            return apiService.getAccount(args);
        },
    },
    Account: {
        client: async (account, args, context, info) => {
            return clientResolvers.Query.client(      /** Error: This expression is not callable. **/
                account,
                { id: account.clientId },
                context,
                info,
            );
        },
    },
};
```

In client.resolvers.ts
```typescript
export const clientResolver: Resolvers<SessionContext> = {
    Query: {
        client: async (root, args, context) => { 
            const apiService = new ApiService(context.apiClient);
            return apiService.getClient(args);
        },
    },
};
```

**Expected behavior**
To be able to call Resolver type

**Environment:**

- OS: MacOS 10.14.6
- `@graphql-codegen/1.8.3`: 
- NodeJS: 10.16

**Additional context**
I was originally able to achieve this when on v0.8.2 by typing my resolvers with the following
```typescript
type clientResolversType = {
    Query: QueryResolvers.Resolvers<SessionContext, any>;
};

type ClientResolversType = {
    Query: QueryResolvers.Resolvers<SessionContext, any>;
    Mutation: MutationResolvers.Resolvers<SessionContext, any>;
    Client: ClientResolvers.Resolvers<SessionContext, Client>;
};

const clientResolver: ClientResolversType = {
    ...
}
```
My work around at the moment is to explicitly type the resolver like so
```typescript
    Account: {
        client: async (account, args, context, info) => {
            return (clientResolvers.Query.client as ResolverFn<
                ResolversTypes['Client'],
                {},
                SessionContext,
                QueryClientArgs
            >)(  
                account,
                { id: account.clientId },
                context,
                info,
            );
        },
    },
```

**Comment by ardatan** [comment]
@raphrueda `resolvers.<TypeName>.<FieldName>` may not be always a function. So typings are correct. It'd better to export reused business logic as a seperate function.

**Comment by raphrueda** [comment]
Right, so there would be no way to explicitly call a resolver function typed as `Resolver<Context>`? It was convenient having the arguments of the nested resolver typed.

**Comment by dotansimha** [comment]
@raphrueda If you are not really using schema stitching, set `noSchemaStitching: true` in your config file.

**Comment by dotansimha** [comment]
Closing. @raphrueda let me know if you need any help with that.
