### ISSUE TITLE
How to define cacheControl

### ISSUE THREAD

**Issue by ktalebian** [dotansimha/graphql-code-generator#3043]
I'm trying to use the https://github.com/apollographql/apollo-server/tree/master/packages/apollo-cache-control `@cacheControl`; well I want the final schema to have that. If I use

```
query ServerGetFeaturesData @cacheControl(maxAge: 3200)($userId: ID!) {
...
}
```

the codegen throws an error, rightfully so. So how can I define this query to be cachable?

**Comment by dotansimha** [comment]
Hi @ktalebian ! 

If you need to extend your schema with directives, you can declare it in a `.graphql` file and load it with the rest of the schema, the codegen will get it merged so your queries won't throw on those. Similar to the solution with `@client` directive.

I think the `@cacheControl` directive should be defined as following:

```graphql
directive @cacheControl(maxAge: Int!, scope: String = "PUBLIC") on FIELD
```

So you can put it in `directives.graphql` file, and then merge it with the rest of the schema:

```yml
schema: 
  - http://localhost:3000/graphql # Or any other schema location you are currently using
  - ./directives.graphql
```
