### ISSUE TITLE
Feature: Plugin for generating fragments from schema

### ISSUE THREAD

**Issue by TikiTDO** [dotansimha/graphql-code-generator#3048]
I would like to generate string fragments, similar to what [develomark/graphql-cli-generate-fragments](https://github.com/develomark/graphql-cli-generate-fragments) does, but in a more frequently updated framework. 

The use-case is moving from an old REST to a new graphql implementation. The best way I can figure out to do this involves coding a whole lot of fragments by hand, which seems like a waste of time given the existence of tools like this one. 

Ideally I'd like to be able to do something like this for every single model type in the system, which would help speed up the migration. 

```ts
import { User } from "../generated/app.fragments.graphql"

const query = gql`
    query CurrentUser {
    currentUser {
      ...User
    }
  }

  ${User}`
```

**Comment by dotansimha** [comment]
Tracking here: https://github.com/dotansimha/graphql-code-generator/discussions/2349
