### ISSUE TITLE
Loading GraphQL schema object, text, ast, or introspection json from JavaScript ES6 export

### ISSUE THREAD

**Issue by webberwang** [dotansimha/graphql-code-generator#305]
```javascript
const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
})

export default schema

gql-gen --schema ./**/schema.js --project ./server/models/
```
I'm using tsc to compile TS to JS, and loading the compiled schema.js

The schema created should be the right type, cause it's generated using makeExecutableSchema().

**Comment by dotansimha** [comment]
@webberwang do you get an error? I didn't understand what's the issue...

BTW, you don't have to compile TS before running the generator, you can use the TS file: https://github.com/dotansimha/graphql-code-generator#typescript-support

**Comment by webberwang** [comment]
@dotansimha thanks, it was some issue with tsconfig.json I believe, ended up working later
