### ISSUE TITLE
Provide a simple way to override schema type for a given field, prior to codegen step

### ISSUE THREAD

**Issue by ahrnee** [dotansimha/graphql-code-generator#3051]
**Is your feature request related to a problem? Please describe.**
My schema has a jsonb scalar fileld type. However, the TypeScript codgen plugin simply resolves this to an `any` TypeScript type. I am looking for a way to provide a custom override type for that field, so that I can get access the JSon contents of that field in a stongly typed way.

**Describe the solution you'd like**
I would like to simple mechanism to provide a custom type for a given field, so that the code-generation uses the custom priovided type instead of the original schema provided type

**Describe alternatives you've considered**
 - I have defined an additional client schema with the desired field type, but (logically) get codegen errors saying that the field is already defined
- I have looked for ways of easily altering the schema prior to the code-gen step, but am struggling to figure it out.

**Additional context**
I am using an Hasura API, with typescript and typescript-react-apollo plugins

**Comment by dotansimha** [comment]
@ahrnee just overriding the field doesn't work? 
redeclare it in a `.graphql` file and add it to your `schema:`, i think it should override the field type.

**Comment by ahrnee** [comment]
@dotansimha - thanks for your response, but that doesn't seem to work in my case. I get the following error:

```
  Unable to merge GraphQL type "MyEntity": Field "myjsonbfield" already defined with a different type. 
  Declared as "MyCustomFieldType", but you tried to override with "jsonb"
```

**Some Futher Details:**
- Im using the [Hasura GraphQL engine](https://github.com/hasura/graphql-engine), which always results in a "jsonb" scalar for all jsonb field types
- I have a client .graphql where I tried to redeclare the field type

**Sidenote**
I also have a [feature-request in with the Hasura Team](https://github.com/hasura/graphql-engine/issues/3451) to custom scalar types to be configured for jsonb fields, but at present this is not possible.

**Comment by FranckErnewein** [comment]
Same problem here.
We generate types from Datocms GraphQL API.
Most of enums are just `Scalars['String']`.
We really need to override for some fields and we can not change the source API. 
We tried to define a local schema but we have the same Error 

```
Unable to merge GraphQL type "TitleRecord": Field "variant" already defined with a different type. Declared as "Variant", but you tried to override with "String"
        Error: Unable to merge GraphQL type "TitleRecord": Field "variant" already defined with a different type. Declared as "Variant", but you tried to override with "String"
```
It would be very nice to allow merge if needed

**Comment by dotansimha** [comment]
I think the best way to do that is to use a custom schema loader, then you can manipulate your schema in any way you wish to. (for example, using `graphql-compose` to change the schema).

Closing.

**Comment by balazsorban44** [comment]
Just checking, is it still the recommended way to use something like `graphql-compose` for this?

Getting an enum in a query (defined as `string` in the schema), and would like to override the generated type for it. Is there a plugin to modify the schema somehow before it is read by the code generator?

**Comment by dotansimha** [comment]
> Just checking, is it still the recommended way to use something like `graphql-compose` for this?
> 
> Getting an enum field in a query (defined as `string` in the schema), and would like to override the generated type for it. Is there a plugin to modify the schema somehow before it is read by the code generator?

TBH, I don't have a recommended way of doing that. You can use anything you wish to perform that. 

We allow you to specify a code file (that will be `require`d) by codegen, and it acts as a custom loader -you just need to make sure to export a valid `GraphQLSchema` object. So you can load, manipulate and transform your schema before feeding it to codegen.

```yaml
generates:
  file.ts:
    schema: ./my-file.js
```

Then:

```
// my-file.js

const mySchema = { ... }; // Should be GraphQLSchema

module.exports = mySchema;
```

See https://graphql-code-generator.com/docs/getting-started/schema-field#code-files and  https://graphql-code-generator.com/docs/getting-started/schema-field#custom-schema-loader

**Comment by ferm10n** [comment]
I think there's a good chance a lot of hasura users will be looking for something like this, here's a link to an example using a custom schema loader: https://github.com/hasura/graphql-engine/issues/3451#issuecomment-846426643
