### ISSUE TITLE
Fragment in schema stitched resolver is not reflected in parent type

### ISSUE THREAD

**Issue by reinvanimschoot** [dotansimha/graphql-code-generator#3057]
**Describe the bug**
 

When providing a resolver with schema stitching, the fragment has no influence on the type of the parent field. In other words, even though a field was specifically declared in the fragment, it is not added as part of the parent type.

**To Reproduce**
Steps to reproduce the behaviour:

![Screenshot 2019-12-01 at 15 33 05](https://user-images.githubusercontent.com/35171567/69915510-16c26800-1450-11ea-8cbe-41a7bd67cfa8.png)

![Screenshot 2019-12-01 at 15 33 16](https://user-images.githubusercontent.com/35171567/69915512-1a55ef00-1450-11ea-9d64-c73330e9b248.png)

I'm not sure if this is the intended behaviour or not?

**Comment by ardatan** [comment]
@reinvanimschoot Could you share your `Comment` type?

**Comment by dotansimha** [comment]
@reinvanimschoot We are still waiting for your response. 
Closing for now, let us know if it's still relevant.
