### ISSUE TITLE
typescript-urql produces invalid type for subscription handler param

### ISSUE THREAD

**Issue by purge** [dotansimha/graphql-code-generator#3062]
**Describe the bug**
typescript-urql produces invalid type for subscriptions handler

**To Reproduce**
See a minimal reproduction in this sandbox (types.ts):

https://codesandbox.io/s/graphql-codegen-issue-template-xg9lq?fontsize=14&hidenavigation=1&theme=dark

**Comment by shd101wyy** [comment]
Yeah I encountered the same problem. Any solutions? Thanks in advance.

**Comment by dotansimha** [comment]
Thanks for reporting this @purge . We'll take a look.

**Comment by dotansimha** [comment]
@shd101wyy @purge 
I think I managed to fix that in: https://github.com/dotansimha/graphql-code-generator/pull/3122 

Can you please give it a try with the following alpha? `1.9.2-alpha-72d88dde.40`

**Comment by dotansimha** [comment]
Fixed in `v1.10.0`.
