### ISSUE TITLE
Fragments don't import scalars correctly

### ISSUE THREAD

**Issue by micimize** [dotansimha/graphql-code-generator#307]
[scalars don't seem to be imported](https://github.com/micimize/graphql-code-generator/blob/75d08522519129350e11d73796da12c445a793e1/dev-test/githunt/ts-multiple/repoinfo.fragment.ts#L4) by fragments, unless part of a nested type.

Very excited about 0.9.x btw, looking forward to reworking [graphql-to-io-ts](https://github.com/micimize/graphql-to-io-ts) to use the template helpers 👍

**Comment by dotansimha** [comment]
@micimize I'm considering to deprecate the multiple files generators. What do you think? is there any special usage you can't do with the single template?

**Comment by micimize** [comment]
Not that I can think of off the top of my head. It's convenient for viewing generated definitions in editors that don't handle large files well, but if it's a maintenance pain point then it's probably not worth it.

Is this only a problem because it's a multiple-file edge case?

**Comment by dotansimha** [comment]
@micimize It's hard to maintain and we find a lot of bugs (usually related to missing imports or missing data).

**Comment by micimize** [comment]
@dotansimha Ok, let me try refactoring to single-file and get back to you, although I don't think it'll be a problem for typescript. It's harder to think about the possible problems across all languages, but I think even "convenience directory structuring" could be solved by allowing multiple top level templates

**Comment by dotansimha** [comment]
Hi @micimize , any update?
I've been thinking a lot about that, and in every project that we initially started with multiple files template, we eventually refactored it and used the single file, since it's easier to use and easier to import from.

**Comment by micimize** [comment]
@dotansimha finally got around to implementing single-file, no problems so far. I think we can safely close this and commit to deprecating multi-file outputs.
