### ISSUE TITLE
Support Client Generation Only

### ISSUE THREAD

**Issue by mikebm** [dotansimha/graphql-code-generator#3074]
Prior to version 1.0, you could use the following plugins to only generate client side.
```
typescript-common
typescript-client
```
Now, you must use:
```
typescript
typescript-operations
```
The problem with this is `typescript` adds server side types that do not match up with the client side queries. This can make it confusing for developers and thus they start importing these server types and referencing fields that were not defined in the query.

It would be super beneficial when using `typescript-operations` to exclude the server side types. Simply, removing `typescript` from the codegen doesn't work because many required types are missing such as Scalars, Maybe, etc.

**Comment by ardatan** [comment]
`Pick` is used to pick used fields in queries, schema types are not used exactly. `typescript` package itself generates typings of schema types to be reused in operation typings. Typings of schema doesn't mean server-side types. We have `resolvers` package for server-side implementation. `typescript` package generates schema types for both client and server-side types. You can see how it works in the examples;
https://github.com/dotansimha/graphql-code-generator/blob/1222b56253542fbdcfbd1207075a2409921d67b5/dev-test/githunt/types.ts#L177
So, `typescript` and `typescript-operations` package together generates typings for client-side,

**Comment by mikebm** [comment]
Pick had to be turned off in my case, because when used with compatibility, everything was Maybe, which is not what ideal. When I define them as server types, it is because most of the types (excluding inputs), are more representative of the complete schema type. This causes confusion when importing types.

For example, we have a cart schema that exposes 14 properties. We have 2 queries, one of those only uses 5 of the fields, and the other uses some of those 5 but many of the other ones. Now, if I import "Cart", it contains every used field from both queries. The only way to get the proper types would be to do type extraction from the Query, which is cumbersome and ugly. To new developers coming in, this adds much confusion.
