### ISSUE TITLE
Add explicit types for resolver parent types

### ISSUE THREAD

**Issue by stephenh** [dotansimha/graphql-code-generator#3093]
Currently it looks like the resolvers generator relies on applying `mapper`-based transforms via an inline mapped type to the standard typescript plugin types.

I.e. if I have a `Project` type with `client: Client` field, and use a mapper to map `Client`'s parent type to say `DbClient`, then the `ResolversObject` ends up looking like:

```typescript
export type ResolversTypes = ResolversObject<{
  Project: ResolverTypeWrapper<Omit<Project, "client"> & { client: ResolversTypes["Client"] }>;
}>
```

Where `ResolversTypes["Client"]` is the `DbClient` as configured.

This is just fine, but I'd like to get at the `Omit<Project, "client"> & { client: ResolverTypes["Client"] }>` bit to use it as a generic argument for some default resolver behavior/metaprogramming thing.

I could probably "pick" that out with some sort of `GetWhatIWant<ResolversTypes, "Project">` that would: a) find the `Project` key and it's value, and then b) de-wrap the `ResolverTypeWrapper` out of the value as I don't want the `Promise<T> | T` part of that.

Or, selfishly, it would be easier if there was just already a type alias for this, i.e.:

```typescript
export type ProjectParent = Omit<Project, "client"> & { client: ResolversTypes["Client"] }>;
```

So that `ResolversTypes` was now:

```typescript
export type ResolversTypes = ResolversObject<{
  Project: ResolverTypeWrapper<ProjectParent>;
}>
```

Also, I'm not entirely sure why, but I'd be tempted to just straight up make a new type, i.e.:

```typescript
export interface ProjectParent {
  client: ResolverTypes["Client"];
  name: ResolverTypes["String"];
}
```

And not depend on the "base"/client-focused/`Project` types at all. I guess it seems conceptually simpler to have a dedicated-to-the-server-side type.

(...I suppose if a project has both a `Project` and `ProjectParent` as their own real types, then the `${type}Parent` is going to conflict with that; I assume graphql-code-generator as a general way of detecting/avoiding those sorts of things.)

**Comment by stephenh** [comment]
Ah, nevermind, I see the `ResolverParentTypes["Client"]` is exactly what I want. 

I think pedantically I would have found that easier if `ResolversTypes` used the `ResolverParentTypes` instead of re-defining the same inline type.

Would that be an okay change? I would probably figure out a PR for that if that's okay.

**Comment by dotansimha** [comment]
@stephenh Sounds good, it makes sense to reuse those types.

**Comment by dotansimha** [comment]
Closing for now. @stephenh if you want to improve that, feel free to open a PR :) 
Thanks
