### ISSUE TITLE
Add support for "--export" flag

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#31]
Use a schema from a JavaScript file that exports the GraphQLSchema, to use with a local environment, and without starting a local server instance.
The flag will be in use instead of "--url" and "--file".

@DxCx , you wanted something like that, right?

**Comment by dotansimha** [comment]
Implemented in 0.5.0

**Comment by DxCx** [comment]
After exploring this i found out it brings problems. Scheme is depeneded on typings.
Eventually i worked against export type definitions and not export scheme, since this is what you really need

**Comment by dotansimha** [comment]
Yeah I got it. 
What do you think about scanning for type definitions (like we do for client side) in your code files? and then use then to create the schema object. 

@DxCx

**Comment by DxCx** [comment]
@dotansimha
im not sure scanning is really needed,
all you need is to process a javascript file which exports the typedefinitions.

let's discuss this further offline ;)
