### ISSUE TITLE
Additional examples of generator templates written in JS

### ISSUE THREAD

**Issue by peterschussheim** [dotansimha/graphql-code-generator#311]
Very nice work on this project!  I am interested in helping to [add Flow support](https://github.com/dotansimha/graphql-code-generator/issues/160), however, I prefer not to use handlebars templates.  

I see a recently added a feature that allows users to write templates in TS or JS; are you able to expand on [this example](https://github.com/dotansimha/graphql-code-generator/tree/master/packages/templates#write-your-own-output-processor) a little further so that others and myself can use it to write more templates?

**Comment by dotansimha** [comment]
@peterschussheim You are right, in the recent versions we added the option to write a custom generator, that is not based on Handlebars! 

I do not have an example at the moment, but a very simple tests that use this feature are available here: 
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/tests/custom-processor.spec.ts (take a look at the processor js file)

And also, you can find the code that execute the output processor here:
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-compiler/src/compile.ts#L82-L99 

It's still a new feature, so it's not well documented. I hope I'll have some time this week to add a good example for it.

Also - if you have the time to add a Flow template - it would be great! We had one in the past, but we didn't have time to migrate it after a big refactor.

**Comment by flexzuu** [comment]
Hey i really like the general js approach. Would it be possible or maybe it currently even is supported. To pass the actual document path in on generation (obviously only in the document generation part not schema related stuff)

**Comment by peterschussheim** [comment]
I'd be happy to add a flow template once the documentation is improved.

**Comment by dotansimha** [comment]
@peterschussheim @flexzuu 
It's not a complete documentation, but you can take a look at a real example for a template without Handlebars here:
https://github.com/dotansimha/graphql-code-generator/tree/master/packages/templates/introspection

**Comment by dotansimha** [comment]
It's available now in our new website: https://graphql-code-generator.com/docs/custom-codegen/
