### ISSUE TITLE
Unnecessary mapping from old verion of graphql-toolkit

### ISSUE THREAD

**Issue by Kerumen** [dotansimha/graphql-code-generator#3134]
**Describe the bug**

On `graphql-codegen-core` there is a mapping of the documents passed to `validateGraphQlDocuments`:

```js
...documents.map(({ filePath, content }) => ({ location: filePath, document: content }))
```

https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/codegen.ts#L51

It's because `graphql-toolkit` used to generate documents with `filePath` and `content`. However in [v0.6.0](https://github.com/ardatan/graphql-toolkit/releases/tag/v0.6.0) they were a breaking change: 

- `DocumentFile` has been changed to `Source` (`{ filePath, content }` to `{ location, document }`).

`graphql-codegen-core` depends on v0.7.4 of `graphql-toolkit`:

https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/package.json#L44

I don't think this mapping is necessary anymore: I'm using latest `graphql-codegen` and latest `graphql-toolkit` and it throws an error).

Thoughts?

**Comment by ardatan** [comment]
GraphQL Toolkit uses `Source` which has `document: DocumentNode` and `location: string` but `DocumentFile` has `content: DocumentNode` and `filePath: string`. It is still like that as I see in the code. Could you share a reproduction to see what errors you have etc?

**Comment by dotansimha** [comment]
As @ardatan said, it seems like the codegen uses it correctly. Closing.
