### ISSUE TITLE
Generate @deprecated annotations in typescript doc comments

### ISSUE THREAD

**Issue by ab-pm** [dotansimha/graphql-code-generator#3141]
I've got a GraphQL schema that has some `@deprecated` types and/or fields. While the descriptions already translate into tsdoc comments with the `typescript` plugin, the deprecations are not mentioned anywhere in the generated type declarations and the typescript compiler won't warn me when using those properties. I would expect a [`@deprecated` tag](https://api-extractor.com/pages/tsdoc/tag_deprecated/) to get created in the doc comment of the respective typescript declaration.

**Comment by dotansimha** [comment]
Available in `v1.13.1` 🎉
