### ISSUE TITLE
how to generate all possible graphql queries, mutations and subscriptions from schema

### ISSUE THREAD

**Issue by saostad** [dotansimha/graphql-code-generator#3153]
is there any way to generate all possible graphql queries, mutations, and subscriptions from the schema for client-side use?

**Comment by dotansimha** [comment]
We have open issues for this: 
- https://github.com/dotansimha/graphql-code-generator/issues/2349 
- https://github.com/dotansimha/graphql-code-generator/issues/3048

PRs are welcome ;)
