### ISSUE TITLE
Generate resolver types?

### ISSUE THREAD

**Issue by AndreiEzhov** [dotansimha/graphql-code-generator#319]
Currently using [graphql-schema-typescript](https://github.com/dangcuuson/graphql-schema-typescript#type-resolvers) to generate resolver typings, forcing me to use different types on client and server. Would love to see this added to graphql-code-generator.

**Comment by dotansimha** [comment]
It sounds good. @AndreiEzhov can you provide an example for the output?

**Comment by fabien0102** [comment]
I was actually searching for this kind of feature, the last missing part to have a fully server side types safety for me ^^

To provide an example:

### Schema
```graphql
type Bundle {
  id: ID!
  name: String!
 }
 
type Query {
  bundle(bundleId: ID!): Bundle
  allBundles(projectId: ID!): [Bundle]!
}
```

### Actual generated types
```ts
/* tslint:disable */

export interface Query {
  bundle?: Bundle | null
  allBundles: (Bundle | null)[]
}

export interface Bundle {
  id: string
  name: string
}
export interface BundleQueryArgs {
  bundleId: string
}
export interface AllBundlesQueryArgs {
  projectId: string
}
```

### Expected Resolvers types
```ts
export type Resolvers<TContext = {}, TParent = any> = {
  Query: {
    bundle: (
      parent: TParent,
      args: BundleQueryArgs,
      context: TContext,
    ) => Bundle | null
    allBundles: (
      parent: TParent,
      args: AllBundlesQueryArgs,
      context: TContext,
    ) => (Bundle | null)[]
  }
}
```

This is not perfect yet, we need to think about custom resolver, that should be optional (for `Bundle` in this example).
