### ISSUE TITLE
Unable to find field "(...)" on type "(...)"

### ISSUE THREAD

**Issue by andreyvital** [dotansimha/graphql-code-generator#3217]
Sorry for duplicating this issue! But GitHub doesn't bump as new comments are added and notifications are a little bit messed up. Take a look here: https://github.com/dotansimha/graphql-code-generator/issues/3018#issuecomment-570745493

Reproduction: https://codesandbox.io/s/ecstatic-hill-f2dbd

Sorry again! :(

/shrug

**Comment by dotansimha** [comment]
Thank @andreyvital :) We'll check that soon.

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/3243 
@andreyvital can you please try `1.10.1-alpha-3ced60a6.20`?

**Comment by dotansimha** [comment]
Fixed in 1.11.0
