### ISSUE TITLE
Documentation typescript-document-nodes error

### ISSUE THREAD

**Issue by webberwang** [dotansimha/graphql-code-generator#3218]
The `plugins` field should be `typescript-document-nodes` instead of `graphql-codegen-typescript-document-nodes`

<img width="1003" alt="TypeScript_document_nodes_·_GraphQL_Code_Generator_and_codelab-ui-nestjs____Code_UIB_codelab-ui-nestjs__-_____codegen_core_yml" src="https://user-images.githubusercontent.com/26264925/71764402-57246400-2e9c-11ea-80df-d4a06d185931.png">

**Comment by dotansimha** [comment]
Fixed in 1.11.0
