### ISSUE TITLE
Npm install fails on the second attempt

### ISSUE THREAD

**Issue by BrunoRoque06** [dotansimha/graphql-code-generator#322]
I have a project A with the following `package.json`:

```json
"devDependencies": {
  "graphql": "^0.13.2",
  "graphql-code-generator": "^0.9.1",
  "graphql-codegen-typescript-template": "^0.9.1",
  "typescript": "^2.8.3"
}
```

And then a project B that imports A:

```json
"dependencies": {
  "A": "file:./some_relative_path",
  "express": "4.16.3",
  "express-graphql": "^0.6.12",
  "graphql": "^0.13.2",
  "grpc": "^1.11.3",
  "protobufjs": "^6.8.6",
  "winston": "^2.4.2"
},
"devDependencies": {
  "@types/chai": "^4.1.2",
  "@types/express": "^4.0.37",
  "@types/express-graphql": "^0.6.1",
  "@types/graphql": "0.13.0",
  "@types/mocha": "^2.2.47",
  "@types/node": "^9.6.17",
  "@types/winston": "^2.3.9",
  "chai": "^4.1.2",
  "mocha": "^5.0.0",
  "ts-mockito": "^2.2.8",
  "ts-node": "^4.1.0",
  "typescript": "^2.8.3"
}
```

After compiling project A, if I run `npm i` in project B everything works. If I delete `node_modules` and run `npm i` again I get the following error:

```bash
npm ERR! enoent ENOENT: no such file or directory, rename '/not_relevant_path/node_modules/.staging/@sdm/A-3e0382ed/node_modules/@types/handlebars' -> 'not_relevant_path/node_modules/.staging/@types/handlebars-54d305d0'
```

To fix this I need to delete package-lock.json and run `npm i` again. Then if I delete `node_modules` and run `npm i` again we get the same error.

Node version: 10.1
Npm version: 6.0.1

Am I doing something wrong, or is this a problem? Is it related with `@types/handlebars`?

**Comment by dotansimha** [comment]
Which version of Node and Npm do you use? @BrunoRoque06

**Comment by BrunoRoque06** [comment]
I completely forgot to mention that. Added Node/Npm version to the original post. Thanks.

**Comment by BrunoRoque06** [comment]
This is a `npm` problem: https://github.com/npm/npm/issues/17444.

With `yarn` everything works good. You can close this. Thank you.
