### ISSUE TITLE
near-operation-file path resolving error

### ISSUE THREAD

**Issue by ialexi-bl** [dotansimha/graphql-code-generator#3221]
**Describe the bug**
near-operation-file throws `ENOENT` errors all the time because it is joining absolute paths instead of resolving them.

**To Reproduce**
Basically just copy the example from documentation
Codesandbox:
https://codesandbox.io/s/stupefied-nobel-722f6?fontsize=14&hidenavigation=1&theme=dark

The error shows up when doing `npm run codegen`

**Expected behavior**
Work in an intended way

**Environment:**

- OS: Ubuntu 19.10
- `@graphql-codegen/...`: 1.10.0
- NodeJS: 13.5.0

**Additional context**
The error happens when creating file in https://github.com/dotansimha/graphql-code-generator/blob/e543ab6f5e5166885faea400e66dac4da11f33a4/packages/graphql-codegen-cli/src/generate-and-save.ts#L61. When using `typescript` plugin to generate base typings, the `result.filename` contains relative path, but when using `near-operation-file`, this path is absolute. I didn't dig deeper into the code of the preset, but I suppose that changing `path.join` to `path.resolve` could help.

**Comment by ardatan** [comment]
@ialexi-bl Could you try this canary version?
`1.10.1-alpha-3fc7bb8a.6`

**Comment by ialexi-bl** [comment]
@ardatan, that seems to have worked, thanks! Waiting for `1.10.1` release

**Comment by ardatan** [comment]
Let's keep it open unfil we release 1.10.1 :)

**Comment by dotansimha** [comment]
Fixed in 1.11.0
