### ISSUE TITLE
Improve handling of `# import` comments

### ISSUE THREAD

**Issue by ialexi-bl** [dotansimha/graphql-code-generator#3222]
**Describe the bug**
I would usually like to explicitly write the dependencies for every file with `# import` comments, but now they produce a `Multiple fragments with the name(s) "..." were found` error

**To Reproduce**
https://codesandbox.io/s/hardcore-lewin-hklkj?fontsize=14&hidenavigation=1&theme=dark

For some reason it works fine, if i have only one graphql document (It works if I remove the `get-user-extra.graphql` file in the sandbox), but otherwise it throws an error. And in general the behaviour of `graphql-codegen` looks buggy in this case, sometimes it shows errors, sometimes it doesn't. Also it works fine if I comment out the usage of the fragment and leave the import comment like this:
```graphql
# import '../fragments/UserData.graphql'
query GetUser {
  user(id: 1) {
    # ...UserData
    email
  }
}
```

Also the error happens somewhere in `near-operation-file` preset, so maybe it produces the problem.

**Environment:**

- OS: Ubuntu 19.10
- `@graphql-codegen/...`: 1.10.1-alpha-fab2a7d7.6
- NodeJS: 13.5.0

**Comment by ardatan** [comment]
@ialexi-bl Thank you for reporting the issue.
Could you try with this version?
`1.10.1-alpha-26eb188e.6`

**Comment by dotansimha** [comment]
Fixed in 1.11.0

**Comment by cj** [comment]
@dotansimha I am having the exact same error using 1.11.2

**Comment by ksrb** [comment]
I verified the same issue in the sandbox:
https://codesandbox.io/s/bold-mccarthy-8gjc9

**types.ts**
![image](https://user-images.githubusercontent.com/3750409/73144857-a1919e80-405e-11ea-8c7c-a90baf015235.png)

However, if you simply remove the import form `documents.graphql` the type generation works fine ¯\_(ツ)_/¯.
