### ISSUE TITLE
Unable to find field "field" on type "Type"

### ISSUE THREAD

**Issue by ivansky** [dotansimha/graphql-code-generator#3235]
**Describe the bug**
There is an error
`Unable to find field "fieldA" on type "AType"`

```
query SomeQuery($input: SomeInput!) {
    some(input: $input) {
        a
        b {
            c {
                ...on AType {
                    d {
                        e
                        f {
                            g
                        }
                    }
                }
            }
            fieldA
            fieldB
        }
    }
}
```
If I change order, put `fieldA` and `fieldB` before `c`, error might disappear.
If before `d` there is another field the problem gone.

Pretty weird. I spent several days to investigate the problem :(

**To Reproduce**

https://github.com/ivansky/graphql-codegen-test-repo

**Expected behavior**

Success generating files.

**Environment:**

- OS: MacOS
- `@graphql-codegen/...`:  1.9.1
- NodeJS: v13.5.0

**Additional context**
If I change fields order the error disappears. Magic parsing error probably.

**Comment by ardatan** [comment]
Looks similar to #3217 . We'll take a look soon!

**Comment by ivansky** [comment]
`1.7.0` - works
`1.8.0+` - doesn't work

**Comment by ardatan** [comment]
@ivansky Did you try the latest version `1.10.0`?

**Comment by ivansky** [comment]
@ardatan Yes, even alpha from Fixes PR

**Comment by dotansimha** [comment]
It seems like the same issue in https://github.com/dotansimha/graphql-code-generator/issues/3217 . It's a bug with `isUsingTypes` that only effects developers who use `preset` feature.
I fixed it in: https://github.com/dotansimha/graphql-code-generator/pull/3243
