### ISSUE TITLE
[Typescript-Resolvers] Add custom DataSources type for apollo resolvers

### ISSUE THREAD

**Issue by victor-accarini** [dotansimha/graphql-code-generator#3239]
I'm trying to create resolvers and keep them strictly typed, but I get an error when trying to access the dataSources that are added automatically to the context by Apollo.

I would like to add an option to typescript-resolvers plugin to enhance the Resolvers types by adding a custom DataSource type.

Before:
```
export type Resolvers<ContextType = ApplicationContext> = ResolversObject<{
  Mutation: MutationResolvers<ContextType>;
  Query: QueryResolvers<ContextType>;
}>;
```

After:
```
export type ResolversContext = ApplicationContext & {
  dataSources: ApplicationDataSources
};

export type Resolvers<ContextType = ResolversContext> = ResolversObject<{
  Mutation: MutationResolvers<ContextType>;
  Query: QueryResolvers<ContextType>;
}>;
```

The `ApplicationDataSources` type would be provided by the user in the same way that the custom application context is provided.

I will try to put an PR together for this feature.

**Comment by ardatan** [comment]
I am not sure if we need a feature for that specific case. Why do you think `contextType` is not enough? `dataSources` is an object that contains some other objects. So this can be easily added into your custom `contextType`.

**Comment by victor-accarini** [comment]
Make sense I could send a context type with the dataSources added to it, I'm just worried if it could affect other types/plugins since AFAIU Apollo only add the data sources for the resolvers context.

**Comment by ardatan** [comment]
@victor-accarini It should be fine to use `contextType` because this option is only used for resolvers. So there is nothing to worry about in my opinion.

**Comment by victor-accarini** [comment]
Thks, I will close the issue
