### ISSUE TITLE
near-operation-file not using exported const gql query

### ISSUE THREAD

**Issue by axelnormand** [dotansimha/graphql-code-generator#3244]
**Describe the bug**
I'm using `near-operation-file` with  `documentMode: external` and
      `importDocumentNodeExternallyFrom: near-operation-file` so the DocumentNode is not re-created in the generated code.

The generated hook code imports `Operations` which then uses the **query name** not the **export const** name in the exported hook so is not correct.
It does works if they happen to be the same.

Is this expected behaviour?

Many thanks

**To Reproduce**

Works as both const and query called "getFoo":
```
// Component.tsx
import { useGetFoo } from './Component.generated';

export const getFoo = gql`{ query getFoo { bar } }`;

export const Component = () => {
const { data, loading } = useGetFoo();
return (...)
}

// Component.generated.ts
import * as Operations from './Component';
export function useGetFoo(
  baseOptions?: ApolloReactHooks.QueryHookOptions<
    GetFoo,
    GetFooVariables
  >
) {
  return ApolloReactHooks.useQuery<GetFoo, GetFooVariables>(
    Operations.getFoo,
    baseOptions
  );
}
```

Does not work as const called "getFooQuery" and query called "getFoo":
```
// Component.tsx
import { useGetFooQuery } from './Component.generated';

export const getFooQuery = gql`{ query getFoo { bar } }`;

export const Component = () => {
const { data, loading } = useGetFooQuery();
return (...)
}

// Component.generated.ts
import * as Operations from './Component';
export function useGetFooQuery(
  baseOptions?: ApolloReactHooks.QueryHookOptions<
    GetFooQuery,
    GetFooQueryVariables
  >
) {
  return ApolloReactHooks.useQuery<GetFooQuery, GetFooQueryVariables>(
    Operations.getFoo, // error here as getFooQuery is exported not getFoo
    baseOptions
  );
}
```

- OS: Mac
- `@graphql-codegen/*`: 1.9.1 
- NodeJS: 10.15

**Comment by dotansimha** [comment]
Closing, I answered on that issue here: https://github.com/dotansimha/graphql-code-generator/issues/4980#issuecomment-721839710
