### ISSUE TITLE
Typescript interface code for GraphQL Type that implements GraphQL interface

### ISSUE THREAD

**Issue by pchrysa** [dotansimha/graphql-code-generator#3319]
**Describe the bug**
Typescript interface code for GraphQL Type that implements GraphQL interface is ignored on generated types

**To Reproduce**
Run codegen cli

1. My GraphQL schema:

```graphql
type FeatureFilter {
    values: [ValueFilter!] 
}

interface ValueFilter {
    itemCount: Int!
}

type XValueFilter implements ValueFilter {
    id: ID!
}

type YValueFilter implements ValueFilter {
    value: String!
}
```

3. My outcome:

```
export type FeatureFilter = {
  values?: Maybe<Array<ValueFilter>>;
};

export type ValueFilter = {
  itemCount: Scalars['Int'];
};

export type XValueFilter = ApiValueFilter & {
  id: Scalars['Int'];
};

export type YValueFilter = ApiValueFilter & {
  value: Scalars['String'];
};
```

**Expected behavior**
I would expect that  `FeatureFilter` would take into account `XValueFilter & YValueFilter` otherwise I need to create a manual overwrite type.

Maybe something like:

```
export type FeatureFilter = {
  values?: Maybe<Array<XValueFilter|YValueFilter>>;
};
```

**Comment by VincentVW** [comment]
@pchrysa I'm running into the same issue. 

Can I ask why you closed this? Did you find a solution or reason this is not desired?

**Comment by pchrysa** [comment]
@VincentVW It has been a while so I do not remember many details. I closed this because I got the understanding that this is a proper outcome and that Typescript should have the feature to handle the `implements` in a type like other type languages eg Java.

In my case I handled this situation in code where I was checking the type of the incoming input whether it was of one or the other type like following:

```
interface Test {
filters: FeatureFilter[]
}

// and filters where of format

const filters: FeatureFilter[] = [
{...} as XValueFilter,
{...} as YValueFilter
]


```
