### ISSUE TITLE
Add support for overriding required field in schema as optional in type definition

### ISSUE THREAD

**Issue by kyle-villeneuve** [dotansimha/graphql-code-generator#3324]
For example if you have an edge in a type, and it's required in your graphql schema, a lot of times the parent resolver isn't handling returning that specific field and is being resolved by a child resolver. This becomes an issue because typescript obviously doesn't know that the field will be resolved elsewhere.

```graphql
type Post {
  title: String!
  author: User! # @codegen-optional
}
```

**Comment by dotansimha** [comment]
Sounds like a nice idea. PRs are welcome! 
If you wish to have it locally in your project now, you can write custom schema loader, that loads the schema from your source files, and uses `graphql-compose` to remove specific fields and manipulate the schema before it's being loaded by the codegen.

**Comment by rintaun** [comment]
I also ran into this in an Apollo Federation environment, e.g.

```graphql
type Story {
  id: ID!
  title: String!
  author: User! @provides(fields: "id")
}

extend type User {
  id: ID! @external
  stories: [Story!]!
}
```

I originally had this implemented by returning `{ id: this.userId }` from my `Story` model, and having a resolver for `User.stories`, but that caused a type error as described above.

---

With #3299 I was able to address this not with a resolver but by returning a function for `stories` (without it that patch, though, it complains the function is not applicable to `Story[]`):

```typescript
class Story implements IStory {
  // ...
  public get user(): UserType {
     return { id: this.userId, stories() { /* ... */ } }
  }
}
```

I would still prefer to have a type-level resolver, but this is an improvement at least

**Comment by LucienLee** [comment]
I got exactly the same issue as @rintaun in my Apollo Federation scenario, too.
The issue comes from the nested type in extended type could be resolved by its type resolvers, but the codegen still ask you have to resolve it in the extend type.

For example, there are user and transaction two services, and here is the code in the transaction service: 
```gql
# typedef
type Transaction {
  id: ID!
  type: String!
  amount: Int!
  account: User! @provides(fields: "id")
}

extend type User {
  id: ID! @external
  transactions: [Transaction!]!
}
``` 

```js 
// in resolvers
const resolvers = {
  Transaction: {
    async __resolveReference(ref) {
      return await transactionService.get(ref.id);
    }
    account(parent) {
      return { __typename: 'User', id: parent.id }; // <= error: type definition from codegen asks you pass transaction here too. However, it could resolve by the transaction resolver itself.  
    }
  },
  User: {
    async transactions(parent) {
      return await transactionService.get(parent.id);
    }
  }
}
```

In that case, the `transaction` in `account` resolver is not necessary.
Is any idea to solve that case, @dotansimha @kamilkisiela?
One way is let developer mark it is optional, and another way is codegen should understand that nested structure.

**Comment by rintaun** [comment]
@LucienLee there is a potential solution outlined in the [`typescript-resolvers` documentation](https://graphql-code-generator.com/docs/plugins/typescript-resolvers) (`Wrap default types with Partial`) that may work for you:

```yaml
plugins
  config:
    defaultMapper: Partial<{T}>
```

Personally, I have stopped using federation for my current project as it wasn't necessary, so I'm not sure that will work, but I have had some success with that approach in a non-federation environment.

**Comment by dotansimha** [comment]
@rintaun is right, the simplest way to do that is to use mappers and to set `defaultMapper`.
We were thinking a lot about that, and we decided that codegen will not be in charge of doing manipulations over the schema (you can do that with a custom schema loader)
