### ISSUE TITLE
Correct usage of graphql-code-generator nullable fields

### ISSUE THREAD

**Issue by cyberprodigy** [dotansimha/graphql-code-generator#3351]
**Is your feature request related to a problem? Please describe.**
Remove undefined type for nullable fields

**Describe the solution you'd like**
Guaranteed values are generated like this
```
userId: Int! --> userId: Scalars['Int']
```
Which I can essentially assign to any typescript variable of number type. That's good.

However if i have nullable field this happens
```
userId: Int --> userId?: Maybe<Scalars['Int']>
```

This I can only assign to typescript variables of type number | null | undefined , null because of Maybe operator, and undefined because of ? 

This feels wrong to type all my variables with both undefined flag and nullable, because when will it ever be undefined? Close with explanation if this is this intentional? 

**Describe alternatives you've considered**
I've looked into plugins but none seems to address the issue

**Comment by ardatan** [comment]
This is not codegen specific thing. This is how GraphQL works. If you don't define a field in GraphQL, it is considered as null. So if it is defined as null, it is considered as null again.

**Comment by cyberprodigy** [comment]
> If you don't define a field in GraphQL, it is considered as null.
Exactly. It should be null, not null or undefined

**Comment by cyberprodigy** [comment]
Also it seems to be a codegen specific issue, as codegen is the one generating types. In Graphql schema it states userId:Int . This means either it will return an Int or null, but never undefined. Then codegen should be generating appropriately 
userId: Maybe<Scalars['Int']>

**Comment by dotansimha** [comment]
As @ardatan said, it depends on how you define your GraphQL schema. 
We are using `Maybe` wrapper in order to mark fields as nullable, which means the values could be `null | undefined`. We are doing that because that's how `Maybe` is defined in `graphql.js` library, and we wish to make the generated code compatible.

This is how the resolver signature is defined:
![image](https://user-images.githubusercontent.com/3680083/72993750-96d8ce80-3dfe-11ea-91f3-5ed7a2bb5c73.png)

And `Maybe` is defined here: https://github.com/graphql/graphql-js/blob/master/src/tsutils/Maybe.d.ts 

But, as with many other plugins of the codegen, we do understand how customiation is important, so we added `maybeValue` configuration, see: https://graphql-code-generator.com/docs/plugins/typescript#maybevalue-string-default-value-t--null

**Comment by philipbulley** [comment]
@dotansimha I understand your rationale with embracing `undefined`. But then why doesn't [codegen's default value of Maybe](https://graphql-code-generator.com/docs/plugins/typescript#maybevalue-string-default-value-t--null) align with that of [graphql's tsutils](https://github.com/graphql/graphql-js/blob/master/src/tsutils/Maybe.d.ts)?

I see that adding `?` introduces `undefined` to the union in the OP's example (`userId?: Maybe<Scalars['Int']>`), subsequently bringing alignment. But codegen can't rely on `?` when given a type containing an array of Maybe values, for instance:

Schema:
```ts
input MyFilter {
  values: [String]!
}
```
Codegen:
```ts
export type MyFilter {
  values: Array<Maybe<Scalars['String']>>   // Maybe = T | null
}
```


If I later attempt to do the following:
```ts
import Maybe from 'graphql/tsutils/Maybe';
const values: Maybe<string>[] = ['hello', null, 'world', undefined];   // Maybe = T | null | undefined
const filter: MyFilter = { values };  // 💥(string | null | undefined)[] is not assignable to type (string | null)[]
```

I'll change the `maybeValue` config for now. However, would it make sense to default codegen's `Maybe` to  `T | null | undefined` and not bother with optional properties `?`.

**Comment by dotansimha** [comment]
You are right, but I suspect it might cause a breaking change. I think adding `avoidOptionals: true` might solve that for you?

**Comment by philipbulley** [comment]
`maybeValue: T | null | undefined` is enough, but `avoidOptionals: true` is the icing on the cake 😃 

```
generates:
  src/__generated__/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      maybeValue: T | null | undefined
      avoidOptionals: true
```

Thanks for such an incredible tool btw 🙏🏽
