### ISSUE TITLE
Support Apollo @export directive

### ISSUE THREAD

**Issue by bretthadley** [dotansimha/graphql-code-generator#3403]
**Is your feature request related to a problem? Please describe.**
Apollo has a feature where you can use local state variables for queries automatically
[https://www.apollographql.com/docs/react/data/local-state/#using-client-fields-as-variables](https://www.apollographql.com/docs/react/data/local-state/#using-client-fields-as-variabless)

Example
```
const query = gql`
  query currentAuthorPostCount($authorId: Int!) {
    currentAuthorId @client @export(as: "authorId")
    postCount(authorId: $authorId)
  }
`;
```

When running generate function it complains that the variable doesn't exist (because apollo will resolve the export first then inject it into the query)

**Describe the solution you'd like**
I'd like support for the export directive

**Comment by Urigo** [comment]
@bretthadley just to make sure, did you managed to make it work?
