### ISSUE TITLE
[typescript-operation] Generating separate type from query properties

### ISSUE THREAD

**Issue by jmvtrinidad** [dotansimha/graphql-code-generator#3420]
**Is your feature request related to a problem? Please describe.**

I want to use the type of property that is generated from Operation like query. Currently I'm copying all the `Pick<>` so I can use it to make it as type of a component prop in react.

**Describe the solution you'd like**

If we can have a flag that will generate a separate type from the property.
So given this query below
```graphql
query currentUser {
  me {
    id
    username
    role
    profile {
      age
    }
  }
}
```
currently it is generating the below typescript
```ts
export type CurrentUserQuery = { me: Maybe<(
  Pick<User, 'id' | 'username' | 'role'>
  & { profile: Maybe<Pick<Profile, 'age'>> }
)> };
```
After applying the flag, it should generate the below output
```ts
export type CurrentUserQueryMeProfileProp = Maybe<Pick<Profile, 'age'>>
export type CurrentUserQueryMeProp = Maybe<(
  Pick<User, 'id' | 'username' | 'role'>
  & { profile: CurrentUserQueryMeProfileProp }
)>
export type CurrentUserQuery = { me: CurrentUserQueryMeProp };
```
In this way, we are able to use the types for Component Prop

**Describe alternatives you've considered**

I've searched on how to pick the type from type but I'm not able to find any.

**Additional context**

In this way maybe it will also be readable for large query

**Comment by ardatan** [comment]
You can use fragments to have smaller types.

**Comment by dotansimha** [comment]
See: https://github.com/dotansimha/graphql-code-generator/issues/1602#issuecomment-478315105

We no longer generate intermediate types, mostly because of the difficult of maintaining it and avoid issues with types mismatch. 

As Arda said, use fragments, it's a best practice in GraphQL and not only in codegen. 
You can access inner types with `MyType['field']`.
