### ISSUE TITLE
External FragmentDoc import is not generated

### ISSUE THREAD

**Issue by Dema** [dotansimha/graphql-code-generator#3426]
**Describe the bug**
 
When I use externally defined fragment, `import for XXXFragmentDoc` statement is not being generated.
I think this is caused by refactoring in this place https://github.com/dotansimha/graphql-code-generator/blob/5b0f76a3a685dbc3702019ffc0394ffc578f9ac8/packages/presets/near-operation-file/src/fragment-resolver.ts#L114

Here https://github.com/dotansimha/graphql-code-generator/blob/5b0f76a3a685dbc3702019ffc0394ffc578f9ac8/packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts#L323 this field is tested if it is defined and when I add `console.log` it shows that `importFrom` field is completely absent from `f`. If I try to add something like 
`importFrom: "ZZZZ"`, then import appears correctly as `import {PropertyFieldsFragmentDoc } from "ZZZ"`

**To Reproduce**
https://codesandbox.io/s/infallible-leftpad-ieqgv
1) Run `yarn generate`
2) open test.generated.tsx

Line 23 has `  ${TestFragmentFragmentDoc}` but there's no relevant import of this fragment

**Expected behavior**

`import {TestFragmentFragmentDoc} from './document.generated'` to be added in generated file.

**Comment by dotansimha** [comment]
Thanks @Dema , we are tracking this in: https://github.com/dotansimha/graphql-code-generator/issues/3259
