### ISSUE TITLE
Question: Support for C# exporting

### ISSUE THREAD

**Issue by sidhants** [dotansimha/graphql-code-generator#3429]
Just came across this tool. Is there support for C# generation from GQL Schema?
Thanks.

**Comment by dotansimha** [comment]
Hi @sidhants 
Can you please share more examples and use cases? 

For servers, we can generate from the schema basic type definitions, or generate a resolvers signature (to be used with a specific implementation for c#).

**Comment by sidhants** [comment]
> Hi @sidhants
> Can you please share more examples and use cases?
> 
> For servers, we can generate from the schema basic type definitions, or generate a resolvers signature (to be used with a specific implementation for c#).

So, here is the manual code which I am hoping can be generated from the GQL schema-

-In order to send requests (via my GQL library), I am having to pass hard-coded query/mutation strings manually for every request as below:
`        private static readonly string deviceTokenAuth = @"
	        mutation deviceTokenAuth($clientID: String!) {
                deviceTokenAuth(clientID: $clientID){
		            device_code
                    user_code
                    verification_uri
                    }
	        }";`

-Then for de-serializing the response (via a JSON library), I am using C# models manually written for each response type as below:
`   [Serializable]
    public class DeviceTokenAuth
    {
        public string device_code{ get; set; };
        public string user_code{ get; set; };
        public string verification_uri{ get; set; };
    }`

This is the use case where I would like to get all the request strings and response models auto generated from schema. Is that possible?

**Comment by ardatan** [comment]
@sidhants This is a plugin idea :) and you can write a plugin for that!
https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin

**Comment by sidhants** [comment]
> @sidhants This is a plugin idea :) and you can write a plugin for that!
> https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin

@ardatan  That will be an interesting project for me and something I can look into. :)
But just want to be sure there is'nt anything existing that I can leverage before I start thinking about going that route.

**Comment by ardatan** [comment]
@sidhants AFAIK there is no plugin for C# :) You can start developing it :)

**Comment by dotansimha** [comment]
There is this one: https://github.com/netspective/graphql-codegen-csharp , but I'm not sure it's the same use-case as yours.

**Comment by dotansimha** [comment]
We can close this one, we have 2 new C# plugins.
