### ISSUE TITLE
[typescript-operations] typesSuffix option

### ISSUE THREAD

**Issue by user753** [dotansimha/graphql-code-generator#3450]
I would like to have an option to add suffix for all schema generated types
```
typesSuffix: Model
```
schema
```
type User {
  name: String
}
```
generated.ts
```
export type UserModel {
  ...
}
```

**Comment by let-aurn** [comment]
Hello @dotansimha, is this ongoing already? I can give a try otherwise..

**Comment by ardatan** [comment]
I think we are not currently working on it but PRs are welcome :)

**Comment by dotansimha** [comment]
This is available for some time now. Closing :)
