### ISSUE TITLE
Missing documentation for `typescript-generic-sdk`

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#3458]
Since `typescript-generic-sdk` got merged, we need to add docs, usage and examples. 

Related: https://github.com/dotansimha/graphql-code-generator/pull/2978

**Comment by DrChrispoper** [comment]
Can we can a minimum of documentation for this? Would be great thanks!

**Comment by dotansimha** [comment]
Done, will be available with next website deployment.
