### ISSUE TITLE
skipGraphQLImport does not work in runtime usage

### ISSUE THREAD

**Issue by GiancarlosIO** [dotansimha/graphql-code-generator#3470]
**Describe the bug**
 
Hi guys, I'm creating a node script to generate types with a dynamic config. I have several graphql files with `#import "../../c/continentFragment.graphql"`. When I try to run the `generate` function from  `@graphql-codegen/cli` I get this error:
![image](https://user-images.githubusercontent.com/17274950/74113421-fc082000-4b71-11ea-8f4b-63af87d675b0.png)

**To Reproduce**
Go to the terminal and run the `npm start` command in this codesandbox:

https://codesandbox.io/s/graphql-codegen-bug-w6694?fontsize=14&hidenavigation=1&theme=dark

1. My GraphQL schema:
https://countries.trevorblades.com/

2. My GraphQL operations:
src/a/
```graphql
#import "../b/continentFragment.graphql"

query continents {
  continents {
    ...ContinentFragment
    countries {
      code
      name
    }
  }
}

```

src/b
```graphql
fragment ContinentFragment on Continent {
  code
  name
}
```

3. My `codegen.yml` config file:
I use a dynamic config.

```js
{
    schema: "https://countries.trevorblades.com/",
    documents: ["**/*.graphql", "!**/*/continentFragment.graphql"],
    generates: {
      [process.cwd() + "/a/graphql.ts"]: {
        plugins: ["typescript"],
        skipGraphQLImport: true
      }
    }
  }
```

**Expected behavior**

It should run without errors.

**Environment:**

- OS: windows 10
- `@graphql-codegen/cli`:  1.12.2
- NodeJS: 12

**Additional context**

I'm follow the Usage (Using in Runtime) part of the docs:
https://graphql-code-generator.com/docs/getting-started/#using-in-runtime

**Comment by dotansimha** [comment]
@ardatan I think it's related to graphql-toolkit?

**Comment by ardatan** [comment]
@GiancarlosIO You're using it wrong. 
```
{
    schema: "https://countries.trevorblades.com/",
    documents: ["**/*.graphql", "!**/*/continentFragment.graphql"],
    generates: {
      [process.cwd() + "/a/graphql.ts"]: {
        plugins: ["typescript"],
        config: {
            skipGraphQLImport: true
        }
      }
    }
  }
```

**Comment by GiancarlosIO** [comment]
@ardatan  Hi, I used what you suggest me but I still get the error :thinking: 
![image](https://user-images.githubusercontent.com/17274950/74469971-a2eb0580-4e6b-11ea-8a37-29e209890393.png)

You can test it using this codesanbox (the same I use to write the issue :eye: )
https://codesandbox.io/s/graphql-codegen-bug-w6694?fontsize=14&hidenavigation=1&theme=dark

**Comment by ardatan** [comment]
@GiancarlosIO I missed something. Why did you remove fragment file?
```
{
    schema: "https://countries.trevorblades.com/",
    documents: ["**/*.graphql", "!**/*/continentFragment.graphql"],
    generates: {
      [process.cwd() + "/a/graphql.ts"]: {
        plugins: ["typescript"],
        config: {
            skipGraphQLImport: true
        }
      }
    }
  }
```
This worked for me on your codesandbox.

**Comment by GiancarlosIO** [comment]
@ardatan with "Why did you remove fragment file?" are you referring to this `"!**/*/continentFragment.graphql"`? 🤔 
I use that regex to simulate my use-case because in my real app I have something like:
```
MyAwesomeApp/
└── app
├── frontend
    └── Components/ 
        └── Card/ => here is where I want to run graphql-codegen cli
    ├── Shared/
        ├──  Fragments.graphql => Here are the graphql fragments shared over severals graphql files
        ├──  Other_graphql_files_that_are_not_in_the_same_schema_.graphql 
    └── Some_Components_With_Grahpql_files_That_Are_Not_In_The_Same_Graphgl_Schema/ 
```

So, I only want to run graphql-codegen over some files because the other files belong to other graphql schemas.

I want literally ignore the imports in the graphql. Is `skipGraphQLImport` useful for this? or skip GraphQL Import works in another way? 🤔 

Also, I see this solution by looking in the issues: 
- https://github.com/dotansimha/graphql-code-generator/issues/3325#issuecomment-577292462
- https://github.com/dotansimha/graphql-code-generator/issues/3219#issuecomment-571125944

**Comment by ardatan** [comment]
@GiancarlosIO You have that fragment in your operation file so you need that fragment's definition. The error is correct because you're ignoring fragment file. But the thing is `documents` field has nothing to do with `typescript` only. `typescript` plugin only generates types for your GraphQL types in your schema. If you want to generate typings for your clientside operations/documents, you need to use `typescript-operations`.

**Comment by GiancarlosIO** [comment]
@ardatan Oh, I see. So `skipGraphQLImport` can't solve my problem :disappointed: . I will close this issue. Thanks you! 

Just In Case. I have find a work around to solve my problem. Basically I want graphql-codegen supports mutilple schemas, thats why I created a simple package to consume a custom configuration file.
https://github.com/GiancarlosIO/react-apollo-generator

```js
// rag.config.js
module.exports = {
  schema: [
    {
      url: 'https://countries.trevorblades.com/',
      tag: 'cont',
      includes: ['../../c/continentFragment.graphql'],
      schemaTypesPath: '../../graphql-schemas/',
    },
    {
      url: 'https://graphql.anilist.co/',
      tag: 'anilist',
      schemaTypesPath: '../../graphql-schemas/',
    },
  ],
};
```

**Comment by ardatan** [comment]
@GiancarlosIO You can do this with GraphQL Codegen already;
For example
```yaml
generates:
    ../../graphql-schemas/cont-generated-types.tsx:
        schema: https://countries.trevorblades.com/
        documents: ./src/graphql/*.cont.graphql
        plugins:
             - typescript
             - typescript-react-apollo
    ../../graphql-schemas/anilist-generated-types.tsx:
        schema: ttps://graphql.anilist.co/
        documents: ./src/graphql/*.cont.graphql
        plugins:
             - typescript
             - typescript-react-apollo
```
