### ISSUE TITLE
unable to run the yarn command

### ISSUE THREAD

**Issue by kvsravindrareddy** [dotansimha/graphql-code-generator#3474]
Trying to implement the code gen with Gradle project and failing with the below.

>yarn add -D graphql @graphql-codegen/cli
Usage: yarn [options]

yarn: error: no such option: -D

**Comment by dotansimha** [comment]
@kvsravindrareddy which version of Yarn are you using?

**Comment by kvsravindrareddy** [comment]
0.32 is the yarn version

**Comment by dotansimha** [comment]
It's really outdated, can you please try to update to latest Yarn 1? It should be `1.22.0` (https://classic.yarnpkg.com/en/docs/install/)

**Comment by kvsravindrareddy** [comment]
Thank you. it works fine with the latest version.
