### ISSUE TITLE
Some type definitions are missing

### ISSUE THREAD

**Issue by icedicerice** [dotansimha/graphql-code-generator#3482]
**Describe the bug**

Some type definitions are missing when generating from multiple files (see reproduce)

**To Reproduce**

https://codesandbox.io/s/boring-bush-0o5mq

The file `codegen1.yml` has glob `./schemas/*.graphql`, some generated definitions from `./schemas/message.graphql` are missing

The file `codegen2.yml` also explicitly include `./schemas/message.graphql`, which when generated with causes some definitions from `./schemas/chat.graphql` to go missing

**Expected behavior**

I guess it should include all types

**Environment:**

- OS: Ubuntu 16.04
- `@graphql-codegen/cli`: 1.12.2
- `@graphql-codegen/typescript`: 1.12.2
- NodeJS: 13.5.0

**Comment by dotansimha** [comment]
@ardatan can you please take a look? I think it might be related to the `graphql-toolkit` loaders.

**Comment by melissag** [comment]
I've run into this problem as well, is there any update?

#### To Reproduce
https://codesandbox.io/s/1131-generates-only-first-schema-wbymw

This workspace utilizes @graphql-codegen/cli 1.13.1.

codegen.json specifies `"schema": ["schema1.graphql", "schema2.graphql"]`, but the resultant types.ts has only the types from schema1 (Query `user` and Mutation `addUser`)

In contrast:
https://codesandbox.io/s/191-generates-both-schemas-idb42

This workspace has the same exact schema files and codegen.json, but is using @graphql-codegen/cli 1.9.1.  The resultant types.ts has the types from both schema files (Queries `user`, `admin` and Mutations `addUser`, `addAdmin`)

**Comment by ardatan** [comment]
It's fixed in 1.13.2
https://codesandbox.io/s/mystifying-curie-3bdof

**Comment by melissag** [comment]
Thanks for the update @ardatan , though I'm afraid it's still broken.

The sandbox you linked actually illustrates the problem - the resulting `Mutation` type in both `types1.ts` and `types2.ts` has the mutations from `chat.graphql` and `user.graphql` (`createChat` and `signup`), but not the mutation from `message.graphql` (`sendMessage`).

**Comment by ardatan** [comment]
My bad you're right. Let's keep it open until it gets fixed.

**Comment by melissag** [comment]
:thumbsup: Thanks!

**Comment by icedicerice** [comment]
Aah, it has been 2 months now and i had already forgotten about this graphql thingy. no updates still?

**Comment by dotansimha** [comment]
It seems like an issue with the usage of `graphql-import`.
@ardatan this was not fixed by the latest version of `graphql-import` (from `graphql-tools`).

Can you please take a look?

**Comment by melissag** [comment]
Sorry for my delay, and thanks for fixing this @dotansimha !  I've encountered a new issue, which I've logged here: https://github.com/dotansimha/graphql-code-generator/issues/4303
