### ISSUE TITLE
add cli option to linearize output

### ISSUE THREAD

**Issue by aappddeevv** [dotansimha/graphql-code-generator#3497]
Currently the CLI updates the line to show some icons and other status. It would be nice to not have the lines update themselves via the terminal codes so that all messages are linearly printed and observed. This would be very helpful when writing new code generators and you need to output console messages. Currently, with the terminal lines updating, some of the output messages are truncated.

**Comment by dotansimha** [comment]
@kamilkisiela is it possible with `listr`?

**Comment by kamilkisiela** [comment]
@dotansimha  there's no-tty mode or something

**Comment by aappddeevv** [comment]
Based on the comment about listr, it looks like there is a listr-verbose-renderer that probably linearizes the output in a "logging" like format. I think a simple cli switch and the use of listr-verbose-renderer would do it. Maybe there is a way to make that pluggable :-).


https://github.com/SamVerschueren/listr-verbose-renderer

**Comment by aappddeevv** [comment]
Looked at the code now that I know what to look for. It looks like if env VERBOSE is defined, its verbose logging and not the fancy logging. I think this is sufficient for what I need so I'm claiming we can close this.
