### ISSUE TITLE
Export TS interface for graphql-request SDK

### ISSUE THREAD

**Issue by westmark** [dotansimha/graphql-code-generator#3499]
Hi!

The generated file from `typescript-graphql-request` does not currently export(or generate) the interface for the generated sdk returned by `getSDK()`, which we need in order to wrap all sdk operations with some monitoring code and at the same time maintain full typing. 

A workaround is obviously to write this interface ourselves, but it goes without saying that it would be easier to just import it from the generated file.

I've made a working example and would very much like to make a PR for this.

**Comment by dotansimha** [comment]
@westmark what do you mean? can you please explain what do you need it to generate? 
The generated code is fully-types, and it's in a `.ts` file, so you can import directly from it, and it will be fully typed (it's done with type inference).

**Comment by westmark** [comment]
Sorry I was not able to explain exactly what I meant. This is how the generated file looks now:
```
// all the type declarations emitted by typescript and typescript-operations plugins

export function getSdk(client: GraphQLClient) {
  return {
    series(variables: SeriesQueryVariables): Promise<SeriesQuery> {
      return client.request<SeriesQuery>(print(SeriesDocument), variables);
    }
  };
}
```

This is what I want:

```
// all the type declarations emitted by typescript and typescript-operations plugins

export interface SDKInterface {
  series(variables: SeriesQueryVariables): Promise<SeriesQuery>;
}
    

export function getSdk(client: GraphQLClient): SDKInterface {
  return {
    series(variables: SeriesQueryVariables): Promise<SeriesQuery> {
      return client.request<SeriesQuery>(print(SeriesDocument), variables);
    }
  };
}
```

And I want to import `SDKInterface` (or whatever it should be named) so I can wrap the sdk in a `Proxy<SDKInterface>(...)`

**Comment by dotansimha** [comment]
@westmark with an updated version of TypeScript, this should work for you: `type SDKInterface = ReturnType<typeof getSdk>`. 

See example here: http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAcwKZQMoBMDWAKCAGxlTCgC5EBDMATwEpEBvAKEXcQCd0ROlWOgxBUR5GAXgB8zRAF8ANGyHsARpTGIpMhUvayW+llFoAHVIgwARANKbEAJR58AKqdQAeY2bjAU6bDiSANwsLKCQsAiIWHAYcAC26AAWMGDIeADOuJRW1owCHFk4AHQqYiGyQA

**Comment by westmark** [comment]
Thanks! I actually googled for this but failed to find anything. This will certainly do.

**Comment by SimenB** [comment]
Didn't notice this, so opened #3704 for it. Most other types are already exported, doesn't seem like a hardship to export this as well even though it's simple to do in userland
