### ISSUE TITLE
parseEnumValues is not exported from visitor-plugin-common but probably should be

### ISSUE THREAD

**Issue by aappddeevv** [dotansimha/graphql-code-generator#3511]
If this was originally intended, can this be exported as part of the main module?

**Comment by dotansimha** [comment]
Fixed in https://github.com/dotansimha/graphql-code-generator/blob/c868a2f8b338f357027d944e173cf55c1cdb2327/packages/plugins/other/visitor-plugin-common/src/index.ts#L6-L7 

Thanks @aappddeevv . We'll release a stable version soon :)

**Comment by dotansimha** [comment]
Fixed in `v1.13.0`
