### ISSUE TITLE
Directive Resolver generation for typescript-resolvers seems to have broken in 1.12.x

### ISSUE THREAD

**Issue by SirensOfTitan** [dotansimha/graphql-code-generator#3527]
**Describe the bug**
See here for a reproduction: https://codesandbox.io/s/inspiring-nobel-7wbf9?fontsize=14&hidenavigation=1&theme=dark

... codegen is sent to console.

Up to 1.11.x, directive resolvers were successfully generated for typescript given a directive definition.  After upgrading to 1.12.x, no directive resolvers seem to be generated.  This seems to be the case at least in the cases of a directive on `OBJECT` or `FIELD_DEFINITION`, I did not test any of the others.

1. My GraphQL schema:

```graphql
  directive @testDirective on FIELD_DEFINITION
  type Query {
    foo: Boolean @testDirective
  }

  schema {
    query: Query
  }
```
**Expected behavior**
A directive-resolver is generated for `@testDirective` in the output.

**Environment:**

- OS: 
- `@graphql-codegen/1.12.2`:

**Comment by ardatan** [comment]
Could you try to parse SDL using `parse` and pass DocumentNode instead of using `printSchema` ?Because `printSchema` might remove directives.

**Comment by SirensOfTitan** [comment]
@ardatan: updated case above, still same result where types for directive aren't generated.

**Comment by ardatan** [comment]
@SirensOfTitan You say only directive resolvers are missing but I noticed that all resolver typings are missing. So I checked the configuration;
```js
const { codegen } = require("@graphql-codegen/core");
const { parse } = require("graphql");
const typescriptPlugin = require("@graphql-codegen/typescript");
const typescriptResolversPlugin = require("@graphql-codegen/typescript-resolvers");
const schema = `
  directive @testDirective on FIELD_DEFINITION
  type Query {
    foo: Boolean @testDirective
  }

  schema {
    query: Query
  }
`;

async function output() {
  const output = await codegen({
    config: [],
    filename: "foo",
    schemaAst: parse(schema),
    plugins: [
      // Each plugin should be an object
      {
        typescript: {}
      },
      {
        typescriptResolvers: {}
      }
    ],
    documents: [],
    pluginMap: {
      typescript: typescriptPlugin,
      typescriptResolvers: typescriptResolversPlugin
    }
  });
  console.log("Parsed", schema);
  // @ts-ignore
  console.log("output", output);
}

output();
```

Each plugin needs to be defined as different objects in an array like above.

**Comment by dotansimha** [comment]
Closing. @SirensOfTitan feel free to comment if it's still doesn't work.
