### ISSUE TITLE
Accept json schema files with Byte Order Mask

### ISSUE THREAD

**Issue by degroote22** [dotansimha/graphql-code-generator#353]
I'm using AWS AppSync and the files they provide me for the schema come with this [BOM](https://en.wikipedia.org/wiki/Byte_order_mark).
I guess it wouldn't be a problem [to work around this](https://github.com/npm/npm/blob/latest/lib/utils/parse-json.js).
Will submit a PR soon :)

**Comment by degroote22** [comment]
@dotansimha would you mind releasing a canary?
My workflow depends on a lot of new features and the state of the package is stable enough.
Thanks :)

**Comment by dotansimha** [comment]
Done! 0.9.2 is available now @degroote22
