### ISSUE TITLE
Emit `possibleTypes` for typescript-react-apollo

### ISSUE THREAD

**Issue by vishwam** [dotansimha/graphql-code-generator#3558]
**Is your feature request related to a problem? Please describe.**

If your schema contains an interface implemented by multiple types and a query that returns that interface, Apollo Client v3 [requires you to provide a `possibleTypes` object](https://www.apollographql.com/docs/react/v3.0-beta/data/fragments/#using-fragments-with-unions-and-interfaces) that maps interfaces to all their possible types. Example:

```graphql
query {
  all_characters {
    ... on Character {
      name
    }
    ... on Jedi {
      side
    }
    ... on Droid {
      model
    }
  }
}
```

If you don't initialize apollo client with a `possibleTypes` map, it just returns the type-specific fields (`side` and `model`) -- not `name` -- because it doesn't know the relationship between `Jedi` and `Character`. You need to do something like the following to make things work:
```js
const cache = new InMemoryCache({
  possibleTypes: {
    Character: ["Jedi", "Droid"]
  },
})
```

**Describe the solution you'd like**
Would it be possible for typescript-react-apollo plugin to emit a `possibleTypes` object that contains a map of interfaces to their implementing types?

**Describe alternatives you've considered**

**Additional context**

**Comment by vishwam** [comment]
For now, I've created my own plugin to do this:
```js
const gql = require('graphql');

module.exports = {
    plugin: (schema) => { 
        const result = {};
        const typeMap = schema.getTypeMap();
        for (const key in typeMap) {
            const type = typeMap[key];
            if (gql.isAbstractType(type)) { // i.e., union or interface
                const possibleTypes = schema.getPossibleTypes(type);
                if (possibleTypes.length !== 0) {
                    result[type.name] = possibleTypes.map(x => x.name);
                }
            }
        }

        return `export const possibleTypes = ${JSON.stringify(result)};\n`;
    },
};
```

For folks wanting to use this: just put this in a .js file and [specify the path to it in your codegen.yml file](https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin).

**Comment by ardatan** [comment]
@vishwam Thank you but we already have this kind of plugin for [Apollo's fragment matcher](https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher) ;
https://graphql-code-generator.com/docs/plugins/fragment-matcher . Let us know if you mean something else.

**Comment by vishwam** [comment]
Oh, my bad then, I’ll close this issue. I did do a search for “possibleTypes” on the site but this page didn’t show up. 

Thanks!
