### ISSUE TITLE
extend typescript-graphql-request to allow retries of requests

### ISSUE THREAD

**Issue by andycmaj** [dotansimha/graphql-code-generator#3574]
i use the typescript-graphql-request template extensively, and one thing i think it's missing is the ability to control error handling/retries for the network calls made by the SDK.
I'd like to be able to retry transient network errors with retries.

There are a few ways i can think of to implement this.

## build configuraable retries into template

add retry policies into the template and allow configuration/overriding

* `withRetryPolicy` helper
```
import polly, { AsyncRetryable } from 'polly-js';

const defaultPolicy = polly()
  .handle(err => {
    return true;
  })
  .waitAndRetry(2);

const withRetryPolicy = <T>(
  action: () => Promise<T>,
// Potentially pass more config into here or pass an override policy
) => {
  return defaultPolicy.executeForPromise(async info => {
    return await action();
  });
};

export default withRetryPolicy;
```

* codegen `visitor`
```
...
    if (this.config.retryPolicy) {
      // TODO: default config now, configurable policy later
      this._additionalImports.push(
        `import { withRetryPolicy } from 'typescript-graphql-request-with-retries';`
      );
    }
...
return `
          ${o.node.name.value}(variables${optionalVariables ? '?' : ''}: ${
            o.operationVariablesTypes
          }): Promise<${o.operationResultType}> {
            return withRetryPolicy(() => client.request<${
              o.operationResultType
            }>(${doc}, variables));
          }
`;
```

## delegate all retry logic to a generic wrapper the consumer can specify

```
export type RetryWrapper = <T>(action: () => Promise<T>) => Promise<T>;
...

          return `
          ${o.node.name.value}(variables${optionalVariables ? '?' : ''}: ${
            o.operationVariablesTypes
          }): Promise<${o.operationResultType}> {
            return withRetries(() => client.request<${
              o.operationResultType
            }>(${doc}, variables));
          }
`;
        }
      })
      .map(s => indentMultiline(s, 2));

    return `export function getSdk(client: GraphQLClient, withRetries: RetryWrapper) {
  return {
${allPossibleActions.join(',\n')}
  };
}`;
```

I think this could easily be layered onto the relatively simple existing typescript-graphql-request template and i'd be happy to submit and test.

**Comment by dotansimha** [comment]
@andycmaj This sounds like a nice idea! Do you want to create a PR for this? it could be turned on with a configuration (something like `pollyRetryPolicy: true`)

**Comment by andycmaj** [comment]
sure. I'm thinking with option 2, configuration might not even be needed. could just always make the wrapper an optional second parameter to the generated `getSdk` function.

that way we don't have to guess about best retry defaults or include any additional dependencies...

 thoughts, @dotansimha ?

**Comment by dotansimha** [comment]
Option 2 sounds good! :) 
Thanks @andycmaj

**Comment by dotansimha** [comment]
This was merged a long time ago :) we can close.
