### ISSUE TITLE
Option to flatten types in typescript-operations

### ISSUE THREAD

**Issue by standy** [dotansimha/graphql-code-generator#3575]
**Is your feature request related to a problem? Please describe.**

I'm using `typescript-operations` and when I need to use a type of some selection set, I write code like:
```ts
type Film = NonNullable<NonNullable<NonNullable<FilmsQuery['allFilms']>['films']>[0]>;
```
That hurts. But I wonder if codegen could provide that type, so It would be much easier
```ts
type Film = FilmsQuery_allFilms_films;
```

**Describe the solution you'd like**

My proposal is to generate a separate type for each selection set (like it was before v1.0.0 released as far as I know).  
The hard part is generating a unique name for each type. We could use OperationName and all field names leading to set, concatenated with a separator (like `_`), which should be configurable

Here is a repository with example https://github.com/standy/graphql-codegen-flattern-feature-request

To be short, now codegen provide this:
```ts
export type FilmsQuery = {
  __typename?: "Root";
  allFilms: Maybe<{
    __typename?: "FilmsConnection";
    films: Maybe<
      Array<
        Maybe<{
          __typename?: "Film";
          title: Maybe<string>;
          director: Maybe<string>;
        }>
      >
    >;
  }>;
};
```

I would like this: 
```ts
export type FilmsQuery_allFilms_films = {
  __typename?: "Film";
  title: Maybe<string>;
  director: Maybe<string>;
};

export type FilmsQuery_allFilms = {
  __typename?: "FilmsConnection";
  films: Maybe<Array<Maybe<FilmsQuery_allFilms_films>>>;
};

export type FilmsQuery = {
  __typename?: "Root";
  allFilms: Maybe<FilmsQuery_allFilms>;
};
```

**Additional context**
Using `@graphql-codegen/typescript-operations@1.12.2` with `preResolveTypes: true` as shown in example repo

**Comment by ardatan** [comment]
You can use GraphQL Fragments to have those types. Let me know if that works for you.

**Comment by standy** [comment]
Fragments are great, but not for this

Imagine query
```graphql
query Films {
  allFilms {
    films {
      title
      director
    }
  }
}
```
And same with fragments just for generating 2 types more:
```graphql
query FilmsWithFragment {
  allFilms {
    ...AllFilms
  }
}

fragment AllFilms on FilmsConnection {
  films {
    ...Film
  }
}

fragment Film on Film {
  title
  director
}
```
First is better, that's why I want to improve codegen instead of queries :)

**Comment by ardatan** [comment]
Codegen used to generate types recursively like that in older versions but we changed that behavior in favor of `Pick` and one single type for each operation(fragments are still seperated) because it increases complexity and causes a lot of bugs. TypeScript Compability plugin still does something similar you want, because I don't think we will have this back in the future. @dotansimha Is that right?

**Comment by dotansimha** [comment]
@ardatan is right, we do not plan to bring back the intermediate types, it caused a lot of issue and was hard to maintain. And using Fragments is a better way to write GraphQL operations, and it also simplifies the generated types (we generate a type per each operation and per each fragment). 

As @ardatan said, the `typescript-compatibility` generates intermediate types, and was intended to help developers to migrate from old codegen to the new form. You can use it to get those types.
