### ISSUE TITLE
pluckConfig option ignored?

### ISSUE THREAD

**Issue by kije** [dotansimha/graphql-code-generator#3580]
**Describe the bug**
I'm currently working on a project using gatsby together with the apollo library. There I ran into an issue when using graphql-code-generator to generate typescript type definitions, since we use apollo (with the `gql` tag) to execute queries on a different schema than with gatsby (using the `graphql` tag), and graphql-code-generator throws an error when trying to generate types from queries/fragments defined in my components since it tries to match the queries executed via apollo with the schema from gatsby.

I tried to fix this issue by providing the `pluckConfig`  to graphql-code-generator like this:

```js
{
   schema: '...',
   // ...
   pluckConfig: {
      modules: [
         {name: 'gatsby', identifier: 'graphql'}
      ],
   },
   // ...
}
```

As I understand it, this should have caused graphql-code-generator to only process queries using the `graphql` tag from gatsby, and ignoring queries using the `gql` tag from apollo. However, I still get the same error as before indicating that a query using a `gql` tag has been processed. 
I also searched the code of graphql-code-generator for usages of the `pluckConfig` option, but found no place where it actually is used (apart from some occurrences in the documentation and in unit tests)

**To Reproduce**
Create a simple project with files using multiple graphql query tags (e.g. `graphql` and `gql` for diffrent schemas). The configure graphql-code-generator to scan those files and generate typescript definition based on the queries. At this point, it should throw an error when tying to generate the type definitions (something like `AggregateError: GraphQLDocumentError: Unknown type "xyz". Did you mean "zxy", "abc", or "..."?`).

Then, add the pluckConfig option to the configuration of graphql-code-generator an try to generate the type definitions again. You should get the exact same error as before.

See also here: https://codesandbox.io/s/proud-firefly-us8l6?expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark

**Comment by ardatan** [comment]
@kije In your production, test.js is empty. Could you update it?

**Comment by dotansimha** [comment]
Hi @kije,
As @ardatan asked, can you please update the reproduction?

**Comment by dotansimha** [comment]
@kije any update?

**Comment by dotansimha** [comment]
Closing. @roborich feel free to comment if it's still relevant.
