### ISSUE TITLE
Migrate to eslint

### ISSUE THREAD

**Issue by standy** [dotansimha/graphql-code-generator#3581]
Since TSLint is deprecated in 2019, typescript-eslint should be used as a successor. And I could help with migration. I did it in several of my projects, so it would be not so hard.
Pretty sure that config based on [@typescript-eslint/recommended](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#recommended-configs) plugin will fit perfectly
What do you think?

**Comment by dotansimha** [comment]
Yeah, we should migrate the repo code to use it, and also change some of the plugins generate `eslint` ignore comments instead of `tslint`. 
Thanks @standy

**Comment by dotansimha** [comment]
Done in `v1.13.1` 🎉  thanks @standy
