### ISSUE TITLE
Run arbitary command after successful change in watch mode

### ISSUE THREAD

**Issue by karibertils** [dotansimha/graphql-code-generator#3582]
I would like to run "touch apollo.config.js" to automatically refresh the apollo plugin in vscode after each successful change when using watch mode.

This can probably be useful in many other scenarios.

**Comment by ardatan** [comment]
Does this work for you?
https://graphql-code-generator.com/docs/getting-started/lifecycle-hooks

**Comment by karibertils** [comment]
Yes works perfectly, that part of the docs completely escaped me.
