### ISSUE TITLE
Export query result subtypes for react-apollo plugin

### ISSUE THREAD

**Issue by danielhusar** [dotansimha/graphql-code-generator#3591]
Right now query result type could look like: 

```
export type GetCurrentUserTeamsQuery = { currentUser: Types.Maybe<(
    Pick<Types.User, 'id'>
    & { teams: Array<(
      Pick<Types.Team, 'id' | 'name'>
      & { sites: Array<Pick<Types.Site, 'id' | 'name'>> }
    )> }
  )> };
```

I think it would be great if we could have a possibility to export separately those subtypes like:

`Pick<Types.Team, 'id' | 'name'>` or `Pick<Types.Site, 'id' | 'name'>`.

At least I haven't found an easy way to do it.
Would you accept PR for this?

**Comment by stonexer** [comment]
You can use GraphQL fragments to get those types.

https://github.com/dotansimha/graphql-code-generator/issues/2977#issuecomment-558242152

**Comment by danielhusar** [comment]
That works, Thanks!

**Comment by dotansimha** [comment]
@danielhusar see this: https://github.com/dotansimha/graphql-code-generator/issues/3575#issuecomment-596188511
