### ISSUE TITLE
Use dependency ranges in package.json

### ISSUE THREAD

**Issue by standy** [dotansimha/graphql-code-generator#3593]
**Is your feature request related to a problem? Please describe.**

Recently, after updating the dependencies of my project, I noticed that some packages loaded many times. 
You may look at this example https://github.com/standy/starwars-graphql-example  
`tslib@1.10.0` is loaded 20 times only for 3 plugins! 

As docs for renovatebot say: libraries should use dependency ranges [https://docs.renovatebot.com/dependency-pinning/#ranges-for-libraries](https://docs.renovatebot.com/dependency-pinning/#ranges-for-libraries).
> bad idea to pin all your dependencies because it will introduce an unnecessarily narrow range (one release!) and cause most users of your package to bloat their node_modules with duplicates

**Describe the solution you'd like**
Remove renovate bot

**Comment by dotansimha** [comment]
@ardatan @kamilkisiela what do you think?

**Comment by standy** [comment]
Any answer will be appreciated 👋 

Npm packages are using semver, so unpinning is safe. Take a look into other big libraries, no one is pinning: 
https://github.com/facebook/react
https://github.com/babel/babel
https://github.com/infernojs/inferno
https://github.com/rollup/rollup
https://github.com/webpack/webpack

**Comment by kamilkisiela** [comment]
Yeah, pinning should be done only on our packages

**Comment by dotansimha** [comment]
I did it partially for now, will improve later.

**Comment by dotansimha** [comment]
Fixed in v1.13.2
