### ISSUE TITLE
[graphql-request]  Subscription support with Rx / async iterable

### ISSUE THREAD

**Issue by Tbaut** [dotansimha/graphql-code-generator#3597]
Thank you so much for your work on graphql-codegen-graphql-request. Using and loving this plugin.
I saw in the code generator documentation that this also supports subscriptions. Would you mind giving an example how it should be used?

When I use it like the queries/mutations :
```js
import { GraphQLClient } from 'graphql-request';
import { getSdk } from './generated/graphql';

const client = new GraphQLClient(graphQLEndpoint);
const mySdk = getSdk(client);
mySdk.mySubscription().then(data => console.log('Got data:', JSON.stringify(data, null, 4))).catch(e => console.log('Oops', e));
```

it gets executed and there's no observable.
What I'm looking for is an endless process, that would emit an event with the (typed) data each time there's a subscription event. I'm pretty sure it's supported, yet I don't know how to build the client.
I tried with:
```js
import { SubscriptionClient } from 'subscriptions-transport-ws';
import ws from 'ws'

const client = new SubscriptionClient(graphQLEndpoint, { reconnect: true }, ws);
``` 

But the Sdk isn't happy with it:
> Argument of type 'SubscriptionClient' is not assignable to parameter of type 'GraphQLClient'.
  Type 'SubscriptionClient' is missing the following properties from type 'GraphQLClient': options, rawRequest, setHeaders, setHeader

Any help or pointer would be greatly appreciated.

**Comment by dotansimha** [comment]
Thanks @Tbaut ! 
GraphQL Codegen supports subscriptions in some plugins, but not in `graphql-request` at the moment.
PRs are welcome ;)

**Comment by Tbaut** [comment]
Thanks for the answer, can you point me to the supported plugins? I'd take a look.

**Comment by dotansimha** [comment]
In this case, I think other plugins might not help you. Because they mostly generates types for TypeScript support (for operations or resolvers). 
In this plugin's case, it generates actual runtime code, which it missing there at the moment.

**Comment by dan-cooke** [comment]
I would be very interested in helping to move this one along - @dotansimha  do you have any pointers or updates in this area? 

I use graphql-codegen in thousands of places in my app, and I've had to circumvent it for subscriptions -which is quite annoying.

**Comment by saihaj** [comment]
Codegen should not generate any runtime code for subscriptions to work. It is very dependent on how `graphql-request` goes about supporting subscriptions and we can provide the types for it to work.
