### ISSUE TITLE
near-operation-file imports unused types

### ISSUE THREAD

**Issue by roborich** [dotansimha/graphql-code-generator#3609]
**Describe the bug**
While using the `near-operation-file` preset.  The plugin correctly imports the file from my `baseTypesPath`, however.  If a particular operation file only uses default Scalar types that can be generated without the types, it will still import the unused types from `baseTypesPath`.

**To Reproduce**
- have a tsconfig file with `noUnusedLocals` set to true
- Generate global types for your schema.
- Define and make an operations file that doesn't need any types from your schema.
- Use the `near-operation-file` preset to generate operation files with a `baseTypesPath` pointing to your global types
- the operations file will have an import for the unused global types.

**Expected behavior**
If the generated operations file from the `near-operation-file` preset doesn't use the types from `baseTypesPath` it should omit or remove them.

**Environment:**

- OS:  MacOs 10.15.3
- `@graphql-codegen/near-operation-file-preset@1.13.0`: 
- NodeJS: v12.13.0

**Comment by dotansimha** [comment]
@roborich can you please share a live reproduction in codesandbox/repo/failing test?

**Comment by dotansimha** [comment]
Closing. @roborich feel free to comment if it's still relevant.

**Comment by Vlad-Shevliakov** [comment]
Maybe I haven't figured it out yet, but I also get unnecessary types in the generated files

**Comment by ardatan** [comment]
@Vlad-Shevliakov Feel free to create a new issue with a clear reproduction as CodeSandbox/repo/failing test.

**Comment by Vlad-Shevliakov** [comment]
@ardatan  If I'm sure it's not my fault. Found this solution now: https://github.com/dotansimha/graphql-code-generator/issues/2587#issuecomment-533053903
