### ISSUE TITLE
Like typescript-document-nodes, but for schema

### ISSUE THREAD

**Issue by yoavain-sundaysky** [dotansimha/graphql-code-generator#3624]
We use a tool called [gql-generator](https://github.com/timqian/gql-generator) to generate gql files from the server's schema (rather then the client's document files).
The way this tool works is it creates a single file for every query/mutation.
The generated file contains all query fields, and its depth is configurable (i.e. if depth=2, it also adds all fields of any Type it finds in the query's top level).

The motivation to having all those gql files is API testing. It allows us to build tests that check all queries/mutations with snapshots of the results which:
1. Help us during development stage
2. Allows us to refactor the resolvers implementations with more confidence (i.e. adding data-loaders)

Would love to see a plugin that works similarly to typescript-document-nodes but on the schema:
1. Creates a single file with all exported gql objects (one per query/mutation, with matching names)
2. Have a configurable depth so we can drill down as much as we want.

**Comment by dotansimha** [comment]
Hi @yoavain-sundaysky ! 
This sounds like a cool idea, and we already have an open for this: https://github.com/dotansimha/graphql-code-generator/issues/2349 

PRs are welcome ;)
