### ISSUE TITLE
Prettier: increase readability with lower the value of printWidth

### ISSUE THREAD

**Issue by standy** [dotansimha/graphql-code-generator#3632]
Some lines in source code don't fit in my screen by far, could we change prettier's settings for `printWidth` from 250 to 120?
Prettier itself recommends 80 https://prettier.io/docs/en/options.html#print-width

I'm on 24 inches monitor fullscreen, and still, this line is killing me :) https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/operations/src/visitor.ts#L67

**Comment by pachuka** [comment]
We use our own prettier configuration in the repo combined with code-gen's hooks support:

```yml
hooks:
  afterAllFileWrite:
    - npm run prettier:fix
```

This will format the files based on our npm `prettier:fix` script.  That will then follow whatever rules you have setup for your own project.

**Comment by standy** [comment]
Thank you for the response! 
But I am telling about  `graphql-code-generator` repo. This line to be precise: https://github.com/dotansimha/graphql-code-generator/blob/master/.prettierrc#L4

I want to contribute, but reading the code with the horizontal scroll is not so easy.

**Comment by pachuka** [comment]
@standy - ah, sorry my mistake! That's what I get for skimming.

**Comment by dotansimha** [comment]
Updated in `master` to 120. Thanks @standy ! and thank you for your contributions ;)
