### ISSUE TITLE
Question: Possible to generate types for Gatsby plus Apollo Client?

### ISSUE THREAD

**Issue by devuxer** [dotansimha/graphql-code-generator#3636]
I can't figure out how to configure graphql-codegen to work in a Gatsby project that has an Apollo Client schema that I query via `gql` and a Gatsby schema that I query via `graphql`.

I'm able to get it to parse my codegen.js file, load the schemas, and load the documents successfully, but no matter what I do with `pluckConfig`, the generator chokes. It appears it's trying to process `graphql` queries with the Apollo Client schema and `gql` queries with the Gatsby schema.

Possible clue: @ardatan wrote in #3336:

> I think both gql and graphql should be default identifiers. Let's keep this open until we do these changes!

Perhaps because both of these are default identifiers, it's not possible to configure the generator to *ignore* `gql` or `graphql`, depending on the schema being processed. If this is the case, is any workaround available?

Here's my codegen.js file:

```js
require("dotenv").config({ path: ".env.development" });

const gatsbySchema = process.env.GATSBY_GRAPHQL_URL;

const hasuraSchema = {
    [process.env.HASURA_GRAPHQL_URL]: {
        headers: {
            "x-hasura-admin-secret": process.env.HASURA_ADMIN_SECRET
        }
    }
};

module.exports = {
    generates: {
        "./generated/gatsby-graphql.ts": {
            schema: gatsbySchema,
            documents: ["./src/**/*.{ts,tsx}", "./node_modules/gatsby*/!(node_modules)/**/*.js"],
            overwrite: true,
            plugins: ["typescript", "typescript-operations"],
            pluckConfig: {
                globalGqlIdentifierName: "graphql",
                modules: {
                    name: "gatsby",
                    identifier: "graphql"
                }
            }
        },
        "./generated/gatsby-graphql-introspection.json": {
            schema: gatsbySchema,
            documents: ["./src/**/*.{ts,tsx}", "./node_modules/gatsby*/!(node_modules)/**/*.js"],
            overwrite: true,
            plugins: ["introspection"],
            pluckConfig: {
                globalGqlIdentifierName: "graphql",
                modules: {
                    name: "gatsby",
                    identifier: "graphql"
                }
            }
        },
        "./generated/hasura-graphql.tsx": {
            schema: hasuraSchema,
            documents: ["./src/**/*.tsx", "./src/**/*.ts"],
            overwrite: true,
            plugins: ["typescript", "typescript-operations", "typescript-react-apollo"],
            config: {
                skipTypename: false,
                withHooks: true,
                withHOC: false,
                withComponent: false
            },
            pluckConfig: {
                globalGqlIdentifierName: "gql",
                modules: {
                    name: "@apollo/client",
                    identifier: "gql"
                }
            }
        },
        "./generated/hasura-graphql-introspection.json": {
            schema: hasuraSchema,
            documents: ["./src/**/*.tsx", "./src/**/*.ts"],
            overwrite: true,
            plugins: ["introspection"],
            pluckConfig: {
                globalGqlIdentifierName: "gql",
                modules: {
                    name: "@apollo/client",
                    identifier: "gql"
                }
            }
        }
    }
};
```

And here's the terminal log:

> > graphql-codegen --config codegen.js
>   √ Parse configuration
>   > Generate outputs
>     > Generate ./generated/gatsby-graphql.ts
>       √ Load GraphQL schemas
>       √ Load GraphQL documents
>       × Generate
>         →         at C:/myproj/web/src/pages/my-profile/index.tsx:2:5
>     > Generate ./generated/gatsby-graphql-introspection.json
>       √ Load GraphQL schemas
>       √ Load GraphQL documents
>       × Generate
>         →         at C:/myproj/web/src/pages/my-profile/index.tsx:2:5
>     > Generate ./generated/hasura-graphql.tsx
>       √ Load GraphQL schemas
>       √ Load GraphQL documents
>       × Generate
>         →         at C:/myproj/web/src/pages/team/schedule.tsx:2:5
>     > Generate ./generated/hasura-graphql-introspection.json
>       √ Load GraphQL schemas
>       √ Load GraphQL documents
>       × Generate
>         →         at C:/myproj/web/src/pages/team/schedule.tsx:2:5
> Something went wrong

Each error seems to be caused by the generator trying to analyze files/queries it should be ignoring:
- my-profile/index.tsx contains: `const query = gql`
- team/schedule.tsx contains `const query = graphql`

**Comment by devuxer** [comment]
Followup: I just tried a test where I replaced my `documents` properties in codegen.js with specific file paths instead of globs like `"./src/**/*.{ts,tsx}"`, and it worked! So, I think this adds strength to my suspicion that, at least as I have it configured, graphql-codegen scan both `gql` and `graphql` queries.

So I think my question reduces down to: how do you configure graphql-codegen to scan *either* `gql` or `graphql` but not both?

**Comment by devuxer** [comment]
Another followup: I was able to get the Apollo Client generator to stop trying to scan Gatsby queries with the following config:

```js
config: {
    gqlImport: "@apollo/client#gql"
}
```

Unfortunately, this was not a solution on the Gatsby generator side, as it still continued to try to scan Apollo Client queries (possibly because `gqlImport` is not a recognized config property if not using the `typescript-react-apollo` plugin.

**Comment by dotansimha** [comment]
It does, and at the moment you can only add more identifiers to look for using `pluckConfig`. 
@devuxer any chance you can create a reproduction in a codesandbox / repo? I will make it simpler for us reproduce and fix.

**Comment by devuxer** [comment]
@dotansimha, I haven't forgotten about this, but it would take me some time to either strip my project down to a simple repo or find a template on codesandbox that is similar enough to my setup and configure it (I need one with Gatsby, TypeScript, and Apollo). It may end up being easier for me to try to debug against the graphql-codegen source code to see if I can isolate the problem that way. I also think gatsby-plugin-graphql-codegen does what I'm trying to do, so I may be able to learn something from that source code as well. I'll keep you posted.

**Comment by devuxer** [comment]
@dotansimha,

Experimenting with the source code definitely helped. I now realize that my config was incorrect because I was trying to put `pluckConfig` *inside* of `generates`. This doesn't cause an error but has no effect on the generation process.

If I put a single `pluckConfig` at the same level as `generates`, that does have an effect, but thus far, I haven't been able to come up with a configuration that solves my problem. I thought this would work:

```js
    pluckConfig: {
        modules: [
            { name: "@apollo/client", identifier: "gql" },
            { name: "gatsby", identifier: "graphql" }
        ],
        globalGqlIdentifierName: []
    }
```

Unfortunately, this continues to try to process queries it shouldn't and errors out.

I *think* the only solution to my problem is to have two entirely separate config files and run the generator twice (once for each config file). This would allow me to specify the module that should be used for each type of query.

A possible feature that might help is the ability to specify a `pluckConfig` inside `generates` that only applies to the specific schema (which is what I was trying to do in the first place 😅).

If you have any better ideas, though I'd love to hear them. Thanks!

----

As an aside, I may have found an error in the [documentation](https://graphql-code-generator.com/docs/getting-started/codegen-config). It mentions a config property `pluckConfig.globalIdentifier`, but in the actual source code, I'm only seeing `pluckConfig.globalGqlIdentifierName`. I see a similar name difference between `magicComment` and `gqlMagicComment`.

**Comment by devuxer** [comment]
@dotansimha,

Me again 😬

I did go ahead and just divide my config into two separate files, then I chained together two calls to `generate` in my package.json:

```json
"generate": "graphql-codegen --config codegen-gatsby.js && graphql-codegen --config codegen-apollo.js"
```

And that actually worked pretty smoothly, so I'm just going to go with that unless you have a better suggestion. Sorry for all the comments, but hopefully this will help someone in the future.

**Comment by gfpacheco** [comment]
@devuxer would you mind sharing both your config files? I'm facing the same problem here, but couldn't make codegen ignore `gql` on gatsby's config yet.

**Comment by gfpacheco** [comment]
Nevermind, just made it work, I had to reset `globalGqlIdentifierName` 👍

**Comment by devuxer** [comment]
@gfpacheco,

Glad you got it working.

Let me post what I have anyway, though, just in case others come along looking for a solution.

Note that I'm developing on Windows--things may differ slightly on Mac/Linux. Also my GraphQL back-end was generated with Hasura, so some of my settings reflect that. Finally, I'm using only the environment variables in my env.development file (since I'm only doing codegen in development).

----
codegen-gatsby.js:

```js
require("dotenv").config({ path: ".env.development" });

const schema = process.env.GATSBY_GRAPHQL_URL;
const documents = ["./src/**/*.{ts,tsx}", "./.cache/fragments/*.js", "./node_modules/gatsby*/!(node_modules)/**/*.js"];

module.exports = {
    generates: {
        "./generated/graphql-gatsby.ts": {
            schema,
            documents,
            plugins: ["typescript", "typescript-operations", "typescript-react-apollo"],
            config: {
                skipTypename: true,
                namingConvention: {
                    enumValues: "keep"
                },
                withHooks: false,
                withHOC: false,
                withComponent: false
            }
        },
        "./generated/graphql-introspection-gatsby.json": {
            schema,
            documents,
            overwrite: true,
            plugins: ["introspection"]
        }
    },
    pluckConfig: {
        modules: [
            {
                name: "gatsby",
                identifier: "graphql"
            }
        ],
        globalGqlIdentifierName: []
    }
};
```
----
codegen-apollo.js:

```js
require("dotenv").config({ path: ".env.development" });

const schema = {
    [process.env.HASURA_GRAPHQL_URL]: {
        headers: {
            "x-hasura-admin-secret": process.env.HASURA_ADMIN_SECRET
        }
    }
};

const documents = ["./src/**/*.tsx", "./src/**/*.ts"];

module.exports = {
    generates: {
        "./generated/graphql-apollo.tsx": {
            schema,
            documents,
            plugins: ["typescript", "typescript-operations", "typescript-react-apollo"],
            config: {
                skipTypename: true,
                namingConvention: {
                    enumValues: "keep"
                },
                withHooks: false,
                withHOC: false,
                withComponent: false
            }
        },
        "./generated/graphql-introspection-apollo.json": {
            schema,
            documents,
            plugins: ["introspection"]
        }
    },
    pluckConfig: {
        modules: [
            {
                name: "@apollo/client",
                identifier: "gql"
            }
        ],
        globalGqlIdentifierName: []
    }
};
```
----
package.json:

```json
"scripts": {
    "generate": "graphql-codegen --config codegen-gatsby.js && graphql-codegen --config codegen-apollo.js"
}
```
