### ISSUE TITLE
link to new code generator

### ISSUE THREAD

**Issue by aappddeevv** [dotansimha/graphql-code-generator#3640]
I needed to build a codegen plugin for @graphql-codegen. Can it get linked to your site as a reference? https://github.com/aappddeevv/graphql-codegen-scala

**Comment by dotansimha** [comment]
This is awesome! Sure @aappddeevv , I added this to the docs, and we'll soon push a new version of the website. 
Thank you!

**Comment by aappddeevv** [comment]
Thanks. I suggest *not* pulling in the entire readme as it will change rapidly as I add new features. Just a light reference would be great.

**Comment by dotansimha** [comment]
@aappddeevv I added a link to the repo in the list of available plugins :)
