### ISSUE TITLE
Logo as SVG

### ISSUE THREAD

**Issue by JohannesHoppe** [dotansimha/graphql-code-generator#368]
Hi, I'm currently writing an article about Angular + Apollo + GraphQL Code Generator.
I'm wondering if there is a higher-res version of the logo available? 😄

**Comment by dotansimha** [comment]
@JohannesHoppe sounds cool! Please let me know if there is something I can do to help with your article.

The SVG is available here: http://svgur.com/s/71t

**Comment by JohannesHoppe** [comment]
That was quick! 👍
You might want to read the article, before publishing?!

**Comment by dotansimha** [comment]
@JohannesHoppe Sure! it would be great!

**Comment by JohannesHoppe** [comment]
Hello again. I wrote everything together. 

Here is the article:
https://angular.schule/blog/2018-06-apollo-graphql-code-generator
which is hosted on Github:
https://github.com/angular-schule/website-articles/blob/gh-pages/blog/2018-06-apollo-graphql-code-generator/README.md

... any kind of feedback is welcome! 👍
