### ISSUE TITLE
Support TypeScript's `import type` syntax and `importsNotUsedAsValues: error` config

### ISSUE THREAD

**Issue by SimenB** [dotansimha/graphql-code-generator#3695]
**Is your feature request related to a problem? Please describe.**

The code generated has TS type errors if `importsNotUsedAsValues: error` is used in config

**Describe the solution you'd like**

An option to use `import type` instead of `import`

**Describe alternatives you've considered**

**Additional context**

**Comment by adam-beck** [comment]
I've tried to just `"exclude"` the generated file in my tsconfig but I still get the error. Does anybody know what that's happening?

**Comment by SimenB** [comment]
With #3706, #4436, #4437, #4447, #4448 all applied locally my work project successfully compiles with `importsNotUsedAsValues: error` config 🎉 There's probably loads of other plugins/presets that we don't use that also should be updated, but it's fairly straightforward to do

**Comment by dotansimha** [comment]
Available in most plugins since `v1.17.7`. Thanks @SimenB !

**Comment by yoavain-sundaysky** [comment]
I see this one is closed, but I'm still having some problems with this one.
1. Getting this 
```import { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';```
instead of this
```import type { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';```

2. When configuring `contextType` i.e 
```contextType: ../context#ApolloContext```
I'm getting:
```import { ApolloContext } from '../context';```
Instead of:
```import type { ApolloContext } from '../context';```

3. Getting this:
```import * as ApolloReactCommon from "@apollo/react-common";```
Instead of this:
```import type { BaseMutationOptions, MutationFunction, MutationResult, QueryResult } from "@apollo/react-common";```

Should I open a new ticket?

**Comment by dotansimha** [comment]
@yoavain-sundaysky please report it in a new issue. We tried to cover all use cases, but I afraid we missed some.

**Comment by f0rmat1k** [comment]
@SimenB looks like there's still a problem. I've just added importsNotUsedAsValues to my project and got:
```
Type error: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

> 1 | import { FieldPolicy, FieldReadFunction, TypePolicies, TypePolicy } from '@apollo/client/cache';
    | ^
```

**Comment by SimenB** [comment]
https://github.com/dotansimha/graphql-code-generator/issues/3695#issuecomment-711949594
