### ISSUE TITLE
shorthand query syntax breaks types for queries

### ISSUE THREAD

**Issue by JohannesHoppe** [dotansimha/graphql-code-generator#372]
I'm using the `graphql-codegen-typescript-template`.
Having this

```typescript
query BookList {
  books {
    title
    description,
    rating
    thumbnails {
      url
    }
  }
}
```

works fine. I get a namespace `BookList` with all required types.

```typescript
export namespace BookList {
  export type Variables = {};

  export type Query = {
    ....
  };
....
}
```
But using the shorthand syntax without operation name (see [here](https://graphql.org/learn/queries/#operation-name)) breaks the code.

```typescript
export const booksQuery = gql`
{
  books {
    isbn
    title
    description,
    rating
    thumbnails {
      url
    }
  }
}
`;
```

results in:
(two empty spaces and absolutely nothing  else)

```
export namespace  {
  export type Variables = {
  }
  ...
}
```

Proposal:
Queries without a name are going to be ignored.

**Comment by dotansimha** [comment]
Yeah that's definitely a bug. will fix soon :)

**Comment by dotansimha** [comment]
@JohannesHoppe Just tested and it seems that shorthand syntax works and the document-finder find the document correctly. 
The issue here is the fact that your Query does not have a name now. 
In the past, we had a names generator for anonymous GraphQL documents, I guess that I need to add it now as well.

**Comment by dotansimha** [comment]
Fixed (and some other changes...) here: https://github.com/dotansimha/graphql-code-generator/pull/374 
Will merge soon after some tests.
