### ISSUE TITLE
Shall ResolverTypeWrapper make type partial for fetching data at field level?

### ISSUE THREAD

**Issue by themez** [dotansimha/graphql-code-generator#3724]
**Is your feature request related to a problem? Please describe.**

When I'm writing resolvers according to [PayPal's resolvers best practice](https://medium.com/paypal-engineering/graphql-resolvers-best-practices-cd36fdbcef55), I found the generated resolver type is too strict that I cannot leave off some field to fetch later, like below:
```ts
export const def = gql`
  type Query {
    event(id: String!): Event!
  }
  type Event {
    id: ID!
    title: String!
    photoUrl: String!
    attendees: [Attendee!]!
  }
`

export const resolvers: Resolvers = {
  Query: {
    event: (root, { id }) => ({ id }),
  },
  Event: {
    title: async ({ id }) => {
      const { title } = await getEvent(id)
      return title
    },
    photoUrl: async ({ id }) => {
      const { photoUrl } = await getEvent(id)
      return photoUrl
    },
    attendees: async ({id}) => 
      await getAttendeesFromEvent(id)
  }
}
```
There would be a type error on `Query.event` resolver, since I declared all fields of `Event` as required, but the resolver returns only `id` field. However, I want to resolve these fields by other field resolvers. 

**Describe the solution you'd like**

So I wonder would it be more reasonable to change `type ResolverTypeWrapper<T> = Promise<T> | T` to `type ResolverTypeWrapper<T> = Promise<Partial<T>> | Partial<T>`? Since it's a best practice to return only part of a type and leave other fields to other field resolvers?

**Describe alternatives you've considered**

I think there might be another hard way to fix this situation, it might be possible to change the way resolver is defined so type checking on all fields could be done together, but I didn't figure it out yet.

**Comment by ardatan** [comment]
That's why we have `mappers` to define your own root/parent types;
```yaml
config:
   mappers:
        Event: ./parent-types#EventParent
```
```ts
export type EventParent {
   id: string;
}
```

**Comment by themez** [comment]
Thanks @ardatan, it solves my problem.
