### ISSUE TITLE
High number of versions breaks update tools

### ISSUE THREAD

**Issue by DaSchTour** [dotansimha/graphql-code-generator#3727]
**Describe the bug**
@graphql-codegen packages let tools like [npm-check](https://www.npmjs.com/package/npm-check) oder [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) die or timeout, probably because of the gigantic number of versions.

**To Reproduce**

* Install packages from @graphql-codegen scope
* Run npm-check -u or ncu

**Expected behavior**
Checking for updates should be possible

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 12

**Additional context**

**Comment by dotansimha** [comment]
I can't really see how it's related to the codegen... releasing an alpha version per each commit is something we do for all our libraries. We mark all alpha versions as `alpha` tag in NPM. 
Releasing frequent alphas helps to to fix and verify issues, and allow consumers of this library to be able to get fixes before it's getting to a stable release. 

I think other tools might need to consider to improve their implementation...

**Comment by DaSchTour** [comment]
Well. Even `npm outdated` times out with a `@graphql-codegen/…` package regularly. So it's even npm itself that possibly can't handle this. It's just annoying I have to remove and re-add all the `@graphql-codegen/…` packages if I want to check my dependencies.

**Comment by dotansimha** [comment]
We are looking into publishing alpha version as GitHub Actions artifacts instead of NPM. This might solve this as well.
