### ISSUE TITLE
Invalid hook calls when calling a normal query with typescript + generated core used as a package

### ISSUE THREAD

**Issue by DogChef** [dotansimha/graphql-code-generator#3798]
I'm using Yarn workspaces with a core package having the generated code and a mobile package that uses it.

When trying to make a call from an imported query I get an invalid hook call. Using any other hook in that component (i.e. useState) works fine.

My package.json of my mobile package imports:
`"@workspace-library/core": "1.0.0",`

I have an index.js file at core/src that has:

```
export * from "./generated/graphql";
export { apollo, useAuth, withAuth };
```
And I import the queries like this:

```
import {
  useArticlesQuery
} from "@workspace-library/core";

const SidebarArticles: FunctionComponent<{ props: any }> = (props: any) => {
  const [test, setTest] = useState("false");
  const data = useArticlesQuery({
    fetchPolicy: "no-cache",
    notifyOnNetworkStatusChange: true,
  });

   return (
    <View>
      <Text>Heyhey</Text>
    </View>
  );
};
```
I can see the useArticlesQuery in my generated/graphql.jsx, just in case:

`export function useArticlesQuery(baseOptions) {
    return ApolloReactHooks.useQuery(ArticlesDocument, baseOptions);
}`

**Environment:**

- OS: Ubuntu
-  "@graphql-codegen/cli": "^1.13.1",
-  "@graphql-codegen/typescript": "^1.13.1",
-  "@graphql-codegen/typescript-operations": "^1.13.1",
-  "@graphql-codegen/typescript-react-apollo": "^1.13.1",
- Yarn workspaces

**Additional context**
Error in question:
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
* /home/dogchef/Development/workspace-library/packages/core/node_modules/react/cjs/react.development.js:1589:4 in resolveDispatcher
* /home/dogchef/Development/workspace-library/packages/core/node_modules/react/cjs/react.development.js:1597:29 in useContext
* http://192.168.1.2:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:181621:41 in useBaseQuery
* /home/dogchef/Development/workspace-library/packages/core/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:550:18 in useQuery
* http://192.168.1.2:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:197883:37 in useArticlesQuery
* components/SidebarArticles.tsx:10:2 in SidebarArticles

```

**Comment by dotansimha** [comment]
I'm not sure it's related directly to codegen. Maybe it's something related to your setup. 
Can you please share a reproduction in codesandbox/repo?

**Comment by dotansimha** [comment]
Closing. @DogChef feel free to comment here if it's still relevant.

**Comment by Je12emy** [comment]
I'm also facing this issue with a `shared` package which holds GraphQL types, here's a repository for reproducing it: https://github.com/Je12emy/monorepo-error

Here's a [SO thread](https://stackoverflow.com/questions/69369742/nextjs-expo-in-monorepo-invalid-hooks-call) for more context

**Comment by Je12emy** [comment]
I just tried moving condegen into each react project, this seems to have fixed some errors, but still causes issues in my React Native app, it works fine with regular hooks such as `useEffect`
