### ISSUE TITLE
Query resolver not support return empty object ({}) to implement apollo resolver chains

### ISSUE THREAD

**Issue by masihjahangiri** [dotansimha/graphql-code-generator#3805]
**Describe the bug**
For nested GraphQL separating concerns reason, I decided to implement apollo resolver chains. I return empty object in query top level resolver to apollo server resolve data in nested field.
For example:
```typescript
const resolvers: Resolvers = {
  Query: {
    staffs: (): {} => ({}), // type error, not allow return empty object
  },
 QueryStaffs: {
    me: async (_source, _args, { dataSources }: { dataSources: DatasourceObject }): Promise<QueryStaffsMeResponse> =>
      dataSources.staffAPI.staffsMe(),
  },
}
```
But type script return type error and we not allow return empty object in top level query resolver.
How to fix it and disable this error?

**Comment by dotansimha** [comment]
You can use `mappers` to replace the types expected by your generated resolvers. See: https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers---overwrite-parents-and-resolved-values 

If you plan to use empty object as a replacement for one of you types, you can do:

```yml
mappers: 
  Staff: "{}"
```

**Comment by masihjahangiri** [comment]
I don't want override parent type resolver! I want to keep QueryStaffs type and add my type as union type i.e:
```typescript
type QueryStaffs  = <auto-generate-type> | <my custom type>;
```

**Comment by ardatan** [comment]
You can add it like below then;
```
mappers: 
  Staff: "Staff | YourType"
```
