### ISSUE TITLE
Make prettier a dev dependency

### ISSUE THREAD

**Issue by P4sca1** [dotansimha/graphql-code-generator#3819]
prettier is listed as a dependency in `graphql-codegen-cli`, but should be a devDependency, because it is not required at runtime and only to format graphql-code-generator`s code itself.
Also, listing it as a dependency might cause problems when the versison differs from your local version of prettier.

**Comment by dotansimha** [comment]
You are right, done, will be shipped in next release.

**Comment by dotansimha** [comment]
Fixed in v1.13.2

**Comment by P4sca1** [comment]
@dotansimha Thank you for the quick fix. You are doing a great job with this project!

**Comment by falkenhawk** [comment]
@P4sca1 @dotansimha note: https://graphql-code-generator.com/docs/integrations/prettier will now fail unless you have added prettier to your project dependencies or have it globally installed.

**Comment by ardatan** [comment]
This part explains the integration so it shouldn't be expected that prettier is part of codegen internals.

**Comment by P4sca1** [comment]
@ardatan is right. You need to install prettier in your projects own devDependencies.
Might be worth to add a hint to the docs.
