### ISSUE TITLE
Suggestion: add Apollo Server config directive to typescript-resolvers plugin

### ISSUE THREAD

**Issue by benallfree** [dotansimha/graphql-code-generator#3828]
I am using [typescript-resolvers](https://graphql-code-generator.com/docs/plugins/typescript-resolvers) and I see #3805 talks about this a little, but I have a suggestion for better Apollo Server compatibility.

It seems both of these config directives are necessary:

```
   config
      useIndexSignature: true.           
      defaultMapper: Partial<{T}>
```
The `defaultMapper` one is needed to support [resolver chains](https://www.apollographql.com/docs/apollo-server/data/resolvers/#resolver-chains) since each resolver might only return part of the final result.

My suggestion is to add a first-class `useApolloServer: true` config setting that combines both of these. Or at least update the doc section about Apollo Server.

What do you think? Happy to send a PR for either one.

**Comment by dotansimha** [comment]
I will update the docs, thanks @benallfree :)

**Comment by dotansimha** [comment]
Done in 1.13.3
