### ISSUE TITLE
Can't use concatAST easily with strictNullChecks

### ISSUE THREAD

**Issue by brandon-leapyear** [dotansimha/graphql-code-generator#3831]
**Describe the bug**
I'm writing my own plugin in Typescript, and I'm copying what other plugins are doing:
```ts
const ast = concatAST(documents.map((v) => v.document))
```
But this breaks on the latest version of graphql-code-generator with `strictNullChecks` turned on:

```
[!] (plugin rpt2) Error: /Users/bchinn/leapyear/graphql-client/graphql-codegen-haskell/src/index.ts(24,25): semantic error TS2345: Argument of type '(DocumentNode | undefined)[]' is not assignable to parameter of type 'readonly DocumentNode[]'.
  Type 'DocumentNode | undefined' is not assignable to type 'DocumentNode'.
    Type 'undefined' is not assignable to type 'DocumentNode'.
```

i'm currently using the following workaround:
```ts
const ast = concatAST(documents.flatMap((v) => v.document ? [v.document] : []))
```
which is less than ideal.

**To Reproduce**
Write a plugin using `concatAST(documents.map((v) => v.document))` with `strictNullChecks` enabled.

**Expected behavior**
It should work, or at least be less painful than it has to be now.

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**

**Comment by dotansimha** [comment]
We are using `graphql-toolkit` to load the documents and schema, which can return `undefined` in case of a file with no found documents. 
Also, `documents` are not mandatory for plugins, that's why it could be `undefined`. So you need to check it before and filter it.
