### ISSUE TITLE
@skip, @include directives do not result in fields becoming optional in the generated code from typescript-operations

### ISSUE THREAD

**Issue by helios1138** [dotansimha/graphql-code-generator#3836]
right now, there is no difference in typescript being generated by `typescript-operations` for
```gql
query DynamicTest {
  viewer {
    id
    me
    ...userFragment
  }
}
```
and
```gql
query DynamicTest($include: Boolean!) {
  viewer {
    id
    me @include(if: $include)
    ...userFragment @include(if: $include)
  }
}
```
expected result: field `me` and all the fields from `userFragment` should become optional (`T | undefined`) in the typings, since they are no longer guaranteed to be present when query executes

**Comment by Cellule** [comment]
I have 2 fragments fetching similar fields, but one has lots of `@include(id: $somevar)`  with different vars.
I want to use typings to figure out which variables should be true to ensure the fragment with conditional results in equivalent fields being fetched.
However, because props with `@include` are not optional, I'm stick listing them all manually which can be error prone (especially when changing the fragments over time)

**Comment by Fi1osof** [comment]
This make me sad :(

@helios1138 +100

**Comment by rathpc** [comment]
Any work being actively done to address this issue?

**Comment by ardatan** [comment]
Currently no. Maybe, you can start with a PR with some initial work so we can support you.

**Comment by dannycochran** [comment]
For reference, here's a PR in the apollo codegen for this:
https://github.com/apollographql/apollo-tooling/pull/1854

**Comment by dotansimha** [comment]
There is some WIP for this issue here: https://github.com/dotansimha/graphql-code-generator/pull/5017

**Comment by dotansimha** [comment]
https://github.com/dotansimha/graphql-code-generator/pull/5017 seems to be ready, merging soon. This feature will be available in next release :) Awesome work, @gilgardosh , thank you!

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/typescript-operations@1.17.10` and `@graphql-codegen/flow-operations@1.18.3`.

Thanks @gilgardosh !

**Comment by Cellule** [comment]
I've updated all the plugins I'm using 

```json
"@graphql-codegen/cli": "^1.19.2",
"@graphql-codegen/fragment-matcher": "^2.0.0",
"@graphql-codegen/typescript": "^1.17.11",
"@graphql-codegen/typescript-operations": "^1.17.10",
"@graphql-codegen/typescript-resolvers": "^1.17.11",
```

however, `@skip` and `@include` uses `MakeOptional` which is not defined in the generated file when using 
plugins:
 - typescript
 - typescript-operations

**Comment by Cellule** [comment]
From looking at the pull request it looks like I need an updated `@graphql-codegen/typescript` is there a plan to publish the new version soon ?

**Comment by Cellule** [comment]
Also, why is `@skip` not respecting the `avoidOptionals` config ?
I would have expected to use 
```ts
type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in keyof Pick<T, K>]?: Maybe<Pick<T, K>[SubKey]> }
type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in keyof Pick<T, K>]: Maybe<Pick<T, K>[SubKey]> }=
```
and depending on the config, to use the right one
I have a lot of places where I don't actually want optional fields
