### ISSUE TITLE
Specify watch mode glob pattern when watch mode enabled with CLI flag

### ISSUE THREAD

**Issue by fabis94** [dotansimha/graphql-code-generator#3854]
**Is your feature request related to a problem? Please describe.**

Currently it looks like the `watch` glob pattern can only be specified in the codegen config, not with the cli flag. I don't want to keep the `watch` glob pattern inside the config, because I occasionally want to run codegen not in watch mode. If I would be able to specify the watch glob pattern along with the cli flag, I could leave the config as is, and only run in watch mode when needed.

**Describe the solution you'd like**
The `-w`/`--watch` flags could accept a glob pattern that specifies where to watch for changes, similarly to how it works in the config file. Example: `yarn graphql-codegen -w "src/**/**.ts"`

**Describe alternatives you've considered**
Maybe if it would be possible to extend the config files, I could have separate configs for watching/not watching.

**Additional context**

**Comment by dotansimha** [comment]
Done in https://github.com/dotansimha/graphql-code-generator/pull/3894 
@fabis94 can you please try the alpha version of that PR? It's `1.13.3-alpha-ad3daa7c.43`.

**Comment by dotansimha** [comment]
Fixed in 1.13.3
