### ISSUE TITLE
Custom template, can't be found (MODULE_NOT_FOUND). Published and linked via lerna 

### ISSUE THREAD

**Issue by appsolutegeek** [dotansimha/graphql-code-generator#389]
Hi,

I have created a custom template but when I run it, i got an npm error. I wonder if you can help ?

I have also installed the custom template via npm myself, and it works, It is published to a private repo.

I am using 

    "graphql-code-generator": "0.9.2",

This is the command I execute
```
gql-gen --schema ../../../graphql.schema.json --template @apps/graphql.codegen.typescript.template --out ./src/generated/index.ts
```

and this results is the following

```
@apps/app.graphql.model@1.0.3 graphql:generate /Users/ian/Development/Work/test-fe/packages/apps/app.graphql.model
> gql-gen --schema ../../../graphql.schema.json --template @apps/graphql.codegen.typescript.template --out ./src/generated/index.ts

11:58:07.918 - info: Loading GraphQL Introspection from file: ../../../graphql.schema.json...
11:58:07.931 - error: {"message":"Cannot find module '@apps/graphql.codegen.typescript.template'","stack":"Error: Cannot find module '@apps/graphql.codegen.typescript.template'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:497:25)\n    at Module.require (internal/modules/cjs/loader.js:626:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/Users/ian/Development/Work/test-fe/node_modules/graphql-code-generator/dist/codegen.js:199:42)\n    at step (/Users/ian/Development/Work/test-fe/node_modules/graphql-code-generator/dist/codegen.js:40:23)\n    at Object.next (/Users/ian/Development/Work/test-fe/node_modules/graphql-code-generator/dist/codegen.js:21:53)\n    at fulfilled (/Users/ian/Development/Work/test-fe/node_modules/graphql-code-generator/dist/codegen.js:12:58)\n    at process._tickCallback (internal/process/next_tick.js:178:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)","code":"MODULE_NOT_FOUND"}
```

How is it attempting to load the package ? I wrote a small node app to require the above app and everything works.

One thing to note, is that I am using lerna to manage a monorepo

Any ideas ??

**Comment by dotansimha** [comment]
@appsolutegeek Can you please share your template package?

Note that you should export `GeneratorConfig` as default export from your main package file (declared as `main` in `package.json`). See this for example: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/templates/typescript/package.json#L19

**Comment by appsolutegeek** [comment]
my template package is the typescript one then i git cloned, nothing has changed. My idea was to customize it a little late... but right now its the same

no difference, but i can put it on github if you like ?

**Comment by dotansimha** [comment]
@appsolutegeek , Sorry for the delay. And yeah it will help :) Did you make sure to run `yarn build` before publishing it?

**Comment by appsolutegeek** [comment]
Hi,

sorry, i went back to using the original package - so I am not overriding it anymore.
