### ISSUE TITLE
Schema AST doesn't merge query schemas with different names

### ISSUE THREAD

**Issue by CSFlorin** [dotansimha/graphql-code-generator#3893]
**Describe the bug**
I have two schemas with `query` being named differently in each. They are not successfully merged.

**To Reproduce**
schema1.graphql:
```
schema {
  query: Query
  mutation: Mutation
}
```

schema2.graphql:
```
schema {
  query: RootQuery
  mutation: RootMutation
}
```
codegen.json:
```
{
  "schema": ["schema1.graphql", "schema2.graphql"],
  "generates": {
    "schema.graphql": {
      "plugins": ["schema-ast"]
    }
  }
}
```

RootQuery and Query are saved as different types.

**Expected behavior**
Both should be merged into a single Query type, which is the behavior that can be seen from `mergeSchemas` in graphql-tools.

Is there a config option I'm missing? This works if I change the type of RootQuery to Query but I can't do that in all cases because I'm merging remote schemas

**Environment:**

- OS: macOS 10.14.6
- `@graphql-codegen/cli`: 1.13.2
- `@graphql-codegen/schema-ast`: 1.13.2
- NodeJS: 12.13.0

**Additional context**

**Comment by ardatan** [comment]
GraphQL Code Generator uses GraphQL Toolkit behind the scenes and schema merging tools in GraphQL Toolkit don't merge schemas in that way. Changing the names of all root Query types to Query might break internal schema such as resolvers and astNode etc. So I don't think we should change this behavior in toolkit. But that doesn't mean you cannot have this behavior in the code generator. You can use graphql-tools to merge your schemas then export that merged schema in a code file, and finally you can point to that code file in codegen.yml file. 

@dotansimha What do you think?

**Comment by dotansimha** [comment]
Thank you @ardatan . I think you are right, we can't really merge root types, because this will effect other things as well.

@CSFlorin please follow @ardatan 's instructions, and manually merge the schemas the way you wish, and export a ready `GraphQLSchema` to codegen.
