### ISSUE TITLE
[question] generate typeDefs

### ISSUE THREAD

**Issue by guiaramos** [dotansimha/graphql-code-generator#3899]
Hey guys, thanks for your amazing project.

I would like to know if there is any plugin for that generates typeDefs like:

```js
export const typeDefs = gql`
  extend type Query {
    isLoggedIn: Boolean!
    cartItems: [ID!]!
  }

  extend type Launch {
    isInCart: Boolean!
  }

  extend type Mutation {
    addOrRemoveFromCart(id: ID!): [ID!]!
  }
`;
```

I am using Apollo Local state management, therefore I want to generate the typeDefs automatically.

Thanks!

[ref document](https://www.apollographql.com/docs/tutorial/local-state/)

**Comment by guiaramos** [comment]
One solution is to use: https://github.com/ardatan/graphql-import

**Comment by marceloverdijk** [comment]
I had basically the same question.
My codegen yml looks like:
```
overwrite: true
schema: "./graphql/schema.graphql"
..
```

It would be useful to generate the typeDefs automatically based on this.

**Comment by marceloverdijk** [comment]
I used a custom plugin like:

`typescript-typedefs.js:`

```
const { printSchema } = require('graphql');

module.exports = {
    plugin: (schema, documents, config) => {
        return [
            'import gql from "graphql-tag";',
            '',
            'export const typeDefs = gql`',
            printSchema(schema),
            '`;',
            '',
        ].join('\n');
    },
};
```

and then added the custom plugin in my codegen.yml:

```
overwrite: true
schema: "./graphqls/*.graphqls"
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
      - "typescript-typedefs.js" 

```

Maybe useful to add something like this to `graphql-code-generator`  so other people can use out of the box?

**Comment by dotansimha** [comment]
Closing, as @marceloverdijk suggested a quick plugin implementation if someone needs that.

**Comment by igrek8** [comment]
Make sure to use `printSchemaWithDirectives` ⚠️ from `@graphql-toolkit/common`. Otherwise, the final schema will not have directives which may result in problems. For example, no `@auth` directives will be applied.

**Comment by ardatan** [comment]
@igrek8 That's right but `graphql-toolkit` has been deprecated in favor of `graphql-tools`. So `@graphql-tools/utils` has the same function :)

**Comment by shepherdjerred** [comment]
This is how I solved the problem using TypeScript. I also removed whitespace using `stripIgnoredCharacters ` which makes the output a little nicer.

src/typescript-typedefs.ts 
```
import { printSchemaWithDirectives } from "@graphql-tools/utils";
import { GraphQLSchema, stripIgnoredCharacters } from "graphql";

const print = (schema: string) => `
  import { gql } from "@apollo/client/core"
  export const typeDefs = gql\`${schema}\`;
`;

export const plugin = (schema: GraphQLSchema) =>
  print(stripIgnoredCharacters(printSchemaWithDirectives(schema)));
```

codegen.yml
```
generates:
  generated/index.ts:
    plugins:
      - "dist/typescript-typedefs.js"
```

**Comment by thdxr** [comment]
Is this still not supported natively? I'm surprised because it seems pretty common

**Comment by Urigo** [comment]
@thdxr up for creating a PR to add this to the options?

**Comment by elenajdanova** [comment]
I'm new to `graphql-code-generator`, so I don't really understand how [shepherdjerred](https://github.com/shepherdjerred) suggested plugin should work. Shouldn't it be written in node.js rather than typescript?

FYI, just copypasting didn't work for me

**Comment by shepherdjerred** [comment]
> I'm new to `graphql-code-generator`, so I don't really understand how [shepherdjerred](https://github.com/shepherdjerred) suggested plugin should work. Shouldn't it be written in node.js rather than typescript?
> 
> FYI, just copypasting didn't work for me

My full repo is here: https://github.com/mira-hq/model

Relevant file: https://github.com/mira-hq/model/blob/main/src/typescript-typedefs.ts

I chose to write my configuration in TypeScript and compile it to JavaScript before feeding it to graphql-code-generator.

**Comment by LarsEjaas** [comment]
> > I'm new to `graphql-code-generator`, so I don't really understand how [shepherdjerred](https://github.com/shepherdjerred) suggested plugin should work. Shouldn't it be written in node.js rather than typescript?
> > FYI, just copypasting didn't work for me
> 
> My full repo is here: https://github.com/mira-hq/model
> 
> Relevant file: https://github.com/mira-hq/model/blob/main/src/typescript-typedefs.ts
> 
> I chose to write my configuration in TypeScript and compile it to JavaScript before feeding it to graphql-code-generator.

I get a 404 when trying to access the repo or file 🤷
Would love to see an example implementation.

**Comment by shepherdjerred** [comment]
Oh so sorry! I moved that repo. Here's the link: https://github.com/shepherdjerred/archive/blob/main/mira-hq/model/src/typescript-typedefs.ts

**Comment by LarsEjaas** [comment]
> Oh so sorry! I moved that repo. Here's the link: https://github.com/shepherdjerred/archive/blob/main/mira-hq/model/src/typescript-typedefs.ts

Thanks 😃

**Comment by kozak-codes** [comment]
JS version:

```javascript
var graphqlUtils = require('@graphql-tools/utils');
var graphql = require('graphql');

// https://github.com/dotansimha/graphql-code-generator/issues/3899
var print = function (schema) {

  // add the below import if you don't have any other plugins
  // import { gql } from "@apollo/client/core"
  return '\n'
   + 'export const typeDefs = gql`' + schema.replace(/`/g, '') + '`;'
}


module.exports = {
  plugin: function(schema) {
    return print(
      graphql.stripIgnoredCharacters(
        graphqlUtils.printSchemaWithDirectives(schema)
      )
    );
  }
};
```

```yaml
...
generates:
  src/generated/graphql.generated.ts:
    plugins:
      - "src/generated/codegen-typedefs.js"
```

**Comment by lukasjapan** [comment]
I have relied on this approach for a while now and finally made a library out of it because I failed to find one.

Using this will save you an extra file in your repository and looks a bit neater in the config:

Install:

```bash
npm install --save-dev graphql-codegen-typescript-typedefs
```
```bash
yarn add --dev graphql-codegen-typescript-typedefs
```

Add the plugin to your config:

```yml
# codegen.yml
generates:
  generated-types.ts:
    schema: "**/*.graphqls"
    plugins:
      - typescript
      - typescript-typedefs
```

Get the type definitions:

```ts
import { TypeDefs } from "generated-types";
```

**Comment by Sam-Kruglov** [comment]
@lukasjapan thanks! if you have time, could you submit a PR in here instead though? 

> Closing, as [@marceloverdijk](https://github.com/marceloverdijk) suggested a quick plugin implementation if someone needs that. Feel free to create a PR!

**Comment by eddeee888** [comment]
We recommend using Server Preset for a managed setup, including generated typeDefs feature requested in this issue. 🙂

More details about the generated files in the [Server Preset guide](https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga-with-server-preset#generate-files)

**Comment by Sam-Kruglov** [comment]
@eddeee888 but I'm not hosting graphql, I'm only consuming it, so I'm using client preset.

I need the typedefs for writing ui tests with https://github.com/apollographql/graphql-testing-library
