### ISSUE TITLE
Collision with enum names when the enum values are different based on number of underscores in them.

### ISSUE THREAD

**Issue by quietgopher** [dotansimha/graphql-code-generator#3910]
**Describe the bug**

My code has a timezone enum values where the number of underscores indicates a different character.

// Time Zones regions from
// https://docs.aws.amazon.com/redshift/latest/dg/CONVERT_TIMEZONE.html
// with the following substitutions for Javascript syntax compatibility:
// _ -> _ [1 underscore as itself]
// / -> __ [slash as 2 underscores]
// - -> ___ [dash as 3 underscores]
// + -> ____ [plus as 4 underscores]

My Timezone enum looks like:

```
enum TimeZone {
  Africa__Abidjan
...

  Etc__GMT
  Etc__GMT____0
  Etc__GMT____1
...
  Etc__GMT0
  Etc__GMT___0
  Etc__GMT___1
...
```

When I run apollo-code-generator on this, these enums collide at EtcGmt_0, etc.

**To Reproduce**

Create a GraphQL schema with with an enum like:

```
enum TimeZone {
  Etc__GMT____0
  Etc__GMT___0
}
```

See if there are collisions.

I tried creating a sandbox but I can't figure out how to re-run generate.

https://codesandbox.io/s/cranky-tereshkova-rx4qk?file=/schema.graphql

1. My GraphQL schema:

See the sandbox link.

```graphql
enum TimeZone {
  Etc__GMT____0
  Etc__GMT___0
}
```

2. My GraphQL operations:

```graphql
```

3. My `codegen.yml` config file:

```yml
```

**Expected behavior**
I figured the underscores would stay in the enum names.  I think it's fine to remove the underscores but now I have a collision.  I tried to find the code that does this formatting but could not.

**Environment:**

- OS: Mac v10.15.2
- `@graphql-codegen/...`: I have a few downloaded.  Mostly related to typescript.
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - "typescript-graphql-files-modules" 
- NodeJS: v13.11.0

**Additional context**

**Comment by dotansimha** [comment]
We discussed it a lot here. Feel free to search the repo.  Codegen has naming convensions to make sure it's generating code that can compile with TypeScript compiler.

If you wish to cancel that behaviour for your `enumValues`, just do:

```
config:
  namingConvention:
    enumValues: keep
```
