### ISSUE TITLE
Enhancement: Output nested types in query operations (typescript-operations)

### ISSUE THREAD

**Issue by benallfree** [dotansimha/graphql-code-generator#3918]
I'm not sure if this is a good idea or not, but here is the situation.

Given this schema,

```gql
type Order {
  trackingNumber: String!
  shipmentNotes: String!
}

type Customer {
  name: String!
  orders: [Order!]!
}

type Query {
  customers: [Customer!]!
}
```

...and this query,

```gql
query Customers {
  customers {
    name
    orders {
      trackingNumber
    }
  }
}
```

`typescript-operations` will output something like:

```gql
export type CustomersQueryResult = {
  __typename?: 'Query'
  customers: Array<{
    __typename?: 'Customer'
    name: string
    orders: Array<{ __typename?: 'Order'; trackingNumber: string }>
  }>
}
```

This is problematic in React because I don't have a type definition for an Order in this particular query result. I can copy/paste, like this:

```jsx
const Order : FC<{...copy & paste??...}> = ({trackingNumber})=> {
   return <div>{trackingNumber}
}
```

Or I can use the `Order` type generated by the `typescript` base plugin, but I have to omit the types that may not be provided by a given query.

```jsx
const Order : FC<Omit<Order, "shipmentNotes">> = ({trackingNumber})=> {
   return <div>{trackingNumber}
}
```

Or I could just `Partial<Order>` everything, but then I've partly defeated the purpose of type checking.

So my idea is this... Rather `Array<{ __typename?: 'Order'; trackingNumber: string }>`, I would like it to generate a separate subtype. Something like this:

```gql
export type CustomersQuery = {
  __typename?: 'Query'
  customers: Array<{
    __typename?: 'Customer'
    name: string
    orders: Array<CustomersQuery_Order>
  }>
}

export type CustomersQuery_Order = {
  __typename?: 'Order'; 
  trackingNumber: string 
}
```

Then I could do 

```jsx
const Order : FC<CustomersQuery_Order> = ({trackingNumber})=> {
   return <div>{trackingNumber}
}
```

That feels pretty good, albeit the props type definition is coming from a specific query, which isn't great. Thoughts?

**Comment by dotansimha** [comment]
We had this in the past, and it was removed. It's hard to maintain, creates messy output, and causes bugs. See: https://github.com/dotansimha/graphql-code-generator/issues/1602#issuecomment-478315105

It's TypeScript, if you wish to have a type for that nested type, you can do:

```
export type CustomersQuery = {
  __typename?: 'Query'
  customers: Array<{
    __typename?: 'Customer'
    name: string
    orders: Array<{
      __typename?: 'Order'; 
      trackingNumber: string 
     }>
  }>
}

export type CustomersQuery_Order = CustomersQuery['customers'][0]['orders'][0];
```

**Comment by benallfree** [comment]
Thank you @dotansimha
