### ISSUE TITLE
Generate .d.ts files next to query.graphql file

### ISSUE THREAD

**Issue by mikefisher84** [dotansimha/graphql-code-generator#3921]
Hi all, I'm using [graphql-fixtures](https://www.npmjs.com/package/graphql-fixtures) to generate typed fixture data for my unit tests. However this tool expects typed queries to be passed into it. The suggested approach is to use `graphql-typescript-definitions` to generate typescript types from your schema. However for multiple reasons I would prefer to use `graphql-code-generator` to create my types. 

**Describe the solution you'd like**
From my understanding it currently isn't possible to generate typescript `.d.ts` files next to their specific queries. I would love to see a feature like this implemented as `graphlql-fixtures` seems like a nice tool for generating fixture data. 
Ideally my file structure would look like this:
```
src:
   MyComponent:
     MyComponent.tsx
     MyComponent.test.tsx
     MyComponentQuery.graphql
     MyComponentQuery.d.ts
```
**Describe alternatives you've considered**
I've considered not using `graphql-code-generator` but I would like to avoid this. 

**Additional context**
If there is an alternative approach I'd be happy to explore that as well. 
Thanks!

**Comment by dotansimha** [comment]
@mikefisher84 I think you can either use `near-operation-file` preset for that, or just use `graphql-let` (https://github.com/piglovesyou/graphql-let)
