### ISSUE TITLE
Splited fields in resolvers

### ISSUE THREAD

**Issue by JanKaczmarkiewicz** [dotansimha/graphql-code-generator#3933]
Hi,
I'm using the generator to create a typing for resolvers. 
I am struggling with types that resolvers should return.
Here is an example of what I am trying to achieve: 
repo: https://github.com/JanKaczmarkiewicz/gql-generator-ts-mongo-issue
I want to have custom resolvers for fields, and typescript doesn't like it. 

This is my schema definition:
```
type House @entity {
  id: String! @id
  number: String! @column
  street: Street! @column
}

type Street @entity {
  id: String! @id
  name: String! @column
  houses: [House]!
}

type Mutation {
  addHouse(input: AddHouseInput!): House!
  addStreet(input: AddStreetInput!): Street!
}

type Query {
  house(id: String!): House
  street(id: String!): Street
}
``` 
And thats how i wrote resolvers: 
```
const resolvers: Resolvers = {
  Mutation: {
    addHouse: (_, { input }) => <any>new House(input).save(),
    addStreet: (_, { input }) => <any>new Street(input).save(),
  },
  Street: {
    id: (street) => ((street as any)._id as any) + "",
    houses: async (street) =>
      <any>House.find({ street: (street as any)._id as any }),
  },
  House: {
    id: (house) => ((house as any)._id as any) + "",
    street: async (house) => <any>Street.findById(house.street),
  },
  Query: {
    street: (_, { id }) => <any>Street.findById(id),
  },
};
```

I want e.g in my addHouse resolver return object in shape: 
```
type House = {
  _id: ObjectID,
  number: string,
  street: ObjectID,
};
```
current:  
```
export type House = {
   __typename?: 'House';
  id: Scalars['String'];
  number: Scalars['String'];
  street: Street;
};
```
And then graphql server will take care of unresolved fields such as street and id (using resolvers.House.street, resolvers.House.id).
But how to define it in my schema? 

**Possible solution**
Add directive @customResolver like that:
```
type House @entity {
  id: String! @id @customResolver
  number: String! @column
  street: Street! @column @customResolver
}
```
and it will be known that the "street" field should be resolved by `resolvers.House.street`
and analogously id by `resolvers.House.id`.

And it will generate the following type (for all resolver that sould return a House): 
```
type House = {
  _id: ObjectID,
  number: string,
  street: ObjectID,
};
```

This feature will help me a lot, and I think it helpful for others too.
Maybe is some workaround, I haven't spotted is yet. If someone has a similar approach I would love to see her/his examples <3.

This is the first issue I ever did. If something is unclear or inconsistent I will try to explain better. 
full sample code in [repo](https://github.com/JanKaczmarkiewicz/gql-generator-ts-mongo-issue)

**Comment by ardatan** [comment]
We already have this kind of feature. Check the docs;
https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers---overwrite-parents-and-resolved-values

**Comment by JanKaczmarkiewicz** [comment]
That's exactly what I needed. Thanks for the reference. I really love this project!
