### ISSUE TITLE
Support schema/operations transformations (like in GraphQL-Mesh)

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#3939]
GraphQL Mesh (https://github.com/Urigo/graphql-mesh) has built-in transforms, and I think supporting those in codegen might help us to allow developers to filter/manage their schema easily. 

Doing that might help with issues like that: https://github.com/dotansimha/graphql-code-generator/pull/3886 

So it will make it easier to do custom logic over the schema easily.

```
schema:
  - my-schema.ts:
      transforms:
         - ./custom-transform.js

documents:
  - "./**/*.graphql":
     transforms:
        - strip-apollo-export-directive

``

**Comment by dotansimha** [comment]
We decided that GraphQL Codegen will no do any transformations internally. 

If you wish to transform of modify your schema, you should be able to do that with a [custom schema loader](https://graphql-code-generator.com/docs/getting-started/schema-field#custom-schema-loader).

**Comment by ToledoNicola** [comment]
> We decided that GraphQL Codegen will no do any transformations internally.
> 
> If you wish to transform of modify your schema, you should be able to do that with a [custom schema loader](https://graphql-code-generator.com/docs/getting-started/schema-field#custom-schema-loader).

hi, is it possible to have a detailed example of how to create a custom shema to support the @export directive?
thank you
this is my query
`query Dashboard() {
  currentUserId @client @export(as: "userId")
  getPatient(id: $userId) {
    id
    name
    doctor {
      id
      name
      surname
      available
    }
    nextSessions {
      id
      day
      hour
      paid
      dayOfWeek
    }
  }
}
`

**Comment by Urigo** [comment]
@ToledoNicola could you create an example where you try to do it and fail, and open a new issue so we could jump in and help?
