### ISSUE TITLE
Error when generating schema from typescript file export

### ISSUE THREAD

**Issue by SkaterDad** [dotansimha/graphql-code-generator#394]
This project looks really great so far!  👍 

When I try to generate types from a Typescript file, I'm getting errors.  I thought I set this up similar to what I saw in your Youtube video, so I'm unsure of why this doesn't work.

Do you have any tips or tricks?  I'd rather generate from source files than spin up the server each time.

package.json script:
```json
{
  "generate":  "gql-gen --require ts-node/register --schema ./src/schema.ts --template typescript --out ./src"
}
```
error message:
```sh
{"message":"Exported schema must be of type GraphQLSchema, text, AST, or introspection JSON."
```

./src/schema.ts
```typescript
import * as base from './modules/_base/schema'
import * as users from './modules/users/schema'
import * as events from './modules/events/schema'
import { makeExecutableSchema } from 'graphql-tools'
import { GraphQLSchema } from 'graphql'

// example:  base.schema = 
//export const schema = gql`
//  type Query {
//    hello: String
//  }
//  type Mutation {
//    _: Boolean
//  }
//`
export const typeDefs = [base.schema, users.schema, events.schema]

export const resolvers = [base.resolvers, users.resolvers, events.resolvers]

export const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
}) as GraphQLSchema

```

**Comment by SkaterDad** [comment]
For whatever reason, the code below works, so this must be related to the output of `makeExecutableSchema`.

```typescript
import * as base from './modules/_base/schema'
import { GraphQLSchema } from 'graphql'

export const schema = base.schema
```

**Comment by kamilkisiela** [comment]
@SkaterDad 

```ts
export default schema
```

**Comment by SkaterDad** [comment]
I tried that as well, with the same error.  Maybe I need to have my tsconfig emit type declarations? Will try that later and report back.

**Comment by dotansimha** [comment]
@SkaterDad any update? 
If that didn't helped, can you please share a reproduction?

**Comment by degroote22** [comment]
I guess that you're trying to pass `graphql-code-generator` the **executable**Schema while you should pass the **schema**.
I've never had issues using the same setup as you but I'd export just a **string** from my script.

**Comment by SkaterDad** [comment]
I haven't had any more time to experiment with this generator, so I'll close the issue.  The tool worked well when you pass it a plain schema, so that will be good enough for me if I come back to it in the future.

**Comment by kfrajtak** [comment]
I got this error when `.graphql` files contained MongoDB related directives like `@entity` or `@column`. After removing those the error went away.
