### ISSUE TITLE
Please add a configuration option to the apollo-angular plugin to allow for usage of custom apollo client 

### ISSUE THREAD

**Issue by cjohn001** [dotansimha/graphql-code-generator#3944]
Hello together,
I am currently patching the apollo-angular library to allow for usage of a patched apollo client with offline support (offix).  I would like to use the apollo-angular plugin of the graphql-code-generator as this is an amazing tool!

Of course I could add an additional plugin to the graphql-code-generator, but the code would be identical except for a single line

The line of code is line 80 in:

graphql-code-generator/packages/plugins/typescript/apollo-angular/src/visitor.ts /

const imports = [`import { Injectable } from '@angular/core';`, `import * as Apollo from 'apollo-angular';`];

for the second import I would require a different import package,  'apollo-angular' would need to become something like 'offix-angular'. 
Could you maybe add a configuration option to the plugin in order to set the package name via a variable? This would save us from code duplication, as the other option would be to provide an additional plugin. Thanks for your help!

**Comment by dotansimha** [comment]
Hi @cjohn001 ! 

I added this in: https://github.com/dotansimha/graphql-code-generator/pull/3952 

Can you please try the alpha version `1.13.5-alpha-3c19cc8e.0`? You should be able to override that with:

```yaml
config:
  apolloAngularPackage: my-package
```

**Comment by dotansimha** [comment]
Available in v1.13.5
