### ISSUE TITLE
Input type are missing when use preResolveTypes + onlyOperationTypes

### ISSUE THREAD

**Issue by xiaoyu-tamu** [dotansimha/graphql-code-generator#3956]
**Describe the bug**
 
1. Input type are missing when use preResolveTypes + onlyOperationTypes
<img width="640" alt="image" src="https://user-images.githubusercontent.com/33362998/80744787-d4778280-8ae4-11ea-86fd-b66b9c6479d9.png">

2. Input type are wrong when use preResolveTypes + onlyOperationTypes + plugin: near-operation-file
<img width="626" alt="image" src="https://user-images.githubusercontent.com/33362998/80744873-f4a74180-8ae4-11ea-88a3-a59db33cb3d6.png">

**To Reproduce**
See this repo
https://github.com/xiaoyu-tamu/graphql-generate-bug-repo

Also, here is the CSB if someone need it, but I have no idea why generated files are not show up in file tree.
https://codesandbox.io/s/romantic-wildflower-4i9ij

**Expected behavior**

No type error

**Environment:**

- OS: MacOS
- NodeJS: 12
- "@graphql-codegen/cli": "1.13.4",
- "@graphql-codegen/introspection": "1.13.4",
- "@graphql-codegen/near-operation-file-preset": "1.13.4",
- "@graphql-codegen/typescript": "1.13.4",
- "@graphql-codegen/typescript-operations": "1.13.4",
- "@graphql-codegen/typescript-react-apollo": "1.13.4",
- "graphql": "15.0.0"

**Additional context**

**Comment by dotansimha** [comment]
Fixed in v1.13.5
