### ISSUE TITLE
TS Types do not agree with GQL Binding types

### ISSUE THREAD

**Issue by jasonkuhrt** [dotansimha/graphql-code-generator#396]
Gen result from same schema:

GQL bindings:
```ts
{
  where?: UserWhereInput
  orderBy?: UserOrderByInput
  skip?: Int
  after?: String
  before?: String
  first?: Int
  last?: Int
}
```

GQL Code Generator:
```ts
export interface UsersQueryArgs {
  where?: UserWhereInput | null
  orderBy?: UserOrderByInput | null
  skip?: number | null
  after?: string | null
  before?: string | null
  first?: number | null
  last?: number | null
}
```

This makes resolvers harder to type because of the type mismatch (the following would type error):

```ts
    users: (_, args: Schema.UsersQueryArgs, ctx, info) => {
      return ctx.core.query.users(args, info)
    },
```

**Comment by dotansimha** [comment]
Which error do you get? can you please elaborate?  @jasonkuhrt

**Comment by jasonkuhrt** [comment]
`  after?: String` vs `after?: string | null`. If I run into the exact error TS produces for this again I'll post it.

I'm actually not 100% sure which is the better type. It seems correct to me that the caller might pass in `null` or `nothing`. @timsuchanek do you have insight about the design decision taken in [`graphql-bindings`](https://github.com/graphql-binding/graphql-binding)?

**Comment by ardatan** [comment]
Could you remove question mark in your typedefs?
```gql
{
  where: UserWhereInput
  orderBy: UserOrderByInput
  skip: Int
  after: String
  before: String
  first: Int
  last: Int
}
```

**Comment by dotansimha** [comment]
@jasonkuhrt can you please try what @ardatan suggested?

**Comment by jasonkuhrt** [comment]
haven't been around this for a while, will do next time I am. Note there has been a new major version of GQL bindings released, of TS, so need to revisit more deeply.
