### ISSUE TITLE
Module not found: Can't resolve 'apollo-client'

### ISSUE THREAD

**Issue by rhlsthrm** [dotansimha/graphql-code-generator#3966]
**Describe the bug**
Error when starting React app with generated code:

```
Failed to compile.

./node_modules/@apollo/react-hooks/lib/react-hooks.esm.js
Module not found: Can't resolve 'apollo-client' in '/Users/rahul/dev/projects/axcio/packages/frontend-react/node_modules/@apollo/react-hooks/lib'
```

**To Reproduce**

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
I can fix this myself by editing the generated code from:
```
import * as ApolloReactHooks from '@apollo/react-hooks';
``` 

to:

```
import * as ApolloReactHooks from '@apollo/client';
```

See: https://github.com/apollographql/apollo-client/issues/5808

**Comment by Gonozal** [comment]
While there does not seem to be a version that supports the apollo-client 3.0 beta, you can adjust the import statements through config parameters (there's a suprising amount of configuration possible!):

codegen.yml:

```
generates:
  src/:
    config:
      apolloReactHooksImportFrom: "@apollo/client"
      apolloReactCommonImportFrom: "@apollo/client"
```

**Comment by dotansimha** [comment]
As @Gonozal said, you can easily customize it. Also you should set `reactApolloVersion: 3` if you use v3 of Apollo.

**Comment by miller-productions** [comment]
> As @Gonozal said, you can easily customize it. Also you should set `reactApolloVersion: 3` if you use v3 of Apollo. (https://graphql-code-generator.com/docs/plugins/typescript-react-apollo)

See here... https://graphql-code-generator.com/docs/generated-config/typescript-react-apollo#reactapolloversion-2--3-default-value-2
