### ISSUE TITLE
Allow multiple templates

### ISSUE THREAD

**Issue by degroote22** [dotansimha/graphql-code-generator#401]
I'm writing a template that generates bindings for react-apollo, and I'm using the types already generated by the typescript template.

Right now I'm forking `graphql-codegen-typescript-template` but I wouldn't like to maintain the fork.
The best approach would be to be able to run more than one template. 
It wouldn't touch any of the current templates implementation and they could be easily extended.
It's one CLI config away, --template would accept a string or a list of strings.

It would also mean we should forever make outFile not configurable or develop an inter dependency mechanism.

What are your thoughts?

**Comment by dotansimha** [comment]
Sounds good. I think it's minor change to add it. Any chance you would like to add this feature and create a PR? @degroote22

**Comment by degroote22** [comment]
For sure, I'll do it.
It may take a couple of days because I'm a little busy but I will do it. :)

**Comment by degroote22** [comment]
I created a prototype but I can't figure out how to keep outfiles configurable.
I can't think of a clean api for this. I guess that it may be better to skip this idea.
The same functionality can be achived in "userland" by running the generator twice.
