### ISSUE TITLE
Subscriptions resolvers should be created with resolve & subscribe methods

### ISSUE THREAD

**Issue by tomasAlabes** [dotansimha/graphql-code-generator#403]
Hi, first thanks for your work!

I've been using the resolvers types but I found a mismatch in the subscription ones. It's done correctly by https://github.com/dangcuuson/graphql-schema-typescript v1.2.0: _Field resolvers under subscriptions are being generated with resolve and subscribe method_

Subscriptions have different resolvers compared to Queries/Mutations.

Thanks!

**Comment by kamilkisiela** [comment]
I will try to work on it in next few days
