### ISSUE TITLE
Drift chat button covers up menu button on mobile

### ISSUE THREAD

**Issue by danielrearden** [dotansimha/graphql-code-generator#4035]
**Describe the bug**
The Drift chat button covers up the menu button when viewing the docs on a mobile browser, making it almost impossible to open the menu. This makes the docs virtually inaccessible unless you use the Previous/Next navigation on the bottom.

**To Reproduce**
Navigate to the docs in a mobile browser.

<img width="358" alt="Screen Shot 2020-05-16 at 4 49 17 PM" src="https://user-images.githubusercontent.com/18018864/82129986-3ac2fd00-9795-11ea-8f4f-8d0106be491d.png">

**Expected behavior**
The menu button should be accessible to enable easy navigation when viewing the site on a mobile browser. It would be enough to have the option to hide the chat button. Otherwise, one button or the other could be moved to another corner of the screen.

**Environment:**

- OS: Chrome on Android  81.0.4044.138

**Comment by dotansimha** [comment]
Fixed :) Thanks @danielrearden !
