### ISSUE TITLE
JSDoc: Failed to transform Input Types

### ISSUE THREAD

**Issue by reicheltp** [dotansimha/graphql-code-generator#4108]
**Describe the bug**
Input types are not generated correctly with Plugin JSDoc. Instead of a type definition it just prints `[object Object]`.

**To Reproduce**

1. My GraphQL schema:

```graphql
input DemoInput {
  test: String!
}

```

2. My `codegen.yml` config file:

```yml
generates:
  schema.js:
    plugins:
      - jsdoc
```

3. False Result

```js
///schema.js

[object Object]
```

**Expected behavior**

```js
///schema.js
/**
 * @typedef {Object} DemoInput
 * @property {String} test
 */
```

**Environment:**

Used: https://graphql-code-generator.com/

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**

**Comment by ardatan** [comment]
Could you create a reproduction using the template below?
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template

**Comment by reicheltp** [comment]
@ardatan Done: https://codesandbox.io/s/distracted-curie-m8cr0?file=/schema.js

See `schema.js` for wrong output.

**Comment by CarloPalinckx** [comment]
@dotansimha pretty sure this can be closed ✌️
