### ISSUE TITLE
Add @optional directive to generate typescript optionals when needed (partial updates)

### ISSUE THREAD

**Issue by lanwin** [dotansimha/graphql-code-generator#4118]
We have a complex input object where we want to support partial updates (send only a few properties instead of the full obj). Our server supports this fine, but the type generation did not. 

**Describe the solution you'd like**

So I would like to suggest to allow an @optional directive and make Codegen generate the field as optional then. This is simple and would allow to generate optionals only when needed.

**Describe alternatives you've considered**

I could do avoidOptionals:false but that would generate wrong types for the rest of the schema. I also could do avoidOptionals only for input objects. But in our case not all Input objects would support partial updates. But the generated types look like it does.

**Comment by dotansimha** [comment]
Hi @lanwin , thank you for opening this issue. 

We decided that codegen input will be a ready to use schema, and to avoid transformations done specifically by codegen. 

If you wish to have this behavior, you can use custom schema loader, and add a custom directive in your setup. Then you can change the schema according to your needs (could be done with graphql-tools or graphql-compose) .

**Comment by lanwin** [comment]
> Hi @lanwin , thank you for opening this issue.
> 
> We decided that codegen input will be a ready to use schema, and to avoid schema transformations in codegen.
> 
> If you wish to have this behavior, you can use custom schema loader, and add a custom directive in your setup. Then you can change the schema according to your needs (could be done with graphql-tools or graphql-compose) .

Hi Dotan, thanks for your answer but I am not sure I understand what you mean. My suggest did not include a schema transformation form what I understand. 

My goal was to add an "optional" directive within my server witch generates that schema. Than make codegen switch the avoidOptionals behavior when it receives that directive on a per field level instead of the hole file.

**Comment by dotansimha** [comment]
I see, but the means that codegen needs to take an opinion, and dictates the usage of `@optional` directive. What if someone else has a directive with the same name? it will break their setup. 
We are trying to avoid those custom behaviour based on directives (same with `@client`, `@connection` and more).

What I'm trying to say is - GraphQL codegen will keep following the GraphQL spec as-is, without additional features.
I know that GraphQL directives can do a lot and it has potential to make a lot of things simpler, but those kind of solutions should be per-project, and not something that built-in within the codegen. 

What I suggested is to create a custom schema loader, and point the codegen to it. Then, this custom loader should take the original schema, look for `@optional` directive, and change the field definition according to your needs. 

Maybe I misunderstood, am I missing something here?

**Comment by lanwin** [comment]
> 
> 
> I see, but the means that codegen needs to take an opinion, and dictates the usage of `@optional` directive. What if someone else has a directive with the same name? it will break their setup.
> We are trying to avoid those custom behaviour based on directives (same with `@client`, `@connection` and more).
> 
> What I'm trying to say is - GraphQL codegen will keep following the GraphQL spec as-is, without additional features.
> I know that GraphQL directives can do a lot and it has potential to make a lot of things simpler, but those kind of solutions should be per-project, and not something that built-in within the codegen.
> 
> What I suggested is to create a custom schema loader, and point the codegen to it. Then, this custom loader should take the original schema, look for `@optional` directive, and change the field definition according to your needs.
> 
> Maybe I misunderstood, am I missing something here?

You are right about the optional directive. But that could be fixed by making the directive disabled by default and make the user configure an name to enable it. Something like `optionalDirective: optional`

Well if the CodeGen really follows the GraphQL spec, then I think avoidOptionals should not exists (cause the GraphQL spec did not know undefined). But it exists for some users needs and all I suggest is to make it not an all or nothing approach and be able to configure it on a per field base. An directive would be an obvious choice but I am not fixed on a directive. I could also imaging allowing to override the config on a per Object maybe Field base.

I am also still now sure how a custom schema loader could help and I hope you can give me a hint there. From what I know, GraphQL schema has nothing like an Javascript undefined which in the end means the field could be omitted from sending (input). So I could look for the directive in the schema. But how can I make the Typescript Generator generate `foo: string|null|undefined` instead of foo: `string|null` for me then.

**Comment by dotansimha** [comment]
`avoidOptionals` is a codegen configuration that effects codegen only, and it's relevant to the TypeScript output.
This configuration doesn't change the structure of your GraphQL schema, it only changes the TypeScript output and avoids using `?` on fields (while `Maybe` value will still apply the null effect). If your GraphQL field is nullable, it will remain nullable and this will not change it.

I'm not against making `avoidOptionals` more granular, and allowing something like that:

```
config:
  forceOptional:
    - Query.myField
    - User.username
```

Because this is a codegen config, and it effect the TypeScript output only. Although this is not ideal, and may cause runtime issues because you change the behaviour of your code based on that.

Doing that with directives is something we are not going to support at the moment, because we don't want people to modify their schema in order to effect codegen behaviour. Your GraphQL schema is a public artifact, and it should not contain development tools "hints". 

Why not just change the schema according to your needs? one of the goals of GraphQL is to allow developers to have type-safety, and by modifying fields attributes, you are breaking the type-safety.

Regarding custom schema loader - You can use it to modify the schema process and change your schema.

Let's say you have a scheme like that, in a file called `schema.graphql`: 

```graphql
directive @codegenOptional on FIELD

type Query {
  myField: String! @codegenOptional
}
```

You application code needs to load that schema and use it as-is, without changing anything on that field.

You can create a custom code file (`codegen-schema-loader.js`) that manages the loading process of that, and modifies the schema according to your needs: 

```ts
import { readFileSync } from 'fs';
import { buildClientSchema, parse, visit } from 'graphql';

const astSchema = parse(readFileSync('./schema.graphql', 'utf-8'));

const modifiedAst = visit(astSchema, {
  FieldDefinition: {
    leave: node => {
       if(node && node.directives) {
          const relevantDirective = node.directives.find(d => d.name.value === 'codegenOptional');

          if (relevantDirective && node.type.kind === 'NonNullType') {
             return { ...node, type: node.type.type };
          }

          return node;
       } 
    }
  }
});

export default buildClientSchema(modifiedAst);
```

And then tell codegen to use it:

```
schema: codegen-schema-loader.js
```

**Comment by lanwin** [comment]
> I'm not against making `avoidOptionals` more granular, and allowing something like that:
> ```
> config:
>   forceOptional:
>     - Query.myField
>     - User.username
> ```

Ok then should I create a new issues for that or can we reuse this one?

> Why not just change the schema according to your needs? one of the goals of GraphQL is to allow developers to have type-safety, and by modifying fields attributes, you are breaking the type-safety.

Cause GraphQL has no support for partial inputs (or optional fields) for now. We have a large input object, but most of the time our users change only one or two values. What basically means I need to load that large object and resend the entire object to the server. Instead we made most of the fields optional so that users can send partial objects. I see no way to reflect that in my GraphQL schema and so I have no chance to communicate that to the CodeGen. I also can not use null cause most of the time, null is a valid input and means the field is "cleared" or "removed" by the user. So null means field value is empty, undefined (or field missing) means the user did not sent it. The only option I see to communicate that via GraphQL schema are a directive like "@partial" or "@optional"

> You can create a custom code file (`codegen-schema-loader.js`) that manages the loading process of that, and modifies the schema according to your needs:

I understand the code and how it works. The only think I did not understand is how I can use that to make the Typescript CodeGenerator let output an optional (or add undefined as allowed value).

Again thanks for your answer and your time!

**Comment by dotansimha** [comment]
@lanwin to allow `undefined` value, you can override `maybeValue` in your config, and it will allow you to use `undefined` where nullable fields are. It will also effect input fields.

```
   config:
     maybeValue: T | null | undefined
```

Btw, I think you can create a custom scalar to represent the option for "ignored" field. And the manage it yourself, and control the "EMPTY" value with your own code. Like a `scalar CustomString` that allow you to set the value to `undefined` or any other predefined string, and the `parseLiteral` of that scalar can transform the custom value into `undefined`.

**Comment by lanwin** [comment]
> @lanwin to allow `undefined` value, you can override `maybeValue` in your config, and it will allow you to use `undefined` where nullable fields are. It will also effect input fields.
>    config:
>      maybeValue: T | null | undefined

Yes that would work for the input obj. But it also would mean that I need to handle undefined in the rest of the codebase. Witch mean I had to handle undefined in a lot of cases where undefined could never happened.

> Btw, I think you can create a custom scalar to represent the option for "ignored" field. And the manage it yourself, and control the "EMPTY" value with your own code. Like a `scalar CustomString` that allow you to set the value to `undefined` or any other predefined string, and the `parseLiteral` of that scalar can transform the custom value into `undefined`.

Hmm that meant to do a lot of code to handle such a simple task. The sad thing is that GraphQL did hot have the concept of Generics. So I 

--

Wouldnt It in general a good idea to be able to override some config options on a type and field level instead of only output file level? If you think about it, it could also be extended to be able to override options if the schema type have a special directive. This way CodeGen did not have any special meaning of a directive per default. But the CodeGen users can define what a directive should do if CodeGen find one.

**Comment by lanwin** [comment]
@dotansimha to come back on that. Should I create a new issue to suggest to override options on a Type/Field level?

**Comment by lanwin** [comment]
@dotansimha I now also testet the scalar route. It works quiet well but I run pretty fast into the issue that I can not handle Lists with that and not even complex objects.

**Comment by IgorSzymanski** [comment]
@lanwin, hey, how did you solve this?

**Comment by lanwin** [comment]
> @lanwin, hey, how did you solve this?

It's sad but I did not have a solution yet. So I postponed the update of graphql gen and still looking for a good solution.
