### ISSUE TITLE
Use PascalCase for isTypeOfResolverFn

### ISSUE THREAD

**Issue by jer-sen** [dotansimha/graphql-code-generator#4129]
`isTypeOfResolverFn` is a type and should be written `IsTypeOfResolverFn`

**Comment by ardatan** [comment]
I think you did a typo because both variable names you wrote is`isTypeOfResolverFn`.

**Comment by jer-sen** [comment]
Yes, sorry. Typo fixed.

**Comment by dotansimha** [comment]
Fixed in https://github.com/dotansimha/graphql-code-generator/commit/871522fe28cb95ad375b4c1d2d26b1ed6c6237dd

**Comment by dotansimha** [comment]
Fixed in `v1.15.2`
