### ISSUE TITLE
Resolver type error

### ISSUE THREAD

**Issue by shinyaohira** [dotansimha/graphql-code-generator#413]
Hi, I'm using graphql-code-generator v0.10.1.
When query root is defined in snake case, the resolver type name is not generated properly.

schema:
```
snake_case_root_query(
  arg: snake_case_arg
): snake_case_result
```

generated type:
```
export type Snake_case_root_queryResolver = Resolver<
  snake_case_result,
  Snake_case_root_queryArgs  # <- NG
>;

export interface SnakeCaseRootQueryArgs {  # <- OK
  arg: snake_case_arg
}
```

**Comment by dotansimha** [comment]
@kamilkisiela 👍

**Comment by rogersp** [comment]
This is still an issue for me in 0.10.5.

![image](https://user-images.githubusercontent.com/2909421/43416908-6ace5dc0-93ee-11e8-9ebb-faf8386b52a7.png)

**Comment by kamilkisiela** [comment]
@rogersp that's because all is pascalCased
