### ISSUE TITLE
Feature/Plugin: Support directive `@connection` to generate Relay schema

### ISSUE THREAD

**Issue by lorenzleutgeb** [dotansimha/graphql-code-generator#4130]
I would like to use this package with schemas that contain [the Relay-related `@connection` directive as provided by GraphQL Kickstart](https://www.graphql-java-kickstart.com/tools/relay/). This would allow users to avoid typing out a lot of boilerplate code when using Relay.

GraphQL Codegen (or a plugin) should process the `@connection` directive and expand

```graphql
type Query {
    users(first: Int, after: String): UserConnection @connection(for: "User")
    organizations(first: Int, after: String): OrganizationConnection @connection(for: "Organization")
}

type User {
    id: ID!
    name: String
}

type Organization {
    id: ID!
}
```

into

```graphql
type Query {
    users(first: Int, after: String): UserConnection
    organizations(first: Int, after: String): OrganizationConnection
}

type UserConnection {
    edges: [UserEdge]
    pageInfo: PageInfo
}

type UserEdge {
    cursor: String
    node: User
}

type PageInfo {
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
}

type User {
    id: ID!
    name: String
}

type OrganizationConnection {
    edges: [OrganizationEdge]
    pageInfo: PageInfo
}

type OrganizationEdge {
    cursor: String
    node: Organization
}

type Organization {
    id: ID!
}
```

before advancing to code generation.

[GraphQL Java Tools](https://github.com/graphql-java-kickstart/graphql-java-tools) contains a Kotlin implementation that could serve as a template:

 * [`RelayConnectionFactory`](https://github.com/graphql-java-kickstart/graphql-java-tools/blob/05de5823690353d506bdf8f4075df3cb3c7af469/src/main/kotlin/graphql/kickstart/tools/relay/RelayConnectionFactory.kt)
 * [`RelayConnectionTest`](https://github.com/graphql-java-kickstart/graphql-java-tools/blob/05de5823690353d506bdf8f4075df3cb3c7af469/src/test/kotlin/graphql/kickstart/tools/RelayConnectionTest.kt)

**Comment by ardatan** [comment]
@lorenzleutgeb You can also point directly to the URL of your GraphQL Endpoint. Isn't that working for you?

**Comment by lorenzleutgeb** [comment]
@ardatan That's of course possible, but in our case it requires compiling, packaging and deploying the backend code. That's a lot less efficient compared to just running GraphQL code generation. In addition there are frontend-oriented developers working on the project, and they usually don't spin up the backend but want to be able to modify the schema anyway.

**Comment by ardatan** [comment]
@lorenzleutgeb I see. Maybe we can generate those typings with https://github.com/graphql/graphql-relay-js. Thanks for the idea!

**Comment by lorenzleutgeb** [comment]
@ardatan Hmm, I wouldn't see how `graphql-relay-js` helps in this case. I searched the repository for "directive" without any luck and couldn't find any code transforming the schema either. If I understood correctly it helps with implementing resolvers. Maybe you could enlighten me and explicate the link that I am missing? The Kotlin implementation I referenced should not be hard to "translate" to TS/JS.

**Comment by ardatan** [comment]
I mentioned this library to generate Connection,Edge and other relay-specific types, not handle the SDL you gave. `@connection` is not standard and something specific for the library you mentioned. That's why we need to handle on our own in that case.

**Comment by dotansimha** [comment]
This is something we are thinking about a lot recently. 
At the moment, Codegen gets the ready-to-use schema, as-is, and generate types according to that. Is simplifies and implementation and eliminates the need to have framework-specific code in this library. 

If you wish to have this kind of behaviour, you can use [custom schema loader](https://graphql-code-generator.com/docs/getting-started/schema-field#custom-schema-loader) to load your schema in a custom way, and run https://github.com/graphql/graphql-relay-js for example, in order to transform the schema before feeding it to the codegen.
