### ISSUE TITLE
Add avoidOptionals "on keys" settings

### ISSUE THREAD

**Issue by stephenh** [dotansimha/graphql-code-generator#4147]
When using `typescript-operations`, for a given input type with an optional field like:

```graphql
input AuthorInput {
  firstName: String
}
```

I want to be able to enable `avoidOptionals: true`-ish behavior where `firstName` is required, but it's value itself can still be `undefined`, i.e.:

```typescript
// invalid, missing firstName
const input1: AuthorInput = {};

// valid, has firstName, but is setting it to undefined
const input2: AuthorInput = {
  firstName: undefined;
}

// also valid
const input3: AutorInput = {
  firstName: null;
}
```

I cannot do `input2` today because `Maybe<T>` is hardcoded as `T | null` instead of `T | null | undefined`. It looks like there used to be an `optionalType` config:

https://github.com/dotansimha/graphql-code-generator/pull/1024/files

But I can't find any vestige of this in the current codebase.

**Comment by dotansimha** [comment]
`Maybe<T>` is not hardcoded. You can customize it with `maybeValue`. 

```yml
   config:
     maybeValue: T | null | undefined
```

Also, if you wish to have more control over optionals, you can do:

```yml
 config:
   avoidOptionals:
     field: true
     inputValue: true
     object: true
```

https://graphql-code-generator.com/docs/plugins/typescript

**Comment by stephenh** [comment]
Gah! I swear I looked for that. :grimacing:  Thanks!
