### ISSUE TITLE
mergedDocuments: Provide operation filename - where a given operation / fragment came from

### ISSUE THREAD

**Issue by adam1658** [dotansimha/graphql-code-generator#415]
I'm writing my own output processor function (https://github.com/dotansimha/graphql-code-generator/tree/master/packages/templates) for client-side operation result types (for Typescript).

For each *.graphql file in my project, I'd like to place multiple *.ts files beside it - one for each operation / fragment, but to do so I need to know what file a given operation / fragment came from.

Is it possible to get the filename that an operation / fragment originated in?

P.S. Thanks for an **awesome** project guys!

**Comment by dotansimha** [comment]
That's sounds interesting. Do you use Handlebars or just JS for your template?
If you wish to create multiple TS files for a single operation -> you can use MULTIPLE_FILES template and use the operation name as your filename.

**Comment by dotansimha** [comment]
@adam1658 , sorry it took time. Now the codegen exposes `originalFile` on each operation, and exposes `documentsFiles` as list of all files.

See: 
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/types.ts#L223-L230

https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-compiler/src/compile.ts#L136-L143

And it's in use in this template: 
https://github.com/dotansimha/graphql-code-generator/tree/master/packages/templates/graphql-files-typescript-modules

**Comment by adam1658** [comment]
@dotansimha, no problem about the wait. This looks great - can't wait for a release :)

**Comment by dotansimha** [comment]
Available in 0.13.0
