### ISSUE TITLE
Support .graphql files as input

### ISSUE THREAD

**Issue by yohcop** [dotansimha/graphql-code-generator#419]
Hi,
I'm trying to generate typescript typings at build time, based on a `.graphql` schema file, checked in with my code. I can't find a way to use those as input directly.

I don't have a `schema.ts`, since my server isn't in nodejs (it's in Go, and it uses the `.graphql` files).
And of course once the server is built and running, using `--url` works, or I can get a `schema.json` file from it,, but I'd like to do this during the build process, such that typings are always in sync with the schema.

I've looked for other potential library/cli converting `.graphql` schema to a compatible introspection `.json`, but couldn't find any. If you know of one, that would be good enough :)

Thanks!

**Comment by yohcop** [comment]
Ah, obviously I've been looking at this all wrong since this morning, and as soon as I ask the question, I  find the simple answer... classic :cry: 

The ts files accepted by --schema flag can be generated very easily... they just need to be like:

```
module.exports = `$(graphql_file_content)`
```

and done... 1 line of code to do that.

That being said, it seems like it would be trivial then to get the string from a .graphql file passed as an argument, instead of from the default export of a ts file.

I'll leave this open if you would like to implement it anyway, otherwise feel free to close.

**Comment by dotansimha** [comment]
It makes sense. I'll look into it :) 
Note that you can create introspection using this package (there is a template for it)

**Comment by dotansimha** [comment]
@yohcop 
With v0.10.3, you can now specify a glob for the schema, and the codegen will try to pick up the graphql files, and compile them to a `GraphQLSchema`.  Use `--schema "./src/schema/**/*.graphql" `.

**Comment by yohcop** [comment]
Well, that was quick! Awesome, thanks a lot!
