### ISSUE TITLE
Type 'GraphQLSchema' is missing the following properties from type 'DocumentNode': kind, definitions

### ISSUE THREAD

**Issue by ricokahler** [dotansimha/graphql-code-generator#4206]
**Describe the bug**
 

I'm passing in a GraphQLSchema from `buildClientSchema` like so:

![image](https://user-images.githubusercontent.com/10551026/84308280-3ab3e400-ab2c-11ea-94b8-84864e0da61e.png)

[`buildClientSchema`](https://github.com/graphql/graphql-js/blob/4a9b8bad6880fee63997913ff7e950014a936873/src/utilities/buildClientSchema.d.ts#L20) returns the type [`GraphQLSchema`](https://github.com/graphql/graphql-js/blob/4a9b8bad6880fee63997913ff7e950014a936873/src/type/schema.d.ts#L48) but [`Types.GenerateOptions['schema']`](https://github.com/dotansimha/graphql-code-generator/blob/5035d7817850e83a83ce1f7b2daa9c84d4d34867/packages/utils/plugins-helpers/src/types.ts#L8) requires a [`DocumentNode`](https://github.com/graphql/graphql-js/blob/4a9b8bad6880fee63997913ff7e950014a936873/src/language/ast.d.ts#L212-L216)

According to this type error, they aren't compatible:

![image](https://user-images.githubusercontent.com/10551026/84308911-54096000-ab2d-11ea-8923-16090823b9aa.png)

**To Reproduce**

This is a type error so to reproduce, just copy and paste this somewhere and resolve the imports:

      await codegen({
        filename: '',
        schema: buildClientSchema(schemaResult.data),
        plugins: [],
        pluginMap: {},
        documents: [],
      })

[CodeSandbox link](https://codesandbox.io/s/withered-glitter-5s6mq?file=/example.ts)

**Expected behavior**

This seems to work when I throw an `// @ts-ignore` in there so I would expect the types to be okay with it.

**Environment:**

- OS: MacOS
- `@graphql-codegen/core@1.15.2`: 
- NodeJS: 12 LTS

**Additional context**

I might have missed something or maybe this is an issue upstream in graphql.js

Thanks!

**Comment by dotansimha** [comment]
This was due to an incorrect usage back then. We are dragging this for a long time. 
We'll for sure fix it in v2 (https://github.com/dotansimha/graphql-code-generator/discussions/3955)

**Comment by ardatan** [comment]
@robcdd Nothing new. This is not a bug. `schema` takes `DocumentNode`, `schemaAst` takes `GraphQLSchema`. If you want to build `GraphQLSchema` from `DocumentNode`, you can use `buildASTSchema` from `graphql-js` but this is completely unrrelated to this issue.
