### ISSUE TITLE
Allow config hooks to be functions if used cli programatically

### ISSUE THREAD

**Issue by KnisterPeter** [dotansimha/graphql-code-generator#4219]
**Is your feature request related to a problem? Please describe.**

I would like to execute a function when a watch is triggered.
I could do so with using the `onWatchTriggered` hook, but this only executes commands.
It is a very big overhead to spawn a new node process if this happens often and a function would help here to run the thing in process.

**Describe the solution you'd like**

I would like to add a function to the hook configuration.

**Comment by KnisterPeter** [comment]
@dotansimha Do you accept contributions?

**Comment by dotansimha** [comment]
@KnisterPeter sure! always :)

**Comment by KnisterPeter** [comment]
@dotansimha It took a bit of time, but now there is a PR for it.
I've removed the specific generics in most parts and fallback to the default generics given by the types. Its only overwritten now in places where its required.

**Comment by dotansimha** [comment]
Available in `v1.16.1`

**Comment by crazyx13th** [comment]
nice idea!, any example?

```typescript
hooks: {
	afterAllFileWrite: (...args) =>
	{
		const fs= require('fs')
		fs.writeFileSync('dummyfile', 'xxxxxxxx')
	},
} 
```

not working at with `generate(input, true)`

thanks!

**Comment by dotansimha** [comment]
@crazyx13th if it's still relevant, can you please report this on a new issue with a reproduction?
