### ISSUE TITLE
Feature: support typescript option importsNotUsedAsValues

### ISSUE THREAD

**Issue by ggascoigne** [dotansimha/graphql-code-generator#4230]
Typescript 3.8 adds support for type only imports.  I would be nice if there was an option to allow the generated code to contain:

```
import type ApolloReactCommon from '@apollo/react-common'
import type ApolloReactHooks from '@apollo/react-hooks'
```

instead of 

```
import * as ApolloReactCommon from '@apollo/react-common'
import * as ApolloReactHooks from '@apollo/react-hooks'
```

This is mostly coming up because recent versions of snowpack use this default.

**Comment by dotansimha** [comment]
Hi @ggascoigne ! 
Let's track it here: https://github.com/dotansimha/graphql-code-generator/issues/3695
