### ISSUE TITLE
Unable to load schema

### ISSUE THREAD

**Issue by palaparthi** [dotansimha/graphql-code-generator#4258]
When I try to generate, it fails with 404 error, however schema exists at `http://localhost:4040/graphql` below is the error

graphql-codegen --config codegen.yml

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.tsx
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate

 Found 1 error

  ✖ src/generated/graphql.tsx
    Failed to load schema from http://localhost:4040/graphql:

        Could not obtain introspection result, received: {"status_code":404,"msg":"Not Found","details":{"path":"/graphql"}}
        Error: Could not obtain introspection result, received: {"status_code":404,"msg":"Not Found","details":{"path":"/graphql"}}
    at getSchemaFromIntrospection (/Users/sree/my-projects/whistlehere-app/node_modules/@graphql-tools/wrap/index.cjs.js:1195:15)
    at Object.introspectSchema (/Users/sree/my-projects/whistlehere-app/node_modules/@graphql-tools/wrap/index.cjs.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async UrlLoader.getSubschemaConfig (/Users/sree/my-projects/whistlehere-app/node_modules/@graphql-tools/url-loader/index.cjs.js:129:21)
    at async UrlLoader.load (/Users/sree/my-projects/whistlehere-app/node_modules/@graphql-tools/url-loader/index.cjs.js:135:33)
    at async loadFile (/Users/sree/my-projects/whistlehere-app/node_modules/@graphql-tools/load/index.cjs.js:48:24)
    at async /Users/sree/my-projects/whistlehere-app/node_modules/@graphql-tools/load/index.cjs.js:425:24`

Following is my codegen.yml

```overwrite: true
schema: "http://localhost:4040/graphql"
documents: "src/graphql/**/*.ts"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-type-graphql"
      - "introspection"
      - "typescript-react-apollo"
    config:
      withHooks: true
      withHOC: false
```

I am using typegraphql on server, any help is much appreciated.

**Comment by ardatan** [comment]
I think you have already opened an issue before on Discussions. https://github.com/dotansimha/graphql-code-generator/discussions/4245 and @dotansimha answered it.

**Comment by palaparthi** [comment]
@ardatan The issue is not resolved and I am not sure how to reproduce this in sandbox. But the schema exists at the url. When I send a raw postman Introspection query I get back a response not 404.

Request Headers
```
Content-Type: application/json
User-Agent: PostmanRuntime/7.25.0
Accept: */*
Host: localhost:4040
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 1468
```

Request body
```
{"operationName":"IntrospectionQuery","variables":{},"query":"query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"}
```

I am happy to provide more information.

**Comment by palaparthi** [comment]
Figured out, localhost wasn't working on my computer had to give ip address instead in the config.yml file

**Comment by PulapakuraBros** [comment]
Can I see the config.yml file please? How did you solve it?

**Comment by MincePie** [comment]
How did you solve this problem?

**Comment by palaparthi** [comment]
Did you try using `127.0.0.1` instead of `locahost` in your yml file?

**Comment by MincePie** [comment]
As in replace the 'localhost' fragment with those numbers? I just tried, and get the same error but with this line difference: Failed to load schema from http://127.0.0.1:5555/graphql:
