### ISSUE TITLE
[typescript] non nullable graphql inputs with default values are not optional as ts types

### ISSUE THREAD

**Issue by bzvikler** [dotansimha/graphql-code-generator#4273]
**Describe the bug**
Currently if a property within the gql schema is set as non nullable, but has a default value assigned to it, the generated typescript property will be set as required.

**To Reproduce**

- navigate to this code sandbox: https://codesandbox.io/s/wandering-forest-efbol?file=/types.ts
- notice that while the input of `App` has a default for `users`, it is still required in the generated ts type

1. My GraphQL schema:

```graphql
input App {
    id: ID!
    displayName: String
    users: [String!]! = ["Hey", "hello"]
}
```

2. Generated type

```typescript
export type App = {
  id: Scalars['ID'];
  displayName?: Maybe<Scalars['String']>;
  users: Array<Scalars['String']>;
};
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

**Expected behavior**
If there is a provided default value, the generated ts type should allow for a value of `undefined`, as this is when the default value would be applied.

**Environment:**
- running on the code sandbox

**Additional context**
The issue arose when I was trying to integrate with a gql schema that indicated an array type with a default value. I wanted the default value, but due to this issue, I had to explicitly enter that value, as opposed to just omitting the type and letting the default handle it.

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript@1.17.10`

**Comment by mhart** [comment]
Hmmm, this has caused a bunch of incompatible changes in our codebase from a patch release.

Making these optional might make sense on a client, but not on a server – because they're guaranteed to have values. What's the best way to get around this issue?

**Comment by dotansimha** [comment]
@mhart I think you are right, can you please report this as separate issue? we'll look into it :) maybe this should be configurable.
