### ISSUE TITLE
graphql-codegen-typescript-template typescript cannot be used in @babel/preset-typescript

### ISSUE THREAD

**Issue by kambing86** [dotansimha/graphql-code-generator#428]
"@babel/cli": "^7.0.0-beta.53",
"@babel/core": "^7.0.0-beta.53",
"@babel/plugin-proposal-class-properties": "^7.0.0-beta.53",
"@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.53",
"@babel/preset-env": "^7.0.0-beta.53",
"@babel/preset-typescript": "^7.0.0-beta.53"

SyntaxError
Namespaces are not supported.

it seems like babel doesn't want to support namespace

https://babeljs.io/docs/en/next/babel-plugin-transform-typescript.html

**Comment by kambing86** [comment]
fast fix for this is to change every `export namespace` to `export declare namespace` or `export declare module`, still need to figuring out why

**Comment by ardatan** [comment]
This has to be fixed by noNamespaces option please check out typescript template documentation for more details;
https://github.com/dotansimha/graphql-code-generator/tree/master/packages/templates/typescript
