### ISSUE TITLE
Optional Namespace/Class Wrapper for C# plugin

### ISSUE THREAD

**Issue by nabeelvalley** [dotansimha/graphql-code-generator#4281]
**Is your feature request related to a problem? Please describe.**

C-Sharp Plugin generates a wrapper class as well as an automatic namespace of `GraphQLCodeGen` that can't be renamed via the CodeGen itself. It would be useful to opt out of this behaviour

**Describe the solution you'd like**

An Option to not include the Wrapper Class (by default this is named `Types` and is overridden with the `config.className` property in the config file. (possibly some kind of boolean field in the config) as well as an option to set the `namespace` for the class. Possibly with a `config.nameSpace` property

**Describe alternatives you've considered**

Setting the `config.className` does not allow the overriding of the namespace, and it doesn't look like it's possible to totally exclude the wrapper class either

**Additional context**

By default, the codegen outputs a file like this:

```cs
namespace GraphQLCodeGen {
  public class Types {
    public class MyTypeName { ... }
   }
}
```

I would like to be able to output something more like this using the config to rename the namespace and removing the wrapper class:

```cs
namespace Project.MyNameSpace {
  public class MyTypeName { ... }
}
```

**Comment by cklam2** [comment]
This was already solved with pull request #4264 so you'll have to wait for a new release or use the [alpha](https://github.com/dotansimha/graphql-code-generator/pull/4264#issuecomment-647375136) version.

**Comment by cklam2** [comment]
Regarding the Types wrapper: I believe that it's added to avoid name clashes. 

There is indeed no way to exclude the wrapper but if you don't want to have constructions like `Types.Query` you can add following `using` to the header of your cs:
```
using static GraphQLCodeGen.Types;
```
Then you can use `Query` as-is.

**Comment by nabeelvalley** [comment]
@cklam2 thanks for the information!

**Comment by dotansimha** [comment]
@nabeelvalley does this fit your needs? we can close this?

**Comment by nabeelvalley** [comment]
@dotansimha yup, fine to close
