### ISSUE TITLE
Where is the documentation for the gqlgen.json file?

### ISSUE THREAD

**Issue by jclangst** [dotansimha/graphql-code-generator#430]
It appears to be referenced throughout, but I could not find it in any of the packages.

Some of the README files have dead links (https://github.com/dotansimha/graphql-code-generator/tree/master/packages/graphql-codegen-compiler) that seem like they might be trying to point to it?

**Comment by ardatan** [comment]
You can see the example config below;
https://github.com/dotansimha/graphql-code-generator/tree/master/packages/graphql-codegen-cli#gql-genjson
