### ISSUE TITLE
Fragment imports from different NPM packages

### ISSUE THREAD

**Issue by lexanth** [dotansimha/graphql-code-generator#4307]
**Describe the bug**
We have some cases where a fragment will be defined alongside a component in one package, and need to be used by a query in another package. We currently end up having to have all queries in the same package as the fragment to use relative path imports.

Apollo and GraphQL codegen both work fine with `#import` and relative paths. Apollo's graphql tag webpack loader also works with package imports, as it just replaces the path with a `require` statement to pull in the fragment ([here](https://www.apollographql.com/blog/webpacking-your-graphql-documents-bf9697ed259b)). However, running codegen with this gives `GraphQLDocumentError: Unknown fragment` because it hasn't resolved the import.

I've tracked this down to the `skipGraphQLImport` option in https://github.com/dotansimha/graphql-code-generator/blob/cbd99701739d9158211b686379412e2209edd94c/packages/graphql-codegen-cli/src/load.ts#L75. I can actually override this by putting `skipGraphQLImport: false` at the root of my graphql config (not in a `config` block, directly at the root), but this isn't a documented behaviour.

**To Reproduce**

In `package-1/src/reusableFragment.graphql`
```graphql
fragment ReusableFragment on SomeSchemaType {
  id
  name
}
```

Then in `package-2/src/MyQuery.graphql`
```graphql
#import "package-1/src/reusableFragment.graphql"

query MyQuery {
  something {
    ...ReusableFragment
  }
}
```

**Expected behavior**
Codegen resolves the import from `package-1` as if the fragment were defined in `package-2`

**Environment:**

- OS: macOS
- `@graphql-codegen/...`: 1.15.4
- NodeJS: 12.16.3

**Additional context**
It looks like `skipGraphQLImport: true` was added to fix https://github.com/dotansimha/graphql-code-generator/issues/3326, but allowing a (documented, supported) override would help.

Or if `skipGraphQLImport: false` is already supported, can it be added to the documentation?

**Comment by Krankypanky** [comment]
Having the same issue...

**Comment by GiancarlosIO** [comment]
same here 👀

**Comment by dotansimha** [comment]
`skipGraphQLImport: false` is supported. We recommend to use glob expression to load all files into codegen, and not to rely on `graphql-import` syntax, since it does some checks that might cause missing types. 

Docs are updated now.
