### ISSUE TITLE
Issues running test suite on fresh clone

### ISSUE THREAD

**Issue by asafh** [dotansimha/graphql-code-generator#4337]
**Describe the bug**
A fresh master clone with dependencies installed has some of the tests issuing errors/warnings and skipped.

```
 PASS  packages/plugins/typescript/named-operations-object/tests/plugin.spec.ts
  ● Console

    console.warn
      Plugin "named-operations-object" has an empty output, since there are no valid operations!

      69 |   if (objectItems.length === 0) {
      70 |     // eslint-disable-next-line no-console
    > 71 |     console.warn(`Plugin "named-operations-object" has an empty output, since there are no valid operations!`);
         |             ^
      72 | 
      73 |     return '';
      74 |   }

      at Object.exports.plugin (packages/plugins/typescript/named-operations-object/src/index.ts:71:13)
      at Object.<anonymous> (packages/plugins/typescript/named-operations-object/tests/plugin.spec.ts:29:26)

    console.warn
      Plugin "named-operations-object" has an empty output, since there are no valid operations!

      69 |   if (objectItems.length === 0) {
      70 |     // eslint-disable-next-line no-console
    > 71 |     console.warn(`Plugin "named-operations-object" has an empty output, since there are no valid operations!`);
         |             ^
      72 | 
      73 |     return '';
      74 |   }

      at Object.exports.plugin (packages/plugins/typescript/named-operations-object/src/index.ts:71:13)
      at Object.<anonymous> (packages/plugins/typescript/named-operations-object/tests/plugin.spec.ts:79:26)
```
and
```
PASS  packages/plugins/java/apollo-android/tests/operations.spec.ts
(node:36470) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
(node:36470) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36470) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
```

**To Reproduce**
```
git clone git@github.com:dotansimha/graphql-code-generator.git
cd graphql-code-generator
yarn
yarn test
#Alternatively:
yarn test -- -t "named-operations-object"
```

**Expected behavior**
All tests to pass without warnings or unhandled promise rejections 

**Environment:**

- OS: macOS Catalina
- `@graphql-codegen/1.16.3`: 
- NodeJS: 12.13

**Additional context**

**Comment by dotansimha** [comment]
Can you please try to run `yarn build` and then try `yarn test`? 
CI seems to be fine...

**Comment by asafh** [comment]
Hi Dotan,
Sure, just did (another fresh clone):
```
git clone git@github.com:dotansimha/graphql-code-generator.git
cd graphql-code-generator
yarn
yarn build
yarn test
```
However I still get the above issues - keep in mind they don't fail their test suite (but perhaps they should?):
```Test Suites: 47 passed, 47 total
Tests:       4 skipped, 918 passed, 922 total
Snapshots:   75 passed, 75 total
Time:        41.403 s
```
That is, whatever creates the promise being unhandled rejection either handle it in according to the wanted test behavior (fail the test on exception then fix the tested code or, if wanted behaviour, have the test expect the code to throw).
As for the "named-operations-object" warning, it's less of a [potential] issue but you might want to remove that print (it's in the actual plugin - not in the test), based on your preferences.

Moreover I just noticed that there's a warning at the end of the test suite:
```A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.```
Though this seems irrelevant:
```Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TTYWRAP

      604 |   onScript: string[];
      605 | }) {
    > 606 |   bddStdin(
          |           ^
      607 |     [].concat(
      608 |       inputs.onTarget,
      609 |       inputs.onSchema,

      at Object.mock [as stdin] (node_modules/mock-stdin/lib/mock/stdin.js:206:36)
      at Object.bddStdin [as default] (node_modules/bdd-stdin/index.js:16:37)
      at useInputs (packages/graphql-codegen-cli/tests/init.spec.ts:606:11)
      at Object.<anonymous> (packages/graphql-codegen-cli/tests/init.spec.ts:100:5)
```

I'll try to narrow down the actual unhandled rejection.

**Comment by asafh** [comment]
To narrow down the unhandled rejection I added a jest setupFile script (place in dev-test - let me know if you'd prefer a different placement) and added it to the configuration in root/jest.project.js:
```js
process.on('unhandledRejection', (err) => {
    fail(err);
});
```
Now any unhandledRejection will not go unnoticed. To narrow down which test specifically causes it I ran jest with ```--runInBand``` and found it belongs to ```apollo-angular.spec.ts```:
```
Cannot read property 'name' of undefined
    at graphql-code-generator/node_modules/graphql/type/introspection.js:592:17
    at Array.some (<anonymous>)
    at Object.isIntrospectionType (graphql-code-generator/node_modules/graphql/type/introspection.js:590:29)
    at Object.Field (graphql-code-generator/packages/plugins/typescript/typescript/src/index.ts:30:27)
    at Object.enter (graphql-code-generator/node_modules/graphql/utilities/TypeInfo.js:370:25)
    at Object.visit (graphql-code-generator/node_modules/graphql/language/visitor.js:243:26)
    at graphql-code-generator/packages/plugins/typescript/typescript/src/index.ts:35:40
    at Array.forEach (<anonymous>)
    at includeIntrospectionDefinitions (graphql-code-generator/packages/plugins/typescript/typescript/src/index.ts:35:15)
    at Object.exports.plugin (graphql-code-generator/packages/plugins/typescript/typescript/src/index.ts:17:38)
 FAIL  packages/plugins/typescript/apollo-angular/tests/apollo-angular.spec.ts
```

I'll try to narrow this down as well as create a PR that will cause any unhandledRejections in the future to fail the tests.

**Comment by asafh** [comment]
I found the orphaned promise, there's a missing await (or return) in the last line of ```Apollo Angular\configuration\should be allowed to define custom operation suffixes in config``` causing that test not to notice the validateTypescript function fails.

Looking more carefully, it seems most calls to validateTypescript in the apollo-anguler.spec.ts file are orphaned and should be awaited

Currently this means this test fails, I'll see if I have a fix for the exception in validation.

**Comment by asafh** [comment]
hi @dotansimha, Created PR #4355 :
> I've made two fixes to the angular tests: (i) awaiting all validateTypeScript calls as to not hide failures and (ii) fixing the test that was (silently) failing by updating its gql mutation/subscription to fit the actual schema.
> 
> Other than that, this PR also includes a setup file for jest which makes sure the execution fails if there's an unhandledRejection so that they may not stay hidden.

It seems like the CI on Node 14 is timing out, there shouldn't be any significant duration increase - is there a way to increase the timeout/rerun the CI or am I mistaken?

**Comment by dotansimha** [comment]
Closed in https://github.com/dotansimha/graphql-code-generator/pull/4355 . Thanks @asafh

**Comment by asafh** [comment]
Happy to. Thanks for maintaining this project.
