### ISSUE TITLE
Limitation in TypeScript can cause properties on arrays inside spread fragments to be dropped.

### ISSUE THREAD

**Issue by threehams** [dotansimha/graphql-code-generator#4344]
**Describe the bug**
Due to a limitation in TypeScript, intersecting two array-containing fragments results in all fragments past the first one being dropped.

**To Reproduce**

https://codesandbox.io/s/goofy-franklin-jrh86?file=/code.ts

1. Create two fragments, each of which selects from an array, and spread them both into a query. Example:
```
query user {
    user(id: 1) {
        id
        username
        email
        ...FriendIds
        ...FriendUsernames
    }
}

fragment FriendIds on User {
    friends {
        id
    }
}

fragment FriendUsernames on User {
    friends {
        username
    }
}
```
2. From the result of this query, call an array method such as `map` or `filter`, on the selected array, and access a property only available on the second fragment.
```
data.user.friends.map(friend => friend.username)
```

The result is that `username` is not found on type `{ id: string }`. The cause of this is that [intersected arrays don't work very well](https://github.com/microsoft/TypeScript/issues/11961).

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
    friends: [User!]!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
        ...FriendIds
        ...FriendUsernames
    }
}

fragment FriendIds on User {
    friends {
        id
    }
}

fragment FriendUsernames on User {
    friends {
        username
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      preResolveTypes: true,
```

**Expected behavior**
This one's tricky! It's a TS limitation, but this sort of thing can happen at any time. When using Relay-style component/fragment combinations, spreading multiple fragments is a normal part of life and there isn't really an available workaround besides some really nasty type assertions.

However, this would be possible to fix in generated types by expanding `preResolveTypes` (or adding yet-another-flag) to pre-resolve fragment types instead of referencing and intersecting them. This could expand the size of the generated types pretty dramatically, so opt-in might be best.

An example of `preResolveTypes` for the above:

```
export type UserQuery = {
  __typename?: "Query";
  user: {
    __typename?: "User";
    id: string;
    username: string;
    email: string;
  } & FriendIdsFragment &
    FriendUsernamesFragment;
};

export type FriendIdsFragment = {
  __typename?: "User";
  friends: Array<{ __typename?: "User"; id: string }>;
};

export type FriendUsernamesFragment = {
  __typename?: "User";
  friends: Array<{ __typename?: "User"; username: string }>;
};
```

With proposed change:

```
export type UserQuery = {
  __typename?: "Query";
  user: {
    __typename?: "User";
    id: string;
    username: string;
    email: string;
    friends: Array<{
      __typename?: "User";
      id: string;
      username: string;
    }>;
  };
};

// still export these for usage
export type FriendIdsFragment = {
  __typename?: "User";
  friends: Array<{ __typename?: "User"; id: string }>;
};

export type FriendUsernamesFragment = {
  __typename?: "User";
  friends: Array<{ __typename?: "User"; username: string }>;
};
```

**Environment:**

- OS: MacOS
- `@graphql-codegen/typescript-operations`: 1.16.3
- NodeJS: 12.13.0

**Additional context**

**Comment by threehams** [comment]
As usual, there are more options now than the last time I looked! `flattenGeneratedTypes` takes care of this issue, but it also eliminates the fragments entirely. I'll see there's a combination that flattens fragments while still exporting them separately.

**Comment by dotansimha** [comment]
@threehams you are right, it does have some issues with TS. The best way to go is to use `flattenGeneratedTypes` at the moment. 
We are trying to find a good solution, let's track this here: https://github.com/dotansimha/graphql-code-generator/issues/4212

**Comment by threehams** [comment]
Oh that's embarrassing, I searched for completely different terms.
