### ISSUE TITLE
-s alias for --silent does not work with graphl-codegen CLI

### ISSUE THREAD

**Issue by romMidnight** [dotansimha/graphql-code-generator#4346]
-s alias for --silent does not work with graphl-codegen CLI

specifying --silent works

[documentation](https://graphql-code-generator.com/docs/getting-started/codegen-config) states that both should work

Is it intended? can create a pull request with the fix

**Comment by dotansimha** [comment]
I guess it's a bug ;) PRs are always welcome :)

**Comment by dotansimha** [comment]
@romMidnight let's keep open until we'll have a release with that.

**Comment by dotansimha** [comment]
Fixed in `v1.17.2`
