### ISSUE TITLE
Customizability of Custom Templates

### ISSUE THREAD

**Issue by aurpine** [dotansimha/graphql-code-generator#435]
I've been using custom templates (`codegen-templates-scripts`). Although very powerful, I've found it to be lacking some fundamental features. 

## Template Calling

The templates called and their contexts are limited. It would be very useful to be able to specify which templates are used and with what contexts. This is especially useful when having to create multiple files with the same context. 

## File Naming

Custom templates currently does not permit custom file naming. It would be nice to be able to specify the file names within the generator instead of having to create a post-generation script to rename all the files. 

## Post Generation Scripts

This one isn't as important, but it would be easier to integrate post generation scripts into the code gen so that all the generation can be run with one command. As some scripts are necessary (such as linting for a different language), I think it makes sense to have some feature that runs on static code. 

---

All three of these are built into GraphQL-code-gen but aren't customizable with custom templates. It would greatly improve the use of the generator to have these customizations available. We can then rely less on scripts run after generation and hacky fixes.

**Comment by dotansimha** [comment]
@aurpine, you are refering to the `PROJECT` generation, right? 
I think it requires a big refactor, so I think if you and others have an idea for a better flow and a better solution - let us know :)

**Comment by dotansimha** [comment]
Closing this. `PROJECT` is not widely use at the moment, and it's possible to create customized templates with the custom output processors, or with a custom template (and you don't have to use Handlebars now)
