### ISSUE TITLE
TypeScript GraphQL Files Modules is unusable.

### ISSUE THREAD

**Issue by vavra7** [dotansimha/graphql-code-generator#4361]
Using plugin according to configuration in [documentation](https://graphql-code-generator.com/docs/plugins/typescript-graphql-files-modules) causes error:
```
        Please make sure that your codegen config file contains either the "schema" field 
        or every generated file has its own "schema" field.
        
        It should looks like that:
        schema:
          - my-schema.graphql

        or:
        generates:
          path/to/output:
            schema: my-schema.graphql
```

Adding schema in config file generates something like following:
```
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: any }> = { [K in keyof T]: T[K] };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Query = {
  __typename?: 'Query';
  hello?: Maybe<Scalars['String']>;
};

declare module '*/test.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const TestQuery: DocumentNode;

  export default defaultDocument;
}

```
Since only second part of file:
```
declare module '*/test.graphql' {
  import { DocumentNode } from 'graphql';
  const defaultDocument: DocumentNode;
  export const TestQuery: DocumentNode;

  export default defaultDocument;
}
```
is valid for file of type `*.d.ts` - typescript fully ignoore generated file.

**Comment by dotansimha** [comment]
Can you please share `codegen.yml`?

**Comment by vavra7** [comment]
I see now based on what you wrote. I used in config file also plugin 'typescript' according to [documentation](https://graphql-code-generator.com/docs/plugins/typescript-graphql-files-modules). When I remove it the incorrect part is no more included in *d.ts. I mistakenly attributed the problem to the need for a scheme. Then sorry for creating the bug. Just is needed to alter documentation.

**Comment by dotansimha** [comment]
@vavra7 you are right, we'll fix that :)

**Comment by dotansimha** [comment]
Pushed a fix for the docs :)
