### ISSUE TITLE
`this.apollo is undefined` when testing components using generated classes extending Apollo.Query

### ISSUE THREAD

**Issue by yannickpschroeder** [dotansimha/graphql-code-generator#4366]
**Describe the bug**
I'm using the graphql-code-generator for my Angular client. The code is generated perfectly from my Graphql schema and the Apollo.Query classes work fine. The problem happens when I run specs for components  using the generated Apollo.Query  classes. The error message always is `this.apollo is undefined`. Means that the constructor of class Query<T = {}, V = R> can't access the Apollo instance. I'm not sure why it works fine in normal operation. But the solution for it would be to add a super call and pass Apollo to the Apollo.Query constructor like:

```Typescript
@Injectable({
    providedIn: 'root'
  })
  export class ServiceGQL extends Apollo.Query<ServiceQuery, ServiceQueryVariables> {
    document = ServiceDocument;
    constructor(apollo:Apollo.Apollo) {
      super(apollo);
    }
  }
```
Adding this makes my spec files work correctly.

**To Reproduce**
- generate typescript interfaces from graphql schema
- inject generated class extending Apollo.Query into component
- write and run a spec for it

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:
```graphql
type Project {
    id: ID!,
    name: String!
}

type Query {
  projects: [Project]
}
```

2. My GraphQL operations:

```graphql
query Service {
    projects {
        id
        name
    }
}
```

3. My `codegen.yml` config file:
```yml
overwrite: true
schema: "../schema/graphql/schema.json"
documents: "../schema/graphql/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

**Expected behavior**
Expect Apollo.Query to not have different behavior when using in tests or normal use

**Environment:**

- OS: 
Dependencies:
```
  "dependencies": {
    "@angular/core": "9.1.0",
    "apollo-angular": "^1.8.0",
    "apollo-angular-link-http": "^1.9.0",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-link": "^1.2.13",
    "graphql": "^14.6.0",
    "graphql-tag": "^2.10.3",
  },
  "devDependencies": {
    "@graphql-codegen/cli": "1.15.0",
    "@graphql-codegen/typescript-apollo-angular": "1.15.0",
    "typescript": "3.8.3",
    "@graphql-codegen/typescript": "1.15.0",
    "@graphql-codegen/typescript-operations": "1.15.0",
    "@graphql-codegen/introspection": "1.15.0"
  },
```
[package.json](https://bitbucket.org/marcusriemer/esqulino/raw/a5c76dbb1a5020aa0590146d70a3419c7e97c13e/client/package.json)

**Additional context**
The Apollo Angular docs recommend to use ApolloTestingModule and ApolloTestingController. Both is used in my testing environment.

**Comment by dotansimha** [comment]
@kamilkisiela can you please try to help? :)

**Comment by MarcusRiemer** [comment]
It seems like the "pass through constructor" could be added quite trivially to the codegenerator: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/apollo-angular/src/visitor.ts#L246

As far as I can tell adding the exact constructor call that @yannickpschroeder provided shouldn't change existing behavior:

```
constructor(apollo:Apollo.Apollo) {
  super(apollo);
}
```

But this might also be an issue with Angular itself. Typescript enforces that non-default constructors of base classes must be called with the arguments of the base class if the deriving class doesn't implement a constructor. Or in terms of code:

```
class Base {
  constructor(a: string) {
    console.log(`Base::constructor(${a})`);
  }
}

class Derived extends Base {
}
new Derived(); //  error TS2346: Supplied parameters do not match any signature of call target.
new Derived("a"); // Compiles
```

But it seems that Angular does not take the constructor of the base class into account when resolving the dependently injected arguments. It does really puzzle me though why this surfaces only during testing.

**Comment by MarcusRiemer** [comment]
I briefly tried to find out whether the [Angular documentation has anything to say about dependency injection and it says](https://angular.io/guide/dependency-injection-in-action#inject-into-a-derived-class): 

> If the base component has injected dependencies, you must re-provide and re-inject them in the derived class and then pass them down to the base class through the constructor.

So the workaround provided by @yannickpschroeder seems to be the canonically correct solution.

**Comment by kamilkisiela** [comment]
@MarcusRiemer  @yannickpschroeder #4508 Could you confirm it works?

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-apollo-angular@2.0.0`.

**Comment by Justinidlerz** [comment]
This feature interrupted my project, coz I overwrite the basic Apollo service and add another DI service, and it will rewrite my injected service to undefined.

I setting the config:
```yml
      apolloAngularPackage: './custom.service'
```

custom.service.ts
```typescript
import * as Apollo from 'apollo-angular';
import {Injectable} from '@angular/core';
import {
  EmptyObject,
  QueryOptionsAlone,
  WatchQueryOptionsAlone,
} from 'apollo-angular/types';
import {QueryRef} from 'apollo-angular';
import {Observable} from 'rxjs';
import {ApolloQueryResult} from '@apollo/client/core';
import {tap} from 'rxjs/operators';
import {NzMessageService} from 'ng-zorro-antd/message';

export * from 'apollo-angular';

@Injectable()
export class Query<T = {}, V = EmptyObject> extends Apollo.Query<T, V> {
  constructor(
    protected apollo: Apollo.Apollo,
    protected message: NzMessageService
  ) {
    super(apollo);

    console.log(this.message); // output is undefined 
  }

  public watch(
    variables?: V,
    options?: WatchQueryOptionsAlone<V>
  ): QueryRef<T, V> {
    const watcher = super.watch(variables, options);

    watcher.valueChanges = watcher.valueChanges.pipe(
      tap(null, (err) => {
        this.message.error(err.message);
      })
    );

    return watcher;
  }

  public fetch(
    variables?: V,
    options?: QueryOptionsAlone<V>
  ): Observable<ApolloQueryResult<T>> {
    return super.fetch(variables, options);
  }
}


```
