### ISSUE TITLE
all input types & enums are generated when specifying -c --skip-schema

### ISSUE THREAD

**Issue by polco** [dotansimha/graphql-code-generator#438]
I think the `input` should also be omitted when specifying the skip schema parameter ? :)
```
input MyQueryInput {
   ...
}
```

**Comment by dotansimha** [comment]
At the moment, enums and input types are generated anyway, because documents are using them and not just the schema. 
@polco , do you have a use can where we need to omit input types?

**Comment by polco** [comment]
I realize my issue's name is not correct. So my current project is using the typescript template generator. I separated the queries and mutations in different folders, so i get a different type files generated for each. In both files, all the schema input types are present, no only the one needed by the mutations or by the queries.
So i guess the only thing is that i get unused types generated in both files.

**Comment by FredyC** [comment]
I am with @polco on this. It's not like a big issue, but I am working on the project and there is like 50+ input types and other 20+ enums floating around that are not referenced in any of other types. There are two small-ish issues about that.

 * autocomplete in VSCode and I am getting a bunch of types that are useless
 * looking up something manually in the generated files means getting through the unrelated mess

I am wondering how hard it could be to emit only types that are actually used.

**Comment by dotansimha** [comment]
@FredyC We can't predict the usage of the generated type, but we can minimize the amount of generated output. Any chance you can provide an example for it? @FredyC

**Comment by FredyC** [comment]
I see what might be a confusion point. The main idea is to consider a whole schema, not queries only.
Consider types of fields in the schema that are probably referencing enum types. Also, mutations would be usually referencing input types. Based on this sort of validation, it should be possible to safely mark types, that are unnecessary to keep in the generated files. 

It should be probably opt-in behavior, but honestly, I don't recall a single moment when I would need to use a type of enum or input type without having them somewhere in the schema.

Does this make any sense? :)

**Comment by dotansimha** [comment]
Closing for now. We are going to keep the behaviour as-is, because of the need to input types and enums on client side as well.

**Comment by Nicoowr** [comment]
@dotansimha I don't understand why unused input types are needed on client side, especially for the clients which do not use them?

**Comment by it7760** [comment]
Imagine you are having a mutation in you schema: 
```graphql
mutation add(args: TodoInput): [ToDo]
```
This allows you to call the mutation with an optional input to add a new todo to your list of todos. So how should the generator know, if it has to generate the TodoInput type or not? It must look into your client code to know this. 

What I can imagine, would be a different approach here: Maybe someone can argue for a config flag allowing you to only generate types, used in calls like this:
```graphql
mutation AddTodoMutation($input: TodoInput) { 
  add(args: $input) {
    # some selection
  }
}
```
so only if an input type is used in a named query + defined variables, it should be generated into interfaces, but this then of course also means, if someone is then only using the mutation without naming + variable definition, someone will not have type for that, but hopefully that someone is then aware of the config flag. 

Sorry for bumping this quiet old topic, but I kind of like the approach of looking only at the named queries. At least on our end we are naming all of our queries on all of our projects. So I would strongly like the possibility to have a config flag as described.
