### ISSUE TITLE
Failed to load schema

### ISSUE THREAD

**Issue by greenteamer** [dotansimha/graphql-code-generator#4381]
I've faced with issue when I can’t load schema from our graphql server.
In the same time I can work with online playground without any problem.

<img width="427" alt="Screen Shot 2020-07-16 at 19 58 57" src="https://user-images.githubusercontent.com/3823447/87694144-e214de00-c79e-11ea-90a9-ad486017c89a.png">

this is my config:
```overwrite: true
schema:
  - https://myserver.com/reportings/graphql:
      headers:
        authorization: 'api-key blablabla'
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
```

Also I se this message in the trace.
`Could not obtain introspection result, received: "Object reference not set to an instance of an object."`

looks like the problem with graphql server, because I have no problem with another playground with the same config file... but I still don't understand how to debug it

is there a way to emulate fetch schema by cUrl for example?

**Comment by tonypee** [comment]
Im having troubles reading my schema too. Try downloading it to a .json out of the graphql window 
![image](https://user-images.githubusercontent.com/3086901/88165180-a2476e00-cc58-11ea-99e2-511682df99df.png)

Despite that, i still cant get mine to read. it says it isnt valid... hmm

**Comment by greenteamer** [comment]
@tonypee I can download the schema from playground interface without problem. But loading from GraphQL-codegen still falling down.

**Comment by danielrearden** [comment]
@greenteamer Sorry for the late reply. This does appear to be a server-side issue in your case but it's not really clear what exactly has gone wrong since that's a pretty generic message we're getting from the server.

FWIW, here's the curl equivalent of the introspection query codegen is sending:

```
curl -X POST -H "Content-Type: application/json" -H "authorization: api-key" --data '{"query": "query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }"}' "https://myserver.com/reportings/graphql"
```

**Comment by danielrearden** [comment]
@tonypee Please share your config if you still need help debugging.

**Comment by tonypee** [comment]
Ill make a seperate ticket - 2 mins!

**Comment by dotansimha** [comment]
@greenteamer any update? :)

**Comment by greenteamer** [comment]
@danielrearden thank's a lot! I will try soon!

**Comment by dotansimha** [comment]
Closing for now. @greenteamer if you are still having issues, let me know and I'll reopen.

**Comment by UlisesAC4** [comment]
Greetings I am having problems with downloading too. My server does not check for the form `authorization: prefix token`, it just reads `jwt: token` and I am not able to make it work with config as it is below. Thank you.

```
overwrite: true
schema: 
  - "my_endpoint":
    headers:
      jwt: my_token
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"
      - "typescript-graphql-files-modules"
```

**Comment by dotansimha** [comment]
@UlisesAC4 you have an indentation issue with your YAML:
```
overwrite: true
schema: 
  - "my_endpoint":
        headers:
          jwt: my_token
```

**Comment by UlisesAC4** [comment]
@dotansimha thank you for this, now everything is fine!
