### ISSUE TITLE
Generate types for each node or edge in the query as a separate interface

### ISSUE THREAD

**Issue by aniravi24** [dotansimha/graphql-code-generator#4390]
**Is your feature request related to a problem? Please describe.**

Apollo's codegen tools allow you to generate query types that look like this. This whole file was a single GraphQL query. Each part of the tree is separated into its own interface.
![image](https://user-images.githubusercontent.com/5902976/87863490-27a4e880-c910-11ea-82d8-f477cca7f4fe.png)

**Describe the solution you'd like**

I would like to be able to do this in graphql-code-generator. I've looked everywhere but I can't figure out how to make it separate the specific object and properties into separate interfaces.

**Describe alternatives you've considered**

Apollo codegen works this way already. I'd like to be able to generate my types like the above picture.
**Additional context**

This is what the type looks like with graphql-code-generator and my settings. I want the below to look like the above.
```
export type GetFaqsQuery = {
  __typename?: 'Query';
  faqs: Maybe<{
    __typename?: 'FaqsConnection';
    nodes: Array<{
      __typename?: 'Faq';
      id: string;
      answer: string;
      question: string;
    }>;
  }>;
};
```

**Comment by dotansimha** [comment]
Duplicate. We are not going to support this use case. You can find solutions and workarounds here: https://github.com/dotansimha/graphql-code-generator/issues/2735#issuecomment-541289099

**Comment by aniravi24** [comment]
Got it, thanks!
