### ISSUE TITLE
Unused varibles in GraphQL query/mutation should report error

### ISSUE THREAD

**Issue by tomasherout** [dotansimha/graphql-code-generator#4402]
According to GraphQL specification unused variables means invalid query (mutation): https://spec.graphql.org/June2018/#sec-All-Variables-Used

Currently, this produce error in runtime, not in code generation time.

Solution probably should be resolved in plugin https://graphql-code-generator.com/docs/plugins/typescript-operations

For example, code generation with apollo tool report this like error.

Thanks a lot

**Comment by ardatan** [comment]
PRs are welcome!

**Comment by danielrearden** [comment]
I'm not sure if it's codegen's job to do validation like that. That sounds more like something that should be handled by a library like graphql-inspector.

**Comment by tomasherout** [comment]
Other mistakes like missing variable, duplicate variable are detected (I don't really know by which part of project).

**Comment by ardatan** [comment]
I agree with @danielrearden . This kind of validation seems out of codegen's scope. You should already make sure your operations are good before code generation step by yourself using a tool like graphql inspector.

**Comment by dotansimha** [comment]
I agree with @ardatan here. Closing.
