### ISSUE TITLE
[typescript-react-apollo] @apollo/client/index has no exported member MutationComponentOptions

### ISSUE THREAD

**Issue by justono1** [dotansimha/graphql-code-generator#4466]
**Describe the bug**
When running `graphql-codegen` there is no error produced in the console. The bug appears when I implement one of the MutationHooks that are supplied by the generated code  from the `typescript-react-apollo` plugin.

I am migrating my codebase over to use Apollo Client 3.0. Prior I was using Apollo 2.6 and Graphql Codegen 1.11.2 and this mutation was being output correctly.

**To Reproduce**
Create a Mutation query and run it through graphql-codegen with the typescript react-apollo-plugin then implement the useNameMutation() hook in react. Once building the project the error will appear. Also inside the actual generated file you can observe the typescript errors

[Screenshot of the error in my generated code](https://www.dropbox.com/s/27acgu57atd6fyo/Screenshot%202020-07-31%2012.29.36.png?dl=0)

[Screenshot of the error in my console](https://www.dropbox.com/s/cccafqtn2x66f0y/Screenshot%202020-07-31%2013.08.52.png?dl=0)

1. My GraphQL schema:

This is a confidential project I can attempt to share an obfuscated schema if this will help in debugging.

2. My GraphQL operations:

Implementing a hook from typescript-react-apollo following this mutation

*src/api/createCompany.ts*
```
import { gql } from '@apollo/client';

export const QUERY_CREATE_COMPANY = gql`
	mutation CreateCompany($company: CreateCompanyInput!) {
		create_Company(company: $company) {
			id
			name
		}
	}
`;

```

3. My `codegen.yml` config file:

```
overwrite: true
schema: 'schema.json'
documents: 'src/api/**/*.ts'
generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      reactApolloVersion: 3
      withHooks: true

```

**Expected behavior**
Run codegen on my codebases graphql queries and generate typed react hooks to use in my react application.

**Environment:**

- OS:  MacOS 10.15.5
Below is also relevant packages for my environment The download types scripts goes and gets the schema from a Hasura instance.
```
{
	"scripts": {
		"download-types": "apollo schema:download --config=apollo.config.js ",
		"generate-typed-queries-from-downloaded-types": "graphql-codegen --config codegen.yml",
		"generate-typed-queries": "yarn download-types && yarn generate-typed-queries-from-downloaded-types",
		"gtq": "yarn generate-typed-queries"
	},
	"dependencies": {
		"@apollo/client": "^3.1.1",
		"graphql": "^15.3.0",
		"react": "^16.12.0",
		"react-scripts": "3.3.0",
		"typescript": "~3.7.2",
	},
	"devDependencies": {
		"@graphql-codegen/add": "^1.17.6",
		"@graphql-codegen/cli": "^1.17.6",
		"@graphql-codegen/introspection": "^1.17.6",
		"@graphql-codegen/typescript": "^1.17.6",
		"@graphql-codegen/typescript-operations": "^1.17.6",
		"@graphql-codegen/typescript-react-apollo": "^1.17.6"
	}
}

```
- NodeJS: v13.3.0

The graphql mutation I listed above in the graphql operations are actually configured as Hasura actions. I don't feel like this should be an issue since its just all graphql in the end but I should at least mention that.

**Comment by RoyBkker** [comment]
Try adding 
            withComponent: false
            withHOC: false
in config

**Comment by dotansimha** [comment]
I think @RoyBkker is right :)
We are also working on stabilising codegen output to support apollo-client 3 without any configuration.

**Comment by justono1** [comment]
@RoyBkker @dotansimha this did work!

I appreciate both of your responses! I look forward to future updates for Apollo Client 3 keep up the great work on this project!

**Comment by dotansimha** [comment]
Progress for migration this plugin to AC3 by default: https://github.com/dotansimha/graphql-code-generator/pull/4487

**Comment by dotansimha** [comment]
Fixed in v2 of this plugin.
