### ISSUE TITLE
`Apollo.gql` import of react apollo v2 plugin not picked up by prettier

### ISSUE THREAD

**Issue by SimenB** [dotansimha/graphql-code-generator#4500]
**Describe the bug**
V2 outputs `Apollo.gql` instead of just `gql`, which means prettier no longer formats the snippets.

**To Reproduce**

I don't believe a repro is necessary, but I can put one together if you need one

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
```

**Expected behavior**

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**

-->

**Comment by dotansimha** [comment]
@SimenB can you try to alias it and use `gql` as is? (`const gql = Apollo.gql`) I think `prettier` is hardcoded for `qql` tag, without namespaces. 
I can add the aliasing to the generated output. The reason it's there is because we wanted to unify all imports from `@apollo/client` to a single one.

**Comment by SimenB** [comment]
Yeah, aliasing should work out 👍

**Comment by dotansimha** [comment]
@SimenB I gave it a try by doing `const gql = Apollo.gql;` and use the `gql` tag as-is. IDE seems to respond good to that change, I guess prettier will be fine as well.

Can you please try the alpha? `@graphql-codegen/typescript-react-apollo@2.0.2-alpha-48409861.0`

**Comment by SimenB** [comment]
The alpha generates properly prettified code for me, thanks!

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-react-apollo@2.0.4`

**Comment by SimenB** [comment]
Hmm, seems this aliasing breaks `babel-plugin-graphql-tag`: https://github.com/gajus/babel-plugin-graphql-tag/blob/e76450c2cf667ebdac85dc34a0dc5d3fce64ec8c/README.md#known-issues

I think doing `import {gql} from '@apollo/client' would make both prettier and the babel plugin happy, not sure how feasible that is, tho

**Comment by dotansimha** [comment]
@SimenB In latest version (2.0.6) I removed aliasing and went back to use the imports we had before (also, it was breaking presets...)
