### ISSUE TITLE
typescript-react-apollo plugin generating incorrect imports for apollo client 3

### ISSUE THREAD

**Issue by jejacobsendev** [dotansimha/graphql-code-generator#4504]
Using the typescript-react-apollo plugin generates imports that do not work with apollo client 3. I have to use config like so
```yml
apolloReactCommonImportFrom: "@apollo/client"
apolloReactHooksImportFrom: "@apollo/client"
```
to force it to use the correct imports.

Also, the docs say that withComponent and withHOC have a default value of false and that withHooks has a default value of true.
However, these are all opposite. Of course, I can manually change all of these to make it work. But is this supposed to be intended? Are the docs just inconsistent with what actually happens, or have I missed something?

dependencies:
"@apollo/client": "^3.1.2",
"@graphql-codegen/cli": "1.17.7",
"@graphql-codegen/typescript": "1.17.7",
"@graphql-codegen/typescript-operations": "1.17.7",
"@graphql-codegen/typescript-react-apollo": "1.17.7"

**Comment by jejacobsendev** [comment]
Nevermind. I see that I need to just upgrade to typescript-react-apollo@2.0.0.

**Comment by dotansimha** [comment]
@jejacobsendev please use `@graphql-codegen/typescript-react-apollo@2.0.4`. Default configuration (without any override) should be 100% compatible with Apollo Client v3 and have the output you mentioned (only hooks, no component, no hoc).
