### ISSUE TITLE
Migration from react-apollo to typed-document-node

### ISSUE THREAD

**Issue by CarsonF** [dotansimha/graphql-code-generator#4511]
**Is your feature request related to a problem? Please describe.**
Looking at migrating from react-apollo plugin to typed-document-node (which looks awesome).
These plugins are not compatible with each other because both generate gql documents.
Thus I cannot gracefully migrate my codebase from the apollo generated hooks to the generic hook with document.

**Describe the solution you'd like**
Some way they could work together ha.
Maybe this is an option in react-apollo to not generate documents?
Really I'd just want react-apollo to generate the hooks only and leave the documents to the other plugin.

**Describe alternatives you've considered**
Migrating the codebase in one fell swoop. I'd like to not, but if it comes down to it I might.

**Additional context**

Thanks for all your work on this tool. It's amazing ❤️

**Comment by dotansimha** [comment]
Thanks @CarsonF ! 
I will look into it. I think we can use the new internal context we recently added, to avoid generating documents multiple times.

**Comment by dotansimha** [comment]
Currently tracking this issue in: https://github.com/dotansimha/graphql-code-generator/issues/5333
