### ISSUE TITLE
Please, can you add the possibility for providing SDKClass in ngModule.

### ISSUE THREAD

**Issue by Ash-kosakyan** [dotansimha/graphql-code-generator#4513]
https://github.com/dotansimha/graphql-code-generator/blob/b9113dafee1874c881e8e140b11406c2b8c633fa/packages/plugins/typescript/apollo-angular/src/visitor.ts#L309

**Comment by dotansimha** [comment]
@kamilkisiela is it something we can do before releasing the new version?

**Comment by kamilkisiela** [comment]
We can do that

**Comment by kamilkisiela** [comment]
#4507 done <3

**Comment by Ash-kosakyan** [comment]
Hey, now everyone is happy ))))

**Comment by dotansimha** [comment]
Fixed in `Fixed in `@graphql-codegen/typescript-apollo-angular@2.0.0`.`
