### ISSUE TITLE
Your Pull Requests includes issues

### ISSUE THREAD

**Issue by Gsandec** [dotansimha/graphql-code-generator#4523]
**Pull Requests Issues**
I've forked your repo (congrats on your project) and implemented a code review tool to check a few pull requests and found a couple issues in seconds.

This maybe useful for your project. Free for open source!
(mind that you and your contributors can see comments on code reviews directly inside your GitHub Pull requests!)

Disclaimer: I work at [Codacy](https://www.codacy.com) and I'm trying to get closer to this amazing open source community!

If you find this useful, would you be kind enough to use our Codacy Badge on your repo? Let me know if you need any help.

Cool Repos that are using Codacy:
* https://github.com/cabaletta/baritone
* https://github.com/faruktoptas/FancyShowCaseView
* https://github.com/nlohmann/json
* https://github.com/igorwojda/android-showcase
* https://github.com/alfianandaa/projectbish

![graphql-code-gen-issue1](https://user-images.githubusercontent.com/67981183/89440504-9de48000-d743-11ea-8c94-26797ebcb45f.png)
<img width="1416" alt="graphql-code-gen-issue2" src="https://user-images.githubusercontent.com/67981183/89440513-a0df7080-d743-11ea-869e-84a2f1cec7a3.png">
<img width="1413" alt="graphql-code-gen-issue3" src="https://user-images.githubusercontent.com/67981183/89440517-a2109d80-d743-11ea-941b-e54e17fe74c2.png">

**Comment by dotansimha** [comment]
Thank you @Gsandec ! We'll give a try. 
Btw, no need to scan `dev-tests`, it's just development tests for checking the output of plugins. ;)
