### ISSUE TITLE
Single fragment files are generated without a `gql` import (problematic when combined with `near-operations-file`)

### ISSUE THREAD

**Issue by nihalgonsalves** [dotansimha/graphql-code-generator#4532]
**Describe the bug**
 

Generating something based on a simple fragment file, for example:

```graphql
fragment Foo on User {
  id
}
```

... produces an invalid [fragment file](https://codesandbox.io/s/sleepy-wilbur-x35uh?file=/fragment.gen.ts) without a `gql` import:

```ts
import * as Types from './types';


export type FooFragment = (
  { __typename?: 'User' }
  & Pick<Types.User, 'id'>
);

export const FooFragmentDoc = gql`
    fragment Foo on User {
  id
}
    `;
```

This is not normally a problem, since everything is output into one final TS file. However, with the `near-operations-file` preset this becomes problematic as you tend to have a `FooFragment.graphql` file that gets converted to its own TypeScript file.

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

Everything is in the sandbox at https://codesandbox.io/s/sleepy-wilbur-x35uh

1. My GraphQL schema:

   https://codesandbox.io/s/sleepy-wilbur-x35uh?file=/schema.graphql

2. My GraphQL operations:

   https://codesandbox.io/s/sleepy-wilbur-x35uh?file=/fragment.graphql

3. My `codegen.yml` config file:

   https://codesandbox.io/s/sleepy-wilbur-x35uh?file=/codegen.yml

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

The `gql` import is added for fragment-only files

**Environment:**

https://codesandbox.io/s/sleepy-wilbur-x35uh?file=/package.json

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by codefo** [comment]
Faced with the same problem, as a workaround I suggest moving your fragment to another `.graphql` file with `query` or `mutation`, it helped me.

**Comment by dotansimha** [comment]
Thank, I'm on it now :)

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/4554 
@adam1658 can you please try the alpha versions from that PR?

**Comment by nihalgonsalves** [comment]
@dotansimha tried it in the sandbox and it seems to work with `@graphql-codegen/typescript-react-apollo@2.0.6-alpha-5f1ac702.0`:

https://codesandbox.io/s/sleepy-wilbur-x35uh?file=/fragment.gen.ts

**Comment by adam1658** [comment]
@dotansimha I've had a bit of a look and tried `@graphql-codegen/typescript-react-apollo@2.0.6-alpha-5f1ac702.0` - it doesn't appear to break anything for me, though I use `documentMode: documentNode`.

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-react-apollo@2.0.6`
