### ISSUE TITLE
[typed-document-node] Duplicated fragments in case of nested fragments

### ISSUE THREAD

**Issue by Amareis** [dotansimha/graphql-code-generator#4573]
1. https://graphql-code-generator.com/
2. TypedDocumentNode template
2. Use this query:
```
query chats {
    myChats {
        id 
        users {
            ...UserFields
        }
        messages {
            ...MessageFields
        }
    }
}

fragment UserFields on User {
  id
  username
  role
}

fragment MessageFields on ChatMessage {
    id
    user {
        ...UserFields
    }
}
```
4. In final code `ChatsDocument` definitions (after rest operator expanding) will includes `UserFieldsFragmentDoc` definition twice. 

It's not good, since after `print` it via `graphql` package there is duplicated fragments and, i.e., apollo-server will throw an error on such queries.

Currently I use home-made dedupe function to work-around this:
```ts
import * as actions from '../api/actions'
import * as subs from '../api/subs'

function dedupe(ds: DocumentNode[]) {
    for (let d of ds) {
        const names: string[] = []
        const res = []
        for (let def of d.definitions) {
            let name: string | undefined = (def as any).name?.value
            if (name && !names.includes(name)) {
                res.push(def)
                names.push(name)
            }
        }
        (d as any).definitions = res
    }
}

dedupe(Object.values(actions))
dedupe(Object.values(subs))
```

**Comment by dotansimha** [comment]
Tracking here:  https://github.com/dotansimha/graphql-code-generator/issues/4684 (same issue, caused by `documentMode: DocumentMode.documentNodeImportFragments` configuration)
