### ISSUE TITLE
Generated useQuery hook throws "Unknown fragment {fragment_name}" when query includes an imported fragment

### ISSUE THREAD

**Issue by amnpoosri** [dotansimha/graphql-code-generator#4576]
**Describe the bug**
Generated useQuery hook throws `GraphQL error: "Unknown fragment {fragment_name}"` when query includes an imported fragment.

**To Reproduce**
The issue can be reproduced from below repo
https://github.com/amnpoosri/codegen-fragment-pokemen-issue

**Environment**
- OS: macOS Catalina 10.15.5
- @graphql-codegen/1.17.8:
- NodeJS: v14.8.0

Additional context

**Comment by dotansimha** [comment]
@amnpoosri it seems like `graphql-pokemon` api is down, so I'm not really able to use that reproduction. 
I tried to print the `DocumentNode` generated by the codegen, and used by the hooks (`GetPokemonDocument`), and it seems valid:

![image](https://user-images.githubusercontent.com/3680083/90329311-6b8d1b00-dfac-11ea-8711-6dfa4be854d1.png)

**Comment by amnpoosri** [comment]
@dotansimha I have updated apollo client endpoint to use weather API. The problem is the generated useGetCityByNameQuery() hook is throwing unknown fragment error.
