### ISSUE TITLE
Code generation fails when using the "--config" argument with a ".js" file

### ISSUE THREAD

**Issue by DarkLite1** [dotansimha/graphql-code-generator#4600]
**Describe the bug**

When I run the code generator with just `graphql-codegen` and the file is named `codegen.js` it works fine. But when I  run `graphql-codegen --config graphql-codegen.js` when the file is named `graphql-codegen.js` it throws the error below:

```
$ graphql-codegen --config graphql-codegen.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```javascript
// codegen.js
module.exports = {
  overwrite: true,
  schema: 'http://localhost:5000/graphql',
  documents: 'src/**/*.graphql',
  hooks: {
    afterAllFileWrite: ['prettier --write'],
  },
  generates: {
    'src/graphql/generated/operations.ts': {
      plugins: [
        {
          add: {
            content: '/* eslint-disable */',
          },
        },
        'typescript',
        'typescript-operations',
        'typescript-vue-apollo',
      ],
    },
    'src/graphql/generated/fragment-matcher.ts': ['fragment-matcher'],
    './graphql.schema.json': {
      plugins: ['introspection'],
    },
  },
}
```

**Comment by charlypoly** [comment]
Hi @DarkLite1!

I could not reproduce the error with a config similar to yours.
Could you please try again with the `--debug` CLI flags and by updating all your `@graphql-codegen/*` dependencies? 🙏🏼 

Also, could you please provide a reproduction on GitHub/Codesandbox?

**Comment by DarkLite1** [comment]
Thx for getting back to me but this issue is almost 2 years old. Currently not writing webcode anymore. So feel free to close this one if you can't replicate the issue anymore.

**Comment by charlypoly** [comment]
@DarkLite1, I understand, sorry for the delay!
