### ISSUE TITLE
Support multiple .env files.

### ISSUE THREAD

**Issue by jake-leland** [dotansimha/graphql-code-generator#4635]
**Is your feature request related to a problem? Please describe.**
`graphql-codegen -r dotenv/config` enables environment variables within `codegen.yml`. For example:
```
schema: ${GRAPHQL_ENDPOINT}
generates:
  ...
```
This is great. However, it is common for frameworks to utilize multiple environment files, such as `.env` and `.env.local` (see [React](https://create-react-app.dev/docs/adding-custom-environment-variables/) and [Vue](https://cli.vuejs.org/guide/mode-and-env.html#modes)). Unfortunately, codegen only reads from the `.env` file.

**Describe the solution you'd like**
Support `.env.local`, `.env.[mode]`, and `.env.[mode].local`.
For example, if `GRAPHQL_ENDPOINT` is defined in both `.env` and `.env.local`, the local version should be loaded into `codegen.yml`.

**Describe alternatives you've considered**
Prebuild scripts to merge all environment files into a single `.env`, but I'd like to avoid this.

**Additional context**
Thanks!

**Comment by fubhy** [comment]
You could just use `dotenv -c development -- graphql-codegen`

**Comment by cantyjeffrey** [comment]
@jake-leland This worked for me..

`package.json`:

```
{
  ...
  "scripts": {
    ...
    "generate": "DOTENV_CONFIG_PATH=./.env.local graphql-codegen -r dotenv/config --config codegen.js",
    ...
  }
}
```

**Comment by dotansimha** [comment]
As suggested by @fubhy and @cantyjeffrey , you can either use `DOTENV_CONFIG_PATH` or wrap the execution of `graphql-codegen` with `dotenv` cli.

**Comment by KoltonG** [comment]
This is not directly related to solving the issue of using a .env file, but if you wanted to use inline environment variables via the npm script, I found the following solution to work!

``` bash
# package.json.scripts
GRAPHQL_URL=http://localhost:4000/graphql graphql-codegen --config codegen-graphql.js
```

```js
// codegen-graphql.js
module.exports = {
  ...,
  schema: process.env.GRAPHQL_URL,
  ...
};
```
