### ISSUE TITLE
[typescript-resolvers] Incorrect top level type definition

### ISSUE THREAD

**Issue by andyrichardson** [dotansimha/graphql-code-generator#4655]
## About

Top level type resolvers aren't fully correct.

[sandbox](https://codesandbox.io/s/modest-bassi-fm5xq?file=/types.ts:4621-5134)

## Reproduction

Create a schema with a type

```gql
type User {
  id: ID!
  name: String!
}
```

Run codegen with the `typescript-resolvers` plugin

## Expected result

The type definition for the top level type resolver is as follows

```ts
export type Resolvers<ContextType = any> = {
  Query?: QueryResolvers<ContextType>;
  User?: Resolver<Resolver<ResolversTypes['User'], ParentType, ContextType>> | UserResolvers<ContextType>;
};
``` 

## Actual result

Type definitions do not allow top level resolver (leading to an incorrect error on the following example)

```ts
const resolvers: Resolvers = {
  User: () => ({
    id: "1",
    name: "Test"
  })
}
```

**Comment by ardatan** [comment]
What is "top level type resolver"? What is the use case of it? Could you provide a working example because I've never seen this before.
```ts
const resolvers: Resolvers = {
  User: () => ({
    id: "1",
    name: "Test"
  })
}
```

**Comment by andyrichardson** [comment]
Might just be a bad assumption on my part - I thought I had managed to do that in the past.

Use case would be when mapping relationships in combination with the _mappers_ functionality.

```tsx
// Some example response
{
  orders: [
    { id: 1234, name: "Codegen book", user: 1234 }
  ]
};

const resolvers: Resolvers = {
  User: (root) => ({
    if (typeof root === "string") {
      return getUser(root);
    }

    return root;
  });
}
```
