### ISSUE TITLE
Generate and verify `@apollo/client@3` `keyFields` configuration

### ISSUE THREAD

**Issue by SimenB** [dotansimha/graphql-code-generator#4700]
`@apollo/client@3` comes with a new config option called `typePolicies` passed to the cache's constructor, which can be used (amongst many different awesome things) to specify `keyFields` for each GraphQL type in your schema, so that the cache knows how to normalize the entries properly.

@benjamn talks about it in this great talk: https://youtu.be/n_j8QckQN5I, and specifically what I'm requesting is the code generation mentioned briefly here: https://youtu.be/n_j8QckQN5I?t=1347.

My hope for this potential new codegen plugin is:

- there would have some sort of directive (`@id`? `@keyField`?) that is applied to types in the schema
- the plugin would generate the config object with `keyFields` (and possibly other stuff in the future) defined, which would be splatted into the cache constructor
- throw an error if we request a type in. a query without specifying all the `keyFields` (i.e. fields with the `@id` directive). This last one would be _really_ awesome as we'd know when we define queries that we request all the relevant fields to properly normalize the cache, avoiding runtime errors/warnings

Docs: https://www.apollographql.com/docs/react/caching/cache-configuration/#generating-unique-identifiers

/cc @hwillson @benjamn would love your thoughts on this 🙂

**Comment by dotansimha** [comment]
That could be great! Thank you @SimenB ! 
Moving to Discussions (we track new plugins requests there).
