### ISSUE TITLE
Invalid graphql file doesn’t throw an error

### ISSUE THREAD

**Issue by lensbart** [dotansimha/graphql-code-generator#4701]
Hello,

Thanks for making this tool. Really useful!!!

I had a couple of mutations that, as a result of some incomplete refactoring, didn’t have a closing bracket (`}`). For example:

```graphql
mutation CreateExample($input: CreateExampleInput!) {
	createExample(input: $input) {
		example {
			id
			color
			someField {
				id
				etc {
					id
				}
			}
		}
	}
```

As you can see, the closing bracket is missing. Normally, the generated types file would contain a `CreateExampleMutation` type via the `typescript-operations` plugin. This type was missing, and I figured out that this was due to a syntax error in the graphql file, but I think an error should have been thrown instead. (In any case, it’s not a severe issue.)

**Comment by dotansimha** [comment]
@lensbart can you please share a reproduction in a sandbox?

**Comment by dotansimha** [comment]
Closing. @lensbart  if this is still relevant, feel free to ping me.
