### ISSUE TITLE
Graphql-import no longer supported in > v1.14.0?

### ISSUE THREAD

**Issue by JesseZomer** [dotansimha/graphql-code-generator#4710]
**Describe the bug**
I have a schema.graphql and use graphql-import (graphql-tools) to divide my schema into multiple files.
In v1.14.0 this works fine, but when I update  to v1.15.0 / v1.17.0 I can no longer generate my files.

**To Reproduce**

https://codesandbox.io/s/bold-bush-ztwm4?file=/schema.graphql

in package.json change:
```
    "@graphql-codegen/add": "1.14.0",
    "@graphql-codegen/cli": "1.14.0",
    "@graphql-codegen/typescript": "1.14.0",
    "@graphql-codegen/typescript-operations": "1.14.0",
```
to 
```
    "@graphql-codegen/add": "1.17.0",
    "@graphql-codegen/cli": "1.17.0",
    "@graphql-codegen/typescript": "1.17.0",
    "@graphql-codegen/typescript-operations": "1.17.0",
```
and `yarn generate` and you get an error, whereas before this worked.
The error you get is:
```
Found 1 error

  ✖ types.ts
    Error: Query root type must be provided.
        at assertValidSchema (/sandbox/node_modules/graphql/type/validate.js:71:11)
```
the Query root type is provided, but it's provided through the `# import Query.*, * from "user.graphql"` import

1. My GraphQL schema:

```graphql
# import Query.*, * from "user.graphql"

scalar Date
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
```

**Expected behavior**
I expect the files to get generated even while using v1.17.0

**Comment by dotansimha** [comment]
@JesseZomer can you please try to upgrade to latest version of those deps? I think this was an issue with the `@graphql-tools` dependency, that was already solved.

**Comment by JesseZomer** [comment]
@dotansimha I'm not actually using those dependency's in the reproduction codesandbox. I'm just creating my schema using that #import syntax style to create the schema. The #import syntax hasn't changed as far as I know.

**Comment by ardatan** [comment]
I don't see any errors with the latest versions;
https://codesandbox.io/s/red-fog-rshky?file=/package.json

**Comment by JesseZomer** [comment]
> I don't see any errors with the latest versions;
> https://codesandbox.io/s/red-fog-rshky?file=/package.json

forking that codesandbox and doing a `yarn generate` gives me the same error as described in the OP

**Comment by ardatan** [comment]
@JesseZomer Oh sorry when I do yarn install, I could reproduce the error. There is a known bug in graphql-import;
The imported types should be used in the parent file for graphql-import if the parent file has other types.
```gql
schema {
  query: Query
}
```
is a good workaround in this case. But you can also remove `scalar Date` from parent file instead. So those two workarounds will solve your issue.

**Comment by JesseZomer** [comment]
@ardatan Thanks for helping me out. While it solved the error message in the reproduction, my real schema file is much larger
```
# import Query.*, Mutation.*, * from "afspraak.graphql"
# import Query.*, Mutation.*, * from "feedback.graphql"
# import Query.*, Mutation.*, * from "jaarbijlage.graphql"
# import Query.*, Mutation.*, * from "leerling.graphql"
# import Query.*, Mutation.*, * from "lesplan-navigatie.graphql"
# import Query.*, Mutation.*, * from "lesplanning.graphql"
# import Query.*, Mutation.*, * from "medewerker.graphql"
# import Query.*, Mutation.*, * from "productboard.graphql"
# import Query.*, Mutation.*, * from "projectgroep.graphql"
# import Query.*, Mutation.*, * from "registratie.graphql"
# import Query.*, Mutation.*, * from "rooster.graphql"
# import Query.*, Mutation.*, * from "shared.graphql"
# import Query.*, Mutation.*, * from "sjabloon.graphql"
# import Query.*, Mutation.*, * from "studiewijzer.graphql"
# import Query.*, Mutation.*, * from "toekenning.graphql"
# import Query.*, Mutation.*, * from "upload.graphql"
# import Query.*, Mutation.*, * from "werkdruk.graphql"
```
and while I removed the scalar types from this parent file and moved them into one of these .graphql files it just comes up with another type it can't find. I am now getting `Couldn't find type Lesgroep in any of the schemas.` while the type is definitely in one of those .graphql files.

If I move the order of these imports, I get a different type.  Maybe it has something to do with this [issue](https://github.com/ardatan/graphql-import/issues/565) ?

**Comment by ardatan** [comment]
You can just use globs like `**/*.graphql` in codegen.yml instead and use this in the project https://www.graphql-tools.com/docs/merge-typedefs#import-everything-from-a-specified-folder .

**Comment by JesseZomer** [comment]
That seems to work, and is a much better solution 🙈 Thank you! 🎉
