### ISSUE TITLE
Cannot remove underscore with transformUnderscore option

### ISSUE THREAD

**Issue by atamano** [dotansimha/graphql-code-generator#4718]
Naming conventions sometimes keep underscores. For example ERROR_202 is converted to Error_202 in pascal case.
I would like to remove the underscore but the `transformUnderscore` option doesn't remove it.

How can I remove underscore ? I want ERROR_202 to be converted to Error202 with the following configuration:

```
namingConvention:
    enumValues: change-case#pascalCase
    transformUnderscore: true
```

**Comment by drj17** [comment]
Same issue.  What's odd is that the generated mutations reference the type with the underscore removed, but the generated type has the underscore still present.

**Comment by dotansimha** [comment]
@drj17 @atamano please provide a reproduction for that issue.

**Comment by atamano** [comment]
@dotansimha here is a reproduction of this issue: https://codesandbox.io/s/epic-violet-fb043?file=/types.ts
Underscores are not removed
