### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by gbiryukov** [dotansimha/graphql-code-generator#4729]
**Is your feature request related to a problem? Please describe.**

Updating `@graphql-codegen/*` is a very painful process in terms oа reviewing the changelog and realize what kind of adjustments the user should/can do. Github releases page contains huge unstructured list on small releases for each individual package which makes it impossible to review the whole list of changes in certain version.

**Describe the solution you'd like**

It would be awesome to have changelog in the repository or at least to reconsider structure of github releases page and make something similar to [babel](https://github.com/babel/babel/blob/main/CHANGELOG.md) releases where all changes grouped by version and contains information about which packages was updated in particular release and what was changed

**Describe alternatives you've considered**
Just wandering maybe this information already available in your blog or `changesets` have a feature to generate a summary of certain version across all monorepo packages?

**Additional context**
Trying to update codegen from 1.13 to 1.17 and realized that I have to review hundreds of weakly structured release pages 😃

**Comment by gbiryukov** [comment]
Realized that `@graphql-codegen/*` packages use independent versioning scheme and each separate package recently received own changelog.

Closing this

**Comment by dotansimha** [comment]
@gbiryukov We recently moved to manage versioning using `changeset` , so now each package has it's own CHANGELOG :)
