### ISSUE TITLE
GraphQL Code Generator freezes on latest versions of "webpack-dev-server"

### ISSUE THREAD

**Issue by mastrzyz** [dotansimha/graphql-code-generator#4760]
**Describe the bug**
 

The GraphQL Code Generator plugin is freezing execution when we try to upgrade to latest version of dev-server.

**To Reproduce**

Upgrade to     "webpack-dev-server": "^3.11.0",

**Expected behavior**
Able to correctly run graph ql code gen

**Environment:**

- OS: OSX
- `@graphql-codegen/...`: 1.17.8
- NodeJS: 12.14.1

**Additional context**

**Comment by dotansimha** [comment]
Hi @mastrzyz , we discussed this offline, it's was a very specific issue with Webpack setup.
