### ISSUE TITLE
Missing context type for __isTypeOf resolver

### ISSUE THREAD

**Issue by lucassus** [dotansimha/graphql-code-generator#4789]
**Describe the bug**

Generated type for __isTypeOf resolve fn is:

```typescript
export type IsTypeOfResolverFn<T = {}> = (
  obj: T,
  info: GraphQLResolveInfo
) => boolean | Promise<boolean>;
```

...but in reality it should be something like:

```typescript
export type IsTypeOfResolverFn<T = {}, TContext = {}> = (
  obj: T,
  context: TContext
  info: GraphQLResolveInfo
) => boolean | Promise<boolean>;
```

In other words the context is missing.

In order to reproduce this issue you could checkout my project https://github.com/lucassus/bookshelf/blob/4ca61de381a16235f168efa6bd96b8412a71cda6/apps/server/src/graphql/users/resolvers.ts#L40

**Comment by dotansimha** [comment]
thank you @lucassus ! 

 
The  [GraphQL docs](https://graphql.org/graphql-js/type/#graphqlobjecttype) are probably outdated, it's defined there as:
```
  isTypeOf?: (value: any, info?: GraphQLResolveInfo) => boolean;
```

While the real signature is defined this way in code:
https://github.com/graphql/graphql-js/blob/d6e760cf7060217bd25fa934bd104ff2400aad96/src/type/definition.js#L937-L941

Fixed it in: https://github.com/dotansimha/graphql-code-generator/pull/4808

fyi @IvanGoncharov

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-resolvers@1.17.10`

**Comment by lucassus** [comment]
Awesome! Thank you 🙏
