### ISSUE TITLE
Override wrong graphql types automatically

### ISSUE THREAD

**Issue by BjoernRave** [dotansimha/graphql-code-generator#4797]
I would like to be able to override my types I have defined in my queries with the right ones.

When trying to generate types and a type in a gql tag is wrong I get an error like this one:
```
GraphQLDocumentError: Variable "$name" of type "StringFieldUpdateOperationsInput!" used in position expecting type "String".
```

I would like to pass a flag like `--override` so that graphql-code-generator just automatically replaces those with the right, expected one

**Comment by ardatan** [comment]
Could you share a reproduction on CodeSandbox?

**Comment by dotansimha** [comment]
@BjoernRave We aim not to do manipulations on the GraphQL schema or operations. 
If you need to manipulate your schema or operations, you can use [custom schema loader](https://graphql-code-generator.com/docs/getting-started/schema-field#custom-schema-loader) or [custom documents loader](https://graphql-code-generator.com/docs/getting-started/documents-field#custom-document-loader)

**Comment by BjoernRave** [comment]
Okay, I will look into that, but I think a plugin for this wouldn't hurt anyone and could save a lot of time.
