### ISSUE TITLE
Feature Request: Preserve Namespaces

### ISSUE THREAD

**Issue by daniel-nagy** [dotansimha/graphql-code-generator#481]
I would like the option to preserve document namespaces. This would allow documents with the same name to coexist in different namespaces.

I think this would require changes to the **codegen-core** package. Maybe adding a `namespace` property to the `AstNode` type.

Given:

```typescript
export namespace FooComponent {
  export const getBazQuery = gql`
    query GetBaz($id: ID!) {
      baz(id: $id) {
        id
      }
    }
  `;
}

export namespace BarComponent {
  export const getBazQuery = gql`
    query GetBaz($id: ID!) {
      baz(id: $id) {
        id
        someOtherProp
      }
    }
  `;
}
```

Would produce:

```typescript
export namespace FooComponent {
  export namespace GetBaz {
    export type Variables = {
      id: string;
    };
    export type Query = {
      __typename?: "Query";
      baz: Baz;
    };
    export type Baz = {
      __typename?: "Baz";
      id: string;
    }
  }
}

export namespace BarComponent {
  export namespace GetBaz {
    export type Variables = {
      id: string;
    };
    export type Query = {
      __typename?: "Query";
      baz: Baz;
    };
    export type Baz = {
      __typename?: "Baz";
      id: string;
      someOtherProp: string;
    }
  }
}
```

**Comment by dotansimha** [comment]
@daniel-nagy 
I think it requires us to read the file (with the `gql` tag) as code file (AST), and not as string, so it might be a bit difficult to address at the moment.
We are accepting PRs, so if you want to try to implement it - you're welcome :)

**Comment by dotansimha** [comment]
@daniel-nagy 
We are trying to avoid `namespace`s at the moment, since they are not supported in Babel 7 TypeScript plugin.
