### ISSUE TITLE
Use non-polling for watch mode by default

### ISSUE THREAD

**Issue by mintchkin** [dotansimha/graphql-code-generator#4815]
**Is your feature request related to a problem? Please describe.**

The current implementation of watch mode explicitly enables the [`usePolling` option of chokidar](https://github.com/dotansimha/graphql-code-generator/blob/80a1e6726c42e5a74d2717befb0834d94b515df4/packages/graphql-codegen-cli/src/utils/watcher.ts#L97), which has a much higher resting cpu footprint than the native filesystem watcher. Polling is technically supported in more cases, but the [documentation suggests](https://nodejs.org/api/fs.html#fs_availability) that native file watch is supported on most common platforms.

**Describe the solution you'd like**

Set `usePolling` to false by default (the default value in chokidar anyway), and either gracefully fall back on platforms that don't support it or allow users an option to override it if they need to.

**Describe alternatives you've considered**

You can override the the option in chokidar through [an environment variable named `CHOKIDAR_USEPOLLING`](https://github.com/paulmillr/chokidar#performance), but IMO it would be more ideal to optimize for the common case and potentially advertise that option to users who need polling for some reason (or support a more direct way to override it via the cli).

**Comment by dotansimha** [comment]
Thank you @mintchkin , I think it could help a lot. Any chance you want to create a PR for this? :) I think we might be able to expose some of the chokidar configuration, and allow developers to override it if needed.

**Comment by mintchkin** [comment]
@dotansimha opened #4823, let me know if that's in line with what you imagined

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/cli@1.18.0`
