### ISSUE TITLE
Namespace imports clashing with Native ESM imports (Vue-Apollo/Vite)

### ISSUE THREAD

**Issue by Drakota** [dotansimha/graphql-code-generator#4816]
**Is your feature request related to a problem? Please describe.**
While trying to make Vue-Apollo plugin work nicely with `vite` & Vue 3, I've runned into an issue with how the generated code handles imports.

Since Native ES modules handles imports differently, those lines causes issues
```ts
import * as VueApolloComposable from '@vue/apollo-composable';
import * as VueCompositionApi from '@vue/composition-api';
```
![image](https://user-images.githubusercontent.com/22665836/94478499-5b6a7d00-01a1-11eb-81c3-7c9da832a08e.png)

[Repo demonstrating the issue](https://github.com/Drakota/vue3-vite-apollo-example)

**Describe the solution you'd like**
It should be something like this instead.
```ts
import VueApolloComposable from '@vue/apollo-composable';
import VueCompositionApi from '@vue/composition-api';
```

**Describe alternatives you've considered**
The `vue-apollo` codegen plugin could either allow to completly disable the imports and use the plugin `add` to manually write imports or a property like `prioritizeDefaultImports` that would just use the default import instead of an namespace import.

I'd be more than happy to offer my help on any implementation to fix this issue. 😀

**Comment by P4sca1** [comment]
`@vue/apollo-composable` and `@vue/composition-api` do not provide default exports so it is correct to use `import * as` imports.

**Comment by dotansimha** [comment]
@P4sca1 thank you for clarifying. Closing.
