### ISSUE TITLE
[WIP] stuck on node-gyp-build when installing @graphql-codegen/cli with 'npm'

### ISSUE THREAD

**Issue by vcheloudiakoff** [dotansimha/graphql-code-generator#4821]
Hi !
I'm working on a rails/graphql server generator and at the same time on a front-end typescript generator (with react).

This morning I wanted to make the installation of @graphql-codegen/cli automatic and I noticed that in this installation there was an infinite loop.

I tested manually in a new repository the installation of this package, and I have an infinite loop on this line

```
❰vincent❙~/test-front❱✔≻ npm install --save-dev @graphql-codegen/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> bufferutil@4.0.1 install /Users/vincent/test-front/node_modules/bufferutil
> node-gyp-build
```

When i retry to install this package with `npm install --save-dev @graphql-codegen/cli` it works.

So, i'm working on this issue, and I saw that when I restart the installation, the modified files are only: `package.json` and `package-lock.json`

<img width="510" alt="Screenshot 2020-09-29 at 16 55 57" src="https://user-images.githubusercontent.com/49758463/94575575-af926180-0274-11eb-8c74-e51894dad440.png">

<img width="329" alt="Screenshot 2020-09-29 at 16 55 48" src="https://user-images.githubusercontent.com/49758463/94575589-b3be7f00-0274-11eb-83b1-e2b460250733.png">

I didn't try to restart my computer, but it was to report my bug while waiting to work on it.

My setup:

macOs Catalina version 10.15.7 (19H2)
npm 6.14.8

Thank's

**Comment by dotansimha** [comment]
@vcheloudiakoff I don't think it's coming from codegen or it's deps. Codegen itself doesn't run or build anything native as far as I know.
Please share a reproduction of that issue.

**Comment by vcheloudiakoff** [comment]
after restarting my computer, it works !
I don't know if there is a way to reproduce that issue, so i think that this post can be closed.

Thanks
