### ISSUE TITLE
Exact is missing in type-graphql plugin output

### ISSUE THREAD

**Issue by borremosch** [dotansimha/graphql-code-generator#4829]
**Describe the bug**
When I generate type-graphl types with the latest version of graphql-codegen, the output contains references to the `Exact<>` generic, but the `Exact<>` type is never defined.

**To Reproduce**
https://codesandbox.io/s/wizardly-dew-wxt8o?file=/types.ts

**Expected behavior**
I expect the `Exact<>` type to be defined.

**Environment:**
- `@graphql-codegen/typescript-type-graphql`: ^1.17.0

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-type-graphql@1.18.1` (thanks @borremosch )
