### ISSUE TITLE
Incorrect version entry for typescript-react-apollo

### ISSUE THREAD

**Issue by tusharsadhwani** [dotansimha/graphql-code-generator#4838]
```
warning Lockfile has incorrect entry for "@graphql-codegen/typescript-react-apollo@1.17.8". Ignoring it.
Couldn't find any versions for "@graphql-codegen/typescript-react-apollo" that matches "1.17.8"
? Please choose a version of "@graphql-codegen/typescript-react-apollo" from this list: 1.17.7
```

v1.17.8 doesn't exist for typescript-react-apollo yet, but that's what the cli puts in package.json

**Comment by dotansimha** [comment]
Hi! How did you get this? Did you do something specific? how can I reproduce this?

**Comment by tusharsadhwani** [comment]
@dotansimha just install graphql codegen version `1.17.8`, configure it to use typescript-react-apollo, and then run `yarn install`

the typescript react apollo config should add the dependency `@graphql-codegen/typescript-react-apollo` with version `1.17.8`, which doesn't exist according to yarn

**Comment by dotansimha** [comment]
Oh got it, this was fixed in 1.17.9 (see https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Fcli%401.17.9 )

**Comment by tusharsadhwani** [comment]
Whoops, now a new error shows up :P 

These are my dev dependencies:

```
"@graphql-codegen/cli": "^1.17.9",
"@graphql-codegen/typescript": "^1.17.9",
"@graphql-codegen/typescript-operations": "^1.17.9",
"@graphql-codegen/typescript-react-apollo": "^1.17.9",
```

But now, `@graphql-codegen/typescript-operations` doesn't have version `1.17.9`. Is there a better, more permanent fix?

**Comment by dotansimha** [comment]
Oh, just use latest version of each plugin, you no longer need to align all versions of GraphQL Codegen.
We are following semver now, which means each package has it's own release and versioning flow.

**Comment by tusharsadhwani** [comment]
Okay great!
