### ISSUE TITLE
Add a CLI flag to make console output in watch mode less verbose

### ISSUE THREAD

**Issue by dkamyshov** [dotansimha/graphql-code-generator#4849]
**Is your feature request related to a problem? Please describe.**

The development workflow in the project I work on requires multiple tools to be running simultaneously in watch mode. I start all the tools via `concurrently` and see a couple, occasionally 5, lines scroll by for each tool for each save. graphql-code-generator, on the other hand, emits ~30 lines on each save (4 lines for each "entrypoint" in codegen.yml). I don't really care about info messages, I only need warning/error messges. There is a `silent` CLI flag, but it also suppresses error output.

**Describe the solution you'd like**

Add a new CLI flag, something like `errors-only`, to only output warnings/errors in watch mode.

**Describe alternatives you've considered**

The alternative might be to print warnings/errors to `stderr` in non-TTY shells (they are printed to stdout now).

**Comment by ajotaos** [comment]
Is this flag available maybe as internal?

**Comment by dkamyshov** [comment]
Turns out, the feature was implemented by @maurobalbi [here](https://github.com/dotansimha/graphql-code-generator/pull/4931). Thank you!

It went unnoticed (for me, at least) and it wasn't included in the docs, so I decided to add it myself - https://github.com/dotansimha/graphql-code-generator/pull/5084.
