### ISSUE TITLE
Types for input Lists do not support coercion

### ISSUE THREAD

**Issue by eightypop** [dotansimha/graphql-code-generator#4888]
**Describe the bug**
 
According to the [graphql spec](https://spec.graphql.org/draft/#sel-FAHjBJFCAACE_Gh7d) input lists can also take a single value of the array's type. However, the types generated do not allow this. This causes the ts to generate type errors with valid queries.

**To Reproduce**
Define an argument that accepts a List
In the operation use the list variable as a single value.

Live repro: https://codesandbox.io/s/wizardly-tereshkova-gqv23?file=/types.ts

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {    
    search(term: [String!]!): [User!]
}

type User {
    id: ID!    
}

```

2. My GraphQL operations:

```graphql
query user($term: [String!]! ) {
    search(term: $term) {
        id
    }
}

```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
Input types generated should be 
```typescript
export type QuerySearchArgs = {
  term: Array<Scalars['String']> | Scalars['String'];
};

export type UserQueryVariables = Exact<{
  term: Array<Scalars['String']> | Scalars['String'];
}>;

```

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS:

**Comment by dotansimha** [comment]
This is totally correct, and I guess this is something from the GraphQL spec we missed in the codegen implementation. Great catch, @eightypop .

**Comment by dotansimha** [comment]
@gilgardosh fixed it in: https://github.com/dotansimha/graphql-code-generator/pull/5115 🎉

**Comment by dotansimha** [comment]
Available now in:
`@graphql-codegen/flow-operations@1.18.5` and `@graphql-codegen/typescript-operations@1.17.13`.

**Comment by elbotho** [comment]
Hey @gilgardosh, should this fix also work for `@graphql-codegen/typescript` without the operations plugin?

**Comment by gilgardosh** [comment]
Hi @elbotho, the fix will work, but coercion cases are relevant for variables therefore irrelevant without `typescript-operations`.

**Comment by elbotho** [comment]
Thanks for the quick reply!
As far as I can tell we only use schema with a notation like this:

``` gql
// pseudo-schema:

type Mutation {
  aMutation(input: MutationInput!): MutationResponse
}

input MutationInput {
  id: [Int!]!
  trashed: Boolean!
}
```

Should MutationInput not also respect coercion?
Should I open a new Issue for that?

**Comment by borekb** [comment]
For people looking to "undo" this feature (though it is correct!), see https://github.com/dotansimha/graphql-code-generator/issues/5352#issuecomment-775851219.

**Comment by dotansimha** [comment]
@elbotho I think it should. Feel free to open a new issue for that! Thank you!
