### ISSUE TITLE
Error running 'init': <function>:16:10 Expected ident but found (static(patterns, options)

### ISSUE THREAD

**Issue by diversit** [dotansimha/graphql-code-generator#4923]
**Describe the bug**
running `npx graphql-codegen init` it fails with:
```
<function>:16:10 Expected ident but found (
    static(patterns, options) {
          ^
```

**To Reproduce**
A clean install on a Mac, in a new folder
First the graphql and then the code generator as described on the installation page using NPM.

```
> npm install --save graphql  
> npm install --save-dev @graphql-codegen/cli
```

package.json
```
{
  "name": "model",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "graphql": "^14.6.0"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^1.17.10"
  }
}
```

**Environment:**

- OS: MacOS Catalina 10.15.5
- `@graphql-codegen/1.17.10`: 
- NodeJS: 10.16.3
- NPM: 6.13.1

**Comment by diversit** [comment]
Ok. Apparently it's because of a wrong Node version.
Just installed Node 14.14.0 and now it works.
However, the documentation does not mention which Node versions are supported.
Would be nice if that kind of info would be added for JS/Node noobs like me.

**Comment by dotansimha** [comment]
Hi @diversit , can you please share which Node version did you use? 
I tested this on latest 10,12,14 and all worked...

**Comment by dotansimha** [comment]
Closing. @diversit if this is still relevant, feel free to ping me.

**Comment by diversit** [comment]
I think it was with the default Node version on Mac which is v8.12.0 in my case.
Was able to continue after changing to v14. Thanks for looking into it anyway.
