### ISSUE TITLE
Default Resolver Implementation Generator

### ISSUE THREAD

**Issue by mateja176** [dotansimha/graphql-code-generator#4925]
Since the shape of the resolvers mirrors the shape of the schema which is defined up front, it is possible to generate default resolver implementations which takes care of the boilerplate. Afterwards it is up the developer to resolve the data. This is not an original idea as it has been done by [graphqlgen](https://github.com/prisma-labs/graphqlgen), however it would complement the [resolver type generation plugin](https://graphql-code-generator.com/docs/plugins/typescript-resolvers) perfectly.

**Comment by dotansimha** [comment]
Thank you @mateja176 , let's track it here: https://github.com/dotansimha/graphql-code-generator/discussions/1772
