### ISSUE TITLE
Create Resource from Type

### ISSUE THREAD

**Issue by mateja176** [dotansimha/graphql-code-generator#4928]
Inspired by the convenience and power of AWS AppSync's [create resource feature](https://youtu.be/_ayZeVjwRPk?t=61), which generates a schema complete with a query, mutations for creating the resource and updating it and subscriptions. On top of that it generates a corresponding DynamoDB table, however this is out of the current scope. This ties very well into [schema merging].

From there on, resolver signatures my be generated from the schema and more.

**Comment by dotansimha** [comment]
Hi @mateja176 
Codegen doesn't generate GraphQL operations for you, it generates code based on schema and operations. 
You can write custom codegen plugin (see docs section) that does that for you, but I don't think we want to maintain this kind of plugin at the moment, since we are trying to keep the generated output of codegen fairly simple.

**Comment by mateja176** [comment]
> Hi @mateja176
> Codegen doesn't generate GraphQL operations for you, it generates code based on schema and operations.
> You can write custom codegen plugin (see docs section) that does that for you, but I don't think we want to maintain this kind of plugin at the moment, since we are trying to keep the generated output of codegen fairly simple.

Yes, this plugin would be an outlier at the moment. However, it would be in line with the codegen philosophy of improving developer experience and stripping away the responsibility to write boilerplate code, that's why I wanted to give it a try. Nevertheless, I already created a project for this purpose [graphql-features](https://github.com/mateja176/graphql-features).

**Comment by dotansimha** [comment]
Cool, let me know if we can help. We are totally open to improve the ecosystem, we just try to not expand the scope of codegen too much, since it will be very hard to maintain. So if you are working on a plugin for codegen that improves your workflow - let us know if we can help in any way ;)
