### ISSUE TITLE
possibleTypes incompatible with InMemoryCache

### ISSUE THREAD

**Issue by mateja176** [dotansimha/graphql-code-generator#4929]
**Describe the bug**
 

`possibleTypes` generated by the [fragment matcher plugin](https://graphql-code-generator.com/docs/plugins/fragment-matcher) are incompatible with the `possibleTypes` parameter of the `InMemoryCache` constructor.

**To Reproduce**

Here's a minimal reproduction [repo](https://github.com/mateja176/codegen-fragment-matcher)

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by dotansimha** [comment]
Hi @mateja176 
You should set `apolloClientVersion: 3` in your codegen config, and this will generate a compatible output.

Then, make sure to use it like that: 

```ts
import possibleTypes from './generated/graphql';

export default new ApolloClient({
  uri: 'https://countries.trevorblades.com',
  cache: new InMemoryCache(possibleTypes),
});
```

Or, like that:

```ts
import introspection from './generated/graphql';

export default new ApolloClient({
  uri: 'https://countries.trevorblades.com',
  cache: new InMemoryCache({ possibleTypes: introspection.possibleTypes }),
});

```

**Comment by mateja176** [comment]
> Hi @mateja176
> You should set `apolloClientVersion: 3` in your codegen config, and this will generate a compatible output.
> 
> Then, make sure to use it like that:
> 
> ```ts
> import possibleTypes from './generated/graphql';
> 
> export default new ApolloClient({
>   uri: 'https://countries.trevorblades.com',
>   cache: new InMemoryCache(possibleTypes),
> });
> ```
> 
> Or, like that:
> 
> ```ts
> import introspection from './generated/graphql';
> 
> export default new ApolloClient({
>   uri: 'https://countries.trevorblades.com',
>   cache: new InMemoryCache({ possibleTypes: introspection.possibleTypes }),
> });
> ```

I've added `apolloClientVersion: 3` in the codegen config, however the issue still persists. And both of the approaches listed yielded typescript errors:
- In the first case
```
Type 'IntrospectionResultData' has no properties in common with type 'InMemoryCacheConfig'.
```
- And in the second case:
```
Property 'possibleTypes' does not exist on type 'IntrospectionResultData'.
```

**Comment by dotansimha** [comment]
@mateja176 can you please share how your codegen config file looks like?

**Comment by mateja176** [comment]
> @mateja176 can you please share how your codegen config file looks like?

Sure, I already pushed the updated version to [master](https://github.com/mateja176/codegen-fragment-matcher).

**Comment by dotansimha** [comment]
@mateja176 please try:
```
overwrite: true
schema: 'https://countries.trevorblades.com'
documents: 'src/**/*.graphql'
generates:
  src/generated/graphql.ts:
    config:
      apolloClientVersion: 3
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'fragment-matcher'
  ./graphql.schema.json:
    plugins:
      - 'introspection'
```

Since `fragment-matcher` is the one that needs to get this configuration flag.
