### ISSUE TITLE
TypeScript generator only used types

### ISSUE THREAD

**Issue by muuvmuuv** [dotansimha/graphql-code-generator#4938]
**Is your feature request related to a problem? Please describe.**

We are connecting to an GraphQL API which has a lot of endpoints so the generated types declaration file is huge (10k lines long). It would be great if it would only create types for used types in the .graphql files and additionally through an option which I also want to add.

**Describe the solution you'd like**

Something like `remove-unused: true` and `included: ["Capability"]`.

**Describe alternatives you've considered**

**Additional context**

**Comment by dotansimha** [comment]
Hi @muuvmuuv ! We have an issue for this here: https://github.com/dotansimha/graphql-code-generator/issues/4562
