### ISSUE TITLE
Fragment type imports are not generated when using Flow / Flow operations plugin

### ISSUE THREAD

**Issue by pastelsky** [dotansimha/graphql-code-generator#4944]
**Describe the bug**
👋 Firstly, thanks for building and maintaining this tool — I'm sure this saves a lot of time and effort for a lot of people. 

While trying out the `nearest-file-output` `preset`, I noticed that type imports for fragments weren't generated for query type files. It seems like this might only be an issue with Flow, as the flow plugin doesn't have the same steps for reading `fragmentImports` as the typescript one.

**To Reproduce**

See this minimal repro -
https://codesandbox.io/s/codegen-flow-bug-kvi73

When I run `yarn codegen`, the `src/index.generated.js` file uses fragments for building its type, but has a missing import. This makes the generated file invalid.

**Expected behavior**
Type imports for fragments are generated whenever a fragment is imported.

**Environment:**

- OS: Any
- `@graphql-codegen/...`: 1.18.0
- NodeJS: 12.3

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/flow-operations@1.18.2`
