### ISSUE TITLE
 Unknown type: "AWSDateTime".

### ISSUE THREAD

**Issue by hirenumradia** [dotansimha/graphql-code-generator#4956]
**Describe the bug**
I am getting a "Unknown type: "AWSDateTime" error when using the library with AWS Amplify

**To Reproduce**

1. Generate a .graphql schema with AWS Amplify
2. Configure 'graphql-code' to generate typescript
2. Attempt code generation with 'graphql-code'

**Expected**
The typescript code generates correctly

**Actual**
An "Unknown type: "AWSDateTime" error is thrown

**Comment by dotansimha** [comment]
@hirenumradia see: https://github.com/dotansimha/graphql-code-generator/discussions/4311
