### ISSUE TITLE
Codegen does not highlight missing syntax from query

### ISSUE THREAD

**Issue by Spartano** [dotansimha/graphql-code-generator#4958]
**Is your feature request related to a problem? Please describe.**

Recently i had a file used for generating a mutation and i didnt see that i was missing a ` } ` at the end of the string

```
./behaviour.js
import gql from "graphql-tag";

const BehaviorMutation = gql`
  mutation Behavior($name:String) {
    createBehavior(name: $name) {
      id
      name
  }
  
`;

```

**Describe the solution you'd like**
It will be nice if codegen will tell you if you're syntax is invalid.

**Comment by ardatan** [comment]
What is the current error you get?

**Comment by dotansimha** [comment]
I think it might be related to graphql-tools (graphql-tag-pluck)

**Comment by Spartano** [comment]
> What is the current error you get?

I dont receive no error, and inside the generated file i see only the types for the mutation, but the useMutation... is missing

**Comment by dotansimha** [comment]
Fixed in tools, we can close this one :)
