### ISSUE TITLE
getting error without error message

### ISSUE THREAD

**Issue by 21stio** [dotansimha/graphql-code-generator#496]
Hey,

when running the generator, it throws an error, but doesn't display an error message..

`$ gql-gen --schema src/schema.graphql --template graphql-codegen-typescript-template --out ./typings/`

`13:17:34.347 - info: Loading GraphQL schema object, text, ast, or introspection json from JavaScript ES6 export: src/types.ts... 
13:17:34.355 - error:  
`

**Comment by 21stio** [comment]
The issue was the way the schema was provided. Even tho, having not error message is a little annoying..

**Comment by dotansimha** [comment]
@21stio maybe we can find a better solution for this. 
How does your `src/schema.graphql` looks like?

**Comment by 21stio** [comment]
Initially I provided a plain text file that only contains the schema a la, using a http endpoint works fine

```
type Link {
    href: String
    description: String
}

input LinkInput {
    href: String
    description: String
}
```

**Comment by 21stio** [comment]
Same is happening for a schema.json that has been generated with 
`apollo schema:download --endpoint=${SCHEMA_DIR}/schema.graphql ${SCHEMA_DIR}/schema.json`

**Comment by timeyr** [comment]
I am also experiencing that. I upgaded from version 0.8x to 0.11.0, replaced `--file` by `--schema` in the CLI command, and now I get this error w/o message:
```
$ cross-env DEBUG=true gql-gen --schema schema.json --template typescript --out ./src/gen/schema/ "./src/input/schema
/partial/**/*.graphql"
10:27:29.399 - info: [executeWithOptions] using template: typescript
10:27:29.404 - error:
```

**Comment by mixail-novikov** [comment]
I faced the same problem. In my case I explicitly install graphql-codegen-typescript-react-apollo-template as dev dependency.

Perhaps, in your case you should install graphql-codegen-typescript-template.

I don't know why this not mentioned in docs.
