### ISSUE TITLE
vue-apollo plugin does not work with useTypeImports

### ISSUE THREAD

**Issue by P4sca1** [dotansimha/graphql-code-generator#5006]
**Describe the bug**
The vue-apollo plugin ignores the `useTypeImports` setting for the import of the composition api.

**To Reproduce**
https://codesandbox.io/s/awesome-mendeleev-71ovu?file=/types.ts

**Expected behavior**
When `useTypeImports: true`, the import of the vue composition api should use `import type`.

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-vue-apollo@2.2.0`
