### ISSUE TITLE
Confusing comment when DateTime is configured

### ISSUE THREAD

**Issue by glennreyes** [dotansimha/graphql-code-generator#5018]
**Describe the bug**
Adding

```yml
config:
  scalars:
    DateTime: Date
```

To config should remove the comment above DateType of generated file:

```ts
/** The javascript `Date` as string. Type represents date and time as the ISO Date string. */
  DateTime: Date;
```

**Expected behavior**

Just remove the comment if DateTime was set in the config.

**Comment by dotansimha** [comment]
Hi @glennreyes ,
This comment is coming from your GraphQL schema.
Please take a look at the implementation of your `scalar DateTime`.

**Comment by glennreyes** [comment]
Thanks for the pointer, it indeed was! I haven't checked since the schema I am using is generated programmatically. Closing this.
