### ISSUE TITLE
Wrong query types generated by typescript-react-apollo-template

### ISSUE THREAD

**Issue by mcongy** [dotansimha/graphql-code-generator#503]
Hey,

First off, thank u so much for this project and for the react-apollo-template. Works very nicely.

**Issue**
graphql-code-generator Version: 0.10.7 (latest as of 8/12/2018)
Node Version: 10.8.0
Platform: Ubuntu 18.04

**Using command:**
`npx gql-gen --template graphql-codegen-typescript-react-apollo-template --config gqlgen.json --out __generated/queries.ts src/queries/**/*.graphql --schema __generated/schema.json`
**gqlgen.json:**

```
{
  "generatorConfig": {
    "noNamespaces": true,
    "resolvers": false
  }
}

```
**For query**
```graphql
query Games {
  games {
    id
    token
    name
  }
}
```
**Result (showing only relevant lines):**
```typescript
export type GamesVariables = {};

export type GamesQuery = {
  __typename?: 'Query';
  games: GamesGames[];
};

export type GamesGames = {
  __typename?: 'Game';
  id: Uuid;
  token: string;
  name: string;
};

import * as ReactApollo from 'react-apollo';

export class GamesComponent extends ReactApollo.Query<Query, GamesVariables> {}
```

**Expected behavior:**
`class GamesComponent` should extend `GamesQuery`, not `Query`

I have to use the no-namespace version, since I'm using babel with typescript preset that doesn't support namespaces.

Is this an issue, or am I doing something wrong? 

Thank u for your time!

**Comment by ardatan** [comment]
It's been fixed by
https://github.com/dotansimha/graphql-code-generator/commit/e5feb631d4383046b9cc2b00c4fad893ec1567a7#diff-60c0e6de76c51ffb8188d0076519b572R11

**Comment by dotansimha** [comment]
Done! 0.11 is available now. @mcongy
