### ISSUE TITLE
baseOptions should be optional on mutation hooks

### ISSUE THREAD

**Issue by daganomri** [dotansimha/graphql-code-generator#5045]
**Describe the bug**
The `baseOptions` argument on generated mutation hooks is required, when it should be optional. 

**To Reproduce**
Generate any mutation hook. 

**Expected behavior**
baseOptions will be optional when calling a mutation hook. 

**Environment:**
- `@graphql-codegen/cli: ^1.19.1`
- `@graphql-codegen/typescript-react-apollo: ^2.1.0`

**Additional context**

**Comment by dotansimha** [comment]
I'll create a PR for skipping [this feature](https://github.com/dotansimha/graphql-code-generator/issues/4964) for mutations. 
Thank you for reporting this @daganomri

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/5046

**Comment by dotansimha** [comment]
Fix available in `@graphql-codegen/typescript-react-apollo@2.1.1`. 
@daganomri @gynekolog

**Comment by bubba** [comment]
Should the baseOptions hook only be optional if there are no required variables needed for the mutation? Otherwise this undos #4964 for the mutations case

**Comment by dotansimha** [comment]
@bubba 
Mutation - always optional, since you can specify it later (while executing), and I think we don't have a way to check that.
Query/Subscription - options are specified on the declaration level ,and now it will depend on the variables.

**Comment by bubba** [comment]
@dotansimha I didn't realise you could specify variables later. Thanks for clarifying!
