### ISSUE TITLE
graphql-request plugin supporting custom headers per each request method.

### ISSUE THREAD

**Issue by moeHaydar** [dotansimha/graphql-code-generator#5049]
A new feature is being supported by graphql-request library: Support passing custom headers per each request method.
This issue is to support that in the generation of the extra parameter than can be passed to the generated code in the plugin

graphql-request: PR: https://github.com/prisma-labs/graphql-request/pull/228

Note: I will do a PR here to resolve this issue once the graphql-request is merged to master

**Comment by dotansimha** [comment]
Thank you, @moeHaydar . I'm closing this since we can track this on the PR you created, and since this feature is not merged yet in `graphql-request`.
