### ISSUE TITLE
generate TS files with `// @ts-nocheck ` at the top by default

### ISSUE THREAD

**Issue by capaj** [dotansimha/graphql-code-generator#5073]
**Is your feature request related to a problem? Please describe.**
our tsconfig is set to flag unused variables as TS errors 
```

front-end/src/pages/bulk-users-import-page/users-import-details/operations/fetchReusableImportMappings.codegen.tsx(6,3): error TS6133: 'UsersCsvImportModelFragment' is declared but its value is never read.
--
403 | front-end/src/pages/bulk-users-import-page/users-import-details/operations/fetchReusableImportMappings.codegen.tsx(11,3): error TS6133: 'UsersCsvImportModelFragmentDoc' is declared but its value is never read.

```

graphql codegen sometimes generates files that have unused imports

**Describe the solution you'd like**

I would like if the generated TS files were not checked by default-this saves time on big projects and it doesn't make sense to check generated files. The fact that these files are generated correctly is checked by the tests in this repo. It doesn't need to be checked by TS compiler again.
**Describe alternatives you've considered**

you can use the existing https://graphql-code-generator.com/docs/plugins/add but most people will never set it up until they start having issues, so it would make sense to add it by default in all typescript plugins
**Additional context**

**Comment by capaj** [comment]
I can create a separate bug issue for the imports being in the TS file, but it is not as big of a priority for me.

**Comment by dotansimha** [comment]
I think we need to discuss that, since we tried to avoid those additions until now (like with linters). Mainly because this could be solved with `add` plugin. 

@ardatan @kamilkisiela what do you think?

**Comment by kamilkisiela** [comment]
Only if it's behind a flag to enable it back on demand

**Comment by saihaj** [comment]
Hey @capaj as @dotansimha suggested it makes sense to use the [`add`](https://www.graphql-code-generator.com/plugins/add) plugin and add this following way. If this is a very common use-case in community, people adding +1 or replying in comments, considering there isn't much demand it makes sense to just use the plug-in instead of maintaining a config option.
 
```yaml
generates:
  path/to/file.ts:
    plugins:
      - add:
          content: '// @ts-nocheck'
      - typescript
```

**Comment by Urigo** [comment]
I do think that in v3 it might be interesting to add it as default somehow, might make the default and initial experience of codegen a bit nicer, like @capaj is suggesting

**Comment by appleseed-iii** [comment]
> but most people will never set it up until they start having issues, so it would make sense to add it by default in all typescript plugins

he just like me fr 😭
