### ISSUE TITLE
[Feature] Static type code generation with inline fragment

### ISSUE THREAD

**Issue by sonatard** [dotansimha/graphql-code-generator#5087]
I'm always frustrated when using following node query.

```graphql
query GetApplication($applicationID: ID!) {
  node(id: $applicationID) {
    ... on Application {
      id
    }
  }
}
```

```tsx
// generation code
export type GetApplication1Query = (
  { __typename?: 'Query' }
  & { application: { __typename?: 'Admin' } | { __typename?: 'User' } |  { __typename?: 'Application' } & Pick<Application, 'id'>
  ) | { __typename?: 'Profile' } 
);
```

I have to write type check code every to write GetApplication1QueryDocument query code, It's so many time.

```tsx
    // typed document node
    const { data } = useQuery(GetApplication1QueryDocument, {
        variables: {
          applicationID,
        },
      },
    );
  
    // type check code
    const application =
      data?.application.__typename === "Application"
        ? data.application
        : undefined;
```

I would like to generate the same code following query.
Also, I want to configure it in yaml config file.

```graphql
query GetApplication($applicationID: ID!) {
  node(id: $applicationID) {
    ... on Application {
      id
    }
  }
}

query GetApplication($applicationID: ID!) {
  application(id: $applicationID) {
    id
  }
}
```

```tsx
export type GetApplication2Query = (
  { __typename?: 'Query' }
  & { application: (
    { __typename?: 'Application' }
    & Pick<Application, 'id'>
  ) }
);
```

I suppose I could solve this problem by providing an application schema, but it's not like GraphQL to use byID queries for all types.

```graphql
node(id: ID!): Node!
# add
application(id: ID!): Application!
# other types query...
```

**Comment by dotansimha** [comment]
There is nothing we can do about it, it's just the way you schema is implemented. 
If you are using interfaces, it means that all implementing types can be returned from that field. Codegen will generate typed with type discrimination based on that `__typename`. 
Even if the fragment is inlined, it still means that something else could be returned from that query, and not `Application`, since the return type is `Node`.
