### ISSUE TITLE
Typescript generation fails with [object Object] instead of field name in Pick

### ISSUE THREAD

**Issue by c100k** [dotansimha/graphql-code-generator#5103]
**Describe the bug**
 

Generation of typescript objects fails since the last update of `typescript-resolvers@1.17.11`.

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

https://codesandbox.io/s/inspiring-pasteur-onywi

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

In the codesandbox `types.ts` files at the line 36, we should have:

```typescript
& Pick<User, '[object Object]' | '[object Object]' | '[object Object]'>
```

instead of:

```typescript
& Pick<User, 'id' | 'user' | 'email'>
```

**Environment:**

- OS: macOS (local) and codesandbox
- `@graphql-codegen/cli`: 1.19.1
- `@graphql-codegen/typescript`: 1.17.11
- `@graphql-codegen/typescript-operations`: 1.17.9
- `@graphql-codegen/typescript-resolvers`: 1.17.11
- `graphql`: 14.7.0
- NodeJS: `node --version` in codesandbox => v10.21.0

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by dotansimha** [comment]
Hi, @c100k , please update `typescript-operations` as well. It should be: `1.17.10`.

**Comment by c100k** [comment]
Hi @dotansimha, thanks for the feedback. Tested on the codesandbox and indeed it fixed it.

Generally speaking, having two dependencies with two different version number makes the whole thing harder to follow.

- @graphql-codegen/typescript-resolvers (1.17.10) + @graphql-codegen/typescript-operations (1.17.9) ✅
- @graphql-codegen/typescript-resolvers (1.17.11) + @graphql-codegen/typescript-operations (1.17.9) ❌
- @graphql-codegen/typescript-resolvers (1.17.11) + @graphql-codegen/typescript-operations (1.17.10) ✅

That does not follow exactly semantic versioning.

**Comment by dotansimha** [comment]
I totally agree with you, but unfortunately, semantic versioning doesn't refer to siblings / optional deps.

The thing here is that `typescript-operations` and `typescript` works together, but it can also be standalone. And both shares a common package. Fixing something in the common package will require you to update both to latest (like in this case). We are trying to avoid these changes as much as possible.

We don't want to publish the entire monorepo on each change... we used to do it in the past but it was causing an overhead and published packages for no reason. 

I will update the release notes, hope that helps.

**Comment by c100k** [comment]
Ah ok I understand. Indeed, publishing everything, everytime is also not a good thing.

Maybe `peerDependencies` can help in this kind of situation. This way it would probably show warnings when executing `yarn install`.

And btw, you're doing a very good job with this tool!
