### ISSUE TITLE
Generating client side types using apollo-link-state

### ISSUE THREAD

**Issue by valentinbe** [dotansimha/graphql-code-generator#511]
Hi,
Thanks for the amazing tool. 
Did anyone managed to generate client side types with part of the schema defined  locally using apollo-link-state? Apollo cli handles this use case with a --clientSchema option on generation step. 
For the moment I am ignoring client side schema definitions files. But limits of this workaround being that types are not generated when I write queries which fetch both client and server side defined schemas becomes increasingly frustrating.

**Comment by dotansimha** [comment]
@valentinbe, thanks for reporting it! Can you please provide an example?

**Comment by dotansimha** [comment]
At the moment, the codegen supports this use case. 
You can an example in my PR for ReactQL here: https://github.com/leebenson/reactql/pull/129 

@valentinbe
