### ISSUE TITLE
Codegen failing on type policies

### ISSUE THREAD

**Issue by danReynolds** [dotansimha/graphql-code-generator#5111]
We've defined some type policies in our app using Apollo 3, such as:
```
{
  Query: {
    fields: {
       testField: {
         read() {
           return true;
         }
       }
    }
  }
}
```

and use it in the client as below:

```
const { data } = useQuery(gql`{ testField @client }`)
```

but when we run codegen, `we get error cannot query field testField` on Query. I know type policies are an Apollo 3 feature, is there anything we need to do to codegen to get it to recognize them and not say that their fields don't exist? Based on what I see in the config for codegen, there's no way of telling it these fields exist since it seems to only take into account your schema and not any Apollo type policies specifications?

**Comment by danReynolds** [comment]
Makes sense that you would define schema extensions for the type policies

**Comment by dotansimha** [comment]
@danReynold unfortunately, we can't really locate your defined typePolicies and convert it into a schema, so you have to define SDL for it, and provide it for codegen.

**Comment by 29er** [comment]
what do you mean 'define SDL for it' . Im running into the same issue and starting to think I can't use codegen if I want to add any client fields to an existing query

**Comment by ardatan** [comment]
@29er He means you need to write an SDL that contains additional type definitions;
```graphql
extend type Query {
  testField
}
```

**Comment by 29er** [comment]
ahh i see, ok thanks!
