### ISSUE TITLE
[typescript] Non-null default fields are incorrectly optional

### ISSUE THREAD

**Issue by jun-sheaf** [dotansimha/graphql-code-generator#5112]
**Describe the bug**
 
Default values are handled incorrectly.

**To Reproduce**
Suppose we have the schema
```graphql
input SomeInput {
  test: String! = "test"
}
```
Then `graphql-codegen` will optionalize the argument `test`.

**Expected behavior**

The above should not be optional as `String!` is never `null`.

**Environment:**

- OS: Mac OS Catalina
- `@graphql-codegen/...`: Latest as of issue date
- NodeJS: Latest as of issue date

**Comment by ardatan** [comment]
If you provide a default value for an input field, it means that input field should be optional on client side. You are able not to provide a value for that because the server is able to handle it with the given default value.

**Comment by jun-sheaf** [comment]
Test cannot be set nullable on client side since test is a non-nullable type.

**Comment by ardatan** [comment]
I was talking about this behavior so in this case `bar` is optional there even if it is `String!`.
https://codesandbox.io/s/late-cache-npyqj?file=/src/index.js

**Comment by jun-sheaf** [comment]
Yes, I am aware, but as I stated, `bar` is not actually `null` for the resolver. [See here](https://codesandbox.io/s/stoic-chaum-un1z1?file=/src/index.js:0-1110)

Thus it would be better to have an `avoidOptionals` option for `defaultValue` for those who generate server types.

**Comment by dotansimha** [comment]
Merged and published. Thanks @jun-sheaf!
