### ISSUE TITLE
Add `useImplementingInterfaces` flag for typescript plugin

### ISSUE THREAD

**Issue by maaft** [dotansimha/graphql-code-generator#5126]
**Is your feature request related to a problem? Please describe.**

Currently interfaces are translated to typescript types using the interface name.
Schema:
```
type Foo {
   m: [Bar!]!
}

interface Bar {
   foo: Foo!
}

type Blub implements Bar {
   ...
}

type Blabla implements Bar {
   ...
}
```

This will generate following types:
```typescript
export type Bar = {
  foo: Foo;
};

export type Blabla = Bar & {
  __typename?: 'Blaba';
  foo: Foo;
  ...
};

export type Blub = Bar & {
  __typename?: 'Blaba';
  foo: Foo;
  ...
};

export type Foo = {
  __typename?: 'Foo';
  m: Array<Bar>;
};
```

The problem here is that I want to store the actual implementations of the interface in my array `m` on type `Foo` and not (per definition non-existent) instances of an interface.

**Describe the solution you'd like**

Add a `useImplementingInterfaces` flag to codegen.yml config.
When set, the generated type `Foo` from above will look like this:
```typescript
export type Foo = {
  __typename?: 'Foo';
  m: Array<Blub | Blabla>;
};
```

**Describe alternatives you've considered**
No alternatives currently available.

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/typescript@1.19.0`
