### ISSUE TITLE
Using CLI with watch option doesn't reload configuration

### ISSUE THREAD

**Issue by robertherber** [dotansimha/graphql-code-generator#5148]
**Describe the bug**
When using the CLI with the watch option I'd expect the configuration file to be reloaded. I just spent an hour figuring out why my newly added typeMappings didn't update - only to realise the config was never reloaded.

**To Reproduce**
1. Use any working codegen.yml/schema setup.
2. Run `graphql-codegen --config codegen.yml --watch my-schema.graphql`
3. Make a change in codegen.yml
4. Make a change in my-schema.graphql

**Expected behavior**
I'd expect the changes in step 3 to be reflected in the generated result.

**Comment by dotansimha** [comment]
Thank you for reporting this @robertherber . This seems related: https://github.com/dotansimha/graphql-code-generator/issues/1735 
Maybe the comment there might be relevant as well.

**Comment by robertherber** [comment]
@dotansimha Indeed - seems like the issue has resurfaced again.

I can add that my current solution is using nodemon instead which works well as a workaround.

**Comment by dotansimha** [comment]
@robertherber is there a chance you know which version you had before and if it worked? just so it will be easier to track what caused it. Thank you!

**Comment by robertherber** [comment]
@dotansimha I'm not sure if it's worked for me before - this happened in a new project. The reason I suppose it's been working in between is simply because of the related issue.. :)

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/5209

**Comment by dotansimha** [comment]
@gilgardosh  fixed it in https://github.com/dotansimha/graphql-code-generator/pull/5209 , and it's available now in `@graphql-codegen/cli@1.20.0`. Thanks!
