### ISSUE TITLE
Predictable output plugin idea

### ISSUE THREAD

**Issue by vladinator1000** [dotansimha/graphql-code-generator#5149]
Hi y'all! I'd like to make a plugin that hashes the input and stores it in a lock file, to prevent generating a new file when the input is the same.

Are y'all cool if I go for something like this?

**Comment by dotansimha** [comment]
Hi @vladinator1000 ,
I'm not sure I fully understood this. Are you referring to a new plugin suggestion? If so, can you please share an example for input/output? 
Or are you referring to an optimization on codegen core to prevent re-generating unchanged files?

**Comment by vladinator1000** [comment]
@dotansimha I'm not sure if it should be a plugin or core but I'm trying to do this, yeah:

> prevent re-generating unchanged files?

**Comment by dotansimha** [comment]
@vladinator1000 I see, thank you. it's a core feature in this case. 
We do prevent fs operations when output file changes, but TBH, so far we didn't see projects that has performance issues with codegen. Is there a use case that requires this kind of feature?

**Comment by vladinator1000** [comment]
I'm mostly doing it cause I commit my generated file to source control and I'd like to avoid it appearing in the diff if it hasn't meaningfully changed.

**Comment by sdzharkov** [comment]
@vladinator1000 I've been looking for a solution for this - our issue is that the order of enums is not deterministic. Meaning - even if no backend GraphQL changes were added, the order of the enums will rearrange, and those changes will then need to be added to source control. 

@dotansimha is there a reason that the order of enums is constantly rearranging, even though no backend changes were introduced?

I'd be interested in collaborating on this - is your issue tied to a specific part of the GraphQL schema?

**Comment by dotansimha** [comment]
I think eventually our best solution it to port this piece of code: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/other/schema-ast/src/index.ts#L57 into `graphql-tools`. 
I think it should be pretty simple. 


@ardatan can you please take a look?

**Comment by dotansimha** [comment]
Tracking in: https://github.com/dotansimha/graphql-code-generator/issues/5106#issuecomment-741689595
