### ISSUE TITLE
React Query infinite pagination 

### ISSUE THREAD

**Issue by galkatz373** [dotansimha/graphql-code-generator#5212]
I would love to use the react query plugin, but unfortunately it doesn't have a support for infinite scrolling and for me itvs really important, I would really appreciate it if you add it.

**Comment by lynxtaa** [comment]
Since my PR (https://github.com/dotansimha/graphql-code-generator/pull/5863) is merged and released in `typescript-react-query@1.3.0` now there is an option `exposeDocument` for exposing document from the hook. So I've written a custom hook for infinite queries:

```ts
interface UseQueryFn<
  TData extends Record<string, any>,
  TVariables extends Record<string, any>
> {
  (variables: TVariables, options?: UseQueryOptions<TData>): unknown
  document: string
  getKey: (variables: TVariables) => unknown[]
}

export function useInfiniteGraphQLQuery<
  TData extends Record<string, any>,
  TVariables extends Record<string, any>
>(
  useQuery: UseQueryFn<TData, TVariables>,
  getVariables: ({ pageParam }: { pageParam?: number }) => TVariables,
  options?: UseInfiniteQueryOptions<TData, Error>,
): UseInfiniteQueryResult<TData, Error> {
  return useInfiniteQuery<TData, Error>(
    useQuery.getKey(getVariables({})),
    ({ pageParam }) => gqlRequest(useQuery.document, getVariables({ pageParam })),
    options,
  )
}
```

And use it like this:
```ts
// All types, key and document are infered from the passed hook
const { fetchNextPage, hasNextPage, data, isLoading } = useInfiniteGraphQLQuery(
  useGetFolderDocumentsQuery, // this is a hook generated by typescript-react-query
  ({ pageParam = 0 }) => ({ // return variables
    folderId,
    limit: 100,
    offset: 100 * pageParam,
   }),
  // getNextPageParam and other options
)
```

In codegen config I'm setting  `exposeQueryKeys: true` and `exposeDocument: true`. I hope you find it helpful

**Comment by Urigo** [comment]
anyone who tracks this issue, do you think @lynxtaa solution (thank again for the PR!) is enough, or something else is needs?
(that might include just a receipt or a mention in the docs)
Thanks!

**Comment by lynxtaa** [comment]
I think the best solution is to add an option `useInfiniteQuery` which takes a list of operations names similarly to `useSRWInfinite` option in `plugin-typescript-swr`:  https://www.npmjs.com/package/graphql-codegen-plugin-typescript-swr#useswrinfinite

**Comment by Urigo** [comment]
Thanks for the comment @lynxtaa 

I think in order to advance this to the [next phase](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow), it would be great if someone would start with a draft PR with a failing test for the wished API

**Comment by jrwpatterson** [comment]
> Hey, has anyone worked on this in the meantime? I would love to use `useInfiniteQuery` with my graphql calls. Or should I opt for the solution from @lynxtaa for now?

hey @nandorojo my company started working on it mid-last week. We are planning on testing it as a patch this week to confirm we are happy. The only thing that we are doing that is slightly out of spec is we are passing the react query options to the Custom Fetcher as an optional parameter then if you do something like...

```typescript
declare module 'react-query' {
  interface UseInfiniteQueryOptions<
    TQueryFnData = unknown,
    TError = unknown,
    TData = TQueryFnData,
    TQueryData = TQueryFnData,
    TQueryKey extends QueryKey = QueryKey,
  > extends InfiniteQueryObserverOptions<
      TQueryFnData,
      TError,
      TData,
      TQueryData,
      TQueryKey
    > {
    optionsParam: string
  }
}

interface MetaData {
  queryKey: Array<string | object>
  pageParam: string | number
}

export const useFetchData =
  <TData, TVariables>(
    query: string,
    options: UseInfiniteQueryOptions,
  ): ((variables?: TVariables, metaData?: MetaData) => Promise<TData>) =>
  async (variables?: TVariables, metaData?: MetaData) => {
    if (metaData?.pageParam != null) {
      variables[options.optionsParam] = metaData.pageParam ?? 0
    }
    const { data } = (await API.graphql({
      query,
      variables: variables as unknown as object,
    })) as GraphQLResult<Promise<TData>>
    return await (data as Promise<TData>)
  }
```

then in the query we are doing 
```typescript
export const Foo = () => {
  const [queryParams, setQueryParams] = useState<QueryGetFooArgs>({
    limit: 5,
    from: 0,
  })

  const { data, hasNextPage, fetchNextPage } = useInfiniteGetFooQuery(
    {
      limit: 5,
      from: 0,
    },
    {
      optionsParam: 'from',
      getNextPageParam: (lastPage, allPages) => {
        const totalLocal = (allPages.length ?? 0) * (queryParams.limit ?? 1)
        const totalServer =
          lastPage.getFoo.__typename === 'fooList'
            ? lastPage.getFoo.total ?? 0
            : 0
        if (totalLocal < totalServer) {
          return (allPages.length ?? 0) * (queryParams.limit ?? 1)
        }
      },
    },
  )
```

does anyone have an issue with this approach or have a better one before I write the tests or is this acceptable? It was the most consistent way with a single fetcher that I could find would be nice that wouldn't require adding more and more to it.

**Comment by jrwpatterson** [comment]
I've now got the pr and changed the API so its less hacky and much more re-usable. the only thing it has is there is a key on the useInfiniteGetFooQuery that is the field that accepts the key for the pageParam in the useInfinitequery

**Comment by dotansimha** [comment]
This is now available in `@graphql-codegen/typescript-react-query@3.2.0`. Thanks!

**Comment by bytesagar** [comment]
@jrwpatterson  
```
const patientActivityQuery = useInfiniteGetPatientActivityQuery(
		{
			patientId,
			requiredPage: {
				Page: 1,
				Limit: 10,
			},
		},
		

		{
			optionsParam:'Page',
			getNextPageParam: (lastPage, allPages) =>
				lastPage.listPatientActivity.pageInfo.pageSize,
		}
	);
```
optionsParam doesn't seem to be supported. How should I fetch next page as I press my Load more button it seems to fetch only same page data everytime

```
	<Button
						// isLoading={isFetchingNextPage}
						onClick={() => {
							fetchNextPage({ pageParam: 1 });
						}}
						disabled={isFetchingNextPage}
						// onClick={() => setPage((prev) => ({ ...prev, Page: page.Page + 1 }))}
					>
						Load More
					</Button>
```

**Comment by drewbietron** [comment]
> 

How are you setting `setQueryParams`?  Trying to follow along with what you provided but I'm not able to tack on the next page results to the previous results, since I have using the state value of `queryParams` as by before/after filter in the query.

Furthermore, is it possible to have multiple infinite paginated queries within a single query?  My example has a query with two arrays of data, each with cursors and Id like to be able to infinitely paginate both but as far as I can see this will just support one set of page params per query?  Not the biggest deal as I can break out my larger query into smaller useQuery's for each array of data that I want to paginate on.

**Comment by drewbietron** [comment]
> > Hey, has anyone worked on this in the meantime? I would love to use `useInfiniteQuery` with my graphql calls. Or should I opt for the solution from @lynxtaa for now?
> 
> hey @nandorojo my company started working on it mid-last week. We are planning on testing it as a patch this week to confirm we are happy. The only thing that we are doing that is slightly out of spec is we are passing the react query options to the Custom Fetcher as an optional parameter then if you do something like...
> 
> ```ts
> declare module 'react-query' {
>   interface UseInfiniteQueryOptions<
>     TQueryFnData = unknown,
>     TError = unknown,
>     TData = TQueryFnData,
>     TQueryData = TQueryFnData,
>     TQueryKey extends QueryKey = QueryKey,
>   > extends InfiniteQueryObserverOptions<
>       TQueryFnData,
>       TError,
>       TData,
>       TQueryData,
>       TQueryKey
>     > {
>     optionsParam: string
>   }
> }
> 
> interface MetaData {
>   queryKey: Array<string | object>
>   pageParam: string | number
> }
> 
> export const useFetchData =
>   <TData, TVariables>(
>     query: string,
>     options: UseInfiniteQueryOptions,
>   ): ((variables?: TVariables, metaData?: MetaData) => Promise<TData>) =>
>   async (variables?: TVariables, metaData?: MetaData) => {
>     if (metaData?.pageParam != null) {
>       variables[options.optionsParam] = metaData.pageParam ?? 0
>     }
>     const { data } = (await API.graphql({
>       query,
>       variables: variables as unknown as object,
>     })) as GraphQLResult<Promise<TData>>
>     return await (data as Promise<TData>)
>   }
> ```
> 
> then in the query we are doing
> 
> ```ts
> export const Foo = () => {
>   const [queryParams, setQueryParams] = useState<QueryGetFooArgs>({
>     limit: 5,
>     from: 0,
>   })
> 
>   const { data, hasNextPage, fetchNextPage } = useInfiniteGetFooQuery(
>     {
>       limit: 5,
>       from: 0,
>     },
>     {
>       optionsParam: 'from',
>       getNextPageParam: (lastPage, allPages) => {
>         const totalLocal = (allPages.length ?? 0) * (queryParams.limit ?? 1)
>         const totalServer =
>           lastPage.getFoo.__typename === 'fooList'
>             ? lastPage.getFoo.total ?? 0
>             : 0
>         if (totalLocal < totalServer) {
>           return (allPages.length ?? 0) * (queryParams.limit ?? 1)
>         }
>       },
>     },
>   )
> ```
> 
> does anyone have an issue with this approach or have a better one before I write the tests or is this acceptable? It was the most consistent way with a single fetcher that I could find would be nice that wouldn't require adding more and more to it.

How are you setting setQueryParams? Trying to follow along with what you provided but I'm not able to tack on the next page results to the previous results, since I have using the state value of queryParams as by before/after filter in the query.

Furthermore, is it possible to have multiple infinite paginated queries within a single query? My example has a query with two arrays of data, each with cursors and Id like to be able to infinitely paginate both but as far as I can see this will just support one set of page params per query? Not the biggest deal as I can break out my larger query into smaller useQuery's for each array of data that I want to paginate on.
