### ISSUE TITLE
Supported formats when loading from URL

### ISSUE THREAD

**Issue by imsteev** [dotansimha/graphql-code-generator#5215]
Does this tool expect a certain format when loading from URL?
We have a `.graphql` file that gets served over HTTP, but when I run codegen on that URL, the CLI complains that it is not JSON. Shouldn't this tool be able to handle schemas in the normal `.graphql` format if we can do that locally?

**Comment by ardatan** [comment]
How does the URL look like because if it ends with '.graphql' URLLoader handles it as an SDL file.

**Comment by imsteev** [comment]
@ardatan it's not suffixed with a file format and the response is just plaintext
```
GET /graphql/schema
```
clients are not always in control of how this is served, so is there a parameter we can pass to the CLI to signal it should be treated as SDL content?

**Comment by ardatan** [comment]
Until this gets released, you can use this url to trick the URL Loader;
`/graphql/schema?ext=.graphql`

**Comment by dotansimha** [comment]
Please make sure to update codegen and it's deps to latest, it should fix that.
