### ISSUE TITLE
No files matched for glob pattern

### ISSUE THREAD

**Issue by ggoforth** [dotansimha/graphql-code-generator#523]
Hello, I'm getting a `No files matched for glob expression: "./src/**/*.graphql"` message when running the code generation function from the command line.

The command I'm running is:

`$(npm bin)/gql-gen --schema http://localhost:3000/graphql --template graphql-codegen-apollo-angular-template --out ./src/generated/graphql.ts \"./src/**/*.graphql\"`

The output I receive during this is:

```> ./gql-code-gen.sh

00:18:42.936 - info: Loading GraphQL Introspection from remote: http://localhost:3000/graphql... 
00:18:42.978 - warn: No files matched for glob expression: "./src/**/*.graphql" 
00:18:43.622 - info: Generated file written to /Users/greg/projects/tatstat/client/src/generated/graphql.ts 

Process finished with exit code 0
```

I do have a `.graphql` file in the project at the glob path:

<img width="300" alt="screen shot 2018-08-22 at 12 15 40 am" src="https://user-images.githubusercontent.com/1167712/44448880-6a81a880-a5a1-11e8-9e4c-71404fe6f811.png">

I'm certain I'm doing something wrong when it comes to the glob, but any reason why the glob pattern wouldn't find my `.graphql` file to use for code generation?  The complete contents of that file look like:

```
query localityByLatLng ($lat: Float!, $lng: Float!) {
  localityByLatLng (lat: $lat, lng: $lng) {
    types
    place_id
    formatted_address
    address_components {
      long_name
      short_name
      types
    }
    geometry {
      location {
        lat
        lng
      }
    }
  }
}
```

I'm running this on a MacBook Pro, running High Sierra.

**Comment by dotansimha** [comment]
@ggoforth can you share a repo?

**Comment by dotansimha** [comment]
closing for now, due to inactivity. @ggoforth, feel free to open a new issue with more details if you still need our help :)
