### ISSUE TITLE
@skip, @include directives are sometimes ignored

### ISSUE THREAD

**Issue by deftomat** [dotansimha/graphql-code-generator#5238]
**Describe the bug**
 

`@skip` and `@include` directives are ignored when they are applied on "object".

Apollo server handles them correctly with no issue. 

Also, the example in GraphQL docs is basically the same: https://graphql.org/learn/queries/#directives

**Doesn't work - `chat` is required:**
```
query User($withChat: Boolean!) {
  user {
    name
    chat @include(if: $withChat) {
      unread
    }
  }
}
```

**Work as expected - `unread` is optional:**
```
query User($withChat: Boolean!) {
  user {
    name
    chat {
      unread @include(if: $withChat)
    }
  }
}
```

**Environment:**

```@graphql-codegen/typescript-operations@1.17.12```

**Comment by dotansimha** [comment]
We can close this one, @gilgardosh fixed it :)
