### ISSUE TITLE
Inconsistency in interpreting `type Query` and `extend type Query` between graphql-codegen and graphql-modules

### ISSUE THREAD

**Issue by laurisvan** [dotansimha/graphql-code-generator#5245]
**Is your feature request related to a problem? Please describe.**

We have been using graphql-codegen and graphql-modules together now for 2 years with great success. However, the adoption of graphql-modules 1.0 has now been blocked due to the differences in schema merging. This particularly blocks modularising Queries (and likely Mutations and Subscriptions), as the interpretation of schemas differs between the two. graphql-modules expects these root level types to be extended, e.g. `extend type Query` whereas graphql-modules fails with that and expects `type Query`.

Until now I have not found any other workaround than squashing all the queries together into a single module, which clearly violates good practices for modularisation. 

@kamilkisiela already expressed that grapql-modules will follow the standards compliant way, e.g. `extend type Query`, https://github.com/Urigo/graphql-modules/issues/1300

**Describe the solution you'd like**

While I do not know how how graphql-codegen merges the schemas together, I would like it to accept the `extend type Query` type format. This might affect the internals (I assume the schema merging is done differently), but perhaps it could be given as a CLI parameter to maintain forward/backward compatibility.

**Describe alternatives you've considered**

An alternative would be to solve the problem in-house, e.g. squash the query/mutation/subscription related schemas together, but I think it defeats the whole purpose of modularisation. The other ways would be to do the compatibility to graphql-modules side.

**Comment by maapteh** [comment]
Hi Lauri, we are using modules too and had a common module. In common module i have the Query and Mutation and in all others i extend. While testing i use a stubbed common module. Maybe this helps you in your current block?

**Comment by kamilkisiela** [comment]
I don't understand (based on description) how GraphQL Modules are related to GraphQL Code Generator. What level we're talking here, loading GraphQL schema or generating types?

Codegen can understand both `extend type Query` and `type Query`.

**Comment by laurisvan** [comment]
@kamilkisiela We are talking about using them together. Now that the interpretation of GraphQL schemas is different on the two, they cannot be used together.

In our stack, we generate GraphQL typings with graphql-codegen and use the generated types together with GraphQL Modules. Correspondingly, the same schemas we generate the types from are needed runtime by graphql-modules, creating the problem.
