### ISSUE TITLE
Add support to the Vue plugin for useLazyQuery 

### ISSUE THREAD

**Issue by DarkLite1** [dotansimha/graphql-code-generator#5258]
**Is your feature request related to a problem? Please describe.**
It seems impossible to start a query on demand as stated in our [StackOverflow question](https://stackoverflow.com/questions/65235192/how-to-trigger-graphql-usequery-on-demand-only-once). 

**Describe the solution you'd like**
Add support for `useLazyQuery` to the Vue plugin.

**Describe alternatives you've considered**
There is currently no way to avoid 2 calls to the graphql backend AFAIK.

Thank you for having a look at this.

**Comment by snowhork** [comment]
@dotansimha 
Hi, I have submitted PR. Could you review it?

https://github.com/dotansimha/graphql-code-generator/pull/7340

**Comment by charlypoly** [comment]
Released in `@graphql-codegen/typescript-vue-apollo@3.2.3` 📦

**Comment by stephane303** [comment]
Is there an example of how to use somewhere ?

**Comment by GitRaymond** [comment]
Was very happy to find this! 

It works for me, except it does not take my input. I have a Ref<string> coming from a input field linked with v-model. 

- [<script lang="ts"> export default defineComponent({
    name: 'CheckOut',
setup() {
        const emailInput = ref('');
        
        const {
            loading,
            result,
            load,
        } = useEmailExistsLazyQuery({ email: emailInput.value });

        const emailExists = useResult(result, null, (data) => data.emailExists);

        return {
            emailInput,
            emailExists,
            load,
            loading,
        };
    },
});
</script>
<template>

                        <div class="">
                            <div v-if="loading">
                                <ClipLoader size="3rem" class="p-1" color="#4299E1"></ClipLoader>
                            </div>
                            <div v-else>
                                <label for="email" >E-mail</label>
                                <input type="text" name="email" id="email" 
                                       v-model="emailInput"
                                       placeholder="E-mail"/>
                            </div>

                        </div>
                        <Button button-text="Continue" class="my-4" @click="load()"
                        ></Button>

                        {{ emailExists }}
                
</template>
] 

Would anyone know why it doesn't take the input from my Ref<string> ?

**Comment by GitRaymond** [comment]
Got it to work:

```
        const emailInput = ref('');

        const {
            loading,
            result,
            load,
        } = useEmailExistsLazyQuery({ email: emailInput.value });

        const emailExists = useResult(result, null, (data) => data.emailExists);

        function getEmailExists() {
            load(undefined, { email: emailInput.value });
        }
```
