### ISSUE TITLE
[experimental-graphql-modules]: option to create d.ts files per module generating

### ISSUE THREAD

**Issue by maapteh** [dotansimha/graphql-code-generator#5260]
I saw in docs i need to import my namespaced typings for a module. I think we can improve this. So not exporting but simply declaring.

```
        presetConfig:
            filename: generated-types/module-types.d.ts
```

Then the file should not be:

```
import * as Types from '../../../generated-types/_graphql';
import * as gm from 'graphql-modules';

export namespace ProductModule {
```

but

```
declare namespace ProductModule {

  import * as Types from "../../../generated-types/_graphql";
  import * as gm from "graphql-modules";
```

Then i dont need to import the type, i can simply use it:
```
import { ProductDataloader } from '../providers/product.dataloader';

export const resolvers: ProductModule.Resolvers = {
    Query: {
        product: async (
            _: any,
            { id }: any,
            { injector }: GraphQLModules.Context,
```

What do you think? You like to explicitly import the namespace, or just to consume it?

**Comment by maapteh** [comment]
Hi Dotan i can pick this up after my holiday. The approach i thought about it:

```
          presetConfig: {
            importBaseTypesFrom: '@types',
            baseTypesPath: 'global-types.ts',
            filename: 'module-types.ts',
            encapsulateModuleTypes: 'none',
          },
 ```
 
 if i see extension of filename is ending with .d.ts then i do stuff like:
 `${shouldDeclare ? 'export' : 'declare'} namespace ${baseVisitor.convertName`
 
 and move the import, good? or you have something else in mind?

**Comment by dotansimha** [comment]
@maapteh sounds good :) We are not generating any code there and only declare types, so it should work.

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/graphql-modules-preset@1.2.0`. Thanks @maapteh

**Comment by maapteh** [comment]
Cool! @dotansimha maybe we can do it everywhere? If the output file is a d.ts then declare namespace :)

Because i was looking in the new typing options with typed document nodes https://the-guild.dev/blog/typed-document-node and it would be even nicer :)

_I'm switching from auto hooks generation to document node because it doesnt leave me with unused lazy hooks in production code since all is in one file and not tree shaked_

**Comment by dotansimha** [comment]
> Cool! @dotansimha maybe we can do it everywhere? If the output file is a d.ts then declare namespace :)

We have it in a few plugins, but not in all, in most cases it causes issues with plugins that generated real code (or even enums..).
