### ISSUE TITLE
Inconsistency between typescript-operations' result type and the actual Apollo query result

### ISSUE THREAD

**Issue by ostrebler** [dotansimha/graphql-code-generator#5266]
**Describe the bug**
When generating `typescript-operations` types for operations, the query's or mutation's fields being called are not marked as optional. For example : 

```typescript
export type UsersQueryData = (
  { __typename?: 'Query' }
  & { users: (
    { __typename?: 'UserPage' }
    & UserRowPageFragment
  ) }
);
```

But in fact, the data returned by Apollo's `useQuery` hook **_can_** be an empty object : 

```typescript
const { data } = useQuery<UsersQueryData, UsersQueryVariables>(USERS_QUERY);

// data can be an empty object, but TS considers it to be UsersQueryData | undefined
```

Thus making the following instruction valid in TypeScript even though it throws a runtime error : 

```typescript
data?.users.items // Ok in TypeScript, but "cannot read property items of undefined" during runtime
```

**Expected behavior**
That `typescript-operations` puts out a result type consistent with Apollo's data, ie. where root fields are optional. Or than an option to do so is provided.

**Comment by dotansimha** [comment]
Hi @ostrebler ,
I'm not sure I understand the issue here. We are generating only the piece of type that represents the return value. The `data` is defined by Apollo itself. 
The `users` is generated based on your GraphQL schema. 

Can you please share a live reproduction of this issue? 

Thanks

**Comment by ostrebler** [comment]
Hello @dotansimha, thanks for your reply. You're right, this might actually be an issue with Apollo : https://github.com/apollographql/apollo-client/issues/7486
