### ISSUE TITLE
[typescript-react-query] Support React Query 3

### ISSUE THREAD

**Issue by zbeyens** [dotansimha/graphql-code-generator#5271]
**Is your feature request related to a problem? Please describe.**

I've updated react-query to version 3 which has breaking changes.

- The generated file is importing `MutationConfig` and `QueryConfig` which no longer exist.
- The generated hooks should have generic types as we can now transform the fetched data into another type.

**Describe the solution you'd like**

Support react-query version 3.

- use `UseMutationOptions` and `UseQueryOptions` instead.
- allow generic types to be able to override the defaults: `useQuery<TData = unknown, TError = unknown, TQueryFnData = TData>` and `useMutation<TData = unknown, TError = unknown, TVariables = void, TContext = unknown>`

**Additional context**

https://react-query.tanstack.com/guides/migrating-to-react-query-3
https://react-query.tanstack.com/guides/migrating-to-react-query-3#query-data-selectors

**Comment by kcwinner** [comment]
My PR addresses the react-query v3 change for the imports.
Also a slight change to the mutations (but perhaps maybe I misunderstood how it was supposed to be used) so that variables are passed to mutate and not at the instantiation.

I haven't taken a look at the generic types yet. I'll try to take a look tomorrow

**Comment by kcwinner** [comment]
Ok @zbeyens do you mean something like this?
Modified v3 custom hook
```
export const useListPostsQueryV3 = <TData, TQueryFnData>(variables: any, options?: UseQueryOptions<TQueryFnData, unknown, TData>) =>
  useQuery<TQueryFnData, unknown, TData>(
    ["ListPosts", variables],
    fetcher<TQueryFnData, ListPostsQueryVariables>(
      ListPostsDocument,
      variables
    ),
    options
  );
```

Example of using the hook
```
const { data, isLoading, refetch } = useListPostsQueryModified<Post[], ListPostsQuery>(null, {
    refetchOnWindowFocus: false,
    select: (posts) => posts.listPosts?.items ?? []
  });
```

**Comment by zbeyens** [comment]
### useQuery

- `useQuery<TData = unknown, TError = unknown, TQueryFnData = TData>`

3 generics: 
```typescript
export const useDocumentItemQueryV3 = <
  TData = DocumentItemQuery,
  TError = unknown,
  TQueryFnData = DocumentItemQuery,
>(
  variables: DocumentItemQueryVariables,
  options?: UseQueryOptions<TData, TError, TQueryFnData>
) =>
  useQuery<TData, TError, TQueryFnData>(
    ['DocumentItem', variables],
    fetcher<TQueryFnData | TData, DocumentItemQueryVariables>(
      client,
      DocumentItemDocument,
      variables
    ),
    options
  );
  ```

I think we can omit the third generic as it should always be `TQueryFnData = DocumentItemQuery`, so with 2 generics:

```typescript
export const useDocumentItemQueryV3 = <
  TData = DocumentItemQuery,
  TError = unknown,
>(
  variables: DocumentItemQueryVariables,
  options?: UseQueryOptions<TData, TError, DocumentItemQuery>
) =>
  useQuery<TData, TError, DocumentItemQuery>(
    ['DocumentItem', variables],
    fetcher<DocumentItemQuery, DocumentItemQueryVariables>(
      client,
      DocumentItemDocument,
      variables
    ),
    options
  );
```

Example of using the hook:

```typescript
// data type is DocumentItemQuery['document_by_pk']
const { data } = useDocumentItemQueryV3<DocumentItemQuery['document_by_pk']>(
    variables,
    { select: (d) => d.document_by_pk } // new option in v3
  )
```

### useMutation

- `useMutation<TData = unknown, TError = unknown, TVariables = void, TContext = unknown>`

2 generics, removing `variables` parameter (see below):

```typescript
export const useDeleteBlockMutation = <TError = unknown, TContext = unknown>(client: GraphQLClient, options?: UseMutationOptions<DeleteBlockMutation, TError, DeleteBlockMutationVariables, TContext>) => 
  useMutation<DeleteBlockMutation, TError, DeleteBlockMutationVariables, TContext>(
    fetcher<DeleteBlockMutation, DeleteBlockMutationVariables>(client, DeleteBlockDocument),
    options
  );
```

### Mutation variables

When doing a mutation, you currently have to pass the variables when declaring the hook:

```typescript
// currently
const { mutate } = useDeleteBlockLazyMutation({ id: 1 }, options);

// should be:
const { mutate } = useDeleteBlockLazyMutation(options);
mutate({ id: 1 });
```

But it's not [the official way react-query is passing variables](https://react-query.tanstack.com/guides/mutations). It's passed in the `mutate` function for more control (e.g. called in a callback), which is not supported with the current fetcher.

Can you please use this fetcher for mutations (not compatible with queries):

```typescript
function mutationFetcher<TData, TVariables>(client: GraphQLClient, query: string) {
  return async (variables?: TVariables): Promise<TData> => client.request<TData, TVariables>(query, variables);
}
```

**Comment by kcwinner** [comment]
@zbeyens Thanks! My generic knowledge is a little lacking. I sweat I tried the `export const useDocumentItemQueryV3 = <TData = DocumentItemQuery, TError = unknown,>(...` example last night and it wasn't working. Fresh day though and it's good to go.

I'll go ahead and rewrite it to drop v2 support. It'll definitely be easier than supporting both.

As for the mutation this appears to work with the current fetch implementations: dropping the variables and calling the function
```
export const useSubmitRepositoryMutation = (
  dataSource: { endpoint: string; fetchParams?: RequestInit },
  options?: UseMutationOptions<SubmitRepositoryMutation, unknown, SubmitRepositoryMutationVariables>
) =>
  useMutation<SubmitRepositoryMutation, unknown, SubmitRepositoryMutationVariables>(
    (variables?: SubmitRepositoryMutationVariables) =>
      fetcher<SubmitRepositoryMutation, SubmitRepositoryMutationVariables>(
        dataSource.endpoint,
        dataSource.fetchParams || {},
        SubmitRepositoryDocument,
        variables
      )(),
    options
  );
```

**Comment by kcwinner** [comment]
PR has been updated. Let me know what you all think

**Comment by zbeyens** [comment]
Perfect! Added a small review

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/typescript-react-query@1.0.0`. Thank you all!
