### ISSUE TITLE
Support configuration of default scalar type for custom scalars

### ISSUE THREAD

**Issue by UselessPickles** [dotansimha/graphql-code-generator#5274]
**Is your feature request related to a problem? Please describe.**

When generating typescript code, I would prefer that the `Scalars` type mapping for custom scalars default to `unknown` rather than `any` (better type safety; forces explicit typecasting; makes missing custom scalar type overrides more obvious). It's conceivable that there may be similar desires when generating code in other languages too.

**Describe the solution you'd like**

A new config option for the typescript code generator that allows me to set the default scalar type to `unknown`. This could possibly be a string config that technically supports any type to be specified, or a boolean config specific to typescript code generation only that restricts the options to `any` or `unknown`. 

I think a string option might be more preferable to generally support this option for other languages. Even within typescript, it may be desirable to use `never` as the default type to more strictly require that custom scalars be given type mappings.

**Describe alternatives you've considered**

Hackishly post-processing the output of the code generator to find/replace `any` with `unknown`. Doesn't seem worth the effort to do it properly.

**Additional context**

I have poked around the source code and found that there is a `buildScalars()` method in `packages/plugins/other/visitor-plugin-common/src/utils.ts` with a `defaultScalarType` parameter that defaults to `'any'`. I don't understand the structure of this project well enough to figure out the "right" way to make the change myself, but I would recommend starting by making the `defaultScalarType` required (no default value; because `any` is not a good default for ALL languages), then following the compiler errors to every usage of `buildScalars()` and make a case-by-case decision on whether to pass a hard-coded value for `defaultScalarType`, or require it to be passed down from the next level up in the call stack, grabbed from config, etc.

**Comment by dotansimha** [comment]
Totally agree :) PRs are welcome ;)

**Comment by andreialecu** [comment]
I'm also interested in this, but I'm thinking of a different approach.

Instead of specifying a custom scalar type, I'd like graphql-code-generator to simply throw an error if it finds a scalar that isn't defined in `scalars`.

It could be a config setting, like `strictScalars: true`.

@dotansimha would you be open to a PR for that?

**Comment by andreialecu** [comment]
I opened a PR that implements both OP's original request and my own variant of it at #5699

**Comment by UselessPickles** [comment]
@andreialecu I like the `strictScalars: true` approach too. It seems so obvious now that you suggested it :)

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/typescript@1.22.0` (and others, if relevant, you can find a list of all publishes packages here: https://github.com/dotansimha/graphql-code-generator/pull/5827 ) Thanks @andreialecu
