### ISSUE TITLE
Codegen writes too many files

### ISSUE THREAD

**Issue by KnisterPeter** [dotansimha/graphql-code-generator#5277]
**Describe the bug**
The types for the cli does state that some hooks (e.g. `afterOneFileWrite`) are not called if the generated file did not change.
This is not the case, files are written all the time. If these files are part of other watchers (e.g. typescript) this will trigger an unncessesary compile cycle.

**To Reproduce**

Have a setup with a graphql file and run the cli.
The hooks will be triggered and the timestamps on the FS changed.

**Expected behavior**
It would be good to not write files which are identical byte-by-byte.

**Comment by dotansimha** [comment]
We do have some code that should prevent writing to the FS during watch mode, when possible. Maybe something is broken and should be improved. 
Thank you for reporting this @KnisterPeter , any chance you can share a reproduction of your setup?

**Comment by KnisterPeter** [comment]
Hi, maybe I've miss understood that. I was not referring to watch mode.
If you like I can propose a PR which implements the missing parts for non watch mode.

**Comment by dotansimha** [comment]
> Hi, maybe I've miss understood that. I was not referring to watch mode.
> If you like I can propose a PR which implements the missing parts for non watch mode.

Sure, this could be amazing. Here's a reference to the piece of code I mentioned: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/generate-and-save.ts#L56-L60 , I think it runs even on non-watch mode, but probably could be improved a lot.  Thank you!

**Comment by charlypoly** [comment]
I don't repro this bug with the latest version of codegen core and CLI.
If the source GraphQL documents and schema are unchanged, the generated file is untouched and the `afterOneFileWrite` hook is not called.
