### ISSUE TITLE
Generate schema types to one file that can be imported for operations types

### ISSUE THREAD

**Issue by TLadd** [dotansimha/graphql-code-generator#5279]
**Is your feature request related to a problem? Please describe.**

I work in a monorepo with a graphql server and multiple packagesthat make requests to the graphql server. Each package defines the queries it needs in a queries.graphql file and I use graphql-code-generator to generate React hooks for each operation defined with appropriate types. This all works great, but there is a lot of duplication in the generated files for each package since the `typescript` plugin generates the types for the whole graphql schema and then the `typescript-operations` plugin uses `Pick` to get the appropriate types based on the defined operations. The main problems I experience right now are:

- git diffs are unnecessarily noisy. End up with the same changeset in each app when making any change to the schema.
- Need to special case the generated file to not trigger running tests in CI for every app when making a non-breaking change to the schema. 

**Describe the solution you'd like**

I would like if I could generate the `typescript` schema types to a single file for my monorepo since it's the same in all cases, and then have the operations I'm using defined per-app, importing from the file with the schema types. This removes all the duplication from each packages' generated file. 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by dotansimha** [comment]
We have `near-operation-file` preset at the moment. it should allow you to generate a single base-types file (from `typescript`) plugin, and then generate TS file per each operation found, and it will maintain imports. You can override the imports generated by this plugin and use scoped imports if you wish to have this done thought your monorepo structure. 

We current don't have a `file-per-each-package` preset, but it should be pretty simple to implement, it's just a different breakdown than `near-operation-file`.  PRs are welcome ;)

**Comment by TLadd** [comment]
Neat, thank you for pointing me to the `near-operation-file` preset. I actually only have one operation file per package, so I think this existing preset will work exactly the same as a `file-per-each-package` would for my purposes.
