### ISSUE TITLE
Error when fragments are separated

### ISSUE THREAD

**Issue by alexk111** [dotansimha/graphql-code-generator#528]
Currently when fragments are stored separately from queries and mutations, the codegen produces a "Unknown fragment ..." error.

Example:

_fragment.ts_
```ts
import gql from 'graphql-tag';

export const userInfo = gql`
  fragment UserInfo on User {
    id
    name
    email
  }
`;
```

_query.ts_
```ts
import gql from 'graphql-tag';

import { userInfo } from './fragment.ts';

export const userQuery = gql`
  query UserQuery($id: ID!) {
    user(id: $id) {
      ...UserInfo
    }
  }

  ${userInfo}
`;
```

**Comment by dotansimha** [comment]
For now, we released an alpha version with a fix for this:
```
Successfully published:
 - graphql-code-generator@0.12.0-alpha.821f12df
 - graphql-codegen-compiler@0.12.0-alpha.821f12df
 - graphql-codegen-core@0.12.0-alpha.821f12df
 - codegen-templates-scripts@0.12.0-alpha.821f12df
 - graphql-codegen-introspection-template@0.12.0-alpha.821f12df
 - graphql-codegen-apollo-angular-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-mongodb-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-react-apollo-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-template@0.12.0-alpha.821f12df
```
@ganeshpms

**Comment by emmanuelbuah** [comment]
Run into this as well but the alpha builds resolve it. Thanks.

**Comment by kamilkisiela** [comment]
#559 should fix it for apollo-angular template

**Comment by ganeshpms** [comment]
Thanks for the Alpha versions. 
Error: Property 'definitions' does not exist on type '{ new (): Document; prototype: Document; }' with Alpha version on the generated code. Which version of typescript is recommended?

**Comment by ganeshpms** [comment]
![fragment](https://user-images.githubusercontent.com/5632736/45218440-3a0e5f80-b26d-11e8-818c-9c081a4f0542.jpg)
As seen in the attachment the `Document` is conflicting with the typescript's dom Document type. Please add the `*namepace*.Docuemnt.definition`. Also, the generated code adds the same fragment multiple time as  I have used the fragment 'Measurement' in multiple places in my query. And finally `,` is missing when there are two are more fragments.

**Comment by RadAcademy** [comment]
I'm getting the same issues with fragments, every query gives me the error.

`ERROR in src/client/app/core/graphql.ts(3064,3): 
error TS2416: Property 'document' in type 'AllChatsGQL' is not assignable to the same property in base type 'Query<Query, Variables>'.
[2]   Type '{ kind: string; definitions: any[]; }' is not assignable to type 'DocumentNode'.
[2]     Types of property 'kind' are incompatible.
[2]       Type 'string' is not assignable to type '"Document"'.
[2] 

src/client/app/core/graphql.ts(3066,31): error TS2339: Property 'definitions' does not exist on type '{ new (): Document; prototype: Document; }'.
[2] src/client/app/core/graphql.ts(3087,3): error TS2416: Property 'document' in type 'ChatByIdGQL' is not assignable to the same property in base type 'Query<Query, Variables>'.
[2]   Type '{ kind: string; definitions: any[]; }' is not assignable to type 'DocumentNode'.
[2]     Types of property 'kind' are incompatible.
[2]       Type 'string' is not assignable to type '"Document"'.
[2] 

src/client/app/core/graphql.ts(3089,31): error TS2339: Property 'definitions' does not exist on type '{ new (): Document; prototype: Document; }'.
[2] src/client/app/core/graphql.ts(3109,3): error TS2416: Property 'document' in type 'SaveChatGQL' is not assignable to the same property in base type 'Mutation<Mutation, Variables>'.
[2]   Type '{ kind: string; definitions: any[]; }' is not assignable to type 'DocumentNode'.
[2]     Types of property 'kind' are incompatible.
[2]       Type 'string' is not assignable to type '"Document"'.`

**Comment by ganeshpms** [comment]
@kamilkisiela I am using `apollo-angular`

**Comment by kamilkisiela** [comment]
@ganeshpms do you use `noGraphqlTag` option?

**Comment by RadAcademy** [comment]
I am also using apollo-angular, I am not doing the 'noGraphqlTag',
"apollo-angular": "^1.3.0",

I was getting the errors using: 

- along with trying to use fragments.
"graphql-code-generator@0.12.0-alpha.821f12df"
"graphql-codegen-apollo-angular-template@0.12.0-alpha.821f12df"

**Comment by dotansimha** [comment]
Fixed in 0.12.0

**Comment by ganeshpms** [comment]
@kamilkisiela , I am not using noGraphQLTag. 

The versions are
    "graphql-code-generator": "^0.12.0-alpha.821f12df",
    "graphql-codegen-apollo-angular-template": "^0.12.0-alpha.821f12df",

Also, the issue #4 that I mentioned is resolved by using `#import './fragment/measurement.gql'` other fixes for #1,#2, #3 are still needed. I just mannually fix them after generated.

**Comment by LawJolla** [comment]
I'm getting this error.  Version 1.0.6 with 1.0.6 versions of typescript and typescript-react-apollo

Works
```
// query.ts

const DealFragment = gql`
  fragment DealFragment on Deal {
    id
  }
`

const DEALS_FOR_VEHICLE = gql`
  query dealsForVehicle($vehicleId: ID!) {
    deals(where: { vehicles_every: { id: $vehicleId } }) {
      __typename
      ...DealFragment
    }
  }
  ${DealFragment}
`
```

```
// query.ts

import gql from "graphql-tag"
import { DealFragment} from "./dealFragment"

const DEALS_FOR_VEHICLE = gql`
  query dealsForVehicle($vehicleId: ID!) {
    deals(where: { vehicles_every: { id: $vehicleId } }) {
      __typename
      ...DealFragment
    }
  }
  ${DealFragment}
`

// dealFragment.ts
import gql from "graphql-tag"

export const DealFragment = gql`
  fragment DealFragment on Deal {
    id
  }
`
```

Returns 
```
$ graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Cannot read property 'onType' of undefined


 Found 1 error

  ✖ src/generated/graphql.tsx
    TypeError: Cannot read property 'onType' of undefined
```

codegen.yml
```
overwrite: true
schema: "../admin-server-nexus/src/generated/schema.graphql"
documents:
  - "src/containers/deals/**/*.tsx"
  - "src/containers/queries/**/*.tsx"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```

Thanks for the amazing work!

**Comment by dotansimha** [comment]
@LawJolla In 1.0.7 we fixed that, now you'll get a more readable error with the missing fragment name. 
If you are still having issues, please open a new issue because this one is closed and outdated.
