### ISSUE TITLE
Syntax Error: Unexpected Name "TermNode" when generating wp-graphql-woocommerce schema

### ISSUE THREAD

**Issue by bkstorm** [dotansimha/graphql-code-generator#5298]
**Describe the bug**
I use wordpress with wp-graphql-woocommerce on the server side, next.js on the client side.
When running `yarn generate` to generate react hooks, it throws an error: `Syntax Error: Unexpected Name "TermNode"`.
I check the schema, there is an interface named TermNode, I don't know why the error occurs, perhaps you know.

**To Reproduce**
Please check the codesandbox.
https://codesandbox.io/s/adoring-villani-oez97?file=/schema.graphql

**Comment by dotansimha** [comment]
Hi @bkstorm 
The schema you are using is compatible only with old versions of GraphQL. It's using `,` as separator for interfaces implementations. In new versions of GraphQL it should be `&`.
