### ISSUE TITLE
rfc: add .graphql operations exports into ts module exports

### ISSUE THREAD

**Issue by cdaringe** [dotansimha/graphql-code-generator#5321]
**Is your feature request related to a problem? Please describe.**

With the current suite of plugins, there is not an idiomatic mechanism to take queries/fragments/mutations from a `.graphql` file and expose those `string` entities in typescript. There are exports for creating `DocumentNode`s, however, my use case just needs the `string` values ported into typescript as values.  If #5303 exported queries piece meal with correct imports to queries, dependent fragments, and did input/output type mappings, I wouldn't need this functionality. However, as it stands, my current workflow is:

- generate types (using operations & the near-file preset)
- post graphql-codegen, copy-and-paste `<source>.graphql` query string into a typescript file, a la `const myQuery: string = <paste>`

It would be ideal to have the code generator _do this work_! 

**Describe the solution you'd like**

- Add a configuration option to the `operations` plugin to allow for adding value exports to the operations file.

**Describe alternatives you've considered**

- An extra plugin

**Additional context**

n/a

**Comment by dotansimha** [comment]
Hi @cdaringe 
You can set `documentMode: string` and it will use `string` for the exported. Does it work for you?

**Comment by dotansimha** [comment]
Closing. @cdaringe feel free to reply if it's still relevant.
