### ISSUE TITLE
expose react-query Query Keys to allow direct interactions with the cache

### ISSUE THREAD

**Issue by Merott** [dotansimha/graphql-code-generator#5334]
**Is your feature request related to a problem? Please describe.**

react-query uses [Query Keys](https://react-query.tanstack.com/guides/query-keys) to manage caching. Methods like [setQueryData](https://react-query.tanstack.com/reference/QueryClient#queryclientsetquerydata) and [getQueryData](https://react-query.tanstack.com/reference/QueryClient#queryclientgetquerydata) need this key.

`typescript-react-query` automatically generates an array-based key, using the query names and variables. Sweet! 💯

The problem is that the key isn't exported from the generated file, which means we have to hard-code it in our own source files, and that can be fragile.

**Describe the solution you'd like**

Not sure what the best solution is here. Here's an idea though… Given this:

```ts
export const useCourses = <TData = CoursesData, TError = unknown>(
  variables?: CoursesVariables,
  options?: UseQueryOptions<CoursesData, TError, TData>,
) =>
  useQuery<CoursesData, TError, TData>(
    ['Courses', variables],
    fetcher<CoursesData, CoursesVariables>(CoursesDocument, variables),
    options,
  )
```

Can we attach a `getKey` method to the hook, like this?

```ts
useCourses.getKey = (variables?: CoursesVariables) => [
  'Courses',
  variables,
]
```

That way, instead of doing this in my React code:

```ts
// no strict typing, and hardcoded 'Courses' 👎
const COURSES_QUERY_KEY = ['Courses', { someVar: myVar }]
```

I can do this:

```ts
// strictly typed variables, and no hardcoded strings 👍
const COURSES_QUERY_KEY = useCourses.getKey({ someVar: myVar })
```

**Describe alternatives you've considered**

The above solution works, but we have to attach something to the hook itself, which isn't ideal.

The alternative would be to expose a method and accept the hook as an input parameter. Specifying strict typings for this would be quite tricky though.

<details>
<summary>See an example...</summary>

```ts
const COURSES_QUERY_KEY = getKey(useCourses, { someVar: myVar })

export const getKey = (
  // specifying the types will be complex -- union types?
  query,
  variables,
) => {
  switch (query) {
    case useCourses: {
      return ['Courses', variables]
    }

    case useAnotherQuery: {
      return ['AnotherQuery', variables]
    }

    default: {
      throw new Error('That was unexpected!')
    }
  }
}
```

</details>

---

**EDIT**: Another possible solution might be to augment the return value of `useQuery` with the generated query key, like so:

```ts
export const useCourses = <TData = CoursesData, TError = unknown>(
  variables?: CoursesVariables,
  options?: UseQueryOptions<CoursesData, TError, TData>,
) => {
  const queryKey = ['Courses', variables]

  return {
    queryKey,

    ...useQuery<CoursesData, TError, TData>(
      queryKey,
      fetcher<CoursesData, CoursesVariables>(CoursesDocument, variables),
      options,
    ),
  }
}
```

**Comment by andrei-datcu** [comment]
Came here to open the same issue, I'm glad to see there are other folks with the same pain :+1: 

I think the first proposed solution (attaching a `getKey` function to the hook) offers the most flexibility while being easier to implement. Returning the key directly from the hook wouldn't be as flexible when the mutations are done from different parts of your app.

**Comment by Merott** [comment]
I've since built myself a workaround. It's working perfectly for me, though you may need to adapt it for your particular setup:

```ts
// graphql-codegen-query-keys.ts

// temporary solution until we have something better:
// https://github.com/dotansimha/graphql-code-generator/issues/5334

import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

import { format, resolveConfig } from 'prettier'

const outFile = join(__dirname, './query-keys.ts')
const graphql = readFileSync(join(__dirname, './graphql.ts'), 'utf-8')

const queriesRegex = /^\s+query ([^( {]+)/gm
const queryNames = []

let matches
while ((matches = queriesRegex.exec(graphql)) !== null) {
  queryNames.push(matches[1])
}

const queryToKeysFunction = (queryName: string) => `
export function ${queryName}QueryKeys(
  variables?: ${queryName}Variables,
) {
  return ['${queryName}', variables]
}
`

const queryNamesVars = queryNames.map(queryName => `${queryName}Variables`)
const imports = `import { ${queryNamesVars.join(', ')} } from './graphql'\n\n`
const queryFunctions = queryNames.map(queryToKeysFunction).join('\n')

resolveConfig(outFile)
  .then(prettierConfig => {
    const content = format(imports + queryFunctions, prettierConfig || {})
    writeFileSync(outFile, content, { encoding: 'utf-8' })
  })
  .catch(e => {
    throw e
  })

```

Add it as an `afterAllFileWrite` hook:

```yml
# graphql-codegen.yml

hooks:
  afterAllFileWrite:
    - yarn graphql-codegen:query-keys
```

```js
// package.json

"scripts": {
  "graphql-codegen:query-keys": "yarn run-ts graphql-codegen-query-keys.ts",
  "run-ts": "ts-node -O '{\"module\": \"commonjs\"}'",
}
```

This'll generate a `query-keys.ts` file, with content like this:

```ts
import { ModuleVariables, CoursesVariables } from './graphql'

export function ModuleQueryKeys(variables?: ModuleVariables) {
  return ['Module', variables]
}

export function CoursesQueryKeys(variables?: CoursesVariables) {
  return ['Courses', variables]
}

```

You can now import these functions from `query-keys.ts`.

If you wanted to go a step further, you could re-export them from `graphql.ts` using [`@graphql-codegen/add`](https://graphql-code-generator.com/docs/plugins/add), so you wouldn't need to import anything directly from `query-keys.ts`:

```yml
# graphql-codegen.yml

plugins:
  # ...
  - add:
      placement: 'append'
      content: "export * from './query-keys'"
```

**Comment by andrei-datcu** [comment]
Attempted an implementation in https://github.com/dotansimha/graphql-code-generator/pull/5423

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/typescript-react-query@1.1.0` :) Thank you all!
