### ISSUE TITLE
Add support for different document-finders

### ISSUE THREAD

**Issue by degroote22** [dotansimha/graphql-code-generator#534]
I'm writing a Dart types generator and I had to use a custom document-finder to find queries inside .dart files.

To do it I forked this lib but would there be a different way to do this?

[Check this diff to see the changes I had to make to make it work. -- (it's an ugly hack)](https://github.com/dotansimha/graphql-code-generator/compare/master...degroote22:master)

**Comment by dotansimha** [comment]
That's interesting. Currently we are thinking about creating a different way to load the documents, and use `require` instead of `fs.readFile`, it will also be a solution for this issue: https://github.com/dotansimha/graphql-code-generator/issues/528 

I'm not familiar with Dart, @degroote22 , can you please explain how Dart files are different from JS or TS files? And how we should load and search them? (as text of require)

**Comment by degroote22** [comment]
Currently the only implementation that uses GraphQL on Dart is [one for Flutter](https://github.com/zino-app/graphql-flutter/) (a framework for building mobile apps).
There isn't a function used to parse all queries as there is in JS, but we could tell people to use an identity function to anotate which strings are GraphQL operations, [like I did here.](https://github.com/degroote22/graphql-flutter/blob/master/example/lib/queries/readRepositories.dart)

With that being said, Dart strings are between " (double quotes), ' (single quote), or """ (three double quotes for multiline string).
And there is a caveat. String interpolation in Dart uses the same sintax as GraphQL variables.
This in Typescript
```typescript
const a = `${variable}`
```
is the same as
```dart
var a = "$variable"
```
in Dart.
So we need to [escape the $ char in the Dart string](https://github.com/degroote22/graphql-flutter/blob/master/example/lib/mutations/addStar.dart) and [strip it away](https://github.com/dotansimha/graphql-code-generator/compare/master...degroote22:master#diff-73cba06a960a4586a1b3b7ca7b879d06R20) from the string on the document-finder.

**Comment by micimize** [comment]
@degroote22 what about writing .gql files and reading them as strings from dart as a stopgap?
Aside from that, I think making operation extraction language-agnostic would best be done through a regex option to match by (like ```/gql`[^`*]`/``` in js) and a string post processing option.

Am also interested in dart in particular, after having had considerable frustrations with react-native

**Comment by degroote22** [comment]
I'd rather have separate front-ends, not a case where one fits all.
This regex can't ignore comments, and this generator does.
One interface where the user would specify a document loader just like we do templates could be a good abstraction.
You'd implement a function that get's the content of a file and can return documents.

**Comment by sandangel** [comment]
So how could I generate Classes and other types for dart using remote graphql schema?

**Comment by micimize** [comment]
@sandangel remote schema usage is in the readme :
` gql-gen --schema http://localhost:3010/graphql --header "Authorization: MY_KEY" ....`

As for template options, idk what state @degroote22's is in, but you could try
[graphql-to-dart](https://github.com/micimize/graphql-to-dart) - still pretty rough around the edges though

**Comment by dotansimha** [comment]
@degroote22 in the new API we have a new feature called `loader`.
You can specify a custom loader that will load your schema/document files.
It's not well documented yet, but it's tested and you can see how to use it here:
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/tests/codegen.spec.ts#L534-L547

**Comment by Parables** [comment]
@sandangel, I am working on a rewrite of my [graphql-codegen-flutter-freezed-classes](https://www.npmjs.com/package/graphql-codegen-flutter-freezed-classes).

finding this issue, I decided to tag you to see if you are still searching for a GraphQL code gen for Flutter, and what are your use cases.
