### ISSUE TITLE
Parse options not being passed to loaders correctly

### ISSUE THREAD

**Issue by danielrearden** [dotansimha/graphql-code-generator#5351]
**Describe the bug**
Users should be able to set parse options (like `experimentalFragmentVariables`) as part of the `config` object and have these passed down to the loaders to be used by the underlying `parse` function from `graphql-js`. Currently setting these options on the `config`, however deeply nested, has no effect. Only setting the options at the root of the configuration file has an effect.

**To Reproduce**

This fails:

```
schema: schema.graphql
documents: src/**/*.query.graphql
config:
  experimentalFragmentVariables: true
```

This works (in the sense that the option is recognized):

```
schema: schema.graphql
documents: src/**/*.query.graphql
experimentalFragmentVariables: true
```

**Expected behavior**
Users should be able to pass the options through the `config` object.

**Comment by dotansimha** [comment]
@ardatan can you please take a look at this one? I think we can use the root `config` and append it to the root object, and it should work, right?

**Comment by ardatan** [comment]
Available in the latest version!
