### ISSUE TITLE
BaseVisitor.ObjectTypeDefinition allows undefined key, but code does not account for that scenario

### ISSUE THREAD

**Issue by jrobber** [dotansimha/graphql-code-generator#5387]
in base-visitor.ts the ObjectTypeDefinition is defined as:
``` 
ObjectTypeDefinition(node: ObjectTypeDefinitionNode, key: number | string | undefined, parent: any): string {
    if (this.config.onlyOperationTypes) return '';
    const originalNode = parent[key] as ObjectTypeDefinitionNode;
    
    ...
```

The third line assumes that key is defined because typescript does not allow undefined to be used as an index.

Ran into this trying to copy/paste modify what you have for my own purposes.  Typescript declares the code invalid and the plugin won't run if you try to do something similar in your own code.

**Comment by dotansimha** [comment]
Thank you @jrobber . Fixed in `master`. There can't be an undefined `key` while visiting GraphQL (I think only for Document, which isn't the case there).
