### ISSUE TITLE
Optional GraphQL fields rendered as T | null | undefined

### ISSUE THREAD

**Issue by marekscholle** [dotansimha/graphql-code-generator#5401]
Say I have the following
```
type Point {
  x: number
  y: number
}
```
As the readme says, the corresponding type is
```
type Point {
  x?: Maybe<number>
  y?: Maybe<number>
}
```
The problem is that there are optional marks on fields (`?`). Why? If I have a `Point` returned from server (e.g. existing, non-null JS object), it can't have missing fields; a correct GraphQL server will include `x` and `y` as `null`s (the correct `Maybe` part), not omit them (incorrect `?`).

This problem showed when I came to a project where I have something like

```
fragment PointFragment on Point {
  x
}
query GetX {
  # `getPoint` returns `Point!`
  getPoint {
    ...PointFragment
  }
}
```
The `data` part for `getX` query has the type `PointFragment`, which also has `x` marked as optional although it can't be `undefined`, only `null`.

The same was fixed in #699. Or do I miss something? At least I think that such behavior should be documented.

**Comment by ardatan** [comment]
You can avoid optionals with  'avoidOptionals' configuration option and change the value of 'Maybe' with 'maybeValue'. I think the following will do the changes you want.
```yml
config:
   avoidOptionals: true
   maybeValue: T | null
```

**Comment by marekscholle** [comment]
Ah, thank you, I missed this feature. I'm surprised this is not the default behavior as that would IMO directly correspond to GraphQL lang, but I understand there may be historical considerations. Closing this issue.

**Comment by levrik** [comment]
@ardatan What actually is the reason behind having `T | undefined | null` instead of `T | null`?
