### ISSUE TITLE
@graphql-codegen/cli has a transitive peer dependency on vue

### ISSUE THREAD

**Issue by maclockard** [dotansimha/graphql-code-generator#5404]
When installing `@graphql-codegen/cli` version `1.20.0` I get a missing peer dependency warning on `vue`.

```
warning "@graphql-codegen/cli > @graphql-tools/git-loader > @graphql-tools/graphql-tag-pluck > @vue/compiler-sfc@3.0.5" has unmet peer dependency "vue@3.0.5".
```

Failing to add this dependency doesn't cause any errors at runtime, but the warning may confuse folks.

**Comment by dotansimha** [comment]
@ardatan can you please take a look and see if we can drop this dependency (or make it optional) in `graphql-tools`? Thanks!

**Comment by ardatan** [comment]
@dotansimha It is an optional dependency already 🤔 
https://github.com/ardatan/graphql-tools/blob/master/packages/graphql-tag-pluck/package.json#L29

**Comment by dotansimha** [comment]
@ardatan You are right, just noticed that. I think we need to have `peerDependenciesMeta` as well (see https://pnpm.js.org/en/package_json#peerdependenciesmeta)

**Comment by frankshwb** [comment]
Since the update of [@graphql-tools/grapqhl-tag-pluck](https://www.npmjs.com/package/@graphql-tools/graphql-tag-pluck/v/6.2.6) to 6.4.1 this breaks some stuff. See also #5486

**Comment by ardatan** [comment]
Fix for this broke other stuff. Closing in favor of #5486  .
