### ISSUE TITLE
Error with generated mutations and queries with react-query plugin. 

### ISSUE THREAD

**Issue by kelvin0712** [dotansimha/graphql-code-generator#5413]
**Describe the bug**
Hi, I am new to graphql code gen so I am not sure if I had the right set up but I got types errors when I tried to generate simple queries and mutations with `@graphql-codegen/typescript-react-query`.

**To Reproduce**
- Sep up GraphQL Code Generator with React-query plugin 
- Run npm command (`npm run generate`).
- Got errors
<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL mutation:

```graphql
mutation Register($firstName: String!, $lastName: String!, $email: String!, $password: String!) {
  register(
    data: { firstName: $firstName, lastName: $lastName, email: $email, password: $password }
  ) {
    user {
      id
      firstName
    }
    errors {
      field
      message
    }
  }
}
```

2. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:4000/graphql'
documents: 'graphql/**/*.graphql'
generates:
  generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-query'
```

3. My `graphql-code/gen` dependencies: 
```
  "@graphql-codegen/cli": "1.20.0",
    "@graphql-codegen/typescript": "1.20.0",
    "@graphql-codegen/typescript-operations": "1.17.13",
    "@graphql-codegen/typescript-react-query": "^1.0.0",
```

**Expected behavior**
- Generated hooks without errors. 

**Environment:**

- NodeJS: v15.5.0

**Additional context**
![image](https://user-images.githubusercontent.com/45527642/104827266-f782d600-58af-11eb-9ae2-c98190dc91f3.png)

**Comment by merelinguist** [comment]
@kelvin0712 What fixed this for you?

**Comment by kelvin0712** [comment]
> @kelvin0712 What fixed this for you?

@merelinguist Hi, it seems like it does not like the `.tsx` file extension, it works when I changed it to `.ts`. I am not sure if this is a bug but when I use Apollo and Urql, they worked well with `.tsx`

**Comment by sushilbansal** [comment]
Yeah; it worked for me as well with .ts extension and does not work with .tsx extension

**Comment by Believer1** [comment]
Yep, worked for me as well

**Comment by ramzizelfani** [comment]
It worked for me too, Thanks
