### ISSUE TITLE
Overriding default scalars

### ISSUE THREAD

**Issue by Slessi** [dotansimha/graphql-code-generator#543]
I have a custom resolver for GraphQL's `ID` scalar, which sends strings to the client but resolves to integers for the server.

I have tried specifying a custom type inside `gql-gen.json`, however I still get `string` inside the generated types.

Is there a way to override the types for default scalars such as `ID`?

```js
// gql-gen.json
{
  "generatorConfig": {
    "scalars": {
      "ID": "number"
    }
  }
}
```

```gql
# schema.graphql
type MyType {
    id: ID!
}
```

```ts
// types.ts
export interface MyType {
 id: string;
}
```

**Comment by Slessi** [comment]
@ardatan Tried as described in [packages/graphql-codegen-cli/README.md](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/README.md) but has no effect.

```js
// gql-gen.json
{
    "primitives": {
        "ID": "number"
    }
}
```

**Comment by Slessi** [comment]
@ardatan That was the first thing I tried. Also tried any other combinations I could think of

**Comment by Slessi** [comment]
@ardatan Minimal repro available here https://github.com/Slessi/gql-gen-primitive-override-repro

**Comment by ardatan** [comment]
Found an issue about CLI's `gql-gen.json` handling.
Thank you!

**Comment by dotansimha** [comment]
For now, we released an alpha version with a fix for this:
```
Successfully published:
 - graphql-code-generator@0.12.0-alpha.821f12df
 - graphql-codegen-compiler@0.12.0-alpha.821f12df
 - graphql-codegen-core@0.12.0-alpha.821f12df
 - codegen-templates-scripts@0.12.0-alpha.821f12df
 - graphql-codegen-introspection-template@0.12.0-alpha.821f12df
 - graphql-codegen-apollo-angular-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-mongodb-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-react-apollo-template@0.12.0-alpha.821f12df
 - graphql-codegen-typescript-template@0.12.0-alpha.821f12df
```

**Comment by Slessi** [comment]
I can confirm that it works for me now with the alpha branch

**Comment by dotansimha** [comment]
Done in 0.12.0
