### ISSUE TITLE
Add `baseOptions` customization for `typescript-react-apollo` plugin.

### ISSUE THREAD

**Issue by dmitrif** [dotansimha/graphql-code-generator#5433]
**Is your feature request related to a problem? Please describe.**
In a codebase that uses multiple GraphQL endpoints, it is common to use `context.clientName` to direct the query to the correct ApolloLink. For example:

```
const client = new ApolloClient({
  link: ApolloLink.split(
    operation => operation.getContext().clientName === "third-party",
    thirdPartyLink, // <= apollo will send to this if context.clientName is "third-party"
    myLink // <= otherwise will send to this
  )
  // other options
});
```

From a codegen perspective, the third party queries are often delimited with a custom gql tag and extracted by configuring `pluckConfig`. The generated hooks / HOC's however currently do not have a way to provide a default context / baseOptions. Current generation example:

```
export function useArticleQuery(baseOptions: ApolloReactHooks.QueryHookOptions<Types.ArticleQuery, Types.ArticleQueryVariables>) {
        return ApolloReactHooks.useQuery<Types.ArticleQuery, Types.ArticleQueryVariables>(ArticleDocument, baseOptions);
      }
```

**Describe the solution you'd like**
It'd be great if there was a way to supply an object to `pluginOptions` such as:
```
config: {
  baseOptions: {
    context: {
      clientName: 'third-party'
    }
  }
}
```

and have the generated code extend the base options for HOC's / Hooks. Example generated:
```
export type const defaultBaseOptions = {
  context: {
    clientName: 'third-party'
  }
}

export function useArticleQuery(baseOptions: ApolloReactHooks.QueryHookOptions<Types.ArticleQuery, Types.ArticleQueryVariables>) {
       const options = deepMerge(defaultBaseOptions, baseOptions);
        return ApolloReactHooks.useQuery<Types.ArticleQuery, Types.ArticleQueryVariables>(ArticleDocument, options);
      }
```

**Describe alternatives you've considered**
1. Doing an AST walk post graphql-codegen run and adding the above.
2. Ignoring the incovinience.

Thank you!

**Comment by trompx** [comment]
On my side I have a custom fetcher (react-query) which takes as first parameter the context. I am looking for a way to have that context passed as the first parameter in the query hooks generated by codegen (not currently possible as per https://graphql-code-generator.com/docs/plugins/typescript-react-query#using-custom-fetcher).
