### ISSUE TITLE
Error: Unknown argument: init

### ISSUE THREAD

**Issue by saostad** [dotansimha/graphql-code-generator#5450]
following docs from [here](https://graphql-code-generator.com/docs/getting-started/installation)

after run `npx graphql-codegen init`
Getting error: `Error: Unknown argument: init`

windows 10
node v14.15.4
npm 6.14.10

**Comment by dotansimha** [comment]
I think on Windows you need to do: `npx graphql-codegen -- init`, can you please try?

**Comment by saostad** [comment]
Same Error message:
```
npx graphql-codegen -- init
Error: Unknown argument: init
```

**Comment by aya-eiya** [comment]
I got same error because of I didn't install `@graphql-codegen/cli`.

fixed by just install it.

```
npm install -D @graphql-codegen/cli 
```

**Comment by saostad** [comment]
> I got same error because of I didn't install `@graphql-codegen/cli`.
> 
> fixed by just install it.
> 
> ```
> npm install -D @graphql-codegen/cli 
> ```

the error message happens in the npx command.
it supposed to work as a one-line command.

**Comment by aya-eiya** [comment]
@saostad 
ok I see, you don't want to install CLI package.
then you can use the CLI package without install the package with npx -p option.

```
npx -p @graphql-codegen/cli graphql-codegen init
```

but the command will add some packages to your package.json, I think it's okay to add the CLI package as well.

**Comment by ardatan** [comment]
@saostad You need to install `@graphql-codegen/cli` package to use init command. That command will already add bunch of codegen packages in your project so I don't see any point to avoid installing `@graphql-codegen/cli`.

**Comment by JanCVanB** [comment]
I think I had the same misunderstanding that @saostad had - after reading the first two sections of [that documentation page](https://graphql-code-generator.com/docs/getting-started/installation), I thought running the one-line shell command in the second section was an alternative to running the two lines of shell commands in the first section. After reading this issue and re-reading that documentation page, I now see that following the first section is mandatory, whether or not you choose to follow the second section. I don't know how the language on that documentation page could be improved, but I think it is slightly ambiguous. Thank you!

**Comment by callumgare** [comment]
This tripped me up too. For better or worse people will skim though it to find commands that will get them up and running quickly and then refer back the docs as needed (no one has time to read all the documentation thoroughly of every new project they try). Because of this adding "After installing those dependencies, " while it might help some people isn't fool proof (as a practiced fool I can vouch for this). My suggestion would be to change the command in the docs to the one @aya-eiya mentioned:
```
npx -p @graphql-codegen/cli graphql-codegen init
```

**Comment by HadiAlizade77** [comment]
probably I'm late, but I managed to run the generator from the bin folder by using

`./node_modules/.bin/graphql-code-generator init`

also make sure your calling graphql-code-generator and not graphql-codegen

**Comment by kitravee** [comment]
I have got the same issue

In my case package.json have 2 packages `@graphql-codegen/cli` and `graphql-codegen` **(duplicate)**
**fix by remove package** `graphql-codegen`
