### ISSUE TITLE
Clean install following documentation requires a lot more extra packages

### ISSUE THREAD

**Issue by leroy0211** [dotansimha/graphql-code-generator#5486]
**Describe the bug**
When following the documentation on a clean project, I needed to install the following packages to get things running. 
Both for the wizard and for running the generator.

* `@vue/compiler-dom`
* `@vue/compiler-ssr`
* `hash-sum`
* `magic-string` 
* `merge-source-map`
* `postcss`
* `postcss-selector-parser`
* `lru-cache`

**To Reproduce**

```
yarn init -y 
yarn add graphql
yarn add -D @graphql-codegen/cli
yarn graphql-codegen init
```

Then you will get the first missing package, and so on.

**Expected behavior**
Installing the generator following the documentation, without any additional packages required to install.

**Environment:**

- OS: MacOS
- `@graphql-codegen/cli`: 1.20.1
- NodeJS: v12.16.1

**Comment by pakatagoh** [comment]
Just ran into the same issue with a deployment on vercel

![image](https://user-images.githubusercontent.com/37908805/106769316-c5c38a80-6677-11eb-918d-f0d73bae1b63.png)

graphql-codegen deps in my package.json if it helps
```
  "@graphql-codegen/cli": "^1.13.1",
    "@graphql-codegen/fragment-matcher": "^1.7.0",
    "@graphql-codegen/introspection": "^1.7.0",
    "@graphql-codegen/near-operation-file-preset": "^1.17.11",
    "@graphql-codegen/typescript": "^1.7.0",
    "@graphql-codegen/typescript-document-nodes": "^1.7.0",
    "@graphql-codegen/typescript-operations": "^1.7.0",
    "@graphql-codegen/typescript-react-apollo": "^1.7.0",
```

**Comment by benedict-jackson** [comment]
I just tried to set this up with react and apollo and having the same issue. I'm working on a react project, it seems silly that I'd be required to install multiple vue packages.

**Comment by benedict-jackson** [comment]
seems like it's a problem with the graphql-tools dependency? Someone's put an issue on that repo with the same problem.

https://github.com/ardatan/graphql-tools/issues/2542

**Comment by leroy0211** [comment]
Workaround: 

Install version 6.4.0 of `@graphql-tools/graphql-tag-pluck`

```
"devDependencies": {
    "@graphql-codegen/cli": "1.20.0",
    "@graphql-tools/graphql-tag-pluck": "6.4.0"
  }
```

**Comment by frankshwb** [comment]
The graphql-tag-pluck got updated today - and it seems to add some Vue and other dependencies.
[See versions](https://www.npmjs.com/package/@graphql-tools/graphql-tag-pluck/v/6.2.6)

The workaround by keeping the latest 1.20.1 version is:
To you package.json add:

`
 "resolutions": {
    "@graphql-tools/graphql-tag-pluck": "6.4.0"
  },
`

This uses the yarn Selective Versions RFC "resolutions" to override nested dependency versions.

**Comment by dep-dt** [comment]
For what it's worth, using `"resolutions": { "@graphql-tools/graphql-tag-pluck": "6.4.0" },` didn't work for me. I add to manually add the following `devDependencies`.

```
"devDependencies": {
    "@cloudvox/mocha-config",
    "@vue/compiler-dom",
    "@vue/compiler-ssr",
    "hash-sum",
    "magic-string",
    "merge-source-map",
    "postcss",
    "postcss-selector-parser"
}
```

**Comment by ardatan** [comment]
We're aware of the issue :) Patch version will be available in a few minutes
`@graphql-tools/graphql-tag-pluck@6.4.2`

**Comment by ardatan** [comment]
@leroy0211 @dep-dt @frankshwb @benedict-jackson @pakatagoh Could you reinstall depedencies, make sure `6.4.2` is installed and working fine?

**Comment by natac13** [comment]
6.4.2 is working

**Comment by dep-dt** [comment]
agreed, all good here too.
