### ISSUE TITLE
Possible issue with dependencies in the codegen website

### ISSUE THREAD

**Issue by tvvignesh** [dotansimha/graphql-code-generator#5499]
**Describe the bug**
I was trying to get the codegen website running locally by running a `yarn install` at the root and then doing a `yarn start` within the website folder and after doing it, this is the error I get (even tried doing a `yarn install` within the website folder just to be safe):

<img width="743" alt="1" src="https://user-images.githubusercontent.com/1165845/107021626-632ed380-67ca-11eb-8b92-647a27bfadf9.PNG">

<img width="868" alt="2" src="https://user-images.githubusercontent.com/1165845/107021643-6924b480-67ca-11eb-89b0-2ec374921524.PNG">

The packages are installed but is hoisted to the `node_modules` directory at the root folder and doesn't lie within the website folder and I guess that is why the packages are not found by the file.

Using yarn version `v1.22.10`

**To Reproduce**
- Clone the repo
- Run `yarn install` at root
- Run `yarn start` within the website folder and you get the error.

Btw, I also tried copying the website folder separately to see if that would work in isolation, and this is the error I get when doing that:

<img width="619" alt="3" src="https://user-images.githubusercontent.com/1165845/107022069-f405af00-67ca-11eb-8096-9a35bb164a51.PNG">

And if I try running `yarn build:website` like in the CI pipeline, this is the error I get:

<img width="661" alt="4" src="https://user-images.githubusercontent.com/1165845/107022930-f6b4d400-67cb-11eb-8b67-f0982d798377.PNG">

Thanks.

**CC:** @Urigo

**Comment by ardatan** [comment]
@tvvignesh You need to build plugins and stuff first before running/building website, just like we do in the CI.
https://github.com/dotansimha/graphql-code-generator/blob/master/.github/workflows/website.yml#L22

**Comment by tvvignesh** [comment]
@ardatan Just did a `yarn build` from the root dir and ran it again. It worked. 👍
