### ISSUE TITLE
CODEGEN_SCHEMA_NO_NAMESPACES is not working

### ISSUE THREAD

**Issue by stevefan1999-personal** [dotansimha/graphql-code-generator#550]
### Reproduction
On Windows and using GraphLOC as an example, if I ran `cross-env CODEGEN_SCHEMA_NO_NAMESPACES=true CODEGEN_PRINT_TIME=true gql-gen --schema https://api.graphloc.com/graphql --template typescript --out ./typings/types.ts`, not only the time is printed, but the namespace is still generated.

**Comment by dotansimha** [comment]
@ardatan can you please take a look? I think it's related to your work there

**Comment by ardatan** [comment]
Maybe, it is related how env variables works on Windows. Could you try to set env variables in Windows way ( using `set` )?
AFAIK, Windows doesn't allow defining env variables like you do, so it'd better to use `gql-gen.json` instead of using env variables.

**Comment by LancelotP** [comment]
@stevefan1999-personal I've had the same problem on OSX either via cross-env or setenv or export.

I finally got it working with the file `gql-gen.json` in root :

```json
{
  "generatorConfig": {
    "noNamespaces": true
  }
}
```

**Comment by ardatan** [comment]
I think the name of env variable is wrong in the documentation. It's supposed to be CODEGEN_NO_NAMESPACES.
