### ISSUE TITLE
[typescript-resolvers] does not take into consideration the `mappers` when typing the `args` of resolvers.

### ISSUE THREAD

**Issue by madeken** [dotansimha/graphql-code-generator#5562]
Reproducible Example: https://codesandbox.io/s/cranky-knuth-g5tst?file=/types.ts

Imagine mapping the `ID` to `GraphId` with something simple like this:
https://codesandbox.io/s/cranky-knuth-g5tst?file=/apollo-graph-id.ts 

This will affect both the arguments and returns of resolvers. However the `mappers` in `typescript-resolvers` is not typing the arguments which, in the reproducible example, the function `user` takes an `id` which `typescript-resolvers` types as a `string` while in reality I'm passed a `GraphId`

**Comment by ardatan** [comment]
@madeken You should use 'scalars' for scalar types

**Comment by madeken** [comment]
Ah thanks, I didn't see that option. It might make sense to give a warning when someone tries to map a scalar?
