### ISSUE TITLE
Support for input argument deprecation

### ISSUE THREAD

**Issue by dmateiu** [dotansimha/graphql-code-generator#5565]
**Is your feature request related to a problem? Please describe.**

In the version 15.4.0 the graphql-js package introduced the support for input argument deprecation.
In version 15.5.0, the introspection query was extended and the `IntrospectionOptions` type was extended by the option `inputValueDeprecation`. See [IntrospectionOptions](https://github.com/graphql/graphql-js/blob/bb58eb95482e5538d94fd70b5a2877b1a8d9bec4/src/utilities/getIntrospectionQuery.d.ts#L5)

The `introspection` plugin, does not include the new config variable. As a result, this new feature is not usable with the graphql-code-generator.

**Describe the solution you'd like**

Add an `inputValueDeprecation` field to the [IntrospectionPluginConfig](https://github.com/dotansimha/graphql-code-generator/blob/bb16e3829593eeff77f65f7be24083eab4aae88f/packages/plugins/other/introspection/src/index.ts#L9) and include the value on the `introspectionFromSchema` call, see [here](https://github.com/dotansimha/graphql-code-generator/blob/bb16e3829593eeff77f65f7be24083eab4aae88f/packages/plugins/other/introspection/src/index.ts#L65)

**Comment by ardatan** [comment]
Would you create a PR for that change?

**Comment by dmateiu** [comment]
I'd be happy to do that, however, the link to your [Contributor Workflow Guide](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) seems to be broken, so I'm not sure how I can contribute.

**Comment by ardatan** [comment]
Fixed :)

**Comment by dmateiu** [comment]
@ardatan I noticed, that the current implementation does include the deprecated `inputFields` by default. 

I got confused by the fact, that [IntrospectionOptions](https://github.com/graphql/graphql-js/blob/bb58eb95482e5538d94fd70b5a2877b1a8d9bec4/src/utilities/getIntrospectionQuery.d.ts#L5) describe the `inputValueDeprecation` option as `false` by default, which is applicable for the [getIntrospectionQuery](https://github.com/graphql/graphql-js/blob/bb58eb95482e5538d94fd70b5a2877b1a8d9bec4/src/utilities/getIntrospectionQuery.js#L25) method.

However, the `introspection-plugin` uses the [introspectionFromSchema](https://github.com/graphql/graphql-js/blob/bb58eb95482e5538d94fd70b5a2877b1a8d9bec4/src/utilities/introspectionFromSchema.js#L32) method, which accepts the `IntrospectionOptions`, but the implementation sets the `inputValueDeprecation` option to `true` by default.

Furthermore, `apollo-server` does not support the deprecation of input fields yet, which I wasn't aware of before.

**Comment by dmateiu** [comment]
You can close this ticket and I'd suggest creating a PR with the changes I've already made, if that's wanted. 
The changes would
* add the deprecation reason of the input field to the generated types. Similar to what is already in place for Fields 
* allow you to exclude deprecated input fields via the configuration

**Comment by dotansimha** [comment]
@dmateiu I'm closing. Feel free to open a PR, we always encourage contributions :)
