### ISSUE TITLE
Support for Apollo clientside query via @client without clientside schema

### ISSUE THREAD

**Issue by emmanuelbuah** [dotansimha/graphql-code-generator#557]
`gql-gen` errors when generating types for clientside graphql queries (with `@client` directive) where clientside schema isn't defined or needs to. Apollo allows you to define clientside queries with or without a clientside schema.

**Comment by kamilkisiela** [comment]
We're planning to add this feature but haven't started working on it yet

**Comment by kamilkisiela** [comment]
#561

**Comment by kamilkisiela** [comment]
@emmanuelbuah Defining GraphQL Schema in Apollo is optional but to generate types and queries you need to have it defined. The tool can't say if a field is a string or a number.

**Comment by emmanuelbuah** [comment]
@kamilkisiela I completely agree. Since apollo allows the user to either define a schema or not for @client queries. I think the required behavior should be to **not** throw an error if it sees a query @client directives without a match graphql schema definition. Currently, it throws an error.

**Comment by dotansimha** [comment]
Please refer to my PR in ReactQL: https://github.com/leebenson/reactql/pull/129
It shows a good example for how to use the codegen with remote schema and local schema, along with `apollo-link-state` and `@client` directive.
