### ISSUE TITLE
The generated type is not suitable for resolvers

### ISSUE THREAD

**Issue by Darfion** [dotansimha/graphql-code-generator#5583]
I have problems with graphql-code-generator. The generated type is not suitable for resolvers. I get an error in the line `viewer: () => ({`.

> Type '() => { createUser: () => { lastName: string; firstName: string; nickName: string; email: string; gender: UserGender; age: string; }; }' is not assignable to type 'Resolver<ResolverTypeWrapper<Pick<ViewerMutation, "__typename"> & { createUser: UnconfirmedUser | Promise<UnconfirmedUser> | LetterNotSent | Promise<...> | WarningDuplicateEmail | Promise<...>; }>, {}, MyContext, {}>'.
 

this my code

***codegen.yml***

    overwrite: true
    schema: "http://localhost:8000/graphql"
    documents: null
    generates:
      src/toolses/generated/resolversTypes.ts:
        plugins:
          - "typescript"
          - "typescript-resolvers"
        config:
          useIndexSignature: true
          contextType: ../../resolvers/typescript-resolvers#MyContext
          customResolverFn: ../../resolvers/typescript-resolvers#customResolverFn

***typescript-resolvers.ts***

    export type MyContext = {
      res: Response;
      req: Request;
      admin: any;
      currentUser: string;
      models: any;
    };
    
    export type customResolverFn<
      TResult,
      TParent = {},
      TArgs = {},
      TContext = {}
    > = (
      parent: TParent,
      args: TArgs,
      context: TContext,
      info: GraphQLResolveInfo
    ) => Promise<TResult | Error> | TResult | Error;

***schema.ts***

    union UnconfirmedUserUnion =
          UnconfirmedUser
        | LetterNotSent
        | WarningDuplicateEmail
    
      enum UserGender {
        MALE
        FEMALE
        OTHER
      }
    
      type UnconfirmedUser {
        lastName: String!
        firstName: String!
        nickName: String!
        email: Email!
        gender: UserGender!
        age: String!
      }
    
      type LetterNotSent {
        lastName: String!
        firstName: String!
        nickName: String!
        email: Email!
        gender: UserGender!
        age: String!
      }
    
      type WarningDuplicateEmail {
        message: String!
        lastName: String!
        firstName: String!
        email: Email!
        gender: UserGender!
        age: String!
      }
    
      input CreateUserInput {
        lastName: String!
        firstName: String!
        email: Email!
        gender: UserGender!
        age: String!
        password: String!
      }
    
      type Query {
        viewer: String
      }
    
      type Mutation {
        viewer: ViewerMutation
      }
    
      type ViewerMutation {
        createUser(newUser: String!): UnconfirmedUserUnion!
      }

***resolvers.ts***

    const resolvers:Resolvers  = {
      ...scalarsType,
      ...InterfacesAndUnions,
      Query: queryResolvers,
      Mutation: {
        viewer: () => ({
          createUser: () => ({
            lastName: "string",
            firstName: "string",
            nickName: "string",
            email: "string",
            gender: UserGender.FEMALE,
            age: "string",
          }),
        }),
      },
    };

How can this error be corrected ?

**Comment by dotansimha** [comment]
You have too many nesting levels in this one: 

```
 Mutation: {
    viewer: () => ({
      createUser: () => ({
        lastName: "string",
        firstName: "string",
        nickName: "string",
        email: "string",
        gender: UserGender.FEMALE,
        age: "string",
      }),
    }),
  },
```

You should have: 

```
 MutationViewer: {
  createUser: () => ({
        lastName: "string",
        firstName: "string",
        nickName: "string",
        email: "string",
        gender: UserGender.FEMALE,
        age: "string",
      })
 },
 Mutation: {
    viewer: () => ({}),
  },
```

Probably with some added `mappers`, or changed to the default mappers. 

If you wish us to take a deeper look, please provide a complete reproduction, as stated in the issue template.
