### ISSUE TITLE
[named-operation-object]: Add flag to toggle `as const`

### ISSUE THREAD

**Issue by stramel** [dotansimha/graphql-code-generator#5597]
**Is your feature request related to a problem? Please describe.**

When using the `named-operation-object` plugin, all types widen to `string`.

**Describe the solution you'd like**

It would be nice to be able to have a flag, for example `useConsts`, that would apply `as const` to the end of each string so that the intellisense would display the name and typings could be more strict.

**Describe alternatives you've considered**

Just dealing with `string`

**Additional context**

**Comment by dotansimha** [comment]
Implemented in https://github.com/dotansimha/graphql-code-generator/commit/65cc0185851f331752348541f679aacd194c21f9 .

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/named-operations-object@1.18.0`

**Comment by stramel** [comment]
Thanks for the quick implementation!
