### ISSUE TITLE
graphql-request's unnecessary `print` function call

### ISSUE THREAD

**Issue by AradAral** [dotansimha/graphql-code-generator#5614]
The `request` function of the [graphql-request](https://github.com/prisma-labs/graphql-request) library accepts either a `DocumentNode` or a `string` as the query. If a `DocumentNode` is passed, it will convert it into a `string` by calling graphql's `print` function internally:
https://github.com/prisma-labs/graphql-request/blob/a8d99f5cdbe57786ecb8d99c88175599608d2fc6/src/index.ts#L207-L211
So there is no need here for us to call the `print` function to convert the query to a `string` before passing it to the `request` function.
https://github.com/dotansimha/graphql-code-generator/blob/4ea2ccd0f7dcb9486145bd7abec6804f6d756f26/packages/plugins/typescript/graphql-request/src/visitor.ts#L103

I was about to create a PR for this but I read that you said you should always post an issue before creating a PR. So I'm waiting for your response.

**Comment by ardatan** [comment]
Thanks for reporting this :) A PR would be awesome!

**Comment by AradAral** [comment]
Sure :)

**Comment by ardatan** [comment]
Sorry I missed some point. Is `print` still used if you define `documentMode: string` in your configuration?

**Comment by AradAral** [comment]
@ardatan 
> Is print still used if you define documentMode: string in your configuration?

No it isn't. It's clear from the condition here:
https://github.com/dotansimha/graphql-code-generator/blob/4ea2ccd0f7dcb9486145bd7abec6804f6d756f26/packages/plugins/typescript/graphql-request/src/visitor.ts#L103

> Your PR breaks the cases when user choose another documentMode except string.

Well, again, graphql-request converts `DocumentNode` to `string` internally. So it doesn't break those.

**Comment by ardatan** [comment]
Ok ok :) My mistake

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-graphql-request@3.1.0`

**Comment by cmonty** [comment]
👋🏻 

This change breaks the generated code when using `rawRequest: true` since `rawReqest` does not call `print` like `request`
