### ISSUE TITLE
Query Key isnt set in React Query

### ISSUE THREAD

**Issue by TkinterinShanghai** [dotansimha/graphql-code-generator#5630]
**Describe the bug**
I can set the Query Hash for a query in the options, but not the key itself

**To Reproduce**
```
  const { data, isFetched } = useExercisesQuery(client,{ isPrivate },{ queryKey: "private", queryHash: '["Exercises", "private"]'
    }
```
In this example the Hash is set, the query key isnt

**Comment by dotansimha** [comment]
Hi @TkinterinShanghai ,
Thank you for reporting this. We have a very strict policy regarding issues reporting. In this issue, we have a missing version of codegen, plugins, version of react-query, a reproduction of that issue, and the expected output. 

I'm closing, feel free to ping me when the missing details are available and we would love to take a look.

**Comment by TkinterinShanghai** [comment]
I have actually found out why that is

This is the code thats generated by Graphql Code Generator. As seen Graphql Code Generator creates a key that cannot be modified unless variables are passed to the request. So it would be nice if additional values can be passed to the key, because that would be possible with plain React Query

```
export const useExercisesQuery = <
      TData = ExercisesQuery,
      TError = unknown
    >(
      client: GraphQLClient, 
      variables: ExercisesQueryVariables, 
      options?: UseQueryOptions<ExercisesQuery, TError, TData>
    ) => 
    useQuery<ExercisesQuery, TError, TData>(
      ['Exercises', variables],
      fetcher<ExercisesQuery, ExercisesQueryVariables>(client, ExercisesDocument, variables),
      options
    );
```

**Comment by dotansimha** [comment]
The key is defined by the GraphQL operation name you are using. Why not change that? What's the use case for allowing this to be modified externally?

**Comment by TkinterinShanghai** [comment]
I have lots of queries. Some are private, only accessible if the user is logged in and some are public. Instead of checking all the queries on whether they are private or public, I'd like to just assign them an extra value in their key so that I just have to invalidate all the queries including the keyword "private" in their name. With vanilla react-query that would be possible and I think it's a useful feature. It's nice that you take care of adding the variables to the key but additional fields would be useful, too
