### ISSUE TITLE
[Question] Non-nullable values in custom types

### ISSUE THREAD

**Issue by alexk111** [dotansimha/graphql-code-generator#566]
Some example code to provide a context for the question:

```ts
export const postTypes = gql`
  type Post {
    id: ID!
    author: PostAuthor!
  }
  extend type Query {
    post(id: ID!): Post
  }
`;
```

For this code the codegen will generate ```QueryResolvers.PostResolver``` function type which requires ```author``` value in a returned object. But what if ```author``` is provided by ```PostResolvers.AuthorResolver```? Currently we have two options:

1. always put ```author: null``` in all returned objects for queries and mutations returning ```Post```
2. make author a nullable value: ```author: PostAuthor```

Is there is a better way for that?

**Comment by dotansimha** [comment]
@kamilkisiela what do you think?

**Comment by kamilkisiela** [comment]
It's possible right now to customize the shape of the result, but only on field resolvers. To do that user would have to remove the interface of the whole type resolver and use interface per field.

```ts
export const Post: {
  author: PostResolvers.AuthorResolver<Result>;
} = {
  author() { ... }
}
```

We could support like a map of results that will be specified in the interface of the GraphQL Type, as a generic type but I don't think it's the best idea.

We could also mark all results as any but this way we would have only interfaces for Context, Arguments and the Type itself.
