### ISSUE TITLE
[typescript-document-nodes] don’t import gql from "graphql-tag" if not used

### ISSUE THREAD

**Issue by lensbart** [dotansimha/graphql-code-generator#5695]
Hi, first of all, thanks for creating this tool. It works really well out-of-the-box! However, I think the experience for new users can be streamlined further by the following.

The default configuration of TypeScript (when initialising via `--init`) includes `"noUnusedLocals": true`, so `tsc` fails when it encounters a file generated by `typescript-document-nodes` if no documents are included (e.g. backend project).

The title suggests the desired change.

Current workaround: including `documentMode: external` in the config options.

**Comment by dotansimha** [comment]
@lensbart can you please share a reproduction? didn't manage to reproduce this issue with latest version.

**Comment by lensbart** [comment]
I’ll close the issue, because my configuration has evolved in the meantime, and I see that I’m neither using `documentMode: external` nor setting `noUnusedLocals: true`.
