### ISSUE TITLE
[typescript-graphql-files-modules] doesn’t work if no documents are specified

### ISSUE THREAD

**Issue by lensbart** [dotansimha/graphql-code-generator#5696]
Hello!

`typescript-graphql-files-modules` doesn’t seem to work for backend-only projects, i.e. projects with no `document` specified (because there’s only a schema, but no queries or mutations). I think it should still generate output under these conditions.

Thanks!

**Comment by dotansimha** [comment]
@lensbart If this is still relevant, please share a reproduction or expand the description with an example.
