### ISSUE TITLE
Support postprocessing for plugins

### ISSUE THREAD

**Issue by lanwin** [dotansimha/graphql-code-generator#5702]
**Is your feature request related to a problem? Please describe.**

As described in https://github.com/dotansimha/graphql-code-generator/issues/5701 I wanted to wrap all document nodes with a function, since the react-query plugin did not support document mode gql-tag. I played with creating a custom plugin to so but was not able to do it since there is currently no api for such scenario. 

**Describe the solution you'd like**

As far as I currently know, plugins can only contribute new pieces to the generated document. But sometime it would be helpful to have plugins that reprocess the document right before it gets written.

To do so I would like to suggest to extend the Output type like so:

```javascript
return {
  postprocess: (content)=>content.replace("A","B")
}
```

This way there could a replace utility plugin.

**Describe alternatives you've considered**

It would be possible to create a custom hook to do so, but in general it would be a good addition for plugins.

**Comment by ardatan** [comment]
You can extend the plugin by creating a custom plugin by yourself like below;
```yml
schema: my-schema.graphql
documents: './src/**/*.graphql'
generates:
  output.ts:
    - my-plugin.js
```

```js
const somePlugin = require('@graphql-codegen/some-plugin';

module.exports = {
  ...somePlugin,
  async plugin: (...args) => {
    const result = somePlugin.plugin(...args);
    // do whatever you want with result
    return result;
  }
}
```

**Comment by lanwin** [comment]
> 
> 
> You can extend the plugin by creating a custom plugin by yourself like below;
> 
> ```yaml
> schema: my-schema.graphql
> documents: './src/**/*.graphql'
> generates:
>   output.ts:
>     - my-plugin.js
> ```
> 
> ```js
> const somePlugin = require('@graphql-codegen/some-plugin';
> 
> module.exports = {
>   ...somePlugin,
>   async plugin: (...args) => {
>     const result = somePlugin.plugin(...args);
>     // do whatever you want with result
>     return result;
>   }
> }
> ```

Thanks @ardatan that is what I end up doing to solve my problem. 

But I think in general it would be helpful when the plugin model could support such scenario out of the box. 

I also write this post about a suggestion to change the plugin model in general https://github.com/dotansimha/graphql-code-generator/discussions/5706.
