### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by kallaspriit** [dotansimha/graphql-code-generator#571]
I'm using the `generate()` API in my own tooling and it would be nice if one could intercept or disable the default log outputs.

The generate function could either accept optional `logger` parameter that matches https://github.com/kallaspriit/ts-log etc and defaults to the winston implementation you're already using. This way the log messages could be intercepted and either ignored or piped elsewhere.

Simpler alternative would be to just accept a `"silent": true` parameter that does not call the log statements.

**Comment by dotansimha** [comment]
Sounds good. I'm on it :)

**Comment by dotansimha** [comment]
Done in https://github.com/dotansimha/graphql-code-generator/commit/c26606593d1a97dc61750dfc29f85ef7dd6bc006

**Comment by dotansimha** [comment]
Done in 0.12.0
