### ISSUE TITLE
Internal values for enums

### ISSUE THREAD

**Issue by Slessi** [dotansimha/graphql-code-generator#576]
Hi,

Currently I think it isn't possible to use [internal values](https://www.apollographql.com/docs/graphql-tools/scalars.html#internal-values) for enums.

I think it would be pretty pretty easy to support though, similar to the scalars fix at #444, can just have an `enums` key (with imports in `prepend`) and not generate types for those enums.

**Comment by Slessi** [comment]
@dotansimha will try, no idea how this project actually works havent looked at source code but shouldnt be a problem

**Comment by dotansimha** [comment]
@Slessi Thanks! 
And we are here to help, feel free to contact us if you're having issues :)
