### ISSUE TITLE
Runtime error with typescript config file

### ISSUE THREAD

**Issue by tobiasdiez** [dotansimha/graphql-code-generator#5762]
**Describe the bug**
If the configuration is part of a typescript `graphql.config.ts` file, then running `graphql-codegen` results in the typescript error "Failed to compile TypeScript: Unexpected token export"

**To Reproduce**
1. Have a simple `graphql.config.ts` configuration file with a `codegen` block
2. Add a simple `tsconfig.json` with pretty standard ESnext/node config
```
    "target": "ES2018",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable",
      "DOM"
    ],
```
3. Run `graphql-codegen`
4. Get `Failed to compile TypeScript: Unexpected token export` error

https://codesandbox.io/s/nameless-sound-qx8he
<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
No error

**Environment:**

- OS: Windows 10
- `@graphql-codegen/...`: 1.21.3
- NodeJS: ?

**Comment by ardatan** [comment]
TypeScript files cannot be imported within NodeJS modules unless you have something like ts-node.
You can try to use "-r ts-node/register" flag with codegen to have ts files recognized by CommonJS.

**Comment by tobiasdiez** [comment]
Thanks for the suggestion! However, running `graphql-codegen -r ts-node/register` with and without `"ts-node": "ts-node --compiler-options \"{\"\"module\"\":\"\"CommonJS\"\"}\""` doesn't work - I still get the same error.

In fact, if I overwrite tsnode to something that doesn't exist, then I still get the same error message - so I suspect graphql-codegen isn't picking the require flag.

**Comment by ardatan** [comment]
This is not issue related to Codegen or GraphQL Config. `ts` files aren't recognized by NodeJS without ts-node and ts-node respects your tsconfig. You can write a script that overwrites `module` coming from your `tsconfig`. If you still think something is wrong with codegen, please share a minimal reproduction on CodeSandbox so we can help you better :)

**Comment by ardatan** [comment]
Or you can use a custom tsconfig file for CJS
See this working example; https://codesandbox.io/s/amazing-dew-kggr0?file=/graphql.config.ts

**Comment by tobiasdiez** [comment]
Thanks, having a special tsconfig with `"module": "commonjs"` worked nicely!

I still find it a bit strange that overwriting `"ts-node": "ts-node --compiler-options \"{\"\"module\"\":\"\"CommonJS\"\"}\""` in the package.json doesn't work, although it does in similar contexts.
