### ISSUE TITLE
Remove access modifiers for interface members in c-sharp

### ISSUE THREAD

**Issue by kurmeroli** [dotansimha/graphql-code-generator#5770]
**Describe the bug**
According to Programming Guide of Microsoft. The access modifiers of interface members need to be removed.

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation

I have already created a PR.
https://github.com/dotansimha/graphql-code-generator/compare/master...kurmeroli:fix-acces-interfaces

**To Reproduce**

Just generate with a file with the c-sharp plugin with a schema, that contains an interface. The access modifier must not exist.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

The members of an interface in the generated file must not have an acccess modifier (public, private etc.)


**Environment:**

- OS: Mac OSX, Windows 10
- `@graphql-codegen/c-sharp`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by ardatan** [comment]
Available in the latest version!
