### ISSUE TITLE
Preserve order when generating TypeScript definitions

### ISSUE THREAD

**Issue by bitshiftza** [dotansimha/graphql-code-generator#5781]
Currently each time the CLI is executed, the TypeScript definitions come out the same, which is correct, but the order of the definitions is not kept constant.

I'd like to propose some type of ordering which keeps the generated file the same, unless some of the definitions actually changed.

Config used when testing this:
```overwrite: true
schema: "http://localhost:8080/graphql"
documents: "src/**/*.{ts,tsx}"
generates:
  src/gql-types.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
config:
 skipTypename: true
 declarationKind: 'interface'```

**Comment by kaitlynmcgoldrick** [comment]
@bitshiftza I believe I'm also experiencing this issue. Right now my generated types file is in source control so I'm committing those changes every time I make changes. 

Someone had suggested gitignoring the generated types file and then running the `graphql-codegen` command as part of the build command

How are you getting around it right now?

**Comment by ardatan** [comment]
We suggest to have generated files "gitignored". But if you still have a "consistent" output, you can use `prettier` or some other tool that sorts the output after GraphQL Codegen runs by using life cycle hooks;
https://www.graphql-code-generator.com/docs/integrations/prettier

**Comment by ardatan** [comment]
Could you try with the alpha versions here;
https://github.com/dotansimha/graphql-code-generator/pull/5982#issuecomment-838547015

**Comment by dotansimha** [comment]
> Could you try with the alpha versions here;
> 
> https://github.com/dotansimha/graphql-code-generator/pull/5982#issuecomment-838547015

Closing. If someone is still experiencing it, please refer to @ardatan 's reply
