### ISSUE TITLE
Procedural(non-parallel) execution

### ISSUE THREAD

**Issue by jjangga0214** [dotansimha/graphql-code-generator#5802]
**Is your feature request related to a problem? Please describe.**

In some cases, a config file has multiple generations, and each generation might depend on each other. 

Thus I believe guaranteeing the order of execution would be helpful in that case.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ardatan** [comment]
You can do that by using Programmatic API.
https://www.graphql-code-generator.com/docs/getting-started/programmatic-usage

**Comment by dotansimha** [comment]
As @ardatan said, this is the only option. We tried to implement it in some scenarios and it makes codegen core a bit more complicated when these dependencies are introduced. 
You can use codegen Programmatic API to achieve that.
