### ISSUE TITLE
[FeatureRequest] [TypeScript GraphQL-Request] Supply query name to SdkFunctionWrapper

### ISSUE THREAD

**Issue by heyitsaamir** [dotansimha/graphql-code-generator#5807]
Background: Typescript GraphQL-Request has [simple middleware capability](https://www.graphql-code-generator.com/docs/plugins/typescript-graphql-request#simple-request-middleware), which is useful to do interesting things when making a call. One of the things we want to do is add perf metrics to our various queries (similar to the example in the docs actually). However, we can't _really_ do that because we don't get the name of the query in the wrapper, which doesn't really help figure out where bottlenecks etc are.

Request: Update the simple wrapper to also supply the name of the query as a parameter to `SdkFunctionWrapper`. This will allow for more helpful logging / more customizable middlewares.

**Comment by ardatan** [comment]
Would you create a draft PR then we can help you?

**Comment by ardatan** [comment]
Available in @graphql-codegen/typescript-graphql-request@3.2.0 !
