### ISSUE TITLE
[c-sharp-operations] losing double-precision due to wrong value type

### ISSUE THREAD

**Issue by 124C41p** [dotansimha/graphql-code-generator#5815]
The GraphQL value type "Float" refers to a double-precision floating-point value. It is translated by the plugin c-sharp-operations to the C#-type "float", which has only single precision (the correct analog would be "double"). Because of that translation error, the generated C#-Code ignores half of the precision of requested floating-point data.

I strongly suspect this bug can be easily corrected by replacing "float" with "double" in [scalars.ts, line 6](https://github.com/dotansimha/graphql-code-generator/blob/6734c58055d283f051bf32f115f2308000e56431/packages/plugins/c-sharp/common/scalars.ts).

**Comment by ardatan** [comment]
Would you create a PR for the fix?

**Comment by dotansimha** [comment]
Fixed in:
```
@graphql-codegen/c-sharp@2.0.2
@graphql-codegen/c-sharp-operations@1.19.2

```
