### ISSUE TITLE
typescript template with support for module

### ISSUE THREAD

**Issue by OneCyrus** [dotansimha/graphql-code-generator#582]
typescript in babel 7 doesn't support namespaces. there were already discussions in the following issues:

https://github.com/dotansimha/graphql-code-generator/issues/428
https://github.com/dotansimha/graphql-code-generator/issues/285

though there is a potential fix with the noNamespace arg. this is imho just a workaround and we should have a proper solution. namespaces are a construct of the past and the ecosystem should move on to modules. there should be a "useModules" option which would add "export declare module" instead of "export namespace". i guess this should be a pretty straight forward change in https://github.com/dotansimha/graphql-code-generator/blob/master/packages/templates/typescript/src/documents.handlebars

are you accepting a PR which adds this?

**Comment by ardatan** [comment]
I don't think `noNamespaces` option is just a workaround, it is an option how types, models and other stuff are generated. And, I also think having multiple modules inside one typescript file is not a good practice. 
You can see more about it in this documentation;
https://www.typescriptlang.org/docs/handbook/modules.html
The actual problem belongs to Babel's TypeScript plugin, because namespaces are part of TypeScript, and Babel's TS plugin should support it.

**Comment by OneCyrus** [comment]
i don't think typescript or babel is moving in this direction. here's a comment from a typescript core maintainer:

> Namespaces imply one of two things:
>
> - Global code structuring (as they'll merge across files)
> - Extra layers of nesting within a module
>
> Neither case seems to be ideal, nor does it feel like the direction the JavaScript community is taking. But more than that, there's a technical constraint which is that Babel's single-file-at-a-time model doesn't really support cross-file resolution.

https://github.com/babel/babel/issues/8244#issuecomment-408187141

multiple module declarations in one file is how a lot of the typescript typings work today.

**Comment by ardatan** [comment]
If graphql-code-generator generates only global declarations, you may be right. But, our tool can also generate code for react-apollo and apollo-angular components as well.
@dotansimha @kamilkisiela what do you think?

**Comment by OneCyrus** [comment]
shouldn't that not even more push to modules instead of namespaces? if I understand you right, your main concern is the use of a single file for all generated code? may be the best thing (even today) would be to generate a file per namespace or module?

**Comment by ecwyne** [comment]
Let me start by saying that I *love* `graphql-code-generator`! Seriously awesome!

I am running up against this also now trying to upgrade `create-react-app`/`react-scripts` which as of today supports TS out of the box 🎊. I suspect many more people will start using CRA for their React/TS projects, as such I think this project would benefit from either moving away from namespaces or documenting `noNamespaces` more prominently for CRA users.

Thanks everyone, you're doing an awesome job!

**Comment by dotansimha** [comment]
Thanks @ecwyne ! 
We documented the usage with RCA/babel-typescript here: https://graphql-code-generator.com/docs/integrations/create-react-app
