### ISSUE TITLE
graphql-modules preset uses non-existent resolver from main generated file

### ISSUE THREAD

**Issue by jjangga0214** [dotansimha/graphql-code-generator#5822]
**Describe the bug**
 

![Screenshot from 2021-04-10 23-23-23](https://user-images.githubusercontent.com/28584151/114273328-91dc5b00-9a54-11eb-8a76-5e75e2146c29.png)

`jsonb`, `timestamptz` and `uuid` are all scalars, whose resolver does not exist.
But graphql-modules preset tries to refer resolvers.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->


<!-- 
**Expected behavior**
-->
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: Ubuntu 20.04.
- "@graphql-codegen/cli": "^1.21.3"
- "@graphql-codegen/graphql-modules-preset": "^1.2.4"
- "@graphql-codegen/typescript": "^1.21.1"
- "@graphql-codegen/typescript-resolvers": "^1.19.0"
- NodeJS: v14.16.0

<!-- 
**Additional context**
-->
<!-- Add any other context about the problem here. -->

**Comment by dotansimha** [comment]
I think this was already fixed. Can you please try `1.2.7` of the preset and let me know if it still persists?
