### ISSUE TITLE
typescript-urql: `documentMode: documentNodeImportFragment` incorrectly references gql from graphql-tag

### ISSUE THREAD

**Issue by wereHamster** [dotansimha/graphql-code-generator#5828]
**Describe the bug**

When I set `documentMode: documentNodeImportFragment`, gql is still being used / referenced within the generated document, but the gql import is not inserted, leading to compiler errors. `documentMode: documentNode` works as expected (ie. gql is not being used nor imported).

**To Reproduce**

https://codesandbox.io/s/blissful-sunset-5u9oz

**Comment by dotansimha** [comment]
It's `documentNodeImportFragments` (with `s`) :)
