### ISSUE TITLE
Better support for GraphQL directives

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#583]
Continue the discussion from here:  https://github.com/dotansimha/graphql-code-generator/pull/561 

The idea is to have better support for directives such as `@skip`, `@include`, and other custom directives that become common such as `@client`.

**Comment by JuHwon** [comment]
i am also having an issue because i am using AWS AppSync, i got a directive `@aws_subscribe` in my schema. the cli returns: `error: Directive aws_subscribe: Couldn't find type aws_subscribe in any of the schemas.`

a nice way to handle custom/popular directives would be awesome.

**Comment by JuHwon** [comment]
@douglasward I created my custom project configuration with my own templates.
This worked out super well, and I am super happy since the flexibility I have now is enormous.
You can easily extend your schema with the custom project configuration.


The following code is my `schema.js` in my project config folder.
```javascript
const fs = require('fs')
const path = require('path')
const makeExecutableSchema = require('graphql-tools').makeExecutableSchema

function loadGraphQL(file) {
  const filePath = path.join(__dirname, file)
  return fs.readFileSync(filePath, 'utf8')
}

const schema = loadGraphQL('../../schema.graphql')
const awsEnhancements = loadGraphQL('./aws-enhancements.graphql')

exports.schema = makeExecutableSchema({
  typeDefs: [awsEnhancements, schema],
})

```

**Comment by douglasward** [comment]
@JuHwon great, that sounds like just what i need, thanks.

Is `aws-enhancements.graphql` the file where you extend the schema to allow directives? If so, do you have one for the `@connection` directive, or could you point me in the right direction as to how I could extend the schema to support that directive?

**Comment by dotansimha** [comment]
You can now specify client-schema easily, and add custom schema pieces for each output. (since 0.14)

**Comment by dotansimha** [comment]
Update on this issue. Since changes in 0.14, we no longer validate your GraphQL directives during the documents validation. So you no longer need to provide the clientSchema file with the directives declaration.

**Comment by dotansimha** [comment]
@mikebm can you please share your `codegen.yml` file?

**Comment by mikebm** [comment]
> @mikebm can you please share your `codegen.yml` file?

```
overwrite: true
schema:
    schema.graphql:
        loader: /full_path_to_loader/loader.js
generates:
    ./src/server/graphql/__generated__/schema-types.d.ts:
        plugins:
            - typescript-common
            - typescript-server
```

Another bug with this format is the loader does not work with relative paths. I must give it a full path to the loader.

**Comment by dotansimha** [comment]
@mikebm it looks like your custom schema loader has an issue, because it thrown an error while building the schema. The ` Unknown directive "internal".` error comes directly from `graphql`. 
Can you please try the latest version of the codegen and see if it still happens? 
Also, does it happen with the default loader?

**Comment by mikebm** [comment]
> @mikebm it looks like your custom schema loader has an issue, because it thrown an error while building the schema. The ` Unknown directive "internal".` error comes directly from `graphql`.
> Can you please try the latest version of the codegen and see if it still happens?
> Also, does it happen with the default loader?

Sorry it took so long to respond. Yes, this is still an issue.
codegen.yml:
```
schema:
  schema.graphql:
    loader: ./src/loader.js
```
./src is in the same folder as codegen.yml.

Changing the path from ./src to the full path works.
ex: /users/myuser/repo/src/loader.js

**Comment by dotansimha** [comment]
@mikebm I created an issue for it: https://github.com/dotansimha/graphql-code-generator/issues/1571
And fixed it in: https://github.com/dotansimha/graphql-code-generator/commit/f349d8669346b899eb5b894d4be5436621dc63fa

**Comment by Flos** [comment]
My solution right now is to remove the "@aws*" directives with the cli using "sed". 

```
cat schema.graphql | sed -e 's/@aws.*{/{/' | sed -e 's/@aws.*//' > src/codegen/schema.graphql
```

I placed that command in the API update script and I don't have to worry about unknown directives  anymore.
