### ISSUE TITLE
Subscription is not generic

### ISSUE THREAD

**Issue by timvandesteeg** [dotansimha/graphql-code-generator#584]
Older typescript versions can't handle a subscription with generics. Angular 6 does not seem to be compatible with typescript > 3.0 just yet (coming with Angular 7). Is it possible to add a flag to generate a Subscription without generics for older typescript versions?

**Comment by ardatan** [comment]
Could you explain your issue with reproduction steps and errors you get?

**Comment by dotansimha** [comment]
@timvandesteeg please try the solution @kamilkisiela suggested. 
If that's still relevant, please re-open and issue.

**Comment by timvandesteeg** [comment]
@kamilkisiela that did solve the problem :) thanks a billion

**Comment by kamilkisiela** [comment]
@timvandesteeg super nice!
