### ISSUE TITLE
Error "Cannot find name 'User'" in typescript-resolvers output

### ISSUE THREAD

**Issue by dariusj18** [dotansimha/graphql-code-generator#5841]
**Describe the bug**
I am just getting used to typescript/graphql etc, so my terminology might not be so good, however I get an error with the resulting type definitions when using the typescript-resolvers plugin with the `typesPrefix` set and `enumPrefix` set to false.  My guess is I misunderstood the intent of the `enumPrefix` option, or there is a bug.

**To Reproduce**

https://codesandbox.io/s/beautiful-smoke-1c1x2?file=/types.ts

**Expected behavior**
The resolver would use the type name with the prefix.

**Environment:**

- OS: Windows
- `@graphql-codegen/...`: 
  @graphql-codegen/typescript
  @graphql-codegen/typescript-operations
  @graphql-codegen/typescript-resolvers
- NodeJS: 14.16.0

**Comment by dariusj18** [comment]
As you can see in the resulting types, the following block

```
export type IResolversTypes = ResolversObject<{
  Query: ResolverTypeWrapper<{}>;
  Int: ResolverTypeWrapper<Scalars["Int"]>;
  User: ResolverTypeWrapper<User>;
  String: ResolverTypeWrapper<Scalars["String"]>;
  Boolean: ResolverTypeWrapper<Scalars["Boolean"]>;
}>;

/** Mapping between all available schema types and the resolvers parents */
export type IResolversParentTypes = ResolversObject<{
  Query: {};
  Int: Scalars["Int"];
  User: User;
  String: Scalars["String"];
  Boolean: Scalars["Boolean"];
}>;
```

I would assume the `User` type should be `IUser`

**Comment by obedm503** [comment]
Having the same issue. A workaround until this is fixed is to manually define it in your `mappers`
```yml
generates:
  path/to/generated/types.ts:
    config:
      mappers:
        User: IUser
```

**Comment by eddeee888** [comment]
This looks fixed in the later versions. Please open another issue if it's still a problem.
[Example sandbox](https://codesandbox.io/p/sandbox/clever-germain-5diu8s?file=%2Ftypes.ts%3A125%2C15&selection=%5B%7B%22endColumn%22%3A36%2C%22endLineNumber%22%3A116%2C%22startColumn%22%3A36%2C%22startLineNumber%22%3A116%7D%5D) with the correct generated type.
