### ISSUE TITLE
Generate code inside node_modules

### ISSUE THREAD

**Issue by liadmat** [dotansimha/graphql-code-generator#5867]
In order to generate types, `graphql-code-generator` needs to "pollute" the codebase with the generated artifacts, as opposed to a more self-contained approach.

Personally, I really like how Prisma does it, where artifacts are generated inside of node_modules (node_modules/.prisma/client).

How do you feel about adding this as an option?

**Comment by ardatan** [comment]
You can point any path under node_modules/. Why would we need an extra option for this?

**Comment by ardatan** [comment]
Closing this issue due to the lack of response. Feel free to create a new one if you're still having issues to generate code inside node_modules.
