### ISSUE TITLE
[FeatureRequest] [typescript-graphql-request] Add ability to modify request headers from middleware

### ISSUE THREAD

**Issue by lyubo** [dotansimha/graphql-code-generator#5883]
Problem: When making calls to back-end, dynamically calculated per-request authentication header is needed. While such header can be added by calling graphqlRequestClient.setHeader() method within middleware implementation, this can lead to side effects as changes are effective on all subsequent calls.

Request: Add argument to action callback in SdkFunctionWrapper to pass request-scoped headers.

**Comment by mariusmarais** [comment]
FYI, I'm currently using this wrapper around the generated SDK to set up-to-date authentication headers per request:

```ts
export interface Options<SDK> {
  url: string;
  headerProvider(): Record<string, string> | Promise<Record<string, string>>;
  sdk(client: GraphQLClient, wrapper: SdkFunctionWrapper): SDK;
}

export function createSdkClient<SDK>({ url, headerProvider, sdk }: Options<SDK>) {
  const client = new GraphQLClient(url);

  return sdk(client, async action => {
    const headers = await headerProvider();
    client.setHeaders(headers);

    return action();
  });
}

// Later...
const client = createSdkClient({
      url,
      headerProvider: () => ({
        // Authorization: 'Bearer TOKEN_HERE'
      }),
      sdk: getSdk
    });
```

That way you get a function that is evaluated for every request. By wrapping the graphql-request client entirely, you don't have the risk of the headers being used elsewhere and the `.setHeaders` call clear the existing headers AFAICT from the graphql-request source.  You could pass more of the client constructor options through as well.

**Comment by ardatan** [comment]
Available in @graphql-codegen/typescript-graphql-request@3.2.0 !
