### ISSUE TITLE
Can not push my branch for a new pull request (as contributor)

### ISSUE THREAD

**Issue by karkael64** [dotansimha/graphql-code-generator#5954]
**Describe the bug**
Hey there, I can not push my custom branch on this repo, it throws a 403 forbidden.

```plain
$> git push origin HEAD
Username for 'https://github.com': karkael64
Password for 'https://karkael64@github.com': 
remote: Permission to dotansimha/graphql-code-generator.git denied to karkael64.
fatal: unable to access 'https://github.com/dotansimha/graphql-code-generator.git/': The requested URL returned error: 403
```

**To Reproduce**

1. Log in as a new github.com user
2. Clone repo, create a branch and a commit
3. Try to push them with the new account

Thanks!

**Comment by ardatan** [comment]
@karkael64 You should fork the repo first under your name. Then push your branch into yours.

**Comment by karkael64** [comment]
For those are not familiar like me:

When you push in your fork, Github selects the original repository for merging the PR, [as mentioned here](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo).

@ardatan Thanks for the reply!
