### ISSUE TITLE
New feature: TypeScript Svelte Apollo

### ISSUE THREAD

**Issue by karkael64** [dotansimha/graphql-code-generator#5957]
There is currently no support for Svelte, I propose a plugin to create a Svelte context to handle the ApolloClient that supports TypeScript. There is nothing complicated at this point, with only two possible parameters:

- `loadGetClientFrom` takes `getClient` from the file pointed to for use with the ApolloClient
- `exportOnlyFunctions` remove exports for graphql documents, data types, input & output formats ; the generated file exports `getClient`, `setClient`, query, mutation & subscription functions.

I propose a PR in 3 commits: 
1. Adding the plugin
2. Add the plugin to the global configuration
3. Add the plugin in the website

Edit: just pushed a complement for documentations. Hope you enjoy it !

**Comment by ticruz38** [comment]
> The [ticruz38 plugin](https://github.com/ticruz38/graphql-codegen-svelte-apollo) doesn't meet Svelte's needs and his code is terrible, neither are the forks. They are all starting to get old, but the Svelte community is excited to use TypeScript and GraphQL more. All that's left is to convince you!

The plugin is dead simple, it basically wraps the query with the types needed. Apollo's watchqueries and Svelte then play together like a charm. 
Have you tried it? What would you have done differently?

**Comment by ticruz38** [comment]
By reading the pull request, everything is pretty much the same, except you're not using watchQueries (they work really well with svelte reactivity).
You are using svelte context to bring the Apollo client, I'm not sure if this is really needed, you will run into problems when using this plugin with sapper/svelte-kit with SSR activated. It's also why you need svelte as a dependency to your plugin.

**Comment by Urigo** [comment]
@karkael64 closing for now as we haven't heard back from you after @ticruz38 recent comment.
If this still doesn't solve your problem please feel free to comment here and reopen the issue and PR.

Also, regarding that, I wonder what Svelte developers think about the new `near-operation-file-preset` introduced in [Codegen V2](https://twitter.com/UriGoldshtein/status/1423268278697398274?s=20)?
Would be great to hear your feedback about that.

Thanks!
