### ISSUE TITLE
GraphQL interface, enum and union types are not parsed from import files

### ISSUE THREAD

**Issue by netpoe** [dotansimha/graphql-code-generator#5972]
**Describe the bug**

I'm trying to migrate `type`s from a `schema.graphql` monolith file to smaller sub-schemas. 

Running `graphql-codegen --watch 'schema.graphql'` throws this error: 

```
 ✖ types.ts
    Failed to load schema from schema.graphql:

        Unknown type: "CommonAccount".
        Error: Unknown type: "CommonAccount".
```

The directory structure is this: 

```
schema.graphql
common.graphql
```

**To Reproduce**

[Codesandbox fork.](https://codesandbox.io/s/admiring-paper-lcx4m?file=/schema.graphql)

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

`schema.graphql`:

```graphql
# import StubbedAccount,UpdateAccountInput from "common.graphql"

type Query {
    user: String
}

type Mutation {
    temporaryUpdateAccount(input: UpdateAccountInput!): StubbedAccount!
}
```

`common.graphql`

```graphql
interface CommonAccount {
  id: String!
}

type IdentityAccount implements CommonAccount {
  id: String!
}

type StubbedAccount {
  id: String!
  identityAccount: IdentityAccount
}

input UpdateAccountInput {
  firstName: String
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

**Expected behavior**

I expect the `schema.graphql` import the types from `common.graphql` without problems, since the syntax is correct, and it works when `interface CommonAccount` is written directly in `schema.graphql`. 

**Environment:**

See [codesandbox](https://codesandbox.io/s/admiring-paper-lcx4m?file=/codegen.yml:0-136), it happens there as well.

**Additional context**

Happens the same with `enum` and `union`.

`package.json`: 

```
"@graphql-codegen/cli": "^1.21.3",
    "@graphql-codegen/introspection": "^1.18.1",
    "@graphql-codegen/typescript": "^1.22.0",
    "@graphql-codegen/typescript-operations": "^1.17.15",
    "@graphql-codegen/typescript-resolvers": "^1.19.0",
    "@graphql-codegen/typescript-urql": "^2.0.5",
```

**Comment by Urigo** [comment]
Hi @netpoe and thank you for the report!

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems already got into `stage 1` thanks to your reproduction! Thank you for that!

Now in order to advance to `stage 2` we'll need a failing test, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).
The question is if this is an issue on codegen or on graphql-tools https://github.com/ardatan/graphql-tools/tree/master/packages/import?
Maybe if you can create a failing test there we could know where the issue originates.

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by netpoe** [comment]
Hi @Urigo 

I was able to keep up with my work. It turns out it was a very simple solution: 

I needed to add the new sub-schema files to the `codegen.yml` file: 

```
schema: [src/api/schema/*.graphql]
```

And that was it. The parser picked the new types, including `interface`, `enum` and `union`

**Comment by Urigo** [comment]
That's awesome, thanks @netpoe for the update!
Do you think there is something we could add to the docs to make it easier for others who would follow your path or having it here in the issue is enough?

**Comment by netpoe** [comment]
> That's awesome, thanks @netpoe for the update!
> Do you think there is something we could add to the docs to make it easier for others who would follow your path or having it here in the issue is enough?

I think I was mislead because the `graphql-codegen` command parsed the `# import` statements fine, but threw errors upon and `interface`, `enum` and `union` from these same `# import` files.
