### ISSUE TITLE
urql-introspection plugin query does not match the urql devtools query causing error

### ISSUE THREAD

**Issue by disbelief** [dotansimha/graphql-code-generator#5981]
**Describe the bug**
The introspection query that the `urql-introspection` plugin uses to generate the schema does not match the one that urql's `devtoolsExchange` uses. Specifically, it is missing `__typename` in several places.

This would be fine, however when urql's `cacheExchange` ([@urql/exchange-graphcache](https://github.com/FormidableLabs/urql/tree/main/exchanges/graphcache)) uses this generated schema, an uncaught error occurs when the `devtoolsExchange` ([@urql/devtools](https://github.com/FormidableLabs/urql-devtools)) attempts to request its own introspection query.

The problem is that the `devtoolsExchange`'s query includes some fields that aren't known to `cacheExchange` due to the differences in the introspection query.

**To Reproduce**

1. use `graphql-codegen` with the `urql-inspection` plugin to generate a schema
2. import the schema into urql `cacheExchange`
3. add the devtoolsExchange in urql client
4. load the app in a browser
5. Result: app will load, then once the urql devtools requests its own introspection query, `cacheExchange` will throw an error when checking the response.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

_Is quite large and not the issue here._

2. My GraphQL operations:

```graphql
########################################
# graphql-codegen introspection query:
########################################
query IntrospectionQuery {
  __schema {
    queryType {
      name
    }
    mutationType {
      name
    }
    subscriptionType {
      name
    }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type {
    ...TypeRef
  }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}

########################################
# urql-devtools introspection query:
########################################
query IntrospectionQuery {
  __schema {
    queryType {
      name
      __typename
    }
    mutationType {
      name
      __typename
    }
    subscriptionType {
      name
      __typename
    }
    types {
      ...FullType
      __typename
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
      __typename
    }
    type {
      ...TypeRef
      __typename
    }
    isDeprecated
    deprecationReason
    __typename
  }
  inputFields {
    ...InputValue
    __typename
  }
  interfaces {
    ...TypeRef
    __typename
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
    __typename
  }
  possibleTypes {
    ...TypeRef
    __typename
  }
}

fragment InputValue on __InputValue {
  name
  description
  type {
    ...TypeRef
    __typename
  }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                __typename
              }
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
```

Here is the diff between the two queries:
```diff
5d4
<       __typename
9d7
<       __typename
13d10
<       __typename
17d13
<       __typename
25d20
<         __typename
27d21
<       __typename
29d22
<     __typename
42d34
<       __typename
46d37
<       __typename
50d40
<     __typename
54d43
<     __typename
58d46
<     __typename
65d52
<     __typename
69d55
<     __typename
78d63
<     __typename
107d91
<                 __typename
109d92
<               __typename
111d93
<             __typename
113d94
<           __typename
115d95
<         __typename
117d96
<       __typename
119d97
<     __typename
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:4000/graphql'
generates:
  src/graphql/schema.ts:
    plugins:
      - 'urql-introspection'
    config:
      useTypeImports: true
      includeEnums: true
      includeInputs: true
      includeDirectives: true
      includeScalars: true
```

**Expected behavior**

Ideally the two schemas should match or at least not conflict so much that it causes page-breaking errors.

One possibility could be adding an `includeTypenames: boolean` option to the `urql-introspection` plugin to adjust the query.

**Environment:**

- OS: macOS 11.3
- `@graphql-codegen/cli`: 1.21.4
- `@graphql-codegen/urql-introspection`: 1.2.0
- NodeJS: v14.16.0

**Additional context**
Apologies but I don't see how I could put this into a codesandbox in any meaningful way. For reference here is how the client is instantiated in my application:

```typescript
import { createClient, dedupExchange, fetchExchange } from 'urql';
import { cacheExchange } from '@urql/exchange-graphcache';
import { devtoolsExchange } from '@urql/devtools';
import schema from '@src/graphql/schema';

const client = createClient({
  url: 'http://localhost:4000/graphql',
  requestPolicy: 'cache-first',
  exchanges: [
    devtoolsExchange,
    dedupExchange,
    cacheExchange({ schema }),
    fetchExchange,
  ],
});
```

The specific error is the following:
```
Unhandled Rejection (Graphcache Error): Invalid Object type: The type `__Schema` is not an object in the defined schema, but the GraphQL document is traversing it.
(Caused At: "IntrospectionQuery" query)
https://bit.ly/2XbVrpR#3
```

This error originates here: https://github.com/FormidableLabs/urql/blob/4c1a9d9bd3df55207aeff1ffc3e2b3262f27cbc9/exchanges/graphcache/src/ast/schemaPredicates.ts#L70

Removing the `devtoolsExchange` from the client removes the error, but at the expense of having no devtools 😢

**Comment by kitten** [comment]
> The problem is that the devtoolsExchange's query includes some fields that aren't known to cacheExchange due to the differences in the introspection query.

That's unfortunately not the issue here, so let's not skip to assumptions 😅 The difference in queries is irrelevant because the `__typename` field annotations will _always_ be added by any `cacheExchange` for caching purposes, but introspection queries are cacheable and the warnings/errors that'd usually trigger ignore built-in types.

> Ideally the two schemas should match or at least not conflict so much that it causes page-breaking errors.

To quickly clarify this, there isn't a conflict; the "schema" that Graphcache ultimately uses isn't served and only used internally. `@urql/introspection` is actually even performing a minification on this schema for internal use and that's why it will never be equal to the queried introspection result, regardless of the selection sets.

However, if you've traced this error to `getField` then there's something more odd going on, so I'll need the full stack trace to fully get an idea here of where this is triggering. I think I have an idea of what's going on, so if the stack contains `isFieldAvailableOnType` then we may have to add another exception, but let's confirm this first :v:

**Comment by disbelief** [comment]
Of course, happy to provide a stack trace. Apologies, timezone differences delayed my reply, though it sounds like you've already solved the issue (many thanks for that).

Here is a screenshot of the source-mapped stacktrace for the record, since copy-paste from the browser wouldn't preserve the formatting.

<img width="827" alt="Screen Shot 2021-05-12 at 10 17 48" src="https://user-images.githubusercontent.com/295574/117950714-ace50800-b33d-11eb-9c6c-5969783be1b0.png">

If the cause of the problem was a difference between the result of devtools' query and what graphecache expects, then I'm not sure how my initial report made an incorrect assumption. Perhaps my terminology is simply lacking. At any rate I was simply trying to provide as much information as I had gleaned from debugging myself.

**Comment by disbelief** [comment]
I can confirm that upgrading to `@urql/exchange-graphcache@4.1.1` has resolved the issue for my installation. Will leave the ticket open in case you have a specific policy around confirming/labelling/closing issues.

**Comment by kitten** [comment]
@disbelief Awesome! No worriers though, I merely mean that more details around errors without speculation often helps us to resolve an issue quicker 🙌 Then again, since we have time to address these issues during normal work hours we often are able to fix them on the same day either way
