### ISSUE TITLE
Documentation is full of dead links

### ISSUE THREAD

**Issue by rex-remind101** [dotansimha/graphql-code-generator#5997]
Documentation is full of dead links like https://the-guild.dev/blog/better-type-safety-for-resolvers-with-graphql-codegen

**To Reproduce**
go to https://www.graphql-code-generator.com/
click "about us"
see a dead page

**Comment by Urigo** [comment]
@rex-remind101 thanks for reporting.

It works for me.. could you maybe send a video/GIF of what you are doing?

**Comment by chenrui333** [comment]
The links are also working for me.

including this one.
> To Reproduce
> go to https://www.graphql-code-generator.com/
> click "about us"
> see a dead page

**Comment by Urigo** [comment]
ok I'll leave it open a bit longer to see if someone else can reproduce it

**Comment by rex-remind101** [comment]
```
Unable to connect

Firefox can’t establish a connection to the server at the-guild.dev.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```

Same thing in Safari. I'm not currently behind a VPN. My connection is from the west cost of the united states.

**Comment by Urigo** [comment]
Super weird..... cc @dotansimha thoughts?

**Comment by dotansimha** [comment]
We had some issues with certificates during May. I think we are all good. Feel free to ping me if something is down again :)
