### ISSUE TITLE
`urql-typescript` Vue composition function support

### ISSUE THREAD

**Issue by hognevevle** [dotansimha/graphql-code-generator#6029]
**Is your feature request related to a problem? Please describe.**
This is supported for vue-apollo, but not for urql. 

**Describe the solution you'd like**
Similar to `withHooks`, but for `@urql/vue`. Tried changing `urqlImportFrom`, but the generated functions aren't compatible in all cases (e.g. subscriptions).

**Comment by bartenra** [comment]
Since the APIs are so similar, would it make more sense to adapt the existing plugin to also support Vue?

@hognevevle Which incompatibilities have you found? Haven't had to do subscriptions with urql yet (only queries and mutations).

**Comment by hognevevle** [comment]
@bartenra Below is an example of the generated functions for subscriptions, which aren't valid for vue.

![image](https://user-images.githubusercontent.com/2721188/120340370-42990500-c2f6-11eb-9094-da2809a9c47f.png)

**Comment by dotansimha** [comment]
Available now (https://github.com/dotansimha/graphql-code-generator/pull/6033)  as `@graphql-codegen/typescript-vue-urql@1.0.0` 🎉

**Comment by viztor** [comment]
> Available now (#6033) as `@graphql-codegen/typescript-vue-urql@1.0.0` 🎉

it seems the generated vue urql doesn't allow reactive variables

**Comment by dotansimha** [comment]
> > Available now (#6033) as `@graphql-codegen/typescript-vue-urql@1.0.0` 🎉
> 
> it seems the generated vue urql doesn't allow reactive variables

If you think this is a missing feature or a bug, can you please create a reproduction and open an new issue? Thanks!
