### ISSUE TITLE
Support future-proof enums as enums

### ISSUE THREAD

**Issue by ertrzyiks** [dotansimha/graphql-code-generator#6061]
**Is your feature request related to a problem? Please describe.**

I want to ensure that all places in the code depending on the enum values from the schema handle possible future extensions.
If a new value is added to enumeration, the code should be forced to handle in a respectful way.

I find the `futureProofEnums` very helpful in this regard
https://github.com/dotansimha/graphql-code-generator/pull/3721

However it works with `enumsAsTypes: true` only and that strips us from benefits of having TS enums:
 - we can iterate over all possible values
 - we can validate input coming from user space (URL param, localstorage etc)
 
I agree with @c0m1t that extending the enum would not be ideal. 

If it's already possible and I just couldn't find it, let's mention the solution in the docs for `futureProofEnums`

**Describe the solution you'd like**

The enum is generated as it is now, but the operation types use `Enum | '%future added value'`

```ts
enum Color {
  RED = 'RED',
  BLUE = 'BLUE'
}

....


type MutationVariables = Types.Exact<{
  color: Types.Color  | '%future added value'
}>
```

**Describe alternatives you've considered**
Use enums as types but generate additional type as an enum

```
type Color = 'RED' | 'BLUE' | '%future added value'

enum ColorActualEnum {
  RED = 'RED',
  BLUE = 'BLUE'
}
```

**Comment by dotansimha** [comment]
Thank you for creating this @ertrzyiks ! Feel free to create a PR if you wish ;)

**Comment by ertrzyiks** [comment]
Hey @dotansimha I'm definitely up for submitting a PR, just wanted to get some feedback what approach has higher chances to get merged to the generator. Do you have any preference?

**Comment by dotansimha** [comment]
I think at the level of the usage might solve that in an elegant way, so `Enum | 'future value'` might do the trick here (in `typescript` plugin I guess).
