### ISSUE TITLE
Inconsistency between MongoDB and other TypeScript templates

### ISSUE THREAD

**Issue by ardatan** [dotansimha/graphql-code-generator#608]
Some features of other TypeScript templates are missing in MongoDB template.

**Comment by kamilkisiela** [comment]
<img width="867" alt="zrzut ekranu 2018-10-2 o 16 18 02" src="https://user-images.githubusercontent.com/8167190/46354423-dc4c1800-c65e-11e8-9f5d-ff09fe245aee.png">

Having `T | null` instead of optional fields causes an issue when interface A doesn't fit interface B because of the missing fields.

**Comment by dotansimha** [comment]
Fixed in 0.14.2 🎉
