### ISSUE TITLE
Live example on the website is broken

### ISSUE THREAD

**Issue by ThomWright** [dotansimha/graphql-code-generator#6080]
**Describe the bug**
The live generator on the website is broken.

Every key press de-focusses the input.

**To Reproduce**

1. Go to the website: https://www.graphql-code-generator.com/

2. Try to change one of the files

**Expected behavior**

I can do more than one key stroke without re-focussing the input.

**Environment:**

- OS: Ubuntu
- Browser: Chrome/Firefox

**Additional context**

N/A

**Comment by ardatan** [comment]
Fixed :) 
https://www.graphql-code-generator.com/
