### ISSUE TITLE
Would a RTK-Query plugin be welcome?

### ISSUE THREAD

**Issue by phryneas** [dotansimha/graphql-code-generator#6085]
Hi there,
I'm a maintainer of Redux Toolkit. 

Over the past half year, we've been working on a "server-side API cache" implementation called "RTK Query" that we are integrating into our package. 

Right now we've [just released](https://github.com/reduxjs/redux-toolkit/releases/tag/v1.6.0) (you can find our [documentation over here](https://redux-toolkit.js.org/rtk-query/overview)) after many alphas, betas and release candidates.

The api itself has been tested over the past half year, is already being used in production by a few teams and has been acknowledged by other package authors (for example, we are already on [React Query's "comparison page"](https://react-query.tanstack.com/comparison) .

We already have [code generation for OpenAPI specifications](https://github.com/rtk-incubator/rtk-query-codegen) and I've set off to also create a plugin for `graphql-codegen`. Honestly, implementing this has been a breeze and it's [pretty much finished by now](https://github.com/phryneas/graphql-code-generator/pull/1).

Would you be interested in getting that into the `graphql-codegen` repo? We could also publish it on our own, but honestly, I'm pretty impressed with the documentation, integration with the demo page and everything, so I'd love to see it in here "officially" :)

**Comment by dotansimha** [comment]
Hi @phryneas !
Thank you for creating this issue. We are always welcome any kind of open-source contributions. RTK is definitely something that we can support, and we would love to see a PR for creating a plugin for it. 
I assume you can use `react-query` plugin as reference since it might be similar in terms of wrapping GraphQL operations. Feel free to reach out in case of questions!

**Comment by phryneas** [comment]
@dotansimha it's already almost done, I'll just need to go through it again and adjust the version number to the release. I'll probably open a PR in the next hour or so :)

**Comment by dotansimha** [comment]
`@graphql-codegen/typescript-rtk-query@1.0.0` is now available. Thanks @phryneas !
