### ISSUE TITLE
[typescript] Allow customization of types string processor ( compound words )

### ISSUE THREAD

**Issue by ardatan** [dotansimha/graphql-code-generator#609]
We may have an option in `generatorConfig` for different methods to handle compound words;
`PascalCase`, `snake_case`, `camelCase` or even `kebab-case`.

**Comment by dotansimha** [comment]
The idea comes from this issue: https://github.com/dotansimha/graphql-code-generator/issues/605

**Comment by dotansimha** [comment]
Available since 0.14. You can now specify `namingConvention` in config, and point to a module and a function (for example, `change-case#lowerCase`)
