### ISSUE TITLE
Generation fails due to incorrect assumption of the apollo @connection directive argument type

### ISSUE THREAD

**Issue by tidychips** [dotansimha/graphql-code-generator#6112]
**Describe the bug**
When using the [apollo `@connection` directive](https://www.apollographql.com/docs/react/caching/advanced-topics/#the-connection-directive), generation assumes incorrect types for the directive arguments if the field with the directives has arguments with the same name but different types.  This causes it to fail with an error like the one below for valid queries.

```
 AggregateError:
        GraphQLDocumentError: Expected value of type "[Filter!]", found "things".
            at document.graphql:3:22
        at new AggregateError (/sandbox/node_modules/@ardatan/aggregate-error/index.cjs.js:141:24)
        at Object.checkValidationErrors (/sandbox/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/utils/index.cjs.js:517:15)
        at Object.codegen (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:102:15)
        at async process (/sandbox/node_modules/@graphql-codegen/cli/bin.js:940:56)
        at async Promise.all (index 0)
        at async /sandbox/node_modules/@graphql-codegen/cli/bin.js:947:37
        at async Task.task (/sandbox/node_modules/@graphql-codegen/cli/bin.js:725:17)
```

This issue is likely not limited to just the `@connection` directive, but I have not tested with others.

**To Reproduce**

https://codesandbox.io/s/frosty-morning-lbhe9

The code sandbox demonstrates an example where the field with the `@connection` directive has a `filter` argument that's a different type than the directive `filter` argument.  The same issue also happens if the `filter` argument in the schema is renamed to `key`, since the directive also takes a `key` argument of a different type.

1. My GraphQL schema:

```graphql
type Query {
    things(filter: [Filter!], limit: Int, offset: Int, search: String): Thing!
}

type Thing {
    id: String!
    name: String!
    field1: String
    field2: Int
}

input Filter {
    fieldId: String!
    isNull: Boolean!
}
```

2. My GraphQL operations:

```graphql
query example($limit: Int, $offset: Int, $search: String) {
  things(limit: $limit, offset: $offset, search: $search)
    @connection(key: "things", filter: ["search"]) {
    id
    name
    field1
    field2
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
```

**Expected behavior**
Don't assume the type of the field argument is the same as the type of the directive argument

**Environment:**

- OS: OSX 10.15.7
- "@graphql-codegen/add": "2.0.2"
- "@graphql-codegen/cli": "1.20.1"
- "@graphql-codegen/typescript": "1.21.0",
- "@graphql-codegen/typescript-operations": "1.17.14",
- NodeJS: v14.16.1

**Comment by dotansimha** [comment]
This issue happens because Apollo uses psuedo-directives on top of queries - these are being removed before the operation is being executed. So they don't really effect GraphQL execution, and they are specific to the way that Apollo-Client behaves. 
This is also something that isn't part of the GraphQL spec, so Codegen doesn't support it out-of-the-box.

If you wish to use that directive and pass codegen validation, you need to have this directive defined in your schema: 

```
directive @connection(key: String, filter: [String]) on FIELD
```

You can define it in your real schema, or inline it specifically for codegen:

```yaml
schema:
  - "directive @connection(key: String, filter: [String]) on FIELD"
  - ./my-schema.graphql
```
