### ISSUE TITLE
Allow an option to provide the parser to use for reading source files

### ISSUE THREAD

**Issue by danielo515** [dotansimha/graphql-code-generator#6121]
**Is your feature request related to a problem? Please describe.**

GraphQL generator is not capable of parsing javascript files with type annotations if they do not have the proper `//@flow` annotation.
While having type annotations on a JS file that doesn't have the `//@flow` annotation at the top is not strictly correct, it is not a problem for the flow parser to process them. 
What GraphQL generator is doing right now is inferring that the file is a regular javascript file: 

> `js` extension and no `@flow` annotation? must be a javascript file, let's use regular babel parser for it

And that makes it fail.

**Describe the solution you'd like**

Ideally you should be able to tell GraphQL generator which parser to use if you need to. This will allow me to check the files of our entire codebase, and not just a subset of them. 

I know the flow parser is able to parse js files with types fine even if they don't have the flow annotation, or even if they have the `@noflow` annotation.

**Describe alternatives you've considered**
Right now I have to move all the Graphql queries to separate files and add the anotation there. This is not ideal. 

**Additional context**

Our codebase has many files with flow annotations that doesn't have the proper flow header. Partly because people forgot to add it but still use types. Now, there are too many files with wrong types to fix them all.

**Comment by dotansimha** [comment]
You can use custom schema loader: https://www.graphql-code-generator.com/docs/getting-started/schema-field#custom-schema-loader and custom operations loader: https://www.graphql-code-generator.com/docs/getting-started/documents-field#custom-document-loader , and this way you can implement any parsing / loading logic.

**Comment by danielo515** [comment]
That flexibility is nice.
But what I'm proposing is a much more user friendly solution, which is just define it as a property.
Is there any reason you are not open to this?

**Comment by dotansimha** [comment]
> That flexibility is nice.
> But what I'm proposing is a much more user friendly solution, which is just define it as a property.
> Is there any reason you are not open to this?

I think it might be an overkill for codegen to deal with parsing files. We prefer to keep it simple, and if someone needs to customize it - it's completely flexible.

**Comment by danielo515** [comment]
> > That flexibility is nice.
> > But what I'm proposing is a much more user friendly solution, which is just define it as a property.
> > Is there any reason you are not open to this?
> 
> I think it might be an overkill for codegen to deal with parsing files. We prefer to keep it simple, and if someone needs to customize it - it's completely flexible.

If you don't want to add the feature I'm completely fine with it. But to keep it clear, all that I'm proposing is to pass the property to the underling parsing library (which I suppose is jscodeshift, or something similar). Unless I'm misunderstanding some internal detail of codegen it should not add any logic to it.

Regards
