### ISSUE TITLE
Website broken on Firefox

### ISSUE THREAD

**Issue by selrond** [dotansimha/graphql-code-generator#6189]
working on Mac chrome & safari

https://user-images.githubusercontent.com/6603389/123415381-7691de00-d5b5-11eb-9d5b-19a63cfc1323.mp4

**Comment by dotansimha** [comment]
Thanks! @entbit any idea why it happens?

**Comment by entbit** [comment]
@dotansimha will investigate it later today.

**Comment by danbruegge** [comment]
![image](https://user-images.githubusercontent.com/1296438/123851614-b17c7480-d91b-11eb-8e7b-84af350b45a8.png)
Looks like this is the reason. :shrug: I have this too on Linux with Firefox 89.0.2 and Firefox Developer Edition 90.0b12.

**Comment by entbit** [comment]
@danbruegge It happens due to the backdrop filter indeed. There's a fix coming pretty soon. For now, you can disable `layout.css.backdrop-filter.enabled` from about:config on your Firefox browser.

**Comment by danbruegge** [comment]
I thought that. I have it enabled because i'm working on a project where it is needed. :)

Looking forward for the fix. ;)

**Comment by dotansimha** [comment]
Fixed :) Thanks, @danbruegge @entbit !
