### ISSUE TITLE
Website: Config selection dropdown values are invisible in dark mode

### ISSUE THREAD

**Issue by theajr** [dotansimha/graphql-code-generator#6205]
**Describe the bug**

In dark mode of the [website](https://www.graphql-code-generator.com/) - Configuration selection dropdown options are almost invisible. 

**To Reproduce**
- Navigate to https://www.graphql-code-generator.com
- Select night mode
- Click on the dropdown to see the options

**Expected behavior**
- Dropdown values should be visible in dark mode as well.

**Environment:**
- Production

![issue](https://user-images.githubusercontent.com/11477078/123774457-0c49a800-d8eb-11eb-81b9-0c2339568fd1.png)

**Comment by theajr** [comment]
![issue](https://user-images.githubusercontent.com/11477078/123774341-f1773380-d8ea-11eb-948f-5c24387ffa78.png)

**Comment by dotansimha** [comment]
@entbit ^

**Comment by saihaj** [comment]
@B2o5T fixed most of these
