### ISSUE TITLE
CLI Package - Update chokidar dependency

### ISSUE THREAD

**Issue by callumfrance** [dotansimha/graphql-code-generator#6208]
**Describe the bug**
chokidar depends on the `glob-parent` package which had a security threat.
chokidar > 3.5.2 has the version of glob-parent without the security risk.
The CLI package's `package.json` will need to be updated accordingly.
https://github.com/advisories/GHSA-ww39-953v-wcq6

**To Reproduce**

Not applicable - this is just a dependency change

`graphql-code-generator/packages/graphql-codegen-cli/package.json`:
```
-    "chokidar": "^3.5.1",
+    "chokidar": "^3.5.2",
```

**Comment by dotansimha** [comment]
Thanks, @callumfrance ! Please note that we use a range, so the eventual version depends on your project. 

To make sure it's not causing issues for others, I bumped the range to enforce latest, available in `@graphql-codegen/cli@1.21.6`.
