### ISSUE TITLE
When validating queries against schema, print the file name with error.

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#621]
**Is your feature request related to a problem? Please describe.**
When I change my schema I get a lot of validation errors which is very good. This helps me refactor the schema! However having 100 errors withouts specification in which files is frustrating.

**Describe the solution you'd like**
In addition to the validation error, also print the file name in which the error occured.

**Describe alternatives you've considered**
Manually checking every field in every query in every file to see if they have caused one of the errors.

**Comment by jonaskello** [comment]
I guess the change need to happen somewhere around [here](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/loaders/documents/document-loader.ts#L30).

**Comment by jonaskello** [comment]
Also printing the number of errors encountered would be helpful. That way when you have 30+ errors you can see if a change was good and gave less errors :-).

**Comment by dotansimha** [comment]
Fixed in v0.12.4. Thanks @jonaskello !

**Comment by jonaskello** [comment]
Sure I'll give it a go in a separate PR :-).
