### ISSUE TITLE
Suffix not present on hooks anymore

### ISSUE THREAD

**Issue by lucasbordeau** [dotansimha/graphql-code-generator#6212]
**Describe the bug**
Since I upgraded to 2.2.6 and above, the suffix is not added on hooks anymore with plugin `typescript-react-apollo` and option `typesSuffix: MySuffix`.

**To Reproduce**

- Install `typescript-react-apollo@2.2.5`
- Generate hooks with option `typesSuffix: MySuffix`
- Create some custom hooks calling `useFindUserQueryMySuffix()`
- Upgrade to `typescript-react-apollo@2.2.6` or above.
- Make the exact same generation
- The apollo hooks are generated without the `MySuffix` and this breaks all of the generated hooks imports

1. My GraphQL schema:

```graphql
scalar Date

schema {
  query: Query
}

type Query {
  me: User!
  user(id: ID!): User
  allUsers: [User]
  search(term: String!): [SearchResult!]!
  myChats: [Chat!]!
}

enum Role {
  USER,
  ADMIN,
}

interface Node {
  id: ID!
}

union SearchResult = User | Chat | ChatMessage

type User implements Node {
  id: ID!
  username: String!
  email: String!
  role: Role!
}

type Chat implements Node {
  id: ID!
  users: [User!]!
  messages: [ChatMessage!]!
}

type ChatMessage implements Node {
  id: ID!
  content: String!
  time: Date!
  user: User!
}

```

2. My GraphQL operations:

```graphql
query findUser($userId: ID!) {
  user(id: $userId) {
    ...UserFields
  }
}

fragment UserFields on User {
  id
  username
  role
}
```

3. My `codegen.yml` config file:

```yml
generates:
  types-and-hooks.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config: 
      typesSuffix: MySuffix
```

**Expected behavior**
Could we have a way to workaround this new behavior ? There's nothing I can do except renaming all my imports or downgrading to `2.2.5`.

**Environment:**

- OS: `OSX 11.4`
- packages : 
`"@graphql-codegen/cli": "^1.21.6",`
`"@graphql-codegen/introspection": "^1.18.2",`
`"@graphql-codegen/typescript": "^1.22.4",`
`"@graphql-codegen/typescript-operations": "^1.18.3",`
`"@graphql-codegen/typescript-react-apollo": "2.2.6",`
- NodeJS: `v14.17.0`

**Additional context**

**Comment by lucasbordeau** [comment]
Link to the fix where this behavior changed : #6001 #6002

**Comment by ardatan** [comment]
See https://github.com/dotansimha/graphql-code-generator/pull/6213

**Comment by dotansimha** [comment]
Fix available in `@graphql-codegen/typescript-react-apollo@2.3.0`
