### ISSUE TITLE
React Query Plugin: Allow custom Typescript Shape for custom fetcher

### ISSUE THREAD

**Issue by chrisdhanaraj** [dotansimha/graphql-code-generator#6214]
Hey there! I've been doing a swap from Apollo to React-Query, and have been leveraging the various graphql-codegen plugins with both iterations. Something I ran into was that, while React-Query is great, it leverages a Promise structure in how it resolves data, and expects you to *throw* an error if an error appears.

However, in our Graph API's it's (unfortunately) relatively common to get partial data with some errors that we can recover from or ignore, which doesn't really work with simply throwing an Error if the payload comes back with a shape of 

```
{
  data: SOME_DATA
  errors: SOME_ERRORS
}
```

What I _want_ to do, then, is setup my custom fetcher to return true if any data is present, but have the shape look like the above payload, versus _just_ the `SOME_DATA`. If no data appears in the response payload _or_ the response comes back `res.ok = false`, _then_ throw an error.

While I can do this right now with the custom fetcher in terms of functionality, the types break down

**Comment by dotansimha** [comment]
Duplicate: https://github.com/dotansimha/graphql-code-generator/issues/6013
