### ISSUE TITLE
Can we change `selectionSet` of NewStitchingResolver as optional?

### ISSUE THREAD

**Issue by highwide** [dotansimha/graphql-code-generator#6243]
**Is your feature request related to a problem? Please describe.**

I've just tried to use `@graphql-codegen/typescript-resolvers` on my project which uses schema-stitching.
But the types generated don't match my resolver definitions because `selectionSet` is required.

I supposed this code is valid, isn't it? (At least, it's working so far.)

```typescript
MyFoo: {
  foo: {
    resolve(payload, args, context, info) {
      return delegateToSchema({
        schema: mySchema,
        operation: 'query',
        fieldName: 'foo',
        args: {
          fooId: payload.fooId,
        },
        context,
        info,
      })
    },
  },
}
```

However, this doesn't match the type below.
The error message shows "Property 'selectionSet' is missing in type".

https://github.com/dotansimha/graphql-code-generator/blob/9005cc17ecaa520ba57380940640e28b837a1488/packages/plugins/typescript/resolvers/src/index.ts#L54-L57

**Describe the solution you'd like**

I supposed `selectionSet` can be changed as optional.

If this solution is ok, I'm happy to create a PR like below;

* Modify packages/plugins/typescript/resolvers/src/index.ts 
  * `selectionSet: string;` -> `selectionSet?: string;`
* yarn build
* yarn generate:examples

**Describe alternatives you've considered**

None.

**Additional context**

This is my first time to open an issue in this project, and I've just begun to use `@graphql-codegen/typescript-resolvers`.
So if there's any misunderstanding, I'm so sorry.

At last, thank you for creating a very cool tool such as graphql-code-generator 🙌

**Comment by dotansimha** [comment]
Hi @highwide ,
thank you for reporting this.

@ardatan can you please confirm that we can select an optional `selectionSet` here?

**Comment by ardatan** [comment]
We can have an additional type as part of Resolver signature union that has only resolve field instead of changing the stitching resolver signature.

**Comment by highwide** [comment]
Do you mean it is good to add "another StitchResolver" which doesn't have a field `selectionSet` as a union to here?
https://github.com/dotansimha/graphql-code-generator/blob/9005cc17ecaa520ba57380940640e28b837a1488/packages/plugins/typescript/resolvers/src/index.ts#L58

If so, can I ask why `selectionSet ` of `NewStitchingResolver` shouldn't be optional?
I found that `graphql-tools` provides it as optional.

https://github.com/ardatan/graphql-tools/blob/aa43054d3415cc29c8a610dea6aa04df5f42e5f9/packages/delegate/src/types.ts#L74

**Comment by ardatan** [comment]
> Do you mean it is good to add "another StitchResolver" which doesn't have a field selectionSet as a part of the union here?

https://github.com/dotansimha/graphql-code-generator/blob/master/dev-test/test-schema/resolvers-types.ts#L56
This union decides which one is your resolver signature, right? So if we make `selectionSet` optional, TS will say `resolve` property is an indicator of being a stitching resolver :)

>  I found that graphql-tools provides it as optional.

That's the signature of `delegateToSchema` not resolvers.

**Comment by highwide** [comment]
@ardatan 

>> I found that graphql-tools provides it as optional.
> That's the signature of delegateToSchema not resolvers.

It was my mistake! Thank you.

> This union decides which one is your resolver signature, right? So if we make selectionSet optional, TS will say resolve property is an indicator of being a stitching resolver :)

Thank you for pointing it out!
So I created a PR by adding another StitchResolver to `StitchingResolver`. https://github.com/dotansimha/graphql-code-generator/pull/6281
I hope I understood exactly what you said... 🙏 
If not, please tell me how to fix, or please close it. Thanks.

**Comment by dotansimha** [comment]
Available in `@graphql-codegen/typescript-resolvers@1.20.0`
