### ISSUE TITLE
Npm audit failing

### ISSUE THREAD

**Issue by marcusmathioudakismoo** [dotansimha/graphql-code-generator#6274]
**Describe the bug**
running npm audit on a project with graphql-codegen/cli installed raises multiple Moderate instances of the `Regular Expression Denial of Service` vulnerability in the `ws` dependency (https://npmjs.com/advisories/1748 ). This has been patched in latest version of `ws`.

**To Reproduce**
in a local npm project, run:
- `npm install @graphql-codegen/cli --save-dev`
- `npm audit`

**Comment by dotansimha** [comment]
Hi @marcusmathioudakismoo ! Thank you for reporting this issue.

I recently saw this interesting article, and I recommend it to everyone who uses/depends on `npm audit`: https://overreacted.io/npm-audit-broken-by-design/ 

Regarding this issue: `ws` is not a direct dependency of `@graphql-codegen/cli` and it comes from a nested dependency. This time it's something we are able to fix and workaround, but note that in many cases that's not the case. 

The issue with `@graphql-tools/url-loader` was addressed and discussed in: https://github.com/ardatan/graphql-tools/issues/3022 , you can force a version of this package to `7.0.0-alpha-bbb5746f.0` in the meantime, until it will be released and updated, and then we'll do it here as well.

**Comment by mtlewis** [comment]
Looks like graphql-tools has been updated, so it should now be possible to upgrade the the dependencies on graphql-tools packages in this project and avoid the vulnerable version of `ws`.
