### ISSUE TITLE
TypeScript faker plugin

### ISSUE THREAD

**Issue by marocchino** [dotansimha/graphql-code-generator#6306]
Hi 👋, Thank you for merge last PR. 
 
I need auto generated mock object without launch extra server.

for example:

schema
```graphql
type User {
  id: ID!
  "@faker name.findName"
  name: String!
  "@faker internet.email"
  email: String!
  age: Int
}
```

query
```graphql
query User($id: ID!) {
   user(id: $id) {
      name
      email
      age
   }
}
```

will generate
```ts
import { UserQuery } from './generated-type';
import faker from 'faker';

export function userQueryMock(): UserQuery {
  return {
    user: {
      name: faker.name.findName(),
      email: faker.internet.email(),
      age: faker.datatype.number()
    }
  }
}
```

There will be a lot of customization for this plugin, but for now I want to start with a simple initial implementation.

**Comment by dotansimha** [comment]
Codegen doesn't deal with custom directives, mainly because it endless... 
Also, moving to Discussions :)
