### ISSUE TITLE
Expose stricter TypedTypePolicies without apollo's native TypePolicies

### ISSUE THREAD

**Issue by MargaretKrutikova** [dotansimha/graphql-code-generator#6318]
**Is your feature request related to a problem? Please describe.**
Currently `TypedTypePolicies` is exposed as a union of typed policies from schema and apollo's native untyped `TypePolicies`:
```typescript
export type TypedTypePolicies = TypePolicies & {
   UserType?: Omit<TypePolicy, "fields" | "keyFields"> & {
       keyFields?: false | UserTypeKeySpecifier | (() => undefined | UserTypeKeySpecifier),
       fields?: UserTypeFieldPolicy,
    }
}
```
Here `UserType` is our own type, while `TypePolicies` is defined like this:
```typescript
export declare type TypePolicies = {
    [__typename: string]: TypePolicy;
};
```
This makes it prone to error if I were to change the existing type policies or if I were to add a field that doesn't exist, e.g.
```typescript
const policies: TypedTypePolicies = {
    UserType: {...},
    UserType2: {....},
    SomethingElse: {....}
}
```
No typescript error is generated here since `TypedTypePolicies` allows any string key.

**Describe the solution you'd like**
I would like `TypedTypePolicies` to be stricter than that and disallow any fields that don't exist in the schema.
It would help to have to separate types exported from the generated code, e.g.

```typescript
export type StrictTypedTypePolicies = {
   UserType?: Omit<TypePolicy, "fields" | "keyFields"> & {
       keyFields?: false | UserTypeKeySpecifier | (() => undefined | UserTypeKeySpecifier),
       fields?: UserTypeFieldPolicy,
    };
};

export TypedTypePolicies = StrictTypedTypePolicies & TypePolicies;
``` 

This would be backwards compatible and wouldn't require adding any options and would allow to choose a stricter type.

**Describe alternatives you've considered**

**Additional context**

Thanks! 😄

**Comment by duncanbeevers** [comment]
I wanted this feature for work, and followed @MargaretKrutikova ' suggestion. It's a simple change, but could probably do with a bit of documentation.

I tested this out in my work codebase and it was :+1:

The feature seems worthwhile, and its cheap to expose a new export. Happy to run with this if its deemed useful.
