### ISSUE TITLE
typescript-compatibility plugin is incompatible with `operationResultSuffix` config of main typescript plugin

### ISSUE THREAD

**Issue by ericbiewener** [dotansimha/graphql-code-generator#6331]
**Describe the bug**
If you use the config option `operationResultSuffix`, `typescript-compatibility` will still reference types that do _not_ have that provided suffix, thus referencing types that don't exist. For example, if you specify `Result` as the suffix, you'll get types generated like:

```
type GetFooQueryResult = { ... } // from typescript plugin
type GetFooName = GetFooQuery["name"] // from typescript-compatibility
```

**To Reproduce**

1. Specify any suffix for `operationResultSuffix`
2. Include the `typescript-compatibility` plugin

**Expected behavior**
The types generated by `typescript-compatibility` should include the suffix:

```
type GetFooName = GetFooQueryResult["name"]
```

**Environment:**

- OS: Mac 11.4
- `@graphql-codegen/core`: 1.17.0
- `@graphql-codegen/typescript`: 1.23.0
- `@graphql-codegen/typescript-compatibility`: 2.1.5
- NodeJS: 14.16.1

**Additional context**

**Comment by dotansimha** [comment]
Hi @ericbiewener !
`typescript-compatibility` was intended for migration between v0 and v1 of codegen (~3 years ago).
We've just released v2 and this plugin is no longer maintained or actively developed. 
I recommend to migrate to the new versions of codegen.
