### ISSUE TITLE
typescript-compatibility plugin does not correctly generate child types when parent types can be null

### ISSUE THREAD

**Issue by ericbiewener** [dotansimha/graphql-code-generator#6332]
**Describe the bug**
Consider the following example:

```tsx
type GetFooQuery = {
  author: null | {
    name: string
  }
} // from typescript plugin

type GetFooAuthorName = GetFooQuery["author"]["name"] // from typescript-compatibility
```

The type `GetFooAuthorName` has an error. It should be: `NonNullable<GetFooQuery["author"]>["name"]`. [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4hwDED2SCKBXCAnEUC8UA3gLABQUUAhusABZJYBcUAdugDbtQA+RZFFFpQC2EZgGdgWAJYsA5vygBfMkqgB6dVABmWJMKihI4gMYywwKGHbo5ssmSPQ4iFAEEa9LADkREAPoAQpQAJviw8MhomDgA2gBE1HQM8QC6CUKiaRpauvqG4BCm5sAAtCb6YJTA0gBG0uzSoI6FEa5IHsk+fv4wKGEE3kgs3hzslLXsEAA8LlEY2CAJSV5pAHwZftmaUBVYWBAmwBBhAG7Y4tLDQA).

**Expected behavior**
Should create valid types by using `NonNullable`:

```tsx
NonNullable<GetFooQuery["author"]>["name"]
```

**Environment:**

- OS: Mac 11.4
- `@graphql-codegen/core`: 1.17.0
- `@graphql-codegen/typescript`: 1.23.0
- `@graphql-codegen/typescript-compatibility`: 2.1.5
- NodeJS: 14.16.1

**Additional context**

**Comment by dotansimha** [comment]
Hi @ericbiewener !
`typescript-compatibility` was intended for migration between v0 and v1 of codegen (~3 years ago).
We've just released v2 and this plugin is no longer maintained or actively developed. 
I recommend to migrate to the new versions of codegen.
