### ISSUE TITLE
Cannot find module '@graphql-tools/batch-execute'

### ISSUE THREAD

**Issue by alisalim17** [dotansimha/graphql-code-generator#6336]
## I am running this code : `yarn graphql-codegen init`

and get this error ->

Error: Cannot find module @graphql-tools/batch-execute

I'm using yarn workspaces,[my repo](https://github.com/alisalim17/airbnb-clone) 

when i use npm,it's works correctly

- OS: Windows 10 
- `@graphql-codegen/...`:  1.21.7
- NodeJS:  14

**Comment by alisalim17** [comment]
I fixed this problem by installing yarn 2.Before this problem i was using yarn 1

**Comment by alisalim17** [comment]
I think changing yarn 2 is not best solution.

Does anybody know better solution ?

**Comment by dotansimha** [comment]
This might be related to your setup and dependencies. I wasn't able to reproduce this issue in a clean environment...
