### ISSUE TITLE
C# Plugin: `GraphQL` namespace in generated code not used at all

### ISSUE THREAD

**Issue by seclerp** [dotansimha/graphql-code-generator#6340]
**Describe the bug**
`using GraphQL;` declaration is included in generated code, but not used at all. Such behavior creates some problems when using this plugin for projects that have no GraphQL dependency installed at all or when it uses another .NET GraphQL framework (HotChocolate in my case).

**To Reproduce**
Just generate C# code using the data provided below.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
enum ns {
  dummy
}
```

2. My `codegen.yml` config file:

```yml
schema: schema.gql
generates:
  MyTypes.cs:
    plugins:
      - c-sharp
    config:
      namespaceName: MyCompany.MyNamespace
```

**Expected behavior**
Generated C# code will not have unused GraphQL dependency

**Environment:**

- OS: Windows
- `@graphql-codegen/cli`: 1.21.7 
- `@graphql-codegen/c-sharp`: 3.0.2
- NodeJS: 14.16.1

**Comment by dotansimha** [comment]
Available in 

```
@graphql-codegen/c-sharp@4.0.0
@graphql-codegen/c-sharp-operations@2.0.0
````
