### ISSUE TITLE
Feature Request: Make resolvers optional in Typescript template

### ISSUE THREAD

**Issue by standy** [dotansimha/graphql-code-generator#639]
There is should be a way to exclude resolvers from generated types in `graphql-codegen-typescript-template`. 
I have very large graphql schema and some small App. Generated types become over 20k lines, but only few of them is useful. For graphql consumers resolvers are large overhead in generated file (more then 80% for me)

**Comment by kamilkisiela** [comment]
Hi :)

It's already optional, there's a flag that turns that off.

https://github.com/dotansimha/graphql-code-generator/tree/master/packages/templates/typescript#resolvers-or-codegen_resolvers-default-value-true

```bash
CODEGEN_RESOLVERS=false gql-gen ...
```

**Comment by standy** [comment]
Oh, thank you!
