### ISSUE TITLE
Directives changing the type of scalar

### ISSUE THREAD

**Issue by Sytten** [dotansimha/graphql-code-generator#6393]
**Is your feature request related to a problem? Please describe.**

Currently I am using a mix of number ID and string ID for a project.
This is annoying since I can't override the default to be always number so the casting needs to happen inside the resolvers.
What I would like is adding a directive that does the casting for me. But then the typing would be wrong.

**Describe the solution you'd like**
(FYI I will code it once this is discussed by the community)
I think we should add a new setting for the typescript generator to allow directives to change the mapping of the scalar.
So let's take an example:
```graphql
directive @AsNumber on
  | ARGUMENT_DEFINITION
  | INPUT_FIELD_DEFINITION

input MyInput {
  someId: ID! @AsNumber
}

type MyType {
  id: ID!
}

extend type Mutation {
  myMutation(id: ID! @AsNumber, input: MyInput!): MyType
}
```

We could then have a config like:
```yaml
config:
  directives:
    AsNumber: 'number'
```

**Describe alternatives you've considered**
Mapping the ID inside the resolvers. This is really annoying when you have complex nested input objects with arrays.

**Additional context**

**Comment by n1ru4l** [comment]
That sounds like an interesting addition! Although, I think the config option name should be more clear!

I recently started working on something similar for using a custom resolver function type based on the directive applied on the field: https://github.com/dotansimha/graphql-code-generator/pull/6330

**Comment by Sytten** [comment]
@n1ru4l I build a first draft of it. It works great from the small testing I have done, I would appreciate your input on it 🙏

**Comment by dotansimha** [comment]
Implemented in https://github.com/dotansimha/graphql-code-generator/pull/6609
