### ISSUE TITLE
add InlineFragment to selection collection criteria

### ISSUE THREAD

**Issue by strass** [dotansimha/graphql-code-generator#6409]
I'm getting an `Invalid state` error from mergeSelectionSets after upgrading to 2.0. I'm one of the users who had a complex fragment use case that prompted the addition of the `inlineFragmentTypes` option in typescript-operations.

I think the logic for adding a selection to the newSelections array needs to be expanded to include more kinds than `FragmentSpread`. I was able to repair the error by adding a check for `InlineFragment` (see linked PR)

Hoping you can accept this without a MWE

**Comment by chrbala** [comment]
I also have this issue and had to use 1.x to make the codegen work.

**Comment by strass** [comment]
Thank you! Worked as expected with this change :)
