### ISSUE TITLE
typescript-react-query: `exposeFetcher` fetcher missing dataSource argument

### ISSUE THREAD

**Issue by dan-lee** [dotansimha/graphql-code-generator#6414]
**Describe the bug**
Generating types with `@graphql-codegen/typescript-react-query` and `exposeFetcher: true` exposes the fetcher but with missing `dataSource` argument (unlike the `useXXX` equivalent)

![image](https://user-images.githubusercontent.com/571589/128164041-2b35aba1-3020-478c-8020-3f2434f95f13.png)

**To Reproduce**

Set `exposeFetcher: true` for `@graphql-codegen/typescript-react-query`

Check CodeSandbox: https://codesandbox.io/s/busy-dhawan-y03d0?file=/types.ts

**Expected behavior**

It should be possible to pass in `dataSource`

**Environment:**

    "@graphql-codegen/cli": "2.0.1",
    "@graphql-codegen/typescript": "2.0.0",
    "@graphql-codegen/typescript-operations": "2.0.1",
    "@graphql-codegen/typescript-react-query": "2.0.0",

**Comment by paolotiu** [comment]
Hey, @dan-lee! I missed this while creating the `exposeFetcher` feature. It  _should_ be a quick fix 😄
