### ISSUE TITLE
v2.0 breaks node 12

### ISSUE THREAD

**Issue by valtism** [dotansimha/graphql-code-generator#6423]
Node 12 `yarn` cannot install v2 of this library because of a dependency on `@graphql-tools/url-loader@7.0.3` which uses `extract-files@11.0.0`. 

My Netlify build using v12.16.3 broke with the message: `extract-files@11.0.0: The engine "node" is incompatible with this module. Expected version "^12.20 || >= 14.13". Got "12.16.3"`

**Comment by ardatan** [comment]
You can add `--ignore-engines` flag near `yarn install` to make it pass for now.

**Comment by LinusU** [comment]
@valtism the problem isn't Node.js 12, it's that you are using a too old a version of Node.js 12.

You are on 12.16.3, but the package requires 12.20.0 or later. Just upgrade your Node.js version and you should be good to go.
