### ISSUE TITLE
Non documented breaking change between typescript-operation 1.18.4 and 2.0.1 ? 

### ISSUE THREAD

**Issue by htulipe** [dotansimha/graphql-code-generator#6428]
**Describe the bug**
My TS compilation failed after upgrading this package. I'm transforming query operations that use fragments on GraphQL interfaces. The trick is that I don't define a fragment for each possible type. It's easier to show than to explain, see below section

**To Reproduce**

https://codesandbox.io/s/crazy-chatterjee-gwewo?file=/types.ts

1. My GraphQL schema:

```graphql
interface Ref {
  ref: ID!
}

type Foo implements Ref {
  ref: ID!
  foo: String
}

type Bar implements Ref {
  ref: ID!
  bar: String
  lol:String
}


type Query {
  entityByRef(type: String!, ref: ID!): Ref
}
```

2. My GraphQL operations:

```graphql
query getFoo($ref:ID!) {
    entityByRef(type:"Foo", ref:$ref) {
        ... on Foo {
            foo
        }
        # Not defining fragment for Bar because I know it can't be anything but a Foo
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      preResolveTypes: true
      skipTypename: true
      
```

**Expected behavior**

Note the generated type GetFooQuery:

```typescript
export type GetFooQuery = { entityByRef?: Maybe<{ foo?: Maybe<string> } | {}> };
```

In previous version it was:

```typescript
export type GetFooQuery = { entityByRef?: Maybe<{ foo?: Maybe<string> }> };
```

There was no `| {}` which I guess represents the other possible types of Ref interface. Though the former output makes more sense, I'd like to known if there's a way to go back to the latter output.

**Environment:**

- OS: MAcOS
- "@graphql-codegen/add": "^3.0.0",
- "@graphql-codegen/cli": "^2.0.1",
- "@graphql-codegen/fragment-matcher": "^3.0.0",
- "@graphql-codegen/typescript": "^2.0.0",
- "@graphql-codegen/typescript-operations": "^2.0.1",
- "@graphql-codegen/typescript-react-apollo": "^3.0.0",
- NodeJS: v14.15.1

**Additional context**
I was updating from:

```
"@graphql-codegen/add": "^2.0.2",
"@graphql-codegen/cli": "^1.21.7",
"@graphql-codegen/fragment-matcher": "^2.0.1",
"@graphql-codegen/typescript": "^1.23.0",
"@graphql-codegen/typescript-operations": "^1.18.4",
"@graphql-codegen/typescript-react-apollo": "^2.3.1",
```

Thanks

**Comment by n1ru4l** [comment]
The previous typing was actually incorrect. The new one is more accurate. Not sure why we should provide a option to use the wrong types. Could you explain that further?

**Comment by htulipe** [comment]
I know the new way is the correct way but it happens to give me more work to do: now I need to make sure that the object I get from my query is actually a Foo by wrapping my code with some type guard such as: `if('foo' in entity) { ... }`.

Anyhow I'll close the issue since there's nothing to do.

Thanks

**Comment by htulipe** [comment]
If anyone found this issue, here is how i removed it:

```typescript
// is T an object and has no key, then remove it from NoEmpty, else use T
type NoEmpty<T> = T extends {} ? (keyof T extends never ? never : T) : T;

const foo = data.entityByRef as NoEmpty<typeof data.entityByRef>;
```
