### ISSUE TITLE
Can't set `fetchPolicy` using `defaultBaseOptions` config variable of `typescript-react-apollo`

### ISSUE THREAD

**Issue by flpvsk** [dotansimha/graphql-code-generator#6451]
**Describe the bug**
 

Can't set `fetchPolicy` using `defaultBaseOptions` config variable of `typescript-react-apollo`.

The `defaultOptions` variable that is added by `typescript-react-apollo` plugin does not have a type signature. Because of that the string value e.g. `"no-cache"` is not recognized by typescript as a member or a `FetchPolicy` (or any other) union.

**To Reproduce**

* Go to sandbox https://codesandbox.io/s/hungry-chatterjee-wztu3
* Run `yarn test` in the terminal

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      defaultBaseOptions:
        fetchPolicy: 'no-cache'
```

**Expected behavior**

I'm able to set default `fetchPolicy`.

**Environment:**


*    "@apollo/client": "3.4.5",
*   "@graphql-codegen/add": "2.0.2",
*   "@graphql-codegen/cli": "1.20.1",
*   "@graphql-codegen/typescript": "1.21.0",
*   "@graphql-codegen/typescript-operations": "1.17.14",
*   "@graphql-codegen/typescript-react-apollo": "3.0.0",
*   "graphql": "15.5.0",
*   "typescript": "4.3.5"
*   NodeJS: 10

**Comment by flpvsk** [comment]
For context, setting default `fetchPolicy` using `defaultOptions` parameter of `ApolloClient` constructor doesn't work either:

https://github.com/apollographql/apollo-client/issues/2555

But for the issue above at least there is a workaround: https://github.com/apollographql/apollo-client/issues/2555#issuecomment-449871538

**Comment by henrikhaugboelle** [comment]
I've encountered this issue too. Turns out it's because of TS rightfully not accepting a `string` input for `FetchPolicy`. It can be fixed by postfixing the `const defaultOptions = {...}` line in the generated file with `as const`. This will allow TS to infer that the contents of the `defaultOptions` will never change and it will therefore accept the value as valid input for `FetchPolicy` as long as it is indeed a valid value for the type.

```typescript
// before – not working
const defaultOptions =  {"fetchPolicy":"network-only"}

// after – working
const defaultOptions =  {"fetchPolicy":"network-only"} as const
```

**Comment by flpvsk** [comment]
There are ways to fix the issue by changing the generated file, including the one you've pointed out. The problem is there is no way to make it "stick". You'd have to manually edit the file every time there is a change to the graphql types, so it breaks the automatic code generation.

**Comment by dotansimha** [comment]
Fixed in https://github.com/dotansimha/graphql-code-generator/commit/c9386e87ad2f32b55e564bcfd4b7ee951c4b4054 

Waiting for a release.

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Ftypescript-react-apollo%403.2.4
