### ISSUE TITLE
Support TypeScript 4.3 noImplicitOverride in typescript-apollo-angular

### ISSUE THREAD

**Issue by toverux** [dotansimha/graphql-code-generator#6465]
Typescript 4.3 [introduced a new `override` keyword and the `noImplicitOverride` rule](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag).

It would be nice to support this keyword with a new option, as the typescript-apollo-angular plugin generates subclasses of Apollo's `Mutation` classes and overrides `Mutation.document`, for example:

```ts
export class AuthResetPasswordUserUpdatePasswordGQL extends Apollo.Mutation<AuthResetPasswordUserUpdatePasswordMutation, AuthResetPasswordUserUpdatePasswordMutationVariables> {
  document = AuthResetPasswordUserUpdatePasswordDocument;
  // ...
}
```

As I use `noImplicitOverride` in my project, unfortunately the generated code breaks the compilation with this kind of errors:

```
Error: apps/client/client.gen.graphql.ts:771:5 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Mutation<AuthLoginLoginWithPasswordMutation, Exact<{ email: string; password: string; }>>'.

771     document = AuthLoginLoginWithPasswordDocument;
        ~~~~~~~~
```

Correct code output with this rule would be:

```ts
export class AuthResetPasswordUserUpdatePasswordGQL extends Apollo.Mutation<AuthResetPasswordUserUpdatePasswordMutation, AuthResetPasswordUserUpdatePasswordMutationVariables> {
  override document = AuthResetPasswordUserUpdatePasswordDocument;
  // ...
}
```

**Comment by ardatan** [comment]
This would be breaking change if we make it by default. It would be better to have it with a configuration flag. We'd love to accept PRs for this change.

**Comment by ToonvanStrijp** [comment]
@ardatan what should the flag be? Just for enabling the implicitOverride? (Don’t know if the current implementation takes the tsconfig into account?) because if we parse the tsconfig and check this we don’t need to enable it by a flag.

**Comment by MaaxGr** [comment]
To clarify for every typescript beginner as i am: The error can be suppressed by specifying a compilerOption in tsconfig.json:
```
"noImplicitOverride": false
```

**Comment by robbecoessens** [comment]
This is the same as #7038 and if you want to add override before document you should add `addExplicitOverride: true` in your config

**Comment by toverux** [comment]
Well since it's been solved I'm closing my issue!
