### ISSUE TITLE
hooks hide logs of their tasks

### ISSUE THREAD

**Issue by jantimon** [dotansimha/graphql-code-generator#6488]
Hooks are really powerful - unfortunately right now all logs are hidden:

https://github.com/dotansimha/graphql-code-generator/blob/71b9a8925d9df494adf8496d16f660308499461a/packages/graphql-codegen-cli/src/hooks.ts#L47-L84

Would it be possible to log them to console? For example in VERBOSE mode?
Without those logs its really hard to find out if those hooks are setup correctly.

**Comment by charlypoly** [comment]
@jantimon, hooks scripts logs are now forwarded to console when codegen is run with `DEBUG=1`, from `@graphql-codegen/cli@2.10.0` 📦
