### ISSUE TITLE
graphql-codegen depends on vulnerable versions of node-fetch

### ISSUE THREAD

**Issue by HT-Moh** [dotansimha/graphql-code-generator#6510]
Hi
using nextjs last version, codegen , prisma. everything is working but we I run `npm audit fix` I got the following error, which bugging me. :-) 

node-fetch  <=2.6.0 || 3.0.0-beta.1 - 3.0.0-beta.8
Denial of Service - https://npmjs.com/advisories/1556
No fix available
node_modules/graphql-codegen/node_modules/node-fetch
  graphql-codegen  *
  Depends on vulnerable versions of node-fetch
  node_modules/graphql-codegen

**Comment by ardatan** [comment]
We don't have a package called `graphql-codegen` on npm. Maybe it is an old version you are using.
Also please see this about  npm audit stuff
https://overreacted.io/npm-audit-broken-by-design/
