### ISSUE TITLE
[TypeScript] NumericEnums config always produces UPPER_CASE enum values

### ISSUE THREAD

**Issue by jisensee** [dotansimha/graphql-code-generator#6532]
**Describe the bug**
Using numericEnums always leads to enum values in upper case instead of the default pascal case. Even setting the naming convention manually does not appear do do anything.

**To Reproduce**
https://codesandbox.io/s/elastic-lederberg-sd10o?file=/types.ts
enum Test should have the value 'TestValue' instead of TEST_VALUE

**Comment by dotansimha** [comment]
Hi @jisensee ! Thank you for reporting this.
I fixed it in: https://github.com/dotansimha/graphql-code-generator/pull/6623, can you please try the alpha version from that PR? (`2.2.1-alpha-d9d206160.0`)

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Ftypescript%402.2.1
