### ISSUE TITLE
Support for interfaces

### ISSUE THREAD

**Issue by tomasreimers** [dotansimha/graphql-code-generator#6539]
**Describe the bug**

Hi, apologies if this is a simple question. I am trying to resolve this issue on Github's API's generated TypeScript definitions: https://github.com/octokit/graphql-schema/issues/526

When a field returns an interface, the generated types only have it as returning that exact interface interface (as opposed to a union of all types which might implement that interface). 

**To Reproduce**

https://codesandbox.io/s/xenodochial-monad-hotoe?file=/types.ts

1. My GraphQL schema:

```graphql
interface Actor {
  """
  The username of the actor.
  """
  login: String!
}

type AutoSquashEnabledEvent {
  """
  Identifies the actor who performed the event.
  """
  actor: Actor
}

type User implements Actor {
  id: String!
}
```

2. My GraphQL operations:

```graphql
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
```

**Expected behavior**

Currently this generates code to the effect of: 

```
export type AutoSquashEnabledEvent = {
  __typename?: 'AutoSquashEnabledEvent';
  /** Identifies the actor who performed the event. */
  actor?: Maybe<Actor>;
};
```

I would expect actor to be able to be fulfilled by any class which implements the interface; for example: 

```
export type AutoSquashEnabledEvent = {
  __typename?: 'AutoSquashEnabledEvent';
  /** Identifies the actor who performed the event. */
  actor?: Maybe<Actor | User>;
};
```

Because I can query for fields on user using something like: 

```
{
  actor {
    ... on User {
      id
    }
  }
}
```

**Environment:**

- OS: Mac OSX
- `@graphql-codegen/cli`: 
- NodeJS: 14.0.0

**Comment by n1ru4l** [comment]
Could you send a PR with a failing test for this?

**Comment by tomasreimers** [comment]
@n1ru4l absolutely! Can oyu point to me to a similar test?

**Comment by ardatan** [comment]
Maybe `useImplementingTypes: true` works for you?
https://www.graphql-code-generator.com/docs/plugins/typescript

**Comment by zhouzi** [comment]
> Maybe `useImplementingTypes: true` works for you? https://www.graphql-code-generator.com/docs/plugins/typescript

I faced the same issue and I confirm that `useImplementingTypes` does the job (related https://github.com/octokit/graphql-schema/issues/526#issuecomment-1132011231).

**Comment by tomasreimers** [comment]
Ah, that seems to solve it!
