### ISSUE TITLE
Cannot load module with namingConvention

### ISSUE THREAD

**Issue by leahciMic** [dotansimha/graphql-code-generator#6553]
**Describe the bug**

resolveExternalModuleAndFn broken since ESM update: https://github.com/dotansimha/graphql-code-generator/pull/6102

`const cwdRequire = module$1.createRequire(process.cwd());`

Looks like using `createRequire` with a path to a folder and not a file/url does not work. It assumes the last part of the path is a filename and strips it. Using `process.cwd() + '/'` will fix it.

**To Reproduce**

https://codesandbox.io/s/empty-rain-hzgdf?file=/package.json

**Expected behavior**

Codegen completes successfully.

**Environment:**

- OS: Linux 5.11.0-27-generic 29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Package versions in codesdanbox.

**Additional context**

Could be fixed by replacing:

`const cwdRequire = module$1.createRequire(process.cwd());`

with:

`const cwdRequire = module$1.createRequire(process.cwd() + '/');`

**Comment by n1ru4l** [comment]
This has been released
