### ISSUE TITLE
Multiple hooks on the same component - Cannot redeclare block-scoped variable 

### ISSUE THREAD

**Issue by HT-Moh** [dotansimha/graphql-code-generator#6587]
I am using three generated hooks on the same component, and I am getting the error 'Cannot redeclare block-scoped variable 'loading'.ts(2451)`  (highlighted on red). when I change the name from `loading` to `Nloading` I get of course `Property 'Nloading' does not exist on type 'MutationResult<InsertBlogTagMutation>'.ts(2339)` 

![image](https://user-images.githubusercontent.com/34759569/131309553-2eb64cf5-3292-4e58-9504-d4f9d870f1e4.png)

how to ignore this error for the three lines only

**Comment by arnabkd** [comment]
You can simply do:
```
const [insertBlogTag, { loading: insertBlogTagLoading }] = useInsertBlogTagMutation()
const [deleteBlogTag, { loading: deleteBlogTagLoading }] = useDeleteBlogTagMutation()

```

Then you'll have two booleans that indicate loading status for the two mutations :)

**Comment by HT-Moh** [comment]
Thanks, I feel stupid :-)
