### ISSUE TITLE
Package has been ignored because it contains invalid configuration.

### ISSUE THREAD

**Issue by canpoyrazoglu** [dotansimha/graphql-code-generator#6599]
After updating to latest versions I've been getting the following warning on app startup:

```
warn Package @graphql-codegen/cli has been ignored because it contains invalid configuration. Reason: Cannot find module '/path/to/my/app/node_modules/@graphql-codegen/cli/package.json.js'
warn Package @graphql-codegen/fragment-matcher has been ignored because it contains invalid configuration. Reason: Cannot find module '/path/to/my/app/node_modules/@graphql-codegen/fragment-matcher/package.json.js'
warn Package @graphql-codegen/introspection has been ignored because it contains invalid configuration. Reason: Cannot find module '/path/to/my/app/node_modules/@graphql-codegen/introspection/package.json.js'
warn Package @graphql-codegen/typescript has been ignored because it contains invalid configuration. Reason: Cannot find module '/path/to/my/app/node_modules/@graphql-codegen/typescript/package.json.js'
warn Package @graphql-codegen/typescript-document-nodes has been ignored because it contains invalid configuration. Reason: Cannot find module '/path/to/my/app/node_modules/@graphql-codegen/typescript-document-nodes/package.json.js'
warn Package @graphql-codegen/typescript-graphql-files-modules has been ignored because it contains invalid configuration. Reason: Cannot find module '/path/to/my/app/node_modules/@graphql-codegen/typescript-graphql-files-modules/package.json.js'
warn Package @graphql-codegen/typescript-graphql-request has been ignored because it contains invalid configuration. Reason: Cannot find module '/path/to/my/app/node_modules/@graphql-codegen/typescript-graphql-request/package.json.js'
warn Package @graphql-codegen/typescript-operations has been ignored because it contains invalid configuration. Reason: Cannot find module '/path/to/my/app/node_modules/@graphql-codegen/typescript-operations/package.json.js'
```

I haven't changed anything related to GraphQL Codegen. I'm on TypeScript 4.4.2, and here is the relevant part of my _DEV_ dependencies:

```
"devDependencies": {
	...
    "@graphql-codegen/cli": "2.1.1",
    "@graphql-codegen/fragment-matcher": "3.1.0",
    "@graphql-codegen/introspection": "2.1.0",
    "@graphql-codegen/typescript": "2.1.2",
    "@graphql-codegen/typescript-document-nodes": "2.1.2",
    "@graphql-codegen/typescript-graphql-files-modules": "2.1.0",
    "@graphql-codegen/typescript-graphql-request": "^4.1.2",
    "@graphql-codegen/typescript-operations": "2.1.2",
	...
  }
```

**To Reproduce**
Have the latest versions of GraphQL codegen for TypeScript in your dev dependencies, run your app, check console.

**Expected behavior**
The warning shouldn't display. 

**Environment:**

- OS: macOS 11.3.1
- `@graphql-codegen/...`:  See above
- NodeJS: 14.17.2

**Additional context**
This wasn't the case before updating to latest versions. Note that this is a minor annoyance, not a breaking bug or anything. Everything still _work as expected_ otherwise.

**Comment by PabloSzx** [comment]
@canpoyrazoglu Could create a reproduction repository please?  with any schema it should work, for example: https://api.spacex.land/graphql/

**Comment by juanlatorre** [comment]
@canpoyrazoglu are you by any chance using react-native ?

**Comment by ThomasGoatITMedia** [comment]
I have te exact same problem, and yes I'm using react-native.

**Comment by canpoyrazoglu** [comment]
@juanlatorre Yes I am using React Native.

**Comment by ThomasGoatITMedia** [comment]
It is referring to `package.json.js`, note the appending `.js`

**Comment by dotansimha** [comment]
I think @PabloSzx did some work on https://github.com/kamilkisiela/bob/pull/30 (the tool we are using to bundle and build codegen) to make sure the artifacts are more robust.

**Comment by blazk0** [comment]
having the same problem

**Comment by Urigo** [comment]
Hi @Mookiies and thank you for the report

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems already got into `stage 1` thanks to your reproduction! Thank you for that!

Now in order to advance to `stage 2` we'll need a failing test, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by sidsarasvati** [comment]
Same issue here with react-native: 0.65.1 
and following graphq-codegen dev packages: 
```
    "@graphql-codegen/cli": "^2.2.0",
    "@graphql-codegen/import-types-preset": "^2.1.4",
    "@graphql-codegen/introspection": "^2.1.0",
    "@graphql-codegen/near-operation-file-preset": "^2.1.4",
    "@graphql-codegen/typed-document-node": "^2.1.4",
    "@graphql-codegen/typescript-apollo-client-helpers": "^2.1.6",
    "@graphql-codegen/typescript-operations": "^2.1.4",
    "@graphql-codegen/typescript-react-apollo": "^3.1.4",
  ```
  
  Adding the info here for now. I will try to create a public repo with repro steps.

**Comment by bryansum** [comment]
@Urigo This issue isn't a library bug per se, just creating a warning as side effect, so not sure the failing test would apply here. 

fwiw I was able to resolve this by adding to each erroring dependencies' `package.json`:
```
diff --git a/node_modules/@graphql-codegen/cli/package.json b/node_modules/@graphql-codegen/cli/package.json
index 837b908..65c7f50 100644
--- a/node_modules/@graphql-codegen/cli/package.json
+++ b/node_modules/@graphql-codegen/cli/package.json
@@ -85,7 +85,8 @@
     "./*": {
       "require": "./*.js",
       "import": "./*.mjs"
-    }
+    },
+    "./package.json": "./package.json"
   },
   "bin": {
     "gql-gen": "bin.js",
```
and then running `npx patch-package --exclude 'nothing' @graphql-codegen/cli` for each package

**Comment by tushar-singhal** [comment]
@bryansum  this worked for me, thanks mate
just wondering what is causing this and what is the proper way to fix it?

**Comment by erheron** [comment]
Any update here? We are experiencing the same problem in our project 👀

**Comment by stelmakhivan** [comment]
@dotansimha, @canpoyrazoglu  I have just tried to install the latest `@graphql-codegen/...` packages, and it seems, that we should close this issue - cause there are not any warnings.
