### ISSUE TITLE
Splitting generated file by queries

### ISSUE THREAD

**Issue by arnabkd** [dotansimha/graphql-code-generator#6610]
**Is your feature request related to a problem? Please describe.**

When starting off with graphql-codegen in a new project, it is quite nice to have everything in one file. However, as the application grows and the number of queries grow with it, having everything in just *one* file is a pain for readability purposes and for the IDE as well.

**Describe the solution you'd like**

I would prefer if there was an option to split files based on graphql queries, along with a global type. This is similar to what apollo codegen did, where for a list of graphql files like so:
- myquery.graphql
- mymutation.graphql

You'd have:
- myquery.ts
- mymutation.ts
- global-types.ts

This scales far better. This can be toggled with say `outputFlat: true` for everything in one file (default, like it is today) or `outputFlat: false` for splitting by query. This is also more logical for me, considering that graphql-codegen provides a specific mutation/query function per graphql file.

See [here](https://github.com/apollographql/apollo-tooling) for a description on how Apollo does it.

**Describe alternatives you've considered**

**Additional context**

I do not know if this has been discussed before, but I could not find any similar requests.

**Comment by ardatan** [comment]
Is that what you want?
https://www.graphql-code-generator.com/docs/presets/near-operation-file

**Comment by arnabkd** [comment]
It's _close_. I would have preferred it if it didn't sit right next to the `.graphql` files, but rather in a `generated` folder along with the rest. Maybe I misunderstood how this works? I couldn't gather all of the generated files in one folder.

**Comment by n1ru4l** [comment]
Closing this as it seems answered.
