### ISSUE TITLE
Bad sublibrary gets seen as "missing codegen plugin"

### ISSUE THREAD

**Issue by krainboltgreene** [dotansimha/graphql-code-generator#6629]
https://github.com/dotansimha/graphql-code-generator/blob/e8bc671a0f4145e9a24436c86ab0d24f94e91725/packages/graphql-codegen-cli/src/plugins.ts#L21-L54

The above code isn't a sufficient try-catch for what I just experienced. In my case, having freshly installed and `init`ed everything I was encountering a message saying libraries that I *did* have installed weren't installed, and I should try the list.

After digging with a debugger into the above lines I found that while `pluginLoader()` did return an error while looking for a plugin, it didn't match the condition `err.code !== 'MODULE_NOT_FOUND'`, which resulted in the above mentioned warning message logic.

However in reality, the error that was occurring was because an underlying library wasn't the right version and had shipped with a bug! I never got to see this message because the catch is too strict.

**Comment by krainboltgreene** [comment]
I know I deleted the template and that's a dick thing to do (I maintain a few large libraries myself), but this situation is so unique I'm willing to come back later with more information. It's just that it's 2am and the barrier to entry should be low for a issue.

**Comment by krainboltgreene** [comment]
I also believe this is why #3275 happens.

**Comment by patrickocoffeyo** [comment]
@krainboltgreene I recently ran into a similar issue using `@graphql/codegen-typescript`. The plugin loader was throwing an error with the code `MODULE_NOT_FOUND`, but when you do a little logging you can see that the real error is `Error: Cannot find module '@babel/runtime/helpers/objectSpread2'`. My temporary solution was to install `@babel/runtime` as a dev dependency, however if I get some time this week I'll put together a PR.

**Comment by krainboltgreene** [comment]
That is the exact thing I'm describing, thanks for bringing receipts!

**Comment by carlosbaraza** [comment]
Sent a PR to add @babel/runtime @patrickocoffeyo  #6716

**Comment by patrickocoffeyo** [comment]
Awesome @carlosbaraza! Thanks for putting that together :raised_hands:
