### ISSUE TITLE
[typescript-react-query] typescript errors in generated file after #6416

### ISSUE THREAD

**Issue by nenadfilipovic** [dotansimha/graphql-code-generator#6633]
**Describe the bug**
 

After https://github.com/dotansimha/graphql-code-generator/pull/6416, generated fetcher is good but it provides optional dataSource param.

If in config you define

```json
"config": {
  "fetcher": "fetch",
  "exposeFetcher": true,
  "exposeQueryKeys": true
 },
```

you get this

```tsx
useGetDeviceFeedQuery.fetcher = (
  dataSource?: { endpoint: string; fetchParams?: RequestInit },
  variables?: Types.GetDeviceFeedQueryVariables,
) =>
  fetcher<Types.GetDeviceFeedQuery, Types.GetDeviceFeedQueryVariables>(
    dataSource.endpoint,
    dataSource.fetchParams || {},
    GetDeviceFeedDocument,
    variables,
  );
```

For this piece of code ts throws `Object is possibly 'undefined'.` for `dataSource.endpoint` and fetchParams. Second problem is that ts is complaining about `A required parameter cannot follow an optional parameter.` and it is caused by dataSource being optional in fetchers that have required variables parameter.

If you do provide endpoint to fetcher config you will get fetcher function that accepts only variables object.

config

```yml
fetcher:
        endpoint: 'http://localhost:3000/graphql'
        fetchParams:
          headers:
            My-Header: SomeValue
```

you get

```ts
useGetOwnDevicesQuery.fetcher = (variables?: Types.GetOwnDevicesQueryVariables) => fetcher<Types.GetOwnDevicesQuery, Types.GetOwnDevicesQueryVariables>(GetOwnDevicesDocument, variables);
```

I think that dataSource should be required param in situations where user have not provided custom endpoint because fetch must get it from somewhere.

Check last line in https://codesandbox.io/s/focused-nash-fcoss?file=/types.ts

**Comment by n1ru4l** [comment]
@nenadfilipovic Can you send a fix for making it non optional?

**Comment by nenadfilipovic** [comment]
Yes, will submit pr soon.
