### ISSUE TITLE
typescript-apollo-angular wrong document value name with near-operation-file preset

### ISSUE THREAD

**Issue by hkashlan** [dotansimha/graphql-code-generator#6636]
**Describe the bug**
 

typescript-apollo-angular  is not supporting near-operation-file preset,  
as a result it is generating wrong document value.

Some Details:

1.  when using near-operation-file it creates `import * as Operations from './${this.clearExtension(basename(this._documents[0].location))}';` in this [line](https://github.com/dotansimha/graphql-code-generator/blob/263570e502dd179f1c4807f592df58d7f21ff096/packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts#L477)
2. and in [Angular Visitor](https://github.com/dotansimha/graphql-code-generator/blob/263570e502dd179f1c4807f592df58d7f21ff096/packages/plugins/typescript/apollo-angular/src/visitor.ts#L253)  it is not considering the Operations package.

**To Reproduce**

- Clone my repos (https://github.com/hkashlan/graphql-code-generator-issue-sandbox) which is based on graphql-code-generator-issue-sandbox
- run yarn generate
- in `document.graphql.gen.ts` you can find `document = UserDocument;` which is wrong I am expecting `document = Operations.UserDocument;`

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:
https://github.com/hkashlan/graphql-code-generator-issue-sandbox/blob/main/schema.graphql


2. My GraphQL operations:
https://github.com/hkashlan/graphql-code-generator-issue-sandbox/blob/main/document.graphql.ts

3. My `codegen.yml` config file:
https://github.com/hkashlan/graphql-code-generator-issue-sandbox/blob/main/codegen.yml

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
add Operations as a prefix to UserDocument
so it should be  `document = Operations.UserDocument;` 

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by n1ru4l** [comment]
@hkashlan Do you think you could create a PR with a failing test case for this?

**Comment by hkashlan** [comment]
@n1ru4l 
yes I can, 
could you please guide me how to do a PR?

**Comment by n1ru4l** [comment]
@hkashlan You can fork this repo, branch off and then follow the instructions over here: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by hkashlan** [comment]
@n1ru4l 
I created a PR, could you please review it?

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Ftypescript-apollo-angular%403.2.0
