### ISSUE TITLE
Lazy query hooks do not include the hooksSuffix config

### ISSUE THREAD

**Issue by johncblandii** [dotansimha/graphql-code-generator#6637]
**Describe the bug**

The lazy queries do not have the same suffix as the non-lazy version.

```typescript
export function useUserQuerySeasonal...
export function useUserLazyQuery...
```

The functions should match with just `Seasonal` (the suffix) added to the lazy version as well.

**To Reproduce**

1. My GraphQL schema:

https://codesandbox.io/s/wizardly-boyd-fdgi2?file=/schema.graphql

2. My GraphQL operations:

https://codesandbox.io/s/wizardly-boyd-fdgi2?file=/document.graphql

3. My `codegen.yml` config file:

https://codesandbox.io/s/wizardly-boyd-fdgi2?file=/codegen.yml

**Expected behavior**

```typescript
export function useUserQuerySeasonal(baseOptions?: Apollo.QueryHookOptions<UserQuery, UserQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UserQuery, UserQueryVariables>(UserDocument, options);
      }
export function useUserLazyQuerySeasonal(baseOptions?: Apollo.LazyQueryHookOptions<UserQuery, UserQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UserQuery, UserQueryVariables>(UserDocument, options);
        }
```

**Environment:**

- OS: any
- https://codesandbox.io/s/wizardly-boyd-fdgi2?file=/package.json 
- NodeJS: any

**Additional context**

**Comment by charlypoly** [comment]
Hi @johncblandii

Thank you for your contribution!

Your patch has been released in `@graphql-codegen/typescript-react-apollo@3.2.6`

**Comment by johncblandii** [comment]
> Hi @johncblandii
> 
> Thank you for your contribution!
> 
> Your patch has been released in `@graphql-codegen/typescript-react-apollo@3.2.6`

Oh wow. I forgot all about this one. 😁 Happy to help.
