### ISSUE TITLE
Template is not found

### ISSUE THREAD

**Issue by alonstar** [dotansimha/graphql-code-generator#668]
**Describe the bug**
I used the latest version of generator & tempalte, got an error.

error: Unknown codegen template: "graphql-codegen-typescript-template", please make sure it's installed using npm/Yarn!

**To Reproduce**
1. npm install --save-dev graphql-code-generator graphql
2. npm install --save-dev graphql-codegen-typescript-template
3.  $ gql-gen --schema http://localhost:3010/graphql --template graphql-codegen-typescript-template --out ./typings/ "./src/**/*.graphql"

**Environment:**
 - OS: Windows 10
 - Codegen:  0.12.6, Template 0.12.6
 - Node:  8.12.0

**Comment by ardatan** [comment]
Could you try the following command?
```
gql-gen --template graphql-codegen-typescript-template --out ./typings/ --schema http://localhost:3010/graphql "./src/**/*.graphql"
```

**Comment by gardinit** [comment]
I had the same issue; Here is my fix

`gql-gen--template node_modules/graphql-codegen-typescript-template --out ./src/gqlgen/saberGqlModel.ts --schema http://localhost:65164/graphql"`

**Comment by dotansimha** [comment]
@alonstar @gardinit which version of node and npm you are using? any chance you can share a reproduction? 
Specifying just `graphql-codegen-typescript-template` should work...

**Comment by alonstar** [comment]
@gardinit  it's work!! thank you.

@dotansimha @ardatan Here is execution log.

	D:\Graphql
	λ gql-gen --template node_modules/graphql-codegen-typescript-template --out models.ts --schema http://localhost:4701/mutual-fund-admin/gra phql
	10:41:36.336 - info: Loading GraphQL Introspection from remote: http://localhost:4701/mutual-fund-admin/graphql...
	10:41:39.228 - info: Generated file written to D:\Graphql\models.ts

	D:\Graphql
	λ gql-gen --template graphql-codegen-typescript-template --out models.ts --schema http://localhost:4701/mutual-fund-admin/graphql
	10:42:13.841 - error: Unknown codegen template: "graphql-codegen-typescript-template", please make sure it's installed using npm/Yarn!

	D:\Graphql
	λ node -v
	v8.12.0

	D:\Graphql
	λ npm -v
	6.4.1

**Comment by dotansimha** [comment]
I'm note sure what's the actual issue here, but we did changed the way we load templates, so it might work now. @alonstar i'm closing this issue at the moment. Can you please try with the latest API and re-open if it still happens?
