### ISSUE TITLE
gql-tag-operations only allows one operation per gql call

### ISSUE THREAD

**Issue by fivethreeo** [dotansimha/graphql-code-generator#6682]
**Describe the bug**
 

**To Reproduce**

Try the example from the 2.0 blog post. 

I will write a test.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by fivethreeo** [comment]
https://github.com/dotansimha/graphql-code-generator/pull/6684

**Comment by n1ru4l** [comment]
@fivethreeo The blog post showcased the initial version built by @arcanis 

For now, we decided that each operation/fragment should have its own tag. Could you explain why you would want to use one gql tag call instead?

**Comment by fivethreeo** [comment]
I think this came about because I had a older codegen plugin installed. So I could not get multiple gql calls working. Then I tried the example for the initial version and it did not work. So that blog post is a bit confusing for beginners, should be clarified that it does not work with multiple operations in one gql call.

So maybe this just adds needless complexity.

**Comment by n1ru4l** [comment]
@fivethreeo You can follow the documentation over on https://www.graphql-code-generator.com/docs/presets/gql-tag-operations

I will update the blog post to point to that and close your PR

**Comment by n1ru4l** [comment]
Closing this as we will for now not support it and keep the complexity of gql-tag-operations low and opinionated (https://github.com/dotansimha/graphql-code-generator/issues/6682).
