### ISSUE TITLE
ResolversParentTypes reference non-existing fields of themselves

### ISSUE THREAD

**Issue by puchm** [dotansimha/graphql-code-generator#6709]
**Describe the bug**
 
Sometimes it can happen with the `typescript-resolvers` plugin that some fields in `ResolversParentTypes` contain references to other fields in `ResolversParentTypes` that don't exist. This only happens with enums that are mapped using the "mappers" functionality.
E.g. look at this from the reproduction sandbox:
```ts
export type ResolversParentTypes = {
  Query: {};
  User: Omit<User, 'gender'> & { gender?: Maybe<ResolversParentTypes['Gender']> };
  Boolean: Scalars['Boolean'];
  String: Scalars['String'];
};
```
`ResolversParentTypes['Gender']` doesn't exist.

Note that this **only happens when mappers are used**.

**To Reproduce**
Repro sandbox: https://codesandbox.io/s/crazy-fast-rcgcb?file=/types.ts:3977-4172

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
extend type Query {
    gender: User!
}

type User {
    gender: Gender
}

enum Gender {
    MALE
    FEMALE
}

```

2. My GraphQL operations:

```graphql
# None
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      mappers:
        Gender: ./gender#OtherGender
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
I think there's two things that would make sense:
1. Include enums in `ResolversParentTypes`
2. The syntax where it omits a field from a type and then concatenates it together again (types.ts line 112 in sandbox) makes no sense in this scenario I think.


**Environment:**

- OS: 
- `@graphql-codegen/cli`: "1.20.1",
- `@graphql-codegen/typescript`: "1.21.0",
- `@graphql-codegen/typescript-resolvers`: "^2.2.1",
- NodeJS: 14.17.6

**Additional context**
<!-- Add any other context about the problem here. -->

Once again: Note that this only happens when mappers are used on enums (as far as I know)

Also, it appears to me that this only happens when the types are nested. I tried adding a field to the `Query` type that returns a `Gender` directly and the result was fine.

I have been digging into the code and [this](https://github.com/dotansimha/graphql-code-generator/blob/0b090e31ad668d993ccdb145d2f0edc8518d740a/packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts#L889-L893) part seems to have something to do with the problem - although I can't find the logic yet concerning the mappers...

**Comment by puchm** [comment]
I added a filter function that checks if the fields are included when the "Omit" thing is applied. I honestly don't really understand what the "Omit" thing is about but this fixes my issue. It's right [here](https://github.com/puchm/graphql-code-generator/blob/5a7a299d3149e8c6468aa1ab90066995f7b18489/packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts#L567-L576).

Should I open a pull request or is this not the right way to solve it?

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Fvisitor-plugin-common%402.4.0
