### ISSUE TITLE
[TypeScript React-Query] exposeFetcher for mutation and exposeMutationKeys

### ISSUE THREAD

**Issue by judastheo** [dotansimha/graphql-code-generator#6724]
**Is your feature request related to a problem? Please describe.**

We are migrating more and more of our API calls to the queries and mutations generated. And sometimes, we want to replace old mutation calls by new ones that are used outside of functional component, hence we cannot use hooks.

**Describe the solution you'd like**

For queries, you already enabled `exposeFetcher` and `exposeQueryKeys` that matches our needs! It would be great to also have  `getKey` and `fetcher` for mutations.

The config of `typescript-react-query` could have two more boolean options:
- `exposeMutationKeys`
- `exposeMutationFetcher`

The generated code could look exactly the same as queries generated with `exposeFetcher` and `exposeQueryKeys`:

```tsx
useMyMutation.getKey = (
  variables: MyMutationVariables
) => ['my', variables];

useMyMutation.fetcher = (
  variables: MyMutationVariables
) =>
  fetch<MyMutation, MyMutationVariables>(
    MyDocument,
    variables
  );
```

**Failing test proposal**

Not very used to it, but here is what I think could be added inside [plugins/typescript/react-query/tests/react-query.spec.ts](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/react-query/tests/react-query.spec.ts)

```ts
    it("Should generate fetcher field when exposeMutationFetcher is true and the fetcher isn't a react hook", async () => {
      const config = {
        fetcher: {
          func: './my-file#customFetcher',
        },
        exposeMutationFetcher: true,
      };

      const out = (await plugin(schema, docs, config)) as Types.ComplexPluginOutput;
      expect(out.content).toBeSimilarStringTo(
        `useTestMutation.fetcher = (variables?: TTestMutationVariables) => customFetcher<TTestMutation, TTestMutationVariables>(TestDocument, variables);`
      );
    });

    it('Should NOT generate fetcher field when exposeMutationFetcher is true and the fetcher IS a react hook', async () => {
      const config = {
        fetcher: {
          func: './my-file#useCustomFetcher',
          isReactHook: true,
        },
        exposeMutationFetcher: true,
      };

      const out = (await plugin(schema, docs, config)) as Types.ComplexPluginOutput;
      expect(out.content).not.toBeSimilarStringTo(`useTestMutation.fetcher`);
    });

  describe('exposeMutationKeys: true', () => {
    it('Should generate getKey for each mutation', async () => {
      const config = {
        fetcher: 'fetch',
        exposeMutationKeys: true,
      };
      const out = (await plugin(schema, docs, config)) as Types.ComplexPluginOutput;
      expect(out.content).toBeSimilarStringTo(
        `useTestMutation.getKey = (variables?: TTestMutationVariables) => variables === undefined ? ['test'] : ['test', variables];`
      );
    });
  });
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Urigo** [comment]
Hi @judastheo and thank you for the report!

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

One way of pushing this forward would be to add an example of the input and the output you expect to get.
Maybe even adding a failing test so we could get this into [stage 2](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)!

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by judastheo** [comment]
Thanks @Urigo, I edited my comment, I hope it fits the requirements!

**Comment by Urigo** [comment]
thanks!  do you think you could prepare a failing test for this new feature?

**Comment by judastheo** [comment]
Not very used to it, but here is what I think could be added inside [plugins/typescript/react-query/tests/react-query.spec.ts](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/react-query/tests/react-query.spec.ts)

```ts
    it("Should generate fetcher field when exposeMutationFetcher is true and the fetcher isn't a react hook", async () => {
      const config = {
        fetcher: {
          func: './my-file#customFetcher',
        },
        exposeMutationFetcher: true,
      };

      const out = (await plugin(schema, docs, config)) as Types.ComplexPluginOutput;
      expect(out.content).toBeSimilarStringTo(
        `useTestMutation.fetcher = (variables?: TTestMutationVariables) => customFetcher<TTestMutation, TTestMutationVariables>(TestDocument, variables);`
      );
    });

    it('Should NOT generate fetcher field when exposeMutationFetcher is true and the fetcher IS a react hook', async () => {
      const config = {
        fetcher: {
          func: './my-file#useCustomFetcher',
          isReactHook: true,
        },
        exposeMutationFetcher: true,
      };

      const out = (await plugin(schema, docs, config)) as Types.ComplexPluginOutput;
      expect(out.content).not.toBeSimilarStringTo(`useTestMutation.fetcher`);
    });

  describe('exposeMutationKeys: true', () => {
    it('Should generate getKey for each mutation', async () => {
      const config = {
        fetcher: 'fetch',
        exposeMutationKeys: true,
      };
      const out = (await plugin(schema, docs, config)) as Types.ComplexPluginOutput;
      expect(out.content).toBeSimilarStringTo(
        `useTestMutation.getKey = (variables?: TTestMutationVariables) => variables === undefined ? ['test'] : ['test', variables];`
      );
    });
  });
```

**Comment by Urigo** [comment]
thank you!  can you open it as a PR? it would give us a good start!

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Ftypescript-react-query%403.2.3
