### ISSUE TITLE
Commented queries not ignored

### ISSUE THREAD

**Issue by patricknazar** [dotansimha/graphql-code-generator#680]
**Describe the bug**
Commented `gql` tags not getting ignored in document. I have some queries that are commented in my typescript code but they are still getting read.

**To Reproduce**
1. Create a typescript file with a commented query ``/*gql`...*/``
2. `code-gen ... src/**/*/*.ts`

**Expected behavior**
Doesn't read commented queries. 

**Environment:**
 - OS: Ubuntu
 - Codegen: 0.12.6
 - Node: 8

**Comment by dotansimha** [comment]
@patricknazar can you please provide a complete file? it will be easier to fix the document-finder regex this way...  thanks

**Comment by patricknazar** [comment]
You know, it's weird I can't seem to reproduce it anymore, and I'm using `.graphql` files instead of `.ts` now, I'll close this for now and reopen if I experience it again.
