### ISSUE TITLE
gql-tag-operations - preset generates sources with \r\n new lines, which don't match the source

### ISSUE THREAD

**Issue by freshollie** [dotansimha/graphql-code-generator#6811]
**Describe the bug**
On windows the preset parses the gql documents and generates a map with `\r\n` newlines. This would be fine (though the source doesn't contain `\r` new lines, so not sure why this is happen), but because the source strings don't exactly match the input strings at runtime (especially after bundling), javascript fails to match the query to the compiled source.

For now, I am switching to `augmentedModuleName` which will solve this issue for me, however I thought this was worth flagging.

**To Reproduce**

On windows, run codegen with the `gql-tag-operations` preset. The `documents` map will looks something like this:

```typescript
const documents = {
    "\r\n      subscription OnConnectionChanged($connection: ID!) {\r\n        onConnectionChanged(connectionId: $connection)\r\n      }\r\n    ": graphql.OnConnectionChangedDocument,
    "\r\n      mutation Disconnect($connection: ID!) {\r\n        close(connectionId: $connection)\r\n      }\r\n    ": graphql.DisconnectDocument,
    "\r\n      mutation DisableArming($connection: ID!) {\r\n        deviceSetArming(\r\n          connectionId: $connection\r\n          armingDisabled: true\r\n          runawayTakeoffPreventionDisabled: false\r\n        )\r\n      }\r\n    ": graphql.DisableArmingDocument,
   ...
}
```    

**Expected behavior**

I would expect the generated source to match the input source new line characters

```typescript
const documents = {
    "\n      subscription OnConnectionChanged($connection: ID!) {\n        onConnectionChanged(connectionId: $connection)\n      }\n    ": graphql.OnConnectionChangedDocument,
    "\n      mutation Disconnect($connection: ID!) {\n        close(connectionId: $connection)\n      }\n    ": graphql.DisconnectDocument,
    "\n      mutation DisableArming($connection: ID!) {\n        deviceSetArming(\n          connectionId: $connection\n          armingDisabled: true\n          runawayTakeoffPreventionDisabled: false\n        )\n      }\n    ": graphql.DisableArmingDocument,
   ...
}
```

**Environment:**

- OS: Windows 10
- `@graphql-codegen/gql-tag-operations@1.2.0.`: 
- NodeJS: 16

**Additional context**

**Comment by n1ru4l** [comment]
Can you provide a full reproduction?

**Comment by freshollie** [comment]
Hi @n1ru4l 

I'll try and get you a simple one soon. 

Alternatively, [this commit](https://github.com/freshollie/fresh-configurator/tree/b3e6e0638a8576b1c4b860dfd3ea84589bf4ab86) in my open source application will fail to compile on windows but compiles fine on macos and linux ([workflow](https://github.com/freshollie/fresh-configurator/runs/3852318866?check_suite_focus=true))

![image](https://user-images.githubusercontent.com/11363036/142404531-6084d6ba-dd1c-44fc-8267-d7c657c0e65b.png)

[This commit](https://github.com/freshollie/fresh-configurator/commit/c3a86f44234c5677039f596671171d05f935c85c) fixed the issue by patching the codegen plugin to replace `\r\n` lines with `\n`

**Comment by n1ru4l** [comment]
@freshollie Do you check out files with different line-endings on windows? Ideally, you use the same line endings on each platform and let you editor take care of converting from and to your platform line endings while you edit code.

I have no issues on my Mac and Windows machines using the preset.

**Comment by freshollie** [comment]
I'm using whatever default settings github uses for windows boxes. When I cloned on a windows machine locally (with git-bash) to diagnose I had the same issue. I write all my stuff on linux and MacOS, so none of the files should have `\r\n` line endings.

**Comment by freshollie** [comment]
Ok, so the solution is to have `.gitattributes` to ensure that line endings are not replaced with `CRLF`

```gitattributes
# Fix line endings on windows
src/**/*.ts text eol=lf
src/**/*.tsx text eol=lf
```

I think this threw me because it's the first time I've encountered Codegen plugin which doesn't work on windows if the line endings change.

**Comment by n1ru4l** [comment]
@freshollie Should we add this to the docs?

**Comment by freshollie** [comment]
Might be good so others don't get caught by this

**Comment by n1ru4l** [comment]
@freshollie it would be awesome if you could  contribute this 😇
