### ISSUE TITLE
Export generated fragment constants (apollo angular)

### ISSUE THREAD

**Issue by patricknazar** [dotansimha/graphql-code-generator#682]
**Is your feature request related to a problem? Please describe.**
I need to use generated fragment constants in my resolvers (apollo-link-state resolvers btw) but I cannot use the generated ones as they are not exported.

**Describe the solution you'd like**
Instead of just `const` I would like `export const` in the generated file.

**Describe alternatives you've considered**
Currently I have to make them up again, which is not ideal

**Additional context**
The interfaces and classes are already exported, but these constants are not.

**Comment by dotansimha** [comment]
fixed in 0.13.0. @patricknazar
