### ISSUE TITLE
ObjectID is deprecated in MongoDB Node.js driver

### ISSUE THREAD

**Issue by fredriklindell** [dotansimha/graphql-code-generator#6830]
**Describe the bug**
MongoDB Node.js driver v4.1 has deprecated ObjectID in favor of ObjectId.

**To Reproduce**
Steps to reproduce the behavior: run `graphql-codegen` in project with below environment.

**Environment:**
- OS: linux
- `@graphql-codegen/typescript-mongodb`: 2.1.4
- NodeJS: 14.17.4
- mongodb: 4.1.3

**Comment by sauhardo2020** [comment]
Thanks!

**Comment by lifecycles1** [comment]
Thanks!

**Comment by tubbo** [comment]
Pretty sure this broke interface types using ObjectID in their types.

![Screen Shot 2022-02-10 at 4 46 46 PM](https://user-images.githubusercontent.com/113026/153502028-572632da-3210-45ac-a38c-ef35fbbfcc4b.png)

This is what is generated after updating to **v2.3.1**. `EventRegistration` is a GraphQL interface while `Friend` is a regular told GraphQL type definition.

**Comment by gregg-cbs** [comment]
I am seeing this:
![image](https://user-images.githubusercontent.com/57114335/178910041-03a910ac-7f7c-4071-a8b9-88c4b1e2f177.png)

Note at the bottom "ObjectID is deprecated"

**Comment by dotansimha** [comment]
This was fixed a long time ago in https://github.com/dotansimha/graphql-code-generator/pull/6831 
If someone is having an issue with that, please upgrade to latest.

**Comment by IanPaniagua** [comment]
I have this problem: 
The signature '(inputId: number): ObjectId' of 'ObjectId' is deprecated.ts(6387)
bson.d.ts(1106, 8): The declaration was marked as deprecated here.
const ObjectId: new (inputId: number) => mongodb.BSON.ObjectId (+6 overloads)
Create ObjectId from a number.

@param inputId — A number.

@deprecated — Instead, use static createFromTime() to set a numeric value for the new ObjectId.

I'm using ObjectId not ObjectID, but any way I have the problem.
And i don't find any solution

**Comment by chrisjameslennon** [comment]
I am using the latest MongoDB nodejs driver (6.5.0). I am using NodeJS 20 and javascript (i.e. not typescript). I have the exact same issue ^^

**Comment by rduinkerken** [comment]
This below is the createFromTime function under the hood
```ts
/**
     * Creates an ObjectId from a second based number, with the rest of the ObjectId zeroed out. Used for comparisons or sorting the ObjectId.
     *
     * @param time - an integer number representing a number of seconds.
     */
    static createFromTime(time: number): ObjectId;
```

So instead of using something like 
```ts
const MyId = "a string value of an objectid";
const MyId = new ObjectId(MyId);
```

You can use the `createFromTime` function on `ObjectId`.

You can create an ObjectId like this
```ts
const MyId = ObjectId.createFromTime(Date.now());
```
(`Date.now()` returns the current time in milliseconds)

Hope this helps!

**Comment by windymiles** [comment]
The `createFromTime` wasn't helpful for me. If you already have an id in a string, you can use `createFromHexString`:

```
const { ObjectId } = require("mongodb");
const strId= '78085939165a472b49439fed'
const objId = ObjectId.createFromHexString(strId)
const results = myCollection.find({ _id: objId})

```
This thread is a little old, but in case others come across it like I did, I hope it helps.

**Comment by IanPaniagua** [comment]
Thank you so much

**Comment by GustavoOS** [comment]
> This below is the createFromTime function under the hood
> 
> ```ts
> /**
>      * Creates an ObjectId from a second based number, with the rest of the ObjectId zeroed out. Used for comparisons or sorting the ObjectId.
>      *
>      * @param time - an integer number representing a number of seconds.
>      */
>     static createFromTime(time: number): ObjectId;
> ```
> 
> So instead of using something like
> 
> ```ts
> const MyId = "a string value of an objectid";
> const MyId = new ObjectId(MyId);
> ```
> 
> You can use the `createFromTime` function on `ObjectId`.
> 
> You can create an ObjectId like this
> 
> ```ts
> const MyId = ObjectId.createFromTime(Date.now());
> ```
> 
> (`Date.now()` returns the current time in milliseconds)
> 
> Hope this helps!

This helps regarding creation, not parsing an existing one

**Comment by GustavoOS** [comment]
> The `createFromTime` wasn't helpful for me. If you already have an id in a string, you can use `createFromHexString`:
> 
> ```
> const { ObjectId } = require("mongodb");
> const strId= '78085939165a472b49439fed'
> const objId = ObjectId.createFromHexString(strId)
> const mydoc = await myCollection.findOne({ _id: objId})
> ```
> 
> This thread is a little old, but in case others come across it like I did, I hope it helps.

Thank you! This worked :)

**Comment by Vandu024** [comment]
Having same problem related to objectid  what should i do

const notes = await Note.aggregate([
      { $sort: { updatedAt: -1 } },
      { $match: { user: new mongoose.Types.ObjectId(req.user.id) } },
      {
        $project: {
          title: { $substr: ["$title", 0, 30] },
          body: { $substr: ["$body", 0, 100] },
        },
      }

**Comment by projectninjatech** [comment]
> The `createFromTime` wasn't helpful for me. If you already have an id in a string, you can use `createFromHexString`:
> 
> ```
> const { ObjectId } = require("mongodb");
> const strId= '78085939165a472b49439fed'
> const objId = ObjectId.createFromHexString(strId)
> const mydoc = await myCollection.findOne({ _id: objId})
> ```
> 
> This thread is a little old, but in case others come across it like I did, I hope it helps.

const { id } = req.body;
const userID = ObjectId.createFromHexString(id)
const usersCollection = db.collection("users");
const user = await usersCollection.findOne({ _id: userID });
This worked for me

**Comment by diogomends** [comment]
Fiz assim no model e ele converteu:
 
 import mongoose from "mongoose";

 id: {
      type: mongoose.ObjectId,
      required: true,
    },
