### ISSUE TITLE
rollup plugin for gql-tag-operations preset

### ISSUE THREAD

**Issue by jgoux** [dotansimha/graphql-code-generator#6883]
Hello,

**Is your feature request related to a problem? Please describe.**

It would be great to have a rollup version of the [babel plugin](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/presets/gql-tag-operations/src/babel.ts) for the gql-tag-operations preset.

It would allow rollup and Vite.js users to use this awesome preset to its full potential. 😄 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by abdonrd** [comment]
@jgoux could you share how you finally did the setup for this? Thanks!
