### ISSUE TITLE
looking for debugging next steps

### ISSUE THREAD

**Issue by BasHamer** [dotansimha/graphql-code-generator#689]
**Describe the bug**
I'm getting inconsistent behavior between the codegen systems, I'm posting here because this is the one I'd like to get working.

This works:
apollo schema:download --endpoint=http://localhost:4446/graphql
gql-gen --schema schema.json --template node_modules/graphql-codegen-typescript-template --out ./src/generated/graphql.ts "./src/**/*.graphql"

This does not work:
apollo schema:download --endpoint=http://localhost:4446/graphql
gql-gen --schema schema.json --template node_modules/graphql-codegen-apollo-angular-template --out ./src/generated/graphql.ts "./src/**/*.graphql"

output: (both commands)
 √ Loading Apollo config
 √ Fetching current schema
 √ Saving schema to schema.json
13:10:59.145 - info: Loading GraphQL Introspection from file: schema.json...
13:10:59.254 - error:

Please note that I did not forget to copy the error, there is just no text. So yeah, any tips on how to get to meaningful information would be awesome.

I'm on windows 10, .net core hosts the endpoint, I hoped that I could take that out of the equation by downloading to json.

[schema.zip](https://github.com/dotansimha/graphql-code-generator/files/2475764/schema.zip)

**Comment by ardatan** [comment]
Could you try the following command?
```
gql-gen --schema http://localhost:4446/graphql --template node_modules/graphql-codegen-typescript-template --out ./src/generated/graphql.ts "./src/**/*.graphql"
```

**Comment by BasHamer** [comment]
PS C:\<Stuff>\App> gql-gen --schema http://localhost:4446/graphql --template node_modules/graphql-codegen-typescript-template --out ./src/generated/graphql.ts "./src/**/*.graphql"
15:27:15.736 - info: Loading GraphQL Introspection from remote: http://localhost:4446/graphql...
15:27:16.777 - error:

**Comment by dotansimha** [comment]
@BasHamer Can you please try the latest version? We fixed a lot of issues regarding the schema loading and merging. 
Please re-open if it still happens.
