### ISSUE TITLE
Add a way to include introspection to schema-ast plugin

### ISSUE THREAD

**Issue by gajus** [dotansimha/graphql-code-generator#6900]
**Is your feature request related to a problem? Please describe.**

Need to have introspection included in GraphQL schema. 

**Describe the solution you'd like**

`includeIntrospection` flag that includes introspection query.

**Describe alternatives you've considered**

Using https://github.com/erictaylor/graphql-codegen-schema-ast

**Additional context**

Happy to submit the PR.

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Fschema-ast%402.4.0
