### ISSUE TITLE
[Feature Request] add `skipPascalCase` option to graphql-codegen-typescript-template config

### ISSUE THREAD

**Issue by frantic1048** [dotansimha/graphql-code-generator#691]
**Is your feature request related to a problem? Please describe.**
I'm updating `graphql-code-generator` from a relatively old version( **0.9.3** ) to latest version( **0.12.6** ). I noticed a compulsive type name conversion was added to `graphql-codegen-typescript-template`.

https://github.com/dotansimha/graphql-code-generator/blob/42633a9d8478f448a034f828a733d79b298d15e9/packages/templates/typescript/src/utils/get-result-type.ts#L11

It makes some non-strict PascalCase type names be different from schema.json from the backend. I know a consistent name convention is a thing. But it should be done in one place, in the source of schema.json (i.e. the backend side), instead of putting an uncontrollable, implicit conversion between frontend and backend.

**Describe the solution you'd like**

I think we could add `skipPascalCase` option to `graphql-codegen-typescript-template` config to skip the type name conversion and keep current default value(prevent from breaking change).

**Comment by dotansimha** [comment]
Makes sense. It also effects other aspects and parts of the code, it might take some time until we'll manage to work on it

**Comment by dotansimha** [comment]
Fixed in 0.14. You can now specify `namingConvention` config. 🎉
