### ISSUE TITLE
graphql 16 support

### ISSUE THREAD

**Issue by juanlatorre** [dotansimha/graphql-code-generator#6937]
**Describe the bug**
graphql-codegen isn't working with graphql 16

**To Reproduce**
Update graphql to 16.0.0
https://codesandbox.io/s/codegen-graphql16-bug-pv9db

**Environment:**

- OS: macOS Monterey 12.0.1
- NodeJS: v16.13.0

**Additional context**

```bash
> graphql-codegen --config codegen.yml --watch

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/graphql/index.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → visitFn.call is not a function


 Found 1 error

  ✖ src/graphql/index.ts
    TypeError: visitFn.call is not a function
        at Object.visit (/project/node_modules/.pnpm/graphql@16.0.0/node_modules/graphql/language/visitor.js:200:21)
        at Object.plugin (/project/node_modules/.pnpm/@graphql-codegen+typescript@2.2.4_graphql@16.0.0/node_modules/
@graphql-codegen/typescript/index.js:367:35)
        at executePlugin (/project/node_modules/.pnpm/@graphql-codegen+core@2.2.0_graphql@16.0.0/node_modules/@graph
ql-codegen/core/index.js:38:35)
        at /project/node_modules/.pnpm/@graphql-codegen+core@2.2.0_graphql@16.0.0/node_modules/@graphql-codegen/core
/index.js:167:30
        at Array.map (<anonymous>)
        at Object.codegen (/project/node_modules/.pnpm/@graphql-codegen+core@2.2.0_graphql@16.0.0/node_modules/@grap
hql-codegen/core/index.js:157:54)
        at async process (/project/node_modules/.pnpm/@graphql-codegen+cli@2.2.1_graphql@16.0.0+typescript@4.4.4/nod
e_modules/@graphql-codegen/cli/bin.js:1003:56)
        at async Promise.all (index 0)
        at async /project/node_modules/.pnpm/@graphql-codegen+cli@2.2.1_graphql@16.0.0+typescript@4.4.4/node_modules
/@graphql-codegen/cli/bin.js:1010:37
        at async Task.task (/project/node_modules/.pnpm/@graphql-codegen+cli@2.2.1_graphql@16.0.0+typescript@4.4.4/n
ode_modules/@graphql-codegen/cli/bin.js:789:17)
    TypeError: visitFn.call is not a function
        at Object.visit (/project/node_modules/.pnpm/graphql@16.0.0/node_modules/graphql/language/visitor.js:200:21)
        at Object.plugin (/project/node_modules/.pnpm/@graphql-codegen+typescript@2.2.4_graphql@16.0.0/node_modules/
@graphql-codegen/typescript/index.js:367:35)
        at executePlugin (/project/node_modules/.pnpm/@graphql-codegen+core@2.2.0_graphql@16.0.0/node_modules/@graph
ql-codegen/core/index.js:38:35)
        at /project/node_modules/.pnpm/@graphql-codegen+core@2.2.0_graphql@16.0.0/node_modules/@graphql-codegen/core
/index.js:167:30
        at Array.map (<anonymous>)
        at Object.codegen (/project/node_modules/.pnpm/@graphql-codegen+core@2.2.0_graphql@16.0.0/node_modules/@grap
hql-codegen/core/index.js:157:54)
        at async process (/project/node_modules/.pnpm/@graphql-codegen+cli@2.2.1_graphql@16.0.0+typescript@4.4.4/nod
e_modules/@graphql-codegen/cli/bin.js:1003:56)
        at async Promise.all (index 0)
        at async /project/node_modules/.pnpm/@graphql-codegen+cli@2.2.1_graphql@16.0.0+typescript@4.4.4/node_modules
/@graphql-codegen/cli/bin.js:1010:37
        at async Task.task (/project/node_modules/.pnpm/@graphql-codegen+cli@2.2.1_graphql@16.0.0+typescript@4.4.4/n
ode_modules/@graphql-codegen/cli/bin.js:789:17)
```

**Comment by PabloSzx** [comment]
GraphQL v16 support was released with @graphql-codegen/core@2.3.0 and friends, more details with all the updated packages here: https://github.com/dotansimha/graphql-code-generator/pull/6892

**Comment by li9269391** [comment]
Graphql v16.6.0， will still report an error，

```
    "@graphql-codegen/cli": "2.13.7",
    "@graphql-codegen/core": "2.6.2",
    "@graphql-codegen/plugin-helpers": "2.7.1",
    "@graphql-codegen/typescript": "2.8.0",
    "@graphql-codegen/typescript-operations": "2.5.5",
    "@graphql-codegen/visitor-plugin-common": "2.13.0",
    "graphql": "16.6.0",
```

**Comment by ethanrcohen** [comment]
> Graphql v16.6.0， will still report an error，
> 
> ```
>     "@graphql-codegen/cli": "2.13.7",
>     "@graphql-codegen/core": "2.6.2",
>     "@graphql-codegen/plugin-helpers": "2.7.1",
>     "@graphql-codegen/typescript": "2.8.0",
>     "@graphql-codegen/typescript-operations": "2.5.5",
>     "@graphql-codegen/visitor-plugin-common": "2.13.0",
>     "graphql": "16.6.0",
> ```
> 
> I found it when writing plug-ins. Example:
> 
> ```
> import { visit } from 'graphql';
> import { getCachedDocumentNodeFromSchema } from '@graphql-codegen/plugin-helpers';
> 
>  const myPlugin = {
>       plugin(schema, documents, config) {
>         const astNode = getCachedDocumentNodeFromSchema(schema) 
>         const visitor:any = {
>           FieldDefinition(node:any) {
>             
>           },
>           ObjectTypeDefinition(node:any) {
>             
>           }
>         }
>         const result = visit(astNode, { leave: visitor });
>         // return result.definitions.join('\n')
>         return ''
>       }
>   }
> ```
> 
> error
> 
> ```
> /Users/yooly/github/gql-code-gen-demo/node_modules/.pnpm/graphql@16.0.0/node_modules/graphql/language/visitor.js:200
>           : visitFn.call(visitor, node, key, parent, path, ancestors);
>                     ^
> TypeError: visitFn.call is not a function
>     at visit (/Users/yooly/github/gql-code-gen-demo/node_modules/.pnpm/graphql@16.0.0/node_modules/graphql/language/visitor.js:200:21)
>     at Object.plugin (/Users/yooly/github/gql-code-gen-demo/src/index.ts:62:31)
>     at /Users/yooly/github/gql-code-gen-demo/node_modules/.pnpm/@graphql-codegen+core@2.6.2_graphql@16.0.0/node_modules/@graphql-codegen/core/cjs/execute-plugin.js:36:54
>     at /Users/yooly/github/gql-code-gen-demo/node_modules/.pnpm/@graphql-codegen+plugin-helpers@2.7.1_graphql@16.0.0/node_modules/@graphql-codegen/plugin-helpers/cjs/profiler.js:7:49
> ```

@li9269391 did you find a solution here?

**Comment by fjcaetano** [comment]
Can we reopen this issue since it seems that it's still relevant and there are quite a few people being affected (or at least reacting) to it?

Just tried upgrading to `graphql@16.6.0` and `@graphql-codegen/cli@2.16.1` and I stumbled upon this issue. 

Downgrading to graphql 15 got rid of the issue, but this workaround is far from ideal

**Comment by jastako** [comment]
+1

**Comment by gtwebsite** [comment]
Also have same issue, moving to 15.0.0. fixed the issue
