### ISSUE TITLE
Is it possible to use original names, not camel?

### ISSUE THREAD

**Issue by ThePlenkov** [dotansimha/graphql-code-generator#6946]
Hi! I try to generate a schema for Gitlab with the following file:
```yaml
schema: "https://gitlab.com/api/graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
```

However in the generated file I see many errors like that:
```
Duplicate identifier 'CreatedAsc'.
Duplicate identifier 'CreatedDesc'.
Duplicate identifier 'UpdatedAsc'.
Duplicate identifier 'UpdatedDesc'.
```

checking original schema i see that they have something like this:
```
 {
        "kind": "ENUM",
        "name": "AlertManagementAlertSort",
        "description": "Values for sorting alerts",
        "fields": null,
        "inputFields": null,
        "interfaces": null,
        "enumValues": [
          {
            "name": "CREATED_ASC",
            "description": "Created at ascending order.",
            "isDeprecated": false,
            "deprecationReason": null
          },
...
     
          {
            "name": "created_asc",
            "description": "Created at ascending order.",
            "isDeprecated": false,
            "deprecationReason": null
          },
```

It looks like they try to support both upper and lower case, which is fine.

The only solution in this case would be using original case in enum, not transformed one.

Do you think is possible?

Thank you!

**Comment by ardatan** [comment]
We have `namingConvention` options in configuration so you can configure it;
https://www.graphql-code-generator.com/docs/plugins/typescript

**Comment by ThePlenkov** [comment]
> We have `namingConvention` options in configuration so you can configure it; https://www.graphql-code-generator.com/docs/plugins/typescript

Exactly what I was searching for:
```
config:
  namingConvention:
    enumValues: keep
```

Thank you!
