### ISSUE TITLE
__typename should not be optional when used in query

### ISSUE THREAD

**Issue by frantic1048** [dotansimha/graphql-code-generator#700]
**Describe the bug**
When use `__typename` in a query, it's type should not be optional in corresponding query namespace.

**To Reproduce**

*schema*:

```gql
# schema.graphql

type Person {
  name: String!
}

type Query {
  person: Person
}
```

*document*:

```gql
query search {
  person {
    __typename
    name
  }
}
```

*command*: `gql-gen --template graphql-codegen-typescript-template --schema schema.graphql document.graphql --out schema.ts`

**Expected behavior**

The namespace of `query search` in generated `schema.ts`:

```ts
export namespace Search {
  export type Variables = {};

  export type Query = {
    __typename?: "Query";
    person?: Person | null;
  };

  export type Person = {
    __typename?: "Person"; // <- this should not be optional because we used it in query
    name: string;
  };
}
```

`Search.Person.__typename` is optional, while it should not be.

**Environment:**
- OS: Arch Linux (latest)
- Codegen: 0.12.6
- Node: 10.11.0
- graphql: 14.0.2

**Comment by frantic1048** [comment]
ehh, I found `__typename` is directly droped in [`get-field-def.ts`](https://github.com/dotansimha/graphql-code-generator/blob/c5ee0f70690190bb74d7d97bda545779323c9644/packages/graphql-codegen-core/src/utils/get-field-def.ts#L6). It looks many places need to be changed to solve this..

**Comment by dotansimha** [comment]
Thanks @frantic1048 . It's a bug and the way to fix it is to check if the selection set has `__typename` and generate the `?` according to it.

**Comment by dotansimha** [comment]
Fixed in 0.15.2 :)

**Comment by mfbx9da4** [comment]
So this is supposedly fixed but I don't see any docs of how to use the query version where `__typename` is required any guidance?

**Comment by saschb2b** [comment]
@mfbx9da4 `nonOptionalTypename: true` made it required for me
