### ISSUE TITLE
Consider publishing all packages with graphql@16 support

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [dotansimha/graphql-code-generator#7003]
**Is your feature request related to a problem? Please describe.**

Changes to support `graphql@16` as a peer dependency has been committed to all packages in this repository, but some have yet to be published. This is not a comprehensive list, but some which have been identified:
- `@graphql-codegen/core`
- `@graphql-codegen/introspection`
- `@graphql-codegen/add`

Some packages have been published since the creation of this issue such as `@graphql-codegen/cli`, `@graphql-codegen/typescript-operations` and `@graphql-codegen/visitor-plugin-common`.

**Describe the solution you'd like**
New publications of packages with `graphql@^16` in the peer dependencies that have not yet been published.

**Describe alternatives you've considered**

**Additional context**

Considering the wave of other `@graphql-codegen` packages simultaneously adding support, could it be this particular upgrade remains unpublished by mistake?

**Comment by dotansimha** [comment]
@ardatan can you please check?

**Comment by ardatan** [comment]
v16 is missing in peerDependencies. Other than that, v16 is fully supported

**Comment by JamiesWhiteShirt** [comment]
Looking deeper into my dependency graph, I discovered that there are a few more packages that have yet to be published with `graphql@^16` in peerDependencies. This is not a comprehensive list, I only looked at my own dependencies.
- `@graphql-codegen/typescript-apollo-client-helpers`
- `@graphql-codegen/typescript-operations`
- `@graphql-codegen/visitor-plugin-common`

I also identified a few transitive dependencies via graphql-tools that have yet to support `graphql@16`, namely `graphql-request` and `relay-compiler`. That might not be a problem, though.

**Comment by yura3d** [comment]
- @graphql-codegen/core@2.3.0
- @graphql-codegen/add@3.1.0

**Comment by jokinol** [comment]
Missing GraphQL 16.x in perDeps in @graphql-codegen/add prevents us to upgrade to GraphQL 16. Would it be possible to release that with updated deps?

**Comment by tushar-singhal** [comment]
`@graphql-codegen/cli` also needs some dependencies upgrade to support graphQL 16. 
```
"@graphql-codegen/cli > @graphql-codegen/core@2.3.0" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-codegen/plugin-helpers@2.3.0" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/apollo-engine-loader@7.0.5" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/code-file-loader@7.0.7" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/git-loader@7.0.6" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/github-loader@7.0.5" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/graphql-file-loader@7.0.6" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/json-file-loader@7.1.3" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/prisma-loader@7.0.6" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/url-loader@7.0.12" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/code-file-loader > @graphql-tools/graphql-tag-pluck@7.0.5" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/graphql-file-loader > @graphql-tools/import@6.3.0" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/prisma-loader > graphql-request@3.4.0" has incorrect peer dependency "graphql@14.x || 15.x".
warning "@graphql-codegen/cli > @graphql-tools/url-loader > @graphql-tools/delegate@8.1.1" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/url-loader > @graphql-tools/wrap@8.0.13" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@graphql-codegen/cli > @graphql-tools/url-loader > @n1ru4l/graphql-live-query@0.7.1" has incorrect peer dependency "graphql@^15.4.0".
warning "@graphql-codegen/cli > @graphql-tools/url-loader > graphql-ws@5.3.0" has incorrect peer dependency "graphql@>=0.11 <=15".
warning "@graphql-codegen/cli > @graphql-tools/url-loader > @graphql-tools/delegate > @graphql-tools/batch-execute@8.0.5" has incorrect peer dependency "graphql@^14.0.0 || ^15.0.0".
```

**Comment by ardatan** [comment]
Thanks for all of your reports. We are aware of it and we will take care of all the packages one by one. Packages don't need to be reported individually.

**Comment by setchy** [comment]
Related #7109
