### ISSUE TITLE
[typescript-react-query] Remove graphql-tag from peerDependencies

### ISSUE THREAD

**Issue by richardkall** [dotansimha/graphql-code-generator#7006]
**Describe the bug**
I get the following warning when running `yarn add -D @graphql-codegen/typescript-react-query`:

```
@graphql-codegen/typescript-react-query@3.1.1" has unmet peer dependency "graphql-tag@^2.0.0"
```

However, I'm not using `graphql-tag` since it's working perfectly fine with just strings. I see no reference to `graphql-tag` in the plugin source, so it seems like an unnecessary peerDependency.

**To Reproduce**
Run `yarn add -D @graphql-codegen/typescript-react-query`.

**Expected behavior**
No warning when installing the package without `graphql-tag`.

**Comment by tvvignesh** [comment]
PR for this here: https://github.com/dotansimha/graphql-code-generator/pull/7301

**Comment by tvvignesh** [comment]
PR merged. Closing this issue. Thanks 🙂
