### ISSUE TITLE
Remote .graphqls files are treated as json

### ISSUE THREAD

**Issue by IanVS** [dotansimha/graphql-code-generator#7026]
**Describe the bug**
My backend exposes a `/schema.graphqls` file.  Pointing to that file locally on disk works fine, but if I try to point to the url hosting it, I get an error:

```
Failed to load schema from http://localhost:9001/schema.graphqls:

        invalid json response body at http://localhost:9001/schema.graphqls reason: Unexpected token y in JSON at position 1
```

Renaming the file to `schema.graphql` works as expected. 

**To Reproduce**
Unfortunately I can't open a reproduction sandbox, since this requires an api server to fetch against.  

**Expected behavior**

**Environment:**

- OS: macos
- @graphql-codegen/cli@2.2.1
- NodeJS: 16

**Additional context**
I found https://github.com/dotansimha/graphql-code-generator/issues/811, which seemingly is why the local file works, but I guess fetching remote files goes down a different branch that is still not supported.

**Comment by tvvignesh** [comment]
That's cause introspection is run on the URL you specify and since introspection cannot be run on a GraphQL file, it probably throws such error.

@dotansimha Do we want to support remote GraphQL files?

**Comment by ardatan** [comment]
We are actually treating URLs ending with `.graphql` as GraphQL SDL;
https://github.com/ardatan/graphql-tools/blob/master/packages/loaders/url/src/index.ts#L616
This needs to support `.graphqls` as well.

**Comment by tvvignesh** [comment]
@ardatan Sent a PR for the same here: https://github.com/ardatan/graphql-tools/pull/4002
