### ISSUE TITLE
How to generate multi files

### ISSUE THREAD

**Issue by bsr203** [dotansimha/graphql-code-generator#703]
The doc say

```

-o,--out | String | Path for output file/directory. When using single-file generator specify filename, and when using multiple-files generator specify a directory
```
I am running it as 
```
    "gen:gql-apollo": "gql-gen --schema ./src/graphql/schema.json --template graphql-codegen-typescript-react-apollo-template --out .tmp/ ./src/graphql/*",
```
where `.tmp` is an existing directory. I always get a single file instead of multi as expected.

Also, I checked the dev examples [here](https://github.com/dotansimha/graphql-code-generator/blob/master/dev-test/generate-all.sh)

I think it uses a different template `graphql-codegen-typescript-template-multiple`
```
node packages/graphql-codegen-cli/dist/cli.js --template graphql-codegen-typescript-template-multiple --schema ./dev-test/githunt/schema.json --out ./dev-test/githunt/ts-multiple/ "./dev-test/githunt/**/*.graphql"
````

so do we need a different template ? is it possible to create multi file for apollo component template?

**Comment by bsr203** [comment]
I guess I read it wrong. seems like we need to use `multi` generator.  Can you please list them at https://github.com/dotansimha/graphql-code-generator#available-templates

**Comment by dotansimha** [comment]
You can take a look at this template: 
https://github.com/dotansimha/graphql-code-generator/tree/master/packages/templates/introspection

It written as a standalone package, that does not have any dependencies. 
The `customOutputProcessor` is the following interface, which you function should implement:
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/types.ts#L307-L311
