### ISSUE TITLE
TypeScript error with @graphql-codegen/typescript@2.4.0

### ISSUE THREAD

**Issue by kryops** [dotansimha/graphql-code-generator#7031]
After upgrading to `@graphql-codegen/typescript` 2.4.0, the following TypeScript error is thrown in my project:

```
node_modules/@graphql-codegen/typescript/visitor.d.ts:35:5 - error TS2416: Property 'ListType' in type 'TsVisitor<TRawConfig, TParsedConfig>' is not assignable to the same property in base type 'BaseTypesVisitor<TRawConfig, TParsedConfig>'.
  Type '(node: ListTypeNode, key: any, parent: any, path: any, ancestors: any) => string' is not assignable to type '(node: ListTypeNode) => string'.

35     ListType(node: ListTypeNode, key: any, parent: any, path: any, ancestors: any): string;
       ~~~~~~~~
```

We use the following dependencies:

```
"@graphql-codegen/core": "^2.1.8",
"@graphql-codegen/typescript": "^2.1.8",
"@graphql-codegen/typescript-operations": "^2.1.8",
```

TypeScript version is 4.2.4.

I think `@graphql-codegen/visitor-plugin-common` was missed in yesterday's release (and maybe some other packages were as well?) because it was changed as part of https://github.com/dotansimha/graphql-code-generator/commit/4c5c84c1b8d2e468a2277a7674513b99ade2a32d, but not included in the release.

Could you have a look into it?
Thanks a lot!

**Comment by n1ru4l** [comment]
You are right, we messed up the publishing! I created https://github.com/dotansimha/graphql-code-generator/pull/7045, will merge and publish shortly!

**Comment by kryops** [comment]
That fixed it for me, thanks! ☺️
