### ISSUE TITLE
Use override in typescript generation

### ISSUE THREAD

**Issue by DaSchTour** [dotansimha/graphql-code-generator#7038]
**Is your feature request related to a problem? Please describe.**

TypeScript 4.3 added a new feature to explicitly mark class override. It can be enabled with the [noImplicitOverride](https://www.typescriptlang.org/tsconfig#noImplicitOverride) compiler option.

When enabling this option on a project with generated angular classes the compilation fails. 

**Describe the solution you'd like**
Detect version of typescript or add an option to use override in code generation.

**Comment by GabrielGil** [comment]
I was about to open an identical issue :)

**Comment by qortex** [comment]
+1

**Comment by qortex** [comment]
PR submitted

**Comment by RyannGalea** [comment]
Has this been implemented just yet?  Using the latest alpha with no luck.

**Comment by GabrielGil** [comment]
Not really. The pull request is still open.

**Comment by GabrielGil** [comment]
Not really @RyannGalea. The pull request is still open.

**Comment by grenobnik** [comment]
Why is it still open? PR has been merged on Feb 14 and there is an option in config file to include `addExplicitOverride: true` that allows us to activate `"noImplicitOverride": true` in tsconfig.  ;)

**Comment by Urigo** [comment]
thank you @grenobnik , closing
