### ISSUE TITLE
Cannot find name 'query', 'Document' does not exist in type 'Query<Query, Variables>'. [react-apollo]

### ISSUE THREAD

**Issue by webberwang** [dotansimha/graphql-code-generator#704]
I posted this bug as a comment in this thread as well https://github.com/dotansimha/graphql-code-generator/issues/659. I can delete either if it's a duplicate.

Using `graphql-codegen-typescript-react-apollo-template`, the generated typescript file has no errors, except for 

```typescript
  export class Component extends React.Component<
    Partial<ReactApollo.QueryProps<Query, Variables>>
  > {
    render() {
      return (
        <ReactApollo.Query<Query, Variables>
          query={Document}
          {...this['props'] as any}
        />
      )
    }
  }
```
The compiled file has `Cannot find name 'query'` & `Document' does not exist in type 'Query<Query, Variables>` errors.

![react-apollo-services_ts_ _uib-tdd](https://user-images.githubusercontent.com/26264925/47069722-81f5a000-d1a4-11e8-8ab7-e2052de52ce0.png)

Here is the VSCode popup errors https://gyazo.com/984b6c728fb8f5a4ff937699ac9c4b5f.

**Expected behavior**
The generated shouldn't have TS errors, even though the types seem to match up.

**Schema/Documents**
The schema doesn't seem to be the issue

**Environment:**
 - OS: macOS 10.13.6
 - Codegen: 0.13.0-alpha.c5ee0f70
 - Node: V10.0.0

**Comment by ardatan** [comment]
What is the extension of the generated file, because it is supposed to be tsx not ts.

**Comment by webberwang** [comment]
Oh man rookie mistake, thanks for that quick fix! 

Hopefully this helps other people in the future if they make the same error.
