### ISSUE TITLE
404 on specific docs

### ISSUE THREAD

**Issue by hyusetiawan** [dotansimha/graphql-code-generator#7086]
not a bug on the graphql code generator itself, here:
https://www.graphql-code-generator.com/docs/presets/near-operation-file

**Comment by ardatan** [comment]
We recently deployed our new website and plugins and presets are now under Plugin Hub;
https://www.graphql-code-generator.com/plugins/near-operation-file-preset

cc @dotansimha @B2o5T Maybe we can keep the old linking. What do you think?

**Comment by ardatan** [comment]
Ok this commit should fix it once it's deployed.
https://github.com/dotansimha/graphql-code-generator/commit/082bb742f19abc9960653646b2bea4f7ae9f804c

**Comment by ardatan** [comment]
It is now working! Thanks for the report!

**Comment by B2o5T** [comment]
@ardatan sure, we must keep redirects to old links, thanks
