### ISSUE TITLE
Introspection Template types don't match IntrospectionSchema

### ISSUE THREAD

**Issue by webberwang** [dotansimha/graphql-code-generator#710]
I'm using

``` json
"graphql-code-generator": "^0.12.6",
"graphql-codegen-introspection-template": "^0.12.6"
```
to generate a JSON schema, but the types don't match up. This is for using with Apollo Client on the front end. 

A picture is worth a thousand words:

![introspectionquery_d_ts_ _uib-tdd](https://user-images.githubusercontent.com/26264925/47189075-aad67c00-d2ef-11e8-9165-628412a9cf3f.png)

**Comment by dotansimha** [comment]
@webberwang thank you for reporting it. Which version of `graphql` and `@types/graphql` do you use?

**Comment by kamilkisiela** [comment]
I don't think it's an issue with the GraphQL Code Generator. We use a query that is provided by the `graphql` package and that's the output, every tool does it in the same way. It's a mismatch between what `graphql` gives and what `@types/graphql` expects.

**Comment by webberwang** [comment]
@dotansimha 

```"graphql": "^14.0.2",
"@types/graphql": "^14.0.0",
```

**Comment by darkbasic** [comment]
I'm closing, if you still experience this issue feel free to reopen.
