### ISSUE TITLE
incorrect output on a mixed usage of InlineFragment and FragmentSpread

### ISSUE THREAD

**Issue by frantic1048** [dotansimha/graphql-code-generator#711]
**Describe the bug**
When using both InlineFragment and FragmentSpread on a union, `graphql-codegen-typescript-template` generates incorrect output, causing a syntax error.

> This bug is found when I'm trying to fix #700   Σ(ﾟ∀ﾟﾉ)ﾉ﻿

**To Reproduce**

*schema*:

```gql
# schema.graphql

type Photo {
  height: Int!
  width: Int!
}

type Sport {
  name: String!
}

union Extra = Photo | Sport

type Person {
  extra: Extra
}

type Query {
  person: Person
}
```

*document*:

```gql
# document.graphql

fragment PhotoFragment on Photo {
  width
}

query search {
  person {
    extra {
      ...PhotoFragment
      ... on Sport {
        name
      }
    }
  }
}

```

*Run command*: `gql-gen --template graphql-codegen-typescript-template --schema schema.graphql document.graphql --out schema.ts`

**Expected behavior**

In generated `schema.ts`, the type of field `extra` is:

```ts
// ...
  export type Extra = PhotoFragment.FragmentSportInlineFragment;
// ...
```
The two type of a union is just joined together without separator(`|`) Σ(ﾟДﾟ||)

**Environment:**

 - OS: Arch Linux (latest)
 - Codegen: 0.12.6
 - Node: 10.11.0
 - graphql: 14.0.2

**Additional context**

This usage is not very common, anyway, it should generate correct typing.

The reason could be the list of InlineFragments and FragmentSpreads are generated separately, and there is lacking some logic to handle this case.

**BTW**:
~~I use Arch~~

A suggestion, shall we write handlebars template with proper indent and line-breaking, and let prettier do the dirty work for generated code? Manipulating style of generated code in the template is so hard and makes the template difficult to read and edit. (e.g. to find the correct pair of a `#each` command).

In my case, I always put generated code go through prettier with the current project's config to follow current project's style.

Thanks for your hard work on this project :)

**Comment by dotansimha** [comment]
fixed in 0.13.0. @frantic1048
