### ISSUE TITLE
Suggestion: Use Pick<T, K> to generate query types

### ISSUE THREAD

**Issue by fetis** [dotansimha/graphql-code-generator#713]
**Is your feature request related to a problem? Please describe.**
Currently, we just have a copy of original type for a query

**Describe the solution you'd like**
I think a more clear approach would be to use Pick<T, K> operator to make a connection to the original type. 

So this would be like this
```
export interface TypeA {
  id: string;
  name: string;
  age: number;
}

export namespace MyQuery {
  export type TypeA = Pick<TypeA, 'id' | 'name'>
}
```

See it's in action here https://medium.com/@curtistatewilkinson/typescript-2-1-and-the-power-of-pick-ff433f1e6fb

**Comment by ardatan** [comment]
Thank you for your suggestion!
That looks a good idea, but how about nested types.
‘’’gql
query SomeQuery {
   foo
   bar
   something {
               x
                y
    }
}
‘’’

**Comment by fetis** [comment]
@ardatan I think it should work the same `Pick<SomeQuery, 'foo', 'something'>`

**Comment by fetis** [comment]
[here's the example with nested complex subtype](http://www.typescriptlang.org/play/#src=export%20interface%20TypeA%20%7B%0D%0A%20%20id%3A%20string%3B%0D%0A%20%20name%3A%20string%3B%0D%0A%20%20age%3A%20number%3B%0D%0A%20%20complex%3A%20%7B%0D%0A%20%20%20%20%20%20id%3A%20string%3B%0D%0A%20%20%20%20%20%20name%3A%20string%3B%20%20%20%20%20%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20_TypeA%20%3D%20TypeA%3B%0D%0A%0D%0Atype%20SubtypeA%20%3D%20Pick%20<TypeA%2C%20'id'%20%7C%20'name'>%20%26%20%7B%0D%0A%20%20complex%3A%20Pick<TypeA%5B'complex'%5D%2C%20'id'>%20%20%0D%0A%7D%3B%0D%0A%0D%0Aconst%20a%3A%20SubtypeA%20%3D%20%7B%0D%0A%20%20%20%20id%3A%20'1'%2C%0D%0A%20%20%20%20name%3A%20''%2C%0D%0A%20%20%20%20complex%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20id%3A%20''%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aexport%20namespace%20Query%20%7B%0D%0A%20%20export%20type%20TypeA%20%3D%20Pick%20<_TypeA%2C%20'id'%20%7C%20'name'>%20%26%20%7B%0D%0A%20%20complex%3A%20Pick<_TypeA%5B'complex'%5D%2C%20'id'>%20%20%0D%0A%7D%3B%20%0D%0A%7D%0D%0A) in Typescript playground

the problem is that you can't reference the outer type in namespace (or I don't know how). So I've introduced alias `_TypeA` for server type to bypass this.

**Comment by ardatan** [comment]
Oh I just understand what you mean! Yes, this will reduce the code size and everything more consistent! I like that idea.
@dotansimha What do you think? If it is ok, I can work on it!

**Comment by dotansimha** [comment]
It's actually looks good and more clean. I think we might need a lot of effort to support this use case, or I'm missing something? @ardatan @fetis

**Comment by dotansimha** [comment]
It's actually looks good and more clean. I think we might need a lot of effort to support this use case, or I'm missing something? @ardatan @fetis

**Comment by dotansimha** [comment]
It's actually looks good and more clean. I think we might need a lot of effort to support this use case, or I'm missing something? @ardatan @fetis

**Comment by fetis** [comment]
@dotansimha hi, sorry for a long reply.
I don't think it should be more efforts than now. Instead of generating a new type every time you'll use a Pick statement on existing server type. There might some edge cases of course, but I can't forsee it now.

**Comment by dotansimha** [comment]
@fetis There are other things to consider, such as fragment, aliasing and more.
I'm doing some research now to see if how that effects the template.
In general, I agree that this syntax is way better than creating inner types.

**Comment by dotansimha** [comment]
@fetis we implemented this concept in the new flow plugins: https://github.com/dotansimha/graphql-code-generator/pull/917 
Maybe later we'll refactor the typescript packages to use the same concept :)

**Comment by swcarlosrj** [comment]
Picking this, @dotansimha where could I ping you up, have some questions about how to approach it!

**Comment by swcarlosrj** [comment]
@dotansimha just checking this out! Thank so much for all this info, I really appreciate it! I'll give a look tomorrow, I'm pretty sure that it'll help a lot in order to design an efficient solution covering all the use cases!

**Comment by NickClark** [comment]
This is a huge improvement! Can't wait to see it come through! Does this also replace `Maybe` types with optionals? In code bases like ours, `nulls` are a bad practice.

**Comment by NickClark** [comment]
Also, it might be nice to consider exposing fragment pick types per #1312

**Comment by dotansimha** [comment]
WIP here: https://github.com/dotansimha/graphql-code-generator/pull/1353 :)

**Comment by NickClark** [comment]
@dotansimha Thanks! In the Typescript world, nulls are typically bad practice... but GraphQL libs tend to return nulls, so maybe there's nothing I can/should do about it. Unless there was a way for libraries like Apollo to do the conversion for us. Anyways, thanks again! Really excited to see this coming!

**Comment by fetis** [comment]
> In the Typescript world, nulls are typically bad practice... 
@NickBolles do you have a proof on that? In connection with GraphQL, I don't think we can get rid of `null`

**Comment by NickClark** [comment]
@fetis I assume you meant me. Yes. A lot of TS even non-TS projects shy away from `null`. The Typescript project itself doesn't use `null` ([TS guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined)) and even Crockford doesn't use `null` anymore ([video](https://www.youtube.com/watch?v=PSGEjv3Tqo0&feature=youtu.be&t=9m21s)) That being said... after considering it further... I don't think we can get rid of null in regard to GraphQL,

**Comment by dotansimha** [comment]
Thank you @fetis for a great idea. It took some time, but we are finally there. 
All plugins are now (1.0.0) using `Pick` - the generated code is much simpler and it resolved so many issues.

**Comment by epeli** [comment]
Just trying out the new 1.0.0 release and I have now hard time figuring out how to access deeper field types.

Example. This type is now generated for my GraphQL query:

```ts
export type ApartmentsQuery = { __typename?: "RootQuery" } & {
    apartments: Maybe<
        { __typename?: "RootQueryToApartmentConnection" } & {
            edges: Maybe<
                Array<
                    Maybe<
                        {
                            __typename?: "RootQueryToApartmentConnectionEdge";
                        } & {
                            node: Maybe<
                                { __typename?: "Apartment" } & Pick<
                                    Apartment,
                                    "id" | "title"
                                > & {
                                        buildingTypes: Maybe<
                                            {
                                                __typename?: "ApartmentToBuildingTypeConnection";
                                            } & {
                                                nodes: Maybe<
                                                    Array<
                                                        Maybe<
                                                            {
                                                                __typename?: "BuildingType";
                                                            } & Pick<
                                                                BuildingType,
                                                                "name" | "slug"
                                                            >
                                                        >
                                                    >
                                                >;
                                            }
                                        >;
                                    }
                            >;
                        }
                    >
                >
            >;
        }
    >;
};
```

I'm looping through the `data.apartments.edges` array and inside it I want to pass `node.buildingTypes` to an external function. In pre 1.0 versions I could just import the `buildingTypes` type for the external function argument types but now that all types are inlined like this. How should I go about it?

**Comment by dotansimha** [comment]
There are 2 options:
1. Use `MyType['fieldA']['fieldB']` until you reach your type. You can also create aliases by using `MyInnerType = MyType['fieldA']['fieldB']`. 
2. Use GraphQL fragments. This way the types you need to use internally will point to your fragments, and you can use the generated fragment `type`. 

We know it's not ideal, but eliminating `namespace`s was very important in order to make the output optimized, and using a single `type` is important because it makes sure that there are no name conflicts and mis-matches in the generated output. 

@epeli

**Comment by epeli** [comment]
1. Doesn't seem to work with intersections?

![image](https://user-images.githubusercontent.com/225712/54697654-99133200-4b36-11e9-9323-5fc65804129c.png)

2. Fragments help a bit it's quite awkward still. You need handle bunch of Maybes and __typenames...

**Comment by epeli** [comment]
It seems that I must do this to be able to reach the type:

```ts
type ArrayType<T> = T extends Array<infer V> ? V : never;

type BuildingTypes = NonNullable<
    NonNullable<
        ArrayType<
            NonNullable<NonNullable<ApartmentsQuery["apartments"]>["edges"]>
        >
    >["node"]
>["buildingTypes"];
```

**Comment by dotansimha** [comment]
@epeli I didn't understand if that's an issue. If so, can you please open a new issue with examples?

**Comment by epeli** [comment]
Will do
