### ISSUE TITLE
Add possibility to use constants for plugin enum-array

### ISSUE THREAD

**Issue by b-eyselein** [dotansimha/graphql-code-generator#7169]
I tried adding the new plugin `enum-array` for my project with React (with Typescript) but the compiler won't let me assign string values as enum values, e. g.

```graphql
enum MyEnum {
  A
  B
}
```

is generated to

```typescript
export enum MyEnum {
  A = 'A',
  B = 'B'
}

export const MY_ENUM: MyEnum[] = ['A', 'B'];
```

I assume this may have to do with React using the `strict` mode in `tsconfig.json`.

What I need is the possibility to directly reference the enum values like this:

```typescript
export const MY_ENUM: MyEnum[] = [MyEnum.A, MyEnum.B];
```

I think we could add an optional config option `useConsts?: boolean` to the plugin that enables this behaviour when set to true and else uses the current behaviour of generating string values.

I have prepared a commit that implements and adds (successful) unit tests for this behaviour: b-eyselein/graphql-code-generator@32c7a5c7fcc6a0bfe6d770b302893fd4c639b661

**Comment by fredericoo** [comment]
I second this

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator-community/pull/77
