### ISSUE TITLE
404 Not found error

### ISSUE THREAD

**Issue by Jay-flow** [dotansimha/graphql-code-generator#7174]
A 404 not found error occurs in the document below.
https://www.graphql-code-generator.com/docs/getting-started/config-reference/codegen-config

![image](https://user-images.githubusercontent.com/29420674/145362523-51564262-08ab-4181-b153-e4cc4f5a97b8.png)

**Comment by dotansimha** [comment]
The updated link is in: https://www.graphql-code-generator.com/docs/config-reference/codegen-config 

I'll add a redirect to support old links, thanks @Jay-flow !

**Comment by dotansimha** [comment]
Fixed 🎉
