### ISSUE TITLE
Duplicate queries/mutations is not checked

### ISSUE THREAD

**Issue by crissi** [dotansimha/graphql-code-generator#720]
**Is your feature request related to a problem? Please describe.**
The problem is that I can mistakenly give two queries the same name and the generated file will therefore have duplicate classes

**Describe the solution you'd like**
Check if all queries and mutations names are unique and fail with an error message.

**Additional context**
![image](https://user-images.githubusercontent.com/3076578/47372138-6ed55980-d6e9-11e8-936f-9395f91ff49e.png)

I might be able to help with a solution.

**Comment by dotansimha** [comment]
Fixed in 0.14.2 🎉
