### ISSUE TITLE
Plugin system instead of multiple templates

### ISSUE THREAD

**Issue by kamilkisiela** [dotansimha/graphql-code-generator#725]
_more soon_

**Comment by dotansimha** [comment]
YES! 
You mean something like that? use typescript template, add "resolvers" plugins (which is just another template), add "react" plugin and output it to the same file.

**Comment by kamilkisiela** [comment]
Yes, Codegen gets types, interfaces and stuff and you decide what to output.

Typescript gets a type and outputs a TS interface with some naming convention.
Apollo Angular knows that is using typescript and `import { typeToName } from 'graphql-codegen-typescript-plugin';`

**Comment by kamilkisiela** [comment]
So they could interact and we no longer have to have one template

**Comment by kamilkisiela** [comment]
I think it will make codegen waay more interesting (BUT IT IS INTERESTING HUUUUUGLY NOW FOR SURE)

**Comment by kamilkisiela** [comment]
```typescript
function typeToName(type) { return pascalCase(type.name); }

class Typescript {
  visitType() { return `interface ${typeToName} { ... }`; }
}
```

You get the idea

**Comment by dotansimha** [comment]
Hmm wait, I think there are multiple things here.

When you say plugins, I'm referring to plugins adding more template to a base template (or, actually, just a list of templates you want to merge together).

The `typeToName` is something else - it means implementing the codegen as visitor pattern, and it something I want to do for a long time, but it might break some stuff, and we'll have to do a lot of refactoring to the core package and templates

**Comment by kamilkisiela** [comment]
Yes, that's why wrote _But that might be for a different issue_

For now having multiple templates seems ok but it would be super nice to use AST or something like this and not handlebars so we could share logic between packages.

**Comment by dotansimha** [comment]
Done in 0.14 🎉
