### ISSUE TITLE
rtk query integration makes unnecessary api import for fragments

### ISSUE THREAD

**Issue by hkasemir** [dotansimha/graphql-code-generator#7278]
**Describe the bug**
when generating code with the rtk toolkit plugin in conjunction with `near-operation-file-preset` graphql files for fragments are generated with an attempt to inject an endpoint into the rtk api, despite fragments not being operations.

**To Reproduce**
repro here: https://github.com/hkasemir/gql-codegen-issue

in particular, the generated file for the fragment: https://github.com/hkasemir/gql-codegen-issue/blob/main/queries/user-fragment.generated.ts

it does not import the `api`, but it does try to export it with an injected endpoint, which causes compile errors.

**Expected behavior**
fragment files should not include an attempt to export the api with an injected endpoint, similarly to how the api is not imported into the generated file if the graphql file does not include operations: (https://github.com/dotansimha/graphql-code-generator/blob/c11011e7b46483909965d51e486ab41933b340e9/packages/plugins/typescript/rtk-query/src/visitor.ts#L48)

**Environment:**

- OS: 
-  "@graphql-codegen/add": "^3.1.0",
    "@graphql-codegen/cli": "^2.3.0",
    "@graphql-codegen/near-operation-file-preset": "^2.2.2",
    "@graphql-codegen/typescript": "^2.4.1",
    "@graphql-codegen/typescript-operations": "^2.2.1",
    "@graphql-codegen/typescript-rtk-query": "^2.2.1",
- NodeJS: 17.2.0

**Comment by charlypoly** [comment]
Hi @hkasemir!

Thank you for your contribution! ⚡ 

Your patch has been released in `@graphql-codegen/typescript-rtk-query@2.2.3` 📦
