### ISSUE TITLE
Fix(react-query): ensure mutationKey is always array

### ISSUE THREAD

**Issue by jonathanstanley** [dotansimha/graphql-code-generator#7281]
**Describe the bug**
React Query is requiring queryKeys and mutationKeys to always be an array.  see:
https://github.com/tannerlinsley/react-query/issues/2919

**To Reproduce**
Use with React Query v4 (currently alpha) will throw type errors.

**Expected behavior**
Use an array for the keys instead of a string.  i.e. `['mystring']` instead of `'mystring'`

**Environment:**
any

**Additional context**
v4 is currently in pre-release and will become more pressing once released.  This is a backwards-compatible upgrade... arrays have always been an acceptable key.

**Comment by charlypoly** [comment]
@jonathanstanley Thank you for your contribution, it has been released in `@graphql-codegen/typescript-react-query@3.4.0` 📦
