### ISSUE TITLE
Support configuring behavior of optimizeOperations in typescript-operations

### ISSUE THREAD

**Issue by asmundg** [dotansimha/graphql-code-generator#7285]
**Is your feature request related to a problem? Please describe.**

We want to both produce flattened documents _and_ fragment interfaces from a set of colocated graphql files. In the default mode, typescript-operations will call relay-operation-optimizer, which will drop fragments after flattening them into the documents. This means we lose the fragment-specific types that we'd like to use as React component interfaces.

**Describe the solution you'd like**

There is already an affordance in visitor-plugin-common to forward the includeFragments option to relay-operation-optimizer, which will cause the fragments to be retained while still producing the same compact documents. We'd like this behavior to be configurable.

**Describe alternatives you've considered**

Including fragments could also be made the default behavior, as extra type information doesn't have any runtime effect.

**Additional context**

**Comment by charlypoly** [comment]
Hi @asmundg,

Thank you for your contribution! ⚡ 

Your change is now available in `@graphql-codegen/typescript-operations@2.3.0`
