### ISSUE TITLE
near-operation-file preset depends on relay-compiler@12, which doesn't support GraphQL 16

### ISSUE THREAD

**Issue by yura3d** [dotansimha/graphql-code-generator#7298]
Hi.

The latest releases of GraphQL code generator packages added GraphQL 16 support. But `near-operation-file` preset depends on `relay-compiler@12`, which doesn't support GraphQL 16:
```
@graphql-codegen/near-operation-file-preset@2.2.3 > @graphql-codegen/visitor-plugin-common@2.5.2 > @graphql-tools/relay-operation-optimizer@6.4.1 > relay-compiler@12.0.0
```
According to https://github.com/facebook/relay/issues/3705 and https://github.com/ardatan/graphql-tools/issues/4070 I see, that GraphQL 16 support for `near-operation-file` preset is a complex feature, since the new `relay-compiler@13` migrated to Rust and `@graphql-tools/relay-operation-optimizer` can't work with it like it did before.

Are there any plans to add GraphQL 16 support for `near-operation-file` preset in the nearest future?

**Comment by aaronadamsCA** [comment]
I am curious why this preset [says it's compatible with GraphQL 16](https://github.com/dotansimha/graphql-code-generator/blob/dfd798daac40cd20361641ef7bc342a23164b894/packages/presets/near-operation-file/package.json#L28) despite the underlying dependency chain not supporting GraphQL 16.

I didn't see any specific problems after the upgrade, but I am a bit wary of using `relay-compiler@12` with `graphql@16` when its own devs say it's not compatible.

**Comment by Pagebakers** [comment]
Any updates on this?

**Comment by ardatan** [comment]
It is compatible with GraphQL v16 and it is just peer dependency definition. You can ignore dependency warnings until we figure that out.

**Comment by Urigo** [comment]
this should have been fixed with the latest version of graphql-tools: https://github.com/ardatan/graphql-tools/discussions/4070#discussioncomment-2915012

**Comment by yura3d** [comment]
@Urigo Yes, now there are no warnings about peer dependencies.
