### ISSUE TITLE
Deprecate `PROJECT` generation

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#731]
`PROJECT` generation was an experiment we did, that intended to generate an existing project directly. 
It has a very messy API, and has a lot of bugs. Also, now that everyone can write his own template (with our without Handlebars), it makes it much easier to do it.

**Comment by robck** [comment]
The --project option works well for me so far. Is having an internal/nested package the only other option?

**Comment by dotansimha** [comment]
@robck we decided to deprecate it in favor of custom templates (which already available now). IT should be more powerful, and easier to customize.

**Comment by dotansimha** [comment]
Done in 0.14 🎉
