### ISSUE TITLE
Make getKey() available for infinite queries

### ISSUE THREAD

**Issue by krumplisbalhe** [dotansimha/graphql-code-generator#7365]
**Is your feature request related to a problem? Please describe.**

We use the getKey function in our app to invalidate only the necessary React Queries. Would it be possible to make the function available for infinite query hooks?

**Describe the solution you'd like**

reactQueryClient.invalidateQueries(useSomeInfiniteQuery.getKey(filters))

**Comment by erik-beus** [comment]
@krumplisbalhe I think you can close this issue now.
The `.getKey` function is now available on infinite queries in version [3.3.2 of @graphql-codegen/typescript-react-query](https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Ftypescript-react-query%403.3.2)
