### ISSUE TITLE
typescript-vue-apollo lazy operations

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [dotansimha/graphql-code-generator#7374]
**Is your feature request related to a problem? Please describe.**
Currently, there is only a generation with `useQuery` but sometimes you maybe want to have also `useLazyQuery`

**Describe the solution you'd like**
Add an additional generation for a lazy variant

**Comment by stephane303** [comment]
Duplicate https://github.com/dotansimha/graphql-code-generator/pull/7340
