### ISSUE TITLE
"typescript-operations@2.2.1" + "avoidOptionals: true" generating "| undefined"

### ISSUE THREAD

**Issue by rjensen-r7** [dotansimha/graphql-code-generator#7401]
**Describe the bug**
Starting in `typescript-operations@2.2.1`, `avoidOptionals: true` is appending `| undefined`; The `| undefined` should not be present with `avoidOptionals: true`.

This was not happening in `typescript-operations@2.2.0`. In 2.2.0, the package correctly generates `x | null`.

**To Reproduce**

**Live example**
https://codesandbox.io/s/icy-browser-u7p8q?file=/codegen.yml:180-201

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}

```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    config:
      avoidOptionals: true
    plugins:
      - typescript
      - typescript-operations
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
`Maybe` types generate `x | null`, not `x | null | undefined`.
**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by simPod** [comment]
`avoidOptionals` IIRC prevents generating `?` in `field?: ...`. But something has changed and `| undefined` is being added now. Did not find a way to disable it yet.

**Comment by simPod** [comment]
The thing happened here https://github.com/dotansimha/graphql-code-generator/pull/6951

**Comment by simPod** [comment]
Ok I just found myself again already solving this :/ https://github.com/dotansimha/graphql-code-generator/pull/7104

**Comment by gilgardosh** [comment]
@simPod I updated #7104, and it'll be merged later today.
meanwhile, you can use the [alphas](https://github.com/dotansimha/graphql-code-generator/pull/7104#issuecomment-981053129)

**Comment by simPod** [comment]
Thank you for pushing this forward!

> meanwhile, you can use the alphas

I guess few more hours of waiting won't kill me now 😜

**Comment by rjensen-r7** [comment]
Verified that this is fixed, thank you
