### ISSUE TITLE
Move `resolvers` to a separate template

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#742]
At the moment, the `resolvers` part of the `typescript` template is generated by default (and might be irrelevant for developers who use it for client side). 
I think we can move it to a separate template that extends `typescript` template.

**Comment by ardatan** [comment]
And this will be great for client-side apollo-angular and react-apollo templates!

**Comment by dotansimha** [comment]
@moonray available in 0.13.0.
