### ISSUE TITLE
[docs]404 Not found

### ISSUE THREAD

**Issue by soudai-s** [dotansimha/graphql-code-generator#7431]
**Describe the bug**

Hi, I found a dead link in the docs at https://www.graphql-code-generator.com/docs/config-reference/codegen-config .
<img width="1316" alt="スクリーンショット 2022-01-28 14 30 34" src="https://user-images.githubusercontent.com/4921350/151493780-c95cd9be-cd55-4cab-ac63-d60cb748b818.png">

The 404 page is at https://www.graphql-code-generator.com/docs/config-reference/docs/custom-codegen.
Thanks.

**Comment by charlypoly** [comment]
Thank you for your fix @soudai-s 🤓
