### ISSUE TITLE
add typescript-validation-schema plugin to website

### ISSUE THREAD

**Issue by Code-Hex** [dotansimha/graphql-code-generator#7437]
I’ve been developing [graphql-codegen-typescript-validation-schema](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema) because there was not form validation schema generation plugins I wanted.

There were a few unofficial entities that existed.

- https://github.com/kazuyaseki/graphql-codegen-yup-schema
- https://github.com/tinezmatias/codegen-graphql-yup
- https://github.com/withshepherd/graphql-codegen-zod

However

- Not supported TypeScript
  - kazuyaseki/graphql-codegen-yup-schema
- The only ones worked for the directive (validate directive) assumed by the plugin.
  - Everyone has their own validation directives, and they should want to use them.

**Comment by charlypoly** [comment]
@Code-Hex it is deployed! 🚢
