### ISSUE TITLE
typescript-urql-graphcache plugin: function argument types always have optional fields

### ISSUE THREAD

**Issue by tobz1000** [dotansimha/graphql-code-generator#7447]
**Describe the bug**
All generated object types for graphcache handler function arguments have their field types converted to `T | undefined`. This means I have to perform a lot of redundant checks (which is infeasible for a large number of fields) or I must type-assert everywhere.

**To Reproduce**

1. Generate the `GraphCacheConfig` type using the typescript-urql-graphcache plugin
2. Use this type parameter on your cacheExchange constructor
3. Try to e.g. define an update function using a non-nullable object return value with non-nullable fields
4. The object's type annotation will declare all of its fields as optional.

The culprit is the `WithTypename` type definition, which makes all fields of the input type optional.

Reproduction with example of an issue this causes: https://codesandbox.io/s/amazing-field-zlkgp?file=/main.ts

![image](https://user-images.githubusercontent.com/1471978/151914351-b5e2a267-71b0-4727-ae02-32a8285ead5e.png)

**Expected behavior**
Objects defined in the generated typedefs have the exact same field types as specified in the gql schema.

**Comment by charlypoly** [comment]
Hi @tobz1000,

Indeed, it seems that the `WithTypename` type definition is incorrect, it should keep the given `T` type as it, not make all its properties optional.

Would you have time to submit a PR to fix this and test it in your application? 👀

**Comment by AndysonDK** [comment]
Hey! I have the same problem. Here is some extra information for debugging purposes:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/28491857/157971042-d3dcfef3-48c2-4b4c-bdf1-2ba8f05dd2eb.png">
The code is located in this file:
https://github.com/AndysonDK/syncbase/blob/626fa9aaf5e0feb7119b21609c2f788523304852/packages/web/src/graphql/client.ts

**Comment by AndysonDK** [comment]
> Hi @tobz1000,
> 
> Indeed, it seems that the `WithTypename` type definition is incorrect, it should keep the given `T` type as it, not make all its properties optional.
> 
> Would you have time to submit a PR to fix this and test it in your application? 👀

Just a heads up I've submitted [PR](https://github.com/dotansimha/graphql-code-generator/pull/7681)

**Comment by charlypoly** [comment]
Thank you for your contribution @AndysonDK!

The fix has been released in `@graphql-codegen/typescript-urql@3.5.7` 📦
