### ISSUE TITLE
[typescript-operations] add the way to specify tsconfig.json, so operations considering flags like `exactOptionalPropertyTypes`, and for optional values adds ` | undefined`

### ISSUE THREAD

**Issue by JustFly1984** [dotansimha/graphql-code-generator#7448]
We have multiple react projects where we have set `exactOptionalPropertyTypes: true` in `tsconfig.json`. 

Modifying Maybe type does not solve an issue completely, cos `__typename?: "..."` is not wrapped in Maybe. 

It could be great if code generator could track `tsconfig` for `exactOptionalPropertyTypes` flag, and did add `undefined` to optionals automatically, but some flag for `typescript-operations` would solve an issue for me.

Currently I have to update all optional values by adding ` | undefined` ay the end of of each optional value, to satisfy this flag.

**Comment by charlypoly** [comment]
Hi @JustFly1984,

Let's keep this subject in the issue https://github.com/dotansimha/graphql-code-generator/issues/7451 that provides more context.
