### ISSUE TITLE
[typescript-operations] export interfaces instead of types by default or with flag.

### ISSUE THREAD

**Issue by JustFly1984** [dotansimha/graphql-code-generator#7449]
Typescript interfaces are more performant. We have huge schemas with tens of thousands lines of types generated, and editors start lagging. Just renaming types to interfaces manually reduces lags.

Please provide a `typescript-operations` flag to export interfaces instead of types.

**Comment by AradAral** [comment]
I think there is such an option already. You can use `declarationKind: 'interface'`.
See [docs](https://www.graphql-code-generator.com/plugins/typescript-operations#:~:text=enumValues-,declarationKind,-enumPrefix)

**Comment by JustFly1984** [comment]
Thank you @AradAral !
