### ISSUE TITLE
Access the parts of the generated type

### ISSUE THREAD

**Issue by nemonemi** [dotansimha/graphql-code-generator#7471]
When I generate types, they are generated based on the queries in my application. Meaning, they might not query for the complete type data, but just a subset.

When, later on, I want to reference a part of such generated type, now I have to do some typescript gymnastics to acquire it.
Something like this:
```ts
type ArrayElement<A> = A extends readonly (infer T)[] ? T : never;
type CompaniesAssignments = Pick<GetCompaniesAssignmentsQuery, 'companiesAssignments'>;
type CompanyAssignmentCertificateTypes = Pick<
  ArrayElement<CompaniesAssignments['companiesAssignments']>,
  'certificateTypes'
>;
type CompanyAssignmentCertificateType = CompanyAssignmentCertificateTypes['certificateTypes'][number];
```

An example:
The `CertificateTypeAssignment` consists of a lot more properties than what is needed in the query that was used to generate this type.
```ts
export type GetCompaniesAssignmentsQuery = {
  __typename?: 'Query';
  companiesAssignments: Array<{
    __typename?: 'CompanyAssignment';
    company: { __typename?: 'Company'; id: string; duns?: string | null | undefined; name: string };
    certificateTypes: Array<{
      __typename?: 'CertificateTypeAssignment';
      type?: { __typename?: 'CertificateType'; id: string; title: string } | null | undefined;
      properties?:
        | Array<
            | {
                __typename: 'CertificatePropertyDate';
                date?: Date | null | undefined;
                property: { __typename?: 'Property'; id: string; name: string };
              }
            | {
                __typename: 'CertificatePropertySimple';
                value?: string | null | undefined;
                property: { __typename?: 'Property'; id: string; name: string };
              }
          >
        | null
        | undefined;
    }>;
  }>;
};
```

Here I want to reference the `certificateTypes` so that the method consuming it gets only the properties that are defined there.

**Describe the solution you'd like**

When generating types, it would be nice if you could also generate their parts as separate types.

**Comment by ardatan** [comment]
Initially codegen used to have that kind of behavior then we decided to remove it because naming was a problem(conflicts etc).
Instead you can easily use TypeScript to get that specific type;
```ts
type MyType =  GetCompaniesAssignmentsQuery['companiesAssignments'][0]['certificateTypes'][0]
```
Or you can use GraphQL Fragments so Codegen wil generate specific types for those fragments.

**Comment by nemonemi** [comment]
This looks like an elegant solution with which I'll close this ticket.
Thanks for the hints, @ardatan!

**Comment by antonvialibri1** [comment]
> Initially codegen used to have that kind of behavior then we decided to remove it because naming was a problem(conflicts etc). Instead you can easily use TypeScript to get that specific type;
> 
> ```ts
> type MyType =  GetCompaniesAssignmentsQuery['companiesAssignments'][0]['certificateTypes'][0]
> ```
> 
> Or you can use fragments so Codegen will generate specific types for those.

@ardatan, how can achieve a similar thing when documenting JSDoc parameters?

`GetCompaniesAssignmentsQuery['companiesAssignments'][0]['certificateTypes'][0]` doesn't seem to be accepted by JSDoc.
