### ISSUE TITLE
New plugin: Hasura allow list generation

### ISSUE THREAD

**Issue by BenoitRanque** [dotansimha/graphql-code-generator#7476]
Disclaimer: I work for hasura

This is a proposal for a simple plugin that generates an allow list for hasura using grapqhl-codegen.
Hasura is allows users to specify which queries should be allowed. Keeping this list in sync with the actual front end code can be tedious. There have been community requests for such a feature, see [here](https://github.com/hasura/graphql-engine/discussions/6078).

This plugin leverages graphql codegen to generate that list based on the the graphql codegen documents.
This allows users to fully automate the creation of the allow list based on the queries they have in the front end.

A PR is ready and will be created soon. Currently the plugin supports fragments, and is otherwise fairly simple.
The only complexity was ensuring fragments are included once, no matter the level of nesting within other fragments.

The name of the generated collection can be configured.
The file should be output to the metadata directory.

Currently unsure about the docs aspect, would appreciate being pointed to the right file.

**Comment by charlypoly** [comment]
Hi @BenoitRanque,

Thank you for your contribution! 🙇🏼 

Your plugin is now available under the version `@graphql-codegen/hasura-allow-list@1.0.1` 📦

**Comment by Zerebokep** [comment]
@BenoitRanque Could you please implement [role based allow lists](https://hasura.io/docs/2.0/security/allow-list/#role-based-allow-list)?
