### ISSUE TITLE
Can’t load TypeScript ESM files using `ts-node/esm`

### ISSUE THREAD

**Issue by huw** [dotansimha/graphql-code-generator#7482]
**Describe the bug**
Codegen can’t load TypeScript ESM files under any circumstances. This is because:

- `ts-node/register` can’t load TypeScript ESM files—you’re supposed to use `ts-node/esm` (this _could_ be clearer in the docs but I figured it out pretty quickly)
- Codegen can’t `require` ES Modules, which `ts-node/esm` is
- Codegen’s CLI doesn’t use `require`, because `bin.js` is compiled as a CJS module, and the transpiler is automatically converting [the raw `import()` from `config.ts`](https://github.com/dotansimha/graphql-code-generator/blob/77faafed93eb0fbc1fa39085c21e701cb56ce8e0/packages/graphql-codegen-cli/src/config.ts#L240) to a `require()` under the hood
  - I figured this one out by inspecting the raw package. Same problem as ardatan/graphql-tools#4227.

I also tried to change all the `require()`s to `import()`s locally, but then I ran into an `ERR_UNKNOWN_TYPE_EXTENSION`, which according to TypeStrong/ts-node#1062 should only happen if `ts-node/esm` hasn’t been loaded properly. So I’m kind of out of ideas on this one.

**To Reproduce**

https://codesandbox.io/s/romantic-austin-zoo29?

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

**Expected behavior**

I expect the TypeScript file to load correctly.

**Additional context**
My current workaround is to create a `schema.js` file that uses `@boost/module` to load the TypeScript file:

```js
import path from "path";
import { requireModule } from "@boost/module";

const { default: schema } = requireModule(
  path.join(process.cwd(), "./schema.ts")
);

export default schema;
```

This also _doesn’t work_ without resolving ardatan/graphql-tools#4227, so I had to patch that in the meantime.

**Comment by ardatan** [comment]
Our CLI uses CommonJS and it is not possible to load ESM from CJS. That's why it doesn't work.

**Comment by huw** [comment]
Thanks for the help on this & the other issue. I’ll close the issue since it’s essentially a duplicate of #5757 🙂
