### ISSUE TITLE
Unknown directive "connection"

### ISSUE THREAD

**Issue by benawad** [dotansimha/graphql-code-generator#749]
I'm using the @connection directive (https://www.apollographql.com/docs/react/features/pagination.html#connection-directive)

Tried generating types using graphql-codegen-typescript-react-apollo-template

Got the following error: `GraphQL Error: Unknown directive "connection".`

How should I handle this?

**Comment by dotansimha** [comment]
@benawad 
Apollo's client-side directives are [declared internally](https://github.com/apollographql/apollo-client/blob/256585b8b7cf68da0629950490761f479b171892/packages/apollo-utilities/src/storeUtils.ts#L179-L184), that means that they are not exposed to `graphql-code-generator`. 

To provide this to the codegen, you can create a file called `client-schema.graphql` with the following:
```graphql
directive @connection on FIELD
```

And then add the following to your `gql-gen` command:
```
--client-schema ./client-schema.graphql
```

**Comment by boom** [comment]
For anyone finding this post via google search as I did, the correct CLI flag for v0.13.0 is:

```
--clientSchema client-schema.graphql
```

**Comment by dotansimha** [comment]
Thanks @boom! 
And since 0.14, you can just specify it a:
```
schema: client-schema.graphql
```
