### ISSUE TITLE
Missing helper: blockComment

### ISSUE THREAD

**Issue by affanshahid** [dotansimha/graphql-code-generator#751]
**Describe the bug**
Running the following: 
```sh
gql-gen --template graphql-codegen-typescript-resolvers-template --schema ./src/schema.graphql --out ./src/resolvers-types.ts
```

I get the following error:
```sh
00:04:34.753 - error: Missing helper: "blockComment"
```

**Environment:**
 - OS: Windows 10
 - Codegen: 0.12.6
 - Node: 10.11.0

My Schema has no comments

**Comment by dotansimha** [comment]
@affanshahid, which version of the codegen do you use? and which version of the template?

**Comment by affanshahid** [comment]
I mentioned the codegen version in my post but here are the other two:
```json
    "graphql": "^14.0.2",
    "graphql-code-generator": "^0.12.6",
    "graphql-codegen-typescript-resolvers-template": "^0.13.0-alpha.34c9c8c7",
```

**Comment by dotansimha** [comment]
@affanshahid if you are using the alpha version, they must match. Install `graphql-code-generator@0.13.0-alpha.34c9c8c7` and it will work :)

**Comment by affanshahid** [comment]
Ah! ofcourse, thank you!
