### ISSUE TITLE
typescript-apollo-angular noImplicitOverride with namedClient doesn't work

### ISSUE THREAD

**Issue by TomONeill** [dotansimha/graphql-code-generator#7548]
**Describe the bug**
In `@graphql-codegen/typescript-apollo-angular@3.4.0`, `noImplicitOverride` was added. Thanks!
But when I'm using it in combination with `namedClient`, another property gets generated, without the `override` modifier which is required there.

```
  export class GetXGQLextends Apollo.Query<GetXQuery, GetXQueryVariables> {
    override document = GetXDocument;
    client = 'any'
```

**Comment by charlypoly** [comment]
Hi @TomONeill,

Thank you for your fix proposal.
In order to properly assess it, could you please provide a reproduction on Codesandbox by using our template?
➡️ https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template/tree/master/

Thank you!

**Comment by TomONeill** [comment]
Closing this issue as it was resolved with the PR mentioned above.
