### ISSUE TITLE
Remove false positive namespace identification in `parseMapper`

### ISSUE THREAD

**Issue by 9at8** [dotansimha/graphql-code-generator#7558]
**Describe the bug**
`parseMapper` incorrectly identifies `file#Type<import("foo").Bar>` mappers as containing a namespace, which leads to a bug.

**To Reproduce**

Use the `mappers` config for typescript-resolvers

3. My `codegen.yml` config file:

```yml
mappers:
  Bar: 'file#Type<import("foo").Bar>'
```

**Actual behavior**

In generated types

```ts
import { Type<import("foo") } from 'file'

// ... later when Type is used

bar: Type<import("foo").Bar>
```

**Expected behavior**

In generated types

```ts
import { Type } from 'file'

// ... later when Type is used

bar: Type<import("foo").Bar>
```

**Additional context**
Created a PR with a failing test

This happens because of https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/other/visitor-plugin-common/src/mappers.ts#L51

**Comment by charlypoly** [comment]
Hi @9at8,

You can use the following configuration to get around this limitation:

```yml
Bar: 'import('file').Type<import("foo").Bar>'
```
