### ISSUE TITLE
directiveResolverMappings generates file with errors

### ISSUE THREAD

**Issue by nick-keller** [dotansimha/graphql-code-generator#7566]
# Plugin `typescript-resolvers` `v2.5.2`
The config `directiveResolverMappings` with a custom class generates a file with errors.

Config file:
```
    config:
      directiveResolverMappings:
        foo: ../types#MyType
```
# Expected behavior
```ts
import { MyType as ResolverFnFoo } from '../types';
export { ResolverFnFoo };
```
# Actual result
```ts
import { MyType as ResolverFnFoo } from '../types';
export { ResolverFn };
```

# How is this an issue?
This export conflicts with another one of the same name in the file.
```
TS2484: Export declaration conflicts with exported declaration of 'ResolverFn'.
```

# Further details
If that helps, using a native type works well:
```
    config:
      directiveResolverMappings:
        foo: string
```
```ts
export type ResolverFnFoo<TResult, TParent, TContext, TArgs> = string	
```

**Comment by charlypoly** [comment]
Fixed in `@graphql-codegen/typescript-resolvers@2.5.3` 📦 

Thank you for your contribution @nick-keller!
