### ISSUE TITLE
typescript-apollo-angular generates unused types with sdkClass option

### ISSUE THREAD

**Issue by coyoteecd** [dotansimha/graphql-code-generator#7573]
**Describe the bug**

When using sdkClass option together with typescript-apollo-angular plugin (see #3005 where this option was added), the generated wrapper service always includes a set of "xxxAlone" types, regardless of the contents of the schema for which code is being generated. But, these types are only used when wrapping a query, mutation or subscription, respectively.

The result is that depending on your schema, a generated type ends up being unused. And if you have enabled noUnusedLocals/noUnusedParameters flags in tsconfig.json, this results in a compile error on the generated code.

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Feed {
  id: Int
}

type Query {
  feed(): [Feed]
}
```

2. My GraphQL operations:

```graphql
query MyFeed {
          feed {
            id
          }
        }
```

3. My `codegen.yml` config file:

```yml
...
generates:
  ./src/graphql-types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular:
          sdkClass: true
          serviceName: GraphqlService
          serviceProvidedInRoot: false
```

Result: the generated file contains:

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

type WatchQueryOptionsAlone<V> = Omit<ApolloCore.WatchQueryOptions<V>, 'query' | 'variables'>;

type QueryOptionsAlone<V> = Omit<ApolloCore.QueryOptions<V>, 'query' | 'variables'>;

type MutationOptionsAlone<T, V> = Omit<ApolloCore.MutationOptions<T, V>, 'mutation' | 'variables'>;

type SubscriptionOptionsAlone<T, V> = Omit<ApolloCore.SubscriptionOptions<T, V>, 'mutation' | 'variables'>;
```

**Expected behavior**

The generated file should contain only types that are required for the wrapper GraphqlService.
So, omit `MutationOptionsAlone` and `SubscriptionOptionsAlone` from the generated output when the schema does not contain mutation/subscription operations.

**Environment:**

- OS: Windows 10
- `@graphql-codegen/typescript-apollo-angular`: 3.4.1
- NodeJS: 14.18.2

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by charlypoly** [comment]
Your changes have been released in `@graphql-codegen/typescript-apollo-angular@3.4.5` 📦 

Thank you!
