### ISSUE TITLE
Add ability to generate queryClient[fetchQuery/executeMutation] like useQuery/useMutation when using react-query without hooks

### ISSUE THREAD

**Issue by fzkirablackwhy** [dotansimha/graphql-code-generator#7599]
**Is your feature request related to a problem? Please describe.**
I want to use react-query without hooks in some places

**Describe the solution you'd like**

Add ability to generate functions like queryClient.fetchQuery and queryClient.executeMutation

**Describe alternatives you've considered**

None

**Additional context**

For example, generated fetchQuery should be like:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/15785413/156311557-ef5de79f-bc22-4e28-b5d1-7573bbd17ca4.png">

**Comment by fzkirablackwhy** [comment]
I saw it, but I want to use it in another way, with client.
It will be cool if I have ability to generate functions like that:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/15785413/156877170-825cb3bb-8921-48a5-a258-57ba3fc1428a.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/15785413/156877181-651556c3-8d28-464f-80cf-ff806f1e6513.png">

**Comment by charlypoly** [comment]
> In your approach everything is connected to hooks.

I agree, however, it does not force you to use hook-based (in the lifecycle POV) functions, you just need to access the fetcher through the hook variable.
The plugin is hook-first by following the design of React Query itself that is hook-first too.
