### ISSUE TITLE
[graphql-request] expose `operationType`, allows for custom caching possibilities via middleware

### ISSUE THREAD

**Issue by Diizzayy** [dotansimha/graphql-code-generator#7608]
**Is your feature request related to a problem? Please describe.**

current implementation doesn't allow `graphql-request` middleware to be aware of the `operationType`.

Having this property exposed would cause zero overhead, whilst allowing for much more custom application specific caching possibilities.

**Describe the solution you'd like**

I'd like for `operationType` to be passed to `SdkFunctionWrapper`.

**Comment by charlypoly** [comment]
Hi @Diizzayy, 

I can see that your PR is now closed, is this subject still pending?

**Comment by Diizzayy** [comment]
It is, I'm not sure why the PR was closed but the operationType can be very easily exposed without having any side effects.

**Comment by charlypoly** [comment]
Released in `@graphql-codegen/typescript-graphql-request@4.4.0`

Thank you for your contribution!
