### ISSUE TITLE
Deprecated dependency `subscriptions-transport-ws`

### ISSUE THREAD

**Issue by llc1123** [dotansimha/graphql-code-generator#7621]
Package `subscriptions-transport-ws` is now deprecated and should switch to `graphql-ws`.
See https://github.com/apollographql/subscriptions-transport-ws/blob/master/README.md

```
@graphql-codegen/cli 2.6.2
├─┬ @graphql-tools/prisma-loader 7.1.2
│ └─┬ @graphql-tools/url-loader 7.8.0
│   └── subscriptions-transport-ws 0.11.0
├─┬ @graphql-tools/url-loader 7.8.0
│ └── subscriptions-transport-ws 0.11.0
└─┬ graphql-config 4.1.0
  └─┬ @graphql-tools/url-loader 7.8.0
    └── subscriptions-transport-ws 0.11.0
```

**Comment by charlypoly** [comment]
Hi @llc1123, thank you for raising this concern!

This dependency is actually from `@graphql-tools/url-loader`, could you recreate this issue on the [`@graphql-tools` repo](https://github.com/ardatan/graphql-tools/issues/new)?

Thank you!
