### ISSUE TITLE
Add developer context for `ENUM_VALUE` deprecated directive similar to `FIELD_DEFINITION`

### ISSUE THREAD

**Issue by tombailey14** [dotansimha/graphql-code-generator#7627]
I noticed when working with the `@deprecated` directive that the deprecated tag and reason is only generated when the directive is used on `FIELD_DEFINITION` types but not `ENUM_VALUE` types. This was noticed when deprecating an enum value, the IDE would not show the enum value with a line through it like on a deprecated field definition. Below shows the schema and generated file when using the `@deprecated` directive on both types.

schema.graphql:

```
type ExampleField {
  id: Int!
  name: String! @deprecated(reason: "No longer used.")
  username: String!
  email: String!
}

enum ExampleEnum {
  Alpha
  Bravo
  Charlie @deprecated(reason: "No longer used.")
  Delta
}
```

resolver-types.ts:

```
export type ExampleField = {
  __typename?: 'ExampleField';
  email: Scalars['String'];
  id: Scalars['Int'];
  /** @deprecated No longer used. */
  name: Scalars['String'];
  username: Scalars['String'];
};

export enum ExampleEnum {
  Alpha = 'Alpha',
  Bravo = 'Bravo',
  Charlie = 'Charlie',
  Delta = 'Delta',
}
```

I have a solution working which makes use of the `getFieldDefinition` function in the `base-types-visitor.ts` file to add a similar comment to the `ENUM_VALUE` type when generating. Happy to put up for PR but wanted to create this issue first. Thanks!

**Additional context**
For context here is the IDE for both deprecated `FIELD_DEFINITION` types and `ENUM_VALUE` types:

Deprecated field definition with line through:
<img width="556" alt="Screenshot 2022-03-07 at 17 39 12" src="https://user-images.githubusercontent.com/98548671/157088080-9f573a65-f6b3-4366-b817-b2c74c7dc5f8.png">

Deprecated enum value with no line through:
<img width="760" alt="Screenshot 2022-03-07 at 17 39 37" src="https://user-images.githubusercontent.com/98548671/157088172-63a577bf-9e08-4e2e-bdc2-6660f04b2c16.png">

**Comment by charlypoly** [comment]
Hi @tombailey14, thank you for spotting this missing enum values support!

Of course, go forward with the pull request, I'll review it as soon as it is ready.
Let me know if you need any guidance.

**Comment by charlypoly** [comment]
Thank you for your contribution @tombailey14 ! 🤓 

Your changes has been released in:
- `@graphql-codegen/visitor-plugin-common@2.7.3`
- `@graphql-codegen/typescript@2.4.7`
- and all dependent packages
