### ISSUE TITLE
Add __typename to generated TypeScript interfaces

### ISSUE THREAD

**Issue by bmarker** [dotansimha/graphql-code-generator#7629]
Checking `__typename` for a field that returns a union works great but a field defined as an interface does not have `__typename` because the generated type for the interface lacks `__typename`.  All the implementing types include `__typename` though.

**Describe the solution you'd like**
It would be nice to have an option to include `__typename` on the generated types for interfaces.

**Describe alternatives you've considered**

**Additional context**
Going to explore adding __typename via another plugin.

**Comment by charlypoly** [comment]
Hi @bmarker and thank you for the report!

Could you please provide a codesandbox to illustrate your example by using the https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template/tree/master/ template?

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you!

**Comment by bmarker** [comment]
I thought that was only for bugs but there's no bug to reproduce here. 

I can add a reproduction of a GraphQL interface codgen.

**Comment by bmarker** [comment]
I was able to create a sandbox as long as I included the document.graphql as well.

https://codesandbox.io/s/winter-leaf-61jxb7?file=/types.ts

Generated type for the interface:
```
export type IMyType = {
  id: Scalars['ID'];
};
```

Generated type for a type:
```
```

**Comment by dotansimha** [comment]
Duplication of https://github.com/dotansimha/graphql-code-generator/issues/3417 

Short answer: The TS types generated are intended to reflect the runtime response of GraphQL, since this is what your code is going to use eventually, and `__typename` will never be available on a GraphQL `interface` because those are being "removed" at runtime and replaces with the concrete GraphQL `type`.

Longer answer with examples is here: https://github.com/dotansimha/graphql-code-generator/issues/3417#issuecomment-609605106

**Comment by bmarker** [comment]
I'm using these types server-side, so I am not using the operations.

We want to use them in type guards in code and we use the `__typename` for the `resolveType` on a type resolver.

We currently need to use `as` or other type casting to check the `__typename` for an interface. Unions work fine implicitly.

**Comment by bmarker** [comment]
I can understand how these would be removed on the client side with `typescript-operations` but I'm missing what would be removed on the server side and what should be used instead of the interface.

**Comment by bmarker** [comment]
Sorry. The page break was right at the end of the post. I did not see there were follow-up messages. Hopefully there's something there.

**Comment by bmarker** [comment]
Basically I'm in this case:
> But - if the consumer is typescript-resolvers, it might be a bit different, because in this case, you want to be able to use the TypeScript interface and have __typename pointing to the possible types (it works with unions now because we point to the all possible types, but it's not the case with GraphQL interfaces).
So we can add that option to add __typename for that purpose.

That issue/thread seems to be just about the `typescript-operations` case. Did I miss the solution for the resolvers case?

If we had this on the service side it would work but I don't see the equivalent. I'm guessing it's still `type-operations`:
```
interface Bar {
  x: string;
}

interface BarA extends Bar {
  __typename?: "BarA";
  a: string; 
  x: string;
}

interface BarB implements Bar {
  __typename?: "BarB";
  b: string; 
  x: string;
}

type BarUnion = BarA | BarB;

type Foo {
  bar: BarUnion; 
}
```

I don't think we have a `BarUnion` equivalent and the type for the `bar` property is just `Bar`.

**Comment by bmarker** [comment]
I updated my sandbox to include the `typescript-resolvers`. I see the parent types might have been what I needed for the type resolver at least:
```
 ResolversParentTypes['IMyInterface']
```
That's a union of the known interface types.

1. We have the default mapping set to `unknown` to work around some other issues (a fix is pending so we might be able to get rid of that).
2. There doesn't seem to be a deep replacement for parent types, just on the resolver functions. So a type with an interface field does not appear to have a matching type generated with the field type set to `ResolversParentTypes['IMyInterface']`. I'll need to add to my sandbox to demonstrate the outer type.

**Comment by bmarker** [comment]
I added a parent type to my schema:
```
type MyParent {
    value: IMyInterface
}
```

And it generated my type:
```
export type MyParent = {
  __typename?: 'MyParent';
  value?: Maybe<IMyInterface>;
};
```

But it does not generate a type for `MyParent` with `value` type `ResolversParentTypes['IMyInterface']`.

It DOES generate a resolver type where the `value` resolver function takes `ResolversParentTypes['IMyInterface']` but I actually need the type.

Because of the way our services are returning federated GraphQL types, I am returning a POJO matching a common type and it is NOT being resolved in my service but in a calling service. We need a type to match the POJO I need to return.

**Comment by bmarker** [comment]
I tried using my real equivalent of `ResolversParentTypes['IMyInterface']` instead of `IMyInterface` for a function parameter hoping to cleanly access `__typename` that way. The type looked OK to me in the generated code but for some reason `tsc` is reporting that the parameter type is `unknown`.

I wonder if there is too many union types just collapse into `unknow` or if there's something with the resolver wrapper types it doesn't like.

**Comment by bmarker** [comment]
Given the number of model mappings our service would require, I do not believe we'll be removing the default mapping of `unknown`. I don't think we can rely on a fully typed `ResolversParentTypes`.

For now I'm doing something like:
```
getInterfaceName<T>(obj: T & { __typename?: Maybe<string> }): Maybe<string>
```

```
