### ISSUE TITLE
[gql-tag-operations-preset] GraphQLError: Unknown fragment

### ISSUE THREAD

**Issue by takashimamorino** [dotansimha/graphql-code-generator#7642]
**Describe the bug**
I would like to use gql-tag-operations-preset .
![image](https://user-images.githubusercontent.com/44386888/157868241-31ef98de-5d78-4d3b-a9db-f03e44363f03.png)
![image](https://user-images.githubusercontent.com/44386888/157868419-4b6df2a0-31a0-4c22-a9ea-7860af54e62d.png)

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
  books: [Book]
}

type Book {
  id: ID!
  title: String!
  author: String!
}

```

2. My GraphQL operations:

```ts
const BooksQuery = gql(/* GraphQL */ `
  query Books {
    books {
      id
      ...BookFragment
    }
  }
`);

const BookFragment = gql(/* GraphQL */ `
  fragment BookFragment on Book {
    title
    author
  }
`);
```

3. My `codegen.yml` config file:

```yml
schema: ../server/src/schemas/**/*.graphql
documents: 'src/**/*.tsx'
generates:
  src/gql/:
    preset: gql-tag-operations-preset
    presetConfig:
      augmentedModuleName: '@apollo/client'
      fragmentMasking: true

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: macOS Monterey 12.1
- `"@graphql-codegen/gql-tag-operations-preset": "^1.3.0"`: 
- NodeJS: v16.13.2

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by n1ru4l** [comment]
Can you provide your babel config? It seems like it is not being used. https://www.graphql-code-generator.com/plugins/gql-tag-operations-preset#using-module-augmentation-for-an-existing-gql-function-from-a-library

**Comment by n1ru4l** [comment]
Closing this as the original poster did not respond.
