### ISSUE TITLE
[Website] Incorrect installation instructions for npm

### ISSUE THREAD

**Issue by gat-cs** [dotansimha/graphql-code-generator#7656]
**Describe the bug**

The installation instructions for npm seem incorrect.

1. In the ["Installing Codgen"](https://www.graphql-code-generator.com/docs/getting-started/installation#installing-codegen) section, the `npm install` step is missing the `--save-dev` flag. Although that's not strictly necessary, it's a good practice to make use of the separation between application dependencies and development dependencies.

2. In the ["Setup > Initialization Wizard"](https://www.graphql-code-generator.com/docs/getting-started/installation#initialization-wizard) section, `npm run graphql-codegen init` fails. This command would only work if a "graphql-codegen" script has previously been defined in the package.json file. The correct command is `npx graphql-codegen init`.

3. There is another related website that seems to belong to "The Guild" as well, but presents different instructions: https://www.graphql-cli.com/codegen/. That website recommends globally installing the npm package, whereas the codegen website recommends against that.

**Expected behavior**

Installation instructions for npm should work out of the box, follow good practices and be consistent across "The Guild" websites.

**Comment by B2o5T** [comment]
@gat-cs sorry for the long response and thank you for your feedback ❤️!, this will be fixed on the new website, which will be released very soon ;)

**Comment by saihaj** [comment]
I think our new website has fixed this.
