### ISSUE TITLE
[Website] Non existing plugin site raises 500 instead of 404 status code

### ISSUE THREAD

**Issue by n1ru4l** [dotansimha/graphql-code-generator#7659]
Visiting the following route results in a 500 error code: https://www.graphql-code-generator.com/plugins/foooooooo

Instead, it should be a 404 error code. similar to envelop.dev (https://www.envelop.dev/plugins/foooooooo).

**Comment by saihaj** [comment]
![CleanShot 2023-02-01 at 15 49 15](https://user-images.githubusercontent.com/44710980/216160069-b8f6352c-8e16-40b0-b61e-be4793899fdc.png)
