### ISSUE TITLE
Testing TypeScript Resolvers

### ISSUE THREAD

**Issue by janhartmann** [dotansimha/graphql-code-generator#767]
**Describe the bug**
I am not sure whether this is a bug or not, or I am basiclly just using this wrong. I want to test a resolver, like so:

**To Reproduce**

```ts
describe("query.scoredUnits", () => {
    it("returns an array of scored units", async () => {
      const result = await queryResolver.scoredUnits(
        null, // Argument of type 'null' is not assignable to parameter of type 'never'.
        null,
        new FakeContext(),
        null
      );
      expect(result.length).toEqual(2);
    });
  });
 });
```

And I do not want to pass in any properties, but I can not set `null` or `undefined` to the current `never` argument.

**Expected behavior**
I expect to pass  `null` or `undefined` or somehow ignore this in unit testing. 

**Schema/Documents**
If possible and relevant, please provide your GraphQL schema and GraphQL documents.

```graphql

type Query {
  scoredUnits: [ScoredUnit!]
}

type ScoredUnit {
  id: Int!
  name: String
}
```

**Environment:**
 - OS: MacOS Mojave
 - Codegen: 
    "graphql-code-generator": "0.13.0",
    "graphql-codegen-typescript-resolvers-template": "^0.13.0",
 - Node: 10.12.0

**Comment by janhartmann** [comment]
Maybe related to #489?

**Comment by dotansimha** [comment]
@janhartmann 
Since 0.13.0, you can override the type of the Parent per each resolvers.

You can declare your `queryResolver` as: `QueryResolvers.Resolver<any, null | undefined | never>` and I think it will do the trick.

**Comment by janhartmann** [comment]
I go for the mocked resolver approach for now, seems a bit cleaner for testing. 

Thanks for this amazing library, it has been very easy to work with.
