### ISSUE TITLE
typescript-generic-sdk generate an incorrect type when rawRequest is true

### ISSUE THREAD

**Issue by heiso** [dotansimha/graphql-code-generator#7688]
Hi there 👋 big fan of graphql-codegen here :)

**Describe the bug**
When using **typescript-generic-sdk** plugin with `rawRequest: true`, one of the generated types is incorrect.

**To Reproduce**
See this [codesandbox reproduction](https://codesandbox.io/s/sleepy-galileo-gbl33r?file=/types.ts)

**Expected behavior**
Requester type should have the correct return type like in this [codesandbox using a possible fix](https://codesandbox.io/s/cool-tesla-5o2lpp?file=/types.ts)

**Additional context**
I made a PR with a possible solution to this problem

**Comment by heiso** [comment]
Hey hello team 👋 
Did someone had a look at this issue/PR ?

**Comment by charlypoly** [comment]
Hi @heiso,

Thank you for your contribution! ⚡ 

It is now fixed in `@graphql-codegen/typescript-generic-sdk@2.5.0` 📦
