### ISSUE TITLE
JsonPropertyName is in `System.Text.Json.Serialization` not `System.Text.Json`

### ISSUE THREAD

**Issue by erri120** [dotansimha/graphql-code-generator#7721]
Docs: https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute?view=net-6.0

**Comment by erri120** [comment]
Temporary solution for people that have this problem: enable implicit namespaces in the project file.

**Comment by charlypoly** [comment]
Released in `@graphql-codegen/c-sharp@4.2.9` 📦 

Thank you @erri120!
