### ISSUE TITLE
contextType path starts with "#"

### ISSUE THREAD

**Issue by sarink** [dotansimha/graphql-code-generator#7762]
Node supports [subpath imports](https://nodejs.org/api/packages.html#subpath-patterns) as long as the import begins with `#`. However, the way that `contextType` works is by looking for an exported variable name after the `#`

That means if your context file is located in an aliased subpath, ie `"#api/src/context#Context"`, the generated types will have an import which cannot be resolved.

Suggestion: Consider using a different character, since Node has already claimed `#` in import paths

**Comment by productdevbook** [comment]
same problem `contextType: '#pergel-graphql#PergelGraphQLContext',`

**Comment by dotansimha** [comment]
I assume the only solution here is allowing to escape `#` with something like `\\#`?
@saihaj what do you think?

**Comment by productdevbook** [comment]
`\\#` dont fork

export -> `import type { pergel-graphql } from '\';`

**Comment by productdevbook** [comment]
@dotansimha

\\# dont fork

export -> import type { pergel-graphql } from '\';

**Comment by productdevbook** [comment]
Can we please resolve this? It's getting in the way. :( Thank you

**Comment by saihaj** [comment]
@productdevbook do you want to send a PR with a failing test case and a potential fix?

**Comment by productdevbook** [comment]
> @productdevbook do you want to send a PR with a failing test case and a potential fix?

I wanted to, but I couldn't find where it was.

**Comment by productdevbook** [comment]
@dotansimha @saihaj i am send [pr](https://github.com/dotansimha/graphql-code-generator/pull/9845) please check.
