### ISSUE TITLE
Add @deprecated annotation to Input fields for Typescript resolver

### ISSUE THREAD

**Issue by samchungy** [dotansimha/graphql-code-generator#7766]
**Is your feature request related to a problem? Please describe.**

I would like to have input fields annotated with the @deprecated comment like other fields

**Describe the solution you'd like**

Inputs marked with GraphQL deprecated directive appear as Typescript comments.

**Describe alternatives you've considered**

Living without deprecated comment

**Additional context**

**Comment by saihaj** [comment]
released: https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Fvisitor-plugin-common%402.10.0
