### ISSUE TITLE
yarn build fails after a fresh clone

### ISSUE THREAD

**Issue by villesau** [dotansimha/graphql-code-generator#7787]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on [Github](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

_Make sure to fork this template and run `yarn generate` in the terminal._

_Please make sure the Codegen and plugins version under `package.json` matches yours._

- [ ] 2. A failing test has been provided

- [ ] 3. A local solution has been provided

- [ ] 4. A pull request is pending review

---

**Describe the bug**

`yarn build` fails after clean clone & `yarn`.

**To Reproduce**

1. `yarn`
2. `yarn build`
3. following error is thrown:

```
yarn build
yarn run v1.22.17
$ rimraf "{,!(node_modules)/**/}dist/"
$ tsc --project tsconfig.json && bob build
Error: Could not resolve entry module (dist/graphql-codegen-cli/src/index.js).
    at error (/Users/path/to/graphql-code-generator/node_modules/rollup/dist/shared/rollup.js:10120:30)
    at /Users/path/to/graphql-code-generator/node_modules/rollup/dist/shared/rollup.js:16553:20
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async rollupInternal (/Users/path/to/graphql-code-generator/node_modules/rollup/dist/shared/rollup.js:18158:18)
    at async build (/Users/path/to/graphql-code-generator/node_modules/bob-the-bundler/dist/commands/build.js:151:20) {
  code: 'UNRESOLVED_ENTRY'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**

To my understanding the build should succeed. I'm following these instructions: https://www.graphql-code-generator.com/docs/custom-codegen/contributing

**Environment:**

- OS: macos
- `@graphql-codegen/...`: latest master at the time of writing
- NodeJS: tried with v14.15.4 & v16.14.2

**Comment by saihaj** [comment]
It hasn't happened to me 🤔

**Comment by villesau** [comment]
Maybe I need to try with more recent and clean clone then.
