### ISSUE TITLE
Move Templates to separate repos? 

### ISSUE THREAD

**Issue by williamluke4** [dotansimha/graphql-code-generator#782]

**Comment by dotansimha** [comment]
Hi @williamluke4 
We are still thinking about it, and it's open for discussion.
At the moment, we are the core maintainers of the codegen and the core maintainers of the templates, so it's easier to test and develop it on the same repo.

**Comment by williamluke4** [comment]
Hi @dotansimha,
I figured as much. I think that moving them to separate repos would make it easier for others to develop templates as they could just 'plug' them in without having to fork the main repo and mess around with npm link. This is just from personal experience, I'm sure there are better ways! 

You could also display a warning if the main repos version differs with the template version.

**Comment by dotansimha** [comment]
Hi again, @williamluke4 .
I updated the README with explanation of how to run the project locally. It's not too difficult.
Also, to develop a custom plugin, you don't need this repo, you can do it directly in your project, or as separated package.

- [How to run this repo locally](https://github.com/dotansimha/graphql-code-generator#contributing)
- [How to develop your own plugin](https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin)
- [How to pack your plugins as NPM package](https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin#packing-your-plugin)
