### ISSUE TITLE
Support @defer and @stream in operations plugin

### ISSUE THREAD

**Issue by n1ru4l** [dotansimha/graphql-code-generator#7885]
defer and stream are close to land and should be correctly supported within the code output.

**Comment by glasser** [comment]
Is there a theory of roughly what sorts of types should be generated for incremental delivery operations?

**Comment by marcesengel** [comment]
@hwillson 😍 any way to support you on this?

@glasser for `@defer` at least it's pretty basic, the deferred fields need to be made optional and that's all. Per the apollo documentation:
> Our deferred fields will not exist as keys on data yet [...]

https://www.apollographql.com/docs/react/data/defer/

**Comment by alesso-x** [comment]
Is defer supported now? Looking at the [PR](https://github.com/dotansimha/graphql-code-generator/pull/9196) referenced and this example https://github.com/dotansimha/graphql-code-generator/tree/master/examples/react/apollo-client-defer.

**Comment by n1ru4l** [comment]
Yes, we will release it today 😇

**Comment by jennyk1** [comment]
@n1ru4l I am still unable to use the defer directive with the latest version of graphql-codegen.
I see the event streams coming in but I think Apollo is having an issue parsing the data that is returned.

![Screenshot 2024-05-16 2 50 35 PM](https://github.com/dotansimha/graphql-code-generator/assets/90651818/c950a520-1ce5-4268-8eda-38c8f2772f22)
![Screenshot 2024-05-16 2 50 31 PM](https://github.com/dotansimha/graphql-code-generator/assets/90651818/ea75e20d-af0c-4833-81c8-0cd6e4008248)


This is the error:
```
ServerParseError: Network Error: Please try again
    at JSON.parse (<anonymous>)
    at parseJsonBody (webpack-internal:///../../node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.js:134:21)
    at eval (webpack-internal:///../../node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.js:167:48)
```

**Comment by alessbell** [comment]
Hi there @jennyk1 👋 I work on Apollo Client and it looks like your server is using SSE to communicate with the client which isn't supported out of the box. 

Can you please open an issue over on the Apollo Client repository since this issue doesn't have to do with codegen? Thanks!
