### ISSUE TITLE
Running apollo-template with NO_NAMESPACES wrong typings generated

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#789]
You run `apollo-template` in the NO_NAMESPACES mode and what you're getting is things like that.
![image 1](https://user-images.githubusercontent.com/3940079/48062361-12cb0480-e1c2-11e8-94fa-6f4f31b529e0.png)
All return types of Mutations/Queries is not actual return type but its name PascalCased.

Actual query in `local.graphql` schema.
```graphql
type Query {
  messages(tab: String!): [SomeMessage]
}
```

And it's using like that in `.ts`
```typescript
const GetMessages = gql`
  query GetMessages($tab: String!) {
    messages(tab: $tab) {
      id
      ...
    }
  }
`
```

**Comment by dotansimha** [comment]
Fixed in 0.14.0 🎉
