### ISSUE TITLE
Typings doesn't work with TS 3.1 for generated HOCs in apollo-template NO_NAMESPACE

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#790]
**How to repoduce:**
You generate stuff using `apollo-template` with NO_NAMESPACE mode.

**Actual:**
I'm using generated HOC in code expecting to get autocomplete and typechecking of its options.
![image](https://user-images.githubusercontent.com/3940079/48062819-6be76800-e1c3-11e8-8f21-381a691a6a4c.png)
But as you can see there is no blame on me in this case from TS Language Server.

But if I go straight to the generated code and trying it there I'm getting slap in my face saying that `unknownField` is not availbalbe on type.
![image](https://user-images.githubusercontent.com/3940079/48062782-49ede580-e1c3-11e8-99a0-bcc0d77cb1dc.png)

**Expected:**
Autocomplete to be there as well as the typechecking.

Tested on both VSCode and WebStorm so it's not IDE/Editor related.

**Comment by RIP21** [comment]
Simple fix to that is to remove `OperationOptions` generic and to put `ReactApollo.OperationOption<...>` directly on  operationOptions function argument.
Not sure whether somebody is going to override this second argument generic in a real life, so sounds like a good solution.

**Comment by dotansimha** [comment]
Fixed in 0.14.0 🎉
