### ISSUE TITLE
`[String!]!` is translating to typescript type `Array<Scalars['String']> | Scalars['String']`

### ISSUE THREAD

**Issue by Pika-Pool** [dotansimha/graphql-code-generator#7913]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on [GitHub](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

> Link to codesandbox: https://codesandbox.io/s/hardcore-tdd-q7uyd1?file=/types.ts

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

The graphql type `[String!]!`, i.e., a non-nullable array of non-nullable strings, is converted to `Array<Scalars['String']> | Scalars['String']` rather than only `Array<Scalars['String']>`.

**To Reproduce**

1. My GraphQL schema:

```graphql
type ProjectCreateMutation {
    response: String!
    message: String!
}

type Mutation {
    createProject(
        description: String!
        name: String!
        subtitle: String!
        tags: [String]!
    ): ProjectCreateMutation
}

type Query {
    getMessage: String
}
```

2. My GraphQL operations:

```graphql
mutation createNewProject(
  $description: String!
  $name: String!
  $subtitle: String!
  $tags: [String!]!
  ) {
  createProject(
      description: $description
      name: $name
      subtitle: $subtitle
      tags: $tags
  ) {
      response
      message
  }
}
```

3. My `codegen.yml` config file:

```yaml
overwrite: true
schema: schema.graphql
documents: document.ts
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
```

**Expected behavior**

`[String!]!` should be converted to `Array<Scalars['String']>`

**Environment:**

- OS: Linux (PopOS)
- `@graphql-codegen/...`:
```json
{
  "dependencies": {
      "@graphql-codegen/cli": "2.6.2",
      "@graphql-codegen/typescript": "2.4.11",
      "@graphql-codegen/typescript-graphql-files-modules": "2.1.1",
      "@graphql-codegen/typescript-operations": "2.4.0",
      "graphql-request": "^4.3.0",
      "graphql": "^16.5.0"
  }
}
```
- NodeJS: v16.14.2

**Additional context**

**Comment by falkenhawk** [comment]
I believe this is expected, because of input coercion for lists: https://spec.graphql.org/June2018/#sec-Type-System.List

**Comment by romshark** [comment]
> I believe this is expected, because of input coercion for lists: https://spec.graphql.org/June2018/#sec-Type-System.List

If I understood correctly [spec October 2021](https://spec.graphql.org/October2021/#sec-List) states that expecting type `[Int]` you can never get `Int(1)` if you provide `1`, instead you should get `[Int(1)]`, which makes sense as you're expecting an array, not an integer.

Therefore `[String!]!` should generate `Array<Scalars['String']>`, and **not** `Array<Scalars['String']> | Scalars['String']` since we're expecting a non-nullable array of non-nullable strings. It can be coerced from a string input to an array with a single string item, but it's always an array in the end.

Please, correct me if I'm wrong.

**Comment by ardatan** [comment]
As a consumer, per spec you can give array or a single value, right? And "operations" plugin generates types for consumers. So this makes the types valid or am I missing something?

**Comment by romshark** [comment]
> As a consumer, per spec you can give array or a single value, right? And "operations" plugin generates types for consumers. So this makes the types valid or am I missing something?

Now I see what you mean. Taking coercion into account, as a consumer, you can send both array and single value so the current behaviour is correct ☑️.

**Comment by ardatan** [comment]
I think we can close this issue then :)

**Comment by mwood23** [comment]
Although it's spec compliant, is there a way to override this behavior? It makes working with the generated types difficult always guarding for a string when we know it will be an array. I would rather not rely on coercion and enforce to callers that they need `Array<Scalars['String']>`.

**Comment by DanielSharkov** [comment]
It's documented, just not in the GQL-Code-Gen docs, but in the plugins docs:
https://the-guild.dev/graphql/codegen/plugins
Search for "typescript-operations", there you can find all the configuration.
