### ISSUE TITLE
Allow --ignore-no-documents flag to prevent exit code 1

### ISSUE THREAD

**Issue by leemhenson** [dotansimha/graphql-code-generator#7943]
**Is your feature request related to a problem? Please describe.**

I have an issue with the way `graphql-codegen` exist with a non-zero code in the case where it could not find any `documents` to codegen. This is a regularly occurring situation in our monorepo, where we scaffold a new package with a predefined set of package scripts (one of which is `codegen`). Our CI runs `codegen` on each package that has that script, and for the new package it will always fail as the package hasn't yet started to be worked on and thus has no `documents`.

**Describe the solution you'd like**

I'd like to be able to set a flag in the codegen.yml like `ignoreNoDocuments: true` or pass a flag to the CLI such as `--ignore-no-documents`. In these cases, if no matching documents were found, the message about missing documents would still be printed but the exit code would be `0`.

**Describe alternatives you've considered**

I could conditionally invoke `graphql-codegen` using `grep`, but it means I would have to maintain the glob in two places now. Alternatively I could remove the `codegen` package script, but then someone would have to remember to add it again later.

**Additional context**

N/A

**Comment by a-type** [comment]
Would also like to not fail the generator if one of my modules doesn't have documents.

We're extracting our app into a separate frontend and backend project and deploying them separately. The backend server Dockerfile currently has to include all of the frontend files in its context so that the codegen step doesn't error out, even though none of those files are used.

**Comment by saihaj** [comment]
hey @leemhenson @a-type here is alpha release for you to test this feature and provide feedback https://github.com/dotansimha/graphql-code-generator/pull/8040#issuecomment-1175506887
