### ISSUE TITLE
Security vulnerability with `latest-version` in `graphql-codegen-cli`

### ISSUE THREAD

**Issue by kevcube** [dotansimha/graphql-code-generator#7990]
### Describe the bug

<img width="918" alt="image" src="https://user-images.githubusercontent.com/716806/176322242-69f59bdc-101b-4470-8d90-bab40517803a.png">

verify with `yarn audit`

latest-version requires package-json which requires got.

This PR upgrades latest-version to 6 because 6 still supports node 12.

If node 12 support can be dropped, then upgrade to latest-version 7.

### Steps to Reproduce the Bug or Issue

```sh
git checkout main
yarn audit
```

### Platform

- `@graphql-codegen/cli` version: 2.6.2

**Comment by saihaj** [comment]
should be fixed in https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen/cli%402.6.3

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/cli@2.6.4`. Keeping open until we'll figure out a more stable way to upgrade and make sure we do not have regressions.

**Comment by saihaj** [comment]
> Fixed in `@graphql-codegen/cli@2.6.4`. Keeping open until we'll figure out a more stable way to upgrade and make sure we do not have regressions.

https://github.com/dotansimha/graphql-code-generator/issues/8008
