### ISSUE TITLE
Syntax errors in fragments are repeated in all files

### ISSUE THREAD

**Issue by vlin02** [dotansimha/graphql-code-generator#8032]
### Describe the bug

Running codegen with errors present inside of queries or mutations seem to only show the error in the file where the error is from. However, when an error is present inside of a fragment, the error is reported for all files, regardless of whether they use the fragment or not.

### Your Example Website or App

https://codesandbox.io/s/zen-http-3lk42q?file=/otherdocument.graphql

### Steps to Reproduce the Bug or Issue

run generate in the sandbox

### Expected behavior

I expect the error to only appear in the file where the fragment is declared.

### Platform

- OS:  macOS,
- NodeJS: 16.15.1
- @graphql-codegen/add": "^3.1.1",
    "@graphql-codegen/cli": "^2.4.0",
    "@graphql-codegen/typescript": "2.6.0",
    "@graphql-codegen/typescript-operations": "2.4.3",
    "graphql": "^16.2.0"

**Comment by saihaj** [comment]
I tried on CLI `2.11.0` and seems to be fixed by https://github.com/dotansimha/graphql-code-generator/commit/e2cfc5c360d09a4ba98d8855769b8711c96f13b2
![image](https://user-images.githubusercontent.com/44710980/181348009-d374e346-e419-4ef7-b954-6e8afb020009.png)
