### ISSUE TITLE
refactor: Make every config option a CLI flag

### ISSUE THREAD

**Issue by saihaj** [dotansimha/graphql-code-generator#8044]
could every config option automatically be a cli option? then we don't have to implement stuff twice?

_Originally posted by @n1ru4l in https://github.com/dotansimha/graphql-code-generator/pull/8040#pullrequestreview-1029768204_

**Comment by charlypoly** [comment]
@saihaj I think that the current design of separating config and CLI flags make sense (ex: `--check` cli flag does not make sense in config)

We could refactor it, but it would be cumbersome considering that `YamlCliFlags` is only owned by the CLI and `Types.Config` is shared with all packages (plugins and presets included)

**Comment by saihaj** [comment]
yeah we can revisit this in future then not too critical imo
