### ISSUE TITLE
Unable to customise the Promise returned from a resolver

### ISSUE THREAD

**Issue by dac09** [dotansimha/graphql-code-generator#8046]
**Context**
When using `typestrict-resolvers` plugin, and using the `mappers` property to map Prisma types

The problem I'm seeing is specific to union types. Prisma's return types for findUnique is Promise<TModel | null>
vs graphql-codegen expected type is `Promise<TModel> | Promise<null>`

This means that you can't just return from a `db.model.findUnique` call in a resolver and the only viable solution is to do typecasting, because the Prisma type is more "strict" than the type generated by codegen.

The errors appear as follows (message will vary slightly depending on ResolverFn definition):
```
Type 'Promise<Post | null>' is not assignable to type 'Promise<null> | Promise<Post>'.
```

**Describe the solution you'd like**
**Either:**
a) The ability to customise how the Promise from a resolver is constructed 
OR
b) Use unions _inside_ the generic of the Promise i.e.
✅ `Promise<TResult | null> `
⚠️ and not `Promise<TResult> | Promise<null>`

**Describe alternatives you've considered**
- I tried changing the `ResolverTypeWrapper` - but to no effect

**Additional context**
Follow this thread https://github.com/redwoodjs/redwood/issues/5481#issuecomment-1157814297 for a bit more info

**Comment by dac09** [comment]
Some additional context:

1. This error only seems to happen, when we try to customise the return type of `ResolverFn` from the default `Promise<TResult> | TResult`

I broke down how the generics and the types are wrapped here in [this playground here](https://www.typescriptlang.org/play?ts=4.7.4#code/PTAEFEA8EMFsAcA2BTUsD2ATZjQDMAndWUABQIEsBnWaAcitAHNkA7ZA6AF2U1C4Ce8ZFQBQg4WUo1opdFS6gAvKADeo0Js0VMALlCsArrABGHANwatXClxT6FlVk0tbQJrAIdcnLq5oBjAmRuXgBBLn0AEVDXLUMqDgBJPQNjMwJQAB80xERLAF9RURBQABUAC2pQaq4K1Gw8aENERUaKVlsKdFZQdDxQAFloATNQaFY+ACURdEQANw4yoWQAdU54YUye5g2KgEdEAFoArGQWVlFkSHh0AkUJVGHR5AAeMoA+ZXLs3MQrm53B4rUAzKhzRYEZbCdbQTYcd5fFTkYjUN6fX5lYolMAARgAdKBVqgAO4bGq9aCgeBEWBo0BHUAKCh5UCIdDoADWHSYfU54hBwXBCyWsPhfBUYIhSxWYq2r3I1FocgUH2KpQATISAHLoEmgEmoWic1C2cZoEZmfHWwlJfhVVic+3VZ5jaokircUABZqJRgCyRkuFJViu1AqMOvIXSqFy3hqnGgADMhOJoEw6GdjA69tQeA60FwCmQ8AANAb6r12p0a7y6qhglxDAReo8+gN66BoyLMnhDKwAjYeom0+xeFn8Hdc2RoPcKIWGe5DIpSLObAvqqx0A96jUqFRDMhCQJ0IZvRMu8gMIsaooJnxmazEqhO1Q4KgaegTChYAHSRsQxROlEiSPBdS4d4wRaLgkU0MooNaUBrh4SZGCAtEABkKBNV4OjwDhynA9DEjVNwAH4pFRRIFTXedEHeIjaTRD5SK0fRiLeVc50LSCRGgljfi49d6PgvjWgTUpKmqWpd0aZpEMbZtWxBQhiFBWYewAMUuNsg3gQCmMSGYmFnTAUH3XiD3E75RKsxQcg4yz+PVMAAAl0EhUAADJQAwjknS9OpqlPLh4GXfgVhtQkPQEdN0BEW9mEzVSSDMHlKOAzjpGVeR7L+L4uEzRzFRkFUYMEwy3iMPI1TbfNWELAB5ZcwsUFQ9IMqjkFA8DXg60NLWQCSwAAIXCoLGDbDMRFYOhFGfEhCtAT0b1fd9qSIb8ryivdZp3apoEHQxC0QWKOlOAhgkHMi-3wAtEGa0Ll11cBLqndqANYDjjNM8yqD6z6ww+IA)


Here's my walkthrough of this repro - but I'm struggling to figure out _why_ this happens... https://s.tape.sh/HnoTWrnn

**Comment by n1ru4l** [comment]
Hey @dac09, I finally tried to tackle this today and I really struggle to reproduce this in a simple way 😭...

In my current understanding the following should already cause this error?

```ts
const typeDefs = /* GraphQL */ `
  type Query {
    hello: String!
  }

  input SumInput {
    a: Float!
    b: Float!
  }

  type Mutation {
    echoString(str: String!): String!
  }
`;

const resolvers: Resolvers = {
  Query: {
    hello: () => 'world',
  },
  Mutation: {
    echoString: (_, args) => {
      // This should cause the error? 
      const foo: Promise<string> | Promise<null> = Math.random() > 0.3 ? Promise.resolve(null) : Promise.resolve('');
      return foo;
    },
  },
};
```

[TypeScript Playground Link](https://www.typescriptlang.org/play?target=7#code/JYWwDg9gTgLgBAbzgcSgQzACwIoBkBKApgM4QA2AboQJIB2AZhHAL5z1QQhwDkA5ulgCOZbgG4AUIQAekWHBgBPMITgBZNAoBGhADwAVAHxwAvHD1wAPnFoBXMmQnTZ8Rcrh0wNmOq27DJtQ1tfQNHGWgXJRUAUSk0AGMYfThpGEJaABNiRDgAbQBrQgUALjhiGChgWl4AXVKbWnzaCAB3WhYjUyRcgGk4KrhChQh6MzqzXpqWMOd5KMDCgHkwGGAIWjQyfQAaOD7U9KzBopGzTrhFkGAkvV2eowAyHNyAZRtNHqL+9p6agH5Sj5gnpXu9PgoakZmDMInM3OpCkC-HcUlI0plskNTv5TJdrjs9o9nm8Pl8Br9AUE-KDSRCoTC5K4VERBDZgFBCAAxYCEMhZAn7NGHTEnUY4i5XG53IndAAK3z2NQAtAC4AA5dZquxkNCaMjU2WQ6biAD0ACozXAAIL2OCaNlkGBKgZoTJweI2cqcMrxTZoKDEXYgDDKDLyJgwTCEdlwBIwGybOAUTY2EhwM0myThRnzF6+nUBgIIcRwdwAEVK5Uq1QkpZeFSqvErDZrJbgACEIORCK7Spou-rXbX3LQYKVbCBtFBh5yyBA0GPrDZJ4Rp+JoeIs7MmWovAu1u0um2APrHpkbECEVXcVR71brMRt-MenVpN4gUp5v0B3LcWfzmBuBqYdCHiTAIHrateFVJEdC-AtiF-SDGyA0J1wkLdYR3W8YH3dYAGFNhfBdCHfK0oF4bIj1LKpPEXd8PC8CQN0wnN4TvA9ojAiCW14cjKKLNsq0-fN-UQ7hkOqIDmIwpwsPmbBUygBRBNLU9zzQS9r0U1cFEfUso3sCARO-cTJN4aT0M3OS2JUBjaDo1TYxMhDf3-BdLNLTQXLEty5w84CrNYyI3CIUhKFXPQogAdQEZQoBCAJZQ4K5iD8IwrD0WTsxC5kSHIKgoGi65MDCgq-DCuwYF2PRZX9dJqrMfD1jSNEav44hzmLUsOXCqhSjKiKoE5Wh9Eqx0arqjlRxq5rR1SdqKM6mTgrhPK+tXMaSCqyb6tHItmFmlrUgOxaBK6ZhOjbKxBsKkatuIHazCmhqjvmtqzA6gxrrgW7V2KyM-oep7ar2xq9Dm1rwa+7Lt3mP7htGvRxvBl6Zqa46Pr0L6AgACjbMAwdKUHpuqtt-Uo4mOu2J9McXCG6ZpmiGGMlABBwAh8oiuhGHEABKEwjGSzhgDS4HHQyswUdh+S3BJYh4kqFYD3lxXgG0e7ke2ibnrBt6obOzq8YJonddJpnYyWqmlot+I6eJyGFrbKpGFKVAMA5v6eYgfnBetYgFFoeJqDSdA9Qq7WYEl4XUt0K0A6DkPV11fVxajtDVp3VWlfvWg-s1lHdvNjH3uhpbznx0tCdJ4m0bJ0sKeIa3KNt+2S4N52Wbd9m8C9lnfeMIwtcex1LDgGPRYjkeo5luQqlD+gEjs94FZzlWV7VqdFk0AArUCbkLsxwVRdEjirRsi9e9uFs+8vECEjfKm0T9H+AZX1mz9WuVG7ohgVPRwTjGHlVFgl90YM1LobNCPUuZUFVJ-d+edYHfzTrsX+ZJ2gAKKEAlGoDr5YxhuuayOVvgLyXnABBucEbbz3okVBZsr4QINrfSiRhuplFfs-Chr9EGfw1qNV0CgwHg0dgQ8uw5erlRfpoVeb8qHIILpHXYgj9Y32xuIohmdcw8NzjQ-e9CsEqQOBiMovFhGqLEawkwP1KHrxkZvVcei6HAJ1oY8x+Cy6sJsTog81Dd76JcajPWHioGz1ytw+xa91gIwMcfYxZ8zEMP2hdCx8AUksKoogS61jSxWFxrjAAdEUxupRBG5BqALQeETZGIKcQfJRR8ijuKYWor6fNvGRLkQeOpsSmlJJEYzDJGcbLhKisofOSMxkkGEadDxB0K4mxrv01upcHaM07q7NmHte7IO9gPIwsE9BTKNlYCeYtDnHIMMMkhO5qDECmYsegCNNazJaWieZxtSwQF3sTFZUM1mQI2azd2WAdkbT2ZUow-ZuyujHmc3Q0LBy0GuXDNwapUjPKRhXSF48UqTxCGEtacAyzsn3sAKgmK06vLrq80RaSsmGw+aYSu1hUilHRWiSlgSDAW2rg1WuetyZWwyX8tlISgXd22ZzcF-ccWBLhXisW3KMLmktOoMAYBGx2kIDAFohB0ixltGgZMwAdThx9FGYMa1siujDJGFQkihrZCZNkDMWjQrIIDMcpynYYW0AGp6qZsUQybXgr5bgvqkWoRnP5RcCMg1xVDaJH8f5Y3RrbDhPC-rfqBpiomhKCBLrDh0spANG0oAJpDQWotbZzJlvKhWvNVa4LJrMrxdNdZlyMXol2hyTEgqqsCBqrV2hdX6vaJsMgsYTVmv1BawgVqXWxjdPauAjrCrZD5aOV1mYRlEoRsQOu3rqIdgHD2bNYaU2RvPZ5OA7l6Ktr8gBW9mbc6lELcWpSJQsnDjrRQx9El22BU7SAbtL9QN9pgCtd1KhX2+M9cQHQbY6VTICCotsR75jxOyAezDyhxJwYfFMUwuGwbHN-IR2gQFxBdSfEROwJF3yqhiW2UsB7yOpufTUC2pY8OEB43AFDUQBMsjZBybkvJ+SUcImQYib5lzUx4LRLw3BvqlmgSkbi5lmOeqQ6WUssF2NRDbVBVCAm+MCaE8oEThBWSkok3yRDlGuLgXMop7gVZVNtjQixPdO4S0KAPXpwTdNUOmHQ7xsjWGhQmNI6TDjAWgIBDiw1BLX7qO0YMryOcOny06CM-hpCQHdgWZC6XKZPnCU7iC1ZlQ4XaAKEy7uXCucYIcWiQhnQtWNMBdVAFmroWoiVc3KaE0Y3xsTcm1N6bU2RviDtrQcoa0yyEHoJk80WzQW4HTCaOAAADNs-mv33303AQyc5Py8QAIRtmYJuZmjl7KOXYQ3Uo96bune8ne2NH2WD3aJZRk7+nQKud4rjYSFDrt80u1BX7pZnwMfkyAXGyme0Qbold6H32AK-bu3tjCC2lvrtXE3HN5bMnsIC++1jZ3sus1xji7gLRoB8m4BbQ6Gb2vZpe5p0HUFSi42PMopaOKeeljG2YTAosyjgTsGGX0noVCrtXBwKAfw4A0-h+sJbjBWbwp0Ofao0dFW6FsPYc46hIwFPQJkTgDO4BGAAAwFIAMxwHV-C63yDcZm7IALUonvie424NwPmw5TscnjFAdouvw+gJpwj18pFlwC6F5bSiovNdrp1TYaP6fiAFNRwUtAcAADU+fC+QYKZoOPHPSwc43EAA)

**Comment by enisdenjo** [comment]
> ...but I'm struggling to figure out _why_ this happens...

```ts
declare let a: (() => 1) | (() => 2)
declare let b: (() => 1 | 2)

a = b // error
b = a
```

The two declarations _are_ actually different:
- _a_ is **two** functions that either always return 1, or always return 2
- _b_ is a **single** function that returns either 1 or 2

_a_ is not equal to _b_ because _b_ will return 1 or 2 from a single source, and _a_ expects consistently 1 or 2 from different sources respectively.

On the other hand, _b_ is equal to _a_ simply because `() => 1` = `() => 1 | 2` - the return union of _b_ matches one or both members of _a_.

**Comment by n1ru4l** [comment]
From https://github.com/redwoodjs/redwood/issues/5481#issuecomment-1160310745

> Which I think makes sense generally, what you accept for one of those - personally, I think switching graphql-codegen to use Promise<Model | null> makes sense because it is the more flexible of the two ways to describe that pattern of something or nothing

I think this is exactly what we already do 🤔 

In this emitted type TResult for `ResolverFn` will be `null | SpecificType`:

```ts
export type Maybe<T> = T | null;

export type Scalars = {
  String: string;
};

export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> =
  | ResolverFn<TResult, TParent, TContext, TArgs>
  | ResolverWithResolve<TResult, TParent, TContext, TArgs>;

export type ResolverWithResolve<TResult, TParent, TContext, TArgs> = {
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type MutationResolvers<
  ContextType = any,
  ParentType extends ResolversParentTypes['Mutation'] = ResolversParentTypes['Mutation']
> = {
  echoString?: Resolver<
    Maybe<ResolversTypes['String']>,
    ParentType,
    ContextType,
    RequireFields<MutationEchoStringArgs, 'str'>
  >;
};
```

**Comment by Tobbe** [comment]
> The two declarations _are_ actually different:
> 
> * _a_ is **two** functions that either always return 1, or always return 2
> * _b_ is a **single** function that returns either 1 or 2
> 
> _a_ is not equal to _b_ because _b_ will return 1 or 2 from a single source, and _a_ expects consistently 1 or 2 from different sources respectively.

Thanks for this explanation. Reading it a couple of times and it finally makes sense 🙂 

calling `a()` multiple times will either *always* return 1 or *always* return 2
calling `b()` multiple times and you can't know from one time to the next if it'll return 1 or 2

**Comment by dac09** [comment]
@n1ru4l so I found out later that it only happens when you customise the ResolverFn. 

So to reuse your playground, this is the change I had to make to reproduce:

```diff
export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
- ) => Promise<TResult> | TResult;
+ ) => TResult extends PromiseLike<infer TResultAwaited>
+     ? TResult
+     : Promise<TResult> | TResult
```

And you'll see the error in the echoString resolver: [TS Playground](https://www.typescriptlang.org/play?target=7#code/JYWwDg9gTgLgBAbzgcSgQzACwIoBkBKApgM4QA2AboQJIB2AZhHAL5z1QQhwDkA5ulgCOZbgG4AUIQAekWHBgBPMITgBZNAoBGhADwAVAHxwAvHD1wAPnFoBXMmQnTZ8Rcrh0wNmOq27DJtQ1tfQNHGWgXJRUAUSk0AGMYfThpGEJaABNiRDgAbQBrQgUALjhiGChgWl4AXVKbWnzaCAB3WhYjUyRcgGk4KrhChQh6MzqzXpqWMOd5KMDCgHkwGGAIWjQyfQAaOD7U9KzBopGzTrhFkGAkvV2eowAyHNyAZRtNHqL+9p6agH5Sj5gnpXu9PgoakZmDMInM3OpCkC-HcUlI0plskNTv5TJdrjs9o9nm8Pl8Br9AUE-KDSRCoTC5K4VERBDZgFBCAAxYCEMhZAn7NGHTEnUY4i5XG53IndAAK3z2NQAtAC4AA5dZquxkNCaMjU2WQ6biAD0ACozXAAIL2OCaNlkGBKgZoTJweI2cqcMrxTZoKDEXYgDDKDLyJgwTCEdlwBIwGybOAUTY2EhwM0myThRnzF6+nUBgIIcRwdwAEVK5Uq1QkpZeFSqvErDZrJbgACEIORCK7Spou-rXbX3LQYKVbCBtFBh5yyBA0GPrDZJ4Rp+JoeIs7MmWovAu1u0um2APrHpkbECEVXcVR71brMRt-MenVpN4gUp5v0B3LcWfzmBuBqYdCHiTAIHrateFVJEdC-AtiF-SDGyA0J1wkLdYR3W8YH3dYAGFNhfBdCHfK0oF4bIj1LKpPEXd8PC8CQN0wnN4TvA9ojAiCW14cjKKLNsq0-fN-UQ7hkOqIDmIwpwsPmbBUygBRBNLU9zzQS9r0U1cFEfUso3sCARO-cTJN4aT0M3OS2JUBjaDo1TYxMhDf3-BdLNLTQXLEty5w84CrNYyI3CIUhKFXPQogAdQEZQoBCAJZQ4K5iD8IwrD0WTsxC5kSHIKgoGi65MDCgq-DCuwYF2PRZX9dJqrMfD1jSNEav44hzmLUsOXCqhSjKiKoE5Wh9Eqx0arqjlRxq5rR1SdqKM6mTgrhPK+tXMaSCqyb6tHItmFmlrUgOxaBK6ZhOjbKxBsKkatuIHazCmhqjvmtqzA6gxrrgW7V2KyM-oep7ar2xq9Dm1rwa+7Lt3mP7htGvRxvBl6Zqa46Pr0L6AgACjbMAwdKUHpuqtt-Uo4mOu2J9McXCG6ZpmiGGMlABBwAh8oiuhGHEABKEwjGR7bHVRdEjmSzhgDS3BgEKHQqnoVczBRq0WjQa5CAyb7S11uA-hVkWYDbPXSkl1KKqNjLDcex1NxNE0zEwaX+myYhQGAAtw3kKM4HWFQWhUOME3sFT1f2mAmE9QhTUd7RfWjuBE7ASpiGDbhsmDMBQzW4hY9ROHQq5u6kZR3bSbeqGzs6vH8710tCdJ4m0bJh369LCniCppaabb9v4jp4nIYWuv68V1nUAwDm-p5iBR9LAXjCFlGxeFOBzelwhZflxXleF22YDVjW0m1+fdYNje0p0KbVk2YHHSPzXte+vv67NlLN+v-1b62feqoMa2N9gB3z-o6NCq0dwkmIPESoKwDxQJgcAbQ91QGozBpXBan0lrnHxg3Imz10HkyWt3SiTN3SDwxu9MmzNGClEnlgPAM8Wb80FtaYgChaDxGoGkdAepLYH0AR-K+Vp2GcO4auXU+p74wAAbDeSbgEGwPvLQP6KCy4EIrpQquWDKI4IJvgkmr0iGUx0YGWmVCh6MzbOPOh7NGHFxoMwxey8jaWHXkI-h-85FyCqDw+gCQ7LvGgUo+BQTEFTkWJoAAVqBG46i9DglXhiMovFy6vS0Zg7G2DEBCTCZUbQn48nADgesRRSCuSjW6EMBUCSijjFQSwNJ6MGZUOrmhHqDjVRlJKSohxaija7CqWSdotSITExXodDJWMYbrmsjlb4fiAlwG6cohGkSYmJGkU08Gw9pnZO6mUIpBTllFJ6WU5Bo1XQKG2RgvZujhy9XKoUzQwTimrL6aXAZsZaDXKmdDbBzE5mF0CS8xBPT1mxK2WYRJBxklVkbDcv5bSTA-RWaE0F+TVwQs2agmq4JEUtO0Vk3RqLTnvI2lAbFcSvmGOabs-59ygXyJBa8npCMoWjKSUceF1RtmnT+fy4lVFECXRRaWKwuNcYADoZWd1KFc3INRnEnIxW8g8VKOX4o0ekwlmSvp81Jaq8F0TIW4uhUUAl9K2neNymYKIqikZRWUIGbV+0Lq3PgBdPReCm6uuoeQixSLrEs1sVPexG1Z4sKXoEXw+gnUkEEVLK+sE9Dxs6uAmytrqDEHjYsegCMUGCvpQdb1ftonEzIQPQNuq2rBtoWzMNnMI1ONYf2bsro3GX10G2wctAM3zJ3GqVIBakY4OVV2kINq1pwDLOyWJwAqAjukYKluRa6aCo6iW2upZaCpFKEOtES7UEGDIY3BqzdCEd2IaYytFCa3+psQ2hhTbyqRuVQ0qwE7j0YXNJadQ2dGx2kIDAQO6RYy2jQMmT2kiVDQKjMGXO3ywyRhUI8oa2QmTZAzBA+GDiAxpqcp2dttABp4fjbFEMm14K+W4ER3tqEZz+UXAjcjcUqOiR-H+JjDG2w4TwiR36ZGYpsYSggS6w4dLKVIxS1jlHRPibbOZaT5UoCyezux0ySFeI8brMuRi9E9MOSYkFX9gQAPVCAyBwgYHNhkFjFBnUfCfTwbQIh10yHfZocKtkM9o4sOZkzdOhGxAW4Eeoh2AcPYBPUc43RqLnk4DuXohx8SSWEt8eUaUMTEmlIlBFcOJTyyUtaaggl+ydFCkgH0ytHD7FcLkpU8QHQbZ6XxoCFcshoX5iwqOMFrrzrfwZYPEBAIfWwZpsGxxB8NRxBdSfEROwJF3yqnZSbQTFKc1RFS9xmoZDSz9cIHtuArWohHZZGyDk3JeT8iGwRBbr5SLLmpjwWiXhuA6zgO0lI3FzIrbw81vWsFgsTYktpyER2DtHZO8oM7hBWRzqu3yJrt3aBcXAuZZ7GcKjvbbGhFigWdySYUMFgHx26ZtdMB1tsB2uXZDG6TEHRORumHpw1RnuWgKzacoZOcf2KU6GB1tkrKFdvr3G6dsnVD4146nTuEn0OVCU5+XN0sKOYJTd6RtnQCuvtE9VET+X5Oogy83LHB25uLeW6t9bq3pvxBVvKGtMshB6DCvNE+jm6ZHYAAM2yE9yzkvWPPWbmQAIRtmYJuZmjlyteED7rNApQkvh71t5RLTGU8sCj9OlH8fSygXR7xXGwllm8VD3zT8Ze1vPkW2+ZcuNXsGaq0ZmA5ek8Z4j+Ib3GEHfwC86uLu63GtOSJ1ltbwfSi42VdwFo0A+TcDIYdXjGux96wLzxKCk-jy7E7sqg5es256Gdm7cCdgwwJzSj7FQq4OBQANmt0sve2Bdnfkm3QPLeBuNsPYc46hIxSvQEyE4Cn0+zgAAAYpUABmfWdxN-AAhxXGb-MgAWV-C2eAjaXGbgbgPmYcPWDkeMKAdoRgCAXAxpave7JbZcLfHfJaPfB-OAfAmwQg2MJaKVRvKVVzAAahYMojYJbylU0FIKX1LCXw3CAA)

So whenever you try to make sure you're not accidentally wrapping a Promise (which happens with Prisma mapped types), we see this happen. Maybe I'm just going about this the wrong way?

<details>

<summary>If you're wondering why I'm even doing this... expand for details - slight tangent</summary>

I've tried to explain in the commented out ResolverFn. The gist of it is, when using mapped types (with Prisma) we need to make sure we wrap it in a Partial, otherwise we force Resolvers to return the _entire_ Prisma object, which is incorrect behaviour also. I've opened a separate issue for this in #8050

</details>

---


> The two declarations are actually different...

All of this makes sense enis thanks, but the bit I don't understand is why suddenly it changes form, when I customise the return type.

**Comment by enisdenjo** [comment]
My guess is that conditionals are expanded in sequence, one by one. If we have:
```ts
type WrapInPromiseIfNot<T> = T extends PromiseLike<any>
    ? T
    : Promise<T>

type Out = WrapInPromiseIfNot<string | Promise<number> | null>;
```

the following will happen:
1. Take `string` member
2. Is it PromiseLike?
3. It is not, wrap `Promise<string>`
4. Take `Promise<number>` member
5. Is it PromiseLike?
6. It is, return `Promise<number>`
7. Take `null` member
8. Is it PromiseLike?
9. It is not, wrap `Promise<null>`

Ultimately ending up with: `Promise<string> | Promise<number> | Promise<null>`.

**Comment by enisdenjo** [comment]
> My guess is that conditionals are expanded in sequence, one by one.

Union members are indeed evaluated one by one, the following example proves the point:
```ts
type IsString<T> = T extends string ? 'yes' : 'no';

type A = IsString<string> // "yes"
type B = IsString<number> // "no"
type C = IsString<string | number> // "yes" | "no"
```

**Comment by enisdenjo** [comment]
> When conditional types act on a generic type, they become distributive when given a union type.
> ...
> Typically, distributivity is the desired behavior. To avoid that behavior, you can surround each side of the extends keyword with square brackets.

_[TypeScript handbook](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types)_

In essence, @dac09, this is what you want:
```ts
type Post = {
    id: number;
    title: string;
    body: string;
    createdAt: Date;
    userId: number | null;
}

export type Maybe<T> = T | null

type WrapInPromiseIfNot<TResult> = [TResult] extends [PromiseLike<infer TResultAwaited>]
     ? Promise<Partial<TResultAwaited>>
     : Promise<Partial<TResult>> | Partial<TResult>

type Out = WrapInPromiseIfNot<Maybe<Post>>; // Partial<Maybe<Post>> | Promise<Partial<Maybe<Post>>>
```

**Comment by dac09** [comment]
> Union members are indeed evaluated one by one, the following example proves the point:

Thanks a bunch @enisdenjo - this is really really great, and super happy to have a concrete explanation for this. ✌️

And appreciate the links to the handbook and your explanation- you have no idea how many people I've spoken to to try and get to the bottom of this!

---

@n1ru4l It looks to me like we can probably close this issue - we still have to look into the other one in #8050 (the whole reaons this problem came up).

**Comment by dac09** [comment]
Closing this issue - confirmed that you can use prisma findUniques! 

Thanks so much @enisdenjo
