### ISSUE TITLE
Got allows a redirect to a UNIX socket 

### ISSUE THREAD

**Issue by tcetin** [dotansimha/graphql-code-generator#8063]
### Describe the bug

There is a vulnerability for the `got` npm dependency.

![image](https://user-images.githubusercontent.com/5071753/177975135-b03df917-d89c-484b-bb36-26d895a95a67.png)

Is there a solution to fix this?

### Your Example Website or App

testing locally

### Steps to Reproduce the Bug or Issue

1- Install `@graphql-codegen/cli` by `yarn add -D @graphql-codegen/cli`
2- run `yarn audit` command

### Expected behavior

It shouldn't has any vulnerability with dependencies.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/5071753/177975589-222d2ad5-015c-4ade-99d1-00354c739a81.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by Obiwan1995** [comment]
`latest-version` dependency has already been removed, so I believe fix should be available soon.
https://github.com/dotansimha/graphql-code-generator/commit/e7870ac28ce3a4d23a4c8f561382a5679090d3d0

**Comment by ardatan** [comment]
Until it's released, you can use alpha versions;
https://github.com/dotansimha/graphql-code-generator/pull/8035#issuecomment-1175122198
