### ISSUE TITLE
Add new flag to `emitLegacyCommonJSImports`

### ISSUE THREAD

**Issue by saihaj** [dotansimha/graphql-code-generator#8067]
Add a new flag to disable adding `.js ` extension by default which users can enable as need be. 

Related: https://github.com/dotansimha/graphql-code-generator/issues/8065

**Comment by n1ru4l** [comment]
https://github.com/dotansimha/graphql-code-generator/pull/8068

**Comment by saihaj** [comment]
test here https://github.com/dotansimha/graphql-code-generator/pull/8077#issuecomment-1180705351

**Comment by n1ru4l** [comment]
@kamilkisiela you can use this alpha release
