### ISSUE TITLE
Generate MutationFn typings for each Mutation

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#807]
This is very common when MutationFn is going to be passed down, to actually create such typings manually as you can see.
It causes a lot of unnecessary imports and clutter when it can be actually generated.
![screenshot 2018-11-07 at 22 28 21](https://user-images.githubusercontent.com/3940079/48162152-a5f85d00-e2dc-11e8-9b5a-916dbe17cf57.png)

Maybe also makes sense to generate such typings for `refetch` and `fetchMore` functions that are often thrown to the children as props. Or maybe injected to the wrapped component through `props`?

**Comment by ardatan** [comment]
I think MutateProps already does that. This PR generates MutateProps and DataProps, so you can add these to your React.Component declaration like
`React.Component<MyProps && CreateMessageProps>`

**Comment by RIP21** [comment]
@ardatan it's rather painful to do like that. Especially if you would like to rename prop for example, or pass only partially etc. It's more for nested components than to the wrapped component itself.

**Comment by ardatan** [comment]
Added with #819

**Comment by dotansimha** [comment]
Available in 0.14.0 🎉
