### ISSUE TITLE
`init` command improvements

### ISSUE THREAD

**Issue by charlypoly** [dotansimha/graphql-code-generator#8074]
- init command does not work with `npx` (_to be confirmed_)
- we should find a simpler what to make it work with `yarn`
  - right now, to use `init`, you need to add codegen as a `package.json`’s scripts, which is not handy  
- update the documentation to better showcase this wizard command

**Comment by saihaj** [comment]
> we should find a simpler what to make it work with yarn

that seems like a `yarn` limitation: https://github.com/yarnpkg/yarn/issues/3937#issuecomment-499155481

**Comment by saihaj** [comment]
> So for some reason it isn't available 🤔 ![image](https://user-images.githubusercontent.com/44710980/178351628-fef55759-1761-433e-a41b-70e498c802ad.png)
> 
> Somehow it is picking up`0.4.0`

So looks like it goes to https://www.npmjs.com/package/graphql-codegen if we do `npx graphql-codegen`

**Comment by saihaj** [comment]
so if you do `npx graphql-code-generator init` it will work as expected 
![image](https://user-images.githubusercontent.com/44710980/178363292-ae0d7a89-04c9-48dd-9fc5-c22a2a58930e.png)

**Comment by charlypoly** [comment]
Issue solved, let's keep track of the transfer of `graphql-codegen` in https://github.com/dotansimha/graphql-code-generator/issues/8108
