### ISSUE TITLE
get back `npx graphql-codegen` ownership

### ISSUE THREAD

**Issue by charlypoly** [dotansimha/graphql-code-generator#8108]
`graphql-codegen` is currently owned by Apollo (deprecated package and project)

We are in the process of potentially transferring ownership.

**Comment by charlypoly** [comment]
@saihaj once this package is transferred, we could achieve a similar experience to `npx` with `yarn`:

```
yarn create graphql-codegen init
```

cf: https://classic.yarnpkg.com/lang/en/docs/cli/create/

For example, this is how CRA exposes it with `yarn`: https://create-react-app.dev/docs/getting-started#yarn

**Comment by ardatan** [comment]
I think `yarn create` needs a name with `create-` prefix.

**Comment by charlypoly** [comment]
> I think `yarn create` needs a name with `create-` prefix.

Good catch!

Then @saihaj, we can already create a `create-codegen-config` package? 👀

**Comment by charlypoly** [comment]
Closing we got answer on ownership of the current package, we will move forward with `graphql-code-generator`.
