### ISSUE TITLE
--clientSchema and --schema don't recognize .graphqls as graphql document

### ISSUE THREAD

**Issue by wesselvdv** [dotansimha/graphql-code-generator#811]
**Describe the bug**
gql-gen tries to load up .graphqls document as a javascript file.

```
Loading GraphQL schema object, text, ast, or introspection json from JavaScript ES6 export: ./src/app/graphql/schema.graphqls
```

**To Reproduce**
1. Use a valid graphql schema document as .graphqls file.
2. Run the following command: `gql-gen --watch --schema 'src/**/*.graphqls' --template graphql-codegen-apollo-angular-template --out './src/app/graphql/queries.ts' './src/**/*.graphql'`

**Expected behavior**
Expected valid types to be generated in queries.ts

**Environment:**
 - OS: alpine
 - Codegen: 0.13.0
 - Node: 10.11

**Additional context**

**Comment by dotansimha** [comment]
Fixed in 0.14.0 🎉
