### ISSUE TITLE
adding suspense for typescript-react-apollo

### ISSUE THREAD

**Issue by haouarihk** [dotansimha/graphql-code-generator#8111]
**Is your feature request related to a problem? Please describe.**
I'm frustrated of the idea of choosing between code generated with components, and make them myself and get the suspense feature,

**Describe the solution you'd like**
I want a plugin(if not add it as a config for the other one), to allow me to opt into suspense mode,

**Describe alternatives you've considered**
I tried making a plugin for the suspense thingy using the use-suspense-query library,
but I failed, first there's no way to run the plugin in last(i used fs and regex to replace Apollo.useQuery with useSuspenseQuery).
then I found out that use-suspense-query doesn't have full support for typescript (i ran the script separately).

**Additional context**
I can't develop a website knowing that I will have to change a ton of stuff to get suspense working in the future.

**Comment by david-morris** [comment]
Is this still unsolved?  useSuspenseQuery is stable now.

**Comment by fforres** [comment]
Just for googling / search purposes, there is support now as of version `4.1.0` 

https://github.com/dotansimha/graphql-code-generator-community/issues/388 
https://github.com/dotansimha/graphql-code-generator-community/pull/392

**Comment by Urigo** [comment]
Thanks @fforres closing this issue
Also I'm adding that the recommend way to use Codegen with React and Apollo client is `client-preset` over `typescript-react-apollo`
