### ISSUE TITLE
react-query v4 upgrade breaks typescript-react-query

### ISSUE THREAD

**Issue by Zerebokep** [dotansimha/graphql-code-generator#8116]
### Describe the bug

react-query v4 has been released and the package has been renamed to '@tanstack/react-query', this breaks the autogenerated code, because it imports from 'react-query'

UseQueryOptions signature also seems to have been changed:

<img width="906" alt="Screenshot" src="https://user-images.githubusercontent.com/15731988/179963756-f467dd9d-35e9-4019-841e-e3f3004b3add.png">

### Your Example Website or App

https://github.com/tanstack/query

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by robin31** [comment]
To manually fix until it is patched:

1. Update first line to `import { useQuery, UseQueryOptions } from '@tanstack/react-query';`
2. for all the generated hooks (end of file) change the option type to:
```
Omit<UseQueryOptions<!!!ACTUAL_QUERY_TYPE_HERE!!!, TError, TData>,'queryKey' | 'queryFn' | 'initialData'>
  ```

**Comment by charlypoly** [comment]
Hi @Zerebokep!

Thanks to @marocchino, a new version of `@graphql-codegen/typescript-react-query` has been published to support react-query v4: `@graphql-codegen/typescript-react-query@4.0.0` 📦
