### ISSUE TITLE
Got a duplicate identifier issue

### ISSUE THREAD

**Issue by MatteoGauthier** [dotansimha/graphql-code-generator#8123]
### Describe the bug

The graphql codegen generate duplicate identifier. cf the codesandbox

```

export type NavigationItemsQueryVariables = Exact<{ [key: string]: never; }>;


export type NavigationItemsQuery = { __typename?: 'Query', homePage?: { __typename?: 'HomePage', id: string, navigation: Array<{ __typename?: 'NavigationItem', id: string, slug?: string | null, title?: string | null }> } | null };


      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {
    "HomePageNavigationItems": [
      "NavigationItem"
    ],
    "Node": [
      "Article",
      "Asset",
      "FieldOfWork",
      "HomePage",
      "NavigationItem",
      "ScheduledOperation",
      "ScheduledRelease",
      "User"
    ],
    "ScheduledOperationAffectedDocument": [
      "Article",
      "Asset",
      "FieldOfWork",
      "HomePage",
      "NavigationItem"
    ]
  }
};
      export default result;
    
export type NavigationItemsQueryVariables = Exact<{ [key: string]: never; }>;


export type NavigationItemsQuery = { __typename?: 'Query', homePage?: { __typename?: 'HomePage', id: string, navigation: Array<{ __typename?: 'NavigationItem', id: string, slug?: string | null, title?: string | null }> } | null };

```

### Your Example Website or App

https://stackblitz.com/edit/github-mvhfsr?file=graphql/generated/index.ts

### Steps to Reproduce the Bug or Issue

1. Run `yarn codegen`
2. Check the `graphql/generated/index.ts` file

### Expected behavior

No duplicate identifier

### Platform

- OS: MacOS
- NodeJS: v16.13.2
- `graphql` 16.5.0
```
    "@graphql-codegen/cli": "2.9.1",
    "@graphql-codegen/fragment-matcher": "3.3.0",
    "@graphql-codegen/introspection": "2.2.0",
    "@graphql-codegen/typescript": "2.7.2",
    "@graphql-codegen/typescript-graphql-request": "^4.5.2",
    "@graphql-codegen/typescript-operations": "2.5.2",
    "@graphql-codegen/typescript-react-apollo": "3.3.2",
    "@types/node": "^18.0.6",
    "@types/react": "^18.0.15",
```

### Codegen Config File

overwrite: true
schema: "https://api-eu-central-1.hygraph.com/v2/cl335cxsw434p01z87rv1ba3t/master"
documents: "graphql/queries/*.{ts,tsx,gql,graphql}"
generates:
  ./graphql/generated/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - fragment-matcher
      - typescript-operations
      - typescript-graphql-request
config:
      namingConvention:
        enumValues: change-case-all#titleCase

**Comment by KenzoBenzo** [comment]
I get the same issue on trying to configure things. It seems the culprit is `typescript-graphql-request` although I've not gotten any further in figuring out why 🤔

**Comment by TrevorDMartin** [comment]
I get the same issue coming from the `typescript` plugin

**Comment by nleborgne** [comment]
I encountered the same issue here, with plugins `typescript`, `typescript-operations` and `typescript-urql`

**Comment by RomanBaiocco** [comment]
I'm running into this issue as well, but it only happens when I use a `codegen.ts` file as my config.

With this as my config, I run into the duplicate identifier issue if _any_ of those plugins are present.
```
// codegen.ts
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: 'schema.graphql',
  documents: ["app/javascript/**/*", "!app/javascript/calendar_app/**/*"],
  generates: {
    "app/javascript/generated/graphql": {
      preset: "client",
      plugins: ['typescript', 'typescript-operations', 'typescript-react-apollo'],
    },
  }
};

export default config;
```

Whereas if I use this `codegen.yml` instead, there are no duplicate identifiers
```
# codegen.yml
overwrite: true
schema: "schema.graphql"
documents: ["app/javascript/**/*", "!app/javascript/calendar_app/**/*"]
generates:
  app/javascript/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```

**Comment by ardatan** [comment]
Configurations are not the same here. In TS file, you have both `client` preset and plugins defined while YAML only has plugins. Could you try TS config without preset?

**Comment by RomanBaiocco** [comment]
@ardatan Thank you so much for the response! I'll probably end up removing the client preset. Would you be able to elaborate a bit more on what change I need to make to the TS config?

**Comment by ardatan** [comment]
@RomanBaiocco you need to add ".tsx" extension in order to use react-apollo plugi.

**Comment by charlypoly** [comment]
> @RomanBaiocco You get `duplicate` error because `client` preset is defined with plugins. You get `validation` error because you don't have `tsx` extension as output in TS Config.

This issue won't be reproducible with newer version of codegen that raises an error when `plugins` are listed along with `preset: "client"`

**Comment by melMass** [comment]
> This issue won't be reproducible with newer version of codegen that raises an error when `plugins` are listed along with `preset: "client"`

Still happening

**Comment by marcelorubini** [comment]
Same here, but i'm not using _preset_ configuration along with plugins
**This began to be an issue about 8 days ago.**

> error on build

```
./types/generated/subgraph.ts:906:3
--
09:15:15.599 | Type error: Duplicate identifier 'ExecutorAddress'.
09:15:15.599 |  
09:15:15.599 | 904 \| export enum TransactionExecution_OrderBy {
09:15:15.599 | 905 \|   Executor = 'executor',
09:15:15.599 | > 906 \|   ExecutorAddress = 'executorAddress',
09:15:15.599 | \|   ^
09:15:15.599 | 907 \|   ExecutorAddress = 'executor__address',
09:15:15.599 | 908 \|   ExecutorBridgeType = 'executor__bridgeType',
09:15:15.599 | 909 \|   ExecutorId = 'executor__id',
```

> generated file
```
export enum TransactionExecution_OrderBy {
  Executor = 'executor',
  ExecutorAddress = 'executorAddress',
  ExecutorAddress = 'executor__address',
  ExecutorBridgeType = 'executor__bridgeType',
  ...
}
```

```
export enum TransactionValidation_OrderBy {
  ...
  Validator = 'validator',
  ValidatorAddress = 'validatorAddress',
  ValidatorAddress = 'validator__address',
}
```

> source entities
```
type TransactionValidation @entity {
  id: ID!
  transaction: Transaction!
  transactionHash: Bytes
  validator: Validator!
  validatorAddress: Bytes
  timestamp: BigInt
}

type TransactionExecution @entity {
  id: ID!
  transaction: Transaction!
  transactionHash: Bytes
  executor: Validator
  executorAddress: Bytes
  timestamp: BigInt
}
```

>  config.js
```
module.exports = {
  overwrite: true,
  schema: schemas,
  documents: 'src/queries/**/*.ts',
  generates: {
    [codeGenOutDir]: {
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-graphql-request',
        'plugin-typescript-swr',
      ],
    },
  },
  config: {
    rawRequest: false,
    autogenSWRKey: true,
  },
}
```

**Comment by tashigeekyants** [comment]
I am getting same, can anyone check what was the issue I am using codegen along with hasura
```codegen.ts```.  
```import yml from 'yaml';
import type { CodegenConfig } from '@graphql-codegen/cli';
import { writeFileSync } from 'fs';
import dotenv from 'dotenv';
dotenv.config();

const config: CodegenConfig = {
    overwrite: true,
    schema: [
        {
            'http://localhost/graphql': {
                headers: {
                    'x-hasura-admin-secret': process.env.HASURA_ADMIN_SECRET || '',
                },
            },
        },
    ],
    documents: ['src/queries/*.ts'],
    generates: {
        'src/codegen/hasura/generated/': {
            preset: 'client-preset',
            plugins: ['typescript'],
        },
    },
};

writeFileSync('src/codegen/hasura/codegen.yml', yml.stringify(config));

export default config;   
```

2. ```codegen.yml```

```overwrite: true
schema:
  - http://localhost/graphql:
      headers:
        x-hasura-admin-secret: sadsadasdsad
documents:
  - src/queries/*.ts
generates:
  src/codegen/hasura/generated/:
    preset: client
    plugins:
      - typescript
```

**Comment by luizakp** [comment]
Using [`futureProofEnums` ](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#futureproofenums)worked for me

**Comment by userAugustos** [comment]
> @ardatan Thank you so much for the response! I'll remove the client preset and see if that fixes it
> 
> Edit: It did! You're amazing, thank you again!
> 
> For anyone who runs into this in the future, in `codegen.ts` I changed
> 
> ```
> generates: {
>     'app/javascript/generated/graphql': {
>       preset: 'client',
>       plugins: ['typescript', 'typescript-operations', 'typescript-react-apollo'],
>     },
>   }
> ```
> 
> to
> 
> ```
> generates: {
>   "app/javascript/generated/graphql.tsx": {
>     plugins: ['typescript', 'typescript-operations', 'typescript-react-apollo'],
>   },
> }
> ```

But how u guys using without the ` preset: 'client',`, her if i run without it in gives an error: `Command failed with exit code 1.`

**Comment by Loque-** [comment]
I was getting this error also and resolved it after trying futureProofEnums (thank you @luizakp!).  In-case it is useful, our config looks a bit like this;

```
const config: CodegenConfig = {
  overwrite: true,
  schema: [
    {
      'https://graphql.datocms.com/': {
        headers: {
          // ... 
        },
      },
    },
  ],
  generates: {
    'src/generated/graphql.ts': {
      plugins: ['typescript'],
      config: {
        enumsAsTypes: true,
        futureProofEnums: true,
      },
    },
    './graphql.schema.json': {
      plugins: ['introspection'],
    },
  },
}
```

**Comment by llanginger** [comment]
I'm running into a similar issue, I'd love some help. I'll note that the `codegen.ts` below works as expected if I have no plugins at all.

With my config as such (the way I would expect it to just -work-):

```const config: CodegenConfig = {
  overwrite: true,
  schema: [
    {
      'myurl': {
        headers: {
          Authorization: "Bearer " + TOKEN,
          ["x-correlation-id"]: uuidv4()
        }
      }
    }
  ],
  documents: ['src/graphql/testQuery/*.{ts,tsx}'],
  generates: {
    './src/__generated__/': {
      preset: 'client',
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-react-apollo'
      ],
      config: {
        withHooks: true,
        withComponent: false,
        futureProofEnums: true
      },
      presetConfig: {
        gqlTagName: 'gql',
        fragmentMasking: false,
      },
    },
  },
  ignoreNoDocuments: true,
}
export default config
```

I get what appears to be 100% duplication of the schema. If I remove the "typescript" plugin, I only get duplication of generated code related to the hooks I am trying to generate.

If I remove the `preset: client` option, I get this error:

```✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to ./src/__generated__/
    ✔ Load GraphQL schemas
    ✔ Load GraphQL documents
    ✖ Plugin "typescript-react-apollo" validation failed:
      Plugin "typescript-react-apollo" requires extension to be ".ts" or ".tsx"!
```

I see this suggestion above to "...add ".tsx" extension in order to use react-apollo plugin." - that sounds promising but I have no idea what that means in practical terms.

In case it's relevant, this is my project's tsconfig:

```{
  "compilerOptions": {
    "outDir": "./dist/",
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "baseUrl": "./src",
    "sourceMap": true,
    "preserveConstEnums": true,
    "types": [
      "jest"
    ],
  },
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "node_modules",
    "build",
  ],
}
```

Any help would be greatly appreciated!

**Comment by jb-1980** [comment]
@llanginger, you need to not have the following in your plugins array: `typescript`, `typescript-operations` and `typescript-react-apollo`. So you config should look like
```js
const config = {
overwrite: true,
  schema: [
    {
      'myurl': {
        headers: {
          Authorization: "Bearer " + TOKEN,
          ["x-correlation-id"]: uuidv4()
        }
      }
    }
  ],
  documents: ['src/graphql/testQuery/*.{ts,tsx}'],
  generates: {
    './src/__generated__/': {
      preset: 'client',
      plugins: [
      // don't need to add plugins when using the client preset
       ],
      config: {
        withHooks: true,
        withComponent: false,
        futureProofEnums: true
      },
      presetConfig: {
        gqlTagName: 'gql',
        fragmentMasking: false,
      },
    },
  },
  ignoreNoDocuments: true,
}
export default config

**Comment by llanginger** [comment]
Hmm, is the functionality to generate the hooks (`useSomeQuery`) available as part of the client preset? If so I completely missed that.

**Comment by jb-1980** [comment]
@llanginger, I misread your original post. Uhm, I think the preset will write to a directory, while the `typescript-react-apollo` wants to write to a file. So if you remove the preset, you have to change `generates` key to a file name instead of a directory, i.e. `./src/__generated__/` needs to become something like `./src/__generated__/generated-hooks.ts`

**Comment by jimjamdev** [comment]
I'm still getting duplicate documents.

codegen
```import { CodegenConfig } from '@graphql-codegen/cli';

const url = process.env.HASURA_GRAPHQL_URL as string;
const apiKey = process.env.HASURA_GRAPHQL_ADMIN_SECRET as string;

const config: CodegenConfig = {
	overwrite: true,
	schema: [
		{
			[url]: {
				headers: {
					'x-hasura-admin-secret': apiKey,
				},
			},
		},
	],
	config: {
		//skipTypename: true,
		//enumsAsTypes: true,
		// dedupeFragments: true,
		/*scalars: {
			numeric: 'number',
		},*/
	},
	documents: './src/graphql/**/*.{ts,tsx,graphql}',
	ignoreNoDocuments: true,
	generates: {
		'./src/lib/gql/': {
			preset: 'client',
			config: {
				withHooks: true,
				futureProofEnums: true,
			},
			plugins: [],
		},
		'./schema.graphql.json': {
			plugins: ['introspection'],
		},
	},
};

export default config;
```

I have a simple list:
```
import { graphqlClient } from '@/lib/graphql-client';
import { GetOrganisationsDocument } from '@/lib/gql/graphql';

// export const revalidate = 'no-cache';

export async function OrganisationsList() {
	const organisations = await graphqlClient.request(GetOrganisationsDocument, {
		limit: 100,
		offset: 0,
	});

	return (
		<ul>
			{organisations?.organisations?.map((organisation) => (
				<li key={organisation?.id}>
					<span className="font-bold">{organisation?.name}</span>
					<ul>
						{organisation?.users?.map((user) => (
							<li key={user?.id}>
								{user.firstName} {user?.lastName}
							</li>
						))}
					</ul>
				</li>
			))}
		</ul>
	);
}

```

and a graphql file in src/graphql/organisations.graphql

```

query GetOrganisations(
	$limit: Int
	$offset: Int
	$where: organisations_bool_exp
	$order_by: [organisations_order_by!]
	$distinct_on: [organisations_select_column!]
) @cached(ttl: 60) {
	organisations(
		limit: $limit
		offset: $offset
		where: $where
		order_by: $order_by
		distinct_on: $distinct_on
	) {
		id
		name
		users {
			id
			firstName
			lastName
		}
	}
}

mutation updateOrganisation($id: Int!, $name: String!) {
	update_organisations(where: { id: { _eq: $id } }, _set: { name: $name }) {
		returning {
			id
			name
			users {
				id
				firstName
				lastName
			}
		}
	}
}


mutation CreateOrganisation($name: String!) {
	insert_organisations_one(object: { name: $name }) {
		id
		name
		users {
			id
			firstName
			lastName
		}
	}
}

mutation UpdateOrganisation($id: Int!) {
	update_organisations_by_pk( pk_columns: { id: $id }) {
		id
		name
		users {
			id
			firstName
			lastName
		}
	}
}

mutation DeleteOrganisation($id: Int!) {
	delete_organisations_by_pk(id: $id) {
		id
		name
		users {
			id
			firstName
			lastName
		}
	}
}

```
But it's still generating duplicate documents :/

**Comment by parazitl2** [comment]
> @llanginger, I misread your original post. Uhm, I think the preset will write to a directory, while the `typescript-react-apollo` wants to write to a file. So if you remove the preset, you have to change `generates` key to a file name instead of a directory, i.e. `./src/__generated__/` needs to become something like `./src/__generated__/generated-hooks.ts`

This approach does not allow to keep the preset features, because `typescript-react-apollo` writes the code dependent from the `graphql.ts` generated by the 'client' preset.

I want to keep the functionality of the preset (with fragment masking, gpl and index files) and I need an apollo plugin. So, is it possible?

**Comment by morteza-gho** [comment]
> The preset: "client" is not meant to be used in combination with other plugins. You must use either the client-preset or typescript-urql-plugin which provides 2 different ways to get typed GraphQL Operations.

https://stackoverflow.com/a/74137167/2690160

**Comment by Qonditive** [comment]
I got the same issues with the following config:

`ignoreNoDocuments: true,
    hooks: {
        afterAllFileWrite: ['prettier --write']
    },
    documents: ['src/graphql/data/**/*.ts'],
    schema: {
        [API_URL]: {
            headers: {
                'key': API_KEY
            }
        }
    },
    generates: {
        './src/graphql/codegen/': {
            preset: 'client',
            plugins: [],
            config: {
                useTypeImports: true,
                documentMode: 'string',
                namingConvention: 'keep'
            },
            presetConfig: {
                fragmentMasking: {
                    unmaskFunctionName: 'unmaskFragment'
                }
            },
            documentTransforms: [addTypenameSelectionDocumentTransform]
        }
    }`

The output is:

`
export type Explainers = {
....
}

export type Explainers = Explainers & {
....
}
`

I solved it by adding namingConvention: 'keep' in the config and the second type is now:

`
export type explainers = Explainers & {
...
}
`

**Comment by henrybabbage** [comment]
My issue is that I need to keep the graphql codegen configured with "client" preset otherwise it does not generate the getSdk client function for graphql request.

How can I avoid duplication while also keeping the config as it is below?

```
generates: {
        "generated/": {
            preset: "client",
            plugins: ['typescript-graphql-request', 'typescript-operations']
        }
    }
```

**Comment by andrewpeapod** [comment]
I'm having the same issue with the following code:

```ts
const config: CodegenConfig = {
  schema: [
    'src/types/**.gql',
    'src/inputs/*.gql',
    'src/queries/*.gql',
    'src/mutations/*.gql',
  ],
  generates: {
    './src/generated/gql-types.ts': {
      plugins: ['typescript', 'typescript-resolvers'],
      config: {
        enumsAsTypes: true,
        futureProofEnums: true,
      },
    },
  },
  watch: true
}
```

**Comment by adriangalilea** [comment]
@Qonditive  That worked, many thanks, my `codegen.ts` is quite complex but may help someone else as a reference:

```diff
import type { CodegenConfig } from "@graphql-codegen/cli"
+ import { addTypenameSelectionDocumentTransform } from "@graphql-codegen/client-preset"
import dotenv from "dotenv"

dotenv.config({ path: ".env.local" })

const config: CodegenConfig = {
  schema: process.env.DGRAPH_GRAPHQL_ENDPOINT,
  documents: [
    "db/operations/**/*.tsx",
    "db/operations/**/*.ts",
    "components/**/*.tsx",
    "components/**/*.ts",
  ],
  watch: true,
  ignoreNoDocuments: true,
+   hooks: {
+     afterAllFileWrite: ["prettier --write"],
+   },
  generates: {
    "./db/generated-graphql/": {
      preset: "client",
      presetConfig: {
        fragmentMasking: { unmaskFunctionName: "getFragmentData" },
      },
      config: {
+        useTypeImports: true,
        documentMode: "string",
+        namingConvention: "keep",
        scalars: {
          DateTime: "Date",
          Int64: "string",
        },
        defaultScalarType: "unknown",
        avoidOptionals: true,
        strictScalars: true,
      },
+      documentTransforms: [addTypenameSelectionDocumentTransform],
    },
    "./db/generated-graphql/types.ts": {
      plugins: ["typescript", "typescript-operations"],
      config: {
        enumsAsTypes: false,
        futureProofEnums: true,
        skipTypename: true,
        scalars: {
          DateTime: "Date",
          Int64: "string",
        },
        defaultScalarType: "unknown",
        avoidOptionals: true,
        strictScalars: true,
+        namingConvention: "keep",
      },
    },
    "./db/schema.graphql": {
      plugins: ["schema-ast"],
      config: {
        includeDirectives: true,
      },
    },
  },
}

export default config

```
