### ISSUE TITLE
Security vulnerability in dependency `cross-undici-fetch`

### ISSUE THREAD

**Issue by GamerBene19** [dotansimha/graphql-code-generator#8132]
### Describe the bug

When your app uses `@graphql-codegen/cli` and you have dependabot alerts enabled you will get an (unresolvable) alert that `undici` prior to `v5.8.0` is insecure.

### Your Example Website or App

https://github.com/GamerBene19/gql-codegen-example

### Steps to Reproduce the Bug or Issue

1. Fork example repo
2. Go to security tab
3. Enable dependabot alerts like so: 
![image](https://user-images.githubusercontent.com/20821976/180466137-1b6b0bd9-559a-4f35-8cbc-a31ae2bfae4b.png)
4. Wait 
5. Observe following two (unresolvable) dependabot alerts: 
![image](https://user-images.githubusercontent.com/20821976/180466337-b61eca88-4ded-4414-8911-7deadcc0544f.png)

### Expected behavior

The "expected behavior" would be to not have a vulnerable version as a dependency or being able to update to a non-vulnerable version.

### Platform

- OS: Arch Linux, but should be irrelevant
- NodeJS: v17.9.0, but should be irrelevant
- `graphql` version: 16.5.0, but should be irrelevant
- `@graphql-codegen/cli` version(s): 2.9.1, very much relevant

### Additional context

As far as I can tell the (problematic) version of `undici` is a transitive dependency of `cross-undici-fetch`  from [here](https://github.com/dotansimha/graphql-code-generator/blob/01dd28efb239a9e18c615e84577dfbee30378b9d/packages/graphql-codegen-cli/package.json#L59).

A quick google search revealed that perhaps [this package](https://github.com/ardatan/whatwg-node/tree/master/packages/fetch) (which might very well just be a renamed version of the original one) is a replacement?

**Comment by charlypoly** [comment]
@GamerBene19, this vulnerability has been fixed by @gustaff-weldon and shipped in `@graphql-codegen/cli@2.10.0` 📦

**Comment by GamerBene19** [comment]
> @GamerBene19, this vulnerability has been fixed by @gustaff-weldon and shipped in `@graphql-codegen/cli@2.10.0` package

Nice! Thanks @gustaff-weldon :smile:

**Comment by Obiwan1995** [comment]
The issue is still present: `@whatwg-node/fetch` depends on `undici 5.5.1`, which is vulnerable

**Comment by GamerBene19** [comment]
Interesting... The package.json I linked above depends on 5.8.0 🤔

**Comment by charlypoly** [comment]
@ardatan could it be linked to our dependency to `@graphql-tools/apollo-engine-loader@^7.3.1` that depends on `cross-undici-fetch@^0.4.11`?:

```
"@graphql-tools/apollo-engine-loader@^7.3.1":
  version "7.3.1"
  resolved "https://registry.yarnpkg.com/@graphql-tools/apollo-engine-loader/-/apollo-engine-loader-7.3.1.tgz#535cb259fa6e0dbf1cf960e7212d58b8294bb370"
  integrity sha512-PJhX4gQeoPtR2BJFYHYVLdLYkqQHB94r9IC64GamFV+kxR+jzQYZJdDTgnFZxvpvGJ7rEgYKNjcfWS+r+CQisQ==
  dependencies:
    "@graphql-tools/utils" "8.8.0"
    cross-undici-fetch "^0.4.11"
    sync-fetch "0.4.1"
    tslib "^2.4.0"

```

**Comment by drewmendenhall** [comment]
@charlypoly FYI @whatwg/fetch also needs to include the update on a new release: https://github.com/ardatan/whatwg-node/commits/master/packages/fetch/package.json

**Comment by Dodie324** [comment]
Running into this issue in our application code as well.

**Comment by ardatan** [comment]
https://github.com/dotansimha/graphql-code-generator/issues/8012#issuecomment-1173608427
We had an issue with the latest versions of Undici and we downgraded and kept that version on purpose.
We preferred to fix this regression and ignore `npm audit` errors temporarily that are mostly unreliable in my opinion. We will update `undici` for sure but first we need strict tests to prevent future regressions caused by Undici or any other dependency we have.

Also see about `npm audit`
https://overreacted.io/npm-audit-broken-by-design/

**Comment by gustaff-weldon** [comment]
@drewmendenhall is right, I have wrongly assumed this change has been released in `@whatwg/fetch`. I should have done a better diligence. 

@ardatan is there any timeline on the release of `@whatwg/fetch` with `undici` 5.8.0?

**Comment by ardatan** [comment]
No currently we don't have any timeline because npm audit is not our priority as I already said. And I don't think Codegen as CLI would affect you with this "vulnerability".

**Comment by gustaff-weldon** [comment]
@ardatan thanks, I'm aware of `audit` deficiencies and have read Dan's article long time ago, but you must also take into account that in many companies there are certain policies related to security vulnerabilities and it is hard to dismiss them just on a "npm audit is broken" basis.

In our case, this is reported by Github on our dependency security checks, we investigate what's the scope of use of affected libs and decide on the resolution, but I would not be surprised if for many, removing the dependency on older `undici` versions will rely on your update to `@whatwg/fetch`.

**Comment by ardatan** [comment]
@gustaff-weldon If that new version is broken, we cannot update it until it gets fixed on their side. If we update it even if it is broken, then you won't be able to use the library at all. 
By the way, you are free to force your package manager to install the newer version on your side.

**Comment by gustaff-weldon** [comment]
> we cannot update it until it gets fixed on their side

I assume thy know sth is broken.

> By the way, you are free to force your package manager to install the newer version on your side.

@ardatan yup, we do that as a last resort with resolutions.

Thanks for chiming in, we have solved the issue on our side, I hope you'll be able to solve it on `@whatwg/fetch` sooner than later 🤞

**Comment by ardatan** [comment]
After hours of work, we finally figured out to make things work on our side with 5.8.0 by adding some workarounds.
https://github.com/dotansimha/graphql-code-generator/pull/8155
So this PR is merged, the new patch version will be available soon.

**Comment by ardatan** [comment]
@graphql-codegen/cli@2.11.2 has been released. It doesn't use `cross-undici-fetch` that depends on the older version of `undici`. Now it uses `@whatwg-node/fetch` which uses the latest `undici`.
https://github.com/dotansimha/graphql-code-generator/blob/master/yarn.lock#L14704

**Comment by Dodie324** [comment]
I recently upgraded to 2.11.3 but still have a dependency on an older version of `undici` via a `graphql-config`. Is this a known issue or are there any workarounds to resolve this dep vulnerability?

<img width="260" alt="Screen Shot 2022-08-01 at 11 37 19" src="https://user-images.githubusercontent.com/9405172/182186433-d7e55c3b-4cc8-4cb6-bb32-2f0f07879434.png">

**Comment by ardatan** [comment]
It seems you still have the older version of url-loader package. Those are ranged dependencies so I think they would be gone after recreating `yarn.lock` or `package-lock.json` file by removing them and running `npm install` or `yarn install`.

**Comment by Dodie324** [comment]
Thanks @ardatan . I should have done that before coming to you on this thread!

**Comment by GamerBene19** [comment]
Just for everyone's interest: I've archived my repository and will delete it in one month.
So if - for whatever reason - anyone still needs it feel free to fork.
