### ISSUE TITLE
`npx graphql-code-generator init` terminates after first wizard question

### ISSUE THREAD

**Issue by x11x** [dotansimha/graphql-code-generator#8162]
### Describe the bug

I install using pnpm as per the [instructions](https://www.graphql-code-generator.com/docs/getting-started/installation) and run `pnpm graphql-code-generator init`.
It displays the first page/question of the wizard and then immediately returns me to command prompt, not allowing me to select any items or complete the wizard.

I also tried `npx` (npm v8.15.1), it does the same thing

Exact output:
```

    Welcome to GraphQL Code Generator!
    Answer few questions and we will setup everything for you.
  
? What type of application are you building? (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
❯◯ Backend - API or server
 ◯ Application built with Angular
 ◯ Application built with React
 ◯ Application built with Stencil
 ◯ Application built with other framework or vanilla JS
```
That's as far as it gets.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

Follow the instructions on https://www.graphql-code-generator.com/docs/getting-started/installation, using the "Initialization wizard" option for configuration.

### Expected behavior

I expected the wizard to complete and configure my project.

### Platform

- OS: Linux (Fedora 35 Silverblue)
- NodeJS: 16.15.0
- `graphql` version: 16.5.0
- `@graphql-codegen/cli` version: 2.11.2
- pnpm: v7.7.0
- npm: 8.15.1
- Shell: bash 5.1.8(1)-release (x86_64-redhat-linux-gnu)
- Terminal: I tried kitty, gnome-terminal and vscode's built in terminal

### Additional context

I should note that my development environment is run inside a podman-based Linux container. (This is how Silverblue works, using its "toolbox" system). I would not expect this to be an issue, but if anyone else using a more conventional Linux/bash environment (any distro) cannot reproduce, this might be the problem.

**Comment by losandies** [comment]
Having the same issue. Saw someone suggest rolling back to an earlier version but that still didn't work for me.

**Comment by AgileMouse** [comment]
Same issue here. Have tried powershell, yarn, npm, and downgrading and still experiencing same problem.

**Comment by saihaj** [comment]
Released a patch thanks to @ohsory1324 https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Fcli%402.11.3

**Comment by AgileMouse** [comment]
Seems as if this still doesn't work via Git Bash, but can confirm init did work via powershell now.

**Comment by x11x** [comment]
Works for me now in Linux/Bash, thanks.
