### ISSUE TITLE
`graphql-codegen-esm` throws `loadTs is not a function`

### ISSUE THREAD

**Issue by mikaelkaron** [dotansimha/graphql-code-generator#8212]
### Describe the bug

When trying the [official esm example](https://github.com/dotansimha/graphql-code-generator/tree/master/examples/typescript-esm) `loadTs is not a function` is thrown

### Your Example Website or App

https://github.com/dotansimha/graphql-code-generator/tree/master/examples/typescript-esm

### Steps to Reproduce the Bug or Issue

1. fetch local copy of https://github.com/dotansimha/graphql-code-generator/tree/master/examples/typescript-esm
2. run `npm run codegen`

### Expected behavior

Expected the example to work

### Platform

- OS: Windows
- NodeJS: 18.4
- `graphql` version: 16.5
- `@graphql-codegen/*` version(s): as example

**Comment by mikaelkaron** [comment]
Playing around a bit this looks to be an upstream problem in [`graphql-config`](https://github.com/kamilkisiela/graphql-config/) and [how it loads `cosmiconfig-typescript-loader`](https://github.com/kamilkisiela/graphql-config/blob/master/src/helpers/cosmiconfig.ts#L2) (well, the _actual_ problem is probably in how `cosmiconfig-typescript-loader` generates types)

In the generated `index.mjs` file you can "fix" the problem like this:

```
import loadTsx from 'cosmiconfig-typescript-loader';
...
const loadTs = loadTsx.default
```

So it looks like the correct default export is not correctly picked up between CJS and ESM. I've seen this in a few projects since I started transitioning to ESM and the [`default-import`](https://www.npmjs.com/package/default-import) package can help to bridge this problem.

**Comment by mikaelkaron** [comment]
there's a [relevant coment](https://github.com/microsoft/TypeScript/issues/49160#issuecomment-1137482639) in the TypeScript repo for reference.

**Comment by lednhatkhanh** [comment]
I'm also facing the same problem.

**Comment by n1ru4l** [comment]
@mikaelkaron What `index.mjs` file are you referring to?

**Comment by mikaelkaron** [comment]
The `index.mjs` discussed is generated from https://github.com/kamilkisiela/graphql-config/blob/master/src/helpers/cosmiconfig.ts#L2, so the fix will have to be applied in that package. 

I see now linking to it that there is a fix landed in their `master` branch, so perhaps a new version is on its way.

**Comment by n1ru4l** [comment]
@mikaelkaron New release with this fix is on the way :) https://github.com/dotansimha/graphql-code-generator/releases
