### ISSUE TITLE
Add Hive as a Schema format

### ISSUE THREAD

**Issue by cancan101** [dotansimha/graphql-code-generator#8240]
**Is your feature request related to a problem? Please describe.**
not related to a bug

**Describe the solution you'd like**
Offer a native [schema format](https://www.graphql-code-generator.com/docs/config-reference/schema-field#available-formats) for code generation to load directly from [GraphQL Hive](https://docs.graphql-hive.com/features/registry-usage)

**Describe alternatives you've considered**
The schema could be fetched using another tool from Hive and then accessed as a local file
Alternatively if there is a URL that hosts the schema it could be used as well

**Additional context**

**Comment by dotansimha** [comment]
@cancan101 if you are using Hive, you can use the CDN feature to get a (secured) URL that always returns the latest composed schema.  From your `target` page, you can click `Connect` and then use the generated URL and auth key with codegen: 

```yml
schema:
  - https://cdn.graphql-hive.com/SOME_ID:
      headers:
        X-Hive-CDN-Key: AUTH_KEY
```

> You can find more info about using custom headers here: https://www.graphql-code-generator.com/docs/config-reference/schema-field#headers

> [GraphQL Hive CDN docs](https://docs.graphql-hive.com/features/registry-usage#cdn-access)
