### ISSUE TITLE
Docs Website: Incorrect link to a core configuration object signature

### ISSUE THREAD

**Issue by DianaSuvorova** [dotansimha/graphql-code-generator#8261]
### Describe the bug

the link to type is outdated

https://www.graphql-code-generator.com/docs/advanced/programmatic-usage

```
Then, create a configuration object ([complete signature](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/codegen.ts#L7-L16)):
```

### Your Example Website or App

https://www.graphql-code-generator.com/docs/advanced/programmatic-usage

### Steps to Reproduce the Bug or Issue

Open the doc site and click the link: https://www.graphql-code-generator.com/docs/advanced/programmatic-usage

### Expected behavior

The referenced code should describe the type of a configuration object.

### Screenshots or Videos

https://user-images.githubusercontent.com/1284223/185692232-b8d56ca0-fe70-4e15-ad19-7afc93803f82.mov

### Platform

- OS: [e.g. macOS, Windows, Linux]

**Comment by n1ru4l** [comment]
Closed via #8262
