### ISSUE TITLE
[V2] typescript mongodb doesn't prodoce DbObjects

### ISSUE THREAD

**Issue by kamilkisiela** [dotansimha/graphql-code-generator#827]
**Describe the bug**
GraphQL Codegen TypeScript MongoDB doesn't produce DbObjects.

**To Reproduce**
https://github.com/darkbasic/graphql-modules-seed/tree/codegen-v2

**Expected behavior**
Having `*DbObject`

**Additional context**
Every type doesn't pass:
https://github.com/dotansimha/graphql-code-generator/blob/4e941c37cb525806994f2601e43a53648f641b4c/packages/plugins/typescript-mongodb/src/templates/type.handlebars#L12

That's because here, it gets called twice. On the first time `schema` has `@entity` and other directives but on the second, they are all missing and we only get `@include`, `@skip` and `@deprecated`. 

https://github.com/dotansimha/graphql-code-generator/blob/4e941c37cb525806994f2601e43a53648f641b4c/packages/graphql-codegen-core/src/utils/get-directives.ts#L6

I noticed that references of both instances don't match. That doesn't happen inside of a unit test.

**Comment by ardatan** [comment]
So, it won't be a template but an external library. And this library will contain schemaDirectives and typeDefs inside of it, right?

**Comment by kamilkisiela** [comment]
In #833, I reproduced what we want to have.

It should merge schemas and keep all directives and types should also keep them.
It does the first thing but every type with a directive, no longer has it in its AST, so plugins like TypeScript MongoDB will fail.

**Comment by konsumer** [comment]
Was this resolved? I am having same issue with schemaDirectives:

```graphql
type User @db {
  id: ID!
  email: String!
  firstName: String
  lastName: String
  name: String @nodb
  posts: [ Post ]!
}
```

gets turned into this:

```graphql
type User {
  id: ID!
  email: String!
  firstName: String
  lastName: String
  name: String
  posts: [Post]!
}
```

With this code:

```
const { printSchema, parse, visit } = require('graphql')

module.exports = {
  plugin: (schema, documents, config) => {
    console.log(printSchema(schema))
  },
  addToSchema: `
    directive @db(table: String) on OBJECT
    directive @nodb on FIELD | FIELD_DEFINITION
  `
}
```

Should I be doing it differently?

**Comment by dotansimha** [comment]
@konsumer Can you please open a new issue for this?

**Comment by konsumer** [comment]
@dotansimha yep, no prob: #2108
