### ISSUE TITLE
feat: support urql graphcase v5

### ISSUE THREAD

**Issue by dargmuesli** [dotansimha/graphql-code-generator#8276]
**Is your feature request related to a problem? Please describe.**

Updating to `@urql/exchange-graphcache` `v5` gives me a pnpm peer dependency error stating that `@graphql-codegen/typescript-urql-graphcache` `v2.3.2` only supports `@urql/exchange-graphcache` `^4.1.1`.

**Describe the solution you'd like**

Either make `@graphql-codegen/typescript-urql-graphcache` support `v5` or just mark it as such. I think I've read over in the urql repos that code generation should continue to work as before.

**Describe alternatives you've considered**

Using `.npmrc` with `strict-peer-dependencies=false` to downgrade errors to warnings.

**Additional context**

https://github.com/FormidableLabs/urql/issues/2621

**Comment by dotansimha** [comment]
Fixed, thanks @JoviDeCroock 
Here's the release: https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1662283159919
