### ISSUE TITLE
Init error with the dependency `undici`

### ISSUE THREAD

**Issue by Ardear** [dotansimha/graphql-code-generator#8277]
### Describe the bug

when I run `pnpm graphql-code-generator init` , It throw an error 
```
.../.pnpm/registry.npmmirror.com+@whatwg-node+fetch@0.2.9/node_modules/@whatwg-node/fetch/dist/create-node-ponyfill.js:163
      class Request extends OriginalRequest {
                            ^
TypeError: Class extends value undefined is not a constructor or null
```

Then I check this file, it's 
```
      const OriginalRequest = ponyfills.Request || undici.Request;

      class Request extends OriginalRequest {
```

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

1. `pnpm add graphql`
2. `pnpm add -D @graphql-codegen/cli`
3. `pnpm graphql-code-generator init`

### Expected behavior

I want to generat files

### Platform

- OS: macOS
- NodeJS: 16.6.1
- `graphql` version:16.6.0
- `@graphql-codegen/*` version(s): 2.11.6

**Comment by henrikhaugboelle** [comment]
If I run this with node `v16.5.0` it gives me the same error, but if I run it with `v12.21.0` it succeeds. Haven't tried any other versions and I do not know the origin of this error, but perhaps this information can help you move forward @Ardear

**Comment by Ardear** [comment]
> If I run this with node `v16.5.0` it gives me the same error, but if I run it with `v12.21.0` it succeeds. Haven't tried any other versions and I do not know the origin of this error, but perhaps this information can help you move forward @Ardear

Thanks!
