### ISSUE TITLE
Skip schema includes unused input types

### ISSUE THREAD

**Issue by josemarluedke** [dotansimha/graphql-code-generator#828]
I'm trying to generate only the document types for a given query.

It seems that passing the option `--skip-schema` does not skip generating input types from the schema, even if they are not used in a query.

**To Reproduce**

Reproduction can be found here: https://github.com/josemarluedke/gql-gen-bug-repro

1. Schema is located at the root of the repo: `schema.graphql`.
2. Document is located at `components/query.graphql`.
3. Run the following command:
```
yarn gql-gen --schema ./schema.graphql --skip-schema --template graphql-codegen-typescript-template --out ./components/__generated__/ ./components/**.graphql
```

**Expected behavior**
I would expect that in the generated file, it would only contain the `documents`. In this case, only the namespace `GetPosts`. It would expect it to contain used Input types as well used scalars.

**Environment:**
 - OS: MacOS Mojave (10.14.1)
 - Codegen: 0.13.0"
 - Node: v10.11.0

Generated types can be found at this file: `components/__generated__/types.ts`.

**Comment by kamilkisiela** [comment]
Yes, it generates every input, enum and scalar defined in the schema. That's because you might use it in documents. Right now, we can't tell which one of them is used or not. That's something we might want to implement after releasing a new major version (soon).

**Comment by dotansimha** [comment]
Hi @josemarluedke ! Thank you for opening this issue! 
@kamilkisiela is right, input types, enums and scalars are required for client side as well, so we cant avoid it. It will be more flexible and customizable in the new API that we'll release soon.

We had a discussion about this issue before, please read https://github.com/dotansimha/graphql-code-generator/issues/438
