### ISSUE TITLE
[V2] webpack plugin - tsloader doesn't pick up changes (in watch mode)

### ISSUE THREAD

**Issue by kamilkisiela** [dotansimha/graphql-code-generator#829]
**Describe the bug**
We've got two files. One is generated by the codegen, the other depends on the first one. If we change something in schema, the output with types is generated correctly, file gets written but webpack doesn't see the change, it uses cached content.

Let's say 

**To Reproduce**
https://github.com/kamilkisiela/graphql-webpack/tree/v2

1. Use `Int!` in `Author.id`
1. `$ yarn build:watch`
1. TS compiles everything correctly
1. Change `Author.id` to `String!`
1. TS compiles everything correctly, no issue (we should get an error)

**Expected behavior**
Webpack should pick up changes in watch mode.

**Environment:**
 - OS:
 - Codegen:
 - Node: 

**Additional context**
I tried to use Webpack's `purge` method (of file system) to remove output file from the cache but it doesn't work.

**Comment by kamilkisiela** [comment]
When I use a custom webpack loader for `.ts` files I see it gets an always fresh output.
I tried `awesome-typescript-loader` and after manually making a change in one of ts files it picks the fresh output and compiles as expected but the same process doesn't work with `ts-loader`.

Based on that I assume they have their own caching mechanism.

**Comment by dotansimha** [comment]
We can't force tsc to recompile when interfaces changes, and shipping the plugin this way might cause confusion because of the compilation lifecycle. We decided to wait a bit before support this.
