### ISSUE TITLE
schema must contain subscriptions and mutations

### ISSUE THREAD

**Issue by thunder7553** [dotansimha/graphql-code-generator#83]
The schema document must contain query, subscription and mutation fields. If it does not contain them, then there will be a error:

`Cannot read property 'name' of null`

The problem is in src/handlers/operation-handler.ts, line 31-33. 

`export const handleOperation = (schema: GraphQLSchema, definitionNode: OperationDefinitionNode, primitivesMap: any, flattenInnerTypes: boolean): CodegenDocument => {
  const name = definitionNode.name.value;
  const type = definitionNode.operation;
  const root = getRoot(schema, definitionNode);
  const typesMap = {
    query: schema.getQueryType().name,
    subscription: schema.getSubscriptionType().name,
    mutation: schema.getMutationType().name,
  };
`

These fields should be either optional, or provide a better exception message.

**Comment by dotansimha** [comment]
Fixed in `graphql-code-generator@0.5.2`! Thanks @thunder7553 !
