### ISSUE TITLE
Docs Website: Several symbols are missing from the sample

### ISSUE THREAD

**Issue by roottool** [dotansimha/graphql-code-generator#8318]
### Describe the details

The samples on "Getting started" page in the website is missing some symbols.

- [Development workflow > Monorepo and Yarn Workspaces](https://www.the-guild.dev/graphql/codegen/docs/getting-started/development-workflow#monorepo-and-yarn-workspaces)
  https://github.com/dotansimha/graphql-code-generator/blob/96fcf9267c2d986d7fbf031be59e91d8664ad4c0/website/src/pages/docs/getting-started/development-workflow.mdx?plain=1#L80-L81
- [ESM TypeScript Usage > Codegen Configuration](https://www.the-guild.dev/graphql/codegen/docs/getting-started/esm-typescript-usage#codegen-configuration)
  https://github.com/dotansimha/graphql-code-generator/blob/96fcf9267c2d986d7fbf031be59e91d8664ad4c0/website/src/pages/docs/getting-started/esm-typescript-usage.mdx?plain=1#L33

### Describe the solution you'd like

- Add `,` at the end 
  - https://github.com/dotansimha/graphql-code-generator/blob/96fcf9267c2d986d7fbf031be59e91d8664ad4c0/website/src/pages/docs/getting-started/development-workflow.mdx?plain=1#L80
  - https://github.com/dotansimha/graphql-code-generator/blob/96fcf9267c2d986d7fbf031be59e91d8664ad4c0/website/src/pages/docs/getting-started/esm-typescript-usage.mdx?plain=1#L33
- Add `:` between key and value
  - https://github.com/dotansimha/graphql-code-generator/blob/96fcf9267c2d986d7fbf031be59e91d8664ad4c0/website/src/pages/docs/getting-started/development-workflow.mdx?plain=1#L81

### Additional context

- Ref. https://github.com/dotansimha/graphql-code-generator/pull/8301#discussion_r960363747

**Comment by saihaj** [comment]
#8319
