### ISSUE TITLE
[typescript-graphql-request] Allow passing Abortsignal to sdk methods

### ISSUE THREAD

**Issue by shkreios** [dotansimha/graphql-code-generator#8360]
**Is your feature request related to a problem? Please describe.**

Currently, it's not possible to pass an `Abortsignal` to the sdk methods generated by the `typescript-graphql-request` plugin.

**Describe the solution you'd like**

Replacing the positional argument call with single argument, described in the new [graphql-request usage](https://github.com/prisma-labs/graphql-request#usage)

**Describe alternatives you've considered**

`Graphql-request` currently does not allow passing an `Abortsignal` any other way.

**Additional context**

Although there is a react-query graphql codegen plugin we started using the `graphql-request` plugin and create custom hooks based on react-query on our own to have more control over the custom hooks. We now want to leverage the signal passed to each fetcher function of `react-query` in `graphql-request`.

**Comment by mirague** [comment]
Just ran into a need for this today as well, good to see there's others who have a need for this.

**Comment by yemi** [comment]
This is really needed for us as well and am willing to help if needed.

**Comment by shkreios** [comment]
@yemi @mirague I currently don't have time to do any more testing, but I have created a new [pr](https://github.com/dotansimha/graphql-code-generator-community/pull/32) and [issue](https://github.com/dotansimha/graphql-code-generator-community/issues/31) on the community plugin repo.
