### ISSUE TITLE
Missing peer dependency on graphql-tag

### ISSUE THREAD

**Issue by MariaSolOs** [dotansimha/graphql-code-generator#8398]
### Describe the bug

When installing `@graphql-codegen/client-preset@1.0.1` with `yarn`, the following error is displayed:
```
➤ YN0002: │ @graphql-codegen/client-preset@npm:1.0.1 [e2984] doesn't provide graphql-tag (p07f0f), requested by @graphql-codegen/gql-tag-operations
```

### Your Example Website or App

https://github.com/MariaSolOs/paradeigma

### Steps to Reproduce the Bug or Issue

1. In any `npm` package using `yarn v2`, run `yarn add @graphql-codegen/client-preset`.
2. Check the output window for `yarn` errors.

### Expected behavior

The dependency should be installed without any errors.

### Platform

- OS: macOS
- NodeJS: 16.17.0
- `graphql` version: 16.6.0
- `@graphql-codegen/cli`: 2.13.0
- `@graphql-codegen/introspection`: 2.2.1
- `@graphql-codegen/typescript`: ^2.7.3
- `@graphql-codegen/typescript-graphql-request`: 4.5.5
- `@graphql-codegen/typescript-operations`: 2.5.3
- `@graphql-codegen/typescript-resolvers`: 2.7.3

**Comment by charlypoly** [comment]
Hi @MariaSolOs,

Thank you for spotting this! 🙇🏼 

It is now fixed in `@graphql-codegen/client-preset@1.0.2` 📦
