### ISSUE TITLE
graphql-codegen-typescript-resolvers-template ignores gql-gen.json config

### ISSUE THREAD

**Issue by lednhatkhanh** [dotansimha/graphql-code-generator#840]
**Describe the bug**
gql-gen.json gets ignore when running using graphql-codegen-typescript-resolvers-template

**To Reproduce**
1. Create `gql-gen.json` with this config:

```json
{
  "prepend": ["import { AppContext } from './utils';"],
  "contextType": "AppContext"
}
```

1. Run with `DEBUG=true gql-gen --template graphql-codegen-typescript-resolvers-template --schema schema.json --out ./src/__generated__/resolvers-types.ts`

2. Log

```
22:12:47.829 - info: [executeWithOptions] Got project config JSON: {"prepend":["import { AppContext } from './utils';"],"contextType":"AppContext"}
22:12:47.833 - info: [executeWithOptions] Schema is being loaded
...
22:12:47.933 - info: Generation result contains total of 1 files...
✔ Generated file written to...
```

**Expected behavior**
`AppContext` will be used at default context type

**Actual**

Context still has type any, everything else works fine

**Environment:**
 - OS: Mac OS 10.14.1
 - Codegen: ^0.13.0
 - Node: 10

**Comment by lednhatkhanh** [comment]
Figured out the correct file has to be:

```json
{
  "generatorConfig": {
    "prepend": ["import { AppContext } from '~/utils';"],
    "contextType": "AppContext"
  }
}
```

This should updated in the README file as well

**Comment by dotansimha** [comment]
@lednhatkhanh we are currently working on improving the API and removing the need for `gqlgen.json`. It will be much easier to use!
