### ISSUE TITLE
Cannot redeclare block-scoped variable `{MutationName}Document` In React Apollo Client

### ISSUE THREAD

**Issue by ilya2207** [dotansimha/graphql-code-generator#8465]
### Describe the bug

For each request/mutation, 2 variables are created with name `{Mutation/Query name}Document}`,

### Your Example Website or App

https://github.com/ilya2207/ggl-codegen

### Steps to Reproduce the Bug or Issue

1. Clone Github project
2. Install deps
3. Execute codegen

### Expected behavior

No errors

### Screenshots or Videos
![image](https://user-images.githubusercontent.com/62308020/194888298-7acd3732-e6c7-4386-8b01-2aa9dc5226f2.png)

### Platform

- OS: Windows
- NodeJS: 16.12.0
- `graphql` version: 16.6.0
- `@graphql-codegen/cli` version(s): 2.13.5
- "@graphql-codegen/typescript-react-apollo": "^3.3.3"
- @graphql-codegen/client-preset: "1.0.5"

**Comment by hl11jp** [comment]
Hi @ilya2207 
use `graphqlrc.yaml` instead of `codegen.ts`

example: https://learn.saleor.io/setup/graphql-code-generator/

**Comment by charlypoly** [comment]
Hi @ilya2207,

The `client` preset should not be used with other plugins.
Here, both the `client` preset and `@graphql-codegen/typescript-react-apollo` plugin are generating types, leading to duplicates.
