### ISSUE TITLE
Duplication identifier issue with codegen

### ISSUE THREAD

**Issue by chenningg** [dotansimha/graphql-code-generator#8467]
### Describe the bug

I have a a query and a mutation inside `./src/graphql/queries`.
I'm generating to the folder `./src/graphql/generated/`.

Somehow the codegen is generating all the typings twice, resulting in a lot of duplicate identifiers. My codegen config is below:

```
import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  debug: true,
  schema: "http://192.168.1.251:5050/api",
  documents: "src/graphql/queries/*.ts",
  ignoreNoDocuments: true,
  config: {
    withHooks: true,
    namingConvention: {
      enumValues: "keep",
    },
  },
  generates: {
    "./src/graphql/generated/": {
      preset: "client",
      config: {
        addUnderscoreToArgsType: true,
      },
      plugins: ["typescript", "typescript-operations", "typescript-urql"],
    },
    "./graphql.schema.json": {
      plugins: ["introspection"],
    },
  },
};

export default config;
```

### Your Example Website or App

Not published

### Steps to Reproduce the Bug or Issue

Have a query and a mutation in a folder, and run codegen on it. The types are generated TWICE in the same output file.

### Expected behavior

The types should only be generated once for the schema.

### Platform

- OS: Windows 10
- NodeJS: v18.9.0
- `graphql` version: ^16.6.0
- `@graphql-codegen/*` version(s): 2.13.5

**Comment by charlypoly** [comment]
Hi @chenningg,

could you try removing the following line?

```
plugins: ["typescript", "typescript-operations", "typescript-urql"],
```

**Comment by chenningg** [comment]
Managed to fix it with the following config:
```
import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  debug: true,
  schema: "http://192.168.1.251:5050/api",
  documents: "src/graphql/queries/*.ts",
  ignoreNoDocuments: true,
  generates: {
    "./src/graphql/generated/index.ts": [
      {
        typescript: {},
      },
      {
        "typescript-operations": {},
      },
      {
        "typescript-urql": {
          withHooks: true,
        },
      },
    ],
    "./graphql.schema.json": {
      plugins: ["introspection"],
    },
  },
};

export default config;
```
I think by specifying the file name explicitly, the plugins can understand they are all writing to the same file and not duplicate the type generation.

**Comment by hl11jp** [comment]
@chenningg 
I did specify the file name explicitly but it created a folder name `/src/graphql/generated/index.ts`
Do you encounter this?
Thanks!

**Comment by chenningg** [comment]
> @chenningg I did specify the file name explicitly but it created a folder name `/src/graphql/generated/index.ts` Do you encounter this? Thanks!

Hmm, no. Mine only generated index.ts in ./src/graphql/generated/. How does your config file look like?

**Comment by hl11jp** [comment]
It looks like this
```
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: "http://localhost:3000/graphql",
  documents: "./src/graphql/**/*.graphql",
  generates: {
    "./src/graphql/generated/index.ts": {
      preset: "client",
      plugins: []
    },
    "./graphql.schema.json": {
      plugins: ["introspection"]
    }
  }
};

export default config;
```

The output is like this
<img width="212" alt="image" src="https://user-images.githubusercontent.com/21292391/195233242-9f68bb3c-bb46-402a-ae08-dcdc93ff4443.png">

This is weird honestly.

**Comment by hl11jp** [comment]
I managed to fix it by using `graphqlrc.yaml` and config manually instead of run `graphql-codegen init` this gave me an `codegen.ts` config file and it is buggy

**Comment by chenningg** [comment]
I have switched to type-document-node plugin like such:
```
import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  debug: true,
  schema: "http://192.168.1.251:5050/api",
  documents: "./src/graphql/queries/*.graphql",
  generates: {
    "./src/graphql/generated/index.ts": {
      plugins: [
        {
          typescript: {},
        },
        {
          "typescript-operations": {},
        },
        {
          "typed-document-node": {},
        },
      ],
    },
    "./graphql.schema.json": {
      plugins: ["introspection"],
    },
  },
};

export default config;
```
The codegen.ts and yaml files are equivalent I think, the file format should not affect your result.

**Comment by hl11jp** [comment]
I see. Thank you for your response!

**Comment by bfourgeaud** [comment]
I still have this problem.

On NextJS I have a folder with all my .graphql queries and fragments.

My codegen.ts is like that :
```ts
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  debug: true,
  schema: process.env.NEXT_PUBLIC_GRAPHCMS_URL || "****",
  documents: "graphql/**/*.graphql",
  ignoreNoDocuments: true,
  generates: {
    "generated/": {
      preset: "client",
      plugins: ['typescript', 'typescript-operations', 'typescript-graphql-request']
    }
  }
};

export default config;
```


But the output always creates a lot of duplicate types in **generated/graphql.ts*

I have for example this Document defined twice : 
```ts
export const PostRequestDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PostRequest"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"stage"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Stage"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"post"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"where"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}]}},{"kind":"Argument","name":{"kind":"Name","value":"stage"},"value":{"kind":"Variable","name":{"kind":"Name","value":"stage"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"PostFragment"}},{"kind":"Field","name":{"kind":"Name","value":"site"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"SiteFragment"}}]}}]}}]}},...PostFragmentFragmentDoc.definitions,...SiteFragmentFragmentDoc.definitions]} as unknown as DocumentNode<PostRequestQuery, PostRequestQueryVariables>;
```

AND 

```ts
export const PostRequestDocument = gql`
    query PostRequest($id: ID!, $stage: Stage!) {
  post(where: {id: $id}, stage: $stage) {
    ...PostFragment
    site {
      ...SiteFragment
    }
  }
}
    ${PostFragmentFragmentDoc}
${SiteFragmentFragmentDoc}`;
```

I would really appreciate some help on this problem ...

**Comment by chenningg** [comment]
Currently, you are applying the "client" preset on all 3 plugins. Not sure if that causes bugs. You may want to remove the client preset, or apply it only on a specific plugin to prevent duplicate generation.

**Comment by charlypoly** [comment]
@bfourgeaud, @chenningg is right, the `client-preset` should not be used in combination of other typescript plugins

**Comment by bfourgeaud** [comment]
Thanks for the update.
It finally worked removing the `client-preset` !

**Comment by charlypoly** [comment]
@bfourgeaud, I would suggest you use the `client-preset` only instead of the plugins, for better integration with `graphql-request`, as showcased here: https://github.com/dotansimha/graphql-code-generator/tree/master/examples/front-end/react/graphql-request

**Comment by bfourgeaud** [comment]
@charlypoly but I really like the `getSdk `function that the `graphql-request` plugin generates. Otherwise I would not have used that plugin in fact.   
What is the drawback of removing the `client-preset` ?

**Comment by chenningg** [comment]
@bfourgeaud Not much to be found in the documentation, but from what I gather, the client preset is just like a collection of plugins to get you up and running fast. If you are specifying the plugins you want to use with their own individual options yourself, you are better off removing the client preset. I could be wrong, though.

**Comment by ShravanSunder** [comment]
> @bfourgeaud, I would suggest you use the `client-preset` only instead of the plugins, for better integration with `graphql-request`, as showcased here: https://github.com/dotansimha/graphql-code-generator/tree/master/examples/front-end/react/graphql-request

@charlypoly how do we pass in typescript configurations to client preset?  I've tried putting it in `presetConfig` however none of the settings are respected.
