### ISSUE TITLE
When Using ESM with @graphql-tools/code-file-loader code generation fails

### ISSUE THREAD

**Issue by sirganya** [dotansimha/graphql-code-generator#8511]
### Describe the bug

When I use a typescript file to define a schema and compile as an ESM the build fails. 

### Your Example Website or App

https://codesandbox.io/s/vigilant-framework-03nz6r?file=/exampleSchema.ts

### Steps to Reproduce the Bug or Issue

Use a ts file as schema source and use `yarn graphql-codegen-esm --config ./codegen.yml` to build 

### Expected behavior

I expect the codegen to complete as it does with without `type: module` in `package.json`

### Platform

- OS: macOS
- NodeJS: 17.9.1
"@graphql-cli/codegen": "^2.4.10",
    "@graphql-codegen/cli": "^2.13.7",
    "@graphql-codegen/typescript": "^2.7.4",
    "@graphql-codegen/typescript-graphql-request": "^4.5.6",
    "@graphql-codegen/typescript-operations": "^2.5.4",
    "@graphql-codegen/typescript-resolvers": "^2.7.4",

### Codegen Config File

```yaml
overwrite: true
emitLegacyCommonJSImports: false
generates:
  ./src/gql/generated/schema.ts:
    schema:
      - ./src/gql/schema/*.ts:
          noPluck: true
    plugins:
      - typescript
      - typescript-resolvers
    config:
      makeResolverTypeCallable: true
      customResolverFn: ./codeGenCustomTypes#DefaultResolver
  ./src/gql/generated/operations.ts:
    schema:
      - ./src/gql/schema/*.ts:
          noPluck: true
    documents: ./src/gql/operations/*.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
    config:
      typesPrefix: 'SDK_'


### Additional context

` Failed to load schema from ./src/gql/schema/*.ts:
      Failed to find any GraphQL type definitions in: ./src/gql/schema/*.ts;
      - Unable to load from file "/Users/gregkavanagh/git/bwos/shared/src/gql/schema/errors.ts": TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/gregkavanagh/git/bwos/share…
      at new NodeError (node:internal/errors:372:5)
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
      at defaultGetFormat (node:internal/modules/esm/get_format:122:38)
      at defaultLoad (node:internal/modules/esm/load:21:20)
      at ESMLoader.load (node:internal/modules/esm/loader:431:26)
      at ESMLoader.moduleProvider (node:internal/modules/esm/loader:350:22)
      at new ModuleJob (node:internal/modules/esm/module_job:66:26)
      at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:369:17)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:328:34)
      at async Promise.all (index 0)

**Comment by ardatan** [comment]
If you disable `graphql-tag-pluck`, you have to setup Node to load TS files as modules using a loader like TS-Node;
https://codesandbox.io/s/long-shape-27i8t5?file=/document.graphql

https://github.com/TypeStrong/ts-node#node-flags-and-other-tools

**Comment by Allaoua9** [comment]
Hello can you post the solution please ?

**Comment by Allaoua9** [comment]
Okay, so adding in my script `NODE_OPTIONS="--loader ts-node/esm"` worked for me.

```json
{
    "codegen": "NODE_OPTIONS=\"--loader ts-node/esm\" graphql-codegen-esm --verbose --config old-codegen.yml"
}
```


PS:
doing it in the config DID NOT work:
```yml
require:
  - ts-node/esm
```
