### ISSUE TITLE
[client-preset] React-query example... Isn't strongly typed. `data` is `any` etc.

### ISSUE THREAD

**Issue by charlypoly** [dotansimha/graphql-code-generator#8516]
> > React-query example... Isn't strongly typed. `data` is `any` etc.
> 
> Hi @Faithfinder,
> 
> Could you provide more context about which example you are referring to? The `client-preset` provides typed GraphQL operations when React Query is used in combination with a supported GraphQL client (ex: `graphql-request@^5`) or when the fetcher is properly typed ([as documented in our guide](https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue#appendix-i-react-query-with-a-custom-fetcher-setup)).

Just checking out an example you've supplied: https://github.com/dotansimha/graphql-code-generator/tree/v3-preset-front-end/examples/front-end/react/tanstack-react-query

Using twoslash here to demostrate that `data` is any, and on `request` to demonstrate that `yarn install` has been run and types are in place, generally.
![image](https://user-images.githubusercontent.com/25051063/196963782-f4106da0-b5c0-45a4-94a4-4eb364782cd2.png)

_Originally posted by @Faithfinder in https://github.com/dotansimha/graphql-code-generator/issues/8296#issuecomment-1285557290_

**Comment by Faithfinder** [comment]
As I keep repeating, it's _your_ `package.json`. I literally just checked out the example from the repo. Checked out, as in `git clone` the repo and `yarn` in the directory of the example.
https://github.com/dotansimha/graphql-code-generator/blob/master/examples/front-end/react/tanstack-react-query/package.json

One of the problems is that `graphql` itself is not installed. If I install it, then some types for `data` appear, but not all of them. If I try to look at `data?.allFilms?.edges[0]?.node`, it only has `__typename`, no typings from fragment.

**Comment by charlypoly** [comment]
You are right, the `graphql` dev dependency is missing; I'll add it.

The typing of fragments is only accessible from the `<Film>` component; this is because of the Fragment Masking, [as explained in our guide](https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue#writing-graphql-fragments).
The current behavior of your local setup is working as expected.
