### ISSUE TITLE
@graphql-codegen/client-preset w/o needing to use `useFragment`

### ISSUE THREAD

**Issue by fabis94** [dotansimha/graphql-code-generator#8520]
**Is your feature request related to a problem? Please describe.**

I love the new client preset '@graphql-codegen/client-preset', but I don't want to always have to use `useFragment` to get some data out from a query that used fragments for one reason or another. 

**Describe the solution you'd like**

A configuration option that allows you to opt out from `useFragment` being a requirement. Essentially it would just change the TS types so that all of the fragment fields are accessible directly, without needing to use `useFragment` first.

**Describe alternatives you've considered**

I could just set up basic GQL codegen without the preset, but this preset is so easy to use and brings such nice DX that I'd rather avoid that.

**Comment by akhma-ps** [comment]
@fabis94 Will [that](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/presets/client/src/index.ts#L21-L39) help you?

```ts
const config = {
   schema: 'https://swapi-graphql.netlify.app/.netlify/functions/index',
   documents: ['src/**\/*.tsx', '!src\/gql/**\/*'],
   generates: {
      './src/gql/': {
         preset: 'front-end',
         presetConfig: {
           fragmentMasking: false,
         }
       },
   },
};
```
