### ISSUE TITLE
Subscription Resolvers Type Error with withFilter

### ISSUE THREAD

**Issue by daytona63** [dotansimha/graphql-code-generator#8547]
### Describe the bug

`SubscriptionResolvers` does not handle the type of [withFilter](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#filtering-events)

### Your Example Website or App

Non

### Steps to Reproduce the Bug or Issue

Run with the Codegen Config File

### Expected behavior

`SubscriptionResolvers` To work with [withFilter](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#filtering-events)

### Platform

- `OS`: macOS M1 Pro
- `NodeJS`: v18.12.0 LTS
- `graphql`: "^16.6.0"
- `@graphql-codegen/add`: "^3.2.1"
- `@graphql-codegen/cli`: "^2.13.8"
- `@graphql-codegen/gql-tag-operations-preset`: "^1.7.0"
- `@graphql-codegen/graphql-modules-preset`: "^2.5.4"
- `@graphql-codegen/introspection`: "^2.2.1"
- `@graphql-codegen/typescript`: "^2.8.0"
- `@graphql-codegen/typescript-document-nodes`: "^2.3.5"
- `@graphql-codegen/typescript-resolvers`: "^2.7.5"

### Codegen Config File

definitions:
  add: &top-comment
    content: >
      /**
       * NOTE: THIS IS AN AUTO-GENERATED FILE. DO NOT MODIFY IT DIRECTLY.
       */

      /* eslint-disable */

      // 👇️ ts-nocheck ignores all ts errors in the file

      // eslint-disable-next-line @typescript-eslint/ban-ts-comment

      // @ts-nocheck
overwrite: true
watch: false
schema: './src/gql/**/typeDefs/*.gql*'
emitLegacyCommonJSImports: false
generates:
  ./src/gql/:
    preset: graphql-modules
    presetConfig:
      baseTypesPath: ../generated-types/graphql.ts # Where to create the complete schema types
      filename: generated-types/module-types.ts # Where to create each module types
    plugins:
      - add: *top-comment
      - add:
          content: 'import { CustomScalars } from "../shared/scalars.js"'
      - typescript:
          enumsAsTypes: false
          typesPrefix: GQL_
          scalars:
            Upload: CustomScalars['Upload']
            Date: CustomScalars['Date']
            DateTime: CustomScalars['DateTime']
            EmailAddress: CustomScalars['EmailAddress']
            JSON: CustomScalars['JSON']
            ObjectID: CustomScalars['ObjectID']
            UUID: CustomScalars['UUID']
      - typescript-resolvers:
          enumsAsTypes: false
          typesPrefix: GQL_
          noNamespaces: true
          useIndexSignature: true
          contextType: 'GraphQLModules.GlobalContext'

  ./graphql.schema.json:
    plugins:
      - 'introspection'

**Comment by ardatan** [comment]
Please share a reproduction using our template.

**Comment by rolexAk** [comment]
@ardatan here you go

https://codesandbox.io/s/suspicious-ritchie-ysvvqs?file=/package.json

**Comment by hfgn** [comment]
Hi @ardatan @daytona63  i have the issue. 
Do you have any solution?

**Comment by daytona63** [comment]
@hfgn I believe once this [PR](https://github.com/apollographql/graphql-subscriptions/pull/250) is merged in graphql subscriptions, then this will be fixable

**Comment by Urigo** [comment]
After so many years of that Apollo library not being maintained, I wouldn't count on it releasing a new version or merging PRs...
Check out this discussion [here](https://github.com/apollographql/graphql-subscriptions/issues/240)

If you are using GraphQL Subscriptions, I would highly recommend you to use [Yoga Server](https://the-guild.dev/graphql/yoga-server/docs/comparison#real-time-and-graphql-subscriptions)
