### ISSUE TITLE
`nonOptionalTypename` is not respected with client preset

### ISSUE THREAD

**Issue by KhaledSakr** [dotansimha/graphql-code-generator#8558]
### Describe the bug

When using the client preset and trying to specify the `nonOptionalTypename` config, the generated types still have optional `__typename`.

### Your Example Website or App

https://codesandbox.io/s/magical-fire-28s03p?file=/codegen.ts

### Steps to Reproduce the Bug or Issue

1. Make sure you have any schema and operations files.
2. Create a minimal codegen config file using the `client` preset.
3. Specify the config `nonOptionalTypename: true`.
4. Generate the types.
5. See that the generated types still have an optional typename (i.e. `__typename?: 'User';`).

### Expected behavior

`client` preset should respect the `nonOptionalTypename` option.

### Platform

- `graphql` version: 15.8.0
- `@graphql-codegen/client-preset` version: 1.1.3

### Codegen Config File
```ts
import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "schema.graphql",
  documents: "document.graphql",
  config: {
    nonOptionalTypename: true
  },
  generates: {
    "./gql/": {
      preset: "client",
      plugins: []
    }
  }
};

export default config;
```

**Comment by ShravanSunder** [comment]
i'm alos having the same issue

**Comment by ithinkdancan** [comment]
Seems like this would be an easy thing to add to the preset by just adding the option to the `forwardedConfig`. Happy to open up a pull request if the project maintainers are on board.

**Comment by saihaj** [comment]
@ithinkdancan that would be awesome! Happy to review and land the fix.

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1670443964814
