### ISSUE TITLE
PR #8497 typescript-react-query infiniteQuery pageParamKey update introduced breaking change for some users

### ISSUE THREAD

**Issue by EandrewJones** [dotansimha/graphql-code-generator#8566]
Please see @marcmll's comment below:
https://github.com/dotansimha/graphql-code-generator/pull/8497#issuecomment-1300617915

I will open a new PR to only overwrite the variables with `pageParamKey` when its value is defined:

```
(metaData) => fetcher<${operationResultType}, ${operationVariablesTypes}>(client, ${documentVariableName}, {...variables, ...(metaData.pageParam ? { [pageParamKey]: metaData.pageParam } : {}}, headers)(),
```

**Comment by saihaj** [comment]
released https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1667578711788

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1667578711788
