### ISSUE TITLE
@graphql-codegen/cli >= 2.13.10 causes "Unknown fragment" error

### ISSUE THREAD

**Issue by rosskevin** [dotansimha/graphql-code-generator#8570]
### Describe the bug

```sh
$ yarn codegen
$ graphql-codegen --config ./codegen.ts
✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to types.ts
    ✔ Load GraphQL schemas
    ✔ Load GraphQL documents
    ✖ GraphQL Document Validation failed with 1 errors;
      Error 0: Unknown fragment "CurrentUser".
      at /sandbox/.graphql:9:8
error Command failed with exit code 1.
```

Broken sandbox:

https://codesandbox.io/s/gql-codegen-fragment-error-reversion-narrow-dep-mtze4x?file=/package.json

```json
  "dependencies": {
    "@graphql-codegen/cli": "2.13.10", // <---------
    "@graphql-codegen/typescript": "2.8.1",
    "@graphql-codegen/typescript-operations": "2.5.6",
    "graphql": "^16.2.0"
  }
```

-------

Working sandbox:

https://codesandbox.io/s/gql-codegen-fragment-error-reversion-working-9j9i6q?file=/package.json

```json
  "dependencies": {
    "@graphql-codegen/cli": "2.13.9",
    "@graphql-codegen/typescript": "2.8.1",
    "@graphql-codegen/typescript-operations": "2.5.6",
    "graphql": "^16.2.0"
  },
```

### Your Example Website or App

https://codesandbox.io/s/gql-codegen-fragment-error-reversion-narrow-dep-mtze4x?file=/package.json

### Steps to Reproduce the Bug or Issue

`yarn generate`

### Expected behavior

I expect `@graphql-codegen/cli >= 2.13.10` to work like previous versions.

### Platform

see codesandbox

### Codegen Config File

default codesandbox file

### Additional context

This has been working fine and I was surprised with a fresh `ncu -u && yarn install` with only patch releases updated that my codegen is broken.  I've narrowed the test sandbox down to @graphql-codegen/cli@2.13.9 being successful, and @graphql-codegen/cli@2.13.10 failing.

**Comment by cheald** [comment]
I've just run into this too. I reverted back to my previous .8 install and things are fine.

**Comment by MokumJ** [comment]
Same same

**Comment by n33pm** [comment]
`2.13.9` works too

**Comment by rosskevin** [comment]
@n33pm - read the title and the issue - `2.13.9` is not `>= 2.13.10`.  I specifically post a working sandbox version with `2.13.9`.

**Comment by Nickersoft** [comment]
Just hit this as well – good to know I'm not crazy 😅

**Comment by duongdev** [comment]
Still getting this on 2.13.11 (upgrading from 2.13.8)

**Comment by strblr** [comment]
Same here.

**Comment by charlypoly** [comment]
Hi everyone!

Very sorry for this regression introduced in a great performance improvement of codegen validations (now 40x faster) 🏎️ 

It is now fixed in `@graphql-codegen/cli@2.13.12` 📦

**Comment by macrozone** [comment]
still broken in version 4 in certain cases

**Comment by SPAHI4** [comment]
same for me

**Comment by nemonemi** [comment]
I am experiencing this problem when I have a fragment that is being imported. If the fragment is defined in the same file, then it simply works, but the point of the fragment is to share it with other queries/mutations.

   "@graphql-codegen/add": "5.0.0",
    "@graphql-codegen/cli": "5.0.0",
    "@graphql-codegen/client-preset": "4.1.0",
    "@graphql-codegen/introspection": "4.0.0",
    "@graphql-codegen/typescript": "4.0.1",
    "@graphql-codegen/typescript-document-nodes": "4.0.1",
    "@graphql-codegen/typescript-graphql-files-modules": "2.2.1",
    "@graphql-codegen/typescript-msw": "1.1.6",
    "@graphql-codegen/typescript-operations": "4.0.1",
    "@graphql-codegen/typescript-react-query": "4.1.0",

**Comment by nitish3006** [comment]
well it works

**Comment by MrOrz** [comment]
I encountered "Unknown fragment" issue when a `tsx` file is loading a fragment definition from a `js` file. Converting the js file containing the fragment to tsx fixes this issue.

Ref: https://github.com/cofacts/rumors-site/commit/e5d9c5d32f33ff4f61a9779cc474173684ec438b
