### ISSUE TITLE
`typed-document-node` with `dedupeFragments: true` not working as expected for generating fragment documents

### ISSUE THREAD

**Issue by helios1138** [dotansimha/graphql-code-generator#8582]
### Describe the bug

`typed-document-node` with `dedupeFragments: true` generates nice Documents for queries that use fragments, automatically including all mentioned fragments. But In case of fragments themselves, it doesn't include the sub-fragments into the documents (`XXXFragmentDoc` objects) which makes it impossible to use for e.g. `client.readFragment` use case

### Platform

`graphql` version: 15.3.0
"@graphql-codegen/cli": "2.2.1",
"@graphql-codegen/typed-document-node": "^2.3.6"

**Comment by adrienharnay** [comment]
Also facing this with all latest versions:
```
"@graphql-codegen/cli": "2.16.2",
"@graphql-codegen/typed-document-node": "2.3.11"
```

which makes `dedupeFragments: true` impossible to use, but when using `false` then there are runtime errors because `There can only be one fragment named ***`

**Comment by LydiaF** [comment]
Also facing this with

"@graphql-codegen/cli": "3.0.0",
"@graphql-codegen/typed-document-node": "3.0.0"

**Comment by n1ru4l** [comment]
This is now fixed, please make sure you are using the latest version
