### ISSUE TITLE
Top level TypeScriptLoader(ts-node) registration issue

### ISSUE THREAD

**Issue by Diizzayy** [dotansimha/graphql-code-generator#8588]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

The [change introduced here](https://github.com/dotansimha/graphql-code-generator/pull/8452/commits/572d3287964ff83dc9a7102cd3d0ac7a0e701c97) by #8452 results in the unnecessarily early registration of `ts-node` which subsequently attempts to load a project's `tsconfig.json` if present.

This isn't an issue for most projects, because the tsconfig tends to be static and independent. 

However though, with [Nuxt 3](https://github.com/nuxt/framework) we've taken the approach of immensely improving upon the developer experience by providing auto imports among with other typescript first conventions to make the workflow as seamless as possible.

Nuxt 3 projects contain a root `tsconfig.json` file which extends from an auto generated tsconfig located at `.nuxt/tsconfig.json`, hence the issue explained above. This has resulted in Nuxt graphql modules which leverage the amazing graphql code generator developed here to crash whenever that `.nuxt/tsconfig.json` hasn't been previously generated.

### Steps to Reproduce the Bug or Issue

1. Clone [`nuxt-graphql-client`](https://github.com/Diizzayy/nuxt-graphql-client)
2. Run `pnpm i` to install dependencies
3. Run `pnpm prepare` to successfully prepare the app

#### Trigger Issue
1. Delete the `playground/.nuxt/tsconfig.json` file
2. Open `package.json` and removed the patched dependency from line 70
3. Run `pnpm i` to apply changes
4. Run `pnpm prepare` to see issue

### Expected behavior

Should run properly without the prerequisites of the project's `tsconfig.json` file being present.

### Platform

- OS: macOS
- NodeJS: v18.11.0
- `graphql` version: 16.6.0
- `@graphql-codegen/cli` version(s): 2.13.11

**Comment by charlypoly** [comment]
@Diizzayy, thanks for the fix!
It has been released in `@graphql-codegen/cli@2.15.0` 📦
