### ISSUE TITLE
📝 DOC: client-preset documentation missing

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [dotansimha/graphql-code-generator#8594]
### Describe the bug

The documentation for the client-preset is missing. On the page.

https://github.com/dotansimha/graphql-code-generator/tree/master/packages/presets/client

### Your Example Website or App

https://www.the-guild.dev/graphql/codegen/plugins/presets/client-preset

### Steps to Reproduce the Bug or Issue

https://www.the-guild.dev/graphql/codegen/plugins/presets/client-preset missing

### Expected behavior

documentation for the client preset

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by beerose** [comment]
The documentation for `client-preset` was added here: https://github.com/dotansimha/graphql-code-generator/pull/8657/files#diff-d284b73dd66d8b59bcaa29eb457b2c68a122722eadf06f0749971a94c041f847

[Link to the website](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client).
