### ISSUE TITLE
Generates invalid TypeScript - TS2300: Duplicate identifier

### ISSUE THREAD

**Issue by rodneyrehm** [dotansimha/graphql-code-generator#8599]
### Describe the bug

Running graphql-codegen for https://gitlab.com/api/graphql produces invalid TypeScript:

```ts
/** Common sort values */
export enum Sort {
  /** Created at ascending order. */
  CreatedAsc = 'CREATED_ASC',
  /** Created at descending order. */
  CreatedDesc = 'CREATED_DESC',
  /** Updated at ascending order. */
  UpdatedAsc = 'UPDATED_ASC',
  /** Updated at descending order. */
  UpdatedDesc = 'UPDATED_DESC',
  /**
   * Created at ascending order.
   * @deprecated This was renamed. Please use `CREATED_ASC`. Deprecated in 13.5.
   */
  CreatedAsc = 'created_asc',
  /**
   * Created at descending order.
   * @deprecated This was renamed. Please use `CREATED_DESC`. Deprecated in 13.5.
   */
  CreatedDesc = 'created_desc',
  /**
   * Updated at ascending order.
   * @deprecated This was renamed. Please use `UPDATED_ASC`. Deprecated in 13.5.
   */
  UpdatedAsc = 'updated_asc',
  /**
   * Updated at descending order.
   * @deprecated This was renamed. Please use `UPDATED_DESC`. Deprecated in 13.5.
   */
  UpdatedDesc = 'updated_desc'
}
```

With the `error TS2300: Duplicate identifier '<key>'` being raised for every key of the generated enum.

### Your Example Website or App

local terminal

### Steps to Reproduce the Bug or Issue

1. run `graphql-codegen` with the supplied codegen config
2. run `tsc --noEmit ./gitlab/gql/graphql.ts`

### Expected behavior

As a user, I expected to get valid TypeScript generated

### Platform

- OS: macOS 12.6
- NodeJS: 16.17.1
- `graphql` version: 16.6.0
- `@graphql-codegen/*` version(s): 2.13.11
- `typescript` version: 4.8.4

### Codegen Config File

```js
{
  schema: 'https://gitlab.com/api/graphql',
  documents: [],
  generates: {
    './gitlab/gql/': {
      preset: 'client',
      plugins: [],
    },
  },
}
```

**Comment by charlypoly** [comment]
Hi,

Could you share the GraphQL definition of the `Sort` enum?

**Comment by charlypoly** [comment]
Hi @rodneyrehm,

This behavior is expected since your enum values translate to the same Capitalized equivalent.
I would suggest you try to configure a different naming convention that would not generate a conflicting enum value name: https://the-guild.dev/graphql/codegen/docs/config-reference/naming-convention#upper-case-enum-values

**Comment by MrTact** [comment]
I was able to fix this problem with a simple naming function:

```javascript
const {lowerCase, pascalCase} = require("change-case-all");

function ignore_deprecated_enums(str) {
  if (str === lowerCase(str)) {
    return str;
  } else {
    return pascalCase(str);
  }
}
```

Then in the config:
```javascript
  config: {
    namingConvention: {
      enumValues: ignore_deprecated_enums
    }
  }
```
