### ISSUE TITLE
codegen creates a --- import { GraphQLResolveInfo } from 'graphql'; --- instead --- import GraphQLResolveInfo from 'graphql'; ---

### ISSUE THREAD

**Issue by Redskinsjo** [dotansimha/graphql-code-generator#8616]
### Which packages are impacted by your issue?

@graphql-codegen/introspection, @graphql-codegen/typescript-operations, @graphql-codegen/typescript-resolvers, @graphql-codegen/typed-document-node, @graphql-codegen/typescript

### Describe the bug

I have installed:
    "@graphql-codegen/introspection": "^2.2.1",
    "@graphql-codegen/typed-document-node": "^2.3.7",
    "@graphql-codegen/typescript": "^2.8.2",
    "@graphql-codegen/typescript-operations": "^2.5.7",
    "@graphql-codegen/typescript-react-apollo": "^3.3.6",
    "@graphql-codegen/typescript-resolvers": "^2.7.7",

when building my nextjs, it led to this error
<img width="1253" alt="Capture d’écran 2022-11-18 à 01 25 39" src="https://user-images.githubusercontent.com/51161811/202589517-6ada0391-809a-44e8-a191-b1b8aeb0c128.png">

because generated.ts shows:
<img width="562" alt="Capture d’écran 2022-11-18 à 01 27 05" src="https://user-images.githubusercontent.com/51161811/202589558-c5e09497-61d8-4c8a-9461-d90fc8053f5b.png">

### Your Example Website or App

https://github.com/Redskinsjo/to-fork-graphql-codegen

### Steps to Reproduce the Bug or Issue

1. yarn install
2. yarn run dev
3. yarn build

### Expected behavior

that build passes

### Platform

- OS: macOS
- NodeJS: v16.14.2
- `graphql` version: "^16.6.0"
-  "graphql-yoga": "^3.0.0",
    "@graphql-codegen/introspection": "^2.2.1",
    "@graphql-codegen/typed-document-node": "^2.3.7",
    "@graphql-codegen/typescript": "^2.8.2",
    "@graphql-codegen/typescript-operations": "^2.5.7",
    "@graphql-codegen/typescript-react-apollo": "^3.3.6",
    "@graphql-codegen/typescript-resolvers": "^2.7.7",

### Codegen Config File

overwrite: true
schema:
  - "http://localhost:3000/api/graphql"
documents:
  - "./graphql/**/*.graphql"
generates:
  ./graphql/generated.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-resolvers"
      - "typed-document-node"
  ./graphql.schema.json:
    plugins:
      - "introspection"
require:
  - ts-node

**Comment by saihaj** [comment]
I guess we need to change it so it is a type import since it is exported as a type https://unpkg.com/browse/graphql@16.6.0/index.d.ts

**Comment by Redskinsjo** [comment]
there was a conflict between the package and my folder './graphql', renamed to './gql' and it works
