### ISSUE TITLE
Not generating in parallel: bad concurrency configuration

### ISSUE THREAD

**Issue by Cellule** [dotansimha/graphql-code-generator#8635]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

GraphQL-Codegen does not run in parallel when it used to and looks like it's still trying to

According to listr2 https://listr2.kilic.dev/getting-started/task-object#options
The configurations `exitOnError` and `concurrent` should be in a second argument to `newListr`

https://github.com/dotansimha/graphql-code-generator/blob/4e3cfdce1bc86c576d792fe634c537017129f682/packages/graphql-codegen-cli/src/codegen.ts#L385-L390

This should solve the issue
```ts
return task.newListr(generateTasks, {
                  // It doesn't stop when one of tasks failed, to finish at least some of outputs
                  exitOnError: false,
                  concurrent: (0, os_1.cpus)().length,
                });
```

I tried locally and it worked as expected

### Your Example Website or App

---

### Steps to Reproduce the Bug or Issue

Run GraphQL Codegen with more than 1 file generated

### Expected behavior

It should run in parallel according to your number of CPUs

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: 16.10
- `graphql` version: 16.2.0
- `@graphql-codegen/cli` version(s): 2.13.12

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1669393783419
