### ISSUE TITLE
fragment not deduplicated by `client` preset

### ISSUE THREAD

**Issue by saihaj** [dotansimha/graphql-code-generator#8670]
Hey 👋  I have also encountered this issue, and it's a bit of a potential blocker so I'm hopeful we can resolve it. I've created a minimal repro here: https://codesandbox.io/s/focused-silence-flkogf

It is a very minimal repro but I think shows the essence of the issue. If you run `npm run start`, the GraphQL query is printed showing two instances of the example `SharedComponentFragment` fragments I included. This is essentially how my query looks when seeing the error at the network level `There can only be one fragment named 'X'`, so hopefully serves as a suitable reproduction — let me know if not though!

_Originally posted by @lrholmes in https://github.com/dotansimha/graphql-code-generator/discussions/8617#discussioncomment-4277757_

**Comment by lrholmes** [comment]
Thanks for creating this issue for us! I'm curious to ask if you have any pointers for how someone could start looking into diagnosing this issue? I've no experience contributing to this repo but this issue is becoming a bit of a blocker for me so am open to helping if I can 🙏

**Comment by saihaj** [comment]
Hey @lrholmes I started with a repro from the codesanbox to this https://github.com/dotansimha/graphql-code-generator/pull/8671 I don't think we have a easy way to mock this. 

But to fix the issue we just need to make the default to be `true` here https://github.com/dotansimha/graphql-code-generator/blob/224a5362ca26952aeab6947db18623efa69eb96e/packages/presets/client/src/index.ts#L94

**Comment by beerose** [comment]
Fixed in https://github.com/dotansimha/graphql-code-generator/pull/8971
