### ISSUE TITLE
Add option to typescript-operations plugin to print generated types on multiple lines

### ISSUE THREAD

**Issue by kbrooks** [dotansimha/graphql-code-generator#8722]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-operations

### Describe the bug

The typescript-operations plugin currently outputs generated types on a single line. This is hard to read for obvious reasons and it would be nice to have the types print on multiple lines for a better developer experience.

A workaround would be to run prettier or another formatter on the generated types, but this would increase the execution time of that tool unnecessarily.

### Your Example Website or App

Reproducible on demo https://the-guild.dev/graphql/codegen

### Steps to Reproduce the Bug or Issue

The single-line type output is easy to see on the "Operations types" demo here: https://the-guild.dev/graphql/codegen.

```
export type FindUserQuery = { __typename?: 'Query', user?: { __typename?: 'User', id: string, username: string, role: Role } | null };
```

### Expected behavior

Something like this would be nice:

```
export type FindUserQuery = {
   __typename?: 'Query',
   user?: {
     __typename?: 'User',
     id: string,
     username: string,
     role: Role
   } | null
 };
```

### Platform

- OS: macOS
- NodeJS: 16.17.1
- `graphql` version: 15.4.0
- `@graphql-codegen/*` version(s): 2.5.10

### Codegen Config File

This is the default behavior. Here is the demo page's config file:

generates:
  operations-types.ts:
    plugins:
      - typescript
      - typescript-operations

**Comment by saihaj** [comment]
Codgen has a plugin and hooks system for a reason. I don't think we need to necessarily engineer any prettier things within codegen. In my experience I haven't find any need to prettifying generated outputs.
