### ISSUE TITLE
pluckConfig.gqlMagicComment breaks client preset generated graphql overload source's format

### ISSUE THREAD

**Issue by rwu823** [dotansimha/graphql-code-generator#8780]
### Which packages are impacted by your issue?

graphql-codegen-cli

### Describe the bug

`pluckConfig.gqlMagicComment` breaks client preset generated `graphql` overload source. it trimmed `\n` and spaces.

### Your Example Website or App

https://stackblitz.com/edit/github-vffocy?file=src%2F__gql__%2Fgql.ts,src%2FApp.tsx,codegen.ts

### Steps to Reproduce the Bug or Issue

just run and check the generated types:

```sh
yarn gql-gen
```

### Expected behavior

generated source should be followed all the template string format, this is the correct one.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/890063/210130438-772fb18e-ccec-4f08-acc1-b72d2be02ff0.png">

### Platform

follows `stackblitz` example

### Codegen Config File

follows `stackblitz` example

### Additional context

even just leave `pluckConfig: {}` also breaks.

_No response_

**Comment by Solo-steven** [comment]
I find the reason for this problem.  when loading documents, CLI will pass pluckConfig to the CodeFileLoader object. (https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/load.ts#L75)
![Screenshot 2023-01-28 at 7 52 27 PM](https://user-images.githubusercontent.com/67428009/215265089-6deaa3ac-8208-4e6b-86de-7f1c132f88ab.png)

but when developer adds config to pluckConfig, CodeFileLoader would merge two config, and its mergeConfig method does not recursively copy, it only copy one layer of config object, so developer's config would overwrite the CLI's config (https://github.com/ardatan/graphql-tools/blob/master/packages/loaders/code-file/src/index.ts#L76)
![Screenshot 2023-01-28 at 7 59 07 PM](https://user-images.githubusercontent.com/67428009/215265250-73dc33f9-a391-42ce-b302-541210f8de12.png)

A simple solution is to add `skipIndent` to `codegen.ts's` config.
https://stackblitz.com/edit/github-vffocy-ba7ruw?embed=1&file=README.md
But I think we better change the merge method of CodeFileLoader to avoid overwriting.
