### ISSUE TITLE
graphql-codegen/cli@2.16.4 needs ts-node

### ISSUE THREAD

**Issue by numb86** [dotansimha/graphql-code-generator#8814]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

Dependency for `graphql-codegen/cli@2.16.4` x is incorrect.

### Your Example Website or App

should occur in all environments.

### Steps to Reproduce the Bug or Issue

```
$ mkdir foo
$ cd foo
$ yarn init -y
$ yarn add graphql@latest
$ yarn add @graphql-codegen/cli@2.16.4
$ yarn graphql-codegen

Error: Cannot find module 'ts-node'
```

### Expected behavior

no error

### Platform

Platform doesn't matter

**Comment by isoppp** [comment]
FYI: `graphql-config` seems to remove `ts-node` dependency in v4.4.0
https://github.com/kamilkisiela/graphql-config/compare/v4.3.6...v4.4.0
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/package.json#L65

**Comment by jbsmith731** [comment]
Can confirm downgrading to `2.16.3` resolves the error

**Comment by ffxsam** [comment]
Side note: simple testing could've prevented a broken release from going out to a highly-used npm package (1.4 million downloads per week).

**Comment by hussein-jaban** [comment]
I just `yarn add ts-node` it worked.

**Comment by n1ru4l** [comment]
This was caused by a minor bump that should have been a major bump within `graphql-config`.
I am right now working on reverting and releasing a patch version for `graphql-config` that will solve this.

In the meantime, the solutions mentioned in https://github.com/dotansimha/graphql-code-generator/issues/8814#issuecomment-1384759057 and https://github.com/dotansimha/graphql-code-generator/issues/8814#issuecomment-1408531960 work.

**Comment by n1ru4l** [comment]
Okay, https://github.com/dotansimha/graphql-code-generator/pull/8865 moved ts-node from peer dependencies to dependencies! I will release new versions shortly. Sorry for the inconvenience.

Regarding https://github.com/dotansimha/graphql-code-generator/issues/8814#issuecomment-1384819476
we will be moving to pnpm soon, which will make these kinds of dependency chain issues easier to track.

Any other additional smoke tets contribution would be highly appreciated.

**Comment by n1ru4l** [comment]
```
@graphql-codegen/cli@2.16.5
```

got released.

**Comment by vladshcherbin** [comment]
@n1ru4l thanks for taking care of it! 🙌
