### ISSUE TITLE
Fragment fields arent generated in typescript

### ISSUE THREAD

**Issue by Banou26** [dotansimha/graphql-code-generator#8818]
### Which packages are impacted by your issue?

@graphql-codegen/client-preset

### Describe the bug

Using a fragment in a query does not generate typescript fields for that fragment.

### Your Example Website or App

https://github.com/Banou26/graphql-code-generator-issue-8818

### Steps to Reproduce the Bug or Issue

1. `npm run codegen`
2. Check out `src/index.ts` and the lines at the end of the file for type errors.
3. Check out `src/generated/graphql.ts` for the related generated types

Error thrown in those case are
```ts
// Property 'id' does not exist on type '{ __typename?: "User" | undefined; } & { ' $fragmentRefs'?: { UserFragmentFragment: UserFragmentFragment; } | undefined; }'.
```
because the generated types with that fragment is
```ts
export type UserFragmentFragment = { __typename?: 'User', id: string, name: string, email: string } & { ' $fragmentName'?: 'UserFragmentFragment' };

export type GetUserQuery = { __typename?: 'Query', user?: (
    { __typename?: 'User' }
    & { ' $fragmentRefs'?: { 'UserFragmentFragment': UserFragmentFragment } }
  ) | null };
```

while it should be something like

```ts
export type UserFragmentFragment = { __typename?: 'User', id: string, name: string, email: string } & { ' $fragmentName'?: 'UserFragmentFragment' };

export type GetUserQuery = { __typename?: 'Query', user?: (
    { __typename?: 'User' }
    & UserFragmentFragment  }
  ) | null };
```

or even

```ts
export type GetUser3Query = { __typename?: 'Query', user?: { __typename?: 'User', id: string, name: string, email: string } | null };
```

### Expected behavior

The typescript query types should contain the fields that the fragment contains

### Platform

- `@graphql-codegen/*` version(s): 2.16.4

Might be duplicate of #8271

**Comment by saihaj** [comment]
By default `client` preset enables [FragmentMasking](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#fragment-masking) so this output is expected.

**Comment by coffenbacher** [comment]
@saihaj , I am running into this as well and I think the issue is that the fragment is simply not _working_ with the types, not that the types are a little unintuitive due to masking.

If you take a look at the example repo OP reported, I think the 'id' field should be available on both tests 1 & 2 they did?

It's possible I'm totally misunderstanding something but I am on the same page as OP, so maybe there's room for an explainer here in the Issues even if it's a wontfix! Thanks for taking a look at this.

**Comment by Banou26** [comment]
I simply disabled `fragmentMasking` to get the wanted behavior, I'll probably switch to fragment masking at some point though.

```ts
const config: CodegenConfig = {
  // ... other config fields
  generates: {
    './src/generated/': {
      // ... other config
      presetConfig: {
        gqlTagName: 'gql',
        fragmentMasking: false
      }
    }
  }
}
```

Hopefully this helps you

**Comment by coffenbacher** [comment]
Thank you @Banou26 for the fix and opening the issue w/ the description! Going to go with that configuration option for now. 

And after further research I think I was misunderstanding the point of fragment masking. It is sort of an interesting approach to pass data but hide the types of it to prevent usage; I see the rationale but it definitely feels unintuitive coming from other typing approaches. Hopefully this issue serves as a beacon on Google for other people with the same error messages 😅

**Comment by chhuang** [comment]
If I turn off `fragmentMasking`, do I have to include `${fragmentData}` at the end of the query?
