### ISSUE TITLE
Every GraphQL type generated to TypeScript is doubled

### ISSUE THREAD

**Issue by h1sashin** [dotansimha/graphql-code-generator#8820]
### Which packages are impacted by your issue?

@graphql-codegen/typescript

### Describe the bug

` graphql-codegen ` command generates `graphql.ts` folder with doubled types, I don't even know what more can I say. It just generates types and then runs again and generates everything but imports again.

### Your Example Website or App

I think it's not needed

### Steps to Reproduce the Bug or Issue

1. Run `npx graphql-codegen`
2. Open `graphql.ts` file

### Expected behavior

Generate types once

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/25825628/212565240-8e2ce825-9ac1-4d3c-ac7a-5bb6298a250f.png)

### Platform

- OS: Windows 11
- NodeJS 16.17.0
- `graphql` version: 16.6.0
- `@graphql-codegen/cli` version(s): 2.16.4

### Codegen Config File

```ts
import { CodegenConfig } from '@graphql-codegen/cli'

const schema = 'https://my-backend-link.com/graphql'

const config: CodegenConfig = {
    schema,
    documents: ['src/**/*.graphql.ts'],
    overwrite: true,
    generates: {
        './src/lib/__generated__/': {
            preset: 'client',
            plugins: ['typescript', 'typescript-operations', 'typescript-react-apollo'],
            presetConfig: {
                gqlTagName: 'gql'
            }
        }
    },
    ignoreNoDocuments: false
}

export default config
```

**Comment by Banou26** [comment]
Duplicate of #8467 
Try removing the `typescript` and `typescript-operations` plugins since you already use the client preset as per <https://github.com/dotansimha/graphql-code-generator/issues/8467#issuecomment-1274283916>

**Comment by h1sashin** [comment]
thanks, it worked

**Comment by codingwesley** [comment]
thanks!
