### ISSUE TITLE
Add possibility to generate intermediary types in documents generating plugins ( `typescript-operations`)

### ISSUE THREAD

**Issue by antoine-malliarakis** [dotansimha/graphql-code-generator#8827]
### Is your feature request related to a problem? Please describe.

When trying to migrate away from the apollo cli and its codegen feature there is one feature which seems to be missing and is described here: https://github.com/apollographql/apollo-tooling/issues/2053#issuecomment-767293917

Basically it generated intermediary core types which could then be reused.

For example it would generate code such as below:

```
export type UserFieldsFragment_profile = { __typename?: 'Profile', age?: number | null };


export type UserFieldsFragment = { __typename?: 'User', id: string, username: string, profile?: UserFieldsFragment_profile | null };

```

In our codeline we use those intermediary types a lot and it would really helps us minimizing the cost of migration.

It would also seem pretty useful to me but then I could be biased.

### Describe the solution you'd like

Have the possibility, when using the `typescript-operations` to explicitely generate intermediary types.

### Describe alternatives you've considered

I've tried playing with the option `exportFragmentSpreadSubTypes` even though the description weren't really giving much hopes about it but it seemed like the closest option.

**Comment by saihaj** [comment]
This is not a feature we want codegen to support. This encourages an anti-pattern. Fragments is how _intermediary types_ should works. Fragments are built in language feature to support things like this we do not need to create some types wrapper because this just gets messier to manage.
