### ISSUE TITLE
Support `.mts` extension for codegen file / package.json "type": "module"

### ISSUE THREAD

**Issue by n1ru4l** [dotansimha/graphql-code-generator#8862]
### Is your feature request related to a problem? Please describe.

It is currently impossible to have a `codegen.mts` config.

### Describe the solution you'd like

Support the `.mts` extension.

### Describe alternatives you've considered

Use `import()` instead of `require()` in order to properly support importing all kinds of modules.

**Comment by n1ru4l** [comment]
See https://github.com/davidtheclark/cosmiconfig/issues/224

**Comment by mirismaili** [comment]
AFAIK when `"type": "module"` we don't need `.mjs`/`.mts` extension.

My problem is I have `"type": "module"` in my "package.json" file. And I get this error:
```bash
> graphql-codegen --config codegen.ts

TypeScriptLoader failed to compile TypeScript:
Must use import to load ES Module: codegen.ts
require() of ES modules is not supported.
require() of codegen.ts from node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from package.json.
```

So I was forced to use yaml config format.

**Comment by xiaoxinghu** [comment]
Having exactly the same issue.

**Comment by n1ru4l** [comment]
@xiaoxinghu For now the following workaround is recommended:

https://github.com/dotansimha/graphql-code-generator/issues/8509#issuecomment-1418270837

> for those running into this issue where a static YAML file is not a solution, you can rename your file to `codegen.cjs`
> 
> ```js
> /** @type {import('@graphql-codegen/cli').CodegenConfig} */
> const config = {
>   // ...
> }
> 
> module.exports = config
> ```
> 
> and then modify your `scripts` in `package.json` accordingly
> 
> ```json
> "scripts": {
>   "codegen": "graphql-codegen --config codegen.cjs",
> }
> ```
