### ISSUE TITLE
@graphql-codegen/cli @whatwg-node/fetch v0.6.0 doesn't support Node v14 

### ISSUE THREAD

**Issue by leneos** [dotansimha/graphql-code-generator#8886]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

Hi, i have node v14. I updated @graphql-codegen/cli to the latest version and now i have an error during executing graphql-codegen: 
class PonyfillBlob extends buffer.Blob
TypeError: Class extends value undefined is not a constructor or null

![Снимок экрана 2023-02-01 144334](https://user-images.githubusercontent.com/20744726/215993612-01c2adb6-5ec8-44f0-9404-9b470b8a8972.png)

It seems that the problem is with the updated to version 0.6.0 @whatwg-node/fetch package. 

### Your Example Website or App

https://codesandbox.io/p/sandbox/nervous-haze-1sorxf?file=%2Fcodegen.ts&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A8%7D%5D

### Steps to Reproduce the Bug or Issue

open terminal
npm start
(the default terminal uses yarn, there are no problems with yarn only with npm)
![image](https://user-images.githubusercontent.com/20744726/216035322-17851c35-e0f6-4503-8fa8-ec6078a34716.png)

### Expected behavior

so this trouble occured after updating the @graphql-codegen/cli, even downgrading doesnt help because it installs packages like @graphql-tools/executor-http, @graphql-tools/apollo-engine-loader and etc. that also have dependency of @whatwg-node/fetch

### Platform

- Windows
- NodeJS: [e.g. 14.17.3]
- `graphql` version: latest
- `@graphql-codegen/*` version(s): latest

### Codegen Config File

import { CodegenConfig } from "@graphql-codegen/cli";
const config: CodegenConfig = {
  overwrite: true,
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    "./src/query.graphql": {
      schema: "https://spacex-production.up.railway.app/",
      documents: ["./**/*.mainEndpoint.ts"],
      plugins: ["typescript", "typescript-operations"],
      presetConfig: {
        gqlTagName: "gql"
      }
    }
  }
};

export default config;

**Comment by andrew-ironforge** [comment]
I'm also seeing this as of 02/04 when running `npx graphql-codegen`.

**Comment by ardatan** [comment]
I think it happens older versions than `v14.18.0`.

**Comment by leneos** [comment]
> I think it happens older versions than `v14.18.0`, right?
seems right. just checked and under node 14.18.0 codegen works, but i think that it is a major bug so better fix it.

**Comment by aayush216** [comment]
> @graphql-codegen/cli

`"@graphql-tools/executor-http": "0.1.1"` 

adding this in the resolutions worked for me. (Node version 14.17.5)

**Comment by aayush216** [comment]
> I'm also seeing this as of 02/04 when running `npx graphql-codegen`.
> 
> Node version `14.17.5`

"@graphql-tools/executor-http": "0.1.1"

adding this in the package.json resolutions worked for me. (Node version 14.17.5)

**Comment by andrew-ironforge** [comment]
@aayush216  This is what I'm seeing as well. In a separate project, @whatwg-node/fetch is set to 0.6.2 and that builds just fine. My version is 0.6.6.

**Comment by costatatiane** [comment]
Updating node version to 14.18.0 worked for me!

**Comment by leneos** [comment]
I updated to the latest version and the text of mistake has changed. As i see they have updated @whatwg-node/fetch to version 0.7.0. I'm having the same mistake, may be because the main package @graphql-codegen/cli uses old version 0.6.0 not 0.7.0.
![image](https://user-images.githubusercontent.com/20744726/217830877-aa8c0039-3e3a-41b6-a41d-eb7e7ec02c5c.png)

![image](https://user-images.githubusercontent.com/20744726/217830489-d137bbe2-0051-40d5-9fd7-7e32ff2b4e94.png)

**Comment by costatatiane** [comment]
> I updated to the latest version and the text of mistake has changed. As i see they have updated @whatwg-node/fetch to version 0.7.0. I'm having the same mistake, may be because the main package @graphql-codegen/cli uses old version 0.6.0 not 0.7.0. ![image](https://user-images.githubusercontent.com/20744726/217830877-aa8c0039-3e3a-41b6-a41d-eb7e7ec02c5c.png)
> 
> ![image](https://user-images.githubusercontent.com/20744726/217830489-d137bbe2-0051-40d5-9fd7-7e32ff2b4e94.png)

did you try to update your node version? you said your version was NodeJS: [e.g. 14.17.3]

**Comment by leneos** [comment]
I can't update node on my current project for reasons beyond my control, so i'm seeking for help from the maintainers of this repo.

**Comment by ardatan** [comment]
Could you reinstall codegen and try again? Now `@whatwg-node/fetch` has its own Blob ponyfill.

**Comment by leneos** [comment]
> Could you reinstall codegen and try again? Now `@whatwg-node/fetch` has its own Blob ponyfill.

Thank you! Everything seems to work now!
