### ISSUE TITLE
Naming convention of types

### ISSUE THREAD

**Issue by janhartmann** [dotansimha/graphql-code-generator#889]
I am unsure whether or not I have missed a configuration step, but my generated types for arrays is looking like this after upgrading to 0.14.1:

```tsx
export namespace GetMachinesForFleetInventory {
  export type Variables = {};

  export type Query = {
    __typename?: "Query";

    machines: Machines[] | null;
  };

  export type Machines = {
    __typename?: "Machine";

    id: number;

    model: string | null;

    category: string | null;

    brand: string | null;

    productionDate: Date | null;
  };
}
```

I would really want `Machines[]` to be `Machine[]` (the `__typename`), as working with them in singular form.

Is there a configuration for this? :-)

**Comment by dotansimha** [comment]
Hi @janhartmann ! 

The codegen just generates according to the name of the fields you ask for. You can change it by using graphql aliases:

```
query {
    machine: machines {
         id
    }
}
``` 

It will replace the name of the fields locally, and cause the codegen to generate a type called `export type Machine` instead of `Machines`.

Do you think we should address this issue in a different way?

**Comment by janhartmann** [comment]
I can see why the codegen does this, and maybe I just need to adjust my mind to this naming. 

I guess  I am just used to have a `Machine` and when its an array its `Machine[]`. So the `__typename` is the one defining the type :-)

**Comment by dotansimha** [comment]
Yeah `__typename` defined the actual GraphQL type, and the name of the interface is according to the name of the field that you asked for. 

Closing for now :)

**Comment by janhartmann** [comment]
I guess I can write my own plugin now ;-)

**Comment by codepunkt** [comment]
I'm actually considering the same. I'd like my query to actually read `machines` and the resulting objects to also have a `machines` property. The type of the `machines` property should be `Machine[]`, not `Machines[]` - based on `__typename`, not on the query.

@janhartmann wrote a plugin yet? 😁 
@dotansimha ever thought exposing this as a configuration option? that'd be lovely! ❤️

**Comment by dotansimha** [comment]
@codepunkt I recommend you to use the latest codegen version - 1.0.0.
We fixed a lot of issues, and now `__typename` is being added automatically, and we are generating only one TypeScript `type` per GraphQL operation, without `namespace`s. 
It makes it much easier to use and maintain, and you can access type fields more easily.

**Comment by codepunkt** [comment]
@dotansimha Thanks for your work! :-)

New version, new problems. See #1535
