### ISSUE TITLE
useSuspenseQuery support

### ISSUE THREAD

**Issue by 0Lucifer0** [dotansimha/graphql-code-generator#8962]
### Is your feature request related to a problem? Please describe.

I'm wondering if there is any plan to add the support for useSuspenseQuery ?
It's currently an official alpha feature of apollo client.
https://github.com/apollographql/apollo-client/issues/10231#issuecomment-1347119382

### Describe the solution you'd like

Add a way to generate the useSuspenseQuery. Not too sure how difficult it would be, seems like the definition should be relatively similar to useQuery ?

**Comment by n1ru4l** [comment]
Hey @0Lucifer0, we currently do not actively plan to add support for this in the [`typescript-react-apollo`](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-apollo) plugin as we now recommend the [`client-preset`](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client).

The document generated by the client preset can be simply passed to `useSuspenseQuery` and the apollo client react package will correctly infer the types.

```ts
import { useSuspenseQuery } from "@apollo/client";
import { graphql } from "./gql";

const MeQuery = query(/* GraphQL */ `
  query Me {
    me {
      id
    }
  }
`);

const MyComponent = () => {
  const { data } = useSuspenseQuery(MeQuery);
  return <div>{data.me.id}</div>;
};
```
