### ISSUE TITLE
Interfaces should be converted to an union of all its implementations

### ISSUE THREAD

**Issue by FezVrasta** [dotansimha/graphql-code-generator#8964]
### Which packages are impacted by your issue?

@graphql-codegen/typescript

### Describe the bug

If I define an interface and create a type that implements it, according to the GraphQL spec I can tell a query to return the interface as a shortcut to say it can return any of its implementations too.

Codegen (on both TS and Flow) instead ignores this, and only returns the interface type. This makes any query that specifies fields only defined in the implementations break.

Schema:
```gql
type Query {
    foo: Foo!
}

interface Foo {
    id: ID!
}

type Bar implements Foo {
    id: ID!
    name: String!
}
```

Output:

```ts
export type Bar = Foo & {
  __typename?: 'Bar';
  id: Scalars['ID'];
  name: Scalars['String'];
};

export type Foo = {
  id: Scalars['ID'];
};

export type Query = {
  __typename?: 'Query';
  foo: Foo;
};
```

### Your Example Website or App

https://codesandbox.io/s/sweet-matsumoto-tl8wfh?file=/schema.graphql

### Steps to Reproduce the Bug or Issue

1. Run codegen
2. Observe the output

### Expected behavior

The expected output should be:

```
```ts
export type Bar = Foo & {
  __typename?: 'Bar';
  id: Scalars['ID'];
  name: Scalars['String'];
};

export type Foo = {
  id: Scalars['ID'];
};

export type Query = {
  __typename?: 'Query';
  foo: Foo | Bar;
};
```
```

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux] macOS
- NodeJS: 16.16.0
- "graphql": "^15.5.3",
- "@graphql-codegen/typescript": "1.21.1",


### Codegen Config File

_No response_

### Additional context

_No response_

**Comment by ardatan** [comment]
You can use `useImplementingTypes` flag to have TS union types for GraphQL interface types;
https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#useimplementingtypes

**Comment by FezVrasta** [comment]
Thanks, I missed that. Do you know if there's an equivalent for Flow?

**Comment by FezVrasta** [comment]
Hello?

**Comment by Urigo** [comment]
Flow is a community supported plugin
I saw you open an issue on the community repo so I'm closing the issue here
