### ISSUE TITLE
cli error when query and subscription has same operation name

### ISSUE THREAD

**Issue by axe-me** [dotansimha/graphql-code-generator#8972]
### Describe the bug

When the operations documents contains queries and subscriptions with same name I got this error:
` ✖ Not all operations have an unique name:`

### Your Example Website or App

https://stackblitz.com/edit/github-ikasjw?file=document.graphql

### Steps to Reproduce the Bug or Issue

Simply run the repro project above

### Expected behavior

maybe add some config to allow user to prefix query or subscription?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

### Codegen Config File

import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "schema.graphql",
  documents: "document.graphql",
  generates: {
    "types.ts": { plugins: ["typescript", "typescript-operations"] },
  },
};

export default config;

**Comment by n1ru4l** [comment]
We don't plan to support this.
