### ISSUE TITLE
Use `unknown` type for Typescript files

### ISSUE THREAD

**Issue by DeeGeeMan** [dotansimha/graphql-code-generator#8979]
### Is your feature request related to a problem? Please describe.

Eslint complains about using `{}` as a type instead of `unknown`.

### Describe the solution you'd like

User `unknown` type in place of `{}` for typescript gen files.

**Comment by n1ru4l** [comment]
Please disable eslint for the emitted artifacts by GraphQL Code Generator.

You can either add those files to your eslint ignore list or instead add the eslint ignore comment via the `add` plugin. https://the-guild.dev/graphql/codegen/plugins/other/add
