### ISSUE TITLE
e.map is not a function

### ISSUE THREAD

**Issue by lieuwestra** [dotansimha/graphql-code-generator#9015]
### Which packages are impacted by your issue?

@graphql-codegen/visitor-plugin-common

### Describe the bug

Running c-sharp-operations yields an error. locally the error is `fragmentNames.map is not a function`, and on the live-demo page it's `e.map is not a function`. 

### Your Example Website or App

https://the-guild.dev/graphql/codegen#live-demo

### Steps to Reproduce the Bug or Issue

Go to the[ live demo page](https://the-guild.dev/graphql/codegen#live-demo) on the graphql home page, and select the `c-sharp-operations` plugin. 

### Expected behavior

I expect Operations code to be generated.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by B2o5T** [comment]
upstream issue https://github.com/dotansimha/graphql-code-generator-community/issues/92
