### ISSUE TITLE
data in react example is not typed

### ISSUE THREAD

**Issue by tombohub** [dotansimha/graphql-code-generator#9020]
### Describe the bug

'you say in documentation that data is typed but it's not 
![image](https://user-images.githubusercontent.com/3029412/220182433-17407d86-9ff1-4323-95e3-ec38b5d3622b.png)

### Your Example Website or App

https://github.com/dotansimha/graphql-code-generator/tree/master/examples/react/urql

### Steps to Reproduce the Bug or Issue

download example
install packages `yarn`
check the code

### Expected behavior

data to be typed with proper type, not `any`

### Platform

- OS: win 10
- NodeJS: 16.13.1
- `graphql` not installed
- `@graphql-codegen/cli` version: ^3.0.0
- `@graphl-codegen/client-preset:  ^2.0.0

### Codegen Config File

```javascript
/* eslint-disable import/no-extraneous-dependencies */
import { type CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: 'https://swapi-graphql.netlify.app/.netlify/functions/index',
  documents: ['src/**/*.tsx', '!src/gql/**/*'],
  generates: {
    './src/gql/': {
      preset: 'client',
    },
  },
  hooks: { afterAllFileWrite: ['prettier --write'] },
};

export default config;
```

**Comment by beerose** [comment]
Works fine on a freshly cloned repo after installing dependencies. 
<img width="604" alt="CleanShot 2023-03-14 at 18 25 22@2x" src="https://user-images.githubusercontent.com/9019397/225087969-4a7f8d83-8655-4c2b-84ce-cda99d630fde.png">


You can try restarting your TS server in VSCode. 
<img width="266" alt="CleanShot 2023-03-14 at 18 24 41@2x" src="https://user-images.githubusercontent.com/9019397/225087759-cfb60274-42b1-4a97-b40f-1183579ee885.png">
