### ISSUE TITLE
client useFragment null discrimination

### ISSUE THREAD

**Issue by n1ru4l** [dotansimha/graphql-code-generator#9038]
### Is your feature request related to a problem? Please describe.

useFragment should be stricter about null and undefined

### Describe the solution you'd like

T | null should be discriminated to T | null not T | null | undefined

**Comment by cochumo** [comment]
@n1ru4l 
I thought the same thing.

Do you know of a solution to this?

**Comment by n1ru4l** [comment]
@cochumo Implementing this should be straight-forward. Let us know if you want to help out by sending a pull request!
