### ISSUE TITLE
resolver: Using {T} in a custom mapper loses Omits

### ISSUE THREAD

**Issue by ryanrhee** [dotansimha/graphql-code-generator#9043]
### Which packages are impacted by your issue?

@graphql-codegen/cli, @graphql-codegen/typescript-resolvers

### Describe the bug

When using a custom mapper with `{T}`, the recursive definition is lost, and the default type from the typescript package is used instead.

https://github.com/dotansimha/graphql-code-generator/issues/1631 says that `{T}` should be the recursive definition.

### Your Example Website or App

https://codesandbox.io/s/reverent-snowflake-7npr0h?file=/codegen.ts

### Steps to Reproduce the Bug or Issue

1. Run `yarn generate` in a codesandbox terminal
2. Read `types.ts`'s `ResolverTypes["Post"]` (line 119), note the definition which is `ResolverTypeWrapper<Omit<Post, 'authorEdge'> & { authorEdge: ResolversTypes['UserEdge'] }>`
3. Go to `codegen.ts` and change the config by uncommenting line 11 so that `Post` gets a custom mapper
4. Re-run `yarn generate`
5. Read the same type in `types.ts`, and note that the new type is now `ResolverTypeWrapper<Omit<Post, 'tags'>>`.

### Expected behavior

At step 5, I expect the type to be:
```ts
ResolverTypeWrapper<Omit<Omit<Post, 'authorEdge'> & { authorEdge: ResolversTypes['UserEdge'] }, 'tags'>
```

### Platform

- OS: macOS
- NodeJS: 16.16.0
- `graphql` version: 16.6.0

```
"@graphql-codegen/cli": "2.16.3",
"@graphql-codegen/typescript": "2.7.1",
"@graphql-codegen/typescript-resolvers": "^2.7.3",
```

### Codegen Config File

```js
import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "schema.graphql",
  documents: "document.graphql",
  generates: {
    "types.ts": {
      config: {
        mappers: {
          UserEdge: "Omit<{T}, 'user'>"
          // Post: "Omit<{T}, 'tags'>"
          // Post is `ResolverTypeWrapper<Omit<Post, 'authorEdge'> & { authorEdge: ResolversTypes['UserEdge'] }>`
          // when mapper is not specified.
          //
          // I expect that whole type to replace `{T}`.
          //
          // However, the type after mapper specification is
          // `Omit<Post, 'tags'>` which loses the `authorEdge` mapped type.
        }
      },
      plugins: ["typescript", "typescript-resolvers"]
    }
  }
};

export default config;
```

**Comment by saihaj** [comment]
[@graphql-codegen/cli@3.2.2](https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1678189242418)

**Comment by ryanrhee** [comment]
Just tested out 3.2.2, and can confirm the bug is fixed. Thank you!
