### ISSUE TITLE
@graphql-codegen/cli 3.2.0 watch mode regeneration triggers on all file changes (not just files specified in config documents pattern)

### ISSUE THREAD

**Issue by GrantASL19** [dotansimha/graphql-code-generator#9045]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

In `@graphql-codegen/cli` 3.2.0 watch mode regeneration is triggered by editing any file in the project. In <=3.1.0 regeneration only triggers when a file in the config’s `documents` pattern is edited (correct me if I’m wrong!).

In our projects this is triggering many regenerations, e.g. seemingly as files are written into the Next.js build folder.

This seems to be a result of https://github.com/dotansimha/graphql-code-generator/pull/9009

Please let me know if I’m missing something! I tried passing a pattern as the `--watch` argument or `watch` config but it seems to make no difference. But IMO even if there’s a configuration workaround this was an unexpected breaking change in a minor release.

### Your Example Website or App

https://github.com/GrantASL19/graphql-codegen-cli-watch-regression-repro

### Steps to Reproduce the Bug or Issue

* `npm i`
* `npm run generate-graphql-watch`
* Edit `src/test.js` and `src/graphQl/staticPage.graphql` and note that the following is output when either file changes:
  ```
  ✔ Parse Configuration
  ✔ Generate outputs
  ℹ Watching for changes...
  ```
* Stop the watch with Ctrl-C
* `npm i @graphql-codegen/cli@3.1.0`
* `npm run generate-graphql-watch`
* Edit `src/test.js` and `src/graphQl/staticPage.graphql` and note that the regeneration is only triggered when `src/graphQl/staticPage.graphql` changes.

### Expected behavior

Regeneration should only trigger when I change a file specified in the config `documents` field.

### Platform

- OS: macOS 13.2.1
- NodeJS: 19.6.1
- `@graphql-codegen/cli` version 3.2.0

### Codegen Config File

```js
/** @type {import('graphql-config').IGraphQLConfig} */
const graphQlConfig = {
  documents: "./src/graphQl/**/*.graphql",
  extensions: {
    /** @type {import("@graphql-codegen/cli").CodegenConfig} */
    codegen: {
      generates: { 
        "./src/generated/graphQl.ts": {
          overwrite: true,
          plugins: [
            "typescript",
            "typescript-operations",
            "typescript-graphql-request",
          ],
          config: {
            avoidOptionals: {
              field: true,
              inputValue: false,
              object: false,
              defaultValue: false,
            },
            dedupeFragments: true,
            documentMode: "string",
            enumsAsTypes: true,
            inlineFragmentTypes: "combine",
            typesPrefix: "Gql",
            omitOperationSuffix: true,
            onlyOperationTypes: true,
            preResolveTypes: true,
            scalars: {
              Date: "string",
              DateTime: "string",
              FlatTags: "../types/apiTypes#FlatTags",
              RichTextFieldType: "string",
            },
            skipTypename: true,
          },
        },
      },
    },
  },
  schema: "src/schema.graphql",
};

module.exports = graphQlConfig;
```

**Comment by saihaj** [comment]
Thanks for reporting this! I have created a fix here https://github.com/dotansimha/graphql-code-generator/pull/9051

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1677178671969

**Comment by GrantASL19** [comment]
Amazing, thanks for the quick fix and release Saihajpreet!
