### ISSUE TITLE
Generated resolvers do not have index signatures even if useIndexSignature is set to true in config

### ISSUE THREAD

**Issue by SiNONiMiTY** [dotansimha/graphql-code-generator#9059]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-resolvers

### Describe the bug

No index signature is generated on resolvers

### Steps to Reproduce the Bug or Issue

Generate types for your schema with useIndexSignature = true

### Expected behavior

An index signature must be present so we can use dynamic property access with the generated types

```
export type BasicInfoInput = {
    [key: string]: any // expecting this
    birthdate: Scalars['Float']
    firstName: Scalars['StringNonEmpty']
    lastName: Scalars['StringNonEmpty']
    middleName?: InputMaybe<Scalars['String']>
    nameExtension?: InputMaybe<Scalars['String']>
}
```

### Platform

- OS: Linux
- NodeJS: 18
- `graphql` version: 16.6.0
- `@graphql-codegen/*` version(s):
```
"@graphql-codegen/add": "^4.0.1",
"@graphql-codegen/cli": "^3.2.1",
"@graphql-codegen/typescript": "^3.0.1",
"@graphql-codegen/typescript-resolvers": "^3.1.0",
```

### Codegen Config File

  plugins:
    - typescript
    - typescript-resolvers
  config:
    useIndexSignature: true
    
    
 ### Sample Error
 
![image](https://user-images.githubusercontent.com/9588282/221156507-d1ea0034-7e07-4519-99a7-9779e4eda3ed.png)

**Comment by SiNONiMiTY** [comment]
I think its because only the `Resolvers` type is wrapped within the `WithIndex` type, but the other types of resolvers are not.

In my case, I was using the `MutationResolver` type to define the type that I was using.

**Comment by SiNONiMiTY** [comment]
Closing this issue in favor of a new feature request to add indexSignatures to base types

**Comment by narthur** [comment]
@SiNONiMiTY Can you link to the new feature reuqest you mentioned? I searched the issues on this repo and couldn't find any other issues you authored.
