### ISSUE TITLE
Fragment not typed

### ISSUE THREAD

**Issue by dstoyanoff** [dotansimha/graphql-code-generator#9081]
### Describe the bug

Hello,
I have started using the client preset recently, but experience issues while reusing fragments. What I would like to achieve is have 1 fragment definition that I could use in multiple places. This works fine if I use `useFragment`, which requires an explicit query to be passed as well. When I want to do it directly, it doesn't get typed.

### Your Example Website or App

.

### Steps to Reproduce the Bug or Issue

I have a user object for which I am trying to define the following fragment:
```
const USER_NOTIFICATION_PREFERENCES_FRAGMENT = gql(`
  fragment userNotification on User {
    notification {
      isEmail
    }
  }
`);
```

When I do that, codegen would generate the following record in `gql.ts`, which seems fine:
```
    "\n  fragment userNotification on User {\n    notification {\n      isEmail\n    }\n  }\n": types.UserNotificationFragmentDoc,
```

Also the `graphql.ts` entry:
```
export const UserNotificationFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"userNotification"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"User"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"notification"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"isEmail"}}]}}]}}]} as unknown as DocumentNode<UserNotificationFragment, unknown>;

```

If I use the above fragment in `useFragment`, all types work.

If I try to directly reuse it in another query (or mutation in this case, also tried with much simpler cases):
```
const UPDATE_USER_NOTIFICATION_PREFERENCES_MUTATION = gql(`
  mutation updateUserNotificationPreferences($userId: String!, $enableEmailNotifications: Boolean!) {
    updateUser(userId: $userId, data: { notification: { isEmail: $enableEmailNotifications } }) {
      __typename
      ... on User {
        ...userNotification
      }
      ... on UserAlreadyExistResponse {
        message
      }
    }
  }
`);
```
The result of the mutation now cannot infer the fragment fields:
![image](https://user-images.githubusercontent.com/5079334/221793507-259022ab-6057-4488-9bd5-1cf915aed06a.png)

The generated client just defines the fragment inline as a string, instead of using the generated type.

Is there a way to get over this? Am I doing something wrong or it's a limitation of the codegen?

### Expected behavior

Should be able to properly type the reused fragment

### Platform

- OS: macOS
- NodeJS: v18.13.0

```
    "graphql": "^16.6.0",
    "@graphql-codegen/cli": "^3.2.1",
    "@graphql-codegen/client-preset": "^2.1.0",
```

**Comment by n1ru4l** [comment]
See https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#fragment-masking

**Comment by dstoyanoff** [comment]
As I mentioned I do use fragment masking and it works fine for the rest of my use-cases. How do I use fragment masking with a mutation?

**Comment by n1ru4l** [comment]
@dstoyanoff you can use `useFragment` also on mutation document results
