### ISSUE TITLE
missing user-agent header sometimes?

### ISSUE THREAD

**Issue by Matzielab** [dotansimha/graphql-code-generator#9087]
### Which packages are impacted by your issue?

@graphql-codegen/cli, @graphql-codegen/fragment-matcher, @graphql-codegen/typescript-operations, @graphql-codegen/typescript

### Describe the bug

We've been using graphql-codegen for a while and recently changed our react-native app to react-native expo. When everything was moved to expo we noticed that the codegen stopped working for the live servers but worked on localhost version of our graphql server. This was only on the new expo repo while the old react-native repo worked fine with the live servers.

After discussing with infra we noticed that they block our schema url request because it's missing the user-agent header. It's strange because it works in the old repo but the package versions and config.yml looks just the same.

Is there some hidden config or any other reason for the generation request not to send a user-agent header?

### Your Example Website or App

private react native app

### Steps to Reproduce the Bug or Issue

run `graphql-codegen --config ./gql/codegen-stage.yml`
request gets blocked by our infra team because of missing user-agent header

### Expected behavior

should generate gql

### Platform

- OS: macOS
- NodeJS: 16.15.1
- `graphql` version: 16.6.0
- @graphql-codegen/cli: 3.2.1,
- @graphql-codegen/fragment-matcher: 3.3.1
- @graphql-codegen/typescript: 2.8.1
- @graphql-codegen/typescript-operations: 2.5.6
- @graphql-codegen/typescript-react-apollo: 3.3.6

**Comment by n1ru4l** [comment]
@Matzielab can you provide a reproduction?

**Comment by ardatan** [comment]
You can send additional headers in the configuration;
```yml
schema: 
  - https://example.com/graphql:
        headers:
            user-agent: "My-User-Agent"
```

**Comment by Matzielab** [comment]
> You can send additional headers in the configuration;
> 
> ```yaml
> schema: 
>   - https://example.com/graphql:
>         headers:
>             user-agent: "My-User-Agent"
> ```

Perfect, this solved it! Thank you very much!
