### ISSUE TITLE
Duplicate type definitions in the output file

### ISSUE THREAD

**Issue by tlehwalder** [dotansimha/graphql-code-generator#9093]
### Which packages are impacted by your issue?

@graphql-codegen/cli, @graphql-codegen/typescript-operations

### Describe the bug

When running graphql-codegen with the provided configuration, the generated output file contains duplicate type definitions for every type. 

I run `graphql-codegen --config codegen.ts`

the config-file (`codegen.ts`):
```typescript
import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  overwrite: true,
  schema: 'http://localhost:4000',
  documents: ['**/src/**/*.tsx'],
  generates: {
    './generated-graphl-types/': {
      preset: "client-preset",
      plugins: ['typescript', 'typescript-operations', 'typescript-react-apollo'],
    },
  },
}

export default config

```

I found similar issues, where the `preset` was named as the root cause, but i tried different presets and either I get an error or face the same issue.

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

1. Run `graphql-codegen --config codegen.ts`with the given config
2. Inspect generated file at `./generated-graphl-types/graphql.ts`

### Expected behavior

Types shouldn't be duplicated in the output file

### Platform

- OS: macOS
- NodeJS: 16.13.0
- graphql@15.8.0
- @graphql-codegen/cli@3.2.1
- @graphql-codegen/client-preset@2.1.0
- @graphql-codegen/fragment-matcher@4.0.1
- @graphql-codegen/typescript-operations@3.0.1
- @graphql-codegen/typescript-react-apollo@3.3.7
- @graphql-codegen/typescript@3.0.1
- graphql-tools@8.3.18

### Codegen Config File

import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  overwrite: true,
  schema: 'http://localhost:4000',
  documents: ['**/src/**/*.tsx'], // '**/src/**/*.ts'
  generates: {
    './generated-graphl-types/': {
      preset: "client-preset",
      plugins: ['typescript', 'typescript-operations', 'typescript-react-apollo'],
    },
  },
}

export default config

**Comment by tlehwalder** [comment]
It looks like the `**` at the beginning of documents was the issue

**Comment by yudiz-bhoomit** [comment]
```typescript

import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: "https://beta.pokeapi.co/graphql/v1beta",
  documents: "./src/**/*.ts",
  generates: {
    "src/gql/": {
      preset: "client",
      plugins: ["@graphql-codegen/typescript-react-apollo"]
    }
  },
};

export default config;
```

I am using this config to geenrate the types and it is generating duplicate types

I am using this plugins with next js
