### ISSUE TITLE
client preset is ignoring a lot of configs

### ISSUE THREAD

**Issue by christiansany** [dotansimha/graphql-code-generator#9104]
### Describe the bug

The Configs that we should be able to use with the new client preset don't do anything.
The client preset should use the typescript plugin underneath, but the config that can be used with the typescript plugin doesn't do anything.

Can we fix this?

In Addition, the client preset generates types for the Schema and the Queries. But in the index.ts file that is generated these types are not exported.

### Steps to Reproduce the Bug or Issue

1. Try it in any project that is using the client preset

### Expected behavior

I want the config for the typescript plugin to also work with the client preset

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

### Codegen Config File

```ts
import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "./__generated__/schema.graphql",
  documents: [
    "./**/*.js",
    "./**/*.vue",
    "./**/*.ts",
    "!./__generated__/schema.graphql",
    "!./**/node_modules/**/*",
    "!./**/*.test.*",
    "!./**/*.d.ts",
  ],
  generates: {
    "./__generated__/gql/": {
      preset: "client",
      presetConfig: {
        gqlTagName: "gql",
        fragmentMasking: { unmaskFunctionName: "getFragmentData" },
        enumsAsConst: true, // Doesn't do anything (probably should not work, but I tried it anyway)
        immutableTypes: true, // Doesn't do anything (probably should not work, but I tried it anyway)
      },
      config: {
        enumsAsConst: true, // Doesn't do anything
        immutableTypes: true, // Doesn't do anything
      },
    },
    "./__generated__/schema.ts": {
      plugins: ["typescript"],
      config: {
        enumsAsConst: true, // Works fine here
        immutableTypes: true, // Works fine here
      },
    },
  },
  ignoreNoDocuments: true,
};

export default config;
```

**Comment by mogelbrod** [comment]
Here's another bug report related to this:
https://github.com/dotansimha/graphql-code-generator/issues/8576#issuecomment-1422205746

**Comment by 2snEM6** [comment]
Any news on this? This is key so for example https://the-guild.dev/graphql/codegen/plugins/typescript/relay-operation-optimizer can be used with `client-preset`

**Comment by n1ru4l** [comment]
See https://github.com/dotansimha/graphql-code-generator/discussions/8993#discussioncomment-6148858 and https://github.com/dotansimha/graphql-code-generator/pull/9496#issuecomment-1586691223
