### ISSUE TITLE
Documentation: update for #9086?

### ISSUE THREAD

**Issue by MrTact** [dotansimha/graphql-code-generator#9154]
### Describe the bug

#9086 looks like it changes the way TypeScript config files are loaded. The website references TypeScript-based config files, calling out the use of cosmiconfig explicitly toward the end: https://github.com/dotansimha/graphql-code-generator/blob/master/website/src/pages/docs/config-reference/codegen-config.mdx

- Does this change invalidate any of that documentation?
- Is there anything new that needs to be called out (e.g. the use of jiti)?

I would normally just submit a PR for something like this, but the project is pretty new to me and that PR is a bit beyond my understanding, so I figured filing an issue was probably a good approach.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

N/A

### Screenshots or Videos

N/A

### Platform

The graphq-codegen website (https://the-guild.dev/graphql/codegen/docs/config-reference/codegen-config)

### Codegen Config File

N/A

**Comment by beerose** [comment]
Hey! The Codegen still uses `cosmiconfig` to manage configuration files, but we dropped `cosmiconfig-typescript-loader` in favor of `jiti` (to be able to support ESM). This means everything works as before, but now you can have a typescript config file along with `type: module` in `package.json`, and you can use `.mts` and `.cts` extensions. I'm gonna add this information to the docs.
