### ISSUE TITLE
Generate one operation per file

### ISSUE THREAD

**Issue by rusted-love** [dotansimha/graphql-code-generator#9160]
### Is your feature request related to a problem? Please describe.

Im using NextJs. Currently I have some unnecessary operations included in my page bundle. 
It can be prevented by file separation that is handled manually.
But it can be done automatically.

### Describe the solution you'd like

It would be amazing to automatically have output of one operation file per `fragment/query/type/mutation/interface` whatever input is.

For example. We have file `cart.graphql`
```
fragment ProductItem {...}
query get_cart {
    ...items{... ProductItem}
}
mutation add_to_cart{
    ... ProductItem
}
```
Output directory structure in `generated` directory.
- `get_cart_Query.ts `
- `add_to_cart_Mutation.ts`
- `ProductItem_Fragment.ts`

Where`add_to_cart_Mutation.ts` and `get_cart_Query.ts` use the same `ProductItem_Fragment.ts` by importing exported ProductItem fragment. 
Only one operation per file.

**Comment by feorex** [comment]
@rusted-love Typescript types are needed for compiler during compilation only. They are not included into JS bundle.

**Comment by rusted-love** [comment]
I mean documents, not types.

**Comment by rusted-love** [comment]
I close the issue. Seems like brand-new `client-preset` is doing his job even better. Thank you for such update!
