### ISSUE TITLE
Negation pattern causing excessive updates with watch mode

### ISSUE THREAD

**Issue by saihaj** [dotansimha/graphql-code-generator#9177]
See https://github.com/dotansimha/graphql-code-generator/pull/9051#discussion_r1133111741

**Comment by milesrichardson** [comment]
Hm, just realized I think this is a duplicate of the one I just opened #9270 

Sorry about that. I included a bunch of `micromatch` examples in my issue though, and I think I found how to workaround it.

**Comment by milesrichardson** [comment]
Sorry, duplicate of #9177, but at least I included a bunch of examples here and I think identified the root cause. I'll work on a fix today.

**Comment by saihaj** [comment]
let's use #9270
