### ISSUE TITLE
[0.14.2] `addToSchema` need to run before all plugins

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#919]
Instead of applying it per-plugin, it should be applied per-file, and only then to execute it.

How to reproduce this?
Use `typescript-common` and `typescript-mongo` together, and use a directive. 
The schema that `typescript-common` gets does not contain the directives `typescript-mongo` adds. 

It requires some refactoring, because that means that we need to load the plugin before executing it, collect all `addToSchema`, built a schema, and then trigger all plugins with the same shared schema.

**Comment by rphansen91** [comment]
```

Updated form version  

✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/gql/types.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ ./src/gql/types.ts
    Failed to load schema from ./src/gql/**/schema.ts:

        Type "Pagination" not found in document.
        Error: Type "Pagination" not found in document.
```

I began seeing this issue after updating from 1.1.0 to 1.15.0, I am using a custom package that I built ts-mongo-codegen. The module exports includes an addToSchema export however it is not found.
