### ISSUE TITLE
Should the client preset forward inputMaybeValue or maybeValue?

### ISSUE THREAD

**Issue by Phoenixmatrix** [dotansimha/graphql-code-generator#9199]
### Which packages are impacted by your issue?

@graphql-codegen/client-preset

### Describe the bug

I'm not 100% sure if its a bug or something I'm missing.
It seems fairly common for people to override inputMaybeValue or maybeValue for better compatibility with existing patterns (eg: using Prisma).

That setting looks to be in the typescript-operations plugin, which is included in the Client preset. So far so good.

However the Client preset seems to only forward [some specific config values](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/presets/client/src/index.ts#L109-L121).

the maybeValue overrides aren't part of this. On the other hand, if you use the Client preset and the operations plugin at the same time, stuff break (expected, by design: duplicating generation and the generates path won't work).

Right now the solution seems to be to manually import the plugins manually, NOT use the Client present, and then one can properly configure inputMaybeValue/maybeValue. With just the Client preset, they are no-ops and do nothing.

Do I have this right? Is there a different way to provide these values that I missed, or is that a bug/omission?

I can also use 2 generate entries, one for client and one for resolvers, but I think if the maybeValue options were forwarded, I could use a single one.

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

- Create a configuration using the Client preset
- set inputMaybeValue: "T | undefined"
- Generate the types
- InputMaybe<T> is NOT set to "T | undefined"

This is particularly relevant when using in combination with the typescript-resolvers plugin

### Expected behavior

`export type InputMaybe<T> = T | undefined;` is correctly generated, as if I was using the plugins individually instead of the preset (this works fine).

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: 18

- `@graphql-codegen/*` version(s): 3.1.1
- `@graphql-codegen/client-preset`: "2.1.1",

### Codegen Config File

import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "./src/graphql/schema.gql",
  documents: ["src/**/*.tsx", "src/**/*.ts"],
  generates: {
    "./src/graphql/types/": {
      present: "client",
      config: {
        inputMaybeValue: "T | undefined",
        maybeValue: "T | null",
      },
    },
  },
};
export default config;

**Comment by n1ru4l** [comment]
@Phoenixmatrix can you please elaborate why you want to use the wrong types? We do not allow customizing `inputMaybeValue`, because that would lead to wrong types and runtime.

**Comment by dotansimha** [comment]
@Phoenixmatrix
for the blog post you mentioned, we are recommending to use those flags with a very specific setup: `typescript` plugin, `typescript-resolvers` plugin and Prisma as ORM. This makes it easier to deal with the strict `null` type that Prisma generates. 

For the `client-preset`, the use-case for using this preset is for frontend (or, client/consumer) setup, and not for resolvers/backend setup.

If you are within a monorepo with both use-case, you can use 2 different outputs in your codegen config.

**Comment by beerose** [comment]
Closing this issue as not relevant. Explanation in the previous comment — https://github.com/dotansimha/graphql-code-generator/issues/9199#issuecomment-1511534486
