### ISSUE TITLE
Load raw graphql schema from URL

### ISSUE THREAD

**Issue by domdomegg** [dotansimha/graphql-code-generator#9214]
### Is your feature request related to a problem? Please describe.

Currently you can specify the schema field to be one of:
- a path to a .graphql schema file
- a path to a .json introspection file
- a URL which retrieves an introspection JSON

If you have a graphql schema file shared at a URL, you can't import it - despite this being behaviour that might be expected.

### Describe the solution you'd like

graphql-codegen supports URLs to graphql schema files. It could use the content-type back from the server to determine whether it's JSON or not, and therefore determine whether to parse it as a introspection JSON or a graphql schema.

### Describe alternatives you've considered

You can implement a [custom schema loader](https://the-guild.dev/graphql/codegen/docs/config-reference/schema-field#loading-api-url-from-typescript-file-example), however this is fairly high overhead for something that should be fairly simple.

You can also write a simple script to curl the file and then just reference that file as if it's a local file - but it feels like something that graphql-codegen should be able to do.

**Comment by saihaj** [comment]
you can import a SDL served from endpoint. see https://github.com/dotansimha/graphql-code-generator/pull/9193

**Comment by domdomegg** [comment]
Ah that looks like exactly what I was searching for. Thanks!
