### ISSUE TITLE
template literal after ( results in Syntax Error: Unexpected Name

### ISSUE THREAD

**Issue by proSingularity** [dotansimha/graphql-code-generator#932]
**Describe the bug**
In my large product, I traverse all `.ts` files (as documents) and look for graphql tags. (Some files do not contain any graphql tags in them.) When `gql-gen` encounters a template literal it fails. I constructed this minimal example. The important part is only the document.

**To Reproduce**
1. Use as schema
```
# example from graphql-code-generator.com, doesn't really matter for the bug
schema {
    query: Query
}

type Query {
    me: User
    user(id: ID!): User
    allUsers: [User]
}

enum Role {
    USER
    ADMIN
}

type User {
    id: ID!
    username: String!
    email: String!
    role: Role!
}
```

2. Use  as documents
```
const templateLiteral = "foobar";

function fn(text: string) {
    console.log(`quo ${templateLiteral}`);
}
```

3. Run the following command: `gql-gen`

**Resulting error**
```
yarn run v1.7.0
$ gql-gen
  √ Parse configuration
  > Generate outputs
    √ Generate ./server-schema.ts
    > Generate ./client-queries.ts
      √ Load GraphQL schemas
      × Load GraphQL documents
        → Syntax Error: Unexpected Name "quo"
        Generate


     We found 1 errors

     Failed to generate [object Object]
Syntax Error: Unexpected Name "quo"

./code-gen-test.ts (1:1)
1: quo
    ^

Something went wrong
error Command failed with exit code 1.
```

**Expected behavior**

**Schema/Documents**
If possible and relevant, please provide your GraphQL schema and GraphQL documents.

**Environment:**
 - OS: Windows 7
 - Codegen: 4.0.2 and 4.0.3 (it used to work in 4.0.1, but there is another bug which is why I depend on 4.0.3)
 - Node: 8.11.3

**Additional context**
The following usage of template literals does not result in an error.
`const nonProblematicLiteralUsage = `working template literal ${templateLiteral}}`

**Comment by kamilkisiela** [comment]
@proSingularity could you check `0.15.0-alpha.a1d3b95d`?

**Comment by proSingularity** [comment]
@kamilkisiela Hi and thank you very much! Both the error in the minimal example as well as the template literal related errors in our large project are solved now :+1:  Good job,

**Comment by kamilkisiela** [comment]
@proSingularity Super nice! I'll release a stable version today or maybe tomorrow 👍

**Comment by kamilkisiela** [comment]
`v0.14.5` is out :)
