### ISSUE TITLE
Webpack Plugin

### ISSUE THREAD

**Issue by vlasenko** [dotansimha/graphql-code-generator#933]
**Is your feature request related to a problem? Please describe.**
We would like to use Webpack with GraphQL Code Generator in watch mode to achieve live reload of TypeScript types when GraphQL schema files change.

**Describe the solution you'd like**
A Webpack Plugin that processes only those files on the filesystem that make up the Webpack project by reading Webpack modules list and generating output file somewhere on the file system, so that TypeScript compiler or other tools could see the output file and changes to it. Preferably the configuration of the plugin should be as simple as possible.

**Describe alternatives you've considered**
We considered alternative of using GraphQL Code Generator cli in watch mode, but it complicates setup for the developer - need to install watchman and it does not take into account that graphql files on the filesystem might not be part of a Webpack project, because they are not get imported and need not to be processed.

**Additional context**
It would be great to share various use cases for Webpack olugin, difficulties with implementation, roadmap, etc.

**Comment by dotansimha** [comment]
Hi @vlasenko 

We had a webpack plugin before, which had a lot of issues, because of the way typescript detects changes and recompiles.

Please see:
https://github.com/dotansimha/graphql-code-generator/issues/829
https://github.com/dotansimha/graphql-code-generator/issues/897

Keeping open for reference, and because we might find a solution in the future.

**Comment by vlasenko** [comment]
Thank you @dotansimha 

I have seen several issues with the example and added issues here:
https://github.com/kamilkisiela/graphql-webpack/issues
as well as Pull Requests to resolve them here:
https://github.com/kamilkisiela/graphql-webpack/pulls

Since the `graphql-webpack` example is not using the webpack plugin from source code of the generator with tag `v0.13.0`, but rather uses some previous code I'm blocked to troubleshoot further. 

@kamilkisiela Could you help me to identify exact commit of `graphql-code-generator` that contains the code of the plugin which is used by the example, or could you update the example to use the code from tag `v0.13.0`?

**Comment by dotansimha** [comment]
Closing this for now, let's track it here: https://github.com/dotansimha/graphql-code-generator/issues/1828
