### ISSUE TITLE
Generated fragment-masking.ts is not compatible with noUncheckedIndexedAccess on upcoming RC

### ISSUE THREAD

**Issue by 2snEM6** [dotansimha/graphql-code-generator#9383]
### Describe the bug

As I mentioned here: https://github.com/dotansimha/graphql-code-generator/pull/9196#discussion_r1189887129 (#9196)

if an user has noUncheckedIndexedAccess set to true on their tsconfig, then `fields` might be undefined, causing type checking to fail.

Code is here: https://github.com/dotansimha/graphql-code-generator/pull/9196/files/7ad08f56be5ff8d0ee7c93250c5988cb3fed2ea4#diff-f6309550f61b610a24949b53525e396490f4af6dbcc264d82cb6bfd3ea9ea8a8R51

### Your Example Website or App

https://github.com/dotansimha/graphql-code-generator/pull/9196/files/7ad08f56be5ff8d0ee7c93250c5988cb3fed2ea4#diff-f6309550f61b610a24949b53525e396490f4af6dbcc264d82cb6bfd3ea9ea8a8R51

### Steps to Reproduce the Bug or Issue

1. Run type checking with tsconfig noUncheckedIndexedAccess on against https://github.com/dotansimha/graphql-code-generator/pull/9196#discussion_r1189887129
2. Watch TS complain about possible undefined index access for the `fields` variable

### Expected behavior

`fields` variable should be checked for undefined/null values

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by beerose** [comment]
Fixed in https://github.com/dotansimha/graphql-code-generator/pull/9385
