### ISSUE TITLE
Prune generated typescript types

### ISSUE THREAD

**Issue by cipriancaba** [dotansimha/graphql-code-generator#9388]
### Is your feature request related to a problem? Please describe.

`codegen` will generate typescript types for all the types it finds in the graphql schema. These types end up being exported from the generated ts files and bloat up the bundle size of the app

Given the following schema on the https://the-guild.dev/graphql/codegen#live-demo

```
scalar Date

schema {
query: Query
}

type Query {
me: User!
user(id: ID!): User
allUsers: [User]
search(term: String!): [SearchResult!]!
myChats: [Chat!]!
}

enum Role {
USER
ADMIN
}

interface Node {
id: ID!
}

type StockOrder {
id: Int!
orderNumber: String!
name: String!
}

union SearchResult = User | Chat | ChatMessage

type User implements Node {
id: ID!
username: String!
email: String!
role: Role!
}

type Chat implements Node {
id: ID!
users: [User!]!
messages: [ChatMessage!]!
}

type ChatMessage implements Node {
id: ID!
content: String!
time: Date!
user: User!
}
```

The generated file will contain this unused type `StockOrder`:

```
export type StockOrder = {
typename?: 'StockOrder';
id: Scalars['Int'];
orderNumber: Scalars['String'];
name: Scalars['String'];
};
```

Ideally this will be omitted from the generated results

### Describe the solution you'd like

Don't generate extra types that are not used in the specified `documents`

**Comment by saihaj** [comment]
>These types end up being exported from the generated ts files and bloat up the bundle size of the app

types shouldn't be bloating the end bundles. Types the shipping to browser should be removed.

If this suggestion is related to not including schema then it makes more sense to have it in discussion here https://github.com/dotansimha/graphql-code-generator/discussions/8693
