### ISSUE TITLE
Typescript-Resolvers' generated code has errors if noUnusedParameters option enabled in tsconfig

### ISSUE THREAD

**Issue by AlexLorenzi** [dotansimha/graphql-code-generator#9486]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-resolvers

### Describe the bug

Are updating to the typescript-resolver v4.0.0 we're running into an issue with our typescript compilation. In our tsconfig.json settings, we enable the `noUnusedParameters` check, and it seems that [this](https://github.com/dotansimha/graphql-code-generator/pull/9229) change introduced some generics that is causing that check to fail.

We're working around this by using the add plugin to prepend a `// @ts-nocheck` at the top of the file, but it'd be nice to have the files included in the checks

### Your Example Website or App

https://github.com/AlexLorenzi/codegen-example

### Steps to Reproduce the Bug or Issue

1. Checkout example project
2. Run `yarn` and `yarn generate`
3. Run `yarn tsc`

### Expected behavior

Expect generated code to compile successfully 

### Platform

- OS: macOS
- NodeJS: v16.20.0
- `graphql` version: 16.6.0
- `@graphql-codegen/*` version(s): 4.0.0

### Codegen Config File

```typescript
import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
    schema: './schema.graphqls',
    generates: {
        './src/graphql/schema-types.generated.ts': {
            plugins: ['typescript', 'typescript-resolvers']
        }
    }
}
export default config
```

**Comment by eddeee888** [comment]
Hello 👋 

This is the same as https://github.com/dotansimha/graphql-code-generator/issues/9486. I've left a reply [here](https://github.com/dotansimha/graphql-code-generator/issues/9498#issuecomment-1598550662).

Please discuss in that issue. Thanks!
