### ISSUE TITLE
[client-preset] `FragmentType` returns type `never` using client-preset 4.0.0

### ISSUE THREAD

**Issue by DerTimonius** [dotansimha/graphql-code-generator#9493]
### Which packages are impacted by your issue?

@graphql-codegen/client-preset

### Describe the bug

Hi everyone, thank you for this great package!
We have been using codegen for a while now and recently updated the `client-preset` from 2.0.0 to 4.0.0 - now a lot of TypeScript errors are popping up across our react/next.js application. The errors could be found in every component that used fragments or that passed the fragment information down to a different component. Upon further inspection I was able to figure out that `FragmentType` is now returning `never` like in the screenshot below

<img width="376" alt="image" src="https://github.com/dotansimha/graphql-code-generator/assets/103483059/339b65ed-7685-42c5-8f9e-b66fa3228c5c">

It's still possible to access the information inside the fragment with `useFragment`, but the type is now `unknown`
<img width="468" alt="image" src="https://github.com/dotansimha/graphql-code-generator/assets/103483059/6a502127-a118-4768-bced-83200b9b6ede">

### Your Example Website or App

private repo

### Steps to Reproduce the Bug or Issue

1. Follow the [guide to create fragments](https://the-guild.dev/graphql/codegen/docs/guides/react-vue#writing-graphql-fragments)
My fragment is similar to this:
```ts
const UserInfoFragment = graphql(/* GraphQL */ `
  fragment UserInfoFragment on User {
    id
    profile {
      id
      firstName
      lastName
    }
  }
`);
```
2. Type it using `FragmentType<typeof UserInfoFragment>`
3. Hover over the type or use two-slash queries
4. See type `never`

### Expected behavior

Before we updated the `client-preset`, `FragmentType` did return the correct type information
<img width="515" alt="image" src="https://github.com/dotansimha/graphql-code-generator/assets/103483059/68d69b51-bdec-4a90-9454-44be14e5a86b">

### Platform

- OS: macOS
- NodeJS: v18.16.0
- `graphql` version: 16.6.0
- `@graphql-codegen/*` version(s): 
	- cli: 4.0.1
	- client-preset: 4.0.0

While trying for a quick fix I also tried re-adding `@graphql-codegen/typescript` and `@graphql-codegen/typescript-urql` but this did not help.

### Codegen Config File

```yaml
schema: supergraph.graphql
documents: [utils/**/*.ts, pages/**/*.tsx, components/**/*.tsx, hooks/*.ts]
generates:
  gql/:
    preset: 'client'
    plugins: []
    config:
      dedupeFragments: true
```

### Additional context

In the `fragment-masking.ts` file I found this error:
<img width="913" alt="image" src="https://github.com/dotansimha/graphql-code-generator/assets/103483059/abf201f7-2b6e-4bf3-a47b-1c913613d851">

I'm pretty sure that no one in our team touched this file, so this might have happened on updating the `client-preset` version.

**Comment by tnyo43** [comment]
Which version of `@graphql-typed-document-node/core` do you use?
You need to use the latest version (v3.2.0) to use [`DocumentTypeDecoration` ](https://github.com/dotansimha/graphql-typed-document-node/pull/154).

(check out the [CHANGELOG](https://github.com/dotansimha/graphql-code-generator/blob/2139f1db5704aa34a0cd89342736bf67ec556da3/packages/plugins/typescript/gql-tag-operations/CHANGELOG.md?plain=1#L28))

**Comment by DerTimonius** [comment]
@tnyo43 Thanks for the running, found two different versions in the lockfile (3.2.0 and 3.1.1). Apparently TS did not recognize v3.2.0.

Was able to resolve this by adding the correct version to the resolutions in the `package.json` file!
