### ISSUE TITLE
Add more documentation on how to write plugins in TypeScript

### ISSUE THREAD

**Issue by kroeder** [dotansimha/graphql-code-generator#951]
**Is your feature request related to a problem? Please describe.**
Since I'm in an Angular environment I wanted to write my plugin in TypeScript. However the only thing in the documentation is this info that you need to compile your plugin before you can run it with `gql-gen`.

What I found out by code-surfing through your repo: `codegen-templates-scripts build` 
`codegen-templates-scripts build` worked, `tsc` did not

I would contribute to the docs but I don't know your prefered way of doing this

**Describe the solution you'd like**
Make TypeScript users happy 🙂 Every plugin in your repo is written in TypeScript and yet you have only docs for vanilla js

**Describe alternatives you've considered**
Writing everything in JavaScript after hours of debugging

**Comment by jreeter** [comment]
I would also like to see this. Specially a more detailed example on generating code with a custom handlebars templates.

**Comment by kamilkisiela** [comment]
https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin :)

**Comment by dotansimha** [comment]
@kamilkisiela is right. 

@kroeder  @jreeter, please read this: https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin 

Using TypeScript to write the template isn't different, and you can take a look at the built-in plugins code here: https://github.com/dotansimha/graphql-code-generator/tree/master/packages/plugins , they are all written in TS. 

The `codegen-templates-scripts` is just a wrapper around Webpack with TypeScript and `.handlebars` support.

**Comment by kroeder** [comment]
Have you tried to write a plugin in typescript by just reading the docs and use `tsc` in combination with  handlebars? As mentioned in my opening post: I was not able to do that

I only figured everything out by putting in a lot of effort and reading your implementations and build scripts you are using yourself (+ this wrapper you are using is not in the documentation so I really am afraid that these are going to break without e.g. a major release because they are not part of the public documentation 🙁 ) 

If you also want people to start code-surfing in order to figure out how this works, then I suggest to put at least the link "packages/plugins" into the documentation

If you think it's fine that way I can live with that. I just want to improve things for others and post about issues I had 🙂

**Comment by dotansimha** [comment]
Hi @kroeder 

Codegen plugins has a very simple interface you need to follow: 
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/yml-config-types.ts#L67-L71

You can use JavaScript or TypeScript to write it. If you wish to use TypeScript, you need to compile your code with `tsc` or `babel`. 
If you wish to use Handlebars, you can either add your Handlebars template as string in your TypeScript code file, or you can load it from a `.handlebars` file (using your preferred way - either with a bundler like Webpack or similar). 

During the recent releases, we tried to avoid using Handlebars as integrated part of the codegen, and only use it inside the plugins. In matter of fact, we are looking for a better alternative for implementing the plugins, without using Handlebars at all, so I can't recommend you to use it. That's also the reason that we are keeping it as internal and not exposing or documenting it at the moment.

I can recommend on trying to implement it in an easier way using `visit` (see https://github.com/dotansimha/graphql-code-generator/pull/917 for examples, I'm trying to do it now for the Flow plugin).
