### ISSUE TITLE
Add more hints to error message "Found x errors in your documents"

### ISSUE THREAD

**Issue by kroeder** [dotansimha/graphql-code-generator#953]
**Is your feature request related to a problem? Please describe.**
There might be an error in one of my ```gql`...` ``` DocumentNodes and gql-gen prints

```
[12:39:39]Something went wrong
 Generate [failed]
[12:39:39] → Found 1 errors in your documents
```

How should I know where to look? Is there a way to identify the source of the Problem?

**Describe the solution you'd like**
Print one of the following
- .graphql file name
- file name where  ```gql`...` ``` failed
- Query or Mutation name if possible

**Comment by kroeder** [comment]
Weird. PowerShell actually printed errors while gitbash did not ... is this a known thing?

**Comment by RadAcademy** [comment]
Yes this is frustrating beyond belief, this:

[2] Something went wrong
[2] [14:39:28] → Found 2 errors in your documents
[2] [14:39:28] Generate src/client/app/core/graphql.ts [failed]
[2] [14:39:28] → Found 2 errors in your documents
[2] [14:39:28] Generate outputs [failed]

Is not helpful

**Comment by kroeder** [comment]
Have you seen my comment? Can you try if it works with a different CLI tool? I got all locations using powershell

**Comment by dotansimha** [comment]
Hi @kroeder @RadAcademy 
I guess it's related to the way we print the errors. It looks the same as this issue: https://github.com/dotansimha/graphql-code-generator/issues/953 

Closing, and we'll look into it :)
