### ISSUE TITLE
Inconsistent enum name

### ISSUE THREAD

**Issue by robertu7** [dotansimha/graphql-code-generator#9543]
### Which packages are impacted by your issue?

@graphql-codegen/cli, @graphql-codegen/client-preset

### Describe the bug

Generated generic type name (`SearchAPIVersion`) is not equals to enum type (`SearchApiVersion`):

```
src/gql/graphql.ts:2413:24 - error TS2552: Cannot find name 'SearchAPIVersion'. Did you mean 'SearchApiVersion'?

2413   version?: InputMaybe<SearchAPIVersion>;
                            ~~~~~~~~~~~~~~~~

  src/gql/graphql.ts:2430:13
    2430 export enum SearchApiVersion {
                     ~~~~~~~~~~~~~~~~
    'SearchApiVersion' is declared here.


Found 1 error in src/gql/graphql.ts:2413
```

### Your Example Website or App

https://github.com/thematters/matters-web/tree/a213f30c951925864e2b8de56a116b298b0dbfeb

### Steps to Reproduce the Bug or Issue

1. `npm install`
2. `npm run gen:type`
3. `npm run lint`
4. error is being throw

### Expected behavior

No type error

### Platform

- OS: macOS
- NodeJS: 16.14.0
- `graphql` version: 14.7.0
- `@graphql-codegen/cli` version(s): 4.0.1
- `@graphql-codegen/client-preset` version(s): 4.0.1

### Codegen Config File

```
import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: [
    process.env.GRAPHQL_SCHEMA_URL as string,
    './src/common/utils/types/index.ts',
  ],
  documents: ['src/**/*.{ts,tsx}'],
  generates: {
    'src/gql/graphql.ts': {
      plugins: ['typescript', 'typescript-operations'],
    },
  },
}

export default config
```

**Comment by BuddhaBing** [comment]
same issue

**Comment by enisdenjo** [comment]
Hey @robertu7, I tried running your reproduction but it doesn't work - it doesn't allow me to generate types. Would you mind providing me an updated repro?

Sorry for the wait, thanks in advance!

**Comment by enisdenjo** [comment]
It seems to be a graphql-js issue related to v14. Please upgrade to v15+. If the issue persists, feel free to re-open this issue.
