### ISSUE TITLE
Please create a pre-commit plugin

### ISSUE THREAD

**Issue by Lexicality** [dotansimha/graphql-code-generator#9561]
### Is your feature request related to a problem? Please describe.

I would like to ensure that I never forget to regenerate my generated types file when I make changes to my GraphQL schema

### Describe the solution you'd like

I would like an official hook for the [pre-commit](https://pre-commit.com/) tool which will catch my mistake before I can even commit it

### Describe alternatives you've considered

I have considered writing a github action to catch this after I have pushed, however that means I have to commit, push, realise my mistake, fix, commit and push again which is frustrating.

**Comment by dotansimha** [comment]
Hi @Lexicality 
You can use tools like `husky` (https://www.npmjs.com/package/husky) to run codegen in a custom flow that matches your needs. 
I also recommend not committing your generated files, and run Codegen locally in development, and also in CI. This will ensure you always have the up to date generated artifacts in all environments.
