### ISSUE TITLE
Got @graphql-tools/graphql-file-loader@8.0.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.20.0" on @graphql-codegen/cli install

### ISSUE THREAD

**Issue by gowtham-v-yubi** [dotansimha/graphql-code-generator#9602]
### Describe the bug

I have tried to install the `@graphql-codegen/cli` got the below error
```
gtm gql % yarn add --dev typescript @graphql-codegen/cli
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @graphql-tools/graphql-file-loader@8.0.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
What is the compatable version for node version 14.20.0
```
(gtm gql % yarn add dev typescript @graphql-codegen/cli @graphql-codegen/client-preset
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error inotify@1.4.6: The platform "darwin" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.)
```

How to resolve this errors
Node version v14.20.0

### Your Example Website or App

could not reproduce in any other place

### Steps to Reproduce the Bug or Issue

run `yarn add dev typescript @graphql-codegen/cli @graphql-codegen/client-preset` and `yarn add --dev typescript @graphql-codegen/cli` in node version v14.20.0

### Expected behavior

dependencies should install without any issue

### Platform

- OS: [macOS]
- NodeJS: [14.20.0]
- `graphql` version: [e.g. 16.8.0]
- `@graphql-codegen/*` version(s): [latest]

**Comment by saihaj** [comment]
downgrade one major version and I think that should help but would not recommend doing that instead should upgrade to stable LTS Node.js version
