### ISSUE TITLE
 Cannot find module `graphql-codegen-core` error when generating types

### ISSUE THREAD

**Issue by emmanuelbuah** [dotansimha/graphql-code-generator#962]
**Describe the bug**
 Cannot find module `graphql-codegen-core` error when generating types

**To Reproduce**
1. Install typescript-server plugin
2. Execute type generation 
3. Errors with 
```
 Unable to load template plugin matching 'typescript-server'.
               Reason:
                 Cannot find module 'graphql-codegen-core'
```

**Expected behavior**
`graphql-codegen-core` should be a dependency of `graphql-codegen-typescript-server` not a devDependency. Its used in the codebase and therefore should not be a devDependency.

**Schema/Documents**
N/A

**Environment:**
 - OS: Mac
 - Codegen: 0.14.5
 - Node: 10.x

**Additional context**

**Comment by kamilkisiela** [comment]
Could you show us what packages that are related to the codegen you have installed?

**Comment by dotansimha** [comment]
@emmanuelbuah Not sure which setup do you use. 
Which version of NPM/Yarn/Node do you use? 
`graphql-codegen-core` should be installed only by `graphql-code-generator`, and not by the plugins.

**Comment by emmanuelbuah** [comment]
@dotansimha I musing lerna so its possible Lerna is playing some dirty tricks on install

**Comment by dotansimha** [comment]
Thanks @emmanuelbuah !
Any chance you can create a small reproduction repo? We are using the codegen in projects that using Lerna (with Lerna+Yarn or Yarn Workspaces) and it seems to work.
Also - where did you put the dependency for the codegen? it the root `package.json` or inside a specific lerna package?

**Comment by emmanuelbuah** [comment]
It's inside my lerna packages. I delete the package-lock.json file and run `npm install` at root which addressed the issue. I'm going to work on trying to reproduce the issue and if I can, I will set up a repo with steps to reproduce here.

**Comment by emmanuelbuah** [comment]
@dotansimha I encountered the issue again. Regenerating the package lock file doesn't address the issue. npm/yarn will only hoist packages if multiple packages depend on the same version of a package. As it stands now if you install just `graphql-codegen-typescript-server` from npm, it will install `graphql-codegen-typescript-common` as a sub package which will in turn contains `graphql-codegen-core`. 

`graphql-codegen-typescript-server` will not have access to `graphql-codegen-core` because its not an install dependency but rather a devDependency.

 I'm not sure why `graphql-codegen-core` is a devDependency in `graphql-codegen-typescript-server` instead of a regular dependency for thats not the case in similar/other packages like say `graphql-codegen-typescript-common` or `graphql-code-generator`?

**Comment by emmanuelbuah** [comment]
The fix was to delete both the lock file and the node_module folder. Even though I have a fix. I'd like to get to the bottom of this issue. I will take some time to submit a repo reproducing the issue.
