### ISSUE TITLE
schema-ast: can we remove the validation as I want to use this with other plug in

### ISSUE THREAD

**Issue by ganeshpms** [dotansimha/graphql-code-generator#967]
can we remove the validation from `schema-ast` until unless it is giving any special value? I want to use this with other plug-in and want to generate the `.ts` file. The validation forcing me to have `.graphql` file extension. 

for example the below configuration is not working.

`
libs/schema/src/lib/schema.graphql.ts:

    plugins:
    - add: // Auto Generated. Please don't edit, the changes will be overwritten
    - time: 
    - typescript-common
    - add: export const typeDefs = "  
    - schema-ast
    - add: "\"};"
`

**Comment by dotansimha** [comment]
Makes sense. I think we can only apply this validation when `schema-ast` is specified by itself, with no other plugins. 
Fixed in: https://github.com/dotansimha/graphql-code-generator/commit/b8839896879a8e04942107f7ab7198547fe15915

**Comment by kamilkisiela** [comment]
Released in `v0.15.0`
