### ISSUE TITLE
How to specify Version when add  graphql-code-generator

### ISSUE THREAD

**Issue by Kunjahamed-P** [dotansimha/graphql-code-generator#971]
How to specify Version when install graphql-code-generator ie: i want install 0.10.3 version. no need to install latest version. is it possible ?

i try npm install graphql-code-generator VB0.10.3 but this not work.

also try yarn add -D graphql-code-generator graphql@0.10.3   but its run , but not installed .10.3 version its installed 0.14.5

**Comment by kamilkisiela** [comment]
```
yarn add -D graphql-code-generator@X.X.X
```

**Comment by kamilkisiela** [comment]
npm: https://docs.npmjs.com/cli/install.html
yarn: https://yarnpkg.com/en/docs/cli/add#toc-adding-dependencies
