### ISSUE TITLE
Provide a way to use `verbatimModuleSyntax` tsconfig option

### ISSUE THREAD

**Issue by none23** [dotansimha/graphql-code-generator#9710]
### Is your feature request related to a problem? Please describe.

When using `preset: client`, the generated files  import types as values.

E.g. 
```ts
 import { ResultOf, DocumentTypeDecoration, TypedDocumentNode } from '@graphql-typed-document-node/core';
 ```
 instead of 
 ```ts
 import type { ResultOf, DocumentTypeDecoration, TypedDocumentNode } from '@graphql-typed-document-node/core';
 ```
 
 This causes the following error if `verbatimModuleSyntax` is set to `true` in `tsconfig.json`:
 `Type error: 'ResultOf' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.`

### Describe the solution you'd like

Using type-only imports inside generated files by default, or providing a way to opt into such behavior.

### Describe alternatives you've considered

I have to disable `verbatimModuleSyntax` for now.

**Comment by xrnoz** [comment]
Same problem. Cannot disable `verbatimModuleSyntax` because is required by Svelte.

**Comment by vkynchev** [comment]
@none23 @xrnoz duplicate of #9595... solution -> https://github.com/dotansimha/graphql-code-generator/issues/9595#issuecomment-1682041289

**Comment by none23** [comment]
Thanks, @vkynchev
