### ISSUE TITLE
react query v5 support

### ISSUE THREAD

**Issue by Zerebokep** [dotansimha/graphql-code-generator#9712]
### Is your feature request related to a problem? Please describe.

React Query v5 has been released: https://tanstack.com/query/latest/

### Describe the solution you'd like

Any plans to support v5? :)

**Comment by dcsky1** [comment]
+1. In need of this for a massive project if we want to migrate to rq5.

**Comment by qlaffont** [comment]
+1 with SolidJS Support

**Comment by saihaj** [comment]
duplicate https://github.com/dotansimha/graphql-code-generator-community/issues/318
