### ISSUE TITLE
`useFragment` in Vue project is not reactive (using client-preset)

### ISSUE THREAD

**Issue by nlepage** [dotansimha/graphql-code-generator#9767]
### Which packages are impacted by your issue?

@graphql-codegen/client-preset

### Describe the bug

The value returned by `useFragment()` generated by client-preset in a Vue project is not reactive:

```ts
const myValue = useFragment(MyFragment, props.myProp) // myValue is not reactive
```

Given that `useFragment` just returns its second parameter, and given that this second parameter is a value extracted from props while the setup script is executed, this behavior is expected from a Vue app, but I'm not sure this is what we expect from `useFragment`.

It can be worked around by wrapping the call to `useFragment` in a computed ref:

```ts
const myValue = computed(() => {
  return useFragment(MyFragment, props.myProp)
})
```

### Your Example Website or App

https://github.com/nlepage/graphql-codegen-client-preset-vue-usefragment-reactivity/

### Steps to Reproduce the Bug or Issue

1. install dependencies `npm install`
2. start GraphQL API in a first shell `npm run start:api`
3. start Vue app in a second shell `npm run start:front`
4. see that "Count extracted from props by useFragment" in FragmentCounter Component keeps `undefined`
5. click the "Increment Query Counter / Fragment Counter" button
6. see that "Count extracted from props by useFragment" in FragmentCounter Component still keeps `undefined`

The example also shows a similar behavior with a shallow ref containing an object given to a sub-component.

### Expected behavior

The value returned by `useFragment()` should be reactive, without having to wrap it in a computed ref.

I am not sure how this should be achieved, returning a computed ref from `useFragment()` would be a breaking change.

It seems that `useFragment` is used just for typing, wouldn't it be possible to give the correct type directly to the prop instead of `FragmentType<MyFragment>`?

### Platform

- OS: Linux
- NodeJS: 18.18.2
- `graphql` version: 16.8.1
- `@graphql-codegen/cli` version: 5.0.0
- `@graphql-codegen/client-preset` version: 4.1.0

### Codegen Config File

```ts
import { CodegenConfig } from '@graphql-codegen/cli'
 
const config: CodegenConfig = {
  schema: 'http://localhost:3000/graphql',
  documents: ['front/src/**/*.vue'],
  generates: {
    './front/src/gql/': {
      preset: 'client',
      config: {
        useTypeImports: true,
      },
    }
  }
}
 
export default config
```

### Additional context

Cheers!

**Comment by bmulholland** [comment]
This might be a naive answer, but elsewhere when you need a prop to be reactive you have to return it from a function. So like `const myValue = useFragment(MyFragment, **() => **props.myProp)`

e.g. that's what you do for watches. Could that fix your issue?

**Comment by saihaj** [comment]
in react world we don't have it as a hook, it is just a name of function which you can rename see: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#the-usefragment-helper

I am not a vue expert but I think it makes sense it is not reactive

**Comment by bmulholland** [comment]
The expectation in Vue is that it's reactive. If this function won't be changed, then the Vue example needs to be updated, because it's going to break expectations that Vue folk will have. Specifically: https://the-guild.dev/graphql/codegen/docs/guides/react-vue#writing-graphql-fragments, it should be `const filmObj = computed(() => useFragment(FilmFragment, props.film))`.

Thing is, this is quite a lot of boiler plate to write every time :\

**Comment by bmulholland** [comment]
Note that the above causes problems: typescript thinks fields aren't being used when they are. See https://github.com/dotansimha/graphql-code-generator/issues/10127
