### ISSUE TITLE
[DOCS] [DX] [Guide: GraphQL Yoga / Apollo Server with Server Preset] More sensible defaults

### ISSUE THREAD

**Issue by konhi** [dotansimha/graphql-code-generator#9830]
### Is your feature request related to a problem? Please describe.

The way this config generates codes naturally makes users do resolvers chaining. This is a standard GraphQL practice documented by [Apollo Docs > Server > Resolvers > Resolver Chains](https://www.apollographql.com/docs/apollo-server/data/resolvers#resolver-chains).

It was unexpected to me that this wasn't supported by default and the types were wrong. I spent few hours trying to look for a solution. Eventually, I realised it's explained in `typescript-resolvers` plugin (https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers#integration-with-apollo-server). I think we should change the docs on this guide, so DX will be better.

I also mentioned this issue directly on plugin page: https://github.com/eddeee888/graphql-code-generator-plugins/issues/225

Other people also had this problem:
- https://github.com/dotansimha/graphql-code-generator/issues/3828
- https://github.com/dotansimha/graphql-code-generator/issues/1219

### Describe the solution you'd like

Update the docs in guide: https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga-with-server-preset#3-configure-codegen-config

Current:

```ts
import type { CodegenConfig } from '@graphql-codegen/cli'
 
const config: CodegenConfig = {
  generates: {
    './resolvers-types.ts': {
      config: {
        useIndexSignature: true
      },
      plugins: ['typescript', 'typescript-resolvers']
    }
  }
}
export default config
```

Expected:

```ts
import type { CodegenConfig } from '@graphql-codegen/cli'
import { defineConfig } from '@eddeee888/gcg-typescript-resolver-files'
 
const config: CodegenConfig = {
  schema: '**/schema.graphql',
  generates: {
    'src/schema': defineConfig({
      typesPluginsConfig: {
        /* Use on Apollo Server if you want resolver chains. https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers#integration-with-apollo-server
        useIndexSignature: true,
        defaultMapper: 'Partial<{T}>',
       */
      }
    })
  }
}
export default config
```

**Comment by arjunyel** [comment]
if you are using resolver chains then you will need nested partials using [`utility-types`](https://github.com/piotrwitek/utility-types) https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers#allow-deep-partial-with-utility-types

```typescript
const config: CodegenConfig = {
 schema: "**/schema.graphql",
 generates: {
  "src/schema": defineConfig({
   add: {
    "./types.generated.ts": {
     content: "import type { DeepPartial } from 'utility-types';",
    },
   },
   typesPluginsConfig: {
    defaultMapper: "DeepPartial<{T}>",
   },
  }),
 },
};
```

**Comment by eddeee888** [comment]
Thanks for opening this issue guys 🙂

I've left the replies in the [issue opened in server preset repo](https://github.com/eddeee888/graphql-code-generator-plugins/issues/225). I'm posting the references here to make it easier:

- [Reason](https://github.com/eddeee888/graphql-code-generator-plugins/issues/225#issuecomment-1968890271) why using `Partial` or `DeepPartial` could lead to runtime errors.
- [How to implement resolver chaining with mapper (either `typescript-resolvers` plugin or Server Preset)](https://github.com/eddeee888/graphql-code-generator-plugins/issues/225#issuecomment-1975105522).

I'll look to clarify these behaviours by updating the related docs or blog posts.
