### ISSUE TITLE
Latest version on npm is not the right one

### ISSUE THREAD

**Issue by adrienharnay** [dotansimha/graphql-code-generator#9832]
### Which packages are impacted by your issue?

@graphql-codegen/cli, @graphql-codegen/add, @graphql-codegen/introspection, @graphql-codegen/gql-tag-operations, @graphql-codegen/typed-document-node, @graphql-codegen/typescript

### Describe the bug

The latest version on npm is still 5.0.0, while 5.0.1 has been released 20 days ago.

### Your Example Website or App

/

### Steps to Reproduce the Bug or Issue

https://www.npmjs.com/package/@graphql-codegen/add?activeTab=versions

### Expected behavior

Latest version released is set to latest on npm

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by eddeee888** [comment]
Thank you for reporting this. Looks like there was an issue in 5.0.1 release, and 5.0.2 has been released successfully as `latest`. 

I'll close this for now. Please let me know if it's still an issue.
