### ISSUE TITLE
Document Query Output Types Renamed

### ISSUE THREAD

**Issue by benafa** [dotansimha/graphql-code-generator#984]
**Describe the bug**
When I'm using the code generator on a document, within a generated query namespace, the type of the output is renamed to the name of the query 

In addition, fields within the output type have their types renamed to the name of the field.

**To Reproduce**
In a document, have a query whose name is not the same as the output type name e.g. if i have a query 'query_name(x): output_name', the output type in the query namespace is query_name instead of output_name, but within the type called query_name it has '_typename?: "output_name"' so it knows what the type should be but renames it. 

e.g. 
document: 
`qgl'query GetBook($id: Int!) { GetBook(id: $id) }'`

schema: 
```
type Book { id: Int!, title: string, publisher: BookPublisher }
type BookPublisher {id: int, name: string}
type Query {
  GetBook(id: int!): Book!
}
```

generated types file: 
```
export namespace GetBook {
  export type Variables = {
     id: number;
  }
  export type Query = {
     _typename? = "Query"
     GetBook: GetBook
  }
  export type GetBook = {
     _typename? = "Book"
     id: int
     title: string
     publisher: Publisher
  }
  export type Publisher = {
     _typename = "BookPublisher"
     id: int
     name: string
  }
}

```
**Expected behavior**
I would expect inside Query the type of GetBook to be Book not GetBook, and for the type of publisher to be BookPublisher not Publisher

```
export namespace GetBook {
  export type Variables = {
     id: number;
  }
  export type Query = {
     _typename? = "Query"
     GetBook: Book
  }
  export type Book = {
     _typename? = "Book"
     id: int
     title: string
     publisher: BookPublisher
  }
  export type BookPublisher = {
     _typename = "BookPublisher"
     id: int
     name: string
  }
}

```

**Environment:**
 - OS: Red Hat 6.8
 - Codegen: 0.14.5
 - Node: Node 8.11.3

**Comment by dotansimha** [comment]
Hi @benafa 
We are using the name of the field as the name of the generated interface, because the interface name `Book` might cause confusion because it's not necessarily has the same fields as the `type Book` because of the selection set you queried. 

If you wish to get a different output for those interfaces, you can use GraphQL aliases and change the name of the fields you are querying and the codegen will use it instead. 

```graphql
query GetBook($id: Int!) {
   myBook: GetBook(id: $id)
}
```
