### ISSUE TITLE
Use --env-file in node 20

### ISSUE THREAD

**Issue by trixobird** [dotansimha/graphql-code-generator#9917]
### Is your feature request related to a problem? Please describe.

We do have a solution for env variables when dotenv is used https://the-guild.dev/graphql/codegen/docs/config-reference/require-field#dotenv-integration. Now that node 20 supports .env files natively we should have a similar solution for codegen without the need of dotenv.

### Describe the solution you'd like

I would like to be able to pass node parameters in CodegenConfig so I can just add `--env-file=.env`

**Comment by ardatan** [comment]
You can use `NODE_OPTIONS` environment variable to pass any Node options.

**Comment by trixobird** [comment]
Thank you for the fast answer. Tried `"NODE_OPTIONS=\"--env-file=.env\" graphql-codegen --config src/schema/codegen.ts"` and I got `node: --env-file= is not allowed in NODE_OPTIONS` which is supported by [this](https://browsee.io/blog/using-environment-variables-in-node-js-20-6-0/#:~:text=Note%3A%20You%20can't%20position,allowed%20to%20avoid%20infinite%20loops): `Note: You can't position NODE_OPTIONS="--env-file .env to your .env file. It is not allowed to avoid infinite loops.`

**Comment by ardatan** [comment]
Hmm I see. Then, if anyone knows how to pass this kind of Node options to Node based CLIs, let us know.
Because currently it seems adding these parameters is only available when calling `node` executable itself.

**Comment by trixobird** [comment]
indirectly solved with [this](https://github.com/dotansimha/graphql-code-generator/issues/9919#issuecomment-2063548975)
