### ISSUE TITLE
top level await fails codegen

### ISSUE THREAD

**Issue by trixobird** [dotansimha/graphql-code-generator#9919]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

When I add a top level await codegen fails with 
```
const a = await new Promise(() => setTimeout(() => {}, 1000)); /* v7-9bf4b0f6539225b8 */
          ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
```

### Your Example Website or App

https://github.com/trixobird/graphql-top-level-await

### Steps to Reproduce the Bug or Issue

1. pnpm i
2. pnpm codegen

### Expected behavior

As a user I expected the codegen to be completed successfully, but instead it failed with `SyntaxError: await is only valid in async functions and the top level bodies of modules`

### Platform

- OS: macOS
- NodeJS: v20.11.1
- `graphql` version: 16.8.1
- `@graphql-codegen/cli`: 5.0.2
- `graphql-codegen/client-preset`: 4.2.5
-  `graphql-codegen/typescript`: 4.0.6
-  `graphql-codegen/typescript-operations`: 4.2.0

### Codegen Config File

```
import { printSchema } from 'graphql';
import type { CodegenConfig } from '@graphql-codegen/cli';
import { schema } from './index.ts';

const config: CodegenConfig = {
  schema: printSchema(schema),
  emitLegacyCommonJSImports: false,
  generates: {
    './src/schema.graphql': {
      plugins: ['schema-ast'],
    },
  },
  config: {
    scalars: {
      Date: 'Date',
      UUID: 'string',
    },
  },
};

// eslint-disable-next-line import/no-default-export -- This is a config file
export default config;
```

**Comment by NehanPathan** [comment]
Wrap Codegen Call in an Async Function

like
(async () => {
  const a = await new Promise(() => setTimeout(() => {}, 1000)); 

  // Rest of code
})();
