### ISSUE TITLE
[plugin/add] Cannot import config type

### ISSUE THREAD

**Issue by taro-28** [dotansimha/graphql-code-generator#9986]
### Is your feature request related to a problem? Please describe.

Unlike other plugins, `@graphql-codegen/add` cannot import config type, making it difficult to write configuration type-safe.

### Describe the solution you'd like

Enable import of config types from `@graphql-codegen/add` as follows.
```typescript
import type { AddPluginConfig } from '@graphql-codegen/add'
```

**Comment by eddeee888** [comment]
Thank you for implementing this feature @taro-28 !

This is released in `@graphql-codegen/add@5.0.3`
